### ISSUE TITLE
[Bug]: I got an error " Uncaught SyntaxError: Unexpected token '<' "

### ISSUE THREAD

**Issue by morshedulmunna** [remix-run/react-router#10003]
### What version of React Router are you using?

^6.8.0

### Steps to Reproduce

This is My App.js =>
```js
import React from "react";
import { RouterProvider } from "react-router-dom";
import routes from "./routes/routes";

const App = () => {
  return (
    <>
      <RouterProvider router={routes} />
    </>
  );
};

export default App;
```

=========================================
this is My routes.js file
```js
import { createBrowserRouter } from "react-router-dom";
import Login from "../pages/Login/Login";

export const router = createBrowserRouter([
  {
    path: "/",
    element: <Login />,
  },
]);
```

==========================
This is my Main.js File
```js
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

### Expected Behavior

When I setup All routes  then my window crush and have an error 

Uncaught SyntaxError: Unexpected token '<' (at routes.js?t=1675096413746:7:14)

### Actual Behavior

Error Show  in my consol.

Uncaught SyntaxError: Unexpected token '<' (at routes.js?t=1675096413746:7:14)

**Comment by timdorr** [comment]
This isn't a React Router bug. This is something to do with your build environment.

**Comment by vevisvs** [comment]
how did you solve it? I have the same error in the console

**Comment by vevisvs** [comment]
how did you solve it?

**Comment by singhdilip1007** [comment]
@morshedulmunna  @timdorr  `Uncaught SyntaxError: Unexpected token '!' (at main.chunk.js:7783:12)` I'm getting this error message and lots of R&D I did but no success, Please suggest on it

Node version: v14.20.1
Application: .Net with React

**Comment by gonzobard777** [comment]
Same error occurred to me due to an incorrectly configured webpack dev server. That helped:
The following field value "historyApiFallback" in the webpack dev server config helped:

```
    historyApiFallback: {
      index: '/index.html',
      disableDotRule: true,
      rewrites: [
        {
          from: /\.(js|css|svg|png|jpg|json|woff|woff2|ttf)$/,
          to: function (context: any) {
            return context.parsedUrl.pathname.replace(/^\/.*\//, '/');
          },
        },
      ],
    }
```

**Comment by huyhoang189** [comment]
i think it is bug. However, you can try replace .js to .jsx. It worked to me

**Comment by group-it-ims** [comment]
> i think it is bug. However, you can try replace .js to .jsx. It worked to me

thanks workedd for me

**Comment by Mayeda-Islam** [comment]
> i think it is bug. However, you can try replace .js to .jsx. It worked to me

It's worked. This is some kind of silly mistake because I am using Vite. So every jsx having component's extension should be jsx instead of js.

**Comment by BarakBarz** [comment]
@Mayeda-Islam can you sho what you did to fix in vite?

**Comment by jesuslencina** [comment]
I am having the same error right now. Freshly created vite app, same code structure. Switching extensions from `.jsx` to `.js` and vice versa did not solve it.

I also tried switching to the `BrowserRouter` approach in `App.jsx`, but it doesn't seem to be the problem, since the browser console will spit the error as soon as it sees any `"<"` character. 

I know this is probably an issue with Vite rather than with React Router itself, but still I'd appreciate some guidance if anybody managed to fix this.

![image](https://github.com/remix-run/react-router/assets/36510164/e60acd51-17ae-468b-a1ee-37c98b8f8c6a)

**Comment by raidkarki** [comment]
didn't work for me!!!!

**Comment by joelcoxx** [comment]
also having this problem

**Comment by Dev-Ahmadubah** [comment]
> i think it is bug. However, you can try replace .js to .jsx. It worked to me

It works. Thanks man

**Comment by shaver-sid** [comment]
> I am having the same error right now. Freshly created vite app, same code structure. Switching extensions from `.jsx` to `.js` and vice versa did not solve it.
> 
> I also tried switching to the `BrowserRouter` approach in `App.jsx`, but it doesn't seem to be the problem, since the browser console will spit the error as soon as it sees any `"<"` character.
> 
> I know this is probably an issue with Vite rather than with React Router itself, but still I'd appreciate some guidance if anybody managed to fix this.
> 
> ![console error](https://github.com/remix-run/react-router/assets/36510164/a754747b-7ec8-4531-a2e8-d070df0a14d6)





https://zekehurdle53.github.io/magento-23/
