### ISSUE TITLE
[Bug]: Using redirection causes page bounce

### ISSUE THREAD

**Issue by guaijie** [remix-run/react-router#10008]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

```tsx
// Use this method to achieve a page refresh
const ReloadPage = () => {
  const { pathname } = useLocation()
  const type = useNavigationType()
  return <Navigate to={type === 'REPLACE' ? pathname : '..'} replace />
}

export const routes: RouteObject[] = [
  {
    path: '/login',
    element: <Login />
  },
  {
    path: '/',
    element: <Navigate to="/home" />
  },
  {
    element: <Layout />,
    children: [
      {
        path: '/reload',
        element: <ReloadPage />
      }
    ]
  }
]
```
I have realized page refresh, but occasionally page bounce occurs. I am not sure why this is, because react-router does not provide a good method for page refresh

### Expected Behavior

The above way to achieve page refresh without page bounce, or provide a better way to achieve page refresh

### Actual Behavior

Page bounce occurs when the page is refreshed

**Comment by timdorr** [comment]
If you need to fully reload the page, you should use `window.location.reload()`. If you need to re-render your component tree, that is left up to you to implement however you want. Updating components is a React thing and is not specific to React Router.
