### ISSUE TITLE
[Bug]: router.navigate doesn't respect 'basename'

### ISSUE THREAD

**Issue by DenJel7** [remix-run/react-router#10019]
### What version of React Router are you using?

6.4.4

### Steps to Reproduce

When i try to navigate directly from router object, it doesn't respect basename option. But it works with hooks

```js
const router = createBrowserRouter(routes, {
  basename: "/app",
});
```

```js
const navigate = useNavigate(); 

navigate('/') // correct behavior. Will navigate to '/app/'
```

```js
router.navigate('/') // incorrect behavior. Will navigate to '/'
```

### Expected Behavior

```js
router.navigate('/') //  Should navigate to '/app/'
```

### Actual Behavior

```js
router.navigate('/') // Navigate to '/'
```

**Comment by brophdawg11** [comment]
This is correct behavior currently.  For now, `basename` is a feature of `react-router-dom` so URL manipulation happens there.  You are not supposed to be navigating directly via the `router`, but if you are you will need to prepend the `basename` yourself.  Keep an eye on [this proposal](https://github.com/remix-run/react-router/discussions/9588) where we'll be moving a lot of that logic into the router and after that I think what you're trying to do would work.
