### ISSUE TITLE
[Bug]: `useMatch` do not work with optional parameters

### ISSUE THREAD

**Issue by popoleeMaster** [remix-run/react-router#10039]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

1) Setup a route using optional parameters
`:optionalParam?/account/:param/list`
2) match url with this path using `useMatch`
```
  const { pathname } = useLocation();
  const match = matchPath({ path: `:optionalParam?/account/:param/list` }, pathname);
```

### Expected Behavior

```
  const { pathname } = useLocation();
  const match = matchPath({ path: `:optionalParam?/account/:param/list` }, pathname);
```

Should match both patch `account/XXX/list` and `XXX/account/YYY/list`

### Actual Behavior

```
  const { pathname } = useLocation();
  const match = matchPath({ path: `:optionalParam?/account/:param/list` }, pathname);
```
This will never match the route and need to be changed to a non optional parameter to return any match
```
  const { pathname } = useLocation();
  const match = matchPath({ path: `:optionalParam/account/:param/list` }, pathname);
```
This require then to also make a match for the case the optionalParam is not provided resulting in 2  `matchPath` needed instead of just one

`end` option do not change the behavior.

**Comment by popoleeMaster** [comment]
Ok I got linked to a discussion https://github.com/remix-run/react-router/discussions/9862

**Comment by brophdawg11** [comment]
I'm going to close this out in favor of the discussion
