### ISSUE TITLE
[Bug]: URL polyfill required for React Router Native createMemoryRouter in v6.8

### ISSUE THREAD

**Issue by stereoplegic** [remix-run/react-router#10058]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

createMemoryRouter became usable in non-browser environments as of v6.7.0 (fixing #9796), and worked fine in React Native apps; however, upon upgrading to v6.8.0 its use of URL.search now requires [react-native-url-polyfill](https://npmjs.com/package/react-native-url-polyfill) for `<Link />` components to be functional.

As with the issue prior to v6.6.3, I'd imagine this is actually coming from `packages/router` and/or `packages/react-router`, esp. since both `createMemoryRouter` and `Link` are just re-exported from `packages/react-router`.

### Expected Behavior

Error-free routing when clicking on a `<Link to="/some/path" />` component.

### Actual Behavior

Yellowbox warning, no route traversal when clicking `<Link />` component.

`WARN  Possible Unhandled Promise Rejection (id: 0):
Error: URL.search is not implemented`

As mentioned in the "Steps to Reproduce," a workaround is to use react-native-url-polyfill:

```js
// App.native.jsx
import "react-native-url-polyfill/auto"

// or conditional import with react-native Platform
Platform.OS !== "web" && import("react-native-url-polyfill/auto")
```

Obviously not ideal, but gets me moving for now.

**Comment by brophdawg11** [comment]
@stereoplegic Do you have a stack trace handy by any chance?  I am assuming this is coming from [this line](https://github.com/remix-run/react-router/blob/react-router%406.11.0/packages/router/router.ts#L3271) but it would be helpful if we could confirm that.

We do currently polyfill `URLSearchParams` in `react-router-native` so maybe we just need to add a spec-compliant `URL` polyfill as well.

**Comment by stereoplegic** [comment]
Unfortunately, I do not. Hoping to get back to some RR Native work this week. I'll try the latest without react-native-url-polyfill when I get a chance and let you know.

**Comment by brophdawg11** [comment]
🙌 Ok, thank you!  If you are able to reproduce, you might even try fixing it at the source by adding the polyfill alongside our `URLSearchParams` polyfill and see if that does indeed resolve the issue:

https://github.com/remix-run/react-router/blob/main/packages/react-router-native/index.tsx#L15
