### ISSUE TITLE
[Bug]: loaders with redirect work in wild, but not in tests

### ISSUE THREAD

**Issue by TinaTiel** [remix-run/react-router#10062]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

I have an application where I have a redirect behavior, for example when they login they should be redirected to a login page if not logged in. The Root app had a level-1 header, and it renders the page contents inside an Outlet.

I've created a contrived example that always performs the redirect, so that the Redirected page should be what the user sees when opening the app.

If I run this in the wild, in my browser, it works exactly as expected and I see the root page and the redirected page outlet. 
![image](https://user-images.githubusercontent.com/51816935/217251909-cb9b8aec-0124-4c25-9974-bb97d80eb6e7.png)

However, in tests it doesn't render the redirected page as expected; it is showing the (should be) ignored page.

```
 FAIL  src/tests/navigation.test.js
  × when rendered, the redirect page is shown instead of the ignored page (1143 ms)

  ● when rendered, the redirect page is shown instead of the ignored page

    Unable to find role="heading" and name "Redirected Page"

    Ignored nodes: comments, script, style
    <body>
      <div>
        <main>
          <h1>
            Root Page
          </h1>
          <section>
            <h2>
              Ignored Page
            </h2>
          </section>
        </main>
      </div>
    </body>

      14 |
      15 |     // We expect the redirect page to be rendered at the outlet
    > 16 |     const redirectedPage = await screen.findByRole('heading', {name: 'Redirected Page'});
         |                                         ^
      17 |     expect(redirectedPage).toBeInTheDocument();
      18 |
      19 |     // We don't expect the ignored page to be rendered at the outlet

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:166:27)
      at findByRole (node_modules/@testing-library/dom/dist/query-helpers.js:86:33)
      at Object.<anonymous> (src/tests/navigation.test.js:16:41)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.936 s, estimated 3 s
```

See: 
https://github.com/TinaTiel/react-router-v6-memory-router-issue

### Expected Behavior

I should see the root page header and the Redirected Page header (via the outlet) in both my browser and my tests.

### Actual Behavior

I only see the root page header and the Redirected Page header (via the outlet) in my browser, but in my tests I don't see the redirected page as expected.

**Comment by TinaTiel** [comment]
(sorry about the confusion of changing things up...I also had an issue with the page not rendering at all and realized that was in-part caused by the query I was using)

**Comment by brophdawg11** [comment]
This is due to create-react-app using a non-spec-compliant polyfill for `fetch`.  There's a linked issue in there in the CRA repo to see if they'd switch to a spec-compliant version.

Closing as a dup of https://github.com/remix-run/react-router/issues/9722
