### ISSUE TITLE
[Bug]: When using unstable_useBlocker, the console logs "A router only supports one blocker at a time" 

### ISSUE THREAD

**Issue by Bestwebdesign** [remix-run/react-router#10073]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

1. Open https://stackblitz.com/edit/github-yrxhzt?file=package.json
(basically it's the same example found here https://github.com/remix-run/react-router/tree/main/examples/navigation-blocking but using version 6.8.1)
2. Open console
3. Click on the link "Three (Form with blocker)"
4. Enter some text in the input
5. Click on another link like "Index", "One", "Two", ...
6. Console will log "A router only supports one blocker at a time"

### Expected Behavior

No warnings in the console.

### Actual Behavior

Console logs a warning "A router only supports one blocker at a time".

**Comment by Bestwebdesign** [comment]
@timdorr The example I provided uses a single blocker, not multiple. It works fine with 6.8.0, the warning is logged only when using 6.8.1.

**Comment by popoleeMaster** [comment]
Same here, we use a single blocker on a page, and we are getting this warning in 6.8.1 (not appearing in 6.8.0) So I wonder if the lib change the way it detect it and there is an issue in our app, of the warning should not be triggered.

**Comment by timdorr** [comment]
Oh geez, I totally mis-read your issue. My apologies for that. This looks legit, so opening it back up...

**Comment by enoh-barbu** [comment]
I've been able to mitigate this issue by using a top level blocker in RootApp and using Context API

**Comment by sjdemartini** [comment]
This seems potentially related to (or the same as) https://github.com/remix-run/react-router/issues/10144. If I use the linked stackblitz here but remove `StrictMode` from `main.tsx`, I don't see the buggy "A router only supports one blocker at a time" logging when following the repro steps. 

It looks like `unstable_useBlocker` does not properly handle StrictMode since it seemingly isn't cleaning up its blockers properly (as described here https://beta.reactjs.org/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development). This makes it difficult to ensure dev and prod consistency, since blocker/routing behavior won't match in certain situations, so ideally could be resolved. And presumably the issue in StrictMode could be indicative of a more fundamental bug as well.

**Comment by moshfiqrony** [comment]
> This seems potentially related to (or the same as) #10144. If I use the linked stackblitz here but remove `StrictMode` from `main.tsx`, I don't see the buggy "A router only supports one blocker at a time" logging when following the repro steps.
> 
> It looks like `unstable_useBlocker` does not properly handle StrictMode since it seemingly isn't cleaning up its blockers properly (as described here https://beta.reactjs.org/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development). This makes it difficult to ensure dev and prod consistency, since blocker/routing behavior won't match in certain situations, so ideally could be resolved. And presumably the issue in StrictMode could be indicative of a more fundamental bug as well.

This was true for me

**Comment by adams-family** [comment]
+1

**Comment by brophdawg11** [comment]
This will be available in `6.14.0` - `6.13.0` was used to add a future flag for `React.startTransition`

**Comment by moshfiqrony** [comment]
Thanks for the update @brophdawg11

**Comment by enoh-barbu** [comment]
After updating to lastest version, I get the following error:

`18react-dom.development.js:67 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at Layout (http://localhost:3000/static/js/bundle.js:61513:63)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:308343:5)
    at RenderErrorBoundary (http://localhost:3000/static/js/bundle.js:308290:5)
    at DataRoutes (http://localhost:3000/static/js/bundle.js:308789:5)
    at Router (http://localhost:3000/static/js/bundle.js:308902:15)
    at RouterProvider (http://localhost:3000/static/js/bundle.js:308729:5)
    at AuthenticatedApp (http://localhost:3000/static/js/bundle.js:634:5)
    at AppRoot (http://localhost:3000/static/js/bundle.js:478:88)
    at AuthenticatorProvider (http://localhost:3000/static/js/bundle.js:342713:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:152273:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:152652:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:150659:14)
    at Provider (http://localhost:3000/static/js/bundle.js:304184:20)`

No more details, so this error it's getting counted every ~second

**Comment by bartelemi** [comment]
@enoh-barbu I reckon it is worth opening another issue with details, especially if you have a self-contained example where the error can be reproduced.

We have the same problem after upgrading to 6.14.0 and we had to downgrade back to 6.8.0.

**Comment by enoh-barbu** [comment]
@bartelemi so if you also have the same problem, should I still open a new issue?

**Comment by bartelemi** [comment]
I think so

**Comment by brophdawg11** [comment]
This is tracked in https://github.com/remix-run/remix/issues/6704 but right now you should wrap your blocker function in a `useCallback` so you are not creating a new function identity on every render.

**Comment by kubmir** [comment]
This is still happening to me. What's worse 6.13.0 works well regarding blocking and displaying UI prompt. However, update to 6.14 / 6.15 (without any code change) causes this warning and blocker is probably not cleared which causes navigation not to work later.

It seems like router is not update / re-rendered and still takes the blocker which should be already removed.

**Comment by vasile-encord** [comment]
@kubmir same issue, getting confirm window twice, and after leaving the page I can see confirm error for every single page change, and I don't have useBlocker there.
If you know any way around to fix it please share.

**Comment by Snouzy** [comment]
same issue with 6.22.0

downgrade to 6.8.0 works well.

I am with viteJS

**Comment by kubmir** [comment]
Hello @vasile-encord did you find any solution ? We had to update to 6.22.0 and it is still not working. It is broken for any version newer than 6.13.0 for me. It looks like redirect work for a second but than the original page is displayed and the warning is triggered.
