### ISSUE TITLE
[Bug]: Redirect does not work with deferred loader

### ISSUE THREAD

**Issue by mnoop** [remix-run/react-router#10088]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

If I return a redirect from a deferred loader, that is used with an Await, the redirect is ignored and is returned as the data used by the Await.

I tried to create a small example to demonstrate this:

```jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Await, defer, useLoaderData, redirect, createBrowserRouter, RouterProvider } from "react-router-dom";

function userLoader() {
  async function getUser() {
    return redirect("/");
  }

  return defer({ user: getUser() });
}

function User() {
  const data = useLoaderData();

  return (
    <React.Suspense fallback={"Loading..."}>
      <Await
        resolve={data.user}
        errorElement={"Error occured"}
      >
        {(resolvedData) => {
          
          console.log(resolvedData);

          return <div>User: {resolvedData.user}</div>
        }}
      </Await>
    </React.Suspense>
  );
}

function Home() {
  return <div>Home</div>;
}

const router = createBrowserRouter([
  {
    path: "/",
    element: <Home />,
  },
  {
    path: "/user",
    element: <User />,
    loader: userLoader,
  }
]);

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
```

### Expected Behavior

If I return a redirect from a deferred loader, the redirect occurs. 

In my specific example, I expect /user to redirect to /, which might be useful if /user was a page that required authentication and I wanted to redirect someone unauthenticated to a different page if the loader encountered a 401 error.

### Actual Behavior

If I return a redirect from a deferred loader, the redirect is ignored and instead used as if it was data returned by the loader.

In my specific example, navigating to /user does not redirect, instead it stays on the /user page, but without the user value, and the console logs the Response object.

**Comment by domosedov** [comment]
it's not a bug, it's bad code

getUser function should return user or error

try something like this
```ts
function userLoader(ctx) {
  const isAuth = await checkAuth(ctx)
  
  if (!isAuth) {
    return redirect("/");
  }
  
  async function getUser() {
    return ...
  }

  return defer({ user: getUser() });
}
```

**Comment by jrmyio** [comment]
> ```ts
>   const isAuth = await checkAuth(ctx)
> ```

In this example your `checkAuth` function is not defered. What if you want to defer that value?

**Comment by jdelglise** [comment]
I don't have access to my code right now, but I had a similar issue and I think I solved it by using https://reactrouter.com/en/main/hooks/use-async-value

**Comment by timdorr** [comment]
This is essentially answered by this FAQ question: https://reactrouter.com/en/main/guides/deferred#why-dont-response-objects-returned-by-the-loader-work-anymore

The main point being that `defer` removes `Response` objects from the loader process, as they don't really make sense in an async context. [Since `redirect` is just a wrapper](https://github.com/remix-run/react-router/blob/0f86bb31856ec19dd45c5b9d1de14df97dc2353b/packages/router/utils.ts#L1355-L1370) around creating a `Response` object, it also makes sense that it won't work.

**Comment by gxxcastillo** [comment]
> In this example your checkAuth function is not defered. What if you want to defer that value?

@jrmyio, If you want to defer the checkAuth value you would not do an await and instead call .then() and subsequently chain the rest of your async requests:

```
const userRequest = checkAuth(ctx).then((isAuth) => {
  ...
}).then(...)

defer({ user: userRequest })
```

**Comment by BereketZz** [comment]
what is wrong with this code? it is not redirecting 

export async function loader(){
  const isLoged= false

    if(!isLoged){
      return redirect("login")
     
    }
   return null

}

**Comment by ibkodify** [comment]
Need help to fix this error!!!

![Image](https://github.com/user-attachments/assets/2eb9d038-14dc-4c7f-a3de-3e700c048ea3)
