### ISSUE TITLE
[Bug]: remove engines field from package.json?

### ISSUE THREAD

**Issue by saintwinkle** [remix-run/react-router#10083]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

Hello, I'm still using `Node.js v12.x` for some reason. 😂 When installing `react-router` to my project, I've got some error messages:

```bash
yarn add react-router-dom
...
> The engine "node" is incompatible with this module. Expected version ">=14". Got "12.16.1"
```

As Ryan said in PR #8951, `react-router` doesn't care about Node.js version at all. Developers who install `react-router` don't need a specific version of Node.js. Why it's been merged?

Maybe revert the change? Thanks for reading!

### Expected Behavior

Installation succeeded

### Actual Behavior

Installation failed

**Comment by timdorr** [comment]
I believe you can add a `--ignore-engines` flag to that command. You can definitely add it to `yarn install`, so perhaps add it by hand and then install with that flag. 

Regardless, we only technically support Node 14.17 and above. Node 12 is now both EOL and not receiving security updates. Node 14's time is almost up too. There's generally a grace period in the community, but you should figure out how to get your version updated regularly so you can keep up with updates and still receive security fixes.

**Comment by saintwinkle** [comment]
> I believe you can add a `--ignore-engines` flag to that command. You can definitely add it to `yarn install`, so perhaps add it by hand and then install with that flag.
> 
> Regardless, we only technically support Node 14.17 and above. Node 12 is now both EOL and not receiving security updates. Node 14's time is almost up too. There's generally a grace period in the community, but you should figure out how to get your version updated regularly so you can keep up with updates and still receive security fixes.

Thanks for relay. Just thought if we could install without `--ignore-engines` flag so I created the issue haha. Anyway, I will gradually update the Node version and dependencies in the near future, thanks again.
