### ISSUE TITLE
[Bug]: child components recall constructor when router component re-render

### ISSUE THREAD

**Issue by sadeghipour** [remix-run/react-router#10084]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

 - define Routes and add some Route into it
 - add console.log into component that you refer to Route as element
 - by useState or in componentDidMount run a function in order to forceUpdate or call api in order to update some value in reducer
 -  in console (or network if you call api) you could find duplicated logs or calls.
 

### Expected Behavior

When we define routes we expect that constructor calls once. (what as before versions do)

### Actual Behavior

child components that referred as element in Route recall constructor when main router component re-rendered.

**Comment by timdorr** [comment]
I'm not understanding what the issue is here. Can you provide an example on Stackblitz or Codesandbox?

**Comment by sadeghipour** [comment]
Sorry, I think that StrictMode causing the issue. I just removed StrictMode from app container and now fixed.
