### ISSUE TITLE
[Bug]: React router not catching the route changes done by other micro frontends

### ISSUE THREAD

**Issue by yashug** [remix-run/react-router#10089]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

I have multiple micro frontends running concurrently. Recently, I integrated a new micro app using react-router v6, while the rest of the micro frontends are using react-router v5. The micro frontends using v5 are functioning properly, but the v6 micro frontend is unable to detect changes in routes made by other micro frontends. As a result, it only works correctly if I reload the page.

### Expected Behavior

The route changes should be cached by react-router v6 micro frontend and thus loading the respected view without reload

### Actual Behavior

Getting an error route saying no route match because it's pointing to the initial load URL, and ignoring the route changes done by other apps, basically, I feel it's not catching the browser history. 

it only works within the v6 micro app, if i reload

**Comment by timdorr** [comment]
React Router v6 only looks at changes to history that it itself has made. We no longer observe outside changes because we wouldn't be able to parse the routes they are for anyways, nor could we guarantee our rendering of `Link`s would be correct.

**Comment by yashug** [comment]
@timdorr it worked fine for me when I replaced createBrowserRouter with <BrowserRouter /> as it uses the browser's built-in history stack. createBrowserRouter is unable to follow the browsers history stack.

**Comment by yashug** [comment]
@timdorr may be in the future its better to provide optional param for this in createBrowserRouter function

**Comment by kiliman** [comment]
Seems like if you want to integrate a third-party package into RR's routing, it should be _that_ package that does the integration, not the other way around.

Does your package provide a hook for when it does a navigation? If so, then you can call RR's `navigate()` as needed. I'm assuming that these are still navigating to a RR route.

**Comment by alexkomarchev** [comment]
any solution?
