### ISSUE TITLE
[Bug]: Concurrent `navigate` and `setSearchParams` not working

### ISSUE THREAD

**Issue by bgeffrault** [remix-run/react-router#10103]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

Hello,
I have a page with some tabs and some filters both handling the nav on their own.
On first render the tabs will apply the default routing with navigate: from "/todo" to "/todo/me"
Same for the filters, it will apply the locally stored filters to the nav: from "" to "?user=test"

```
import * as React from 'react';
import {
  Link,
  Route,
  Routes,
  useLocation,
  useNavigate,
  useSearchParams,
} from 'react-router-dom';

export default function App() {
  const location = useLocation();

  return (
    <div>
      <div>Pathname: {location.pathname}</div>
      <div>Search: {location.search}</div>
      <Link to="/">Trigger Bug</Link>
      <Routes>
        <Route path="/" element={<TriggerBug />} />
        <Route path="/TabsWithFilters" element={<TabsWithFilters />} />
        <Route path="/Tab" element={<div>I'm never render</div>} />
      </Routes>
    </div>
  );
}

function TriggerBug() {
  const navigate = useNavigate();
  React.useEffect(() => {
    navigate('TabsWithFilters');
  }, []);
  return <div></div>;
}
function TabsWithFilters() {
  const navigate = useNavigate();

  return (
    <div>
      <TabRouting />
      <SearchFilters />
    </div>
  );
}

function SearchFilters() {
  let [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  React.useEffect(() => {
    console.log('set search params search');
    setSearchParams({ user: 'test' });
  }, []);
  return <div>Component for tabs</div>;
}
function TabRouting() {
  const navigate = useNavigate();

  React.useEffect(() => {
    console.log('navigate to /tab');
    navigate('/Tab');
  }, []);
  return <div>Component for filters</div>;
}

```
I understand that if you navigate on two different routes the nav will take the last value.
But in my case that it should be decorrelated since I update two different parts of the route (pathname & search)

[Demo](https://stackblitz.com/edit/github-jtcuwn?file=src%2FApp.tsx,package.json)

Instead of `setSearchParams` I tried with navigate but same result.
I thought it could be a good idea to have something like the `setSate` hook:`navigate((nav) => ({...nav, search: "user=test"})` but idk the possibilities

### Expected Behavior

The routing end like this "/todo/me?user=test".

### Actual Behavior

The routing end like this "/todo?user=test" instead of "/todo/me?user=test".

**Comment by timdorr** [comment]
`setSearchParams` uses `navigate` under the hood, so your navigations are overwriting each other. You should just `navigate` with the `search` property set in one single call to get around this. You could also `replace: true` the `navigate` for your search filter updates to have them update as changed and not add to the history stack.
