### ISSUE TITLE
[Bug]: `navigate()` stops working after `<RouterProvider />` re-render

### ISSUE THREAD

**Issue by armiiis** [remix-run/react-router#10102]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

Issue reproduction in [codesandobx](https://codesandbox.io/s/floral-lake-ogpzmx).

After migrating App I'm working with to data router (`createBrowserRouter`) I was facing issues where `navigate()` calls would not update page view, even though URL is updated.

After investigating and debugging I've found out that the issue was with `<RouterProvider router={router} />` placement in the App tree. In case there is any state update to the parent component of `RouterProvider`, the navigation was not working as expected in some corner cases. I've fixed this by moving `RouterProvider` upper in the App tree so it wouldn't be re-rendered when state changes. I'm not exactly sure if this is a bug or it was mentioned somewhere in the documentation that `RouterProvider` bust be placed as a root component in the App.

### Expected Behavior

Open [codesandobx](https://codesandbox.io/s/floral-lake-ogpzmx)
1. Go to `/profile` URL.
2. After some time `navigate('/settings')` is called.
3. URL is updated and settings page is visible.

### Actual Behavior

Open [codesandobx](https://codesandbox.io/s/floral-lake-ogpzmx)
1. Go to `/profile` URL.
2. After some time `navigate('/settings')` is called.
3. URL is updated but navigation didn't happen. Profile page is still visible.

**Comment by timdorr** [comment]
You shouldn't define your routes inside of a component. They should live at the top level so that your `router` instance is stable.

**Comment by armiiis** [comment]
@timdorr Thanks for your reply. I think it would be nice to have this mentioned somewhere in the documentation. If you think this is not required, then I could provide my arguments why I think it would be a nice addition.

**Comment by jitendra-gosavi** [comment]
@timdorr would it be possible to share a working example of the above? I am facing the same issue but am not able to fix it. Thanks in advance.

**Comment by armiiis** [comment]
@jitendra-gosavi Here is [working example](https://codesandbox.io/s/kind-feather-2t4eyh?file=/src/index.js) of the above.

As it was mentioned above `router` instance should be stable. This can be fixed by removing `const { data } = useContext(Context);` from `Root` component. `useContext` should be moved to required children components.
