### ISSUE TITLE
[Bug]: fetcher.load doesn't update useLoaderData result on an active route

### ISSUE THREAD

**Issue by iMoses** [remix-run/react-router#10109]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

Create a route with a loader that 

```
createBrowserRouter([
  {
    path: "/page",
    element: <MyPage />,
    loader: async () => {
      console.log("loader");
      return { data: Math.random() };
    },
  },
]);

const MyPage = () => {
  const fetcher = useFetcher();
  const data = useLoaderData();
  console.log(data);
  return (
    <span onClick={() => fetcher.load(window.location.pathname)}>TEST</span>
  );
};
```
Click `TEST` and see that "loader" appears in the console, the component is rerendering but the `data` object remains the same.

### Expected Behavior

Expected `useLoaderData` response to change when the loader runs again.

### Actual Behavior

`useLoaderData` response doesn't change, making it impossible to refetch the data without navigating elsewhere.

**Comment by iMoses** [comment]
@timdorr https://codesandbox.io/s/reverent-lucy-29ldg3

**Comment by timdorr** [comment]
Thanks for this. There is a misunderstanding of the point of `useFetcher` here. This is to get a new instance of the loader, separate from the one used by the router. The functions and properties provided by `fetcher` are separate from the router's lifecycle. As the docs say:
> Many interactions with the server aren't navigation events. This hook lets you plug your UI into your actions and loaders without navigating.
This means loading with the fetcher won't trigger changes to the UI state, which is by design.

**Comment by iMoses** [comment]
@timdorr So I'm clearly missing something. How can I refresh the loader data after an external mutation on the same page?

I was trying to follow the example from the tutorial without any luck

https://reactrouter.com/en/main/start/tutorial#mutations-without-navigation

**Comment by kiliman** [comment]
You access the data from fetchers via `fetcher.data`, not `useLoaderData()` 

They also participate in revalidation after mutations.

**Comment by oleksandr-danylchenko** [comment]
Am I getting it right that I should combine the data from the`useFetcher` with the one from the `useLoaderData` like this?
```tsx
{(fetcher.data?.contacts || contacts).length ? (
	<ul>
		{(fetcher.data?.contacts || contacts).map((contact) => (
			<li key={contact.id}>...</li>
		))}
	</ul>
) : (
	<p>
		<i>No contacts</i>
	</p>
)}
```

Doesn't look too great TBH 🤷🏻‍♂️

**Comment by MattyBalaam** [comment]
I would merge: 

`const contacts = fetcher.data?.contacts || loaderData.contacts`
