### ISSUE TITLE
[Bug]: Scroll Restoration doesn't play nice with a strict Content Security Policy

### ISSUE THREAD

**Issue by meza** [remix-run/react-router#10136]
### What version of React Router are you using?

Using through @remix-run/react@1.13.0

### Steps to Reproduce

Set your CSP to:

```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self';">
```

Use a site with `<ScrollRestoration/>`

Check the console for errors.

### Expected Behavior

React itself has a great workaround for this, it's detailed here: https://drag13.io/posts/react-inline-runtimer-chunk/index.html

I would expect this module to respect the `INLINE_RUNTIME_CHUNK=false` environment variable - or something similar.

### Actual Behavior

The issue is that the `dangerouslySetInnerHTML` on a `<script>` will violate a good CSP.

**Comment by timdorr** [comment]
`dangerouslySetInnerHTML` is only called by `StaticRouter`, which is only used server-side and doesn't apply here. [`INLINE_RUNTIME_CHUNK` is a Create React App feature](https://create-react-app.dev/docs/advanced-configuration/), not something React itself or this library is even aware of. 

Can you provide a reproduction of this on Codesandbox or StackBlitz? That might better clear up what is happening here.

**Comment by meza** [comment]
I think this would explain the issue more: https://content-security-policy.com/unsafe-inline/

The problem isn't with the `dangerouslySetInnerHTML` per se, it's with the inline scripts. `<script>this is inline</script>` which get blocked when proper security standards are in place.

I'll see if I can get this in an example shortly

**Comment by timdorr** [comment]
That has nothing to do with either React Router or `ScrollRestoration`. I need an example that shows a bug in the code in this repo.
