### ISSUE TITLE
[Bug]: Parent `errorElement` unexpected waits for child `loader`s

### ISSUE THREAD

**Issue by SevenOutman** [remix-run/react-router#10131]
### What version of React Router are you using?

`react-router-dom@6.8.0`

### Steps to Reproduce

I have these routes setup where a parent route and a child route has their own `loader`s and `errorElement`s:

```js
const routes = [
  {
    path: 'parent',
    loader: parentLoader,
    errorElement: <ParentErrorElement />,
    element: <Parent />, // renders <Outlet />
    children: [
      {
        path: 'child',
        loader: childLoader,
        errorElement: <ChildErrorElement />,
        element: <Child />
      }
    ]
  }
]
```

The problem arises when **I visit `/parent/child` and `parentLoader` fails fast and `childLoader` hangs**

### Expected Behavior

The `<ParentErrorElement />` should be rendered as soon as the `parentLoader` fails

### Actual Behavior

The UI hangs (rendering router's `fallbackElement`) until `childLoader` resolves, then `<ParentErrorElement />` shows.

**Comment by brophdawg11** [comment]
When running loaders in parallel, we can't short-circuit just because we see one error.  What if another loader returns a `redirect`?  That would take precedence and potentially land the user on a different (but successfully rendered) page.

**Comment by SevenOutman** [comment]
> What if another loader returns a redirect? That would take precedence and potentially land the user on a different (but successfully rendered) page.

Hmm that makes sense - but not as much in this parent-child scenario IMO.

**Comment by brophdawg11** [comment]
Children redirects take precedence, so the same logic applies and we can't short circuit if we see a parent redirect.  This is because children routes are more "targeted" to the route/data in question.

**Comment by SevenOutman** [comment]
> This is because children routes are more "targeted" to the route/data in question.

I don't quite get it why children redirect takes precedence here. To my understanding, if parent redirects, it mean that it decides none of its children is going be matched, thus any children actions - loader/render - should be aborted immediately.

**Comment by brophdawg11** [comment]
Routes are already matched by the time loaders run, so the parent loader isn't deciding "don't match my children" so much as it's deciding that a given URL can't be processed due to data concerns discovered in the loader.  Child loaders know more about the data in question and can provide a more accurate redirect (i.e., the slug in `/product/:slug` has been renamed to a new slug) hence why they take precedence.

It sounds like you want a way to prevent children loader from running at all, which is what [middleware](https://github.com/remix-run/react-router/discussions/9564) will handle when it's added.

**Comment by SevenOutman** [comment]
> Child loaders know more about the data in question and can provide a more accurate redirect (i.e., the slug in `/product/:slug` has been renamed to a new slug) hence why they take precedence.

I don't agree that child loaders always knows better about what to do than the parent, because the very `loader` should know the best about what data its related page wants.

To my understanding, for a real-world use case like this one:

- **Parent route:** `/projects/:id`
- **Child route:** `/projects/:id/tasks`

The parent page may contain several data fetches - e.g. the project detail as main content of the page (subscribed in various components with useQuery-ish approach), ads on the sidebar, recommendations on another sidebar, etc. 
When `GET /projects/:id` returns 404 status code, I want my app to display a 404 error page, while other fetch failures should only result in partial errors in the block where it's used.
Even when I'm visiting the child page `/projects/:id/tasks`, if `GET /projects/:id` fails, the parent route should display the error right away, and the child loader - `GET /projects/:id/tasks` - immediately becomes meaningless.
I didn't find a good pattern for reasonably distinguishing this `GET /projects/:id` from other fetches, until `loader` comes out.

I would like to refer to this as "what the *primary data* is for the page"(distinguished from other minor data) - isn't that what React Router just trying to solve with the introduction of `loader`?

> It sounds like you want a way to prevent children loader from running at all, which is what [middleware](https://github.com/remix-run/react-router/discussions/9564) will handle when it's added.

Looks like what I want. It's bit like v3 routing guards coming back :P - but this time with a separated concern of data loading and rendering, which is good.

I'll keep an eye on the RFC, thanks!
