### ISSUE TITLE
[Bug]: v6.5+ supporting optional parameters in route paths, but useMatch doesn't

### ISSUE THREAD

**Issue by thediveo** [remix-run/react-router#10148]
### What version of React Router are you using?

6.8.2

### Steps to Reproduce

```tsx
const App = () => {

    const match = useMatch('/w/:slug?')

    return
                <Routes>
                    <Route path="/w/:slug" element={<DetailsView />} />
                    <Route path="/w" element={<AllView />} />
                </Routes>
}
```

### Expected Behavior

`useMatch()` returns a non-null match for paths like `/w` and `/w/foo`.

### Actual Behavior

`useMatch()` always returns null, regardless of path, due to the presence of the optional path element `/:slug?`.

**Comment by timdorr** [comment]
Duplicate of #9862
