### ISSUE TITLE
[Bug]: once an error is captured by errorboundary, router doesn't work anymore

### ISSUE THREAD

**Issue by cityvoice** [remix-run/react-router#10157]
### What version of React Router are you using?

v6.8.1

### Steps to Reproduce

my component is imported dynamically by lazy, and I use ErrorBoundary to catch javascript errors, but now if some error is throwed, the router stops responsing to any navigate action anymore unless using location.replace or location.href.

here is the demo: [click here](https://stackblitz.com/edit/github-yphzes-rfnm7m?file=src/layout.tsx)

I have found the resolvertion to 

### Expected Behavior

the navigate can works normally whether some errors have happend

### Actual Behavior

the navigate doesn't work anymore once some errors have happend

**Comment by Tchilo** [comment]
Hello, @cityvoice facing the same error here.
Did you manage to fix it?
