### ISSUE TITLE
[Docs]: Tutorial

### ISSUE THREAD

**Issue by mjoycemilburn** [remix-run/react-router#10167]
### Describe what's incorrect/missing in the documentation

I really think you need to "road test" the new tutorial on a React-router novice. The previous version at https://reactrouter.com/en/6.8.2/docs/en/v6/getting-started/tutorial was pretty fierce (and how about a redirect rather than a 404 here), but this new version is just something else.

The use of vite will scare most novices and needs to be explained much more clearly. Beyond that, the setup for the demo project files could surely be made easier - the whole thing has taken me a couple of hours. and I thought I knew (vaguely) what I was doing!

**Comment by timdorr** [comment]
This is definitely a subjective opinion. I understand if it didn't work well for you, but we've found it works best for most folks. If you have specific suggestions for improvements, we can take action, but this isn't really an actionable issue.

**Comment by mjoycemilburn** [comment]
Fair enough Tim. tutorials are really hard to write and I know you'll never
satisfy everyone.

But if you dig out the previous incarnation of the router tutorial I think
you'll see that it was much more welcoming to beginners. I remember feeling
extremely grateful for it myself last year! I think that if I'd been
trying to use the current version I'd just have given up.

Specifically, I think the use of vite is an immediate turnoff. Newcomers
wanting to add routes to the simple webapps they've created will have
graduated from create-react-app. They just want to learn about routes, not
a new scaffolding tool!

Further distractions are the references to "touch" and the weird
instruction to "Set <Root> as the root route's element" on root.jsx with a
stack of code that starts with  "/* existing imports */". The latter needs
to be much more prescriptive. I bet at least 50% of newcomers would just
overwrite the *whole *of root.jsx with this lot and then panic at the
resultant scary error messages.

I hope you'll take my comments in the spirit in which they're intended -
which is to wish you every success with the new tutorial.

With best wishes, MartinJ
