### ISSUE TITLE
[Bug]: It is impossible to pass custom <Route/> component to <Routes/> container.

### ISSUE THREAD

**Issue by tugarinzmey** [remix-run/react-router#10170]
### What version of React Router are you using?

18.2.0

### Steps to Reproduce

I am creating HOC. And my HOC returns `<Route/>`. I want to pass this HOC into `<Routes/>` container.
```

import './App.css';
import Home from './Home/Home';
import Login from './Login/Login';
import Logout from './Logout/Logout';
import { useSelector } from 'react-redux';
import {
  BrowserRouter,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";

const PrivateRoute = ({ element: Component, ...rest }) => {
  const { isLoggedIn } = useSelector((state) => state.rootReducer.authSlice);
  return (
    <Route {...rest} element={(props) => isLoggedIn ?
      <Component {...props} />
      : <Navigate to={"/login"} />
    } />
  )
}

const App = () => {

  return (
    <BrowserRouter>
      <Routes>
        <Route path='/login' element={<Login />} />
        <Route path='/logout' element={<Logout />} />
        <PrivateRoute element={<Home />} path={"/"} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;

```

### Expected Behavior

This solution would work with old versions of the react-router, where we had `<Switch/>` instead of `<Routes/>`. My idea is to wrap <Route/> component with any custom HOC. 

### Actual Behavior

The console shows me this error.
![image](https://user-images.githubusercontent.com/71755647/223716602-c29f661f-b080-4de0-979e-ced4ca2769a1.png)

**Comment by tlthiem** [comment]
not supported anymore
