### ISSUE TITLE
[Docs]: On the tutorial, the function `getContacts()` is never defined and is confusing

### ISSUE THREAD

**Issue by TheMassapequaTutor** [remix-run/react-router#10173]
### Describe what's incorrect/missing in the documentation

The first mention of the function `getContacts()` is mentioned [here](https://reactrouter.com/en/main/start/tutorial#:~:text=Export%20a%20loader%20from%20root.jsx). This is used in the loader function and is confusing because I don't quite understand the loader function.

**Comment by timdorr** [comment]
It's provided in the linked gist: https://gist.githubusercontent.com/ryanflorence/1e7f5d3344c0db4a8394292c157cd305/raw/f7ff21e9ae7ffd55bfaaaf320e09c6a08a8a6611/contacts.js
