### ISSUE TITLE
[Bug]: App.tsx RequireAuth Navigate

### ISSUE THREAD

**Issue by rwb196884** [remix-run/react-router#10184]
### What version of React Router are you using?

current

### Steps to Reproduce

[[react-router](https://github.com/remix-run/react-router/tree/dev)/[examples](https://github.com/remix-run/react-router/tree/dev/examples)/[auth](https://github.com/remix-run/react-router/tree/dev/examples/auth)/[src](https://github.com/remix-run/react-router/tree/dev/examples/auth/src)/App.tsx](https://github.com/remix-run/react-router/blob/dev/examples/auth/src/App.tsx)

line 139
```
return <Navigate to="/login" state={{ from: location }} replace />;
```
Doesn't even compile.
Error	TS2749	(TS) 'Navigate' refers to a value, but is being used as a type here. Did you mean 'typeof Navigate'?	

As far as I can tell you need to do this instead.
```
    if (!auth.isAuthenticated) {
        let navigateOptions: NavigateOptions = {
            state: { from: location },
            replace: true
        };

    // Redirect them to the login page, but save the current location they were
    // trying to go to when they were redirected. This allows us to send them
    // along to that page after they login, which is a nicer user experience
    // than dropping them off on the home page.
        return navigate("/", navigateOptions);
```

### Expected Behavior

It works.

### Actual Behavior

It doesn't even compile

**Comment by timdorr** [comment]
It seems like something was typed incorrectly, as that example works correctly directly from the repo here over on StackBlitz: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src%2FApp.tsx
