### ISSUE TITLE
[Docs]: The docs say `<Link to="..">` works like `cd ..` — it does not

### ISSUE THREAD

**Issue by srmagura** [remix-run/react-router#10186]
### Describe what's incorrect/missing in the documentation

There is a disagreement between the documentation and the actual behavior of React Router. I _think_ this is a documentation issue rather than a bug, but I'm not sure.

https://reactrouter.com/en/6.9.0/components/link says:

> A relative `<Link to>` value (that does not begin with /) resolves relative to the parent route, which means that it builds upon the URL path that was matched by the route that rendered that `<Link>`. It may contain .. to link to routes further up the hierarchy. In these cases, .. works exactly like the command-line cd function; each .. removes one segment of the parent path.

This is not accurate. In reality, `<Link to="..">` may remove multiple path segments, as shown by [this CodeSandbox](https://codesandbox.io/s/react-router-dotdot-fpjh5u?file=/src/App.tsx). The comparison to `cd` is incorrect, since `cd ..` always removes a single path segment.

Related issue from a while ago: https://github.com/remix-run/react-router/discussions/8998

**Comment by timdorr** [comment]
The key words there are "In these cases". It's saying this description applies when referring to nested routes. Your example doesn't have any nesting, so this doesn't apply.

**Comment by srmagura** [comment]
Thanks for responding @timdorr. I updated my [example](https://codesandbox.io/s/react-router-dotdot-v2-fpjh5u?file=/src/App.tsx) to include one level of nesting and you can see that the `<Link to="..">` still removes multiple segments of the path.

Perhaps the confusion is around the definition of the word "segment". Personally I would say the path `/a/b/c/d/e/f` has 6 segments, though maybe you would say it only has 2, due to how the `<Route>`s are defined in my example.

**Comment by kiliman** [comment]
By default, _relative_ paths are relative to the route hierarchy, not URL segments. To navigate the path, use `<Link to=".." relative="path">Parent</Link>`
