### ISSUE TITLE
[Bug]: createBrowserRouter only produce maximum of 3 level of nested children

### ISSUE THREAD

**Issue by bayu-wicaksono-at-insignia** [remix-run/react-router#10195]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

1. Create 4 levels of nested children for example:
![image](https://user-images.githubusercontent.com/107827903/224815930-488d8543-ec8a-4336-a16f-ccb8faac6852.png)

3. `export const router = createBrowserRouter(routes);`
4. add member and edit member page doesn't show up

### Expected Behavior

Add member and edit member are supposedly showing up

### Actual Behavior

It only renders the access management page

**Comment by brophdawg11** [comment]
I'm inclined to think this has something do do with your local setup - maybe you forgot an `<Outlet/>` somewhere?  There's no issue with deeply nesting children - here's an example going 6 levels deep - https://codesandbox.io/s/nesting-hgbtp4?file=/src/index.js.  

If you can provide a reproduction on Code Sandbox, please feel free to re-open this issue 👍 .

**Comment by bayu-wicaksono-at-insignia** [comment]
the access management and the add member are separate pages but I need to include the add member page inside the children. somehow it is still possible to show the access management page but when I navigate to add member the URL was changed but the page still stuck in the access management page
![image](https://user-images.githubusercontent.com/107827903/224886980-94ee75cd-b39b-4366-bd2d-75228d9c1622.png)

**Comment by bayu-wicaksono-at-insignia** [comment]
I made the code similar to this
https://codesandbox.io/s/nesting-forked-uyf2x1?file=/src/index.js

**Comment by brophdawg11** [comment]
You need to include [`<Outlet/>`](https://reactrouter.com/en/main/components/outlet) components in parent route elements so the router knows where to render their children.
