### ISSUE TITLE
[Bug]: shouldRevalidate behaves differently on production then development

### ISSUE THREAD

**Issue by FFGFlash** [remix-run/react-router#10197]
### What version of React Router are you using?

v6.8.0 - v6.9.0

### Steps to Reproduce

1. Create Project using createBrowserRouter()
2. Create 2 Routes
```js
const Routes = [
  {
    path: '/',
    children: [
      {
        path: 'one',
        element: <RouteOne />
      },
      {
        path: 'two',
        action: () => {},
        loader: () => 'Hello World!',
        shouldRevalidate: ({ currentUrl, nextUrl, formAction }) => {
          console.log('current: ', currentUrl.pathname)
          console.log('next: ', nextUrl.pathname)
          console.log('action: ', formAction)
          const shouldRevalidate = currentUrl.pathname !== nextUrl.pathname || currentUrl.pathname === formAction
          console.log('shouldRevalidate: ', shouldRevalidate )
          return shouldRevalidate 
        }
      }
    ]
  }
]

const Router = createBrowserRouter(Routes)
```

3.  Create two fetchers on route one
```js
function RouteOne() {
  const loaderFetcher = useFetcher();
  const actionFetcher = useFetcher();

  useEffect(() => {
    if (loaderFetcher .data || loaderFetcher .state !== "idle") return;
    loaderFetcher .load("/two");
  }, [loaderFetcher ]);

  const handleSomeAction = actionFetcher.submit(
    { data: "some data" },
    { action: "/two", method: "post" }
  );

  return (
    <>
      <div>{fetcher.data || "Loading..."}</div>
      <button onClick={handleSomeAction}>Some Action</button>
    </>
  );
}
```

### Expected Behavior (v6.7.0)

Expected behavior is that when we use the actionFetcher to submit to '/two' it should revalidate the loaderFetcher given the rules of shouldRevalidate. ``currentUrl.pathname !== nextUrl.pathname`` should revalidate due to navigation of children routes and ``currentUrl.pathname === formAction`` should revalidate when the action function is called on the given route.

In the given steps to reproduce the expected result looks something like the following
```
current: /two
next: /two
action: /two
shouldRevalidate: true
```

### Actual Behavior (v6.8.0 - v6.9.0)

In the versions 6.8.0 to 6.9.0 (currently latest), the currentUrl and nextUrl instead give the pathname of the rendered route instead of the route corresponding to the action and loader.

Results:
```
current: /one
next: /one
action: /two
shouldRevalidate: false
```

**Comment by FFGFlash** [comment]
I now can't get this to replicate, and instead I am getting the unexpected result, unfortunately I cannot provide the code in which I'm experience the expected behavior. Though if it isn't intended, I do believe it makes more sense for the currentUrl and nextUrl provided to shouldRevalidate should be the same as the path provided to the fetcher that's checking if it should revalidate, so possible feature request? This applies to currentParams and nextParams as well

**Comment by FFGFlash** [comment]
Expected behavior can be found in version 6.7.0 and is lost in version 6.8.0 (I'm guessing one of my team members updated the package and I hadn't updated on my local directory) I'm still wondering if this is an intentional change as I feel this is less intuitive?

**Comment by timdorr** [comment]
This was [an explicitly mentioned change in 6.8](https://github.com/remix-run/react-router/releases/tag/react-router@6.8.0), via #9948. The reasoning is posted in that PR and also in the release note. This is functioning as intended.
