### ISSUE TITLE
[Docs]: How to change page title

### ISSUE THREAD

**Issue by mpdata7** [remix-run/react-router#10199]
### Describe what's incorrect/missing in the documentation

I need to **change page title** for different react router dom pages.
There is noting about it in tutorial.
I dont understand how to do it correctly for 2 hours already.

I try to google this question, but the answer only works for older versions of this lib.

Please, add this to tutorial!

**Comment by timdorr** [comment]
This isn't something the Router does. You're looking for a library like [react-helmet](https://github.com/nfl/react-helmet).
