### ISSUE TITLE
[Bug]: The navigate method is not available in the browser of Vivo y53s

### ISSUE THREAD

**Issue by wangpanhb** [remix-run/react-router#10203]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

import { useNavigate, useParams } from 'react-router'

navigate('/path',{replace:true})

### Expected Behavior

Can jump to the corresponding path

### Actual Behavior

Do not jump when replace is used.
You can use window.location.replace to jump

**Comment by timdorr** [comment]
This should definitely work. If the browser on that device doesn't support this, it's not following the spec properly. There's nothing we can do about this.
