### ISSUE TITLE
[Docs]: Add docs for private/protected route implementation

### ISSUE THREAD

**Issue by differencialx** [remix-run/react-router#10206]
### Describe what's incorrect/missing in the documentation

I would like to see docs about private routes implementation, it's a common use case for applications. People writes articles about how to implement private routes(even for specific versions of react router), but don't you think that it should be documented as well and taken into account during next versions development?
https://dev.to/iamandrewluca/private-route-in-react-router-v6-lg5
https://jasonwatmore.com/post/2022/06/24/react-router-6-private-route-component-to-restrict-access-to-protected-pages

**Comment by differencialx** [comment]
@timdorr thank you, sorry for bothering you.

**Comment by Karbust** [comment]
> Hi @timdorr , can we have an example for protected routes using the new data router `createBrowserRouter` ? I was looking on how to do this using react hook/context to check the user auth status as most react auth libs provide hooks for checking the auth status but I am not sure if we can use hooks or context in `createBrowserRouter`
> 
> an official example for protected routes using hooks/context will really help here

Any news about this?

**Comment by aress31** [comment]
I would need an example using `createBrowserRouter` along with the `JSON` object definition of the routes.
