### ISSUE TITLE
React Router starter templates are broken

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#10215]
When you open an issue on react router you have these two links, but the first one doesn't run:

![Image](https://user-images.githubusercontent.com/100200/225723530-b1813d96-4001-41cd-b770-a33ef04aa8ce.png)

**Comment by ryanflorence** [comment]
There's also just way too much stuff in there. Should just have the root route w/ a hello world in it.

**Comment by ryanflorence** [comment]
```jsx
import React from "react";
import {
  createBrowserRouter,
  Outlet,
  RouterProvider,
} from "react-router-dom";

import "./index.css";

let router = createBrowserRouter([
  {
    path: "/",
    element: <Layout />,
  },
]);


export default function App() {
  return <RouterProvider router={router} />;
}


export function Layout() {
  return (
    <>
      <h1>Hello World</h1>
      <Outlet />
    </>
  );
}


if (import.meta.hot) {
  import.meta.hot.dispose(() => router.dispose());
}
```

Any objections to something like this instead?

Side note, the broken part is using `Component` instead of `element` on the route.

**Comment by johtso** [comment]
Looks sensible to me!

**Comment by brophdawg11** [comment]
This should be fixed now that `dev` merged down to `main` which had the missing update to `6.9.0` in the example (for `Component` support).  I updated to a much simpler example in #10285.
