### ISSUE TITLE
[Bug]: Navigate component navigates twice in a row in StrictMode

### ISSUE THREAD

**Issue by alex3d** [remix-run/react-router#10217]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

Render `<Navigate to={-1} />` in StrictMode.

### Expected Behavior

Window navigated to previous location in the history stack.

### Actual Behavior

Window navigated to second to previous location in the history stack.

**Comment by timdorr** [comment]
@ryanflorence had this to say recently: https://github.com/remix-run/react-router/issues/9116#issuecomment-1209771121

**Comment by brophdawg11** [comment]
`<Navigate>` only accepts strings by design so that dual-effects in StrictMode are to the same place.  `useNavigate` can accept a `-1` and you can use that and manage the double-effect logic with your own ref if needed.
