### ISSUE TITLE
[Bug]: TypeScript SetURLSearchParams type is not exported

### ISSUE THREAD

**Issue by thibaut-decherit** [remix-run/react-router#10212]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I have an utility class with the following function:
```typescript
static updateSearchParams(
  data: {
    [key: string]: string
  },
  searchParams: URLSearchParams,
  setSearchParams: (
    nextInit?: URLSearchParamsInit | ((prev: URLSearchParams) => URLSearchParamsInit),
    navigateOpts?: NavigateOptions
  ) => void
) {
  setSearchParams({
    ...Object.fromEntries([...searchParams]),
    ...data
  });
}
```

### Expected Behavior

Be able to type `setSearchParams` as `SetURLSearchParams`.

### Actual Behavior

`SetURLSearchParams` type is not exported, I have to duplicate it.

**Comment by brophdawg11** [comment]
This is exported in #10444 and will be available once 6.11.2 is released
