### ISSUE TITLE
[Docs]: Ambiguity around accessing or creating history object.

### ISSUE THREAD

**Issue by msteitle** [remix-run/react-router#10227]
### Describe what's incorrect/missing in the documentation

The docs (https://reactrouter.com/en/main/start/concepts#history-object) refer to utilizing a "React Router specific history object" directly for listening to navigation events. However it fails to specify how to create or access this history object. The docs provide a code example in which createBrowserHistory is used, but not where to import it from.

```javascript
let history = createBrowserHistory();
history.listen(({ location, action }) => {
  // this is called whenever new locations come in
  // the action is POP, PUSH, or REPLACE
});
```

`createBrowserHistory` is exported from the canonical `history` library, but not react-router or react-router-dom. Is the expectation that the history library be installed separately and used to create this object?

**Comment by timdorr** [comment]
That is just explaining some internal mechanics of React Router. It's not code you have to write yourself.

**Comment by msteitle** [comment]
Hi @timdorr. Thanks for your reply, but that's not helpful. It is not merely explaining internal mechanics. The app I support has long since used connected-react-router to accomplish navigation as part of an asynchronous action which exists outside of the React component flow, so using a hook (useNavigate) or using declarative navigation via <Navigate /> aren't options.

**Comment by jamesthomsondev** [comment]
@msteitle Were you able to find a resolution to this? I've just hit the same issue. I need to listen to history to determine the action so I can animate view transition according to forward/back in the history stack. The underlying lib has exactly what I need, but as you, I'm disappointed to find that this specific behaviour is not exposed to React Router,

**Comment by msteitle** [comment]
@jamesthomsondev Yes, though it sounds like our use cases are slightly different. I rolled my own replacement for redux router navigation. First, I created redux actions for _push_, _replace_, and _back_ navigation operations. I use them in place of the prior redux-router actions e.g. `dispatch(push('/foo'))`. Its purpose is to store the last navigation operation. Finally, I created a hook that I added to the top of my routes definition component. Its purpose is to subscribe to changes to the aforementioned navigation state and execute the last navigation operation when it is added using `navigate` from the `useNavigate` redux-router-dom hook.

**Comment by jamesthomsondev** [comment]
Thanks for your reply @msteitle. It's definitely looking like I'll have to roll my own solution as well. For now I'm using the `useNavigationType` hook's `POP` value to get me 90% there. Sadly this doesn't allow me to determine forward navigations (e.g. triggered by the browser button) so I'll have to come up with a proper fix later - probably something to do with comparing history keys.
