### ISSUE TITLE
[Bug]: MatchPath not working with optional parameter

### ISSUE THREAD

**Issue by grzegorzCieslik95** [remix-run/react-router#10226]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I have a route with path = `/login/:serviceName?`
When the user goes to pathname -> `matchPath(/login/test )` returns null.

### Expected Behavior

It should work like in v5 

### Actual Behavior

Return null should return true or some object with details

**Comment by timdorr** [comment]
Duplicate of https://github.com/remix-run/react-router/issues/9793 / https://github.com/remix-run/react-router/discussions/9862
