### ISSUE TITLE
[Bug]: Race Condition, React Router flushes before React state updates

### ISSUE THREAD

**Issue by SukkaW** [remix-run/react-router#10232]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I have created a reproduction on StackBlitz: https://stackblitz.com/edit/react-ts-cju3ly?file=App.tsx

This is a dead simple login page, and I have implemented protected routes with React Router's pathless route feature.

### Expected Behavior

After clicking the `Log In` button, the page should be navigated to the index page (showing `SECRET!`).

### Actual Behavior

You will have to click the `Log In` button twice to see the index page.

Turns out that the React Router has navigated before the `token` state is set.

## Additional  Information

Here is the full source code of the reproduction, copied from the stackblitz:

```tsx
// App.tsx
import * as React from 'react';
import './style.css';
import {
  RouterProvider,
  Outlet,
  Navigate,
  useLocation,
  createBrowserRouter,
  useNavigate,
} from 'react-router-dom';

// Token And Stuff
const TokenContext = React.createContext<string | null>(null);
const SetTokenContext = React.createContext<
  React.Dispatch<React.SetStateAction<string | null>>
>(() => {});
const TokenProvider = ({ children }) => {
  const [token, setToken] = React.useState(null);
  return (
    <SetTokenContext.Provider value={setToken}>
      <TokenContext.Provider value={token}>{children}</TokenContext.Provider>
    </SetTokenContext.Provider>
  );
};
const useToken = () => React.useContext(TokenContext);
const useSetToken = () => React.useContext(SetTokenContext);

// Login Page
let loginButtonClicked = 0;
const LoginPage = () => {
  const setToken = useSetToken();
  const navigate = useNavigate();

  return (
    <div>
      <button
        onClick={async () => {
          loginButtonClicked++;
          await fetch('https://httpbin.org/json'); // simulate login
          setToken('random');
          navigate('/');
        }}
      >
        Log In (click count: {loginButtonClicked})
      </button>
      <p>
        click count should never exceeds 0, as once login button is clicked the
        page should be navigated away
      </p>
    </div>
  );
};

// Protected Page
const ProtectedIndex = () => <div>SECRET!</div>;

// Layout
const Layout = () => (
  <div>
    <Outlet />
  </div>
);

// Protected
const Protected = () => {
  const token = useToken();
  const { pathname } = useLocation();

  console.log({
    description: '<Protected /> is checking token',
    token,
    pathname,
  });

  if (!token) {
    return <Navigate to="/login" replace />;
  }

  return <Outlet />;
};

// Routes
const router = createBrowserRouter([
  {
    // pathless route, root layout
    element: <Layout />,
    children: [
      {
        path: '/login',
        element: <LoginPage />,
      },
      {
        // another pathless route, grouping protected routes
        element: <Protected />,
        children: [{ index: true, element: <ProtectedIndex /> }],
      },
    ],
  },
]);

export default function App() {
  return (
    <TokenProvider>
      <RouterProvider router={router} />
    </TokenProvider>
  );
}
```
```tsx
// index.tsx
import * as React from 'react';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

import App from './App';

const rootElement = document.getElementById('root');
const root = createRoot(rootElement);

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
```

**Comment by harveyhq** [comment]
@SukkaW setToken() on button click causes re-rendering

**Comment by SukkaW** [comment]
> @SukkaW setToken() on button click causes re-rendering

@harveyhq The expected behavior is that, `setToken` and `navigate` is batched, result in one re-render. Or they are not batched, causing two re-renders, but `setToken`'s re-render should happen before `navigate`'s re-render.

**Comment by harveyhq** [comment]
You are right, not sure if its a react-router bug, mroe like react batch schedule, but as a workaround
```js
setTimeout(() => navigate('/'), 0);

//or

useEffect(() => {
  if (token !== null) {
    navigate("/");
  }
}, [token, navigate]);
```

**Comment by brophdawg11** [comment]
I agree this seems unrelated to react router and has to do with how React batches/schedules.

If you're using `createBrowserRouter`, the recommended way to do protected routes is via a `loader` and `redirect` which decouples your navigation from rendering and avoids these low-level react batching issues.

```js
const router = createBrowserRouter([{
  path: "/",
  loader() {
    if (!token) {
      return redirect("/login");
    }
    ...
  },
  ...
}, {
  path: "/login", 
  ...
}]);
```

**Comment by SukkaW** [comment]
> If you're using `createBrowserRouter`, the recommended way to do protected routes is via a `loader` and `redirect` which decouples your navigation from rendering and avoids these low-level react batching issues.

What happens if I am not building a protected route but building a form, and I need to redirect after I store some state? The not-batching state is still there.
