### ISSUE TITLE
[Bug]: useNavigate hook mounts the target page twice (mount-unmount-mount) - in StrictMode

### ISSUE THREAD

**Issue by CiprianDraghici** [remix-run/react-router#10240]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

1. Create a clean react project (react v18 and react-router-dom v6)
2. Use basic navigation between 2 pages
3. Set some console logs in useEffect on the target page to see the behavior
```
useEffect(() => {
        console.log("Page mounted");

        return () => {
            console.log("Page unmounted");
        }
    }, [])
```
4. Checking the console then it's visible that the first time when navigating to a page it tries to mount the page, but immediately unmounts the page and after that remount the page. (mount - unmount- mount)
5. Demo project can be found here: https://github.com/CiprianDraghici/react-router-dom-v6-navigation-issue

**!!! Important note !!!**
1. It's not reproducible using react 17. 
2. Using react 18 and react-router-dom v5 (using useHistory) is not reproducible

**### Later edit:
Looks like the behavior is reproducible only in StrictMode**

### Expected Behavior

Navigating to a page should mount the page only one time.

### Actual Behavior

Mount-unmount-mount

https://user-images.githubusercontent.com/11082863/226609762-7ac29ccb-4df4-4789-a149-a05458ec0ded.mov

**Comment by timdorr** [comment]
This is what StrictMode does to your app. It will always render your app twice to find impure effects and missing cleanup functions: https://react.dev/reference/react/StrictMode
