### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xuzs** [remix-run/react-router#10269]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

if my url is '/test/1-a' can not match <Route />

<img width="577" alt="image" src="https://user-images.githubusercontent.com/11747801/227887463-e8588d66-5256-408f-b07d-fa2bd1ce526b.png">

i find it is '**compilePath**' function in  **"@remix-run/router@1.4.0"**

version < 1.4.0,  **Work properly**

please use it 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/11747801/227888570-2a174a27-2229-4645-ac6b-5f20434cd5c7.png">

### Expected Behavior

const [matcher,params] = compilePath('/search/brands/:keywords-:country', false, true)

i want params is ['keywords', 'country']

### Actual Behavior

const [matcher,params] = compilePath('/search/brands/:keywords-:country', false, true)

i want params is ['keywords', 'country']

**Comment by xuzs** [comment]
Now I have to use version < 6.5.0

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/10251#issuecomment-1483353341
