### ISSUE TITLE
[Bug]: `useSearchParams` doesnt reflect defaultInit in search param

### ISSUE THREAD

**Issue by keita-determined** [remix-run/react-router#10268]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

https://codesandbox.io/s/using-usesearchparams-forked-235kqm

Even if i set `defaultInit`, the values are not reflected in URL
```tsx
import React from "react";
import { useSearchParams } from "react-router-dom";

export default function App() {
  const [searchParams, setSearchParams] = useSearchParams(
    new URLSearchParams([
      ["foo", "1"],
      ["bar", "2"]
    ])
  );

  return (
    <div className="App">
      <div>foo: {searchParams.get("foo")}</div>
      <div>bar: {searchParams.get("bar")}</div>
    </div>
  );
}

```

### Expected Behavior

the url should have `?foo=1&bar=2`

### Actual Behavior

URL without search params

**Comment by timdorr** [comment]
The `defaultInit` allows you to set values to be used if the params are not into the page's URL. It's not possible to set them via the parameters of the hook, as that would cause a navigation event and a mutation of state, which would make the hook impure and would be a violation of the rules of hooks. 

If you want those values in the URL, you'll need to call `setSearchParams`.
