### ISSUE TITLE
[Bug]: Can't use File in action

### ISSUE THREAD

**Issue by SH5H** [remix-run/react-router#10261]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

https://stackblitz.com/edit/github-q4yzzl?file=src/app.tsx

I tried to use a file in an `action` using the `<Form/>` component, but the file is not found and I can only see the filename as a string.

### Expected Behavior

An object of the file type should appear in the console.

### Actual Behavior

The console displays only filenames in string format.

**Comment by timdorr** [comment]
Add `encType="multipart/form-data"` to your Form's props.

**Comment by SH5H** [comment]
Thanks, I think this option should be added to the documentation.

**Comment by SH5H** [comment]
Thanks
