### ISSUE TITLE
[Bug]: generatePath strips trailing slashes

### ISSUE THREAD

**Issue by mrginglymus** [remix-run/react-router#10291]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

`generatePath('/foo/')`

### Expected Behavior

`/foo/`

### Actual Behavior

`/foo`

I'm guessing this is caused by #10078

**Comment by jdouitsis** [comment]
Hello, is anyone working on this issue?

**Comment by gmaxlev** [comment]
As far as I can see, generatePath removed the slash from the end because it interpreted it as an empty segment.

https://github.com/remix-run/react-router/blob/main/packages/router/utils.ts#L749

**Comment by timdorr** [comment]
This is correct. React Router treats the slash as a separator. So, in generating a path, we treat that final segment as an empty string and remove it for having no value. We always generate URLs without the trailing slash.

**Comment by mrginglymus** [comment]
Is there a recommended way to get back the original behaviour? This breaking change from the original behaviour of the code (which whilst did not document that it would preserve trailing slashes, did not also say that it would remove empty segments, because it didn’t) has caught us by surprise.

**Comment by mrginglymus** [comment]
I would be happy to provide a patch to restore the original behaviour; otherwise I’d suggest that further detail in the documentation and tests verifying the stripping of empty segments is added to help anyone else upgrading who was expecting preservation of trailing slashes

**Comment by fpasquet** [comment]
Yes, I agree that this is a breaking change, for all those who use React Router and who make SSG it is very problematic.
In our case, when we navigate to the search url:
```tsx
export const PATHS = {
   ...
  SEARCH: '/:lang/search/',
};
...
navigate({
      pathname: generatePath(PATHS.SEARCH, { lang: i18n.language }),
      search: `search=${value}`,
    });
```

The generated url is `/en/search?search=keyword`
And so when we refresh the page, we lose all the query parameters.

Can add a `trailingSlash` option like on NextJS, https://nextjs.org/docs/api-reference/next.config.js/trailing-slash

**Comment by alanjo4** [comment]
Hi @Eliasvdb did you mentioned that you were working on an old AEM frontend? Were you able to migrate to v6? I'm not able to do that and I'm still researching on how to do that, as you (probably) already know, maybe you notice that <Route> does not contain <Routes> parent. There is a file called RouterHelper, but when I use <Routes> my app is rendering a blank page without errors. I will really appreciate your hints, thanks in advance.

**Comment by Flaysh** [comment]
thank you

**Comment by samkuehn** [comment]
This is the hack that I came up with:
```javascript
let path = generatePath(route.path, params);
path = path.replace(/\/?(\?|#|$)/, "/$1");
```

**Comment by dazlious** [comment]
Another dev here that has a problem with this not being backwards compatible (and not being mentioned on the release notes)
