### ISSUE TITLE
[Bug]: generatePath function corrupts double slashes at the start of the url

### ISSUE THREAD

**Issue by IHiFiveI** [remix-run/react-router#10304]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

```
  const originalURL = 'https://mysite.com/posts/:postId';
  const newURL = generatePath(originalURL, {
    postId: '5055',
  });
```

### Expected Behavior

I would expect `newURL` to be equal to `https://mysite.com/posts/5055`

### Actual Behavior

`newURL` equals to `https:/mysite.com/posts/5055`

**Comment by TrueRacoon** [comment]
Caused by #10078. Before these commits steps to reproduce led to the expected result.

**Comment by timdorr** [comment]
`generatePath` doesn't take a fully-qualified URL, just the pathname section. The origin should be left out.
