### ISSUE TITLE
[Docs]: Form doesnt make navigation if there is no action

### ISSUE THREAD

**Issue by wusaby-rush** [remix-run/react-router#10303]
### Describe what's incorrect/missing in the documentation

In https://reactrouter.com/en/main/start/tutorial#mutations-without-navigation they use fetcher.Form to prevent navigation, but from my test Form doesnt make navigation if there is no action, in same example there is no action

useFetcher here is needless, please make another example for this future

**Comment by timdorr** [comment]
This is mentioned in the paragram directly following it:

> Since there is no `<fetcher.Form action="...">` prop, it will post to the route where the form is rendered.
