### ISSUE TITLE
[Bug]: Should initialise the passed searchParams correctly at simultaneous useEffect

### ISSUE THREAD

**Issue by OttlikG** [remix-run/react-router#10316]
### What version of React Router are you using?

6.9

### Steps to Reproduce

Go [here](https://codesandbox.io/s/react-router-init-search-param-cqw44j).

And see the search params.

### Expected Behavior

It's expected to have `?a=a&b=b` instead of the last set overwriting the previous.

When we invoke the `setSearchParams` from a callback that sets the search params correctly.

### Actual Behavior

I would like to initialise the search params from different points of my application at initial rendering.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/9757#issuecomment-1359693916
