### ISSUE TITLE
Why is the official use case wrong

### ISSUE THREAD

**Issue by pushOkIsGo** [remix-run/react-router#10319]
### Describe what's incorrect/missing in the documentation

![image](https://user-images.githubusercontent.com/101095473/230530101-caee7b90-bca8-4c67-bd46-9abc0d5ae1ae.png)

![image](https://user-images.githubusercontent.com/101095473/230530197-76b56557-1a70-40bf-956a-26fa19ba05c9.png)

**Comment by timdorr** [comment]
Something else is going on here, as [that is a function component](https://github.com/remix-run/react-router/blob/b06af699ed744f6f5013c6719975eeb214005e65/packages/react-router/lib/components.tsx#L56-L59). Perhaps you have something transpiling it to a class component? Regardless, this isn't a bug in our code.
