### ISSUE TITLE
[Bug]: Getting "Should not already be working" error in Firefox for unstable_usePrompt

### ISSUE THREAD

**Issue by noherczeg** [remix-run/react-router#10314]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

```
import {unstable_usePrompt as usePrompt, useParams} from 'react-router-dom';

usePrompt({
    message: 'Please don\'t leave!',
    when: true,
});
```

### Expected Behavior

Should not print error in Firefox

### Actual Behavior

It actually works as expected, but we are getting an error in Firefox consoles:

`Uncaught Error: Minified React error #327; visit https://reactjs.org/docs/error-decoder.html?invariant=327 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

Which results in "Should not already be working."

Maybe this should help? https://github.com/facebook/react/issues/17355#issuecomment-1232806058

**Comment by noherczeg** [comment]
Has something to do with this I guess:

```javascript
React.useEffect(() => {
    if (blocker.state === "blocked") {
      let proceed = window.confirm(message);
      if (proceed) {
        setTimeout(blocker.proceed, 0);
      } else {
        blocker.reset();
      }
    }
  }, [blocker, message]);
```

**Comment by timdorr** [comment]
You should be running a development build of React while running your app locally. It will give more helpful error messages and context this way.

This may be a browser-specific issue, possibly related to policy things built-in to Firefox. Given that this is still an unstable API, we can't yet support this use case. We would need a more specific error message to work with.

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏
