### ISSUE TITLE
[Bug]: Nested routes from components not matching or loaded

### ISSUE THREAD

**Issue by angellindo** [remix-run/react-router#10321]
### What version of React Router are you using?

RR 6.x, React 18.2.0

### Steps to Reproduce

I've created this example to demonstrate the issue I'm having while migrating from `5.3.4` to `6.x`

https://codesandbox.io/s/eloquent-shaw-4qgm3c?file=/src/App.js

so basically I got the main routes and a component that has "internal" routes that in the app I'm working on are tabs.

In that example if you go to the url `/portal/organisations/23` it loads the index fine.

once you click on tasks or notes it does nothing, I tried relative paths and absolute paths and none worked.
the only thing that made the paths match was to change the path from the main routes to use the splat.

Unless we are missing something on how v6 works and the documentation that says `<Routes>` can be used anywhere. 

In our app there's much more logic than that example that made us do it that way.

### Expected Behavior

Render the UI components that match the routes in that component, ie. change the url based tab navigation and show their content

### Actual Behavior

Routes in the nested component are not matching and doesn't render even partially

**Comment by angellindo** [comment]
I tried this other approach and also doesn't match the routes in the component

https://codesandbox.io/s/hungry-chihiro-75uxhi?file=/src/App.js

**Comment by timdorr** [comment]
You need a wildcard at the top route that's matching so it can match other pathnames underneath it:

```js
<Route path=":orgId/*" element={<OrganisationDetails />} />
```
