### ISSUE TITLE
[Bug]: NavLink active even when hash does not match

### ISSUE THREAD

**Issue by wfjake** [remix-run/react-router#10325]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

When a NavLink has a to= with a hash parameter, it should not be set active unless that hash is also in the current URL.

For example,
```
<NavLink to="#tabA">Tab A</NavLink>
<NavLink to="#tabB">Tab B</NavLink>
<NavLink to="#tabC">Tab C</NavLink>
 ```
These are all set to active despite the URL not containing any of them. I am using this to navigate a tab within the page like so (notice all have active set):
![image](https://user-images.githubusercontent.com/118236421/230736775-9ca10312-aa3e-4d59-94a3-240c3d857b26.png)

### Expected Behavior

NavLink should have some kind of `exact` attribute or automatically check hash when setting active. Alternatively, NavLink should allow users to override the default check for setting active like in previous versions.

### Actual Behavior

All NavLinks are set as active instead of just the current hash.

**Comment by timdorr** [comment]
NavLink only [matches based on the `pathname`](https://github.com/remix-run/react-router/blob/f85e0b33536645aa14c9d7cc6e3f9e09f63373da/packages/react-router-dom/index.tsx#L555-L559) of the provided string or Location object. A hash is just a link to an anchor on the same page, so those all should be active when at the same page/pathname. If you need different behavior, it's going to be easier to use `Link` and provide your own matching behavior.
