### ISSUE TITLE
[Docs]: Tutorial on reactrouter.com isn't the same as what is in github.  

### ISSUE THREAD

**Issue by edtbl76** [remix-run/react-router#10337]
### Describe what's incorrect/missing in the documentation

Title says it all.

**Comment by timdorr** [comment]
I see all of the content here: https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md visible here: https://reactrouter.com/en/main/start/tutorial

If there's something specifically missing, please let us know what that is.

**Comment by edtbl76** [comment]
The tutorial content doesn't match the actual tutorial...

**Comment by edtbl76** [comment]
Look in the tutorial directory. The code is some Bookkeeper app,not the
code for the getting started tutorial.

(The tutorial is also broken. Once you get to edit.jsx, it fails to update
w/ an error about the updates variable.)

**Comment by timdorr** [comment]
You're looking at the wrong file. You don't want `_tutorial.md`. This is the file for the tutorial on the site: https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md

**Comment by edtbl76** [comment]
No, you're assuming that is what I'm looking for.

I'm not referring to the markdown file. I'm referring to the application
example in the tutorial folder.

The example CODE does not match the CODE in the tutorial.

There is no CODE example for the tutorial, only the markdown file you
referenced

The reason I'm looking for the example app is that the tutorial (that you
are referencing) has a bug in it.

The edit.jsx specifically. When trying to save a new entry, an error
references the update variable.

**Comment by edtbl76** [comment]
Yes, were getting closer now.

As I stated before, following the instructions doesn't yield a completed
project. It yields an error due to a problem in edit.jsx.

If one copies all of the code directly from the markdown...bug.
