### ISSUE TITLE
[Bug]: In the component library, useInRouterContext() return false

### ISSUE THREAD

**Issue by distance321** [remix-run/react-router#10332]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

Encapsulates a component in a component library that uses the Hooks method provided by the React Router. Other projects reference components encapsulated in this component library

### Expected Behavior

Components encapsulated in other project reference component libraries can be used as normal

### Actual Behavior

The components encapsulated in my component library project use the Hooks method in React Router. Before version 6.9.0, other projects had no issues referencing this component, but after version 6.9.0, In encapsulated components useInRouterContext() return false, all Hooks methods unusable.

**Comment by timdorr** [comment]
This is not a bug with our library. You have two copies of React Router installed (one in your component library and one in your app). This is likely a side effect of the upgrade to the latest version. I'd find the duplicates via `npm ls` and make sure your version selectors allow for the exact same version to exist in your project and library.

**Comment by distance321** [comment]
I checked the dependencies of the two projects and found that other packages in the component library referenced the lower version of the dependency. I have solved the problem, thanks for your answer
