### ISSUE TITLE
[Bug]: Different behaviour between Chrome & Firefox while using event.stopPropagation from a child of a Link

### ISSUE THREAD

**Issue by antonisprovidakis** [remix-run/react-router#10340]
### What version of React Router are you using?

v6.2.1

### Steps to Reproduce

As you can see in the codesandbox I've attached, there is a `<Link>` that wraps a div, and a checkbox is placed inside the div.
When you click on each of those divs, I want to redirect on a different route.
However, when a checkbox is clicked I just want the checkbox to toggle states, and prevent the redirect from happening.

I see Chrome behaves differently from Firefox:
- **Chrome**: Clicking on the checkbox works as expected, the checkbox's state is toggled. No navigation takes place.
- **Firefox**: Clicking on the checkbox works as expected, the checkbox's state is toggled (I can see the checkmark for a fraction of time). However, a navigation takes place to the Links' `to` value with a full page reload. I guess, it's like I'm clicking on a raw `a` element.

Codesandbox: https://codesandbox.io/s/blazing-field-ju60l2

### Expected Behavior

I'd expect Firefox to behave like Chrome, meaning:
The navigation of the Link (a) not to run, since the onClick event of the checkbox is stopped from propagating.

### Actual Behavior

I think the Link, acts like a normal `a` and the `href` is followed normally from the browser.
So, the navigation is performed actually with a full page refresh.

**Comment by antonisprovidakis** [comment]
To be honest, I'm not sure if this is a react-router bug.
So please feel free to close this, if it's not.

**Comment by timdorr** [comment]
Putting form elements within an `<a>` is generally not recommended, as you'll deal with event priority issues and browser quirks like this. This doesn't appear to be a bug with React Router though.
