### ISSUE TITLE
[Bug]: search params lost when redirected to parent route with child index redirect route

### ISSUE THREAD

**Issue by shravyaRB** [remix-run/react-router#10343]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Hello when I navigate to a parent url with search params, the search params are lost when this parent route has an index redirect to its child route

Example:
```
// I navigate to topics link with search params:
 <Link to="/topics?search=hooks">
      Topics
</Link>

const Topics = () => {
  return (
      //.. other code
      <Routes>
        <Route index element={<Navigate to="reactjs" />} />
        <Route path=":topicId/*" element={<Topic />} />
      </Routes>
  )
}
```

When I click on Topics  the search params attached are lost and the URL is now `topics/reactjs` instead of `topics/reactjs?search=hooks`

### Reproducible repo
https://stackblitz.com/edit/react-jpukhl?file=src/App.js

### Expected Behavior

The search params should preserve when I navigate to a URL that has an index redirect to the child route URL

### Actual Behavior

The search params are lost. My final URL is `topics/reactjs` instead of `topics/reactjs?search=hooks`

**Comment by timdorr** [comment]
That is not the expected behavior here. They do not automatically get added to the URL for `<Navigate>`. If you need them to be carried over, you should create a component that uses `useNavigate` and `useSearchParams` to carry them through.

**Comment by shravyaRB** [comment]
Ok, we are migrating from v3 to v6 and it raised some doubts because it is automatically handled by `IndexRedirect` in `v3`
