### ISSUE TITLE
[Docs]: Upgrade guide is out of date

### ISSUE THREAD

**Issue by kaaboaye** [remix-run/react-router#10348]
### Describe what's incorrect/missing in the documentation

in https://reactrouter.com/en/6.10.0/upgrading/v5

```tsx
<Switch>
  <Redirect from="about" to="about-us" />
</Switch>

// to this:
<Switch>
  <Route path="about" render={() => <Redirect to="about-us" />} />
</Switch>
```

There is no `<Route render>` prop and `<Redirect>` component.

**Comment by kaaboaye** [comment]
I have to say that this upgrade process is the worst one I've ever seen. It basically requires rewrite of entire app with no apparent way to do this incrementally. And there are no great incentives to do so.

**Comment by timdorr** [comment]
At that stage, you are still at v5, so there is a render prop for Routes. That changes to an `element` prop in v6 later on.
