### ISSUE TITLE
[Bug]: window.location.origin is undefined getting a blank page

### ISSUE THREAD

**Issue by jaryway** [remix-run/react-router#10341]
### What version of React Router are you using?

react-router-dom v6

### Steps to Reproduce

in low version ie 11 (for me ie version 11.0.9600.16428)
![image](https://user-images.githubusercontent.com/5987056/231738990-be0c642c-1a32-4d72-b0e9-8be1e8fd2abb.png)

window.location.origin is undefined that causing an error, resulting in a blank page
```
`No window.location.(origin|href) available to create URL for href: /`
```

https://github.com/remix-run/react-router/blob/f85e0b33536645aa14c9d7cc6e3f9e09f63373da/packages/router/history.ts#L667

```js

let base =
      window.location.origin !== "null"
        ? window.location.origin
        : window.location.href;

```

### Expected Behavior

No errors occur

### Actual Behavior

Got a blank page

**Comment by timdorr** [comment]
We don't support Internet Explorer.
