### ISSUE TITLE
[Bug]: router.navigate(...) will not automatically bring basename

### ISSUE THREAD

**Issue by GrinZero** [remix-run/react-router#10352]
### What version of React Router are you using?

v6.10.0

### Steps to Reproduce

I have prepared an online case study：https://stackblitz.com/edit/github-kdru9h?file=src/app.tsx
If a white screen appears in the case, please manually add '/web' after the URL of the case`，The homepage of the case looks like this：
![image](https://user-images.githubusercontent.com/70185413/232306902-cced34aa-6203-462c-9a8d-51bdbf7e6bf9.png)

1. use `createHashRouter` or `createBrowerRouter` to create `router`
2. use `router.navigate(...)`

### Expected Behavior

In the example, I hope that jumping through 'router. navigate ('/user ')' is effective, rather than manually adding 'basename' to 'router. navigate ('/web/user ')`

### Actual Behavior

router.navigate(...) will not automatically bring basename

**Comment by timdorr** [comment]
This is expected behavior. Link adds the basename as it is emulating a plain `<a>` and that will be affected by `<base>`. `navigate` isn't a DOM API, so it isn't necessarily affected by the `basename` property.

**Comment by shalldie** [comment]
I found that `router.navigate(...)` will bring the basename at `"react-router-dom": "^6.14.2"`

Can you tell me from which version this behavior originated ? I need to check and upgrade a lot of apps.

@timdorr
