### ISSUE TITLE
[Bug]: catch all display not correct on nested route

### ISSUE THREAD

**Issue by JiangWeixian** [remix-run/react-router#10357]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Routes define in my project like this:

**Method-1**

```tsx
<BrowserRouter>
  <Routes>
    <Route path='/blog'>
      <Route path='*' element={<CatchAll />} />
      <Route path=':id' element={<BlogId />} />
    </Route>
    <Route path='*' element={<CatchAll />} />
  </Routes>
</BrowserRouter>
```

When goto `/blog`, not fallback into `<Route path='*' element={<CatchAll />} /> under <Route path='/blog'>`. However when I change routes into:

**Method-2**

```tsx
<BrowserRouter>
  <Routes>
    <Route path='/blog/*' element={<CatchAll />} />
    <Route path='/blog/:id' element={<BlogId />} />
    <Route path='*' element={<CatchAll />} />
  </Routes>
</BrowserRouter>
```

When goto `/blog`, fallback into `<Route path='blog/*' element={<CatchAll />} />`.

**Method-3**

or add `index` prop to `*` route

```tsx
<BrowserRouter>
  <Routes>
    <Route path='/blog'>
      <Route path='*' index={true} element={<CatchAll />} />
      <Route path=':id' element={<BlogId />} />
    </Route>
    <Route path='*' element={<CatchAll />} />
  </Routes>
</BrowserRouter>
```

When goto `/blog`, fallback into `<Route path='*' element={<CatchAll />} /> under <Route path='/blog'>`.

### Expected Behavior

> Routes define see the above **Method-1**:

- `/blog` render `<CatchAll />` (if index not exit), just like **Method-2** and **Method-3**

### Actual Behavior

> Routes define see the above **Method-1**:

- `/blog` render nothing

**Comment by JiangWeixian** [comment]
> You want an `index` prop for these routes, not a wildcard: https://reactrouter.com/en/main/route/route#index

Thanks for response, I get it now. If I want catch `/blog` or `/blog/id/xxx`, I should use `<Route index={true} path="*" element={<CatchAll />} />`

But I found another case, when I define my routes like this:

```tsx
<Routes>
  <Route path='/blog'>
    <Route path=':id' element={<BlogId />} />
  </Route>
  <Route path='*' element={<CatchAll />} />
</Routes>
``` 

No `index` route under `/blog`, when I goto `/blog`, should fallback into root `<CatchAll />` route? (I not sure it's bug or just by design. Or I just have to define my route like `<Route path='/blog/:id' element={<BlogId />} />`)

**Comment by timdorr** [comment]
That is by design. The `/blog` path has matched, so it's now attempting to match a Route within that block. You need a `<Route index element={} />` within that block as well.
