### ISSUE TITLE
[Bug]: History createURL window.location.origin and href are null when using outlook

### ISSUE THREAD

**Issue by DanNelson99** [remix-run/react-router#10356]
### What version of React Router are you using?

^6.8.1

### Steps to Reproduce

1. Create app with several routes and set up routes with createBrowserRouter.
2. Open app in current version of outlook. 
3. Navigate to a new url
4. Nothing happens
5. The error is from createURL in history.ts and neither window.location.origin or window.location.href have values they both null.

### Expected Behavior

The page should have rendered with no issue

### Actual Behavior

When clicking the button with a link nothing happens

**Comment by timdorr** [comment]
Sorry, but Outlook's embedded browser is not supported.
