### ISSUE TITLE
[6.10.0][Bug]: tree shaking is not implemented

### ISSUE THREAD

**Issue by xr0master** [remix-run/react-router#10354]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

It looks like the tree shaking is not implemented. The library is huge.

version 5
<img width="713" alt="Screenshot 2023-04-16 at 23 39 20" src="https://user-images.githubusercontent.com/8962340/232324362-e6148d2a-9bf7-4481-82fc-6ff399f8e14f.png">

version 6
<img width="710" alt="Screenshot 2023-04-16 at 23 38 01" src="https://user-images.githubusercontent.com/8962340/232324378-7e9ecc58-921f-4c7f-ac22-73b967196309.png">

### Expected Behavior

"In v6, the size of the minified gzipped bundle is reduced by more than 50%. so, React Router currently contributes less than 4kb of your overall app bundle."

### Actual Behavior

v6 is more than 5 times larger than v5

**Comment by timdorr** [comment]
Tree-shaking is a bundler matter, not a concern of the library. We export modules, which your bundler can import and tree-shake appropriately. The entirety of the library will rarely be fully included in any bundle. If it is, you have a bundler configuration issue.

**Comment by gerhardsletten** [comment]
So to clarify, the bundle size has doubled in v6:

[bundlephobia.com/package/react-router-dom@6.10.0](https://bundlephobia.com/package/react-router-dom@6.10.0) - 63.8 kB (20 kB gzip)

vs v5:

[bundlephobia.com/package/react-router-dom@5.3.4](https://bundlephobia.com/package/react-router-dom@5.3.4) - 30.7 kB 9.8 kB gzip)

Are there any plans to do something with this?

**Comment by xr0master** [comment]
@timdorr I did not expect another answer/action from Remix Run (away). Most use CRA for React, and I doubt that there is a problem with the bundler.

Of course, instead of analyzers, we can use some "hello world" project and look at the real numbers.

**Comment by xr0master** [comment]
@gerhardsletten thanks for the tip! In fact, if avoid using the data router, then the size is significantly reduced. `398.14 kB (-10.17 kB)`.

**Comment by gerhardsletten** [comment]
@xr0master I also made an Vite example with an updated way to handle both lazy Routes modules and data fetching with react-query here: [github.com/gerhardsletten/vite-react-router-ssr-suspend](https://github.com/gerhardsletten/vite-react-router-ssr-suspend)

**Comment by khoroshevj** [comment]
still an issue, huge size impact of `@remix-run/router` in bundle, using react-router-dom version 6.23.1 with Vite. any workaround? using just these `createBrowserRouter, useParams, Outlet, Link, Navigate, RouteObject, RouterProvider` from `react-router-dom`

<img width="521" alt="Screenshot 2024-05-23 at 14 11 00" src="https://github.com/remix-run/react-router/assets/13628506/909c58cf-e180-46a8-8089-378c1fcd7f50">

<img width="479" alt="Screenshot 2024-05-23 at 14 17 44" src="https://github.com/remix-run/react-router/assets/13628506/41c47015-a10e-43a9-973c-8fc57f480961">
<img width="509" alt="Screenshot 2024-05-23 at 14 20 49" src="https://github.com/remix-run/react-router/assets/13628506/a5bdb8e3-2dae-44ac-a1df-cc21a8cc4c9f">

**Comment by sphinxrave** [comment]
@khoroshevj , I reproduced this in bundlejs here:

https://bundlejs.com/?q=react-router-dom%2Creact-router-dom&treeshake=%5B*%5D%2C%5B*%5D&text=%22createBrowserRouter%28%29%3B%5CnNavigate%3B%5Cn%5CnLink%3B%22&config=%7B%22analysis%22%3A%22treemap%22%2C%22esbuild%22%3A%7B%22external%22%3A%5B%22react%22%2C%22react-dom%22%5D%7D%7D

Do note though that the analysis *might* be off, since it reports 15kb gzip full but the treemap suggests 72kb gzip full, I'm not sure which to believe?

![image](https://github.com/remix-run/react-router/assets/62570796/81aa572a-60fe-4243-9f11-7468ace7cca1)
![image](https://github.com/remix-run/react-router/assets/62570796/06a5d476-ade9-465d-b829-602d9cd34755)

**Comment by TimVerheul** [comment]
Also having this issue. Not sure why it is closed. 173kb router.js file which I can't seem to get splitted

**Comment by orbachar** [comment]
It’s getting worse in React Router v7 😕, I just upgraded from v5 to v7, and the bundle size increased by 50KB (gzipped)!

**Comment by neoncube2** [comment]
@timdorr Please reopen. Although tree shaking is a bundler feature, NPM modules have to export and architect their code in a way that's tree shakable, and it seems that `react-router` may not be doing that :)

Updating `react-router` from 7.5 to 7.7 increased minified bundle size by more than 150KB, which is crazy! XD

**Comment by neoncube2** [comment]
@timdorr Here's an example! :)

`<Link>` references `<PrefetchPageLinks>` [here](https://github.com/remix-run/react-router/blob/35718a35725627fd9fcfbd60199b50b70db9490d/packages/react-router/lib/dom/lib.tsx#L701C1-L701C5), which calls `useDataRouterContext()` [here](https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/dom/ssr/components.tsx#L292), so all of `DataRouterContext` as well as the error message `"You must render this element inside a <DataRouterContext.Provider> element"` are not eligible for tree-shaking (since they're being referenced).

This leads to code like this being included in my production bundle, even though I'm not using the data loader:

```js
var I=r.createContext(null);I.displayName="DataRouter";var D=r.createContext(null);D.displayName="DataRouterState";var F=r.createContext({isTransitioning:!1});F.displayName="ViewTransition",r.createContext(new Map).displayName="Fetchers",r.createContext(null).displayName="Await";var U=r.createContext(null);U.displayName="Navigation";var $=r.createContext(null);$.displayName="Location";var B=r.createContext({outlet:null,matches:[],isDataRoute:!1});B.displayName="Route";var H=r.createContext(null);H.displayName="RouteError";

....

function Ce(){let e=r.useContext(D);return be(e,"You must render this element inside a <DataRouterStateContext.Provider> element"),e}r.Component;var xe=r.createContext(void 0);function Re(){let e=r.useContext(xe);return be(e,"You must render this element inside a <HydratedRouter> element"),e}function Te(e,t){return n=>{e&&e(n),n.defaultPrevented||t(n)}}function Oe({page:e,...t}){let{router:n}=ke(),a=r.useMemo((()=>d(n.routes,e,n.basename)),[n.routes,e,n.basename]);return a?r.createElement(Le,{page:e,matches:a,...t}):null}function Ne(e){let{manifest:t,routeModules:n}=Re(),[a,o]=r.useState([]);return r.useEffect((()=>{let r=!1;return async function(e,t,n){return function(e,t){let n=new Set,r=new Set(t);return e.reduce(((e,a)=>{if(t&&(null==(o=a)||"string"!=typeof o.page)&&"script"===a.as&&a.href&&r.has(a.href))return e;var o;let i=JSON.stringify(function(e){let t={},n=Object.keys(e).sort();for(let r of n)t[r]=e[r];return t}(a));return n.has(i)||(n.add(i),e.push({key:i,link:a})),e}),[])}((await Promise.all(e.map((async e=>{let r=t.routes[e.route.id];if(r){let e=await async function(e,t){if(e.id in t)return t[e.id];try{let n=await import(e.module);return t[e.id]=n,n}catch(t){return console.error(`Error loading route module \`${e.module}\`, reloading page...`),console.error(t),window.__reactRouterContext&&window.__reactRouterContext.isSpaMode,window.location.reload(),new Promise((()=>{}))}}(r,n);return e.links?e.links():[]}return[]})))).flat(1).filter(we).filter((e=>"stylesheet"===e.rel||"preload"===e.rel)).map((e=>"stylesheet"===e.rel?{...e,rel:"prefetch",as:"style"}:{...e,rel:"prefetch"})))}(e,t,n).then((e=>{r||o(e)})),()=>{r=!0}}),[e,t,n]),a}function Le({page:e,matches:t,...n}){let a=W(),{manifest:o,routeModules:i}=Re(),{basename:l}=ke(),{loaderData:s,matches:u}=Ce(),c=r.useMemo((()=>Ee(e,t,u,o,a,"data")),[e,t,u,o,a]),f=r.useMemo((()=>Ee(e,t,u,o,a,"assets")),[e,t,u,o,a]),d=r.useMemo((()=>{if(e===a.pathname+a.search+a.hash)return[]

...
```

**Comment by neoncube2** [comment]
I've opened a new issue for the `<Link>` issue, specifically: https://github.com/remix-run/react-router/issues/14058 :)
