### ISSUE TITLE
[Bug]: createMemoryRouter does not handle a redirect returned from a route action

### ISSUE THREAD

**Issue by jvnlwn** [remix-run/react-router#10375]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I didn't realize there was a StackBlitz starter before creating this example on CodeSandbox:
https://codesandbox.io/s/react-router-dom-membory-router-bug-u20cjd?file=/src/RouteElement.test.jsx

Also, I apologize if this is user error on my part. Thanks!

There are two tests:
  1. "memory router updates location after <Link /> click" – _passing_
  2. "memory router updates location after action redirect" – _failing_

The first test is a sanity check to make sure the second test should actually expect to pass. There's a simple browser router setup that you can manually interact with to verify the UI behavior.

There are two ways of navigating the app:
  1. By clicking the "Link" <Link />
  2. By clicking the "Submit" <Button />

Both will navigate you from "/" to "/home". The latter does so by returning a redirect from the "/" route action.

The passing test proves that the first UX flow works. The failing test proves that the second UX flow fails (but only when testing).

### Expected Behavior

When testing a [`createMemoryRouter`](https://reactrouter.com/en/main/routers/create-memory-router#creatememoryrouter) router a [`redirect`](https://reactrouter.com/en/main/fetch/redirect#redirect) returned from a route [`action`](https://reactrouter.com/en/main/route/action#action) should result in the router navigating to the redirect url.

### Actual Behavior

No navigation occurs.

**Comment by brophdawg11** [comment]
This is usually due to the test environment (node) not having `fetch` API polyfilled (or being polyfilled in a [non-spec-compliant way](https://github.com/remix-run/react-router/issues/9722)) so your returned `Response` isn't properly identified.  Here's how we do it for our own unit tests: https://github.com/remix-run/react-router/blob/main/packages/react-router/__tests__/setup.ts.

Try polyfilling from `@remix-run/web-fetch` and please re-open this issue if that doesn't solve the problem!

**Comment by jvnlwn** [comment]
@brophdawg11 thanks for the helpful and quick feedback!

Here's what I've found. In the CodeSandbox test, I wasn't actually able to add the workaround due to the error:

```'globalThis' is not defined```

I tried resolving that but didn't get far.

So, I used the CodeBlitz starter and was able to add the same test scenario: https://stackblitz.com/edit/github-eufygg?file=setup.ts

This time I had difficulty setting up testing with `jest` in that starter so I went with `vitest`. Without the workaround, actually _both_ tests fail:

```ReferenceError: Request is not defined```

 With the workaround both tests pass. You can simply comment out the `setupFetch()` call to get the tests to fail.

Though, in a private repo where I initially experienced the issue I am also testing with `jest`. It's a [`craco`](https://github.com/dilanx/craco) repo and seems to already be polyfilling `fetch`. If I add the workaround and just overwrite `fetch`, etc. regardless if `fetch` already exists, the issue still occurs. There seems to be no difference.

I've even added the same router tests from my examples to my private repo just to be sure and there is also no difference in that case.

Hope that helps.

**Comment by brophdawg11** [comment]
I'm not familiar with `craco` but if it's a wrapper around CRA then you may be running into the fact that it uses a non-spec-compliant `fetch` polyfill: https://github.com/facebook/create-react-app/issues/12913 (created from https://github.com/remix-run/react-router/issues/9722).

**Comment by jvnlwn** [comment]
Got it working with your [unit test polyfill](https://github.com/remix-run/react-router/blob/main/packages/react-router/__tests__/setup.ts.).

Since `craco` provides a way to override CRA options, I did the following:

```javascript
// craco.config.js

module.exports = {
  webpack: {/*...*/},
  jest: {
    configure: config => {
      // Prevent create-react-app from polyfilling fetch: https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-scripts/scripts/utils/createJestConfig.js#L33
      config.setupFiles = []
      return config
    }
  }
}
```

Thanks again @brophdawg11!
