### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by MJCoder15** [remix-run/react-router#10370]
## useLocation hook in react-router website needs a little more description in deep that what it does

- **I was learning useLocation hook through a tutorial and I went to check what official docs are saying and I found out that there is not much information provided for useLocation hook**

- here's the link of that webpage: [https://reactrouter.com/en/main/hooks/use-location](https://reactrouter.com/en/main/hooks/use-location)

**Image:-**

![image](https://user-images.githubusercontent.com/91000828/232974433-92fa3847-4b11-41c9-9861-0943b8c79d39.png)

**Comment by timdorr** [comment]
This is just the reference doc for the API. It's not meant to be exhaustive in the description. The concept of a location is described elsewhere.

**Comment by MJCoder15** [comment]
OK thanks for providing Info
