### ISSUE TITLE
[Bug]: State of window.location is different from useLocation when using navigate inside async function with react-dom 17 render

### ISSUE THREAD

**Issue by frolad** [remix-run/react-router#10391]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Here is a simple code example:

```js
import ReactDOM from "react-dom";
import {
  RouterProvider,
  createBrowserRouter,
  useNavigate,
  useLocation,
} from "react-router-dom";

function Landing() {
  const navigate = useNavigate();

  async function openAbout(e) {
    e.preventDefault();

    await fetch("https://catfact.ninja/fact");
    navigate("/about");
  }

  return (
    <div>
      <h1>Landing</h1>
      <a href="/landing" onClick={openAbout}>
        about
      </a>
    </div>
  );
}

function About() {
  const navigate = useNavigate();
  const location = useLocation();

  console.log(
    `WINDOW: ${window.location.pathname + window.location.search}`,
    `ROUTER: ${location.pathname + location.search}`
  );

  return (
    <div>
      <h1>About</h1>
      <a
        href="/landing"
        onClick={(e) => {
          e.preventDefault();
          navigate("/");
        }}
      >
        back
      </a>
    </div>
  );
}

const router = createBrowserRouter([
  {
    path: "/",
    element: <Landing />,
  },
  {
    path: "about",
    element: <About />,
  },
]);

ReactDOM.render(
  <RouterProvider router={router} />,
  document.getElementById("root")
);
```

package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.24",
    "@types/react": "^18.0.38",
    "@types/react-dom": "^18.0.11",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.10.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

react-dom version is 18 but rendering is done with the old render method. Clicking "about" from the landing page first fetches an API and then navigates to /about (real world example would be custom form submissions or something similar which would require an API call before the navigation).

On the about page there are 2 console logs for the state of window.location and location from useLocation. With this example the state for window.location is different (still landing page) from useLocation on the first render of About component. If I remove `await fetch` then window.location will be the same as useLocation.

It works as expected if I change the render method to react-dom 18.

Using useLocation everywhere is a solution but it won't help with 3rd-party/old components. For example some components may use window.location inside initial react ref state or even as a variable before render to extract variable from the search string.

### Expected Behavior

After opening home page and clicking "about" in the console you should see
```
WINDOW: /about
ROUTER: /about
```
and window.location should point to about page

### Actual Behavior

After opening home page and clicking "about" in the console you see
```
WINDOW: /
ROUTER: /about
```

so the state of window.location is still pointing to the landing page even though the About component is already rendered.

**Comment by EricLiam94** [comment]
If you use old way to define routes, it works as expected,
![image](https://github.com/user-attachments/assets/9bb4b490-0dd1-4061-b1b0-32d5a0cc11ad)
