### ISSUE TITLE
[Bug]: Not able to manually manipulate route state outside of react router

### ISSUE THREAD

**Issue by xsjcTony** [remix-run/react-router#10428]
### What version of React Router are you using?

v6.11.0

### Steps to Reproduce

Sorry if this is not a bug, but I can't really find a way to manipulate the route state without using functions provided by React Router, seems like React Router is using its own route state management system instead of reading from the native `window.history.state`.

I'm wondering whether we have a way to manipulate the route state in some other environment, e.g. I'm using `Cypress` to test my website.

My certain page requires some route state otherwise it's going to throw some error, so that's what I'm trying to do in my `Cypress` test:
```ts
describe('1', () => {
  it('2', () => {
    cy.visit('/test', {
      onBeforeLoad(window) {
        window.history.pushState(
          {
            customer_id: 123,
            hash: '123'
          },
          ''
        );
      }
    });
  });
});
```
And in the react component I have:
```tsx
const routeState = useLocation().state;
console.log(`React router's state: `, routeState);
console.log(`window.history.state: `, window.history.state);
```
Which results in this:
![image](https://user-images.githubusercontent.com/45784210/235556585-22780b27-ff8b-4568-8504-e268a0c981cc.png)
Hence my test can't perform as I expected.

Is their anyway to workaround this?

### Expected Behavior

Route State should be updated if `window.history.pushState` is called.

### Actual Behavior

They are not synced.

**Comment by brophdawg11** [comment]
React Router provides a small wrapper on top of the built-in history state and generally speaking you should do everything via react router.  I would probably attempt to have your Cypress test click a `<Link to="." state={...} replace>` to set state the same way as it would be set if a user was navigating the app.

But if you want to set it manually, you'll need to push a `state` object that aligns with the internal structure react router uses:

```
{
  idx: number, // starts with 0 and increments with each push
  key: string, // starts with 'default'
  usr: any, // This is the state exposed via useLocation()
}
```

**Comment by xsjcTony** [comment]
@brophdawg11 Thanks for the reply, but since I'm doing E2E tests with real code on dev server, so I'm afraid it's impossible for me to manually add a `<Link>` component to simulate it.

And for the second solution, I'm not quite getting it. Since no matter what I push to `window.history`, seems like it won't be picked up by react router by any chance?

**Comment by brophdawg11** [comment]
You need to push it in the proper format to RR picks it up:

**App:**
```jsx
import {
  useLocation,
  createBrowserRouter,
  RouterProvider,
} from "react-router-dom";

let router = createBrowserRouter([
  {
    path: "/",
    Component() {
      let { state } = useLocation();
      return (
        <>
          <h2>Home</h2>
          <p>{JSON.stringify(state)}</p>
        </>
      );
    },
  },
]);

export default function App() {
  return <RouterProvider router={router} />;
}
```

**Cypress:**

```js
describe("template spec", () => {
  it("passes", () => {
    cy.visit("http://localhost:5173", {
      onBeforeLoad(window) {
        window.history.pushState(
          {
            idx: 0,
            key: "default",
            usr: { customer_id: 123, hash: "123" },
          },
          ""
        );
      },
    });
    cy.contains("Home");
    cy.contains('"customer_id":123');
    cy.contains('"hash":"123"');
  });
});
```

**Comment by lake2** [comment]
> React Router provides a small wrapper on top of the built-in history state and generally speaking, you should do everything via react-router. I would probably attempt to have your Cypress test click a `<Link to="." state={...} replace>` to set state the same way as it would be set if a user was navigating the app.
> 
> But if you want to set it manually, you'll need to push a `state` object that aligns with the internal structure react router uses:
> 
> ```
> {
>   idx: number, // starts with 0 and increments with each push
>   key: string, // starts with 'default'
>   usr: any, // This is the state exposed via useLocation()
> }
> ```

This may be a problem when the page has multiple web framework instances.
For instance, there are two root elements on the page:

```html
<div id='vue'></div>
<div id='react'></div>
```
The vue mount on the `vue` node and React mount on the `react` node.
The expected behavior is to use general `window.history.pushState` to navigate in these two nodes.
However, `window.history.pushState` is not working on v6.
This is prevalent in the micro-frontend scene.

**Comment by het0** [comment]
@lake2 getting exactly the problem when trying to integrate project that uses react-router into my next.js project. Because both react-router and router from next using some additional state I can't seems to make them work together. Trying to make them work together with no luck :(

`  useIsomorphicLayoutEffect(() => {
    const replaceState = globalThis?.history?.replaceState;
    const pushState = globalThis?.history?.pushState;

    const prepareArguments = (type: string, ...args: any[]) => {
      const incomeState = args[0] ?? {};
      const existingState = globalThis?.history?.state ?? {};
      const isInitiatedByNext = (incomeState.__N === true);
      const url = args[2] ?? window.location.pathname;
      // Keeping next route state
      const newState = {
        ...existingState,
        ...incomeState,
        __N: isInitiatedByNext,
      };

      // If initiated by next router - just pass it through
      if (isInitiatedByNext && type === 'push') {
        if (typeof newState.idx !== 'number') {
          newState.idx = 0;
        } else if (typeof newState.idx === 'number') {
          newState.idx++;
        }
        newState.key = 'default';
      }

      // Forcing all react-routing-dom app routes to be "shallow", because we don't use ssr on those pages
      newState.options = Object.assign(newState.options ?? {}, { shallow: true });
      // We need to replace "as" parameter to support back and forward actions
      newState.as = newState.as ? url : newState.as;
      return [newState, ...args.slice(1)];
    };

    if (replaceState) {
      history.replaceState = function (...args: any[]) {
        replaceState.apply(history, prepareArguments('replace', ...args));
      };
    }
    if (pushState) {
      history.pushState = function (...args: any[]) {
        pushState.apply(history, prepareArguments('push', ...args));
      };
    }

    return () => {
      if (replaceState) {
        history.replaceState = replaceState;
      }
      if (pushState) {
        history.pushState = pushState;
      }
    };
  }, []);`
