### ISSUE TITLE
[Docs]: Insufficient info on useLocation() 

### ISSUE THREAD

**Issue by serapieTuyishime** [remix-run/react-router#10449]
### Describe what's incorrect/missing in the documentation

https://reactrouter.com/en/main/hooks/use-location.

I feell that there should be more examples on how to use it. And maybe return types for typescript users

**Comment by timdorr** [comment]
The return type is listed at the top if you expand the Type Definition section. 

There are plenty of examples of use elsewhere in the docs. This is just a reference page, so it's intentionally minimal. If you want to see improvements made to the docs, please submit a PR.
