### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by arizakevin** [remix-run/react-router#10445]
### What version of React Router are you using?

react-router-dom: "6.2.1"

### Steps to Reproduce

Just import `redirect` on any react project where `react-router-dom` 6.2.1 is installed:

`import { redirect } from "react-router";`

I did this as explained in the docs: https://reactrouter.com/en/main/fetch/redirect

### Expected Behavior

The `redirect` function should be exported from `react-router-dom` so it can be used for redirecting to another route.

### Actual Behavior

Got the following error:

```none
export 'redirect' (imported as 'redirect') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, renderMatches, resolvePath, unstable_HistoryRouter, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams)
```

![react-router-dom redirect not working](https://user-images.githubusercontent.com/56013162/236096673-720abe7e-f1fb-4a99-98b8-e1d2cca15f4c.png)

**Comment by arlendp** [comment]
`redirect` is supported in `react-router-dom` >= 6.4.0, just upgrade it

**Comment by timdorr** [comment]
Correct. This was added in later versions, as it only applies to data routers.
