### ISSUE TITLE
[Bug]: loader not functional when used in useRoutes (v6.11.1)

### ISSUE THREAD

**Issue by victorcodex** [remix-run/react-router#10459]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

loader not functional when used in useRoutes (v6.11.1)

Example

```
function App() {

  let element = useRoutes([
    {
      path: "/",
      element: <Dashboard />,
      loader: async ({ request, params }: LoaderFunctionArgs) => {
         console.log('useRoutes log', { params }); --> This does not get printed in the browser's console
         return fakeDb.from("teams").select("*");
      },
      children: [
        {
          path: "messages",
          element: <DashboardMessages />,
        },
        { path: "tasks", element: <DashboardTasks /> },
      ],
    },
    { path: "team", element: <AboutPage /> },
  ]);

  return element;
}
```

### Expected Behavior

I would expect to see the loader function executed when called in a `useRoutes`;

### Actual Behavior

Loader not functional when used in `useRoutes`

**Comment by timdorr** [comment]
`useRoutes` is connected to the legacy Router components, not the new data routers. It doesn't participate in data loading.
