### ISSUE TITLE
[Bug]: useEffect not trigger first

### ISSUE THREAD

**Issue by TobiasFriberg** [remix-run/react-router#10454]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

I believe the following is a bug.

I have a view, that contains an error if a variable is not set, so, naturally I want to check if the variable is set before I render the router.

Anyway, the code-example will work as long as there is not an error in `<MyView />`. I believe that the `useEffect` should trigger before the router renders, yes, no?

```
const MyView = () => {
  return <div>{StuffThatDoesNotExist}</div>;
};

export const Router = () => {
  useEffect(() => {
    console.log('This will not trigger');
  }, []);

  return (
    <HashRouter>
        <Routes>
          <Route index element={<MyView />} />
       </Routes>
    </HashRouter>
  );
};
```

### Expected Behavior

`useEffect` should run first

### Actual Behavior

`useEffect` does not run first

**Comment by timdorr** [comment]
This has nothing to do with React Router. How `useEffect` operates is a React concern and we have no ability to control or alter its behavior.
