### ISSUE TITLE
[Bug]: Basename is duplicated in nested routes

### ISSUE THREAD

**Issue by fkaempfer** [remix-run/react-router#10467]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

This seems similar to https://github.com/remix-run/react-router/issues/10431 , but I'm unsure whether this is a regression, since I only recently switched to vite.

In particular scenarios with nested routes it happens that the basename is duplicated. I managed to create an example here:
https://stackblitz.com/edit/github-cjtxux?file=src/App.tsx
https://githubcjtxux-uvj1--5173--9c984a48.local-corp.webcontainer.io/test/test/dashboard

* Click on Dashboard -> Dashboard is loaded fine
* Click on About which contains a nested route to dashboard
* Click on Dashboard link on the bottom -> Dashboard link is not resolved (Nothing to see here), the URL contains the basename twice (/test/test/dashboard)

### Expected Behavior

Clicking the link on the about page should load the dashboard page

### Actual Behavior

Clicking the link on the about page loads the 404 page

**Comment by nonameolsson** [comment]
I can agree with this bug report. The same behaviour is happening for us.

**Comment by brophdawg11** [comment]
Thanks for the reproduction @fkaempfer!  This does look like a regression in 6.11.1 so we'll get a fix out in a patch release soon.

**Comment by hasan-wajahat** [comment]
I also saw this issue in our project. But this is introduced only in 6.11, it worked as expected when I downgraded to 6.10.

**Comment by brophdawg11** [comment]
This is fixed by #10492 and will be available once 6.11.2 is released 👍

**Comment by fkaempfer** [comment]
Thanks, it seems to fix the issue in my app.
