### ISSUE TITLE
[Bug]: assigning ref on Form inside useFetcher does not assign ref

### ISSUE THREAD

**Issue by welpie21** [remix-run/react-router#10470]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

```tsx
const component = (props: any) => {
      const form = useRef<HTMLFormElement>(null);
      const fetch = useFetcher();
      
      console.log(form);
      
      return (
          <fetch.Form ref={form}>
                ...
          </fetch.Form>
      );
}
```

### Expected Behavior

Ref should be assigned a HTMLFormElement and not be null

### Actual Behavior

Ref is assigned as "null".

printed in console.log on my end:
```
{ current: null }
```

**Comment by timdorr** [comment]
That should be null at that point. You're inspecting the `form` variable before it's even passed to the Form component, let alone when it's assigned by `React.forwardRef`. On your next render, `form.current` will be set as expected.
