### ISSUE TITLE
[Bug]: The ":id?" syntax above version 6.11.1 is not supported in the production environment

### ISSUE THREAD

**Issue by huangjihua** [remix-run/react-router#10484]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

```jsx
  <Route path="*" element={<div>******</div>} /> 
  <Route path="/:b/:b/:c?" element={<div>test</div>} /> 
```

### Expected Behavior

http://localhost:5173/csd/1   => test
http://localhost:5173/csd/1/1   => test

Both URL access result pages should be test.

### Actual Behavior

![image](https://github.com/remix-run/react-router/assets/3156292/4dc3ca5a-71b9-4752-8352-f1b254703be5)

**Comment by timdorr** [comment]
If you have your wildcard route before the optional route, it will get priority.
