### ISSUE TITLE
[Bug]: I can't go back (navigation(-1, { state: props })) updating props

### ISSUE THREAD

**Issue by Alpacora** [remix-run/react-router#10487]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

Page1:
 navigation('page2', { state: propsV1 })

Page2:
  const propsV1 = useLocation().state;
  navigation('page3', { state: propsV1 })

Page3:
  const propsV1 = useLocation().state;
  const propsV2 = {
    ...propsV1,
    name: 'John Doe'
  }

 navigation(-1, { state: propsV2 })

### Expected Behavior

it is expected that when returning from page3 to page2 the useLocation of page2 will receive the new updated props (propsV2) that were sent in the "goBack" of page3

### Actual Behavior

The current behavior is that page2 continues to receive the old properties, when I navigate navigation(-1, {state: props }) it is not passing the new props.

I can't navigate to the previous page updating the props with the new values ​​example:
navigation(-1, {state: props })

Does anyone have any suggestions?

**Comment by Alpacora** [comment]
Ok buddy, so it's possible to remove some route from stack? Example: 

Before Stack: page1 -> page2 ->page3
After Stack: page1 -> page3

**Comment by kiliman** [comment]
When you navigate, either via `Link` or `useNavigate`, you can pass `replace: true` to replace the current stack entry with the new location.

https://reactrouter.com/en/main/components/link#replace
https://reactrouter.com/en/main/hooks/use-navigate
