### ISSUE TITLE
Errors building with browserify / watchify (0.3.4)

### ISSUE THREAD

**Issue by JedWatson** [remix-run/react-router#105]
I'm getting the following errors when building with gulp and browserify / watchify:

```
[13:32:43] Browserify Error [Error: Cannot find module 'browserify-shim' from 'project/node_modules/react-nested-router']
[13:32:43] Browserify Error [Error: Cannot find module 'envify' from 'project/node_modules/react-nested-router']
```

(clipped project path for brevity)

I've got both `react` and `react-nested-router` declared in my main `package.json` file:

```
    "react": "^0.11.0",
    "react-nested-router": "^0.3.4",
```

The issue seems to be that `npm install` doesn't install the `devDependencies` from modules, only the main `package.json`.

To resolve it I can either (a) run `node install` from my project's `/node_modules/react-nested-router` folder, or (b) declare `envify` and `browserify-shim` as `devDependencies` in my main `package.json` (this creates a version conflict though as react wants `"envify": "^2.0.0"` and the router wants `"envify": "~1.2.0"`)

React declares `envify` as a normal (not dev) dependency:

```
  "dependencies": {
    "envify": "^2.0.0"
  }
```

... which works fine, perhaps `react-nested-router` could do the same with `envify` and `browserify-shim`?

**Comment by imawuman** [comment]
@mjackson I'm getting errors when running browserify rails in the form:
```
BrowserifyRails::BrowserifyError: Error while running `/home/ubuntu/proj/node_modules/.bin/browserifyinc -t babelify --extension ".js" --fast --list --cachefile=/home/ubuntu/proj/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/ubuntu/proj/tmp/cache/browserify-rails/output20170316-14582-lmi4l7" -`:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'loose-envify' from '/home/ubuntu/proj/node_modules/react-router-dom'
```
is this related issue and/or do you know what i'm missing? thanks!
