### ISSUE TITLE
[Docs]: In tutorial, importing the component <Route> is missing 

### ISSUE THREAD

**Issue by mung3477** [remix-run/react-router#10508]
### Describe what's incorrect/missing in the documentation

Hello, I was following the tutorial in the documentation, and there was a minor error.
[link](https://reactrouter.com/en/main/start/tutorial#jsx-routes) is missing the import statement of component <Route>.

Or is it some grammatical sugar that I didn't know? If it is, sorry for the unnecessary issue😉

**Comment by sash9696** [comment]
Hi @brophdawg11 , I would like to work on this issue. It would be of great help if you could assign it .
