### ISSUE TITLE
🗺️ switch to `startTransition`

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#10501]
@gaearon put me in a headlock at RemixConf and wouldn't let go until I agreed to do this, as well as pay for his pizza.

- Original Issue: https://github.com/remix-run/remix/issues/5763
- PR: #10438

**Comment by brophdawg11** [comment]
Merged in #10438 and should be available when 6.12.0 is released

**Comment by bug-brain** [comment]
`flushSync` does no longer work when `navigate` uses `startTransition`. What would be the recommended way to prevent renders while states (location and some other React state) are inconsistent?

**Comment by brophdawg11** [comment]
[`6.13.0`](https://github.com/remix-run/react-router/releases/tag/react-router%406.13.0) moved the usage of `startTransition` behind a future flag so you can upgrade to 6.13 to avoid the usage of `startTransition` and then opt in when your application is compatible.
