### ISSUE TITLE
[Bug]:  Scroll Restoration seems flaky in 6.11.2

### ISSUE THREAD

**Issue by fetters5** [remix-run/react-router#10511]
### What version of React Router are you using?

6.11.2

### Steps to Reproduce

If you hit refresh on the sample page without a loader it will sometimes maintain scroll position and other times it will revert back to the top 

The link with the loader seems to work everytime. 

demo https://stackblitz.com/edit/github-o9lrzh?file=src%2Fapp.tsx 

This did not seem to occur in 6.10.0 and when I revert the package in stackblitz the page with no loader seems to maintain scroll position

### Expected Behavior

Maintain scroll position on pages without loaders

### Actual Behavior

Doesnt maintain position consistently

**Comment by timdorr** [comment]
I'm not seeing any case where it doesn't restore scroll position, even after refreshing a few dozen times. This may be a browser extension interfering.

**Comment by fetters5** [comment]
@timdorr I've had two other people try it across multiple browsers with the same issue extensions on and off, can you tell me what browser you were using so I can try that browser to see if I can replicate on that
