### ISSUE TITLE
[Bug]: 'TypeScript error: Property or signature expected' in @remix-run/router/dist/router.d.ts

### ISSUE THREAD

**Issue by leedsrising** [remix-run/react-router#10523]
### What version of React Router are you using?

1.6.2

### Steps to Reproduce

I've just npm installed remix router

looks like this line is the issue

```
    12 |      * Return the basename for the router
    13 |      */
  > 14 |     get basename(): RouterInit["basename"];
       |     ^
    15 |     /**
    16 |      * @internal
    17 |      * PRIVATE - DO NOT USE
```
### Expected Behavior

Should not see this error. Am not even using remix router in my app.

### Actual Behavior

seeing this error
```
/Desktop/mysimpleco/node_modules/@remix-run/router/dist/router.d.ts
TypeScript error: Property or signature expected.  TS1131

    12 |      * Return the basename for the router
    13 |      */
  > 14 |     get basename(): RouterInit["basename"];
       |     ^
    15 |     /**
    16 |      * @internal
    17 |      * PRIVATE - DO NOT USE
```

**Comment by timdorr** [comment]
You shouldn't be installing this package directly; it is an internal dependency that is managed for you. Install `react-router` or `react-router-dom` to use the library and be importing only from those modules.

**Comment by mohak54e** [comment]
> You shouldn't be installing this package directly; it is an internal dependency that is managed for you. Install `react-router` or `react-router-dom` to use the library and be importing only from those modules.

even without installing externally, getting the same exact issue. 
- React / React-dom => 17
- react-router / react-router-dom => 6.21.0

**Comment by varunutreja** [comment]
I'm getting this error too. Is there any working solution to this? Thanks.

**Comment by newtypeid** [comment]
I solved this issue. my typescript version was 4.2.1. but, the minimum typescript version is 4.3.2. upgrade your typescript version.
