### ISSUE TITLE
[Bug]: router will fail when keyword "data" is used on the path 

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [remix-run/react-router#10520]
### What version of React Router are you using?

6.10

### Steps to Reproduce

- basic implementation of react-router with BrowserRouter
- add "data" on your keyword like 'pathtogo/data' 
- even though we have configured 'pathtogo' parameter or path data will fail with message "Sorry can't find that!"
- happens only on reload or bacward navigation using browser 

### Expected Behavior

Navigate to router 

### Actual Behavior

fail with "Sorry can't find that!"

**Comment by timdorr** [comment]
Can you provide a reproduction of this? We don't have specific handling for keywords. There may be an invalid path pattern you're using.

**Comment by EsmeraldiBejolli** [comment]
```
const  route = createBrowserRouter([
    {
        path: "/",
        element: <Home/>
    },
 
    { 
        path: '/search/:term',
        element: <Search />,
    }
}
```

this is my router and it works when I navigate to router with the path `search/data` but when I reload it will fail , the samme will happen if I navigate to another path and click on browser back button

**Comment by EsmeraldiBejolli** [comment]
the issue is not on readct-router but on my rollup. thanks for quick response @timdorr
