### ISSUE TITLE
[Bug]: navigation is not working properly with(useNavigate) after the page reload.

### ISSUE THREAD

**Issue by DhineshMinnal** [remix-run/react-router#10544]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

Open a app which using react router dom version 6.4.0 or later. Randomly move to different routes Then refresh the page now click browser back button. Now it navigates to the route that does not belong react app(the route previous to react app)

### Expected Behavior

Open a app which using react router dom version 6.4.0 or later. Randomly move to different routes Then refresh the page now click browser back button. Now it should navigate to previous route

### Actual Behavior

- Open a app which using react router dom version 6.4.0 or later. 
- Randomly move to different routes 
- Then refresh the page now click browser back button. 
- Now it navigates to the route that does not belong react app(the route previous to react app)

**Comment by timdorr** [comment]
Without a reproduction of this, it's impossible to know exactly what's going on here. My best guess is you're using a MemoryRouter, which doesn't store navigation entries in the browser stack and will be erased on page reload.

But this is definitely something supported, so it's very unlikely to be a bug with the library itself.

**Comment by crossa** [comment]
I've meet the issue on my project these days
When I use `createBrowserRouter` to create the routes,`navigate()` would take no effect after page reloaded .
But when I  use `createHashRouter` to create the routes,  it has different  behavior. 
`navigate()` would take no effect after page reloaded  but if I reload the page with same url again, the page would be correct one.

Here's the related information.

 "react": "^18.2.0",
 "react-dom": "^18.2.0",
 "react-router-dom": "^6.21.1",
