### ISSUE TITLE
[Bug]: Switch does not exclusively render the first matched Route/Redirect.

### ISSUE THREAD

**Issue by nullromo** [remix-run/react-router#10551]
### What version of React Router are you using?

5.3.4

### Steps to Reproduce

Put routes and redirects in the same switch, like this:

```jsx
<Switch>
    <Route exact={true} path='/page1' >
        <Page1 />
    </Route>
    <Route exact={true} path='/page2' >
        <Page2 />
    </Route>
    <Route exact={true} path='/home' >
        <Home />
    </Route>
    <Redirect path='/' to='/home' />
</Switch>
```

Then try entering `http://localhost:3000/page2` in the web browser.

### Expected Behavior

The [documentation for \<Switch\>](https://v5.reactrouter.com/core/api/Switch) says "Renders the first child that matches the location." It also mentions "Only the first child to match the current location will be rendered." Based on this, I expect the first route to be matched, and a `<Page1>` component should be rendered. The `<Redirect>` matches, but it's not the first match so it should not be rendered. The `<Redirect>` is supposed to act as a fallback for when none of the other routes matched. That's the whole point of the `<Switch>` here.

### Actual Behavior

When I go to `http://localhost:3000/page2`, I get redirected to `http://localhost:3001/home` because of the `<Redirect>`, even though the `<Redirect>` is not the first match in the `<Switch>`.

**Comment by nullromo** [comment]
For anyone else with this issue, I implemented a workaround. I use the `render` function version of `Route` and check the `props.location.pathname` against all my other routes. If it didn't match anything, then I return a `<Redirect>`, otherwise I just return `null`.

```jsx
enum MyPaths {
    PAGE_1 = '/page1',
    PAGE_2  = '/page2',
    HOME = '/home',
}

<Switch>
    <Route exact={true} path={MyPaths.PAGE_1} ><Page1 /></Route>
    <Route exact={true} path={MyPaths.PAGE_2} ><Page2 /></Route>
    <Route exact={true} path={MyPaths.HOME} ><Home /></Route>
    <Route path='/' render={(props: RouteComponentProps) => {
        if ((Object.values(MyPaths) as string[]).includes(props.location.pathname)) {
            return null;
        }
        return <Redirect to='/home' />
    }} />
</Switch>
```

Even though the `'/'` `<Route>` shouldn't get rendered because of the `<Switch>`, I can still have a working solution. That route gets rendered, and I just conditionally render the `<Redirect>` component based on the path. It's not ideal since I'm basically just re-implementing the functionality that the `<Switch>` was supposed to have in the first place, but at least it works.

**Comment by timdorr** [comment]
Unless you can reproduce this for us on StackBlitz or CodeSandbox, I think something is going on with your app setup. This definitely works, as we have this example that uses Redirect just fine: https://github.com/remix-run/react-router/blob/v5/packages/react-router-dom/examples/NoMatch.js

**Comment by nullromo** [comment]
I found out what the problem was. Again, the documentation states that a `<Switch>`

> "Renders the first child `<Route>` or `<Redirect>` that matches the location."

However, what it really means is that it

> "Renders all children up to and including the first child `<Route>` or `<Redirect>` that matches the location."

In other words, a `<Switch>` will unconditionally render all of it's children that are placed before the first match. Furthermore, the children of those children will be unconditionally rendered as well. I found out that my code actually looked like this:

```jsx

// This is the problematic component
const MyComponent = (props: React.PropsWithChildren<{}>) => {
    return <>{props.children}</>;
};

export const App = () => {
    return (
        <Router>
            <Switch>
                {/* Wrapping the routes in a parent component
                causes them all to be rendered. The <Switch>
                does not perform a "deep scan" for conditional
                rendering */}
                <MyComponent>
                    <Route exact={true} path='/page1'>
                        <Page1 />
                    </Route>
                    <Route exact={true} path='/page2'>
                        <Page2 />
                    </Route>
                    <Route exact={true} path='/home'>
                        <Home />
                    </Route>
                    <Redirect path='/' to='/home' />
                </MyComponent>
            </Switch>
        </Router>
    );
};
```

So what happens here is that the `<MyComponent>` gets rendered no matter what, and the `<Switch>` is doing nothing here because none of the `<Route>`s or `<Redirect>`s are direct children of the `<Switch>`.

The documentation also says

> "All children of a `<Switch>` should be `<Route>` or `<Redirect>` elements. Only the first child to match the current location will be rendered."

which is almost true, but not quite.

Anyway, the tl;dr is make sure the `<Route>` and `<Redirect>` components are **direct** children of the `<Switch>` if you want the `<Switch>` to do its job.
