### ISSUE TITLE
[Docs]: StackBlitz examples fail due to missing dependency

### ISSUE THREAD

**Issue by JosephLandy** [remix-run/react-router#10559]
### Describe what's incorrect/missing in the documentation

Small issue, but I didn't see any other reports. The examples on StackBlitz linked to in the documentation (https://reactrouter.com/en/main/start/examples) are failing to run due to a missing dependency "@esbuild/linux-x64".

> failed to load config from /home/projects/aonimgbzl.github/vite.config.ts
error when starting dev server:
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.

Running `npm i -D @esbuild/linux-x64` in the StackBlitz console followed by `npm run dev` fixed it. 

I tried out three examples, and it happened on all of them:

- [Modal](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/modal?file=src%2FApp.tsx)
- [Data Router](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/data-router?file=README.md)
- [Navigation Blocking](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/navigation-blocking?file=README.md)

Thanks!

**Comment by timdorr** [comment]
I just fixed this on main: 06d198c2a72189982578eb0413e1367279272f02
