### ISSUE TITLE
[Bug]: Suspense around router not render fallback since v6.12.0 (breaking-change)

### ISSUE THREAD

**Issue by BC-M** [remix-run/react-router#10568]
### What version of React Router are you using?

6.12.0

### Steps to Reproduce

Up to v6.11.2, the `Routes' component can be wrapped by a single suspense to display a loading screen each time a new (lazy-loading) module needs to be loaded.

```typescript
<Suspense fallback={<LoadModuleScreen />}>
  <Routes>
     <Route element={<LazyModule1 />} ... />
     <Route element={<LazyModule2 />} ... />
     <Route element={<LazyModule3 />} ... />
  </Routes>
</Suspense>
```

As of v6.12.0, we have to wrap each route element with a suspense, which makes the code look a bit more clunky.

```typescript
<Routes>
   <Route element={
      <Suspense fallback={<LoadModuleScreen />}>
         <LazyModule1 />
      </Suspense>
   } ... />
   <Route element={
      <Suspense fallback={<LoadModuleScreen />}>
         <LazyModule2 />
      </Suspense>
   } ... />
   <Route element={
      <Suspense fallback={<LoadModuleScreen />}>
         <LazyModule3 />
      </Suspense>
   } ... />
</Routes>
```

It would be nice if a single suspense could be used to render a loading screen when using lazy-loaded modules. Maybe with a fallback prop on the routes element or a flag to keep the old behaviour until v6.11.2.

### Expected Behavior

Same until v6.11.2: Render the loading screen from suspense that wraps the hole router.

### Actual Behavior

The screen "freezes" until lazy-loading module is loaded.

**Comment by prajilshrestha** [comment]
@brophdawg11 having a similar issue here as well, not sure if its an bug or wrong with the implementation but the suspense just wont fallback. [Link](https://stackoverflow.com/questions/77145028/react-router-v6-15-lazy-not-rendering-suspenses-fallback-component?noredirect=1#comment136002705_77145028)

**Comment by y-nk** [comment]
i've reverted v7 to @6.11 because of this. at the moment i dont think i can provide easily the `location.key` since it needs `useLocation()` and i'm having my Suspense outside of the router.

a bit of DX should be nice for this usecase.

**Comment by jbmagx** [comment]
I do wrap each lazy component with Suspense and have not notice anything up to v6.27.0. But when I updated to v6.28.0, the Suspense doesn't render the fallback element anymore. Looks like I need to stay at v6.27.0 because of this. I prefer showing the Suspense fallback element immediately after I click a nav link rather than the screen freeze until lazy component is loaded.
