### ISSUE TITLE
[Bug]: useNavigate force redirection to wrong route

### ISSUE THREAD

**Issue by timmyBaiii** [remix-run/react-router#10560]
### What version of React Router are you using?

6.11.2

### Steps to Reproduce

force redirection to wrong route not auto redirect 404 route

### Expected Behavior

auto redirect 404 route

### Actual Behavior

route setting
export const baseRoutes = [
    {
        path: '/',
        element: <Home />
    },
    {
        path: '/about',
        element: <About />
    },
    {
        path: '/404',
        element: <ErrorPage404 />
    },
    {
        path: '*',
        elementError: <ErrorPage404 />,
        element: <Navigate to={'/404'} />
    }
]

// actual behavior
const navigate = useNavigate();
navigate('/test')

not auto redirect 404 route

**Comment by shrutisingh17** [comment]
Hi there! I'm interested in contributing to this issue. Is it still open for contributions? If so, I would like to work on it. Could you please assign it to me or provide any additional guidance or steps to get started? Thank you!

**Comment by timdorr** [comment]
Your `path: '/'` route isn't marked as exact, so it's catching anything that doesn't match the other routes. You need to either mark it `exact: true` or make it an `index: true` route.
