### ISSUE TITLE
[Bug]: Undeclared dependency on @remix-run/router in react-router-dom-v5-compat

### ISSUE THREAD

**Issue by dobesv** [remix-run/react-router#10570]
### What version of React Router are you using?

```
   "react-router": "5.3.4",
    "react-router-dom": "5.3.4",
    "react-router-dom-v5-compat": "^6.12.0",
```

### Steps to Reproduce

Using yarn pnp, try to use [react-router-dom-v5-compat](https://github.com/remix-run/react-router/tree/main/packages/react-router-dom-v5-compat)

### Expected Behavior

Works

### Actual Behavior

Get an error during webpack build:

```
@formative/main:build:web: ERROR in ../../.yarn/__virtual__/react-router-dom-v5-compat-virtual-82d2bc035e/0/cache/react-router-dom-v5-compat-npm-6.12.0-4c2102b0e2-0a0970956d.zip/node_modules/react-router-dom-v5-compat/dist/umd/react-router-dom-v5-compat.development.js 12:125-153
@formative/main:build:web: Module not found: Error: Can't resolve '@remix-run/router' in '/home/dobes/projects/formative/app.fixups/.yarn/__virtual__/react-router-dom-v5-compat-virtual-82d2bc035e/0/cache/react-router-dom-v5-compat-npm-6.12.0-4c2102b0e2-0a0970956d.zip/node_modules/react-router-dom-v5-compat/dist/umd'
@formative/main:build:web:  @ ../../.yarn/__virtual__/react-router-dom-v5-compat-virtual-82d2bc035e/0/cache/react-router-dom-v5-compat-npm-6.12.0-4c2102b0e2-0a0970956d.zip/node_modules/react-router-dom-v5-compat/dist/main.js 18:2-77
```

### Workaround

Edit `.yarnrc.yml` and add 

```
packageExtensions:
  react-router-dom-v5-compat@^6.12.0:
    dependencies:
      "@remix-run/router": '*'
```

**Comment by timdorr** [comment]
Something else is going on here. `react-router-dom-v5-compat` [depends on `react-router@6`](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom-v5-compat/package.json#L27), which [depends on `@remix-run/router`](https://github.com/remix-run/react-router/blob/main/packages/react-router/package.json#L26). So, you should have this dependency installed with a normal install of the top-level compat package. There is likely a problem with your install.

**Comment by dobesv** [comment]
- The published code for the package includes the expression `require("@remix-run/router")`.
- Yarn PnP requires that packages declare all the dependencies they import or require.
- You cannot import or require packages just because they are dependencies of your own dependencies
- You cannot import or require packages that are installed by packages that depend on your package unless you declare them as a peer dependency

**Comment by dobesv** [comment]
See also a similar report in https://github.com/remix-run/react-router/issues/9243 for the `react-router-dom` package.  In that case the issue was resolved correctly by updating `package.json` include the dependency, in https://github.com/remix-run/react-router/pull/9285/files

**Comment by dobesv** [comment]
Admittedly some may feel like using "yarn pnp" is a problem with my install, I quite like it and I do think it's pretty popular.  Anyhow, the workaround is available and easy for anyone else who runs into this, even if it's not fixed here they can hopefully find this issue and apply the workaround.
