### ISSUE TITLE
[Bug]: Updates to `URLSearchParams` are not accumulated correctly

### ISSUE THREAD

**Issue by Stehsegler** [remix-run/react-router#10580]
### What version of React Router are you using?

react-router-dom v6.12.1

### Steps to Reproduce

I have got a custom hook, whose relevant parts are as follows:

```
function useSomething(key: string) {
  const [urlSearchParams, setUrlSearchParams] = useSearchParams();

  // ...

  return {
    // ...
    reset: () =>
      setUrlSearchParams((params) => {
        params.delete(key);
        return params;
      })
  };
}
```

I use this hook multiple times in my component:

```
const something1 = useSomething("key1");
const something2 = useSomething("key2");
```

Then I do in an event handler:

```
something1.reset();
something2.reset();
```

### Expected Behavior

Both `key1` and `key2` are removed from the search params in the URL within the browser's address bar.

### Actual Behavior

Only `key2` is removed, i.e. the first update to the search params is lost.

This problem only occurs when the updates are made using `setUrlSearchParams` functions returned by _different_ calls to `useSearchParams()`. When doing something like

```
const [urlSearchParams, setUrlSearchParams] = useSearchParams();

const reset = () => {
  setUrlSearchParams((params) => {
    params.delete("key1");
    return params;
  });
  setUrlSearchParams((params) => {
    params.delete("key2");
    return params;
  });
}
```

we can observe the correct behavior when `reset` is called.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/9757#issuecomment-1359693916
