### ISSUE TITLE
[Bug]: v7_startTransition is not on typings

### ISSUE THREAD

**Issue by davbrito** [remix-run/react-router#10615]
### What version of React Router are you using?

6.13.0

### Steps to Reproduce

1. Install v6.13.9
2. Add the future.v7_startTransition flag.
3. TypeScript complains

### Expected Behavior

The typings should contain the flag

### Actual Behavior

The typings doesn't contain the flag.
![image](https://github.com/remix-run/react-router/assets/39559632/7ef3082d-f986-4451-9930-55ed0cc46842)

**Comment by brophdawg11** [comment]
This is admittedly confusing, but that's the wrong `FutureConfig` 😉.  I'd love to hear your thoughts as end users on the best way to document this, but right now we discuss the difference [here](https://reactrouter.com/en/main/guides/api-development-strategy#current-future-flags) which admittedly doesn't do much to reference the specific package versions and where to import from.

There's one set of `FutureConfig` flags to change behavior of the `router` you pass to `RouterProvider`, which is exported from `@remix-run/router`.  See https://www.unpkg.com/browse/@remix-run/router@1.6.3/dist/router.d.ts.

Then there's a second `FutureConfig` that changes the behavior of the UI layer (`BrowserRouter`, `RouterProvider`, etc.) that is exported from `react-router` and `react-router-dom`.  See: https://www.unpkg.com/browse/react-router@6.13.0/dist/lib/components.d.ts.

Definitely open to suggestions and PRs to make this clearer!

**Comment by dignifiedquire** [comment]
I am trying to use this feature on `6.18.0` and getting this error

```
Type '{ v7_startTransition: true; }' is not assignable to type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.
  Object literal may only specify known properties, and 'v7_startTransition' does not exist in type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.

92     v7_startTransition: true
       ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/App.tsx:92
```
with the codep
```js
createBrowserRouter(routes, {
  future: {
    v7_startTransition: true
  },
);
```

**Comment by IgorLuzhnyi** [comment]
> I am trying to use this feature on `6.18.0` and getting this error
> 
> ```
> Type '{ v7_startTransition: true; }' is not assignable to type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.
>   Object literal may only specify known properties, and 'v7_startTransition' does not exist in type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.
> 
> 92     v7_startTransition: true
>        ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 1 error in src/App.tsx:92
> ```
> 
> with the code
> 
> ```js
> createBrowserRouter(routes, {
>   future: {
>     v7_startTransition: true
>   },
> );
> ```

Hi, I have the same issue - were you able to resolve this? Thanks in advance!

**Comment by lhartvik** [comment]
I placed the v7_startTransition option like this, seems to have fixed it:

            <RouterProvider
                router={createBrowserRouter(
                    createRoutesFromElements(
                        <Route path={ROOT} ErrorBoundary={ErrorBoundary}>
                            <Route path={ROOT} element={<HomePage/>}/>
                            <Route path={"/something"} element={<Something/>}/>,
                            <Route path={"/other"} element={<Other/>}/>,
                        </Route>,
                    ),
                    {
                        basename: BASENAME, future: {
                            v7_fetcherPersist: true,
                            v7_relativeSplatPath: true,
                            v7_partialHydration: true,
                            v7_normalizeFormMethod: true,
                            v7_skipActionErrorRevalidation: true,
                        }
                    }
                )}
                future={{v7_startTransition: true}}
            />

**Comment by Lucasdxvid** [comment]
> I placed the v7_startTransition option like this, seems to have fixed it:
> 
> ```
>         <RouterProvider
>             router={createBrowserRouter(
>                 createRoutesFromElements(
>                     <Route path={ROOT} ErrorBoundary={ErrorBoundary}>
>                         <Route path={ROOT} element={<HomePage/>}/>
>                         <Route path={"/something"} element={<Something/>}/>,
>                         <Route path={"/other"} element={<Other/>}/>,
>                     </Route>,
>                 ),
>                 {
>                     basename: BASENAME, future: {
>                         v7_fetcherPersist: true,
>                         v7_relativeSplatPath: true,
>                         v7_partialHydration: true,
>                         v7_normalizeFormMethod: true,
>                         v7_skipActionErrorRevalidation: true,
>                     }
>                 }
>             )}
>             future={{v7_startTransition: true}}
>         />
> ```

Works!

**Comment by WilliamNazarian** [comment]
> > I am trying to use this feature on `6.18.0` and getting this error
> > ```
> > Type '{ v7_startTransition: true; }' is not assignable to type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.
> >   Object literal may only specify known properties, and 'v7_startTransition' does not exist in type 'Partial<Omit<FutureConfig, "v7_prependBasename">>'.
> > 
> > 92     v7_startTransition: true
> >        ~~~~~~~~~~~~~~~~~~~~~~~~
> > 
> > 
> > Found 1 error in src/App.tsx:92
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with the code
> > createBrowserRouter(routes, {
> >   future: {
> >     v7_startTransition: true
> >   },
> > );
> 
> Hi, I have the same issue - were you able to resolve this? Thanks in advance!

I am still getting this error on react-router v7.1.5 I have the future flag in routerprovider and it says future does not exist for this element
