### ISSUE TITLE
[Bug]: Descendant <Routes> - Optional segment followed by splat doesn't render relative nested route with dynamic segment, if first segment is omitted

### ISSUE THREAD

**Issue by AndyOGo** [remix-run/react-router#10617]
### What version of React Router are you using?

6.13.0

### Steps to Reproduce

Create [descendant `<Routes>`](https://reactrouter.com/en/main/start/faq#how-do-i-nest-routes-deep-in-the-tree), like:

1. create a route with optional segment, e.g. `/:search?/*`
2. create a descendant relative nested route, which renders an item detail below above route, e.g. `item/:itemId` (note: leading `/` slash is omitted to be relative)

Reproduction:
https://stackblitz.com/edit/github-oxxqr6

### Expected Behavior

Optional dynamic segments should work together with splats and descendant relative nested routes should still match, if the top-level optional segment is omitted in the URL.

- `/search-param/item/some-item-id` <- should work
- `/item/some-item-id` <- should work too

### Actual Behavior

Optional dynamic segments are broken if the top-level optional segment is omitted in the URL.
Descendant nested route isn't rendered.

- `/search-param/item/some-item-id` <- works
- `/item/some-item-id` <- fails

**Comment by AndyOGo** [comment]
This only works if the routes are defined together, like:


```jsx
<Routes>
        // this only works when defined together
        <Route path="/:search?/*" element={<Search />}>
          <Route path="item/:item" element={<Item />} />
        </Route>
</Routes>
```

Updated working example:
https://stackblitz.com/edit/github-oxxqr6-ukfe7y?file=src%2FApp.tsx

**Comment by brophdawg11** [comment]
I don't think this is a bug?  The router eagerly matches top-level routes, starts rendering the matched elements, and if it finds descendant routes it will attempt to keep matching the remaining path.

If you define an optional dynamic param in your top-level routes (`/:search?/*`) then when you route to `/item/foo` it _correctly_ matches `:search` with `"item"` and then renders `<Search>`.  When it gets to your descendant routes it only has `/foo` left which wont match `item/:item`.

Optional route params are a more advanced use-case and rely on the route scoring/ranking logic which only knows about the given set of `<Routes>` it's currently processing.  So in this case there is no way for the router to know that there is a deeper `<Routes>` that will match `/item/:item`.

I would recommend lifting your routes up as you've done in the second example, but if you can't do that then you may want to just skip the the optional aspect and set up two routes at the root:

```jsx
<Routes>
  <Route path="/search/:search/*" element={<Search />} />
  <Route path="/*" element={<Search />} />
</Routes>
```

**Comment by AndyOGo** [comment]
Thx @brophdawg11 
I will try setting up the two routes.

**Comment by AndyOGo** [comment]
FYI: it doesn't work either with setting up two routes at the root.

https://stackblitz.com/edit/github-oxxqr6-eulhnz?file=src%2FApp.tsx

**Comment by AndyOGo** [comment]
Thx for your reply.
Yeah I noticed that static segment.
Unfortunately it doesn’t work for our url structure.
I will use the top level approach.
