### ISSUE TITLE
[Bug]: Wrong id is used when trying to scroll to anchor if id contains `%20`

### ISSUE THREAD

**Issue by istarkov** [remix-run/react-router#10641]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Example app.
https://codesandbox.io/s/crimson-cdn-n3gpdq?file=/src/App.js

Create broserRouter and following route
```js
import { Link } from "react-router-dom";
import { ScrollRestoration } from "react-router-dom";

export default function App() {
  return (
    <>
      <ScrollRestoration />
      <div className="App">
        <Link to="/#hello%2520%20world">
          MUST WORK AND SCROLL TO BOTTOM, BUT WORKS ONLY WITH JS DISABLED OR ON
          REFRESH. CLICK ME AND REFRESH.
        </Link>
        <div style={{ height: "3000px" }}></div>
        <Link id={"hello%20 world"}>Link</Link>
      </div>
    </>
  );
}
```

With disabled js first links work, and scrolls to bottom. With refresh too. 
With enabled js not.

The issue is here 
https://github.com/remix-run/react-router/blob/bc2552840147206716544e5cdcdb54f649f9193f/packages/react-router-dom/index.tsx#L1300

Must be

`decodeURIComponent(location.hash.slice(1))`

### Expected Behavior

Should work even with js enabled

### Actual Behavior

Work only if js disabled.

**Comment by brophdawg11** [comment]
This is fixed by #10682 and should be available in the next release.
