### ISSUE TITLE
[Bug]: useLoaderData doesn't ascend route tree when used on a route element[|component?]

### ISSUE THREAD

**Issue by eckdanny** [remix-run/react-router#10668]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

[![StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/github-uictu2?file=src%2Fapp.tsx)

(I forked the [`Data Router` example](https://github.com/remix-run/react-router/tree/dev/examples/data-router))

### Expected Behavior

The verbiage [_"...nearest ancestor route loader"_](https://github.com/remix-run/react-router/blob/7178a484fb2c63a3e793f775527242b90d6b48d1/packages/react-router/lib/hooks.tsx#L857-L859) makes me think _ascending_ the route tree for resolved loader data, -exactly how `useLoaderData()` behaves when used in a component. I thought this would apply to `Route`s too.

Use case I have in mind is not data-loading (https://github.com/remix-run/react-router/issues/10616) or composing queries from resolved tributary data (https://github.com/remix-run/react-router/issues/9188#issuecomment-1248180434). I'm thinking about tabbed interfaces (`player/:id/<offense>|<defense>`) or wizards (`thing/new/<1-of-2>|<2-of-2>`) where the underlying data might exist at the `:id` or `new` segment respectively, but the leaf views are RRD `Route`s.

I kinda get what I want doing:

```
function useLoaderDataFromFirstAncestor() {
  const matches = useMatches();
  return matches.reverse().find((d) => Boolean(d.data))?.data;
}
```

but that doesn't feel right. Maybe I'm not interpreting docs correctly or this is usage question, but I started with a bug report.

### Actual Behavior

When I use `useLoaderData()` on `Route` components/elements and don't define a loader, it ascends the tree.

**Comment by timdorr** [comment]
That comment is referring to other components in the tree rendered by the Route's element. It does not cross the Route boundary upwards. [The docs make this pretty clear.](https://reactrouter.com/en/main/hooks/use-loader-data) (Note: You should be reading the docs, not the source code comments. They're not always updated correctly and have less people checking them for accuracy.)
