### ISSUE TITLE
[Bug]: Version 6.14.1 doesn't pass params

### ISSUE THREAD

**Issue by marekdedic** [remix-run/react-router#10667]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

https://github.com/skaut/poptavky/pull/972

### Expected Behavior

No errors, same as on version 6.14.0

### Actual Behavior

See for example in this test:

https://github.com/skaut/poptavky/blob/6a2ce6020f49184d7e7e1e9b564c0212b65dcdb7/packages/frontend/__tests__/pages/ProjectDetail.test.tsx#L10-L22

The `useParams` call here:

https://github.com/skaut/poptavky/blob/6a2ce6020f49184d7e7e1e9b564c0212b65dcdb7/packages/frontend/src/pages/ProjectDetail.tsx#L22-L26

returns `undefined` for all params in 6.14.1

**Comment by timdorr** [comment]
You updated react-router without updating react-router-dom. You need to only use react-router-dom or upgrade both together.
