### ISSUE TITLE
[Docs]: getContacts is never defined in the tutorial docs

### ISSUE THREAD

**Issue by ChrisKneller** [remix-run/react-router#10684]
### Describe what's incorrect/missing in the documentation

https://reactrouter.com/en/main/start/tutorial#loading-data

Here we `import { getContacts } from "../contacts";`

However, `getContacts` is not defined at any point in the tutorial. We can't ever get contacts if we follow the tutorial. It's very difficult to follow along because of this gap.

**Comment by timdorr** [comment]
It's provided in [the Gist](https://gist.githubusercontent.com/ryanflorence/1e7f5d3344c0db4a8394292c157cd305/raw/f7ff21e9ae7ffd55bfaaaf320e09c6a08a8a6611/contacts.js) that's linked in [the Setup section](https://reactrouter.com/en/main/start/tutorial#setup).

**Comment by cfez** [comment]
when I get to the part where I have to use getContact my web page goes blank, I dont know why, but I don't get any output at all.

**Comment by cfez** [comment]
I dont know what I am doing wrong, I am following the tutorial but I get stuck at that part
