### ISSUE TITLE
[Docs]: File object through actions document isn't available.

### ISSUE THREAD

**Issue by harsimarriar96-dappquire** [remix-run/react-router#10685]
### Describe what's incorrect/missing in the documentation

I am currently trying to upload files
I am using actions for routers but the file passed to the action is converted to a string and unable to send it as a file.

**Comment by timdorr** [comment]
Add `encType="multipart/form-data"` to your Form's props.

**Comment by jeshtan** [comment]
@harsimarriar96-dappquire I run into the same problem today. May I know how you overcome the problem?

**Comment by bsides** [comment]
Same problem here with the added effect that it behaves differently from other encTypes - it will go to the route via GET, loading the loader in the process, so if the route doesn't have an element / loader, it will break the app.
