### ISSUE TITLE
[Bug]: wildcard route is not returned when url has CRLF injection

### ISSUE THREAD

**Issue by ben-liveauctioneers** [remix-run/react-router#10700]
### What version of React Router are you using?

6.10.0 (also present on 6.14.1)

### Steps to Reproduce

https://codesandbox.io/s/vigorous-raman-k5gdzh?file=/src/index.js

```
  <BrowserRouter>
    <Routes>
      <Route path="/" element={<h1>Home</h1>} />
      <Route path="*" element={<h1>Wildcard</h1>} />
    </Routes>
  </BrowserRouter
  ```

Observe that path 
- `/` returns Home
- `/asdf` returns Wildcard
- `/%2F` returns Wildcard
- `/%0D%0A` returns blank page

### Expected Behavior

A path including `%0D%0A` should return a wildcard route match

### Actual Behavior

A path including `%0D%0A` returns an empty route match array

### Proposed changes
*** note: I'm very new to react and it's ecosystem (~6 months) and I wasn't able to successfully npm install my local react-router repo so this may not work ***

Add another assertion that checks if CRLF injection has been matched to wildcard route
packages/react-router/__tests__/matchRoutes-test.tsx:65
```
expect(pickPaths(routes, '/%0D%0A')).toEqual(['*']);
```

Trim CRLF injection from decoded url
packages/router/utils.ts:995
```
value = value.replace(/(.*?)(%0[dD]%0[aA].*)/gm, `$1`);
return decodeURI(value);
```

**Comment by timdorr** [comment]
That isn't a valid URI when normalized and decoded according to the spec: https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.2 (Those aren't unreserved characters). Those should go in a query string.

**Comment by ben-liveauctioneers** [comment]
Thanks for the response @timdorr but I'm not understanding. Are you saying that any url string handed to `matchRoutes` needs to be decoded and sanitized first?

**Comment by cccRaim** [comment]
I got the same issue, when has blank, "%20", returns blank page, any solutions?

**Comment by cccRaim** [comment]
> That isn't a valid URI when normalized and decoded according to the spec: https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.2 (Those aren't unreserved characters). Those should go in a query string.

I think a wildcard should represent all characters, rather than instructing developers to use URI or query. This limits the use of developers and prevents them from better serving the product.
