### ISSUE TITLE
[Bug]: Page refresh location.state is still present

### ISSUE THREAD

**Issue by vaynevayne** [remix-run/react-router#10713]
### What version of React Router are you using?

latest

### Steps to Reproduce

```jsx
 navigate('/tableView', {
                state: form,
              })
```

```jsx
const location = useLocation()
console.log(location.state) // page reload , this still exist 
```

### Expected Behavior

state is null

### Actual Behavior

state is form

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by timdorr** [comment]
This is expected behavior. If you're just refreshing, the browser retains this value in the history stack, even though the data isn't represented in the URL shown.

**Comment by vaynevayne** [comment]
> This is expected behavior. If you're just refreshing, the browser retains this value in the history stack, even though the data isn't represented in the URL shown.

How can I clear this value in react-router so that it will be empty when the page is refreshed?

**Comment by Dobby89** [comment]
@vaynevayne Did you figure out how to clear on refresh?
