### ISSUE TITLE
[Bug]: The router does not catch errors caused in the rendering of components

### ISSUE THREAD

**Issue by vnva** [remix-run/react-router#10722]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

Initialize the router as usual, add an errorElement and trigger the error in the component renderer.

[Playground](https://stackblitz.com/edit/stackblitz-starters-ga9svu?file=src%2Frouter.tsx) 

### Expected Behavior

The error should catch

### Actual Behavior

The error is not catching

**Comment by vnva** [comment]
Working in `useEffect`, but error not parsed

**Comment by brophdawg11** [comment]
React Error boundaries don't catch errors thrown in event handlers: https://legacy.reactjs.org/docs/error-boundaries.html

> Error boundaries do not catch errors for:
>
> * Event handlers ([learn more](https://legacy.reactjs.org/docs/error-boundaries.html#how-about-event-handlers))
> * Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
> * Server side rendering
> * Errors thrown in the error boundary itself (rather than its children)
