### ISSUE TITLE
[Bug]: SSR Hydratation error with <Outlet />

### ISSUE THREAD

**Issue by SanNic20** [remix-run/react-router#10728]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

I followed the docs on [https://reactrouter.com/en/main/guides/ssr](https://reactrouter.com/en/main/guides/ssr) to make an SSR app.

### Expected Behavior

Should server render hydratation without errors

### Actual Behavior

I have an SSR application with React-Router that works fine, but when I use the `<Outlet />` component, I get the error below:

`This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.`

I did the tests with a simple page with "Hello World". When I use it without going through the `<Outlet />` it works, but if I go through `<Outlet />` I get this hydratation error.

In the source code of the page, I also noticed this. Without going through the `<Outlet />`, hydration is done correctly like this:
`<div id="root"><div class="MuiBox-root mui-style-1g4yje1">Hello World</div></div>`

But if I go through the Outlet, the hydration is different:
`<div id="root"><div class="MuiBox-root mui-style-1g4yje1"><!--$--><!--$-->Hello World<!--/$--><!--/$--></div></div>`
Why is `<!--$-->` is added? Is this normal behaviour?

I also tried to load the page with the lazy and suspense component, but still got the same error message.

For information, I use version `18.2.0` of `react` and `react-dom`

Of course, I remain at your disposal for any questions or tests you may have. Thank you in advance for your help.

**Comment by timdorr** [comment]
Nothing in our code base adds those comment nodes. They are likely coming from somewhere else in your libraries or perhaps your own code.
