### ISSUE TITLE
[Bug]: react router browsing fails when i update graphQL token

### ISSUE THREAD

**Issue by tastafur** [remix-run/react-router#10721]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

When I navigate to a view where I have a loader, which makes calls to graphql and the token has expired, I intercept the call refresh the token and redo the failed call, the loader waits for all that to happen but the navigation to that view sometimes fails. Then it changes the browser path as if it was going to navigate but it does not navigate.

### Expected Behavior

The expected behavior is that the navigation flow will not be broken and it will navigate

### Actual Behavior

The current behavior is that the navigation flow is broken.

**Comment by tastafur** [comment]
I add the logic of the code:
Loader:
```typescript
export const SearchAndCreateHistoricalLoader: (
  userData: AuthContextType | null
) => LoaderFunction = (userData) => async () => {
  if (userData?.user) {
    const communications = await client.query({
      query: FETCH_COMMUNICATIONS,
    });

    const ordersWithDataCommunication = await selectCommunicationOrders(
      communications.data.communications
    );

    return defer({ data: ordersWithDataCommunication });
  }
  return {};
};
```

GraphQL subscript/interception logic:
```typescript
const setError = useCallback<ErrorHandler>(
    ({ graphQLErrors, networkError, operation, forward }) => {
      if (graphQLErrors) {
        for (const err of graphQLErrors) {
          switch (err.extensions.code) {
            case 'FORBIDDEN': {
              const response = err.extensions.response as { message: string };
              if (response?.message === 'Refresh token expire') {
                userData?.setUser(null);
              } else {
                return;
              }
              break;
            }
            case 'UNAUTHENTICATED':
              // ignore 401 error for a refresh request
              if (operation.operationName === 'regenerateAccessToken') return;

              return new Observable<FetchResult>((observer) => {
                // used an annonymous function for using an async function
                (async () => {
                  try {
                    const user = getLocalStorageUser();
                    if (!user?.accessToken) {
                      throw new GraphQLError('Empty AccessToken');
                    }
                    const accessToken = await refreshToken(user?.refreshToken);

                    userData?.setUser({
                      ...user,
                      accessToken,
                    });

                    // Retry the failed request
                    const subscriber = {
                      next: observer.next.bind(observer),
                      error: observer.error.bind(observer),
                      complete: observer.complete.bind(observer),
                    };

                    forward(operation).subscribe(subscriber);
                  } catch (err) {
                    observer.error(err);
                  }
                })();
              });
          }
        }
      }

      if (networkError) console.log(`[Network error]: ${networkError}`);
    },
    [userData?.user]
  );
```

**Comment by brophdawg11** [comment]
It's har to say for sure without a minimal reproduction, but this looks to me like you're trying to combine loaders with values driven by react hooks which doesn't work due to the decoupling of fetching and rendering in `RouterProvider`.  Your loader cannot rely on information (`userData`) that is driven by the render cycle (`useCallback`) because loaders/actions run entirely outside of the render cycle, and won't run on changes to hook-driven state.

Instead, you should do your intercepting outside of React inside your API client (with something like an `axios` interceptor or similar logic).

If this is not a hook/loader coupling issue, please feel free to re-open with a minimal reproduction!

**Comment by tastafur** [comment]
I tried another way to unlink it from the react cycle and it worked, thank you very much.
