### ISSUE TITLE
[Bug]: matchRoutes doesn't automatically consider your basename

### ISSUE THREAD

**Issue by slashwhatever** [remix-run/react-router#10735]
### What version of React Router are you using?

6.13

### Steps to Reproduce

When using the `matchRoutes` method, failing to pass in your configured `basename` will result in failed matches.

```
// app.tsx

  const router = createBrowserRouter(myRouterConfig(), {
    basename,
  });

return (
  <RouterProvider
    router={router}
    fallbackElement={<ProgressSpinner />}
  />
);
 
// myComponent.tsx

  const matchThisRoute = [{ path: `/messages/:messageId` }];
  const isAMatch = Boolean(
    matchRoutes(matchThisRoute, location)?.length
  );

// isAMatch = false

  const matchThisRoute = [{ path: `/messages/:messageId` }];
  const isAMatch = Boolean(
    matchRoutes(matchThisRoute, location, basename)?.length
  );

// isAMatch = true


```

### Expected Behavior

```
// app.tsx

  const basename = '/baseroute'

  const router = createBrowserRouter(myRouterConfig(), {
    basename
  });

return (
  <RouterProvider
    router={router}
    fallbackElement={<ProgressSpinner />}
  />
);
 
// myComponent.tsx

  const matchThisRoute = [{ path: `/messages/:messageId` }];
  const isAMatch = Boolean(
    matchRoutes(matchThisRoute, location)?.length
  );

// isAMatch = true

```

### Actual Behavior

IMO, if you've configured a `basename`, you should expect all route matching to work with that `basename` in consideration. I can't find any other methods or hooks (`useMatch`, or `useMatches` for example) that require you to pass this value in.

**Comment by timdorr** [comment]
[`basename` is the third argument of the function.](https://github.com/remix-run/react-router/blob/868e5157bbb72fb77f827f264a2b7f6f6106147d/packages/router/utils.ts#L456)
