### ISSUE TITLE
[Bug]: Basename doesn't work

### ISSUE THREAD

**Issue by AdrianGolda** [remix-run/react-router#10737]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

https://stackblitz.com/edit/github-usqppu?file=src%2FApp.tsx

I used the code from the docs. 

### Expected Behavior

The page should render under '/' as the docs say. It worked in version 5.

### Actual Behavior

The page is blank and the error is:

`<Router basename="/app"> is not able to match the URL "/" because it does not start with the basename, so the <Router> won't render anything.`

**Comment by bilalk711** [comment]
I tried to check this code 
https://stackblitz.com/edit/github-usqppu?file=src%2FApp.tsx
It has some issues like BrowserRouter in the main.ts and it's also added in app.ts but after fixing that, if I go to "/" route I get 
`<Router basename="/app"> is not able to match the URL "/" because it does not start with the basename, so the <Router> won't render anything.`
I will see if I can find the fix.
@AdrianGolda

**Comment by bilalk711** [comment]
This solution will help to redirect but it needs to be fixed 
https://stackoverflow.com/questions/70519315/router-basename-is-not-able-to-match-the-url-because-it-does-not-start-with-the
@AdrianGolda

**Comment by timdorr** [comment]
You need to put `/app` at the front of your URL for things to match. You also have two BrowserRouter instances and your Route has no element prop, so won't render anything.

**Comment by bilalk711** [comment]
@timdorr I have a question, suppose basename is "/app" but the user hits the domain without that subpath "/app", it will render nothing by default if there is no redirection configured such that hitting the main domain url redirects to basename "/app". Is this as expected, I mean it's up to users to set that redirection and btw what is the point of using basename prop if redirection should be configured manually?

**Comment by xc1427** [comment]
I upvote @bilalk711 idea. At least an option should be given to enable the "redirect" feature.

> @timdorr I have a question, suppose basename is "/app" but the user hits the domain without that subpath "/app", it will render nothing by default if there is no redirection configured such that hitting the main domain url redirects to basename "/app". Is this as expected, I mean it's up to users to set that redirection and btw what is the point of using basename prop if redirection should be configured manually?

**Comment by philipp-serfling** [comment]
Any news on that?
Also the provided workaround does not address the issue when using `createBrowserRouter()`

> I upvote @bilalk711 idea. At least an option should be given to enable the "redirect" feature.
> 
> > @timdorr I have a question, suppose basename is "/app" but the user hits the domain without that subpath "/app", it will render nothing by default if there is no redirection configured such that hitting the main domain url redirects to basename "/app". Is this as expected, I mean it's up to users to set that redirection and btw what is the point of using basename prop if redirection should be configured manually?
