### ISSUE TITLE
[Bug]: Reading special characters like (+) is not working with useSearchParams 

### ISSUE THREAD

**Issue by maazakn** [remix-run/react-router#10746]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

I have created a code sandbox: [https://codesandbox.io/s/wispy-water-mps7ly?file=/src/App.js](https://codesandbox.io/s/wispy-water-mps7ly?file=/src/App.js)

Use this link to test: [https://mps7ly.csb.app/?code=+_somecode](https://mps7ly.csb.app/?code=+_somecode)

### Expected Behavior

"+_somecode"

### Actual Behavior

"_somecode"

**Comment by timdorr** [comment]
If you `JSON.stringify`, you'll see the string you get is `" _somecode"`. The plus is converted into a space character by the browser. If you need that in your URL, you need to URL encode it.
