### ISSUE TITLE
[Bug]: Failed loader doesn't throw an error

### ISSUE THREAD

**Issue by nemonemi** [remix-run/react-router#10744]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

1. Have a route `loader` that fetches data and returns a promise.
2. Consume the data via `useDataLoader`
3. Trigger that response to fail
4. Check the `error` from the `useRouteError`
5. Check the `data` from `useDataLoader`

They both are undefined.

### Expected Behavior

I would expect that if the server responds with 400 or a similar type of error, the loader informs the component in some way about it.

### Actual Behavior

There is no way to react to oan error that occurred in the `loader`.

**Comment by brophdawg11** [comment]
Can you provide a reproduction?  If a loader throws, it will bubble to the nearest [`errorElement/ErrorBoundary`](https://reactrouter.com/en/main/route/error-element):

https://codesandbox.io/s/serene-sara-kc38yd
