### ISSUE TITLE
[Bug]: Regression - useNavigate is not stable

### ISSUE THREAD

**Issue by codebutler** [remix-run/react-router#10767]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

Hi, if I am understanding the conversation in #10743 correctly, `useNavigate` should be stable while navigating when using `RouterProvider`, but that's not the behavior I'm seeing. 

Simple example: https://replit.com/@codebutler/React-Router-useNavigate-re-render-bug#src/App.tsx

### Expected Behavior

Root component should not re-render when location changes.

### Actual Behavior

Root component re-renders.

**Comment by brophdawg11** [comment]
You're confusing "stability" with "re-rendering".  React always re-renders when state changes.  The state changing is the global router state and it performs a top-down re-render.  This is also what happens on your context access.  This comment in the original issue speaks a bit to this: https://github.com/remix-run/react-router/issues/7634#issuecomment-1530030214.

The `navigate` function is stable when using `RouterProvider` which means that it's identity will not change across navigations and thus it will not trigger re-executions of effects on navigations when it's used as a dependency.

```js
let navigate = useNavigate();
console.log("render"); // This will log on location changes

useEffect(() => {
  console.log("effect"); // This will not log on location changes
}, [navigate]);
```
