### ISSUE TITLE
[Bug]: double slash after origin create error Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by LexaDel** [remix-run/react-router#10789]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

In [example](https://codesandbox.io/s/naughty-stallman-59lyk2) 
add extra slash to url https://59lyk2.csb.app//

### Expected Behavior

we should see "Error component"

### Actual Behavior

we see **Failed to construct 'URL': Invalid URL**

**Comment by timdorr** [comment]
Duplicate of #10005

I'm also unable to reproduce this on my end with the example. I think something else is going on here.

**Comment by LexaDel** [comment]
@timdorr  I've updated example, now it reproduce
