### ISSUE TITLE
[Bug]: Testing Form submit, calls action with empty Formdata, tried both happy-dom and jsdom

### ISSUE THREAD

**Issue by sandeepkumaar** [remix-run/react-router#10784]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

```
import { Form, redirect, } from 'react-router-dom';
async function action({request}) {
  console.log('action called');
  let formData = await request.formData();
  let formObj = Object.fromEntries(formData);
  console.log('form submit', formObj); // <---- empty object {}
  let { id } = formObj;
  return redirect(`/contacts/${id}`);
};

function App() {
  return (
    <div>
      <Form method='post'>
        <input  name="id" defaultValue='5'></input>
        <button type='submit'>Start</button>
      </Form>
    </div>
  )
};


test('<AppForm/> submit', async assert => {

  let routes = [
        {
          path: '/',
          element: <App />,
          action: action,
        },
        {
          path: "/contacts/:id",
          element: <LocationDisplay/>,
        },
  ];
  const { screen, user } = domRenderWithRouterProvider(routes, assert.teardown);
  let submitBtn = await screen.getByText('Start');
  await user.click(submitBtn);
  let locationEl = await waitFor(async () => screen.getByTestId('location-display'));
  assert.same(locationEl.innerText, '/contacts/5', 'On Submit; Should have redirected to /contacts/5');
})

```

### Expected Behavior

Expecting the form object should have the property `id` from the `name` attribute on form submission. This is working in browser. but not in jsdom and happydom

### Actual Behavior

To have formData object similar to browser. If this is a limitation of dom libraries. please let me know a workaround, I couldn't find any reference to handle this. 

Repo: https://github.com/sandeepkumaar/test-react-router-formdata-happydom

**Comment by timdorr** [comment]
This isn't a React Router bug. Check your setup for jsdom, because it definitely [works in that environment](https://github.com/remix-run/react-router/blob/e254133b3f1daa9247d1b39ed46f77a7ffba5cdc/packages/react-router-dom/__tests__/data-browser-router-test.tsx#L2435-L2501).
