### ISSUE TITLE
[Bug]: Endless render occurs when I use navigate() along with unstable_useBlocker

### ISSUE THREAD

**Issue by Ivan-Papko** [remix-run/react-router#10791]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

I have an app where I use react router V6.15.0 for routing
I need to navigate to another page when I select an option in a input with type select. 
I cannot use Link in this case so I hate to call the navigate() method, that's returned by useNavigate()
Also I have to use the unstable_useBlocker hook as I need to prevent user from losing half-filled form info when navigating away.

### Expected Behavior

There is no any endless render 

### Actual Behavior

All app is endlessly rendered when I use unstable_useBlocker, that's called with true and  try to navigate with help the navigate() method.

**Comment by brophdawg11** [comment]
Can you provide a minimal reproduction of the issue?
