### ISSUE TITLE
[Bug]: useSearchParams does not update when using navigate / useNavigate

### ISSUE THREAD

**Issue by dor6-deepcred** [remix-run/react-router#10809]
### What version of React Router are you using?

6.15 / 6.14

### Steps to Reproduce

create a button that adds a search param using useNavigate (lets say `a=tralala`)
use useSearchParams to get the search params, render searchParams.get("a");

### Expected Behavior

after clicking the button "tralala" will be rendered 

### Actual Behavior

after clicking the button nothing will be rendered

**Comment by timdorr** [comment]
Can you add a reproduction of this? There's not enough info here to know what's going on. Here are the starters:

[Using `<RouterProvider>`](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/basic-data-router?file=src/app.tsx)
[Using `<BrowserRouter>`](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/basic?file=src/App.tsx)

**Comment by dor6-deepcred** [comment]
@timdorr 
I tried to recreate and failed with the links
Its not related to navigate i switched the logic to use useSearchParams and it did not help
why could it happen where It get updated using the the same useSearchParams object but when changing the search params from somewhere else it does not (only when i open the browser)
we use BrowserRouter

**Comment by timdorr** [comment]
This doesn't sound like a bug, just a misuse of the API. Unless you can create a reproduction somewhere (it doesn't have to be StackBlitz), there's not enough information to work with here. You should consult other help resources, like our Discord server.
