### ISSUE TITLE
[Bug]: Failed to decode param

### ISSUE THREAD

**Issue by mehdux** [remix-run/react-router#10807]
### What version of React Router are you using?

v6.11.1

### Steps to Reproduce

I introduce in the browser field a url with a % and I get the following error: 
decode_param : node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js

### Expected Behavior

The browser should show me a normal web page.

### Actual Behavior

Normally I shouldn't have this kind of error.

**Comment by timdorr** [comment]
Please don't open duplicate issues.
