### ISSUE TITLE
[Bug]: Namespace 'React' has no exported member 'JSX'.

### ISSUE THREAD

**Issue by su-kialo** [remix-run/react-router#10824]
### What version of React Router are you using?

v6.15.0

### Steps to Reproduce

`react` Version: v16.14.0
`react-dom`Version: v16.14.0

`react-router-dom` version v.6.15.0

1. Run `tsc` with the following `tsconfig`

```
{
 // ...
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "noEmit": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "jsx": "preserve",
        "module": "esnext",
        "moduleResolution": "node",
        "sourceMap": true,
        "strict": true,
        "target": "es2015",
        "noErrorTruncation": false,
        "lib": ["dom", "es6", "dom.iterable", "scripthost", "es2016.array.include"],
        "noUnusedLocals": true,
        "resolveJsonModule": true
    },
 // ...
}
```

### Expected Behavior

No errors to be reported.
Typescript should build successfully

### Actual Behavior

The following error is reported by the Typescript compiler.

`Error: node_modules/react-router-dom/dist/index.d.ts(36,107): error TS2694: Namespace 'React' has no exported member 'JSX'.`

**Comment by brophdawg11** [comment]
Could you provide a minimal reproduction of the issue?

**Comment by timdorr** [comment]
Make sure your `@types/react` version is up to date. This is likely a version prior to 18.2.6, where `React.JSX.Element` was added and the global `JSX.Element` was deprecated.

**Comment by su-kialo** [comment]
Ok thanks.
For other reasons, we can't upgrade our version of React right now (we're working on it).

Is there documentation about the minimum supported React version for `react-router`?
If there is, I couldn't find it.

**Comment by timdorr** [comment]
I believe the JSX namespace changes were backported to the older packages as well. 16.14.41 should be compatible.
