### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by germanescobar** [remix-run/react-router#10836]
### What version of React Router are you using?

6.11.2

### Steps to Reproduce

Using TypeScript create an `App` component that receives a router through props (created with `createBrowserRouter`) and try to type it:

```jsx
type Props = {
  router: ?????
}
function App({ router }: Props) {
  <RouterProvider router={router} />
}
```

### Expected Behavior

`RemixRouter` should be re-exported or `createXxxxRouter` functions should return a type that people can use in their code. 

`RemixRouter` is currently inside [@remix-run/router](https://www.npmjs.com/package/@remix-run/router) and its documentation clearly states:

> If you're using React Router, you should never import anything directly from the @remix-run/router - you should have everything you need in react-router-dom (or react-router/react-router-native if you're not rendering in the browser). All of those packages should re-export everything you would otherwise need from @remix-run/router.

There are two similar issues #9923 and #10787 which were closed without a proper resolution. 

### Actual Behavior

`RemixRouter` is not re-exported from  [@remix-run/router](https://www.npmjs.com/package/@remix-run/router).

**Comment by timdorr** [comment]
We say that so folks don't use the wrong package when starting out. It's fine to use the types from that package, as they're already included via react-router-dom anyways.

**Comment by germanescobar** [comment]
> We say that so folks don't use the wrong package when starting out. It's fine to use the types from that package, as they're already included via react-router-dom anyways.

Shouldn't `react-router-dom` re-export `RemixRouter` so that we don't have to include the @remix-run/router package? Or is there another way? Sorry, but this is just confusing tbh.

**Comment by timdorr** [comment]
You can also use `ReturnType`:

```ts
import type { createBrowserRouter } from "react-router-dom";

type RemixRouter = ReturnType<typeof createBrowserRouter>
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAxlFBDGFAISggHcBnFKAJQgFdCo4BfOAM1JDgCJc8sMALSlG1IQBMIIHgG4AUPKSo4NFCGAAPOmOYBeVShj0oAOwAqyFAB5lKCO2z9CJclVoMmAPkXt6pwWAIUwQUChgAClEmAC5DDW1PagBKDHk4DOxgiggAGxQAOlyIAHMopKgCgCM8KlM8EBRk+RYgA
