### ISSUE TITLE
[Bug]: external links open in the same tab

### ISSUE THREAD

**Issue by BasemYahia402** [remix-run/react-router#10839]
### What version of React Router are you using?

6.4

### Steps to Reproduce

- Open page home on vsc
- Go to links in the navbar
- Add attribute target="_blank" to all links

### Expected Behavior

 link of repo GitHub and link of telegram on the home page when click them it will open in the new tab

### Actual Behavior

link of repo GitHub and link of telegram on the home page when click them it will open in the same tab

**Comment by timdorr** [comment]
`Link` renders an `<a>` with the click handler overridden to keep the navigation on the same page. As a result, it's not possible for us to spawn new tabs/windows without running into various security and spam restrictions built into the browser. If you want this, use a plain `<a>` tag.
