### ISSUE TITLE
[Bug]: LastPass extension ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by aguerschuAdapptr** [remix-run/react-router#10841]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

When using my web application who is built on react and uses react-router-dom in some cases the inputs and the forms get auto-filled and submitted which causes a crash on my application as far as I saw is related to the fact that some of my users have the LastPass browser extension installed and this causes the error.

I just wonder how is possible that this extension crashes my whole application, have you heard about this issue?
Could you please help me to sort this out?

Related link: [](https://stackoverflow.com/questions/76187282/react-resizeobserver-loop-completed-with-undelivered-notifications)

Thanks in advance!

### Expected Behavior

Even with the lastPass browser extension, my users should be able to work on my application without any issue.
When a login or a form with a password is present they should be able to use the last pass extension, but in other forms nonrelated to passwords or logins they should not get any field auto-filled or submitted.

### Actual Behavior

when entering to forms with inputs with a big width or random and normal input texts, the application crashes and gives an error: ResizeObserver loop completed with undelivered notifications

https://stackoverflow.com/questions/76187282/react-resizeobserver-loop-completed-with-undelivered-notifications

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router.

**Comment by WJKwok** [comment]
https://stackoverflow.com/questions/76187282/react-resizeobserver-loop-completed-with-undelivered-notifications
