### ISSUE TITLE
[Bug]: TS issue, 'MemoryRouter'/'Route'/'Outlet' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by tinaboyce** [remix-run/react-router#10847]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

Typescript is currently throwing TS2786 everywhere. Started about 6 hours ago. I have a CI pipeline that would do a fresh "npm install" with no package-lock.json beforehand. 

Using either MemoryRoute, Route or Outlet (the ones I use in this current project) as a JSX results in this error when running `tsc --noEmit`

### Expected Behavior

`tsc --noEmit` to not return anything

### Actual Behavior

MemoryRouter error
```
error TS2786: 'MemoryRouter' cannot be used as a JSX component.
  Its type '({ basename, children, initialEntries, initialIndex, future, }: MemoryRouterProps) => ReactElement<any, string | JSXElementConstructor<any>>' is not a valid JSX element type.

96                 <MemoryRouter initialEntries={[{ pathname: '/' }]}>
                    ~~~~~~~~~~~~
```

Route error
```
error TS2786: 'Route' cannot be used as a JSX component.
  Its type '(_props: RouteProps) => ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX element type.

19             <Route
                ~~~~~
```

Outlet error
```
error TS2786: 'Outlet' cannot be used as a JSX component.
  Its type '(props: OutletProps) => ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX element type.
    Type '(props: OutletProps) => ReactElement<any, string | JSXElementConstructor<any>> | null' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not assignable to type 'ReactNode'.

40                 <Outlet />
```

**Comment by timdorr** [comment]
Something else is going on here because those are definitely React components. This isn't a bug with React Router. I'd check your @types/react version, as that may be contributing.

**Comment by tinaboyce** [comment]
Thanks for your feedback @timdorr and sorry for wasting your time. After further investigation, you are correct, it isn't a bug, managed to find the root cause, a peer-dependencies somewhere.

Adding `"react": [ "./node_modules/@types/react" ]" to the "paths" section of tsconfig.json fixed it for now.

```
{
  "compilerOptions": {
    ...
    "paths": {
      ...
      "react": [ "./node_modules/@types/react" ]
    },
    ...
}
```
