### ISSUE TITLE
[Bug]: createHashRouter doesn't change a browser URL

### ISSUE THREAD

**Issue by DmytriyZahrebelny** [remix-run/react-router#10855]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

1. Install the latest react-router-dom
2. Create a router with `createHashRouter`
3. Delploy the app

### Expected Behavior

I have two hashes in the URL, and my app is a sub-directory where such URLs are `index` for the app `https://app.io/**#**/pokemon/**#**/` or `https://app.io/**#**/pokemon`.

 When I click on links and go to new pages, I want to see that the URL will be changed regarding the current page. Lile `https://app.io/**#**/pokemon/**#**/create` or `https://app.io/**#**/pokemon/**#**/news`.

### Actual Behavior

It happened after migration from v5 to v6.4.

I can press the link, and it will work. I will go by the pages. But the URL is always the same - `https://app.io/#/pokemon`.
I tried adding the `basename` with different options, but I had a blank screen after that.

```
{
    basename: "pokemon", // "/pokemon", "/pokemon/", "#/pokemon/#", "/#/pokemon", "/#"
}
```

I have the second environment to deploy and test the app. Using a URL with one hash in the second environment works appropriately as in the local environment.

**Comment by timdorr** [comment]
You can't have multiple number signs in the URL structure. The way we parse paths will interfere with this, [where the second number sign will get parsed into the `hash` component of the location](https://github.com/remix-run/react-router/blob/4b494b935d62cd1244fe5c091db920d3f0315e9e/packages/router/history.ts#L573-L577). This is consistent with [the fragment definition of RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5). Technically, these are actually invalid URLs. Hence, we can't support this. If this worked before, it was _technically_ a bug.
