### ISSUE TITLE
[Bug]: Multiple Rendering

### ISSUE THREAD

**Issue by martingg88** [remix-run/react-router#10854]
### What version of React Router are you using?

V6

### Steps to Reproduce

I have wrapped component with withRouter as follows, but I found out that it will re-render view if any route changed. how to prevent it cause unnecessary render?

let ComponentWithRouterProp = (props) => {

        let location = useLocation();
        let navigate = useNavigate();
        let params = useParams();

        return (

            <Component
                {...props}
                router={{ location, navigate, params }}
            />
        );
    };

### Expected Behavior

x

### Actual Behavior

x

**Comment by brophdawg11** [comment]
Could you provide a minimal reproduction of the issue in code sandbox?

**Comment by timdorr** [comment]
This is expected behavior. The useLocation hook will always trigger a re-render on a navigation because the location changed and it needs to update its value.

**Comment by martingg88** [comment]
> 

Yes.  You are right. But how to avoid it to re-render for certain components as they not really need any data from router hook even if location changed.

**Comment by brophdawg11** [comment]
https://react.dev/reference/react/memo
