### ISSUE TITLE
[Bug]: TypeError: Cannot destructure property 'basename' of 'React__namespace.useContext(...)'

### ISSUE THREAD

**Issue by angeldevildev** [remix-run/react-router#10867]
null
- error node_modules\react-router-dom\dist\umd\react-router-dom.development.js (483:0) @ LinkWithRef
- error TypeError: Cannot destructure property 'basename' of 'React__namespace.useContext(...)' as it is null.
null

![image](https://github.com/remix-run/react-router/assets/122638135/b3a1998d-2ec8-4354-84e3-9f1d0503233e)

Code:
Navbar.js:
`"use client";

import { Link } from 'react-router-dom';
import { useState } from "react";
import { IconMenu2, IconX } from "@tabler/icons-react";
import "./Navbar.css";

function Navbar() {
  const [nav, setNav] = useState(false);

  const openNav = () => {
    setNav(!nav);
  };

  return (
    <div>
      <nav>
        {/* mobile */}
        <div className={`mobile-navbar ${nav ? "open-nav" : ""}`}>
          <div onClick={openNav} className="mobile-navbar__close">
            <IconX width={30} height={30} />
          </div>
          <ul className="mobile-navbar__links">
            <li>
              <Link onClick={openNav} to="/">
                Home
              </Link>
            </li>
            <li>
              <Link onClick={openNav} to="/">
                About
              </Link>
            </li>
            <li>
              <Link onClick={openNav} to="/">
                Models
              </Link>
            </li>
            <li>
              <Link onClick={openNav} to="/">
                Testimonials
              </Link>
            </li>
            <li>
              <Link onClick={openNav} to="/">
                Our Team
              </Link>
            </li>
            <li>
              <Link onClick={openNav} to="/">
                Contact
              </Link>
            </li>
          </ul>
        </div>

        {/* desktop */}

        <div className="navbar">
          <div className="navbar__img"></div>
          <ul className="navbar__links">
            <li>
              <Link className="home-link" to="/">
                Home
              </Link>
            </li>
            <li>
              <Link className="about-link" to="/">
                About
              </Link>
            </li>
            <li>
              <Link className="models-link" to="/">
                Vehicle Models
              </Link>
            </li>
            <li>
              <Link className="testi-link" to="/">
                Testimonials
              </Link>
            </li>
            <li>
              <Link className="team-link" to="/">
                Our Team
              </Link>
            </li>
            <li>
              <Link className="contact-link" to="/">
                Contact
              </Link>
            </li>
          </ul>
          <div className="navbar__buttons">
            <Link className="navbar__buttons__sign-in" to="/">
              Sign In
            </Link>
            <Link className="navbar__buttons__register" to="/">
              Register
            </Link>
          </div>

          {/* mobile */}
          <div className="mobile-hamb" onClick={openNav}>
            <IconMenu2 width={30} height={30} />
          </div>
        </div>
      </nav>
    </div>
  );
}

export default Navbar;
`
index.js:
`import * as React from "react";
import * as ReactDOM from "react-dom/client";
import Home from "./page";
import {
  createBrowserRouter,
  RouterProvier,
} from "react-roduter-dom";
import "./index.css";

const router = createBrowserRouter([
  {
    path: "/",
    element: <Home />,
  },
]);

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);`

I was doing the navbar with the <Link /> component but it gives me an error which would be what you see in the screenshots, how can I fix it?

**Comment by AlexisThink** [comment]
@angeldevildev Can you share how you solve this error? Or what trigger?

**Comment by smishradev** [comment]
How did you solved it??
