### ISSUE TITLE
[Bug]: In v6.16, NavLink elements throw exceptions upon server-side rendering using the Microsoft ClearScript engine

### ISSUE THREAD

**Issue by OttoG** [remix-run/react-router#10887]
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

Create a React app that uses NavLink components and React Router 6.16.0, and render it using the React renderToString method in a Microsoft ClearScript V8 JavaScript engine – see https://microsoft.github.io/ClearScript/about for information about the engine.

Invoking renderToString will cause the exception "ReferenceError: URL is not defined".

We use Microsoft ClearScript V8 in production for websites, in order to render a React-based user interface, combined with a .NET-based content management system, without having to maintain separate hosting environments for .NET and React SSR.

### Expected Behavior

The app should be rendered by the server-side script engine, which works fine in React Router version 6.15.0, which does not reference the URL API.

It seems unnecessary to reference an API that, while implemented by Node.js, is not implemented by every JavaScript engine, when it is only used in an internal method (encodeLocation) that performs some basic URL manipulation.

It is not immediately obvious to me how the functionality of encodeLocation in packages/react-router-dom/server.tsx and packages/react-router-dom-v5-compat/lib/components.tsx differs between  6.15.0 and  6.16.0, but presumably, any bugs with the  6.15.0 behavior would be possible to fix without introducing the URL API.

### Actual Behavior

This is a sample stack trace from the "ReferenceError: URL is not defined" exception thrown:

    at Object.encodeLocation (Script:51687:69)
    at NavLinkWithRef (Script:51323:59)
    at renderWithHooks (Script:41474:22)
    at renderForwardRef (Script:41614:24)
    at renderElement (Script:41727:15)
    at renderNodeDestructiveImpl (Script:41796:15)
    at renderNodeDestructive (Script:41776:20)
    at renderIndeterminateComponent (Script:41571:13)
    at renderElement (Script:41691:13)
    at renderNodeDestructiveImpl (Script:41796:15)

This happens because commit #8b3559a that is part of version 6.16.0 introduced references to the URL API – https://developer.mozilla.org/en-US/docs/Web/API/URL – which is not implemented by the Microsoft ClearScript V8 engine.

See the following diff: https://github.com/remix-run/react-router/commit/8b3559a50de61a29972ca161a2fccd007441ac58#diff-7ed8b4bc66a4ab5d58e8cf35ffa197dedac618234110203b30cb47c2b835e552

While it might be possible to add a third-party implementation of the URL API to the SSR bundle, it seems to me that a widely used library like React Router should avoid introducing API dependencies for SSR that are not generally needed for React SSR apps. For now, we will just avoid upgrading to 6.16.0, but we would appreciate very much if the dependency could be removed in a future version.

**Comment by timdorr** [comment]
`URL` is implemented in Node: https://nodejs.org/api/url.html#url and has been implemented all the way back to 0.10 (probably before that, even). It's a standard API available in most environments. If this one doesn't have it, that's not really our fault. Same goes for things like `JSON.stringify` or `Map`. 

I would apply a polyfill to supplement for now and petition ClearScript to add that API.

**Comment by miguelski** [comment]
Same problem, i am using deno_core lib to run react in the server, URL is undefined, previous version of encodeLocation was working fine

**Comment by miguelcaravantes** [comment]
corejs polyfill seems to fix the issue in V8

```javascript
import 'core-js/features/url';
import 'core-js/features/url-search-params';
```
