### ISSUE TITLE
[Docs]: Documentation for unstable_useBlocker and unstable_usePrompt missing?

### ISSUE THREAD

**Issue by ePirat** [remix-run/react-router#10885]
### Describe what's incorrect/missing in the documentation

According to one of the last comments on #8139 back from January, documentation for this is worked on "as we speak", however it seems both
`unstable_useBlocker` and `unstable_usePrompt` are still completely undocumented, or I am really bad at searching the documentation.

It would be really great to have these documented, even if not stable, as I spent forever finding them, after finally stumbling over the issue…

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/10831#issuecomment-1701282982

**Comment by ePirat** [comment]
Thanks, that makes sense. Is there any information on what it takes to make these stable?
