### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by billizzard** [remix-run/react-router#10899]
### Describe what's incorrect/missing in the documentation

Simple code from documentation not work

```
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import Menu from './pages/Menu';
import FileList from './pages/FileList';

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Menu />}>
          <Route path="files" element={<FileList />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;

```
On route `/files` or route `/` always render Menu element

documentation: [doc](https://github.com/remix-run/react-router/blob/dev/examples/basic/src/App.tsx)

**Comment by timdorr** [comment]
You need an `Outlet` component most likely.
