### ISSUE TITLE
[Bug]: useBeforeUnload

### ISSUE THREAD

**Issue by WHC198025** [remix-run/react-router#10894]
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

I am new to react router.
I want to alert some text before I route to another page.
However, when I use navigate() to route, nothing happened.
What i do is just the simplest action like this:
  useBeforeUnload(
    React.useCallback(() => {
      alert("hello");
    })
  );
Thanks a lot.

### Expected Behavior

when I use navigate() to route, useBeforeUnload can call the alert("hello")

### Actual Behavior

when I use navigate() to route, useBeforeUnload can't call the alert("hello")

**Comment by brophdawg11** [comment]
This hook is for when the page is unloaded (closing the tab, or performing a full document/MPA navigation to a different page).  It is not for when you are routing between pages in a SPA.  For those, you are probably best with either looking for changes to `useLocation` and/or detecting route components being unmounted via `useEffect`.

* https://reactrouter.com/en/main/hooks/use-before-unload
* https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
