### ISSUE TITLE
[Bug]: `useRouteError` should return `Error | undefined`

### ISSUE THREAD

**Issue by AbraaoAlves** [remix-run/react-router#10910]
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

Try to use `useRouteError` hook inside a `tsx` file. You'll note that the returned value is `unknow` and must be cast before usage.

 

### Expected Behavior

The hook should give the opportunity to developer understand the returned value can be Error or just `undefined`

![image](https://github.com/remix-run/react-router/assets/608731/c873b49c-8e2c-4e75-8f29-5ec176f38eb0 "returned value should be infered like Error or undefined value")

And maybe, give the opportunity to modify what kind of Error developer needs to wait, like this:

![image](https://github.com/remix-run/react-router/assets/608731/cde419c3-f523-46d9-8bc7-401f1bd88c17 "Or hook can be a generic function to enable developer specify what kind of error expect")

  

### Actual Behavior

![image](https://github.com/remix-run/react-router/assets/608731/2cfb7c51-7802-4824-b89d-ef749e5e43f9 "message: (error is typeof `unknow`) after try use return hook value. Its breaks use of Error props in typescript code")

the

**Comment by timdorr** [comment]
It's unknown because it's possible to `throw` anything from your loader or action. It doesn't have to be an `Error`. You need to either add type guards or cast it to a known type.
