### ISSUE TITLE
[Bug]: unstable_viewTransition does nothing

### ISSUE THREAD

**Issue by simPod** [remix-run/react-router#10938]
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

I have added `unstable_viewTransition` to my Link components from react-router-dom (as specified in release notes).

https://stackblitz.com/edit/github-ktzafa?file=src%2FApp.tsx

### Expected Behavior

I'd like to see view transitions.

### Actual Behavior

I don't see any transitions.

**Comment by brophdawg11** [comment]
View Transitions [only work when using `RouterProvider`](https://reactrouter.com/en/main/components/link#unstable_viewtransition)

<img width="635" alt="Screenshot 2023-10-17 at 2 56 30 PM" src="https://github.com/remix-run/react-router/assets/1609022/044dbd14-4ecd-404c-baed-8173c830e485">

You can see an example of them in use here: https://github.com/remix-run/react-router/tree/main/examples/view-transitions

**Comment by simPod** [comment]
Ah I see, thanks. Is there any plan for BrowserRouter support?

**Comment by brophdawg11** [comment]
Not at the moment.  `RouterProvider` is the future-facing API (and is more powerful than `BrowserRouter`) so we generally only add new features there (often times because the new features can only work in a data router landscape).
