### ISSUE TITLE
[Bug]: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format

### ISSUE THREAD

**Issue by chrisboe** [remix-run/react-router#10942]
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

Server side rendering a react (17) app that uses some of the react-router components with `useLayoutEffect` (in react-router code, not ours) triggers this warning. Some examples:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
     at RouterProvider ((...)/node_modules/react-router/lib/components.tsx:90:3)
     at Provider ((...)/node_modules/react-redux/lib/components/Provider.js:21:20)
     (...)
```

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
     at LinkWithRef ((...)/node_modules/react-router-dom/index.tsx:520:7)
     (...)
```

### Expected Behavior

Expected behaviour would be that it renders a hydrate-able tree using SSR without these warnings.

### Actual Behavior

Actual behaviour is that we get lots and lots of these warnings.

We have also tried to upgrade to react 18, and suspect that the `useLayoutEffect` is a culprit of hydration errors because of tree differences. The warnings are present on both react 17 and 18.

**Comment by brophdawg11** [comment]
You need to use [`https://reactrouter.com/en/main/routers/static-router-provider`](https://reactrouter.com/en/main/routers/static-router-provider) during SSR.  `RouterProvider` is for the client side application.
