### ISSUE TITLE
[Bug]: Que conflict with router and setSearchParams

### ISSUE THREAD

**Issue by patriklarssson** [remix-run/react-router#10948]
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

Create a simple page and add a router and a setSearchParams

```
import { useEffect } from "react";
import {
  HashRouter,
  Outlet,
  useRoutes,
  useSearchParams,
  Navigate
} from "react-router-dom";
export default function App() {
  return (
    <HashRouter>
      <Routes />
    </HashRouter>
  );
}
const Routes = () => {
  const [, setSearchParams] = useSearchParams({});
  useEffect(() => {
    // Remove me
    setSearchParams({ lang: "test" });
  }, [setSearchParams]);
  return useRoutes([
    {
      path: "/",
      element: <Outlet />,
      children: [
        {
          path: "",
          element: <Navigate replace to={`/page`} />
        },
        {
          path: `/page`,
          element: <h1>Page</h1>
        }
      ]
    }
  ]);
};
```

### Expected Behavior

Should be redirected to /page and query parameter set to "?lang=test"

### Actual Behavior

Does not route to /page but sets the query parameter correctly
If i wrap the set setSearchParams like this navigation and param works as intended

`setTimeout(() => {setSearchParams({lang}},0)`

**Comment by timdorr** [comment]
`Navigate` and `setSearchParams` call `navigate` under the hood. There is no way for these two calls to communicate their conflicting changes and one will overwrite the other. 

It would be better to use `useNavigate` here and conditionally navigate instead.
