### ISSUE TITLE
Component used for multiple routes is not remounted

### ISSUE THREAD

**Issue by JakobJingleheimer** [remix-run/react-router#10958]
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

```jsx
<Routes>
  <Route path="/forms">
    <Route path="foo" lazy={import('./FormView.jsx')} />
    <Route path="bar" lazy={import('./FormView.jsx')} />
  </Route>
<Routes>
```

When navigating in-app between /forms/foo and /forms/bar, FormView is not re-mounted. This causes FormView's internal state to not get re-set.

### Expected Behavior

The route component should re-mount.

### Actual Behavior

The Route component is only re-rendered.

**Comment by timdorr** [comment]
This isn't a bug, it's just how React works. When you render the same component tree, just with different props or context, it re-uses the state from previous instances.

You will need to look for changes to the location or params to detect when the "page" changes and you should reset some/all of that state.

**Comment by JakobJingleheimer** [comment]
No, this is easily solved if react-router sets a `key` on the route component it instantiates.

**Comment by JakobJingleheimer** [comment]
For anyone encountering this, there's a fairly simple workaround:

```jsx
<Route path="/forms">
  <Route
    lazy={async () => {
      const { Component, ...rest } = await import('./FormView.jsx');
      return { ...rest, element: <Component key="foo" /> };
    }
    path="foo"
  />
  
  <Route
    lazy={async () => {
      const { Component, ...rest } = await import('./FormView.jsx');
      return { ...rest, element: <Component key="bar" /> };
    }
    path="bar"
  />
</Route>
```

**Comment by udbhavgoyal-fareye** [comment]
I am facing the same issue in `react-router@6.20.1`, but it is working fine in `react-router@5.1.2`
