### ISSUE TITLE
[Bug]: state.idx returns NaN sometimes

### ISSUE THREAD

**Issue by ahammer-sc** [remix-run/react-router#10964]
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

I cannot reproduce this easily, but many of my users are reporting issues. I use the window.state.idx to determine whether or not I can go back in the browser history window but stay on my same site, or if i should go back to a fallback url. This allows us to easily use navigate(-1) on modals/etc and go back to where the user was previously, but not go back to say yahoo.com if a user has that in their browser history.

I know idx is internal and not documented, but many [issues](https://github.com/remix-run/react-router/issues/9273), [devs](https://github.com/remix-run/react-router/discussions/9922) and [stackoverflow](https://stackoverflow.com/questions/65948671/how-to-go-back-to-previous-route-in-react-router-dom-v6) answers suggest using it to achieve this "fallback" to a navigate back to keep the user on your site.

I cannot always reproduce on my own machine, but I have debugged in a remote session with a user where `window.history.state.idx` is `NaN` -> but I am expecting it to be 0 or even 1. This happens especially if there is a #hash in the url. Is there any reason why idx should be NaN when a hash is in the url? Is there some possible bug where it gets set to this? 

see also https://github.com/remix-run/react-router/discussions/9067

### Expected Behavior

`window.history.state.idx` should never be a NaN .

### Actual Behavior

`window.history.state.idx` is sometimes a NaN when there is a hash in the url (and only on some machines/browsers)

**Comment by timdorr** [comment]
This isn't something we can support or resolve because it is an internal value and not documented or tested. We may remove it at any time, so you shouldn't rely on it. A better option would be to rely on [`location.key == 'default'`](https://github.com/remix-run/react-router/blob/a23f017ec16b1eb3c622a5549645227066c49e3a/packages/react-router/lib/components.tsx#L413).
