### ISSUE TITLE
[Bug]: useMatch does not work on dynamic routes that use the new "?" optional char

### ISSUE THREAD

**Issue by georgeiliadis91** [remix-run/react-router#10972]
### What version of React Router are you using?

6.17.

### Steps to Reproduce

You can visit this code sandbox I prepared here: https://codesandbox.io/s/react-router-v6-forked-vt8ppc?file=/src/App.js 

### Expected Behavior

When trying to match a route, i expect to be able to pass the exact route declaration string for it to return a match for where I am. 

### Actual Behavior

When using the useMatch hook, and having a dynamic route with optional params 

Example: 
`/apple/:test? ` 

when trying to match it will not match and return null. 

if you remove the "?" it will only match the route when you pass a dynamic one. 

To see this in effect comment and uncomment the lines  18 and 19 on the sandbox provided.

**Comment by timdorr** [comment]
This was already fixed in #10768 and will be in the next release.
