### ISSUE TITLE
[Bug]: Can't install latest version of react-router (react-router@6.18.0)

### ISSUE THREAD

**Issue by Alevale** [remix-run/react-router#10982]
### What version of React Router are you using?

latest

### Steps to Reproduce

`rm -rf node_modules package-lock.json && npm i`

### Expected Behavior

It should install all dependencies

### Actual Behavior

I am getting an error where the latest version of react-router isn't being found.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-router@6.18.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by timdorr** [comment]
This version definitely exists: https://www.npmjs.com/package/react-router/v/6.18.0

This doesn't have to do with the library itself.

**Comment by Alevale** [comment]
Indeed, this seemed to be some kind of hiccup with artifactory (probably on our side)... Thx!
