### ISSUE TITLE
Relative Path Links not working

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/react-router#10998]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
npx --yes create-remix@latest --template --install https://github.com/epicweb-dev/full-stack-foundations/tree/main/exercises/02.routing/02.solution.links link-bug
cd link-bug
npm run dev
```

Open `http://localhost:3000/users/kody/notes`

Notice the "Back to Kody" link changes based on whether you're on `/users/kody/notes` vs `/users/kody/notes/whatever`.

More info here: https://www.loom.com/share/0e7be5f39c4e4e58afacc96feb0fc730

```
<Routes>
  <Route file="root.tsx">
    <Route index file="routes/index.tsx" />
    <Route path="users/kody" file="routes/users+/kody.tsx" />
    <Route path="users/kody/notes" file="routes/users+/kody_+/notes.tsx">
      <Route index file="routes/users+/kody_+/notes.index.tsx" />
      <Route path="some-note-id" file="routes/users+/kody_+/notes.some-note-id.tsx" />
    </Route>
  </Route>
</Routes>
```

Trying to add this to the users/kody/notes route and it's not working the way I want:

```
<Link to=".." relative="path" className="underline">
    Back to Kody
</Link>
```

### Expected Behavior

I expect to be able to use relative="path" and have that be relative to the path of the route I'm rendering within. As @ryanflorence said:

> It should be relative to the “route in context” path, not the url

### Actual Behavior

The relative path is currently relative to the url

**Comment by brophdawg11** [comment]
Fixed by #11006 - will be available in the next release 👍

**Comment by kentcdodds** [comment]
I've verified this is working. Thank you!

**Comment by lpsinger** [comment]
> I expect to be able to use relative="path" and have that be relative to the path of the route I'm rendering within. As @ryanflorence said:
> 
> > It should be relative to the “route in context” path, not the url

I think that [the documentation](https://reactrouter.com/en/main/components/link#relative) is a bit ambiguous on this point:

> By default, links are relative to the route hierarchy (`relative="route"`), so `..` will go up one `Route` level. Occasionally, you may find that you have matching URL patterns that do not make sense to be nested, and you'd prefer to use relative path routing. You can opt into this behavior with `relative="path"`:

Would it be possible to update the docs to clarify that `relative="path"` routing is relative to the path of the current route module, not the full path of the current URL?

**Comment by brophdawg11** [comment]
@lpsinger Thanks for the call out - I just updated the docs to be a bit clearer in c47464c7e51c38cdf21a9fc2db81248daee2d171
