### ISSUE TITLE
[Bug] Redux Store Access Issue When Refreshing the Page in React Router v6

### ISSUE THREAD

**Issue by aksh-22** [remix-run/react-router#10990]
### What version of React Router are you using?

v6

### Steps to Reproduce

1. Navigate to a page in your React Router v6 application.
2. In the loader of that page, attempt to access the Redux store.
3. Use a Link component to navigate to another page within the application.
4. Observe that the Redux store values are accessible when navigating via the Link component.
5. Manually copy the route URL or refresh the page.
6. Notice that when you refresh the page or manually enter the route URL, the Redux store values become undefined.

### Expected Behavior

When refreshing the page or manually entering a route URL, the application should maintain access to the Redux store and its values.

### Actual Behavior

Upon refreshing the page or manually entering a route URL, the application loses access to the Redux store, resulting in undefined values.

**Comment by timdorr** [comment]
There isn't enough info here to go on. But this isn't a bug with React Router.
