### ISSUE TITLE
`Route.ErrorBoundary` is non-compliant

### ISSUE THREAD

**Issue by JakobJingleheimer** [remix-run/react-router#11007]
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

Specify a Route.ErrorBoundary & Route.loader

trigger an error in that Route.loader

### Expected Behavior

ErrorBoundary should behave as a react ErrorBoundary

To achieve this, instantiate a hollow component and throw the error from within it, like:

```jsx
function ThrowErrorFromOutsideLifecycle({ error }) {
  throw error;
}

function TriggerBoundaryNormally({ RouteErrorBoundaryCompliantWithReactErrorBoundary, error }) {
  return (
    <RouteErrorBoundaryCompliantWithReactErrorBoundary>
      <ThrowErrorFromOutsideLifecycle error={error} /
    </RouteErrorBoundaryCompliantWithReactErrorBoundary>
  );
}
```

### Actual Behavior

Errors are not surfaced normally and are instead hidden within a `useRouteError` hook, which is incompatible with an actual `ErrorBoundary`.

**Comment by timdorr** [comment]
This is a naming collision, not a bug. We probably shouldn't have called this `ErrorBoundary`, as it has a different meaning than React's definition. `ErrorComponent` would have been more accurate. It is equivalent to [`errorElement`](https://reactrouter.com/en/main/route/error-element), just running `createElement` for you. It works on `loader` and `action` errors, which exist outside of the React render cycle, so things like `componentDidCatch` don't apply and we cannot be compliant with React's definition of ErrorBoundary.

**Comment by JakobJingleheimer** [comment]
Thanka for your response, but it seems you did not read all of my original message which describes exactly how to do so.

**Comment by brophdawg11** [comment]
> ErrorBoundary should behave as a react ErrorBoundary

As @timdorr said, this naming may be misleading but these *are not* simply React error boundaries.  React error boundaries handle render errors.  `route.ErrorBoundary` handles both data and render errors, which means they have some different behaviors.  We'd be happy to accept a PR for the docs to provide some clarification!

**Comment by JakobJingleheimer** [comment]
> these are not simply React error boundaries. React error boundaries handle render errors.

Okay, but why aren't they. It's a distinction without a difference, except the distinction then requires duplication. The app for sure does not care from where the error originated—something is broken and the app can't recover. You surely chose the name ErrorBoundary because that's what it actually is; but the feature as implemented re-invents that wheel to a merely more complicated but no more sophisticated wheel.

You could easily align your ErrorBoundary with the existing/standard ErrorBoundary, surely removing complexity for both your own library code as well as app code.

**Comment by timdorr** [comment]
No, we cannot "easily" align them with React's `ErrorBoundary` components as they are fundamentally different things. Again, the naming is wrong here. Someone at some point saw `ErrorBoundary` with React and thought similar naming would bring familiarity. But they are different things and that's creating the confusion here.

All this prop does is define a component to show when an error occurs in `loader`/`action`. It's more akin to the `fallback` prop than to the `ErrorBoundary` component. We should have called it `ErrorComponent` or `FallbackComponent` instead.

**Comment by brophdawg11** [comment]
Agreed, this is a naming confusion issue, not a functional issue.

> no more sophisticated wheel

This is simply not true.  React error boundaries handle strictly [client side](https://github.com/facebook/react/issues/23184) rendering errors.  Remix/React Router `ErrorBoundary`'s build on top of this and add support for data errors in loader/actions and SSR support.
