### ISSUE TITLE
How to route paths with colon?

### ISSUE THREAD

**Issue by Nosferatu31** [remix-run/react-router#11015]
### What version of React Router are you using?

v6.18.0

### Steps to Reproduce

Using paths such as `/test::id` where I want the colon to be added to the path

### Expected Behavior

Parse routes such as: `/test:123`

### Actual Behavior

Does not work

**Comment by Nosferatu31** [comment]
I am aware that RegExp-style routes were removed on v6, but will characters such as `:` be supported in the future?

**Comment by timdorr** [comment]
No, because `:` is a reserved character in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) and cannot be used without URL encoding.

**Comment by tesaguri** [comment]
> No, because `:` is a reserved character in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) and cannot be used without URL encoding.

While `:` cannot be used in arbitrary position of an IETF URI, the `pchar` ABNF rule that is used in the path component explicitly includes the colon character:

```abnf
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

So `:` is valid in the path component without being percent-encoded.

**Comment by tesaguri** [comment]
And FYI, the WHATWG [URL Pattern API](https://developer.mozilla.org/docs/Web/API/URL_Pattern_API) supports literal colons with an escape syntax like `"/test\\::id"`.
