### ISSUE TITLE
[Bug]: useLocation() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by sdomino** [remix-run/react-router#11016]
### What version of React Router are you using?

"react-router-dom": "^6.15.0"

### Steps to Reproduce

Given the following component:

```
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

export const ScrollToTop = () => {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
};
```

When imported from a local project directory it works just fine. However, when imported from a remote package we get the following error:

`useLocation() may be used only in the context of a <Router> component`

Local Import (WORKS):
```
import { ScrollToTop } from './utils/ScrollToTop';
// import { ScrollToTop } from '@crew/owen';

export const App: FunctionComponent = () => {
  return (
    <BrowserRouter>
      <ScrollToTop />
      <Routes>
        <Route path='/' element={<InitialScreen />}>
```

Remote package import (DOES NOT WORK):
```
// import { ScrollToTop } from './utils/ScrollToTop';
import { ScrollToTop } from '@crew/owen';

export const App: FunctionComponent = () => {
  return (
    <BrowserRouter>
      <ScrollToTop />
      <Routes>
        <Route path='/' element={<InitialScreen />}>
```

Both projects are using the same version of `react-router-dom` ("^6.15.0")

### Expected Behavior

We'd expect the component to be usable when imported from a remote packge the same as when it's being imported from a local file.

### Actual Behavior

We get the following error:

`useLocation() may be used only in the context of a <Router> component`

**Comment by timdorr** [comment]
You have two instances of react-router-dom in your tree somehow. You can confirm this with `npm ls react-router-dom`.

**Comment by sdomino** [comment]
Hi @timdorr, thanks for the response!

I see it in there twice:

![Screenshot 2023-11-21 at 9 44 36 AM](https://github.com/remix-run/react-router/assets/28181/5b1398fa-f03c-4c1d-b554-6d8010fc6268)

Sorry, probably a dumb question, but is it a `react-router-dom` specific thing that it can only be in the tree once? I can select almost any other package and it's in the tree multiple times (`prettier` (4x), `eslint` (12x), `lodash` (12x), `react` (>24x), etc... ) and doesn't seem to cause issues.

**Comment by pedroleung** [comment]
> Hi @timdorr, thanks for the response!
> 
> I see it in there twice:
> 
> ![Screenshot 2023-11-21 at 9 44 36 AM](https://private-user-images.githubusercontent.com/28181/284659714-5b1398fa-f03c-4c1d-b554-6d8010fc6268.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTM2NzcsIm5iZiI6MTcwNDY5MzM3NywicGF0aCI6Ii8yODE4MS8yODQ2NTk3MTQtNWIxMzk4ZmEtZjAzYy00YzFkLWI1NTQtNmQ4MDEwZmM2MjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNmM1NTk4NmFiNmQxZTQ5ZWE3N2NlNWQ2MTZmMzY2NjI0YTZjNDVkYTY5OTBhOGYwMzhhMGY3ZDQ3NzBkZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYbXBYnv5eXM0OyqDdX1o8-YHminLFGb6kmPy7o2t1c)
> 
> Sorry, probably a dumb question, but is it a `react-router-dom` specific thing that it can only be in the tree once? I can select almost any other package and it's in the tree multiple times (`prettier` (4x), `eslint` (12x), `lodash` (12x), `react` (>24x), etc... ) and doesn't seem to cause issues.

Hey @sdomino were you able to solve this issue? I am facing a similar issue, but in my case it's the opposite. It works on remote package, but it doesn't work locally.
Locally it's a monorepo project.

**Comment by iest** [comment]
@sdomino I had the same issue — you probably figured it out by now, but you want to make sure that there aren't different versions of the same package. As long as the versions all match, the same module should be used everywhere.

**Comment by jonaldinger** [comment]
Thanks @timdorr for pointing me in the right direction! For anyone using Yarn workspaces, you need to make sure the installed _instances_ are all the same, in addition to the version numbers. `yarn why -R react-router` (or `react-router-dom` for older versions) will list out the deps tree. The circled SHAs below are the mismatched instances of the same dependency/version, which is what should be avoided. In my case the bug only occurred in production builds, which made it extra tricky to track down.

![Image](https://github.com/user-attachments/assets/b1e2effc-3625-43c0-b71a-43607b1db513)

**Comment by jonaldinger** [comment]
My issue wound up being that I had two different versions of `@types/react-dom` specified across workspaces. It seems that because `react-router` lists `react-dom` as a peer dependency, Yarn was being highly defensive with the resolutions and creating multiple instances of the same version of `react-router` 😵‍💫. Aligning my versions of `@types/react-dom` resolved the multiple instances of `react-router`. See: https://github.com/yarnpkg/berry/issues/6229

**Comment by cbotsikas** [comment]
Great hint about the two instances. 
We had a similar issue in a turborepo when we moved some navigation code to the shadcn ui package and we added the "react-router" as a regular dependency instead of a peerDependency.
It was only broken on build output.
