### ISSUE TITLE
`useActionData` receives data from wrong `action`

### ISSUE THREAD

**Issue by MoSattler** [remix-run/react-router#11022]
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- [Stackblitz](https://stackblitz.com/github/MoSattler/remix-repro/tree/repro-form-dupli?file=README.md)
- [GH Reproduction Branch](https://github.com/MoSattler/remix-repro/tree/repro-form-dupli)

Steps:
1. Submit `parent.tsx` (and notice that it posts to the correct action handler)
2. Go to /parent/child
3. Submit `parent.child.tsx` and notice that `parents.tsx` also updates to data from `parent.child.tsx`

### Expected Behavior

that the component in `parent.tsx` only gets data from the action defined in `parent.tsx`.

### Actual Behavior

When submitting `parent.child.tsx`, the component in `parent.tsx` receives data from `action` in `parent.child.tsx`.

https://github.com/remix-run/remix/assets/64152453/a8112b61-549e-4d32-90f3-9d3a6bab6efb

**Comment by brophdawg11** [comment]
This is fixed by #11023 and will be available in the next release 👍

**Comment by nicolas-besnard** [comment]
This doesn't seem to be a bug, but rather a feature. Looking at the `useActionData` documentation ( https://remix.run/docs/en/main/hooks/use-action-data#useactiondata):

> Returns the serialized data from the most recent route action or undefined if there isn't one.

**Comment by brophdawg11** [comment]
@nicolas-besnard - _"most recent route action"_ is referring to the current contextual route in context, not _any_ route in the tree.  Otherwise, `useActionData<typeof action>();` would be completely unreliable since the action data could be from any acton function in the app - not the specific action you are typing it with (the one for that route).
