### ISSUE TITLE
[Docs]: Lack of Documentation for useNavigation formAction and formMethod Properties

### ISSUE THREAD

**Issue by thecode00** [remix-run/react-router#11036]
### Describe what's incorrect/missing in the documentation

page: https://reactrouter.com/en/main/hooks/use-navigation

```javascript
import { useNavigation } from "react-router-dom";

function SomeComponent() {
  const navigation = useNavigation();
  navigation.state;
  navigation.location;
  navigation.formData;
  navigation.json;
  navigation.text;
  navigation.formAction;
  navigation.formMethod;
}
```

In the provided example in the documentation, these properties are used, but there is no corresponding documentation explaining their functionality.

Thank you for your attention to this matter.

**Comment by KubasuIvanSakwa** [comment]
I also had heard a pr about useLocation where I requested for more explanation about the properties but we ended up just adding to the type declaration so maybe you can include a type declaration

**Comment by brophdawg11** [comment]
Documentation PR's are always welcome if you'd like to take a stab at adding sections for these fields!
