### ISSUE TITLE
v3_fetcherPersist is re-executing fetchers that should be cleaned up

### ISSUE THREAD

**Issue by dmarkow** [remix-run/react-router#11043]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-uglfw8?file=app%2Froutes%2Ftasks.tsx

Click the Tasks link. Delete a task without editing it first and there is no error. Next, edit a task. This first gets the current version from the server via a fetcher, then displays a form with that data. Hit save, then delete that same task and an error will be triggered. Even though `<FetchEditTask />` is unmounted and its fetcher is idle, it's still making a request to `/resources/tasks/${id}` with the id of the deleted record. This raises a "not found" error on the server.

This only happens with v3_fetcherPersist turned on.

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.84 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.asdf/installs/nodejs/20.9.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.9.0/bin/yarn
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
    bun: 1.0.11 - ~/.bun/bin/bun
    Watchman: 2023.11.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 119.0.6045.159
    Edge: 119.0.2151.72
    Safari: 17.1
  npmPackages:
    @remix-run/dev: ^2.3.0 => 2.3.0
    @remix-run/eslint-config: ^2.3.0 => 2.3.0
    @remix-run/node: ^2.3.0 => 2.3.0
    @remix-run/react: ^2.3.0 => 2.3.0
    @remix-run/serve: ^2.3.0 => 2.3.0
    vite: ^5.0.0 => 5.0.0
```

### Used Package Manager

yarn

### Expected Behavior

An idle/completed fetcher on an unmounted component should not make another network request.

### Actual Behavior

Network requests are being made on fetchers that are unmounted and idle, which can trigger error boundaries if it tries to load non-existent/deleted data.

**Comment by brophdawg11** [comment]
This is fixed in #11044 and will be available in the next release
