### ISSUE TITLE
[Bug]:  import {redirect } from 'react-router-dom'

### ISSUE THREAD

**Issue by Renstrio24p** [remix-run/react-router#11041]
### What version of React Router are you using?

v6

### Steps to Reproduce

```js
import { redirect } from "react-router-dom"
export async function requireAuth() {
    const isLoggedIn = false
    if (!isLoggedIn) {
        throw redirect("/login")
    }
}
```

is not working when I'm using webpack 5 with esbuild-loader

### Expected Behavior

I write this code to protect my routes especially when I write this code in webpack 5 as a bundler
```js
import { redirect } from "react-router-dom"

export async function requireAuth() {
    const isLoggedIn = false
    
    if (!isLoggedIn) {
        throw redirect("/login")
    }
}
```
then this error appears not expected to happened
```
Unexpected Application Error!
{"type":"default","status":302,"ok":false,"statusText":"","headers":{"map":{"location":"/login"}},"url":"","bodyUsed":false,"_bodyInit":null,"_bodyText":""}

💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```
when I use vite this code works fine

how to fix this error on webpack 5 + react? 

### Actual Behavior
```
Unexpected Application Error!
{"type":"default","status":302,"ok":false,"statusText":"","headers":{"map":{"location":"/login"}},"url":"","bodyUsed":false,"_bodyInit":null,"_bodyText":""}

💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```
expected to route in /login

**Comment by timdorr** [comment]
This isn't a bug with a React Router. If your build tooling is giving the error, then something is wrong with that setup.

**Comment by arkamaldeen** [comment]
Hi! I was facing the same issue any solution?
@Renstrio24p

**Comment by AnukaSamuditha** [comment]
> ### What version of React Router are you using?
> v6
> 
> ### Steps to Reproduce
> ```js
> import { redirect } from "react-router-dom"
> export async function requireAuth() {
>     const isLoggedIn = false
>     if (!isLoggedIn) {
>         throw redirect("/login")
>     }
> }
> ```
> 
> is not working when I'm using webpack 5 with esbuild-loader
> 
> ### Expected Behavior
> I write this code to protect my routes especially when I write this code in webpack 5 as a bundler
> 
> ```js
> import { redirect } from "react-router-dom"
> 
> export async function requireAuth() {
>     const isLoggedIn = false
>     
>     if (!isLoggedIn) {
>         throw redirect("/login")
>     }
> }
> ```
> 
> then this error appears not expected to happened
> 
> ```
> Unexpected Application Error!
> {"type":"default","status":302,"ok":false,"statusText":"","headers":{"map":{"location":"/login"}},"url":"","bodyUsed":false,"_bodyInit":null,"_bodyText":""}
> 
> 💿 Hey developer 👋
> 
> You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
> ```
> 
> when I use vite this code works fine
> 
> how to fix this error on webpack 5 + react?
> 
> ### Actual Behavior
> ```
> Unexpected Application Error!
> {"type":"default","status":302,"ok":false,"statusText":"","headers":{"map":{"location":"/login"}},"url":"","bodyUsed":false,"_bodyInit":null,"_bodyText":""}
> 
> 💿 Hey developer 👋
> 
> You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
> ```
> 
> expected to route in /login

Did you find any solution for this?

**Comment by AnukaSamuditha** [comment]
> Hi! I was facing the same issue any solution? @Renstrio24p

Did you find any solution for this?

**Comment by Renstrio24p** [comment]
I solve this I just change throw with navigate

**Comment by carsaig** [comment]
Same issue here...any solution?
