### ISSUE TITLE
[Bug]: Unhandled error when throwing read responses

### ISSUE THREAD

**Issue by mbwestphal** [remix-run/react-router#11055]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

- Handle errors in an error element
- In any loader: Read the body of a Response using `.json()` or `.text()`
- Throw that response

### Expected Behavior

The error element catches _something_. Maybe even exactly the error of reading from an already consumed response.

### Actual Behavior

The error element does not catch anything.

Instead an error is printed to the console:

```
Uncaught (in promise) TypeError: Response.text: Body has already been consumed.
```

**Comment by brophdawg11** [comment]
This is resolved by #11061 and will be available in the next release
