### ISSUE TITLE
[Bug]:React Router caught the following error during render ReferenceError: “ShadowRoot”未定义 [object Object]（ ie11）

### ISSUE THREAD

**Issue by ZHYCH992** [remix-run/react-router#11056]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

import React, {lazy, Suspense} from 'react';
import {createHashRouter, RouterProvider} from 'react-router-dom';
import Home from './../page/Home.jsx';

const UserRouter = () => {
	const WapTable = lazy(() => import('../page/WapTable.jsx'));

	const router = createHashRouter([
		{
			path: '/',
			element: <Home />,
		},
		{
			path: '/info/:time',
			element: (
				<Suspense>
					<WapTable />
				</Suspense>
			),
		},
	]);
	return <RouterProvider router={router} />;
};
export default UserRouter;

### Expected Behavior

兼容ie11

### Actual Behavior

![Dingtalk_20231124171007](https://github.com/remix-run/react-router/assets/112610680/021e19ef-6236-485c-a261-74f815874e9e)

**Comment by timdorr** [comment]
This isn't a bug with React Router.
