### ISSUE TITLE
[Bug]: Cannot include a '#' character in a manually specified `to.search` field

### ISSUE THREAD

**Issue by cseas** [remix-run/react-router#11068]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

Use the navigate hook and add a `#` character in the search parameter.

```ts
import { useLocation, useNavigate, useParams } from 'react-router-dom';
...
const navigate = useNavigate();
...
navigate({
  hash,
  pathname,
  search: 'abcd#123'
})
```

### Expected Behavior

I'm using this code in a search input where adding `#` to the input is a valid search. This used to work in earlier version of react router but the search doesn't seem to support special characters anymore after upgrading to react-router-dom v6.

### Actual Behavior

Error is thrown and no navigation is triggered.

**Comment by timdorr** [comment]
That is not a valid part of the search string. You're mixing two separate sections of the location in a single field, so internal parsing logic won't work.

**Comment by cseas** [comment]
Found a workaround. If we encode the search string then it works fine.

```tsx
navigate({
  hash,
  pathname,
  search: encodeURIComponent('abcd#123')
})
```

Subsequently the code where this query parameter is getting read also needs to be updated to be: `decodeURIComponent(value)`.
