### ISSUE TITLE
[Bug]: ScrollRestoration doesn't work with scrollable <div> with fixed position

### ISSUE THREAD

**Issue by guoyunhe** [remix-run/react-router#11072]
### What version of React Router are you using?

6.x

### Steps to Reproduce

If you make a fixed layout:

```html
<html>
<head>
<style>
#navbar {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 50px;
}

#sidebar {
  position: fixed;
  left: 0;
  top: 50px;
  width: 200px;
  height: calc(100vh - 50px);
}

#root {
  position: fixed;
  top: 50px;
  left: 0;
  width: 100vw;
  height: calc(100vh-50px);
  overflow: auto;
}
</style>
</head>
<body>
  <nav id="navbar"></nav>
  <div id="root"></div>
  <aside id="sidebar"></aside>
</body>
</html>
```

and you mount your React app on `#root`.

### Expected Behavior

<ScrollRestoration> should work.

### Actual Behavior

<ScrollRestoration> doesn't work.

**Comment by timdorr** [comment]
ScrollRestoration only works on the page's scroll position. If you want the position retained on that specific element, that is something you have to implement yourself.
