### ISSUE TITLE
[Bug]: Upgrading from v5 hashType="noslash"?

### ISSUE THREAD

**Issue by Lugribossk** [remix-run/react-router#11076]
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

I'm trying to upgrade a project that uses react-router-dom v5.3.4 to v6.20.0. It uses `<HashRouter hashType="noslash">` for the router. I can't seem to find a way to configure `createHashRouter` to behave in the same way where the routes do not have a leading slash.
Is this a breaking change in v6? It's not mentioned in the [v5 upgrade guide](https://reactrouter.com/en/main/upgrading/v5) or the changelog for v6.
And no, changing the routes is not an option at this point.

### Expected Behavior

Some option to be able to continue using hash routes without a leading slash.

### Actual Behavior

Routes suddenly have a leading slash.

**Comment by timdorr** [comment]
This is a side effect first of upgrading to `history` 5 (which doesn't have this option) and then internalizing the history management in `@remix-run/router`.

There is no plan to support this prior behavior. If you need it, I would stick with React Router 5.
