### ISSUE TITLE
[Bug]: Hook `useRouteLoaderData` causes unnecessary re-renders on Remix app during revalidation

### ISSUE THREAD

**Issue by mikkpokk** [remix-run/react-router#11075]
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

**Create a clean project**

```
npx create-remix@latest
```

**Use following root.tsx**

```tsx
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";
import {LoaderFunction} from '@remix-run/node'
import Test from '~/component/Test'

// For testing purpose always true
export const shouldRevalidate = () => {
  return true
}

export const loader: LoaderFunction = () => {
  return {
    user: {
      id: 1,
      name: 'Test',
    }
  }
}

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body>
        <Test/>
        <Outlet />
        <ScrollRestoration />
        <LiveReload />
        <Scripts />
      </body>
    </html>
  );
}
```

**Create a Test component which calls useRouteLoaderData**

_app/component/Test/index.tsx_
```tsx
import {useRouteLoaderData} from '@remix-run/react'
import {memo} from 'react'

const Test = memo(() => {
    const data = useRouteLoaderData('root')

    console.log('Render')

    return (
        <div className={style.Test}>
            {JSON.stringify(data)}
        </div>
    )
})

export default Test
```

**Create new route file**

_app/routes/test.tsx_
```tsx
import type { MetaFunction } from "@remix-run/node";
import Test from '~/component/Test'
import {Link} from '@remix-run/react'

export const meta: MetaFunction = () => {
    return [
        { title: "Test page" },
    ];
};

export default function Index() {
    return (
        <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
            <h1>Welcome to Remix</h1>
            <ul>
                <li>
                    <Link to={'/'}>
                        Index
                    </Link>
                </li>
            </ul>
        </div>
    );
}
```

**Add link to index route file**

app/routes/_index.tsx
```tsx
// ...
    <li>
        <Link to={'/test'}>
            Test
        </Link>
    </li>
// ...
```

### Expected Behavior

On route change, Test component should not re-render at all because root data stays unchanged. 

Seems like context is missing useMemo, instead it passes every change to provider and forces all tree to re-render. Most interesting part is that React profiler catches context modification twice (also "Render" triggers twice on console + extra 2x times on development due to React.StrictMode).

### Actual Behavior

Re-renders <Test/> component twice (with React.StrictMode x4)
<img width="303" alt="image" src="https://github.com/remix-run/react-router/assets/14272312/18027dd3-f4c4-4b48-a6d6-4185a25d45bd">

**Comment by timdorr** [comment]
This is expected behavior. Because the loader may call on external data sources (APIs, in particular), we must fetch all loaders in the current tree on each route change. 

https://reactrouter.com/en/main/route/loader

> As the user navigates around the app, the loaders for the next matching branch of routes will be called in parallel and their data made available to components through [useLoaderData](https://reactrouter.com/en/main/hooks/use-loader-data).

**Comment by mikkpokk** [comment]
@timdorr Expected behaviour is loader to re-fetch an external data resources. 

However, I think it is not expected to re-render whole app when data has not been changed. That's what currently implemented context does without applying memoized function.
