### ISSUE TITLE
[Docs]: how can i get req.headers in router array?

### ISSUE THREAD

**Issue by VISHALl1166** [remix-run/react-router#11083]
### Describe what's incorrect/missing in the documentation

express server req.headers shows cookies but unable to send these cookies with fetch request in router array loader funtion

**Comment by timdorr** [comment]
This is covered with `createStaticRouter` and it's `context` parameter: https://reactrouter.com/en/main/routers/create-static-router

**Comment by timdorr** [comment]
And you probably want to read the SSR doc: https://reactrouter.com/en/main/guides/ssr

**Comment by VISHALl1166** [comment]
![image](https://github.com/remix-run/react-router/assets/68598311/e5f61691-8050-453e-9a0b-6f13f8e1e3e6)
here are my codes how can i access req.headers in routes array loader function
![image](https://github.com/remix-run/react-router/assets/68598311/ac2e7118-d1bc-4088-b2c6-1fa8cead1915)
