### ISSUE TITLE
[Docs]: how can i access req.headers in loader function ?

### ISSUE THREAD

**Issue by VISHALl1166** [remix-run/react-router#11084]
### Please help me how can get header cookies in fetch function

![image](https://github.com/remix-run/react-router/assets/68598311/833f01e9-4a6b-4dea-bf3b-37927b36b6e6)
![image](https://github.com/remix-run/react-router/assets/68598311/ef60f8d3-1609-47a7-9812-b6baf8af7800)
please help me how can i get headers in loader function

**Comment by brophdawg11** [comment]
Your loader receives a [`request`](https://reactrouter.com/en/main/route/loader#request) which is just a [Fetch Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) so you can use [`request.headers`](https://developer.mozilla.org/en-US/docs/Web/API/Request/headers)
