### ISSUE TITLE
[Bug]: redirect method not working

### ISSUE THREAD

**Issue by iambijayd** [remix-run/react-router#11096]
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

In the function below, I want the user to be redirected to `/manage-room` after receiving a response from the server. The user gets created in the database, and a toast notification fires successfully, but the redirect does not work. I also tried using throw, but it is not working. I am using Vite 4.4.5. 
```
async function handleSubmit(e) {
		e.preventDefault();
		if (playerName.length < 4) {
			setError({ message: 'Name must be of 4 characters' });
		} else {
			const response = await axios.post(
				SERVER_URL + '/create-player',
				{ name: playerName },
				{
					withCredentials: true,
				}
			);
			setPlayerName('');
			if (response.data?.statusCode == 201) {
				toast(response.data?.message, {
					type: toast.TYPE.SUCCESS,
					autoClose: 2000,
					closeButton: false,
				});
				return redirect('/manage-room');
			}
		}
	}
```

### Expected Behavior

`redirect('/manage-room')` should redirect the user to `manage-room` route.

### Actual Behavior

`redirect()` is doing nothing.

**Comment by timdorr** [comment]
Based on your function name and calling `preventDefault()`, it seems like you're doing this in a form `onSubmit` handler. `redirect` only works in `action` or `loader` functions.
