### ISSUE TITLE
initialPath / rootUrl option

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#111]
I haven't tested this, but I'm pretty sure we can't handle an app starting at a deep url already.

For example, we're building a new feature that starts at `/courses/123/files`, hash urls will be fine, but as soon as we turn on `location="history"` it's probably not going to work.

I suspect we'll need `<Route rootPath="/courses/123/files"/>`

**Comment by Davorak** [comment]
> writing the whole path on the routes is not actually all that bad, closing until more squeaky wheels show up.

@ryanflorence - Consider this one more squeaky wheel in the application I am working I want to be able to host everything on a suburl.  Currently use a slightly modified version of Link and have a helper function that I mostly remember to use when using history.push and friends.

**Comment by taion** [comment]
This is a really ancient issue! We have this concept – it's called `basename` now. Check the current docs.

**Comment by dverbru** [comment]
See https://github.com/ReactJSTraining/history/blob/master/docs/BasenameSupport.md.
