### ISSUE TITLE
useRoutes错误

### ISSUE THREAD

**Issue by renjiali68666** [remix-run/react-router#11103]
### What version of React Router are you using?

6.20.1

### Steps to Reproduce

```
import { Suspense } from "react";
import { BrowserRouter, useRoutes } from "react-router-dom";
import LoadingView from "@/components/Loading";
import { router } from "@/router";

const Router = () => {
  return useRoutes(router);
};

const App = () => {
  return (
    <Suspense fallback={<LoadingView />}>
      <BrowserRouter>
        <Router></Router>
      </BrowserRouter>
    </Suspense>
  );
};
export default App;



import { redirect, type RouteObject } from "react-router-dom";

export const router: RouteObject[] = [
  {
    path: "/",
    lazy: () => import("@/layout"),
    children: [
      {
        index: true,
        loader: () => redirect("/Dashboard"),
      },
      {
        path: "/Dashboard",
        lazy: () => import("@/views/Dashboard"),
      },
    ],
  },
];



layout.tsx
import { Outlet } from "react-router-dom";

export const Component = () => {
  return <Outlet></Outlet>;
};

```

### Expected Behavior

normal

### Actual Behavior

App.tsx:7 Matched leaf route at location "/" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.
warning @ react-router-dom.js?t=1701997788572&v=f5f84842:213
useRoutesImpl @ react-router-dom.js?t=1701997788572&v=f5f84842:3401
useRoutes @ react-router-dom.js?t=1701997788572&v=f5f84842:3358
Router @ App.tsx:7
renderWithHooks @ chunk-MCEUSTYS.js?v=f5f84842:12169
mountIndeterminateComponent @ chunk-MCEUSTYS.js?v=f5f84842:14919
beginWork @ chunk-MCEUSTYS.js?v=f5f84842:15900
beginWork$1 @ chunk-MCEUSTYS.js?v=f5f84842:19747
performUnitOfWork @ chunk-MCEUSTYS.js?v=f5f84842:19192
workLoopSync @ chunk-MCEUSTYS.js?v=f5f84842:19131
renderRootSync @ chunk-MCEUSTYS.js?v=f5f84842:19110
performConcurrentWorkOnRoot @ chunk-MCEUSTYS.js?v=f5f84842:18672
workLoop @ chunk-MCEUSTYS.js?v=f5f84842:195
flushWork @ chunk-MCEUSTYS.js?v=f5f84842:174
performWorkUntilDeadline @ chunk-MCEUSTYS.js?v=f5f84842:382
显示另外 14 个框架
收起
installHook.js:1 Matched leaf route at location "/" does not have an element or Component. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.

**Comment by timdorr** [comment]
The error message here is explaining exactly what is happening. You need an element for your index route so something is rendered.
