### ISSUE TITLE
[Bug]: Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by etlovett** [remix-run/react-router#11110]
### What version of React Router are you using?

6.20.1

### Steps to Reproduce

Have an app with the following code:
```
const router = createBrowserRouter([
  {
    element: <Homepage />,
    path: '/',
  },
  {
    element: <div>Page A</div>,
    path: '/a',
  },
  {
    element: <div>Page B</div>,
    path: '/b',
  },
])
function Homepage() {
  return (
    <div>
      Homepage, <Link to="/a">Page A</Link>, <Link to="/b">Page B</Link>
    </div>
  )
}
function App() {
  return <RouterProvider router={router} />
}

const container = document.getElementById('root')
if (!container) {
  document.body.textContent = 'Unable to find root element'
  throw new Error('Unable to find root element')
}
const root = createRoot(container)
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
```

Load the `/` route, click the link to page A (`/a`), then use browser buttons or keyboard shortcuts to go back and forth in history between `/` and `/a`.

### Expected Behavior

I expect to be able to go back and forth without issue.

### Actual Behavior

I get the following error:
```
Error handled by React Router default ErrorBoundary: DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

### Other Context

There is one related issue: https://github.com/remix-run/react-router/issues/8834. That one was closed as not being a bug in React Router, but I believe there is actually a bug in React Router given that a test case as simple as the one above fails.

Interestingly, either one of the following two changes will prevent this issue from occurring:
* Inlining the `Homepage` component in the `createBrowserRouter` array argument, as `element: <div>Homepage, <Link to="/a">Page A</Link>, <Link to="/b">Page B</Link></div>`
* Wrapping the `<RouterProvider router={router} />` in a `<div>` in `App`

Given the second prevention method and the comments on that related issue, I suspect the bug may be caused by my sample code having this React Fragment as the top-most entry in `App`'s React tree: https://github.com/remix-run/react-router/blob/c47464c7e51c38cdf21a9fc2db81248daee2d171/packages/react-router-dom/index.tsx#L671.

Having an app structure this simple is a pretty rare case, however, so I'll leave it up to you to decide if it's worth fixing, or just documenting, or none of the above. Thanks for building and maintaining such a great library!

**Comment by brophdawg11** [comment]
Can you provide a reproduction of the issue?  I copied your code above into a codesandbox and it seems to be working fine for me navigating back and forth with my mouse buttons and browser back/forward buttons.  Make sure you open the preview in a new window to get out of the codesandbox iframe/mocked location weirdness which doesn't update the URL and back/forward can be weird.

https://codesandbox.io/p/sandbox/dazzling-ganguly-v87d3j?file=%2Fsrc%2Findex.js%3A41%2C1

**Comment by JanHmmr** [comment]
"Wrapping the <RouterProvider router={router} /> in a <div> in App"

This saved my ass, thank you!!!
