### ISSUE TITLE
[Bug]: Vite with react not working for basename with react-router-dom after build

### ISSUE THREAD

**Issue by dreygur** [remix-run/react-router#11116]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

main.jsx
```jsx
import ReactDOM from "react-dom/client";
import { RouterProvider } from "react-router-dom";
import { router } from "./routes/routes";

ReactDOM.createRoot(document.getElementById("root")).render(
  <RouterProvider router={router} />
);
```

routes.jsx
```jsx
import { createBrowserRouter, redirect } from "react-router-dom";
import Main from "../Layout/Main";
import Home from "../pages/Home";
import Login from "../pages/Login";
import Recovery from "../pages/Recovery";
import Signup from "../pages/Signup";
import ErrorPage from "../pages/ErrorPage";

const routes = [
  {
    path: "/",
    element: <Main />,
    errorElement: <ErrorPage />,
    children: [
      {
        path: "/",
        element: <Home />,
      },
      {
        path: "/login",
        element: <Login />,
      },
      {
        path: "/reset",
        element: <Recovery />,
      },
      {
        path: "/signup",
        element: <Signup />,
      },
    ],
  },
];

export const router = createBrowserRouter(routes, {
  basename: "/packers"
});
```

vite.config.js
```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import svgr from "vite-plugin-svgr";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), svgr()],
  base: '/packers'
});
```

### Expected Behavior

The project should render the assets after build

### Actual Behavior

Not rendering assets after build

**Comment by dreygur** [comment]
Also created a question on stack: https://stackoverflow.com/q/77655971/7277428

**Comment by valzzu** [comment]
I got similar issue here's a image of the code
![image](https://github.com/remix-run/react-router/assets/52419539/718d37c7-6797-41c5-85c2-620e47ff4934)

everything works locally fine but when i built it and uploaded to a server it stopped working.

![recording of what is happening](https://github.com/remix-run/react-router/assets/52419539/cc077b0b-7fac-41f9-90dd-b936d5f67aa6)

**Comment by dreygur** [comment]
> Could you provide a working reproduction of the issue? Vite + basename works fine for me in the `examples/basic` example in the repository

you can check this one: https://github.com/andrekgb/field-logger/tree/main

**Comment by brophdawg11** [comment]
Oh - this is production mode.  When in dev, the vite server handles the base path for you.  But for your production builds you need to handle that since `vite` only generates an `index.html` file for you - you own the server.

Basically, the stuff vite outputs to `dist` needs to be served from `/field-logger` in your case.  How you do it will depend on your server setup.  You could do this via [express](https://expressjs.com/en/starter/static-files.html), or you could just move the files there after the build:

```
npm run build
cd dist
mkdir field-logger
mv index.html field-logger/
mv assets field-logger/
npx http-server .

```

Then you should be able to access your app at http://localhost:8081/field-logger

**Comment by dreygur** [comment]
@brophdawg11 I wonder if you really understood the problem. I mentioned in title that the issue is occurring after build. So, obviously it's in production. And I have previously used `<BrowserRouter>` which worked fine. The issue is with `createBrowserRouter()`

Could I explain the issue?

**Comment by brophdawg11** [comment]
From what you have provided, I do not think this is related to `BrowserRouter`/`createBrowserRouter`.  No matter which you use, when you run `npm run build`, `vite` is going to generate an `index.html` file for you which is expecting to be loaded at the base path of `/field-logger/`.  You need to configure your server to serve that `index.html` file at that base path.  

I don't see a server nor any `npom run start`/`npm run serve` scripts in your reproduction repo so I can't be sure how you are currently intending to serve your application in production.

The following express server works for the production build of your repository:

```js
const express = require("express");
const app = express();

// Serve dist/ files from the /field-logger/ base path
app.use("/field-logger/", express.static("dist"));

// If desired, you can also redirect the root path to the proper base path
app.use("/", (req, res) => res.redirect("/field-logger/"));

app.listen(8081);
```

As mentioned in https://github.com/remix-run/react-router/issues/11116#issuecomment-1856805850, this is effectively the same as serving the files statically from `dist/field-logger/`

> the issue is occurring after build. So, obviously it's in production

Vite builds your app in development as well 😉

**Comment by rinkeshjain** [comment]
@dreygur  

while creating a build you need to pass the base name 

`vite build --base=/packers`

**Comment by rajsawhoney** [comment]
Hi @dreygur 
If anyone still facing this issue, can do the following to get it working.
I am using aws amplify for hosting my react(1) and next.js(2) app.
www.myapp.com=> base next.js app
www.myapp.com/user/<*>=> user next.js app
www.myapp.com/enterprise/<*>=> enterprise vite react app

And I am using next.js feature for rewrite rules to achieve this.

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import svgr from "vite-plugin-svgr";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), svgr()],
  build: {
        assetsDir: "packers",
    },
});
```

**Comment by dreygur** [comment]
> @dreygur
> 
> while creating a build you need to pass the base name
> 
> `vite build --base=/packers`

This does solve the issue. Thanks mate!

**Comment by Haschtl** [comment]
Isn't this the best/general solution for vite?

```
createBrowserRouter([ 
... 
  ], 
  { basename: import.meta.env.BASE_URL }
)
```
together with 
`vite build --base=BASE`

At least it works for me

**Comment by Gellipapa** [comment]
I experienced the same thing after the build, I got a 404 page error and the page didn't load. I used a custom path which was /main. 

I set up a 404 custom page component and my problem was solved. 

```
const router = createBrowserRouter(
  createRoutesFromElements(
    <Route path="/" element={<App />}>
      <Route path="*" element={<NotFound />} /> // Added this line 
      <Route index element={<Navigate replace to={ROUTES_PATH.MAIN} />} />
      {generateNestedRoutes(combinedRoutes)}
    </Route>
  )
)
```

Hope I was able to help someone.

**Comment by soft4pilot** [comment]
> > Could you provide a working reproduction of the issue? Vite + basename works fine for me in the `examples/basic` example in the repository
> @brophdawg11 you can check this one: https://github.com/andrekgb/field-logger/tree/main

You forget a slash (/) in your routes.tsx file.
