### ISSUE TITLE
[Bug]: Errors are being stripped of all props when serialized

### ISSUE THREAD

**Issue by piotrblasiak** [remix-run/react-router#11123]
### What version of React Router are you using?

6.21.0

### Steps to Reproduce

Throw any error with non-standard properties (in my case "userFriendlyMessage") using the data router & SSR.

### Expected Behavior

The client will get an object with the same properties as the original error - it's understandable if the stack trace is not there, or that it's not a real Error object - but it should contain all the same properties as they may influence rendering.

### Actual Behavior

Only the "message" property is kept.

**Comment by piotrblasiak** [comment]
https://github.com/remix-run/react-router/blob/cc4436c544300a09d9d95c5f733d3b00fd7d426f/packages/react-router-dom/server.tsx#L188

**Comment by piotrblasiak** [comment]
Nevermind, I just found that you can provide your own hydration methods.

**Comment by brophdawg11** [comment]
This goes beyond the scope of the built-in serialization logic which handles the most common use-cases of thrown `Response` and `Error` instances.  If you need to do more advanced serialization you can opt-out of automatic hydration and serialize manually: https://reactrouter.com/en/main/routers/static-router-provider#hydrate
