### ISSUE TITLE
[Bug]: NavLink isPending should not trigger for routes that specify end prop

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/react-router#11122]
### What version of React Router are you using?

2.4.0 of remix

### Steps to Reproduce

when I have two routes

```
/a
/a/b
```

even when I specify the end prop on a `NavLink` `isPending` from `children` is true when clicking on `/a/b` for `/a`

note:

this might also be a bug in the `Link` component also, but I didn't test

### Expected Behavior

`isPending` is only true for the active link being clicked

### Actual Behavior

`isPending` is true for both links in the example above

**Comment by brophdawg11** [comment]
Can you provide a reproduction?  I'm not seeing this behavior: https://stackblitz.com/edit/remix-run-remix-ke1u3a?file=app%2Froot.tsx
