### ISSUE TITLE
[Docs]: tutorial related issue

### ISSUE THREAD

**Issue by Mokshparashar** [remix-run/react-router#11130]
### Describe what's incorrect/missing in the documentation

while following the tutorial I encountered with an issue, while we are destructuring the the (contact) from useLoaderData() but we have already assigned a object data set with that name and this is throwing an error.

![Untitled](https://github.com/remix-run/react-router/assets/122145284/ba3ba0be-b924-4f90-9035-4fd67fbcc2a6)
In this image we have assigned an object naming contact.
![Untitled2](https://github.com/remix-run/react-router/assets/122145284/ed4f3292-b887-4203-8965-9304daa7ab0f)
and On the same page in this image we are destructuring the value of contact from useLoaderData().

**Comment by kiliman** [comment]
Ah. I think the docs show how, initially we have a static `contact` object that we are rendering in our route. We then update it to get the contact that is returned from the `loader` function via `useLoaderData`. So the documentation should probably say, replace the existing contact with the call to `useLoaderData`.

They could have added to the diff showing the contact initialization as _deleted_ code, but there are several lines there that would have probably cluttered up the diff.

**Comment by Mokshparashar** [comment]
yeah!! got it.
