### ISSUE TITLE
[Bug]: asterisk param is populated even if last route has none

### ISSUE THREAD

**Issue by alondon17** [remix-run/react-router#11141]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

put a route without an \* inside a route with an \*

### Expected Behavior

no * from useParams

### Actual Behavior

"\*" is equal to the outer routes's astrisk
if "one/\*" has "two" inside it, "\*" will be "two"

**Comment by timdorr** [comment]
This is expected behavior. We include all params in the useParams output, including ancestor routes and wildcards/splats: https://reactrouter.com/en/main/route/route#splats
