### ISSUE TITLE
[Bug]: Usage of Math.random()

### ISSUE THREAD

**Issue by swetha8612** [remix-run/react-router#11149]
### What version of React Router are you using?

5.3.4

### Steps to Reproduce

As part of our company's security policy, we run all our application through fortify scan. Fortify scan raised a flag where Math.random() has been used in this package. It is suggesting to replace with window.crypto.getRandomValues(new Uint32Array(10))[0]. We are using version 5.3.4. Could you please have a look. Thank you.

### Expected Behavior

Expecting to replace with window.crypto.getRandomValues(new Uint32Array(10))[0]

### Actual Behavior

Fortify scan is raising a flag for this Math.random() usage.

**Comment by timdorr** [comment]
Same basic idea as reduxjs/redux#4637

We use it to generate keys for history items. This is in no way a security issue and a false positive.

**Comment by swetha8612** [comment]
Thank you for confirming.
