### ISSUE TITLE
error when i use the Link component [Bug]: 

### ISSUE THREAD

**Issue by rayenhidri27** [remix-run/react-router#11142]
### What version of React Router are you using?

v6

### Steps to Reproduce

i have an error when i use the Link component from react-router-dom
i work on a new project on react 18 - router v6
this my test component 
```js
import { Link } from 'react-router-dom'

const Test = () => {
  return (
   <Link to="/">test</Link>
  );
}

export default Test
```

and this is my package.json

```js
{
  "name": "e-commerce-perso",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@popperjs/core": "^2.11.8",
    "@reduxjs/toolkit": "^2.0.1",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.6.2",
    "bootstrap": "^5.3.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.21.1",
    "react-scripts": "5.0.1",
    "react-toastify": "^9.1.3",
    "uuid": "^9.0.1",
    "web-vitals": "^2.1.4"
  },
  ```

![react-error](https://github.com/remix-run/react-router/assets/50717784/df66eb6d-cb0c-4a6a-80c8-95466f001084)

### Expected Behavior

it's expected to make a link to the home page

### Actual Behavior

error on compilation
![react-error](https://github.com/remix-run/react-router/assets/50717784/6e295d01-5444-459b-8171-5e6c5ae50834)

**Comment by rayenhidri27** [comment]
i'm using node 18.13.0
i tried an new installation of react to avoir and dependdecies conflict, but the error still the same

**Comment by timdorr** [comment]
This is some other error with webpack or another part of your build setup. This isn't a React Router bug.

**Comment by rayenhidri27** [comment]
i used the default configuration as create-react-app, i didn't change anything
i tried to use the test component in other components and it worked
i dont know why it doesn't in the app component where i put the router
