### ISSUE TITLE
TypeScript definition for `<Link>` component doesn't allow a number for `to` property

### ISSUE THREAD

**Issue by luukdv** [remix-run/react-router#11153]
### What version of React Router are you using?

6.21.1

### Steps to Reproduce

```tsx
<Link to={-1}>Back</Link>
```

### Expected Behavior

TypeScript doesn't throw an error, since a delta is allowed for `useNavigate`:

https://github.com/remix-run/react-router/blob/e4f663cec9f79150933127e53c7fdacf87eaab6e/packages/react-router/lib/hooks.tsx#L152-L155

https://github.com/remix-run/react-router/blob/e4f663cec9f79150933127e53c7fdacf87eaab6e/packages/react-router-dom/index.tsx#L1380

### Actual Behavior

TypeScript throws an error because of this type definition:

https://github.com/remix-run/react-router/blob/e4f663cec9f79150933127e53c7fdacf87eaab6e/packages/react-router-dom/index.tsx#L888

https://github.com/remix-run/react-router/blob/e4f663cec9f79150933127e53c7fdacf87eaab6e/packages/router/history.ts#L106

**Comment by brophdawg11** [comment]
This is correct, since `<Link>` renders an `<a href>` and it is impossible to determine the right `href` to render when navigating via a delta in the history stack.  If you need to navigate via a delta, you should use `<button onClick={() => navigate(delta)}>`

**Comment by luukdv** [comment]
@brophdawg11 Maybe I'm missing something, but adding an on `onClick` handler that calls `navigate(delta)` is exactly what happens internally when rendering `<Link to={-1}>`: https://github.com/remix-run/react-router/blob/ef0d0d70cea8f8979b42e1d7ef50fc39dd72d9cd/packages/react-router-dom/index.tsx#L970

What is the benefit of adding it yourself manually? Or is it purely because of the tag that is rendered (`a` vs `button`)?

Thanks.

**Comment by brophdawg11** [comment]
> purely because of the tag that is rendered

This - theres no way to render an `href` when using a number.
