### ISSUE TITLE
[Bug]: When using useBlocker, if page has a use of useNavigate the console logs "A router only supports one blocker at a time

### ISSUE THREAD

**Issue by e-senturk** [remix-run/react-router#11155]
### What version of React Router are you using?

6.21.1

### Steps to Reproduce

1-) Add a tab or button component that uses navigate method from useNavigate.
2-) Add a useBlocker method that also works on this component. (It doesn't need to be set as dirty to block page for trigger that bug)
3-) Click one of the buttons or tabs that activates navigate.
4-) Block and navigation works as intended but I see console.logs for (A router only supports one blocker at a time). Tracing the issue says it has some issue with navigate method.

### Expected Behavior

Not seeing console logs.

### Actual Behavior

Everytime I navigate with useNavigate I see console logs says (A router only supports one blocker at a time).

**Comment by brophdawg11** [comment]
Can you provide a reproduction?   I don't see this message following your steps above: https://codesandbox.io/p/sandbox/silly-hoover-2v4l7f?file=%2Fsrc%2Findex.js

Are you sure you don't have 2 `useBlocker` calls mounted at the same time?
