### ISSUE TITLE
[Bug]: Scroll position can't be restored correctly if the page has some async rendering.

### ISSUE THREAD

**Issue by LvChengbin** [remix-run/react-router#11158]
### What version of React Router are you using?

react-router-dom v6.21.1

### Steps to Reproduce

I think the question is not that complex so, I just give a simple sample code here.

```tsx
function Card( { id } ) {

    // the useData hook request data asynchronously, for example from a recoil/jotai atom.
    const data = useData( id );

    // the height of the card is dynamic and depends on the data.
    return (
        <div>
            {data.name}
        </div>
    );
}

function List() {
    return (
        <div>
            {list.map( id => <Card id={id} /> )}
        </div>
    );
}
```

### Expected Behavior

After going back to this page, the `useScrollRestoration` hook will restore the scrolling position with code:

```js
if (typeof restoreScrollPosition === "number") {
    window.scrollTo(0, restoreScrollPosition);
    return;
}
```

The `restoreScrollPosition` variable has a correct value of the previous scroll position, let's say for example 3000. But because not all `<Card />` finish their rendering, the whole page `body` doesn't have enough height for scrolling.

### Actual Behavior

I set a `minHeight` to `document.body` can resolve this issue:

```js
if (typeof restoreScrollPosition === "number") {
    document.body.style.minHeight = `calc( 100vh + ${restoreScrollPosition}px )`;
    window.scrollTo(0, restoreScrollPosition);
    return;
}
```

**Comment by brophdawg11** [comment]
This is expected behavior - browsers only restore scroll on initial render and React Router does as well.  It's generally a bad UX to render something, wait for async data to load, and then move the scroll position as the user could have started interacting with your UX and then you shift everything around without an user action.

I would recommend moving your async data fetching to a `loader` to avoid the issue - that way the data will be ready prior to rendering.

**Comment by LvChengbin** [comment]
1. Using async data doesn't mean user need to "wait for" it, it just means the data is loaded by an async function.
2. There are different data fetching strategy that more complex than request a list with a simple request, and for me, I split data into small items because I want each item can be cached by CDN and client separately and I need to reuse them everywhere not only in the list.
3. For me, I think a framework or a library should do more than browsers do, its the reason we use it, browsers don't support JSX, browsers don't tell us to use suspense elements. `react-router-dom` is a library for React users, it should try to resolve these problems. 

> I would recommend moving your async data fetching to a loader to avoid the issue

I would recommend you stop giving this type of recommendations, a library should not be a limitation of innovation, don't tell new learners that using a different data fetching strategy is incorrect.
