### ISSUE TITLE
[Docs]: Submitting Objects via useSubmit

### ISSUE THREAD

**Issue by aress31** [remix-run/react-router#11152]
### Describe what's incorrect/missing in the documentation

I am facing the following issue.

1. I have the following `values.rows[0]` getting submitted via `useSubmit`:

```js
onSubmit: async (values) => {
    await submit(values.rows[0], {
      method: "post",
      encType: "application/json",
    });
},
```

> Note: `values.rows[0]` contains `Blob`.

2. In my linked `action`, the `Blob` don't seem to be accessible.

```js
action: async ({ params, request }) => {
    const formData = await request.json();
    console.log("action -> entriesArray:", formData);
    console.log(
      "action -> formData.photoURL.name:",
      formData.photoURL.name
    );
    return null;
}
```

> See the output:

```
onSubmit -> formData.entries: (2) [Array(2), Array(2)]
SettingsView.js:50 onSubmit -> typeof photoURL: object
routerConfig.js:148 action -> entriesArray: {displayName: 'yo', photoURL: {…}}displayName: "yo"photoURL: [[Prototype]]: Object[[Prototype]]: Object
routerConfig.js:149 action -> formData.photoURL.name: undefined
```

If anyone could tell me how to work with `Blob` and update the doc to show working examples that would be super appreciated.

**Comment by timdorr** [comment]
This isn't one of the accepted types of inputs: https://reactrouter.com/en/main/hooks/use-submit#submit-target

You need to convert it to some sort of plain object that can be serialized.
