### ISSUE TITLE
[Bug]: useParams can only parse one path param correctly with wildcard in the path

### ISSUE THREAD

**Issue by sylhero** [remix-run/react-router#11161]
### What version of React Router are you using?

6.21.1

### Steps to Reproduce

```
<Routes>
     <Route path="/test/:id/:name/*" element={<TestRoutes />} />
</Routes>
```
```
const TestRoutes = () => {
const params = useParams();
console.log(params) // {id: 1, *: "testname"} "name" here is not defined
}
```

Go to http://localhost:3000/test/1/testname/anything

### Expected Behavior

{id: 1, name: "testName", *: "not sure what value it should be" }

### Actual Behavior

{id: 1, *: "testname"}

**Comment by brophdawg11** [comment]
Can you provide a reproduction?  This is working as expected for me in this simple code sandbox: https://codesandbox.io/p/sandbox/hopeful-hopper-ydrp3c?file=%2Fsrc%2Findex.js%3A9%2C1
