### ISSUE TITLE
[Bug]: `fetcher.data` returned from `useFetcher` is always undefined after running `fetcher.load(...)`

### ISSUE THREAD

**Issue by kgonyon** [remix-run/react-router#11184]
### What version of React Router are you using?

6.21.1

### Steps to Reproduce

I am using the following router.
```
const router = createBrowserRouter(
    createRoutesFromElements(
      <Route>
        <Route path="/incidents/all" loader={() => ({ data: 'test' })} />
        <Route element="/team/:teamId/incidents" element={<IncidentsRoute />} />
      </Route>,
    ),
);
```
Along with the following view
```
export function IncidentsRoute() {
  const [firstRender, setFirstRender] = useState(true);
  const fetcher = useFetcher({ key: 'incidents' });

  useEffect(() => {
    if (fetcher.state === 'idle' && fetcher.data == null && firstRender) {
      setFirstRender(false);
      fetcher.load('/incidents/all');
    }
  }, [fetcher, firstRender]);

  return <div>Hello</div>;
}
```

1. Navigate to /team/:teamId/incidents
2. Place a console log in the loader and notice that it is run, but no data is ever populated in `fetcher.data`

### Expected Behavior

After the loader returns the IncidentsRoute component should re-render with `fetcher.data` being populated with the data returned from the loader.

### Actual Behavior

`fetcher.data` is always undefined. I had to place the `firstRender` state in the component to keep the `useEffect` from looping infinitely.

**Comment by brophdawg11** [comment]
I tried recreating this setup but it doesn't reproduce the issue - `fetcher.data` is populated as expected: https://codesandbox.io/p/sandbox/stoic-wave-xw5w6d?file=%2Fsrc%2Findex.js%3A31%2C36

Could you fork that codesandbox and reproduce the issue you're seeing?

**Comment by kgonyon** [comment]
That example seems to work for me as well. I just remembered that a difference in my setup is we are running the app in an iFrame within a parent website (we have a micro frontend setup). That might have something to do with it not working fully. I'll experiment with that when I have a moment.
