### ISSUE TITLE
[Bug]: NavLink isPending state does not work when BrowserRouter option 'basename' is set

### ISSUE THREAD

**Issue by alexanderhorner** [remix-run/react-router#11194]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

[Reproduction on Stackblitz](https://stackblitz.com/edit/github-hiv5tg?file=src%2Fapp.tsx)

Using the Reproduction:

1. Click the Link "Link to slow Route"

Steps to reproduce from scratch:

1. Add a route with a slow loader.
3. Add `basename` option
4. Use NavLink to link to it, and use the isPending render prop somehow

### Expected Behavior

When clicking the NavLink, `isPending` should be `true` while the loader executes.

### Actual Behavior

When clicking the NavLink, `isPending` is `false` while the loader executes.

**Comment by brophdawg11** [comment]
Fixed by #11195 and will be available in the next release 👍

**Comment by alexanderhorner** [comment]
Thank you!
