### ISSUE TITLE
[Bug]: Parent Component with Outlet not trigger Navigate

### ISSUE THREAD

**Issue by lgl017** [remix-run/react-router#11197]
### What version of React Router are you using?

6.21.2

### Steps to Reproduce

[demo](https://stackblitz.com/edit/github-8walcs)

0. may need fork first(open in new tab without fork may connect fail), then refresh to load
1. open in new tab(default preview window con't change hash)
2. delete all hash and goto

visit / will navigate to /Index/Home, then refresh again will navigate to /login

### Expected Behavior

navigate to /login

### Actual Behavior

navigate to /Index/Home

**Comment by brophdawg11** [comment]
You need to short circuit on your navigation to login.  Since you are still rendering `<Outlet>` that is rendering the `IndexRoot` route which does a navigation to Home and cancels the prior navigation to login

```jsx
class Index extends React.Component {
  render() {
    return (
      <>
        {!loginUser.id && <Navigate to={'/Login'} />} // 👈 navigates  to /Login (cancelled)
        <div>index header</div>
        <Outlet />  // 👈 renders IndexRoot which navigates  to /Home
        <div>index footer</div>
      </>
    );
  }
}
```

Instead, if you need to redirecr you should notk be rendering the normal Index route body:
```jsx
class Index extends React.Component {
  render() {
    if (!loginUser.id) {
      return <Navigate to={'/Login'} />;
    }
    return (
      <>
        <div>index header</div>
        <Outlet />
        <div>index footer</div>
      </>
    );
  }
}
```

**Comment by brophdawg11** [comment]
That said, when using `RouterProvider` it's recommended to do your redirects via `loader` functions to decouple them from the render cycle.
