### ISSUE TITLE
[Docs]: Found error on react native router doc

### ISSUE THREAD

**Issue by nepalivai** [remix-run/react-router#11191]
### Describe what's incorrect/missing in the documentation

On official doc. [Basic](https://v5.reactrouter.com/native/example/Basic)
Error found after compiling. 
<img width="956" alt="image" src="https://github.com/remix-run/react-router/assets/108126089/2d808179-1ff3-4e22-b3db-59aa87e9ca3e">

**Comment by timdorr** [comment]
This is the legacy docs site. No further updates are planned.
