### ISSUE TITLE
[Bug]: The loader is triggered repeatedly until the page crashes

### ISSUE THREAD

**Issue by Orange-001** [remix-run/react-router#11205]
### What version of React Router are you using?

6.21.2

### Steps to Reproduce

```tsx
// src/router/index.tsx
/* eslint-disable react-refresh/only-export-components */
import { lazy } from 'react'
import type { RouteObject } from 'react-router-dom'
import { createBrowserRouter } from 'react-router-dom'

import Layout from '@/layout/Layout'
import ErrorPage from '@/views/ErrorPage'
import NotFound from '@/views/ErrorPage/404'

import rootLoader from './loader/rootLoader'

const NewChat = lazy(() => import('@/views/NewChat'))
const Chat = lazy(() => import('@/views/Chat'))

export const router: RouteObject[] = [
  {
    path: '/',
    element: <Layout />,
    errorElement: <ErrorPage />,
    loader: rootLoader, // rootLoader
    children: [
      {
        index: true,
        element: <NewChat />
      },
      {
        path: '/chat',
        element: <Chat />
      }
    ]
  },
  {
    path: '/*',
    element: <NotFound />
  }
]

const browserRouter = createBrowserRouter(router)

export default browserRouter

```

```tsx
// src/router/loader/rootLoader.tsx
import type { LoaderFunction } from 'react-router-dom'
import { redirect } from 'react-router-dom'

const rootLoader: LoaderFunction = () => {
  // When the route is at /chat, I refresh the page,
  // and then the loader is triggered repeatedly until the page crashes.
  console.log('invoke loader')
  const isAuth = true
  if (isAuth && location.pathname === '/chat') {
    return redirect('/')
  }
  return null
}

export default rootLoader
```

### Expected Behavior

- `Loader` should not be triggered infinite times
- `redirect` should trigger normally

### Actual Behavior

-  When the route is at `/chat`, I refresh the page, and then the loader is triggered repeatedly until the page crashes.
- When I enter the `/chat` route twice in a row, only one redirect is triggered.

**Comment by brophdawg11** [comment]
Loaders run _before_ the next route is rendered and `history` is updated, so checking `window.location` won;'t be accurate.  You want to check the location the `loader` is executing for via the `request`.

The loop you're hitting is:

* Load `window.location = "/chat"`
* Root loader runs and redirects to `/`
* `/` _also_ matches the root route so while we run the loaders for the _next_ location (`/`) - `window.location` is still `/chat` so you hit your redirect again
* loop!

Instead:

```js
const rootLoader: LoaderFunction = ({ request }) => {
  const isAuth = true
  if (isAuth && new URL(request.url).pathname === '/chat') {
    return redirect('/')
  }
  return null
}
```

**Comment by Orange-001** [comment]
> Loaders run _before_ the next route is rendered and `history` is updated, so checking `window.location` won;'t be accurate. You want to check the location the `loader` is executing for via the `request`.加载器在渲染下一个路由并更新 `history` 之前运行，因此检查 `window.location` 并不准确。您想通过 `request` 检查 `loader` 正在执行的位置。
> 
> The loop you're hitting is:您遇到的循环是：
> 
> * Load `window.location = "/chat"` 加载 `window.location = "/chat"`
> * Root loader runs and redirects to `/`根加载程序运行并重定向到 `/`
> * `/` _also_ matches the root route so while we run the loaders for the _next_ location (`/`) - `window.location` is still `/chat` so you hit your redirect again `/` 也匹配根路由，因此当我们为下一个位置（ `/` ）运行加载程序时 - `window.location` 仍然是 `/chat` 所以你再次点击您的重定向
> * loop! 环形！
> 
> Instead: 反而：
> 
> ```js
> const rootLoader: LoaderFunction = ({ request }) => {
>   const isAuth = true
>   if (isAuth && new URL(request.url).pathname === '/chat') {
>     return redirect('/')
>   }
>   return null
> }
> ```

Thank you!
