### ISSUE TITLE
[Docs]: Include renderToPipeableStream into the Server-Side Rendering guide

### ISSUE THREAD

**Issue by silvenon** [remix-run/react-router#11210]
### Describe what's incorrect/missing in the documentation

Hello, Remix team ❤️ 

I tried implementing SSR by following React Router's [server-side rendering guide](https://reactrouter.com/en/main/guides/ssr), but I'm using deferred data, so it looks like React is telling me that I need to be using `renderToPipeableStream` instead of `renderToString`.

I'm using Vite with Express. I'll probably be able to pull it off eventually, using Remix's `entry.server.tsx` as a reference is helpful as well, but I'm not able to follow clearly how it connects to the server, and what is Remix-specific code that is safe to delete.

I think that barebones instructions just for React Router would be a really handy addition to the guide, because in its current state it won't work for all usages of data routing.

**Comment by brophdawg11** [comment]
We can add a note or small code example of `renderToPipeableStream` - but just beware that won't make deferred data work.  At the moment we document `renderToString` _because_ it's the simplest way to demonstrate SSR working and the guide is more of a basic how-to and less of a guide for advanced use cases like deferred data.

Wiring up deferred data in a manual SSR setup is quite tricky - and we would strongly suggest using Remix for that.  The tricky part is that you need to take the `Promise`'s from the server load - serialize them over the network in the HTTP response and reconstruct them as `Promise` instances on the client.  Tjhat's ewhat the Remix codebase does with `<Scripts>` and goes beyond the scope of what we'd want to document in this type of a simple "here's how to SSR a React Router app" document.

**Comment by silvenon** [comment]
I see… yeah, I just stumbled upon https://github.com/remix-run/react-router/discussions/10602#discussioncomment-8148512and learned about this context, I thought it would be as simple as switching to `renderToPipeableStream`.

In that case I think the docs should mention pretty much what you said, that the implementation is hard, and that for streaming data from the server it's better to use Remix instead of implementing a solution. And give some hint of what the solution would include, so that people get discouraged 😄

**Comment by brophdawg11** [comment]
👍 Thanks for the callout!  Added some notes in 462bb712156a3f739d6139a0f14810b76b002df6
