### ISSUE TITLE
[Bug]: A question about navigate (-1)

### ISSUE THREAD

**Issue by 3420580499** [remix-run/react-router#11211]
### What version of React Router are you using?

6.21.0

### Steps to Reproduce

I use navigate (-1) in react router and click back, but when I click in my mobile browser, the browser path does change, but the page remains the same. Even if I keep clicking, I can only jump to the correct page after actively refreshing the page. However, strangely enough, when I use navigate (URL), this problem does not occur. I use BrowserRouter

### Expected Behavior

as above

### Actual Behavior

as above

**Comment by brophdawg11** [comment]
Can you provide a reproduction?
