### ISSUE TITLE
[Bug]: Hydration issues with a barebones Express example (link to repo included)

### ISSUE THREAD

**Issue by silvenon** [remix-run/react-router#11212]
### What version of React Router are you using?

6.21.3

### Steps to Reproduce

1. create an Express server for development and production by using Vite as middleware
2. create client and server entries based on the official [SSR data router example](https://github.com/remix-run/react-router/tree/fb0f1f94778f4762989930db209e6a111504aa63/examples/ssr-data-router)
3. create a simple home route, no loaders or actions
4. run the server
5. take a look at the console

I carefully studied the official example and made my own minimal example based on it, so you can use that to see the error. https://github.com/silvenon/repro/tree/9b079d9ff307ff77003821edb95c91278a741e3b

Run `npm run dev`, open http://localhost:3000, and take a look at the browser console.

So in my case routes are simply:

```tsx
import { Outlet, type RouteObject } from "react-router-dom";

export const routes: RouteObject[] = [
  {
    path: "/",
    element: <Outlet />,
    children: [
      {
        index: true,
        element: <h1>Hello!</h1>,
      },
    ],
  },
];
```

### Expected Behavior

No hydration errors, just like in the official example. Even in the official example I expect no hydration errors if I don't `sleep` in the loader, or if I don't have the loader at all.

### Actual Behavior

For the life of me I was unable to get the simplest route content to render without hydration errors. The official example succeeds in this, but **only** if its loader waits! Otherwise the hydration error surfaces there as well.

<details>
<summary>Hydration error</summary>

```
[Error] Warning: Expected server HTML to contain a matching <h1> in <div>.
h1
RenderedRoute@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:3548:11
Outlet@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:3916:25
RenderedRoute@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:3548:11
RenderErrorBoundary@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:3505:10
DataRoutes@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:4653:12
Router@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:3930:12
RouterProvider@http://localhost:3000/node_modules/.vite/deps/react-router-dom.js:4470:11
	printWarning (chunk-MCEUSTYS.js:519)
	error (chunk-MCEUSTYS.js:503)
	warnForInsertedHydratedElement (chunk-MCEUSTYS.js:8009)
	didNotFindHydratableInstanceWithinContainer (chunk-MCEUSTYS.js:8729)
	warnNonhydratedInstance (chunk-MCEUSTYS.js:9367)
	tryToClaimNextHydratableInstance (chunk-MCEUSTYS.js:9509)
	updateHostComponent (chunk-MCEUSTYS.js:14787)
	beginWork$1 (chunk-MCEUSTYS.js:19747)
	performUnitOfWork (chunk-MCEUSTYS.js:19192)
	workLoopSync (chunk-MCEUSTYS.js:19131)
	renderRootSync (chunk-MCEUSTYS.js:19110)
	performConcurrentWorkOnRoot (chunk-MCEUSTYS.js:18672:98)
	workLoop (chunk-MCEUSTYS.js:195)
	flushWork (chunk-MCEUSTYS.js:174)
	performWorkUntilDeadline (chunk-MCEUSTYS.js:382)
```

</details>

What am I missing?

**Comment by silvenon** [comment]
Whitespace. There shouldn't be any whitespace around the comment where I'm inserting my server-side rendered content. 🤦‍♂️

**Comment by depoulo** [comment]
I had a similar error, making me pull my hair out. The issue would only occur in the happy path, but not in case the ErrorBoundary was rendered (e.g. 404 page). I upgraded to React 18 to get better debugging warnings, and made the error go away. I then downgraded to React 17 out of curiosity, and the error was back!
