### ISSUE TITLE
[Bug]: matchPath not matching if path pattern ends in optional segment

### ISSUE THREAD

**Issue by sahishnu** [remix-run/react-router#11226]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

```
import { matchPath } from 'react-router-dom';

const test1 = matchPath('/profile/:id?', '/profile/ABC-123');
const test2 = matchPath('/profile/:id', '/profile/ABC-123')

console.log(test1) // null
console.log(test2) // PathMatch object
```

Call `matchPath` using a path pattern that ends in an optional segment, and a location pathname that includes the optional segment.

### Expected Behavior

I would expect `matchPath` to return a match object for both scenarios.

1. `/profile/:id?` should return a match object for path `/profile/ABC-123`
2. `/profile/id` should return a match object for path`/profile/ABC-123`

### Actual Behavior

`matchPath` returns `null` for scenario `test1`.

```
const test1 = matchPath('/profile/:id?', '/profile/ABC-123')
console.log(test1) // null
```

**Comment by brophdawg11** [comment]
This was resolved in [6.18.0](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6180) via https://github.com/remix-run/react-router/pull/10768
