### ISSUE TITLE
[Bug]: window hashchange event is not triggered on navigate() with createHashRouter

### ISSUE THREAD

**Issue by RakeshPawar** [remix-run/react-router#11220]
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

I am new to react router , would appreciate some help here.

- use createHashRouter to setup router and couple of child routes
- add window event listener to check 'hashchange' event.
- Routing works as expected but event does not trigger.

[sandbox link
](https://codesandbox.io/p/sandbox/react-router-6-7-0-hash-router-back-forked-8lfrmx?file=%2Fsrc%2FApp.tsx%3A23%2C57&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrrg5s4u00063b6io9dw21bc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrrg5s4u00023b6iqoxh08kv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrrg5s4u00033b6iwmmsg9xh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrrg5s4u00053b6ija81x405%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrrg5s4u00023b6iqoxh08kv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrrg5s4u00013b6inl8zzc4x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrrg7rdv007n3b6icu5fvylv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A57%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A57%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrrg5s4u00023b6iqoxh08kv%2522%252C%2522activeTabId%2522%253A%2522clrrg7rdv007n3b6icu5fvylv%2522%257D%252C%2522clrrg5s4u00053b6ija81x405%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrrg5s4u00043b6isth8a3hr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2523%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrrg5s4u00053b6ija81x405%2522%252C%2522activeTabId%2522%253A%2522clrrg5s4u00043b6isth8a3hr%2522%257D%252C%2522clrrg5s4u00033b6iwmmsg9xh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrrg5s4u00033b6iwmmsg9xh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
Background-

I am working on vite+ react app as shell in micro-frontend , child micro-frontends also has its own routing and I am using 'hashchange' event to sync them together.

### Expected Behavior

Should raise 'hashchange' event?

### Actual Behavior

no event is raised.
Event is raised if I use back or navigate(-1)

**Comment by brophdawg11** [comment]
React Router uses `history.pushState`/`history.replaceState` under the hood for push/replace navigations which don't trigger `hashchange` events.  Your best best to synchronize across these sub-apps is probably to use an effect to fire a custom event on `useLocation` changes
