### ISSUE TITLE
[Docs]: Incomplete upgrade documentation

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [remix-run/react-router#11236]
### Describe what's incorrect/missing in the documentation

Our project is using react router v5, I'm thinking about upgrading to V6.
And I have two questions:
1. We are currently using HashRouter. Is BrowserRouter more recommended? If we want to replace it, will the changes be major?
2. I read the upgrade documentation, but some documents are missing. [upgrading from V5](https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md) eg: There is no replacement for Prompt, but we really need it.

**Comment by timdorr** [comment]
The upgrade guide isn't meant to be exhaustive in covering all the APIs of v5. As such, we're not going to cover every nook and cranny of the API surface in that doc, just the major and most commonly-used parts.

As for the switch between BrowserRouter and HashRouter, that's really outside of the scope of the migration doc. You can do that before migrating.

Specifically for Prompt, you have a new hook API: https://reactrouter.com/en/main/hooks/use-prompt

**Comment by JinHe-PerkinElmer** [comment]
> The upgrade guide isn't meant to be exhaustive in covering all the APIs of v5. As such, we're not going to cover every nook and cranny of the API surface in that doc, just the major and most commonly-used parts.
> 
> As for the switch between BrowserRouter and HashRouter, that's really outside of the scope of the migration doc. You can do that before migrating.
> 
> Specifically for Prompt, you have a new hook API: https://reactrouter.com/en/main/hooks/use-prompt

Thank you for your reply, I will check it out later
