### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot destructure property 'basename' of 'React.useContext(...)' as it is null.

### ISSUE THREAD

**Issue by kadiyamsuresh** [remix-run/react-router#11237]
### What version of React Router are you using?

6

### Steps to Reproduce

Hi Team,
 
This issue is in continuation to https://github.com/remix-run/react-router/issues/11162
 
I have created an application in codesandbox with our components library which contains wrapper of all the standard components like Link. Link component of react-router-dom v6 is breaking the application, getting the below error in console.
 
To reproduce issue, see below URL.
codesandbox URL: https://codesandbox.io/p/devbox/tsc8ph?file=%2Fpackage.json%3A26%2C27

![image](https://github.com/remix-run/react-router/assets/155627606/e6959e20-d16a-4736-9835-fd5464d6881d)

### Expected Behavior

Link component from React-router-dom v6 should work.

### Actual Behavior

Link component from React-router-dom v6 is breaking application

**Comment by khaledtag98** [comment]
Any workaround available to share the same Router instance between application and library?

**Comment by sureshsumtotal** [comment]
To maintain same instance for both places we need to update package.json file in library repository.

We should add “react-router-dom” library under “peerDependencies” section.

We should not add “react-router-dom” library under “dependencies” section.

We should add “react-router-dom” library under “resolutions” section to maintain same version in both repositories. 

“react-router-dom” should not be part of library bundles.
