### ISSUE TITLE
[Bug]: Images are not loading in the Hash Router

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [remix-run/react-router#11230]
### What version of React Router are you using?

^6.21.3

### Steps to Reproduce

Clone this repo: https://github.com/FleetAdmiralJakob/Portfolio
Install all dependencies
start with `pnpm start`
go to /#/about or any other hash subpath

### Expected Behavior

![image](https://github.com/remix-run/react-router/assets/77451351/8b6624cd-533f-430d-8922-5c612de2153b)

### Actual Behavior

![image](https://github.com/remix-run/react-router/assets/77451351/8851caf3-cf6e-4d4a-adb5-3630c9e9815c)

**Comment by FleetAdmiralJakob** [comment]
You can also use the live demo: https://www.roessner.tech

**Comment by brophdawg11** [comment]
This isn't related to React Router but something about how your `Picture` component is rendering responsive images via `<picture>` . You can see this by rendering the logo as `<img src={logo} className="logo" alt="brand" />`, which works without issue.

It looks like your `Picture` component creates two very different elements based on whether you load the site at the root or at a sub-route with a hash value.

When loaded at the root (working):

![Screenshot 2024-01-29 at 1 51 21 PM](https://github.com/remix-run/react-router/assets/1609022/c3d7a548-d550-403e-ba16-375025250a63)


But when you reload for a sub-route, like `/#/about`, you get a bunch of webp stuff in there which is breaking it:

![Screenshot 2024-01-29 at 1 51 06 PM](https://github.com/remix-run/react-router/assets/1609022/c40cb030-9488-482a-8367-dc260b16e7e2)

I would dig into why the `Picture` component is rendering different values based on the route path 👍
