### ISSUE TITLE
[Docs]: useOutletContext in React.Component class missing example usage

### ISSUE THREAD

**Issue by dimaslanjaka** [remix-run/react-router#11246]
### Describe what's incorrect/missing in the documentation

missing how to use outlet context inside `React.Component` class in https://reactrouter.com/en/main/hooks/use-outlet-context.
I dont know how to implement `useOutletContext` inside React.Component class.

![image](https://github.com/remix-run/react-router/assets/12471057/73ad2d7f-d025-4fc6-92b8-6120ea5af9d1)

**Comment by timdorr** [comment]
This is a React Hook, as indicated by being under the hooks section of the docs. You cannot use them in class components.
