### ISSUE TITLE
[Bug]: TS6133: declared but its value is never read. when importing type from @remix-run/router

### ISSUE THREAD

**Issue by SainteCroquette** [remix-run/react-router#11251]
### What version of React Router are you using?

6.22.0

### Steps to Reproduce

I am using latest version of react-router-dom

Importing a type from @remix-run/router/utils.ts will generate linter error for some methods :
```typescript
import type { LoaderFunction } from '@remix-run/router/utils.ts';
```

while using unused parameter linting rules in tsconfig.json from your main project
```json
{
    "compilerOptions": {
        "noUnusedLocals": true,
        "noUnusedParameters": true,
    }
}
```

Then use vite to build your app (fails at tsc)
```
tsc && vite build
```

    "typescript": "^5.3.3",
    "react-router-dom": "^6.22.0",

### Expected Behavior

No typescript error when using types from @remix-run/router on production build

### Actual Behavior

Production build fails because of linting rules :

```
tsc && vite build

node_modules/@remix-run/router/history.ts:377:30 - error TS6133: 'window' is declared but its value is never read.

377   function createBrowserHref(window: Window, to: To) {
                                 ~~~~~~

node_modules/@remix-run/router/utils.ts:1451:34 - error TS6133: 'v' is declared but its value is never read.

1451     this.pendingKeysSet.forEach((v, k) => this.pendingKeysSet.delete(k));
                                      ~

node_modules/@remix-run/router/utils.ts:1579:11 - error TS6133: 'error' is declared but its value is never read.

1579   private error?: Error;
               ~~~~~

node_modules/@remix-run/router/utils.ts:1580:11 - error TS6133: 'internal' is declared but its value is never read.

1580   private internal: boolean;
               ~~~~~~~~


Found 4 errors in 2 files.

Errors  Files
     1  node_modules/@remix-run/router/history.ts:377
     3  node_modules/@remix-run/router/utils.ts:1451

```

It is not a big issue but it'll probably make me use `unknown` instead of `LoaderFunction` because I'd prefer to enforce strict linting rules rather than types from an external dependency even if some type inference capabilities are losts.

**Comment by SainteCroquette** [comment]
Quick fixes:
1. rename `window` in `_window`
2. rename `v` in `_v`
3. add //@ts-expect-error to `error` definition to ignore unused parameter error
4. add //@ts-expect-error to `internal` definition to ignore unused parameter error

1 & 2 should be okay but 3 & 4 are obviously really bad
I'll make a pull request if I find a clean way to do this

**Comment by layerok** [comment]
@timdorr unfortunatelly I can not find all imports that I need in react-router-dom. 
for example, I import `Router` type from `@remix-run/router`. I couldn't find this import in react-router-dom.
```tsx
import { type Router } from `@remix-run/router`;
function useRouterTabs({ router }: { router: Router}) {}
```
So my solution was to disable `noUnusedParameters` setting
