### ISSUE TITLE
[Bug]: URL Scroll-To-Text Fragment feature not working

### ISSUE THREAD

**Issue by roydigerhund** [remix-run/react-router#11258]
### What version of React Router are you using?

6.22.0

### Steps to Reproduce

1. Create a Link containing the markup for the Scroll-To-Text-Fragment browser feature, like this:  
`<Link to="/test#:~:text=Highlight">Go to test route</Link>`
2. Place the text which should be highlighted on the target page, in this case the word "Highlight".
3. Click the link 

### Expected Behavior

After the target page is loaded, the to-be-highlighted text snippet should be highlighted and scrolled into view. The URL should still contain `#:~:text=Highlight`.

### Actual Behavior

1. In Safari everything after the `#` will be removed in the URL, on reload it appears again, the word is highlighted but not scrolled into view.
2. In Chrome, the URL stays intact but the word is not highlighted and not scrolled into view.
3. Opening the URL https://scroll-to-text-fragment.vercel.app/test#:~:text=Highlight directly in a fresh tab works in Chrome and Safari, but in Chrome `#:~:text=Highlight` will be stripped from the URL.

I've created a live demo and a repository containing a fresh remix installation with just the changes to show this behavior.  
Repository: https://github.com/roydigerhund/scroll-to-text-fragment  
Live Demo: https://scroll-to-text-fragment.vercel.app

The feature is support in Chrome, Edge, Safari and Opera: https://caniuse.com/url-scroll-to-text-fragment

More info about the feature is available here:  
https://chromestatus.com/feature/4733392803332096  
https://web.dev/articles/text-fragments?hl=en

**Comment by roydigerhund** [comment]
I just found this paragraph on the last link (web.dev) and this behavior might be intended by the browser.

> **Security**
Text fragment directives are invoked only on full (non-same-page) navigations that are the result of a [user activation](https://html.spec.whatwg.org/multipage/interaction.html#tracking-user-activation). Additionally, navigations originating from a different origin than the destination will require the navigation to take place in a [noopener](https://html.spec.whatwg.org/multipage/links.html#link-type-noopener) context, such that the destination page is known to be sufficiently isolated. Text fragment directives are only applied to the main frame. This means that text will not be searched inside iframes, and iframe navigation will not invoke a text fragment.

**Comment by timdorr** [comment]
Since you're not actually using the router here, it's probably best to make this a plain `<a>` link. However, adding `rel="noopener"` will likely fix it for you.
