### ISSUE TITLE
[Bug]: Routing from a location to a location/hash

### ISSUE THREAD

**Issue by rebeccapeltz** [remix-run/react-router#11264]
### What version of React Router are you using?

18.2.17

### Steps to Reproduce

Here's a sandbox showing what I see as the problem.
https://codesandbox.io/p/sandbox/react-router-dom-example-forked-h2p5xq

There is a hash link in the Midpoint link in the navbar.   If you click on it it doesn't navigate you to the hash, just to the location.

 The router always looks at just the location and not the hash.  
I'm handling it by using scrolTo in the page. but I have to check location and hash on every page load.  
Is there a better way?

### Expected Behavior

click on link with a hash does the scrollTo for you

### Actual Behavior

click on link with hash takes you to location only and ignores hash

**Comment by timdorr** [comment]
`Link` uses a click handler that intercepts this scroll event. As a simple workaround, you can add `reloadDocument` as a prop to the `Link` and it will function as a normal `<a>` and will handle the hash link as expected.

**Comment by rebeccapeltz** [comment]
I modified the sandbox to use reloadDocument in the link in Navbar.  I still don't take the user to the Midpoint when they click on the Midpoint item.
```
 <Link to="/#midpoint" reloadDocument={true}>
            Midpoint
 </Link>
```

**Comment by rebeccapeltz** [comment]
Here's a sandbox with updated packages.  The reloadDocument is working if you're on the same page as the hash, but if you try to navigate from About to /#midpoint, it doesn't take you there.  It takes you to the top of Home.  Is there something missing.  New sandbox: https://stackblitz.com/edit/react-ts-9kwbcp

**Comment by rebeccapeltz** [comment]
I don't see why this is closed.  You cannot open a link to a page's hash from another page.  
Click on About and then Click on Midpoint from the About page.  You will be taken to the top of the Home Page instead of the midpoint.  This leaves it to the developer to write custom code on the home page to check for a hash and then scroll to it.   Try it out here: https://stackblitz.com/edit/react-ts-9kwbcp

**Comment by rebeccapeltz** [comment]
try this HTML to see how you would expect navigating to a hash on a page would work:  https://replit.com/@RebeccaPeltz/Opentohash
shouldn't require JavaScript to navigate to a hash on a page
