### ISSUE TITLE
[Docs]: index.js

### ISSUE THREAD

**Issue by kingram6865** [remix-run/react-router#11269]
### Describe what's incorrect/missing in the documentation

The way I learned react router was this:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom'
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <Router>
      <App />
    </Router>
  </React.StrictMode>,
  document.getElementById('root')
);
```

Your tutorial for React Router v6 does not properly demonstrate how to transition from this to
the new React Router method.

I don't feel like doing trial and error to figure out how this needs to translate.

Please provide some guidance.

**Comment by timdorr** [comment]
We have several migration guides. The one you're looking for is here: https://reactrouter.com/en/main/upgrading/v6-data

**Comment by kingram6865** [comment]
> We have several migration guides. The one you're looking for is here: https://reactrouter.com/en/main/upgrading/v6-data

It doesn't address the specific question I had. Which of your docs addresses my specific question about `index.js`?

**Comment by kingram6865** [comment]
Thank you for providing those extra details.
