### ISSUE TITLE
[Bug]: Encoded hash breaks route matching

### ISSUE THREAD

**Issue by Sodik** [remix-run/react-router#11276]
### What version of React Router are you using?

6.15.0 and 6.22.0

### Steps to Reproduce

Use `%23` instead of `#` in  `NavLink` href.
https://stackblitz.com/edit/github-uofrqk?file=README.md

### Expected Behavior

Both URLs lead to the same route.
`/about#id=23`
`/about%23id%3D23`

### Actual Behavior

The route `/about%23id%3D23` was not found

**Comment by brophdawg11** [comment]
This is expected behavior because you are encoding the `#` character which makes it no longer behave as a normal hash (and thus ending the `pathname` as `/about`) and instead it becomes part of the pathname and `/about%23id%3D23` does not match `/about`.  It would match a route defined as:

```jsx
<Route path="about#id=23" element={<h3>Works</h3>} />
```
