### ISSUE TITLE
[Bug]: Multiple memory routers cannot be used independently at the same time

### ISSUE THREAD

**Issue by hungtcs** [remix-run/react-router#11292]
### What version of React Router are you using?

v6.22.1

### Steps to Reproduce

> I am using in-memory routing to manage view state in a web component,
> and when I create multiple instances of the same web component, 
> I realize that the in-memory routing cannot be used independently.

1. Open the test project at https://stackblitz.com/edit/github-ny2pod?file=src%2Fmain.tsx
2. I used RouterProvider in App and created two App components in main.ts.
3. When switch the route of the first app, the route of the second app switches as well, but they are different Memory Router instances.

### Expected Behavior

1. Each memory route created through `RouterProvider` and `createMemoryRouter` should be able to be used independently of each other.

### Actual Behavior

1. When one of the routes is switched, the other one is switched with it and cannot be used independently

**Comment by brophdawg11** [comment]
You're using the same router instance in both apps - you should instead create a _different_ router instance for each app: <https://stackblitz.com/edit/github-ny2pod-82jayz>

**Comment by hungtcs** [comment]
Sorry for the stupid question, I made a basic mistake.

**Comment by brophdawg11** [comment]
Don't be sorry!  We all make mistakes!
