### ISSUE TITLE
useNavigate can only be called inside a Router 

### ISSUE THREAD

**Issue by AsuraKev** [remix-run/react-router#11307]
### What version of React Router are you using?

6.22.1

### Steps to Reproduce

Hi there,

I am getting an error complaining about useNavigate can only be used inside a router after upgrading react router to the latest.

I have the following route config and calling useNavigate on my AuthProvider which is wrapped in a route. 

![image](https://github.com/remix-run/react-router/assets/52765572/0e4e606d-4a30-4f79-a195-12abd554e7b0)

![image](https://github.com/remix-run/react-router/assets/52765572/931e7110-1d46-4a7a-a5ad-c30b3cb777e5)

### Expected Behavior

we should be able to call useNavigate when a component is part of the route tree

### Actual Behavior

useNavigate doesnt work

**Comment by AsuraKev** [comment]
Downgraded to v6.22.0 and issue is gone. Looks like v6.22.1 might have affected it

**Comment by timdorr** [comment]
This is most likely an issue with mismatched versions of React Router installed. Check with `npm ls react-router-dom` (or whichever package you have installed) to see if you have multiple versions.

**Comment by dsuchan** [comment]
I have the same problem. I have problem with calling `useNavigate` inside dialog. The same message as you. I tried to downgrade to 6.22.0 but that didn't help me. I checked the installed versions and i currently have only the 6.22.0.

**Comment by AsuraKev** [comment]
Tried again today, remove node module and delete package.lock.json and reinstall. Looks like its working :D. Happy to close if anyone is able to resolve. thanks!

**Comment by AsuraKev** [comment]
> I have the same problem. I have problem with calling `useNavigate` inside dialog. The same message as you. I tried to downgrade to 6.22.0 but that didn't help me. I checked the installed versions and i currently have only the 6.22.0.

try my last comment, feel free to raise it again if it didnt work for you
