### ISSUE TITLE
[Bug]: Error no route matches URL /  v6.22.1 with Create react app

### ISSUE THREAD

**Issue by AsuraKev** [remix-run/react-router#11311]
### What version of React Router are you using?

6.22.1

### Steps to Reproduce

A route config that looks like 
![image](https://github.com/remix-run/react-router/assets/52765572/931198b6-373b-4f53-888f-40df2ca248d6)

The default layout has no path as its a layout route. However this issue doesnt happen to my other project thats on Vite so I am wondering if React router v6.19 above doesnt work with Create react app?

![image](https://github.com/remix-run/react-router/assets/52765572/5b1213ac-eb55-4f29-9deb-df185d8b2511)

thanks!

### Expected Behavior

Based on the the screenshot, React router should find DefaultLayout and start rendering it

### Actual Behavior

No path matched / because no path were specified

**Comment by AsuraKev** [comment]
oh and actually navigation doesnt load the page accordingly either ..

**Comment by brophdawg11** [comment]
Pathless routes don't "match" as leaf routes.  If you want to match `/` you need to provide an `index` route for the pathless layout route, or add `path="/"` as you discovered.  Right now only the two path'd children would match - so `/litmos-group-signup` and `/education-group-signup`.

```jsx
const routes = [
  {
    element: <Layout />,
    children: [
      {
        index: true, // match at the path "/"
        element: <h2>Index</h2>,
      },
      {
        path: "temp",
        element: <h2>Temp</h2>,
      },
    ],
  },
];
```

**Comment by johnnyreilly** [comment]
If you've landed on this page, it might be because you're being bitten by this issue: https://github.com/remix-run/react-router/issues/11480

Putting a link here just to help connect folk
