### ISSUE TITLE
[Bug]: react-router-dom is showing a white page

### ISSUE THREAD

**Issue by SamTV12345** [remix-run/react-router#11340]
### What version of React Router are you using?

6.22.3

### Steps to Reproduce

```bash
git clone https://github.com/ether/ether.github.com.git
cd ether.github.com
pnpm i
pnpm run dev
```
To reproduce the step just update react-router and react-router-dom to 6.22.3 and you will see no content on this page. Only the header is shown and no routes are displayed

### Expected Behavior

The page should show without any issue

### Actual Behavior

The default route is blank and nothing is shown

**Comment by kiliman** [comment]
Did you check the browser DevTools console to see if there are any JavaScript errors?

**Comment by SamTV12345** [comment]
There weren't any. I opened the panel and nothing is showing. It was very strange to debug as I had to go through all the latest dependabot updates to find that.

**Comment by timdorr** [comment]
You have [both `react-router` and `react-router-dom` installed](https://github.com/ether/ether.github.com/blob/ee59532e4bd85c0a1948cdf2fc067e6745015edb/package.json#L25-L26), so they are probably using different versions. Uninstall the `react-router` as `react-router-dom` will already include it by proxy.
