### ISSUE TITLE
[Bug]: Loader runs twice on page refresh and without using <StrictMode>

### ISSUE THREAD

**Issue by AsuraKev** [remix-run/react-router#11341]
### What version of React Router are you using?

latest

### Steps to Reproduce

I have a loader exported from the page component like this. When I refresh the page, I expect the loader to only fire once but it actually trigger the alert twice

![image](https://github.com/remix-run/react-router/assets/52765572/10aa0257-fc27-4ca6-b804-5658c0db75b1)

### Expected Behavior

Expect the loader to only run once

### Actual Behavior

fires twice

**Comment by AsuraKev** [comment]
Actually, will loaders be triggered when <RouterProvider/> is rerendered?  e.g when App rerenders

![image](https://github.com/remix-run/react-router/assets/52765572/4136dec0-da4b-4e76-8597-89adccf39a3a)

**Comment by timdorr** [comment]
You shouldn't be calling `create*Router()` from within your React components. It may be re-rendered by a number of different sources and that will re-initialize the router instance and lose any stored state. Move this call outside of React to its own module.
