### ISSUE TITLE
[Bug]: createFileRoute beroferLoad return value is not typechecked by typescript is root was created with context

### ISSUE THREAD

**Issue by freddi301** [remix-run/react-router#11363]
### What version of React Router are you using?

1.22.0

### Steps to Reproduce

createFileRoute beroferLoad return value is not typechecked by typescript is root was created with context

### Expected Behavior

to be typechecked

### Actual Behavior

you can return anything in beforeLoad and you do not get intellisense

**Comment by timdorr** [comment]
You have the wrong project. This is about TanStack Router, but you're in the React Router repo.
