### ISSUE TITLE
[Bug]:  Can not navigate after signInWithRedirect  for Google from Firebase

### ISSUE THREAD

**Issue by KJ-GM** [remix-run/react-router#11367]
### What version of React Router are you using?

^6.22.3

### Steps to Reproduce

```js 
const handelMicrosoftSignIn = async () => {
     await signInWithRedirect(FIREBASE_AUTH, GOOGLE_PROVIDER).then(() => navigate("/student"));
  };
```

### Expected Behavior

The user signs in to google normally, when he gets redirected back to the page and try to navigate dose not work?

### Actual Behavior

I tried to debug, but no solution, and notice that if I use signInWithPopup, the app dose navigate and work.

**Comment by timdorr** [comment]
There isn't enough information to go on here, but I'm not seeing anything that points to a bug in the library. This is probably something wrong with your code or your handling of the redirect to/from Google.
