### ISSUE TITLE
[Bug]: `<Navigate to=...` breaks after `6.14.2`

### ISSUE THREAD

**Issue by lessp** [remix-run/react-router#11375]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

We have the following code (which itself may be incorrect), however, this throws `Uncaught (in promise) ReferenceError: AwaitRenderStatus is not defined` for versions post `6.14.2`.

```typescript
createBrowserRouter(
  createRoutesFromElements(
    <Route path="/" element={...}>
      <Route path="*" element={...} />
      <Route path="/foo" element={<Navigate to="/bar" />} />
    </Route>,
  ),
);
```

### Expected Behavior

Depending on if we're using this correctly, I'd expect it to navigate to `bar` without throwing.

### Actual Behavior

Throws `Uncaught (in promise) ReferenceError: AwaitRenderStatus is not defined`

**Comment by brophdawg11** [comment]
Could you provide a minimal reproduction of the bug?  

It sounds like you may have some mismatched versions - that private internal variable exists in 6.15.0 [here](https://github.com/remix-run/react-router/blob/react-router%406.15.0/packages/react-router/lib/components.tsx#L497).  Maybe try an `npm ls react-router-dom` and see if you need to dedupe?
