### ISSUE TITLE
[Bug]: Cannot navigate in windows production

### ISSUE THREAD

**Issue by ImJeremyHe** [remix-run/react-router#11390]
### What version of React Router are you using?

6.22.1

### Steps to Reproduce

Building an electron app with these related packages

```
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.22.1",
```
Code looks like this
```typescript
const navigate = useNavigate()
navigate(`myUrl`)
```

### Expected Behavior

Work in the windows production

### Actual Behavior

`navigate` can not render the page without any error in windows production.
Weird thing is that in windows development environment and macos, it works.

**Comment by timdorr** [comment]
The host operating system should have no effect on this library, as the browser abstracts that away from us. Without a reproducible test case, we can't assume this is a bug with the library anyways. It is very likely something with your local setup, such as a browser extension.

**Comment by ImJeremyHe** [comment]
@timdorr Thanks for your reply.
After debugging, I found that `navigate` actually works in windows production, just navigate to a wrong component(which is same as the current displayed one, so it looks like it doesn't work).
If I have time, I will make a minimum reproducible repo
