### ISSUE TITLE
[Bug]: <Outlet/> Component is not working in deployment

### ISSUE THREAD

**Issue by mahabubsaki** [remix-run/react-router#11485]
### What version of React Router are you using?

6.22.3

### Steps to Reproduce

If I use <Outlet/> component locally it works perfectly but <Outlet/> component is not rendered in production

### Expected Behavior

<Outlet/> component should be rendered in children routes

### Actual Behavior

<Outlet/> component not rendered in children routes

**Comment by brophdawg11** [comment]
Dup of https://github.com/remix-run/react-router/issues/11480

Please pin rollup to 4.15.0 or upgrade it to 4.16.4
