### ISSUE TITLE
[Bug]: Cloudflare Pages - Outlet not working.

### ISSUE THREAD

**Issue by NeikiDev** [remix-run/react-router#11480]
### What version of React Router are you using?

^6.22.3

### Steps to Reproduce

I am using an normal createReactRouter, and since today it just doesnt work after i run the build command.

### Expected Behavior

Using Routes, it just shows the 404 Error not found page, anything else is just a blank page,
I changed nothing on the Routing part or whatever, i just redeployed to cloudflare pages

### Actual Behavior

Just blank page.

Main.ts
```ts
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Routes />
  </React.StrictMode>,
)
```

Routes.tsx
```ts

export const ANDRoutes = [
    {
        path: '/',
        index: true,
        element: <Home />
    },
    {
        path: "/upload",
        element: <Home />
    },
    {
        path: '*',
        element: <NotFound />
    }
]

const router = createBrowserRouter([
    {
        path: '/',
        element: <App />,
        children: ANDRoutes,
        errorElement: <ErrorPage />
    }
])

export function Routes() {

    return (
        <>
            <RouterProvider router={router} />
        </>
    )
}
```

App.tsx
```ts
function App() {
  
  return (
    <Box>
      <Outlet/>
    </Box>
  )
}

export default App
```

And home.tsx and the others returns valid Elements,
If i remove the Outlet and just use static my <Home/> it displays that,
if i use use <Outlet/> nothing appears just a blank white page, no errors nothing

**Comment by NeikiDev** [comment]
When i just use npm run dev, so locally dev build it actually works, but when i run the build command to build the html, js etc it doesnt work anymore.

**Comment by NeikiDev** [comment]
First error i found
```
dh
data
: 
"Error: No route matches URL \"/reports/ds\""
error
: 
Error: No route matches URL "/reports/ds" at wr (https://e6dba700.analyzenetworkreact.pages.dev/assets/index-MoUOeJtY.js:50:8478) at yE (https://e6dba700.analyzenetworkreact.pages.dev/assets/index-MoUOeJtY.js:49:10799) at VE (https://e6dba700.analyzenetworkreact.pages.dev/assets/index-MoUOeJtY.js:68:314) at https://e6dba700.analyzenetworkreact.pages.dev/assets/index-MoUOeJtY.js:310:9659
internal
: 
true
status
: 
404
statusText
: 
"Not Found"
[[Prototype]]
: 
Object
```

**Comment by NeikiDev** [comment]
Changed it to 

```ts
return (
        <SnackbarProvider maxSnack={3} preventDuplicate>
            <BrowserRouter>
                <Routes>
                    {
                        ANDRoutes.map((route, index) => {
                            return <Route key={index} path={route.path} element={route.element} errorElement={<ErrorPage />} />
                        })
                    }
                </Routes>
            </BrowserRouter>
        </SnackbarProvider>
    )
    ```
    
    Now it works, but why not like before?

**Comment by NoorBayari** [comment]
+1

**Comment by AbdallahAbuKhurma** [comment]
+1

**Comment by yuan116** [comment]
+1

**Comment by DigitalNaut** [comment]
+1 

This was so frustrating to debug. There went my entire morning. 😥

**Comment by NeikiDev** [comment]
I want to add the actuall Error you get when using the built app on production.
Any page other than the actually "index" of the page shows the exact same with that error:

```json
"Error: No route matches URL \"/reports/ds\""
Error: No route matches URL "/reports/ds" at wr 
internal: true
status: 404
statusText: "Not Found"
```

**Comment by danilo-89** [comment]
Not sure if related, but Outlet component is not working when built and on Vercel too with newest Vite (everything works with when run with `vite dev`)

repo: https://github.com/danilo-89/react-error-boundary-research
```
import { Routes as ReactRoutes, Route } from 'react-router-dom';

// Layouts
import Layout from '../layouts/Layout';

// Components
import NoMatch from '../pages/NoMatch';
import Home from '../pages/Home';
import About from '../pages/About';
import RouteErrorBoundary from '../components/errorHandling/RouteErrorBoundary';

const Routes = () => {
	return (
		<>
			<ReactRoutes>
				<Route path='/' element={<Layout />}>
					{/* HOME */}
					<Route index element={<Home />} />

					{/* ABOUT */}
					{/* Route with Error Boundary */}
					<Route
						path='/about'
						element={
							<RouteErrorBoundary>
								<About />
							</RouteErrorBoundary>
						}
					/>

					{/* 404 */}
					<Route path='*' element={<NoMatch />} />
				</Route>
			</ReactRoutes>
		</>
	);
};

export default Routes;
```

```
import { Link, Outlet } from 'react-router-dom';

export default function Layout() {
	return (
		<>
			<nav className='absolute top-0 left-0 w-full p-5 bg-[#1a1a1a]'>
				<Link to='/'>Home</Link> | <Link to='/about'>About</Link>
			</nav>
			<div className='pt-10'>
				<Outlet />
			</div>
		</>
	);
}
```

**Comment by riccardotrinchieri** [comment]
+1

**Comment by gabfeudo** [comment]
+1 same problem. It stopped working randomly with `vite build`. Our production project was working fine until yesterday. `package.json` has fixed versions (without `ˆ`)

**Comment by mbelaidi** [comment]
+1 when using <Outlet /> for layout, i try remove it then build the routing logic work normaly without the layout

**Comment by ZGFuZHk100** [comment]
+1

**Comment by DigitalNaut** [comment]
> +1 same problem. It stopped working randomly with `vite build`. Our production project was working fine until yesterday. `package.json` has fixed versions (without `ˆ`)

Same here. I have a build on Netlify fully working from over a month ago. Now the same build with all the exact same dependency versions breaks. So odd.

**Comment by markgomez** [comment]
I think this might have something to do with a recent update to Vite (or one of its transitive dependencies somewhere)?

I created two projects — the only difference between them is one uses `vite@4`, the other `vite@5`.

`vite@4`:
https://stackblitz.com/edit/react-router-outlet-with-vite-4

`vite@5`:
https://stackblitz.com/edit/react-router-outlet-with-vite-5

Both will look fine at first because the `dev` servers are running. Stop the `dev` servers then build/preview them instead. You'll see that in the `vite@5` version the main content (`<Outlet />`) is missing and trying to navigate to the "About" page errors-out.

**Comment by ssadler** [comment]
+1. Actually nested didn't work for me at all after I built it, only in dev. The fix was un-nesting and passing {children}.

**Comment by mbelaidi** [comment]
> +1. Actually nested didn't work for me at all after I built it, only in dev. The fix was un-nesting and passing {children}.

i use the same fix (we broke the production without image backup) took us all day

**Comment by chrooti** [comment]
This might be due to rollup 4.16 transforming

```typescript
function flattenRoutes<
  RouteObjectType extends AgnosticRouteObject = AgnosticRouteObject
>(
  routes: RouteObjectType[],
  branches: RouteBranch<RouteObjectType>[] = [],
  parentsMeta: RouteMeta<RouteObjectType>[] = [],
  parentPath = ""
): RouteBranch<RouteObjectType>[] {
  ...
}
```

into

```javascript
function flattenRoutes(routes, branches, parentsMeta, parentPath) {
  {
    branches = [];
  }
  ...
  }
```
  
  
Maybe this is not even the same problem, but just in case, try reverting to older vite/rollup versions?

**Comment by felipehertzer** [comment]
I'm using Yarn, and a temp fix for that issue is:

package.json:
```json
"resolutions": {
    "rollup": "4.13.1"
}
```

**Comment by cpojer** [comment]
I'm convinced this PR is causing the issue we are running into: https://github.com/rollup/rollup/pull/5443#issuecomment-2068528821

Definitely a compiler bug, not a React Router bug.

**Comment by totoro0103** [comment]
> I'm using Yarn, and a temp fix for that issue is:
> 
> package.json:
> 
> ```json
> "resolutions": {
>     "rollup": "4.15.0"
> }
> ```
> 
> It seems to be this commit [rollup/rollup#5443](https://github.com/rollup/rollup/pull/5443)

you save my day

**Comment by mahmoud-bebars** [comment]
I have the same issue with the Outlet the Bug appears after updating the react-router package, it took me all day to figure it out but finally, I solved the issue in my Code.

the Code that isn't working for me :
```javascript
// ./src/App.jsx
return (
 <BrowserRouter>
            <Routes>
              <Route path="/" element={<Layout />}>
                <Route index element={<Home />} />
                {routes.map(({ element, path, id }) => (
                  <Route
                    key={id}
                    exact={true}
                    path={path}
                    element={createElement(element)}
                  />
                ))}
                <Route path="/*" element={<NotFound />} />
              </Route>
            </Routes>
          </BrowserRouter>
)
```

and i was using the `<Outlet />` in the  `<Layout />` so...

```javascript
// ./src/layout/index.jsx
         return (
                  <Navbar />
                       <Outlet />
                  <Footer />
        );
```

i passed the `<Routes>` for the  `<Layout/>` as a children props and removed the `<Outlet />` from it, chaging my code to

```javascript
// ./src/App.jsx
return (
  <BrowserRouter>
         <Layout>
            <Routes>
              <Route index element={<Home />} />
              {routes.map(({ element, path, id }) => (
                <Route
                  key={id}
                  exact={true}
                  path={path}
                  element={createElement(element)}
                />
              ))}
              <Route path="/*" element={<NotFound />} />
            </Routes>
          </Layout>
  </BrowserRouter>
)
```

```javascript
// ./src/layout/index.jsx
const Layout = ({children})=> {

         return (
                  <Navbar />
                       {children}
                  <Footer />
        );
}
```

I think this is the same method NextJS is using in Layout also

if there is another solution I would be happy to use it

**Comment by DevelopJKong** [comment]
same here

**Comment by amentotech026** [comment]
`  return (
        isAuthenticated && callBackType != "impersonation" ? <Navigate to={navigateTo} /> : <Outlet />
    )`

`  <Route element={<ProtectPublicRoute />}>

                    <Route path="/onboarding/*" element={
                        <Suspense fallback={<Spinner color='#007b5e' />}>
                            <Onboarding />
                        </Suspense>
                    } />
<Route/>
`
    
 This is my code for Outlet and its also stop working on build but its working fine on dev server. can anyone please suggest me the solution that i am doing wrong ? it happens suddenly i didn't even changed anything

**Comment by DigitalNaut** [comment]
> can anyone please suggest me the solution that i am doing wrong ? it happens suddenly i didn't even changed anything

It's not your code, it's a recent change to the Rollup 4.16.1 that breaks React Router on build. Just do what has been [suggested above](https://github.com/remix-run/react-router/issues/11480#issuecomment-2068981983) in your `package.json` file in the meantime while it gets sorted out.

**Comment by brophdawg11** [comment]
As noted above, this is a bug introduced in `rollup@4.16` which was released over the weekend, and `vite` uses a dependency of `rollup@^4.13.0` so it can pick it up on fresh installs.  It's being looked into by the rollup team (https://github.com/rollup/rollup/pull/5443) and a PR is open with a fix (https://github.com/rollup/rollup/pull/5482).

For now, you can install `rollup@4.15.0` into your app's `devDependencies` or use the `overrides` field in `package.json` to pin to `rollup@4.15.0` as a workaround.

**Comment by zhu-hong** [comment]
is a very serious problem🥲

**Comment by eityeily** [comment]
I had a same issue. it makes me to waste full day to fix. :( not good. 
thank you, @brophdawg11 and others.

**Comment by Shakeskeyboarde** [comment]
Rollup 4.16.2 is out with a fix that might address this. https://github.com/rollup/rollup/pull/5482#issuecomment-2069859661

**Comment by brophdawg11** [comment]
This should be resolved in rollup 4.16.2: https://github.com/rollup/rollup/releases/tag/v4.16.2

**Comment by danilo-timacum** [comment]
No more need for overrides for Vite projects, now that rollup is updated, this fixes it:

```
npm  upgrade rollup
// OR
pnpm upgrade rollup
// OR
yarn  upgrade rollup
```

**Comment by mahabubsaki** [comment]
Change the vite version to 4.4.1 build again and deploy. It should work

**Comment by Tuscan-blue** [comment]
npm install rollup -D solved my issue. Thanks a lot!!
