### ISSUE TITLE
[Docs]: When should I use `react-router` vs `react-router-dom`?

### ISSUE THREAD

**Issue by githorse** [remix-run/react-router#11536]
### Describe what's incorrect/missing in the documentation

This seems to be a popular question with a [less-than-clear StackOverflow answer](https://stackoverflow.com/questions/42684809/react-router-vs-react-router-dom-when-to-use-one-or-the-other). At any rate it seems like the `react-router` project should provide the canonical answer for this somewhere. Could we add it to the docs (perhaps in the FAQ)?

**Comment by timdorr** [comment]
This is changing in v7, so it will be answered when that releases.
