### ISSUE TITLE
[Bug]: Cannot read properties of null (reading b

### ISSUE THREAD

**Issue by algomage** [remix-run/react-router#11534]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

Install react-router-dom ^6.14.1 and react ^18.2.0 in an electron app. As it is an electron app instead of Browserrouter I am using hashRouter
It is running smoothly on all users machine except one windows machine where blank screen with the below error is coming

![WhatsApp Image 2024-05-06 at 4 36 27 PM](https://github.com/remix-run/react-router/assets/108169958/3fc6dd25-8358-4b2a-ab0c-c6d790f6d964)
![WhatsApp Image 2024-05-06 at 4 36 28 PM](https://github.com/remix-run/react-router/assets/108169958/20b73224-bf20-4d92-8898-5817470b4988)

### Expected Behavior

React router should work properly and it should navigate through different page

### Actual Behavior

Currently it's crashing just when routes are called.

**Comment by timdorr** [comment]
It appears you're using a `Link` outside of `BrowserRouter`/`RouterProvider`. This isn't a bug with the library.

**Comment by algomage** [comment]
Apologies for raising it as a bug. Thanks a lot for your reply. It solved our issue. Just out of curiosity why this issue popped up in 2 machine out of 600. Is it something to do with electron ?
