### ISSUE TITLE
[Bug]: flattenRoutes recursion broken in production

### ISSUE THREAD

**Issue by pleymor** [remix-run/react-router#11572]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

Crate a Tauri project with Vite and React
Run cargo tauri build --debug
Run the windows installer newly created
Launcher the application
A 404 appears 
Open the inspector
Place a beak point in the function flattenRoutes
See the branches variable gets 2 elements in the recursive callee but these elements are not added to the branches variable of the recursive caller.

### Expected Behavior

flattenRoutes should return the elements of all the recursion levels.

### Actual Behavior

flattenRoutes returns an empty array, leading to a 404 Not found (no match with "/")

**Comment by timdorr** [comment]
Can you add a reproduction here? We need to see some code to understand what's going on here.
