### ISSUE TITLE
[Bug]: '.' not resolving to splat path even with v7_relativeSplatPath future

### ISSUE THREAD

**Issue by mspiess** [remix-run/react-router#11629]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

1. Have a router with future `v7_relativeSplatPath` set to `true`.
2. Have an index/pathless layout route in the tree.
3. Have a splat route as a child (doesn't have to be a direct child).
4. Call `useResolvedPath('.')` in the splat route component.

Minimal example:
https://stackblitz.com/edit/github-9el7os?file=src%2Fapp.tsx

### Expected Behavior

The result of `useResolvedPath('.')` should include the splat.

>When you enable the flag, this "bug" is fixed so that path resolution is consistent across all route types, and useResolvedPath(".") always resolves to the current pathname for the contextual route. This includes any dynamic param or splat param values.

### Actual Behavior

The result of `useResolvedPath('.')` is the `pathnameBase`, i.e. lacking the splat part.

**Comment by brophdawg11** [comment]
This is resolved via https://github.com/remix-run/react-router/pull/11633.  This got merged to `dev` after the `6.24.0-pre.N` release branch was cut, so it will be included in the next release after `6.24.0`.
