### ISSUE TITLE
How can I implement the prompt functionality when I am using BrowserRouter as my Router in react-router v6?

### ISSUE THREAD

**Issue by Akshay-21-crypto** [remix-run/react-router#11636]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

Recently I have upgraded to react router version 6.23.1. At few places in my application, I have used Prompt to display a modal to the user before navigating to a different page, when there are some unsaved changes in the current page. Since, Prompt was removed in version 6, this feature was breaking. After going through the latest docs, found that useBlocker can be used to implement the same behavior. But the problem is useBlocker can only be used when data routers are being used. In my application, I am using BrowserRouter component. So I can't use useBlocker. 

### Expected Behavior

How can I implement the blocking behavior now, without using data routers

### Actual Behavior

useBlocker is giving an error as I am not using data routers.

**Comment by timdorr** [comment]
You can either use [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) yourself, or switch to a data router.

**Comment by marcellobarile** [comment]
@timdorr, what about for example the `go back` where the `popstate` event is triggered? It seems that without having access to the router's internals it's not possible to cancel the operation; isn't it?
