### ISSUE TITLE
[Bug]: Page unmount when go to next page

### ISSUE THREAD

**Issue by mehardiknaik** [remix-run/react-router#11634]
### What version of React Router are you using?

6

### Steps to Reproduce

When i navigate from one page to other page my previous page goes umounted
 I want react navigation like stack screen behaviour where i send prop <Route mounted/>

### Expected Behavior

Keep previous page mounted 
I want 
`{
    path: "/",
    element: <div>Hello world!</div>,
   mounted:true
  },`

### Actual Behavior

The page unmounted and when i click back it will remount again

**Comment by timdorr** [comment]
That isn't how React Router is architected. If you want to retain prior components, you need to nest you components underneath each other so that the parents can be retained while you navigate deeper in the route tree.
