### ISSUE TITLE
Nice to Have: npx migrate-react-router-v7 cli

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#11637]
We already have `npx upgrade-remix`, could work like that.

**Comment by brophdawg11** [comment]
Main codemods
* package.json: @remix-run/* -> @react-router/*
* package.json: @remix-run/react -> react-router
* Update all imports to use the new package names
* RemixServer -> ServerRouter
* RemixBrowser -> HydratedRouter

**Comment by jrestall** [comment]
Thanks for creating codemods, will make converting a very large monorepo with several remix apps a lot easier. 

Any love for the stub testing api changes? We have 1000's of imports that will need to change. Hopefully it's just the function name and not deeper breaking changes like the function parameters?

createRemixStub -> createRoutesStub

```ts
import { createRemixStub } from "@remix-run/testing"; -> import { createRoutesStub } from "react-router";
```

```ts
// Before
const RemixStub = createRemixStub([
      {
        path: "/accounts",
        ...

// After
const RoutesStub = createRoutesStub([
      {
        path: "/accounts",
        ...
```

**Comment by brophdawg11** [comment]
Good catch!  Added to the list above - we've already renamed to [`createRoutesStub`](https://github.com/remix-run/react-router/blob/dev/packages/react-router/lib/dom/ssr/routes-test-stub.tsx#L93) in the v7 code 👍

**Comment by pcattori** [comment]
Closing this as the venerable @jrestall made a [codemod](https://codemod.com/registry/remix-2-react-router-upgrade) that we're [recommend in our docs](https://reactrouter.com/7.0.1/upgrading/remix)
