### ISSUE TITLE
Deduplicate code from various packages into "react-router"

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#11646]
- PR https://github.com/remix-run/react-router/pull/11698
- Followup PR to remove re-exports: https://github.com/remix-run/react-router/pull/11702

Pedro had started working on this task to move all shared things into the `"remix"` package, now it all goes to `"react-router"`

**Comment by markdalgleish** [comment]
I've started lo look into this as part of moving the runtime/adapter packages out of the monorepo since it means we likely don't want to re-export the entire `server-runtime` API from these standalone packages anymore.
