### ISSUE TITLE
add deprecation warnings to RR v6 and Remix v2

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#11648]

**Comment by brophdawg11** [comment]
* Add warnings for stable future flags
* Add deprecation warnings to APIs - `json`/`defer` in Remix
  * Probably can't warn from the utils but can detect the type of response returned from loader/action and warn there?
* Remove `json`/`defer` in Rr v7
* Update `redirect` utils in v7 to use `data` under the hood

**Comment by brophdawg11** [comment]
https://github.com/remix-run/remix/pull/10126

**Comment by brophdawg11** [comment]
https://github.com/remix-run/react-router/pull/12144
