### ISSUE TITLE
[Bug]: Navigate did not update URL

### ISSUE THREAD

**Issue by kberridge** [remix-run/react-router#11673]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

I'll show the code snippets below to illustrate the setup, but this is a redirecting index page pattern, so the index route fetches some data and renders a <Navigate>, the page is correctly re-rendering, but the URL is not updating.  And to make matters worse, this appears to be some kind of race condition because it works as expected sometimes and not others.  I also have two identical versions of this pattern on different pages and one always works, and the other reliably sometimes doesn't work.

The routes look like this:
```tsx
return {
    path: "home",
    children: [
      {
        index: true,
        element: <DashboardIndexRedirect />,
        loader: () => indexLoader(),
      },
      {
        path: "tab1",
        lazy: async () => {
          const { Tab1, loader } = await import("./tab1");
          return {
            element: <Tab1 />,
            loader: () => loader(),
          };
        },
      },
```
The redirect looks like this:
```tsx
async function indexLoader(standardApiClient: ApiClient) {
  return /* ... fetch the last tab the user was on ... */
}

function DashboardIndexRedirect() {
  const tabType = useLoaderData() as TabTypeSystemKey;
  return (
    <LoadingPage context={props.context}>
      <Navigate replace to={`/home/${tabType}`} />
    </LoadingPage>
  );
}
```

The <Navigate> component is absolutely updating and the page is re-rendering, but when it does the URL stays /home instead of updating to /home/tab1.  Oddly, hitting F5 always DOES redirect to /home/tab1, but following a <Link to="/home" /> never redirects to /home/tab1 the first time.  Sometimes subsequent times do work.  But on another page that is using exactly the same route structure and redirect patterns it always works.

After a ton of random troubleshooting I discovered that removing the loader on the index route makes it always reliably redirect.  So my work around for now was to not use loader on <DashboardIndexRedirect> and implement the loading in a useEffect inside the component instead (which fortunately I can get away with here because that component is basically just a fancy fallback element anyway).

Very interestingly, even if I update the indexLoader so that it is not async and does not call fetch and simply does `return "tab1"`, it still has the race condition.

This is so odd that it seems like it could be some kind of loader related race condition in react router.  There could be some oddity of our code contributing too of course...  But if so, I'm totally stumped as to what it could be at this point.

Thanks,
Kevin

### Expected Behavior

Expected the URL to update and the new page to render, every time.

### Actual Behavior

The new page renders, but the URL does not update (or it's being set back I don't know), but it does not do that when the page is refreshed (F5), only when following a <Link>.

**Comment by brophdawg11** [comment]
When using a data router, you should `redirect` from your loader instead of your component because of the decoupled fetching/rendering.  By redirecting on initial render I think you may be creating a race condition between two `history.pushState`/`replaceState` calls in the same tick and browsers don't always handle those consistently.

Instead of passing the location up to the component and using `Navigate`, you can `redirect` from the `loader`:

```jsx
return {
  path: "home",
  children: [{
    index: true,
    loader() {
      let tabType = await indexLoader();
      return redirect(`/home/${tabType}`);
    },
  }
  ...
```

**Comment by kberridge** [comment]
Thank you!! That is working perfectly, and is so much simpler too.

**Comment by huykon** [comment]
Hi @brophdawg11 @kberridge I'm using redirect from `action` but the url still not change
