### ISSUE TITLE
[Bug]: Incomplete TS support for useLocation

### ISSUE THREAD

**Issue by sparrowek** [remix-run/react-router#11684]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

I use 
```
const state: NavigationState = { from: location.pathname };
<Navigate to="/login" state={state} />
```
to redirect user to a login page passing the original location to redirect to after successful login

I have found that in router v6 the following code breakes:
```
const navigate = useNavigation();
const from = location.state.from
```
because state can be udefined when the user enters the login page directly (it seems it was not in the v5 version)

TS cannot warn about it because state is typed as "any" and there is no way to specify the type here
```
export declare function useLocation(): Location;
export interface Location<State = any> extends Path
```

The Location interface can provide the type for state but the useLocation is missing this opportunity.

### Expected Behavior

I would like to provide type for useLocation like this:
location = useLocation<{ from: string } | undefined>
location.state?.from

### Actual Behavior

location = useLocation();
location.state.from -> no TS warning here

**Comment by timdorr** [comment]
This has been suggested many times. 

This would actually remove type safety, as you would be overriding `state` to that type. You should be using type narrowing to determine the type of `state` safely. A generic would be a hack to force that to work.

https://github.com/remix-run/react-router/pull/8370#issuecomment-974578233
https://github.com/remix-run/react-router/issues/8396#issuecomment-980829670
