### ISSUE TITLE
fix responseStub

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#11707]
API is cumbersome, I'm thinking this:

```tsx
function loader({ response }) {
  // change status
  response.status(404)

  // append/set headers
  response.headers.append('Cookie', 'foo=bar')
  response.headers.set('X-Foo', 'bar')

  // redirect (throws)
  response.redirect('/login')
  response.redirect(`/post/${newPostId}`, 303)

  // redirect with status and SET headers
  response.headers.set('Cookie', clearedCookie())
  response.redirect('/login', 303)

  // raise (throw) data and status to the error boundary
  response.raise('Not Found', 404)
}
```

**Comment by roonie007** [comment]
@brophdawg11 That would actually be better

**Comment by brophdawg11** [comment]
Per the discussion in the latest roadmap planning livestream (https://www.youtube.com/live/f5z_axCofW0?feature=shared&t=1009) we've decided to backtrack on `responseStub`. Keep an eye out in an upcoming release for the new approach - we're going to stick to using `headers` to align with current Remix approaches.
