### ISSUE TITLE
[Bug]: navigate breaks browser's back and forward navigation in Chrome 126.0.6478.63 (Official Build) (arm64)

### ISSUE THREAD

**Issue by ghanlohar** [remix-run/react-router#11713]
### What version of React Router are you using?

6.23.1

### Steps to Reproduce

To reproduce the issue I have created a [CodeSandbox here](https://codesandbox.io/p/sandbox/router-v6-navigate-vz66tr?file=%2Fsrc%2FApp.js):
Following are the steps to reproduce the issue:

1. Visit https://vz66tr.csb.app/about
2. Click on Link1
3. Click on Link2
4. Click on Link3
5. Click on Link4
6. Click on browser back button 3-4 times
7. Verify that the browser back & forward buttons are disabled
8. Click anywhere on the page in the browser
9. Back button enables but forward button will be disabled.
10. If you try to play a bit more, you will see history is modified incorrectly 

Video here for reference:
https://github.com/remix-run/react-router/assets/5575651/92b5dcd8-7b4e-4855-b156-b8783af4e2ce

Versions:

- react - 18
- react-router - 6.23.1
- chrome - 126.0.6478.63 (Official Build) (arm64)

### Expected Behavior

Browser back and forward button must not be disabled & should work consistently.

### Actual Behavior

When we use navigate with search and hash together, browser's history messed up sometimes.

**Comment by timdorr** [comment]
You are navigating with regular `<a>` tags, which don't hook into the lifecycle of the router correctly.  This isn't a bug with React Router.

**Comment by ghanlohar** [comment]
Hey @timdorr thanks for replying. That made sense to me, I replaced `<a>` with `<link>` [here](https://codesandbox.io/p/sandbox/router-v5-history-forked-2h7nkw?file=%2Fsrc%2FuseLinkCountHook.js%3A71%2C19-71%2C26). I think same issue exist in this set up.
