### ISSUE TITLE
[Docs]: Tutorial missing imports within 'contacts.js'. [ "match-sorter" , "localforage" , "sort-by" ]

### ISSUE THREAD

**Issue by leventeberry** [remix-run/react-router#11737]
### Describe what's incorrect/missing in the documentation

Upon completing the steps within the [Loading Data](https://reactrouter.com/en/main/start/tutorial#loading-data) portion of the tutorial, an error occurs regarding three imports that are unretrievable:

- `import localforage from "localforage";`
- `import { matchSorter } from "match-sorter";`
- `import sortBy from "sort-by";`

Please include these files as apart of the beginning scaffolding within the [Setup](https://reactrouter.com/en/main/start/tutorial#setup) portion of the tutorial.

![image_2024-06-26_201338560](https://github.com/remix-run/react-router/assets/53123391/62bae9f9-eb27-4c7e-88e4-34110fae3c0c)

**Comment by timdorr** [comment]
These are installed in the Setup section: https://reactrouter.com/en/main/start/tutorial#setup
