### ISSUE TITLE
[Bug]: unstable_patchRoutesOnMiss is superseded by "*" (404)

### ISSUE THREAD

**Issue by Wykks** [remix-run/react-router#11746]
### What version of React Router are you using?

6.24.0

### Steps to Reproduce

https://stackblitz.com/edit/github-tgrtuk-ngtlrk?file=src%2Fapp.tsx

### Expected Behavior

`unstable_patchRoutesOnMiss` should be called when going to a unknown route on bootstrap

### Actual Behavior

When you click on the link to /test, it does call `unstable_patchRoutesOnMiss`

But,when you go directly to /test, it should call `unstable_patchRoutesOnMiss`, but instead it's just showing the 404 page.

**Comment by brophdawg11** [comment]
Thats for the reproduction!  This will be fixed by #11759 but in the meantime you could work around this by leaving the splat route out of the initial routes and applying it to the route tree via `patchRoutesOnMiss` when needed
