### ISSUE TITLE
[Bug]:  Could not resolve './utils' from packages/router/index.ts

### ISSUE THREAD

**Issue by dominate666** [remix-run/react-router#11779]
### What version of React Router are you using?

6.24.1

### Steps to Reproduce

git clone git@github.com:remix-run/react-router.git
pnpm install
pnpm run build

### Expected Behavior

The command pnpm run build is successful

### Actual Behavior

 Could not resolve './utils' from packages/router/index.ts

**Comment by timdorr** [comment]
This isn't a valid installation method for React Router, nor is it expected to be working at all time.

**Comment by dominate666** [comment]
So what should I do?

**Comment by TusharYaar** [comment]
Hi, I'm also facing this issue, were you able to resolve it ?

**Comment by TusharYaar** [comment]
Figured it out. You can't built it on windows. use wsl or docker with pnpm. Works like a charm.
