### ISSUE TITLE
[Bug]: Link when used with Outlet is not working. It is routing to error page when clicked. 

### ISSUE THREAD

**Issue by ashwiniraj096** [remix-run/react-router#11781]
### What version of React Router are you using?

6.24.1

### Steps to Reproduce

Following along with the Tutorial. Client side routing made with Link element in root.jsx causing issue. 

### Expected Behavior

contacts/:id URL should load Contact Page

### Actual Behavior

contacts/:id URL is routed to Error Page instead of Contact Page
![image](https://github.com/remix-run/react-router/assets/35617003/cca7d8d6-5cb6-42c4-b8a6-554a539f1dfb)
![image](https://github.com/remix-run/react-router/assets/35617003/6fa2933e-61c7-4c9a-80f6-cda1fd458658)

**Comment by kiliman** [comment]
The error is `Link is not defined`. Did you remember to import it?

```ts
import { Link } from 'react-router-dom'
```
https://reactrouter.com/en/main/components/link
