### ISSUE TITLE
[Bug]: setSearchParams from useSearchParams remove hash

### ISSUE THREAD

**Issue by MariusJam** [remix-run/react-router#11788]
### What version of React Router are you using?

6.22.3

### Steps to Reproduce

1. Navigate to a page and add a hash to the url
2. Call setSearchParams to add some query params to the url

Example available here: https://stackblitz.com/edit/github-zuy2xj?file=src%2Fapp.tsx

### Expected Behavior

Both the hash and query params should be in the final URL. As stated in react-router documentation "The useSearchParams hook is used to read and modify the query string in the URL" so, the hash in the URL should not be impacted.

### Actual Behavior

Query params are in the url but the hash is completely removed.

**Comment by timdorr** [comment]
You're updating the location outside of the router's knowledge (via direct DOM access), so it doesn't know that you've changed it and it needs to take that change into account.

Another way to look at it: the hash is supposed to be for linking to a specific part of the page. If you change the query parameters, you are technically on a new page with potentially different content and therefore different anchors on the page for the hash to link to.
