### ISSUE TITLE
[Bug]: HashRouter need to wrapped twice

### ISSUE THREAD

**Issue by shalevsharabi** [remix-run/react-router#11795]
### What version of React Router are you using?

6.24.1

### Steps to Reproduce

1. Create a Component that uses react-router functionality (In a Outsource library)
2. Config project to work in react-router
3. Wrapped it with a HashRouter
4. Use the Component (React project)
5. Run it
6. Failed to run, Error in the console of 'useLocation() may be used only in the context of a <Router> component.'

### Expected Behavior

The Outsource Component should 'know' about the parent HashRouter wrapper, and not fail to run.

### Actual Behavior

Right now throw an exception.

If I wrap the library and the project in 2 HashRouter (One for each one), it can run (What it is not supposed to), but a kind of weird behavior happened (With the state of the URL params)

**Comment by timdorr** [comment]
This is likely because you have two different copies of React Router in your module tree. You can confirm this with `npm ls react-router`. These need to be the exact same copy (not just the same version) so that we can access the same instances of key internals across different packages.
