### ISSUE TITLE
[Docs]: docs show reach/router instead of react/router

### ISSUE THREAD

**Issue by busylink** [remix-run/react-router#11797]
### Describe what's incorrect/missing in the documentation

Found on serveral pages. https://reactrouter.com/en/main/upgrading/reach#install-react-router-v6

<img width="769" alt="image" src="https://github.com/user-attachments/assets/df01b0a4-f33c-4db0-b29f-2e1105ae11ee">

**Comment by rschristian** [comment]
What's do you think is incorrect?

That page is talking about migrating from [`@reach/router`](https://npm.im/@reach/router), an entirely separate package to React Router, hence the version mismatch in the comment:

> If we were to make a `@reach/router` v2, it would look pretty much exactly like React Router v6.

**Comment by timdorr** [comment]
Correct, this is for the prior Reach ecosystem. It's supposed to reference it.
