### ISSUE TITLE
[Bug]: v7_partialHydration with unstable_patchRoutesOnMiss: hydrateFallbackElement not shown on patched routes

### ISSUE THREAD

**Issue by Manizuca** [remix-run/react-router#11812]
### What version of React Router are you using?

6.25.0

### Steps to Reproduce

https://stackblitz.com/edit/github-smnznp?file=package.json,src%2Fapp.tsx

- Have a route that gets patched with unstable_patchRoutesOnMiss
- Enable v7_partialHydration and add hydrateFallbackElement to the root route
- Add some delay to the root loader function

### Expected Behavior

The fallback element of the root route is shown while the loaders are executing

### Actual Behavior

No fallback is shown
- In the example, load the application at  /without-loading-indicator
- For routes defined from the start, it is shown correctly, like /with-loading-indicator

**Comment by brophdawg11** [comment]
I am not seeing the described behavior. When I load `/without-loading-indicator` in your stackblitz I see the loading indicator:

![Screenshot 2024-07-17 at 1 41 34 PM](https://github.com/user-attachments/assets/6ec1f222-d1f2-436d-8d96-df6b29e25292)

**Comment by Manizuca** [comment]
Hi @brophdawg11 
There is apparently a difference between different browsers, when there is a promise that gets immediately resolved. In Firefox i dont get the message, but in chrome i do

I've updated the demo, so the children promise resolves after 10ms instead of 0ms, and now i get the same behaviour in chrome and firefox (the loading indicator is not shown)
https://stackblitz.com/edit/github-smnznp-pcfnbz?file=package.json,src%2Fapp.tsx
