### ISSUE TITLE
[Bug]: Navlink className function props not work as expected it

### ISSUE THREAD

**Issue by F-z-Coder** [remix-run/react-router#11878]
### What version of React Router are you using?

    "react-router-dom": "6.26.0",

### Steps to Reproduce

       <NavLink
          to={item.url}
          className={({ isActive }) =>
            cn(
              buttonVariants({ variant: item.variant, size: "icon" }),
              item.variant === "default" &&
                "dark:bg-muted dark:text-muted-foreground dark:hover:bg-muted dark:hover:text-white",
              isActive && "bg-primary-foreground",
            )
          }
        >
          <item.icon className="h-8 w-8" />
          <span className="sr-only">{item.title}</span>
        </NavLink>

### Expected Behavior

it render string classname

### Actual Behavior

```
<a data-state="closed" class="({ isActive }) => cn(
          buttonVariants({ variant: item.variant, size: &quot;icon&quot; }),
          item.variant === &quot;default&quot; &amp;&amp; &quot;dark:bg-muted dark:text-muted-foreground dark:hover:bg-muted dark:hover:text-white&quot;,
          isActive &amp;&amp; &quot;bg-primary-foreground&quot;
        )" href="/dashboard"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-layout-dashboard h-8 w-8"><rect width="7" height="9" x="3" y="3" rx="1"></rect><rect width="7" height="5" x="14" y="3" rx="1"></rect><rect width="7" height="9" x="14" y="12" rx="1"></rect><rect width="7" height="5" x="3" y="16" rx="1"></rect></svg><span class="sr-only">Dashboard</span></a>
```

**Comment by pawelblaszczyk5** [comment]
By the `data-state=“closed”` I assume that’s not the full reproduction. 

Maybe you’re using something like Radix with `asChild` prop? Commonly libraries made to merge props have some assumptions about className prop being a string

**Comment by timdorr** [comment]
Yeah, something else is transforming this code if you're ending up with the function being printed as a string to the DOM. This isn't a bug with the library.

**Comment by cabello** [comment]
Thank you for the insight, this happened to me and yes it was Radix Tabs interfering with NavLink class name:
Something like:

```
<TabsTrigger key={key} value={key} asChild>
                    <NavLink
                      to={`/components/${key}`}
                      className=// can't use className function here as radix merges it as string
                    >
```

Options are:
a) wrap a div before asChild, deal with the styling differences
b) find another approach, in my case I extract the active from the location path and pass it as a tab value
