### ISSUE TITLE
[Bug]: HashRouter need to wrapped twice

### ISSUE THREAD

**Issue by shalev312** [remix-run/react-router#11870]
### What version of React Router are you using?

6.26.0

### Steps to Reproduce

Create a Component that uses react-router functionality (In a Outsource library)
Config project to work in react-router
Wrapped it with a HashRouter
Use the Component (React project)
Run it
Failed to run, Error in the console of 'useLocation() may be used only in the context of a component.'

### Expected Behavior

The Outsource Component should 'know' about the parent HashRouter wrapper, and not fail to run.

### Actual Behavior

Right now throw an exception.

If I wrap the library and the project in 2 HashRouter (One for each one), it can run (What it is not supposed to), but a kind of weird behavior happened (With the state of the URL params)

** Only one instance of the library

<img width="269" alt="Screenshot 2024-08-04 at 1 40 49" src="https://github.com/user-attachments/assets/01e5d221-35c9-45fc-977e-5e0db69cd4be">

**Comment by timdorr** [comment]
This is likely something with how the app is being built and bundled, resulting in two instances of the library. Separate instances of some key internal variables is the reason you would get this message, so something about your build process is likely resulting in this. This isn't a bug in the library.
