### ISSUE TITLE
[Docs]: Switched parameters in matchPath

### ISSUE THREAD

**Issue by martinadamec** [remix-run/react-router#11894]
### Describe what's incorrect/missing in the documentation

In doc you have
```
import { matchPath } from "react-router";

const match = matchPath("/users/123", {
  path: "/users/:id",
  exact: true,
  strict: false
});
```
but parameters should be switched to:
```
import { matchPath } from "react-router";

const match = matchPath({
  path: "/users/:id",
  exact: true,
  strict: false
}, "/users/123");
```
source code: https://github.com/remix-run/react-router/blob/main/packages/router/utils.ts#L967

**Comment by timdorr** [comment]
You are looking at the v5 docs. That code is for v6, which is the current version of the library.
