### ISSUE TITLE
[Bug]: Relative option is not work in useNavigate

### ISSUE THREAD

**Issue by avs-doom** [remix-run/react-router#11914]
### What version of React Router are you using?

6.26.1

### Steps to Reproduce

1) Get navigate function at useNavigate hook
2) Set navigate option is { relatiove: 'path' } or { relative: 'route' }

### Expected Behavior

The behavior of relative routing is changing

### Actual Behavior

The behavior of relative routing does not change with any configuration.

After the update from 6.16 to 6.26, everything stopped working as I expected, I know about the v7_relativeSplatPath flag, but this does not solve the problem because the behavior that was in version 6.16 no works anymore

**Comment by timdorr** [comment]
Can you please provide an example, preferrably something in CodeSandbox or StackBlitz?

**Comment by avs-doom** [comment]
> Can you please provide an example, preferably something in CodeSandbox or StackBlitz?

https://codesandbox.io/p/devbox/cranky-sammet-spfyy3

Version 6.16 is used there, if the same thing is run on version 6.26.1, then it doesn’t matter what to pass to navigation options.

**Comment by timdorr** [comment]
You're not doing a relative navigation in that code, which is when you go up the path chain using `..`. The `relative` option refers to how it resolves the `..` into a final path.
