### ISSUE TITLE
[Docs]: Grammatical error. It should be "further along" not "farther along"

### ISSUE THREAD

**Issue by Mtendekuyokwa19** [remix-run/react-router#12036]
### Describe what's incorrect/missing in the documentation

The docs has a grammatical error. It says "farther along" instead of "further along" This is grammatically incorrect.
A reference for extra support is here [here](https://www.dictionary.com/e/farther-vs-further/#:~:text=The%20widely%20accepted%20rule%20is%20to%20use%20farther%20when%20being%20literal%20and%20discussing%20a%20physical%20distance%2C%20as%20in%20%E2%80%9CHe%20went%20farther%20down%20the%20road.%E2%80%9D%C2%A0Further%20is%20used%20when%20discussing%20a%20more%20symbolic%20distance%20or%20to%20discuss%20a%20degree%20or%20extent%2C%20as%20in%C2%A0%E2%80%9CI%20wanted%20to%20discuss%20it%20further%2C%20but%20we%20didn%E2%80%99t%20have%20time.%E2%80%9D) .

[This](https://reactrouter.com/en/main/start/tutorial#:~:text=we%27ll%20have%20nested%20layouts%20as%20we%20get%20farther%20along.) is the docs error. 
I am open to fixing this error.I just need a go ahead

**Comment by timdorr** [comment]
Please make a PR for docs updates, not an issue.
