### ISSUE TITLE
[Bug]: createRouter never defined in the CDNJS package

### ISSUE THREAD

**Issue by mmorris8** [remix-run/react-router#12041]
### What version of React Router are you using?

6.26.2

### Steps to Reproduce

Call createBrowserRouter() always returns error

```
Uncaught TypeError: Cannot read properties of undefined (reading 'createRouter')
    at createBrowserRouter (react-router-dom.development.js?r=172cb168de3838bf645df51378d228be6f583615:277:19)
    at Root.jsx:12:16
    at search.js:12:32
```

A scan of the react-router-dom file shows it only has 2 references to createRouter and neither is a definition.

How did this get past automated testing?  The CDN file @ https://[cdnjs.cloudflare.com/ajax/libs/react-router-dom/6.26.2/react-router-dom.development.js](https://cdnjs.cloudflare.com/ajax/libs/react-router-dom/6.26.2/react-router-dom.development.js) is unusable.

### Expected Behavior

```
import React from 'react'
import {Tabs, TabList, Tab, TabPanel} from 'react-aria-components'

import {
  createBrowserRouter,
  RouterProvider,
  Outlet,
  useLocation,
  useNavigate
} from "react-router-dom"

const router = createBrowserRouter([{
  path: "/",
  element: <AppTabs />,
  
  children: [
    {
      index: true,
      element: <div>I'm Home</div>
    },
    {
      path: "one",
      element: <div>Page One</div>
    },
    {
      path: "two",
      element: <div>Page Two</div>
    },
    {
      path: "three",
      element: <div>Page Three</div>
    }
  ]
}], {basename: "/search/"})

function AppTabs() {
  const { pathname } = useLocation() ?? 'all'
  console.log(pathname)

  return (
    <Tabs selectedKey={pathname ? pathname : 'all'}>
      <TabList aria-label="Tabs">
        <Tab id="/" href="./">Home</Tab>
        <Tab id="/one" href="one">One</Tab>
        <Tab id="/two" href="two">Two</Tab>
        <Tab id="/three" href="three">Three</Tab>
      </TabList>
      <TabPanel id={pathname ? pathname : 'all'}>
        <Outlet />
      </TabPanel>
    </Tabs>
  )
}


export default function App() {
 return <RouterProvider router={router} /> 
}
```

This works in a react app created by create-react-app.  It fails in an app using esbuild to provide react-router-dom via the cdn library.

### Actual Behavior

See above

**Comment by mmorris8** [comment]
And thinking I missed an **undocumented** dependency I added ReactRouter to the build.  Still doesn't work.

So do the world a favor and advertise your product as completely unusable unless packed into the distro using webpack or rollup. The CDNs are POINTLESS.

**Comment by timdorr** [comment]
This isn't an issue with the library. That function is exported from the UMD build. There may be particular ways you need to configure your build tool  to handle it properly, but that is not something we have to make any changes for on our end.

Also, please don't attempt to yell at us with heading text. We're volunteer software developers. Not cool man.

**Comment by matigarowel** [comment]
Same issue I'm using CDN (cause I will host my app on 1mb file storage susch us ESP2866). I'm using https://unpkg.com/react-router-dom@6/dist/umd/react-router-dom.production.min.js. and webpack.config.js
