### ISSUE TITLE
Get "Expected fetch controller: :r1:" when calling fetcher.load and revalidator.revalidate

### ISSUE THREAD

**Issue by tmcw** [remix-run/react-router#12049]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-l7uvb2?file=app%2Froutes%2F_index.tsx

Open your developer tools console and click Trigger revalidations

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @remix-run/dev: * => 2.12.1 
    @remix-run/node: * => 2.12.1 
    @remix-run/react: * => 2.12.1 
    @remix-run/serve: * => 2.12.1 
    vite: ^5.1.0 => 5.4.7
```

### Used Package Manager

npm

### Expected Behavior

It should be possible to call fetchers and revalidators without throwing errors.

### Actual Behavior

If you call

```ts
revalidator.revalidate();
revalidator.revalidate();
fetcher.load('/');
```

Then you will reliably trigger an uncaught error. If there's idle state to be dealt with here, it should possibly be dealt with behind the scenes. The revalidator docs state:

> Race conditions are automatically handled when calling revalidate() when a revalidation is already in progress for any other reason.

Maybe we're supposed to handle race conditions with `fetcher.load`, but I don't see any notes about having to do that in the fetcher docs.

**Comment by brophdawg11** [comment]
This doesn't cause any runtime issues right? Just an unexpected thrown error in the background, the associated console log, and maybe a `window.onerror` handler?  Going tov remove this overzealous check in #12050 but just confirming there's no user-facing impact to ensure we're seeing the full picture
