### ISSUE TITLE
[Docs]: v7 alpha -- layout example doesn't work

### ISSUE THREAD

**Issue by gregory-j-baker** [remix-run/react-router#12079]
### Describe what's incorrect/missing in the documentation

The [layout routes example](https://reactrouter.com/dev/guides/start/routing#layout-routes) doesn't work. The `route(..)` function on line 13 requires a filename as its second argument which is missing from the example.

**Comment by nulfrost** [comment]
similar to #12068

**Comment by brophdawg11** [comment]
I believe this is fixed and the docs updated with the new `prefix` API - that should be out in a new prerelease tomorrow or early next week
