### ISSUE TITLE
[Bug]: Invalid type inference for `data` function

### ISSUE THREAD

**Issue by houfio** [remix-run/react-router#12102]
### What version of React Router are you using?

7.0.0-pre.0

### Steps to Reproduce

I'm writing a simple loader that returns raw data and headers, using the `data()` function.

### Expected Behavior

I'd expect the inferred `loaderData` type to be the type of the data that is given to the `data()` function.

### Actual Behavior

Instead, the `loaderData` type contains all fields that the `data()` function returns.

See https://stackblitz.com/edit/github-hzv5zx?file=app%2Froutes%2Fhome.tsx

**Comment by brophdawg11** [comment]
This should be fixed by https://github.com/remix-run/react-router/pull/12073 and available in the next prerelease 👍
