### ISSUE TITLE
[Bug]: v7pre vanilla-extract/vite-plugin

### ISSUE THREAD

**Issue by ziimakc** [remix-run/react-router#12128]
### What version of React Router are you using?

v7pre1

### Steps to Reproduce

```
import { reactRouter } from "@react-router/dev/vite";
import { vanillaExtractPlugin } from "@vanilla-extract/vite-plugin";
import { defineConfig } from "vite";

export default defineConfig(() => {
	return {
		plugins: [reactRouter(), vanillaExtractPlugin()],
	};
});
```
- Run `npm add @vanilla-extract/css @vanilla-extract/vite-plugin`
- Add `@vanilla-extract/vite-plugin` to config
- Run in dev mode or build

### Expected Behavior

No error

### Actual Behavior

Error: The React Router Vite plugin requires the use of a Vite config file

**Comment by kube** [comment]
This is the same issue as: https://github.com/vanilla-extract-css/vanilla-extract/issues/1311

Except that now, the Plugin is named React-Router instead of Remix.

**Comment by kube** [comment]
I created a PR to address this issue: https://github.com/vanilla-extract-css/vanilla-extract/pull/1492
