### ISSUE TITLE
[Bug]: When using custom `basename` in `SSR` `useLoaderData` doesn't work.

### ISSUE THREAD

**Issue by denchiklut** [remix-run/react-router#12125]
### What version of React Router are you using?

^6.26.2"

### Steps to Reproduce

setup routes:
```ts
export const routes: RouteObject[] = [
  {
    ...
      children: [
        {
          index: true,
          loader: async () => await fetchPosts(),
          element: <Home />
        },
        ...
      ]
  }
]
```

on server we can only set basname after we fetched data:
```ts
// render.middleware.ts
...
const { query } = createStaticHandler(routes)
const webRequest = createFetchRequest(req)
const context = await query(webRequest)

if (context instanceof globalThis.Response) {
  return res.status(context.status).redirect(context.url)
}

context.basename = basename
...
```

So when I a have a component that renders on server:
```ts
export const Posts = () => {
  const posts = useLoaderData() as PostsResponse

  return ...
}
``` 

posts is equal to undefined. But as soon as I set basname to `/` it works as expected.

To help with debugging here is a [link](https://github.com/denchiklut/ssr-boilerplate) to repo.

- loader function: [link](https://github.com/denchiklut/ssr-boilerplate/blob/0330e6985d05303c7456d7e508346f3bc651dbbb/src/client/components/%40shared/app/routes/index.tsx#L18)
- useLoaderData usage: [link](https://github.com/denchiklut/ssr-boilerplate/blob/0330e6985d05303c7456d7e508346f3bc651dbbb/src/client/components/home/posts/index.tsx#L5)
- render middleware: [link](https://github.com/denchiklut/ssr-boilerplate/blob/0330e6985d05303c7456d7e508346f3bc651dbbb/src/server/middleware/render/index.tsx#L31)

To run with custom `basname` add `CLIENT_HOST=http://localhost:3000/app` to the `.env` file (here `/app` will be used as basename for the router.)
Finally run `yarn dev` - app will crash because on server useLoaderData will return undefined instead of an array of data.

### Expected Behavior

When you use custom `basename` useLoaderData during ssr should return data (based on what you specified on `loader` function) 

### Actual Behavior

If you use custom `basename` useLoaderData during ssr returns undefined

**Comment by timdorr** [comment]
You add `basename` on `createStaticHandler`: https://reactrouter.com/en/main/routers/create-static-handler#type-declaration
