### ISSUE TITLE
[Bug]: previous route is still rendered during navigation with loader

### ISSUE THREAD

**Issue by youri-oliver** [remix-run/react-router#12130]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

https://stackblitz.com/edit/github-fmmzla

Click on "A route" and navigate to "B route"

### Expected Behavior

During navigating from A to B, the A component should not be rendered...

### Actual Behavior

During navigation from A to B, the A is still rendered. After the loader is finished with the setTimeout, the A is removed.

**Comment by youri-oliver** [comment]
Possible solution, but it feels kinda weird

```
{loading ? <Loader /> : <Outlet />}
```

The `<Outlet />` should update itself?

**Comment by timdorr** [comment]
This is expected behavior: https://reactrouter.com/en/main/start/overview#pending-navigation-ui

**Comment by youri-oliver** [comment]
@timdorr So the `<Outlet />` in the docs should be conditional as my "possible" solution, right? Else you are gonna have the problem I described...
