### ISSUE TITLE
[Bug]: React Router v7 is unable to pre-render files that import markdown

### ISSUE THREAD

**Issue by amanape** [remix-run/react-router#12155]
### What version of React Router are you using?

v7 prerelease

### Steps to Reproduce

1. Create some `.md` files in `/app/markdown` and import them into some components (e.g., through a `BlogAPI` class)
2. Set prerender function
```ts
    reactRouter({
      ssr: false,
      prerender: () => {
        const blogs = blogAPI.getAllBlogs();
        return blogs.map((blog) => `/blog/${stringToSlug(blog.data.title)}`);
      },
    }),
```
3. Build with `react-router build`
4. Error!

```
ERROR: No loader is configured for ".md" files:
    at failureErrorWithLog (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:943:7)
    at /Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/Users/.../Desktop/Personal/Other/all-hands-original/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
error: script "build" exited with code 1
```

### Expected Behavior

I should receive a `build` folder with the pre-render content for my routes

### Actual Behavior

Error is thrown!

**Comment by brophdawg11** [comment]
I think you probably just need a vite plugin that knows how to handle markdown files?  Something like https://www.npmjs.com/package/vite-plugin-markdown

**Comment by clintandrewhall** [comment]
I'm having this issue, even though I handle Markdown files in my `vite.config.ts` with `vite-plugin-markdown`.  The application works fine with markdown, but if I try to prepare a list in `prerender`, it fails:

```
export default {
  ssr: false,
  prerender: async () => {
    const articles = import.meta.glob<ArticleImport>('./src/content/articles/*.md', {
      eager: true,
    });

    return [
      '/',
      ...Object.values(articles)
        .map((article) => article.attributes.id)
        .map((id) => `/article/${id}`),
    ];
  },
...
}
```

Does `prerender` utilize the configuration specified in `vite.config.js`...?

Should this issue be reopened @timdorr @brophdawg11 ...?  Or am I missing something here?

**Comment by brophdawg11** [comment]
If you can provide a minimal reproduction with markdown files working normally and breaking when prerendering is enabled, we can take a look!

**Comment by zilahir** [comment]
i am also struggling with this, funny enough, the error comes earlier in my case: 

```
    const projects = import.meta.glob<ProjectImport>("./app/projects/*.md", {
      eager: true,
    });
```

when `eager` is `true`, i am getting: 

```
 [react-router] Error loading /[...]/react-router.config.ts: SyntaxError: Invalid or unexpected token
```

when it set to `false` this error not getting, but then i am unable to produce the required paths for the static content.

**Comment by noahtigner** [comment]
> I think you probably just need a vite plugin that knows how to handle markdown files? Something like https://www.npmjs.com/package/vite-plugin-markdown

I really wish this project was actively maintained
