### ISSUE TITLE
[Bug]: Issues with content update after react-router v6.25.1 change – requires multiple interactions or keydown event to reflect changes

### ISSUE THREAD

**Issue by 42-jan** [remix-run/react-router#12165]
### What version of React Router are you using?

17.0.2

### Steps to Reproduce

Checkout react-router-dom min. 6.25.1

### Expected Behavior

app renders changes directly like in version 6.25.0

### Actual Behavior

since this https://github.com/remix-run/react-router/pull/11803 (6.25.1) change i have problems with updating content on a page (in my react app). when i change text by clicking a button, this is only changed when the button is clicked again or when a button is pressed (“keydown-event”) or the rendering is only partially executed for some components after a short waiting time.

**Comment by timdorr** [comment]
Can you provide a reproduction of this issue on something like Codesandbox or StackBlitz?
