### ISSUE TITLE
[Bug]: (v7) typegen doesn't take into account `appDirectory` config setting

### ISSUE THREAD

**Issue by vsnig** [remix-run/react-router#12162]
### What version of React Router are you using?

7.0.0-pre.1

### Steps to Reproduce

This repo is a clone of the sample app (`npx degit remix-run/react-router/templates/basic#dev my-app`) with `{appDirectory: './app/website'}` config setting and files that previously were in `app` moved to `app/website`
```
> git clone https://github.com/vsnig/rr-v7-typegen
> npm i
> npm run typecheck
```

### Expected Behavior

Path to generated routes types should be `.react-router/types/app/website/routes`

### Actual Behavior

Path to generated routes types is `.react-router/types/app/routes`
Not taking into account `appDirectory` config setting and making them impossible (as far as I can see) to import

**Comment by pcattori** [comment]
Fixed by #12190 in 7.0.0-pre.5
