### ISSUE TITLE
[Bug]: Inaccurate Peer Dependency Declaration in react-router-config

### ISSUE THREAD

**Issue by Deol** [remix-run/react-router#12173]
### What version of React Router are you using?

6.27.0

### Steps to Reproduce

react-router-config version: 5.1.1
react-router version: 6.x

```
import { matchRoutes } from 'react-router-config';

const routes = [
  {
    component: Root,
    routes: [
      {
        path: "/",
        exact: true,
        component: Home
      },
      {
        path: "/child/:id",
        component: Child,
        routes: [
          {
            path: "/child/:id/grand-child",
            component: GrandChild
          }
        ]
      }
    ]
  }
];

matchRoutes(routes, "/child/23");
```

```
pathname.match is not a function
TypeError: pathname.match is not a function
    at matchPath (webpack-internal:///./node_modules/@remix-run/router/dist/router.js:834:24)
    at eval (webpack-internal:///./node_modules/react-router-config/esm/react-router-config.js:23:85)
    at Array.some (<anonymous>)
    at matchRoutes (webpack-internal:///./node_modules/react-router-config/esm/react-router-config.js:22:10)
```

### Expected Behavior

The react-router-config@5 package should list react-router@5 as a peer dependency to ensure compatibility. This prevents runtime issues with the matchPath function, which changed in react-router@6. Users need to use react-router-config safely without errors related to matchPath.

### Actual Behavior

The peerDependencies for react-router-config@5.1.1 state that react-router must be version >=5. However, with the release of react-router@6, the matchPath function changed in a way that breaks compatibility with react-router-config@5. As a result, using react-router-config@5 with react-router@6 can lead to issues.

**Comment by timdorr** [comment]
While the peerDep is wider than it should be (we built that package well before v6 was even conceived), it's still on the user to install the correct version. This is an older and deprecated package (it's code is not even easily visible in this repo), so we won't be updating it.
