### ISSUE TITLE
[Bug]: useNavigate does not work correctly if used outside of the route file

### ISSUE THREAD

**Issue by alexfoxy** [remix-run/react-router#12174]
### What version of React Router are you using?

6.27.0

### Steps to Reproduce

This is perhaps unintended use of the useNavigate hook, but in our system we want to have a global store that is able to navigate. 

Simple example here: https://codesandbox.io/p/sandbox/react-router-navigate-example-fzlq8s

1. Go to the "/" route, in this basic example this sets the "navigate" function on the "navigationStore"
2. Press "Apple" in the toolbar which navigates to "/apple"
3. Press "See extra" on the page which navigates to "/apple/extra"
4a. Press "Go back". This works as intended, and goes back to "/apple". This is using `<Link to=".."`
4b. Press "Navigate back". This goes back to "/" which is not intended. This is using the global navigationStores navigate method.

### Expected Behavior

Using a global navigate("..") should go back one page, even if the navigate function was pulled from a hook in a different heirachy. 

### Actual Behavior

See example below of the current behaviour.
https://github.com/user-attachments/assets/7fefc7fc-8d9b-4ef7-b2f9-0b2ab61bb2e8

**Comment by OlegDev1** [comment]
When `navigate(-1)` is used instead of `navigate("..")`, everything works as expected in this case. But yes, they both should work

**Comment by OlegDev1** [comment]
@alexfoxy I guess it is. When `navigate` has an argument of type number there is a different behaviour. https://github.com/remix-run/react-router/blob/230181d1b0d9805b141623925bb2df04ae13e0c7/packages/react-router/lib/hooks.tsx#L1103-L1107

**Comment by alexfoxy** [comment]
@OlegDev1 Yeh from the code it looks like it depends on the `fromRouteId: id` to navigate correctly. Not sure if this context can be added in somehow.

**Comment by timdorr** [comment]
This is expected behavior because you are passing a value that depends on the React context out of the render cycle entirely, and therefore essentially disconnecting it from that context. This is likely to cause things like memory leaks and other unexpected behavior. This isn't supported by React, as it [violates the Rules of React](https://react.dev/reference/rules/rules-of-hooks#only-call-hooks-from-react-functions), and therefore isn't supported by React Router.
