### ISSUE TITLE
[Bug]: v7 - unable to import react-router/testing

### ISSUE THREAD

**Issue by ondrejsevcik** [remix-run/react-router#12185]
### What version of React Router are you using?

7.0.0-pre.2

### Steps to Reproduce

1. Install `react-router` package in version `7.0.0-pre.2`. 
2. Try to import `import { createStub } from 'react-router/testing'`
3. It will fail, since there is no `testing` export in the `package.json` defined

### Expected Behavior

According to the [dev testing documentation](https://reactrouter.com/dev/guides/start/testing), it should be possible to import from this package.

### Actual Behavior

The build fails with 

```
error TS2307: Cannot find module 'react-router/testing' or its corresponding type declarations.
import { createStub } from 'react-router/testing'
```

**Comment by brophdawg11** [comment]
I think this is just a docs issue - try `import { createRoutesStub } from "react-router"`?

**Comment by ondrejsevcik** [comment]
Thanks @brophdawg11, this fixes the issue.

**Comment by brophdawg11** [comment]
ah ok yeah those route helpers don't make sense for testing (at least at the moment) - I'll update that in the docs too

```js
  const Stub = createStub([
    { 
      path:"/login",
      Component: LoginForm,
    }
]);
```
