### ISSUE TITLE
[Bug]: loader can't get store value at first time when i reload window

### ISSUE THREAD

**Issue by hang-bro** [remix-run/react-router#12212]
### What version of React Router are you using?

6.27.0

### Steps to Reproduce

1.createBrowserRouter([ {
    path: '/',
    Component: Layout,
    loader: layoutLoader,
    children: layoutRoutes,
  }])

2.layoutLoader

![image](https://github.com/user-attachments/assets/d83082f8-8d53-43f0-8239-16dd2ea4960a)

3.consoled "!role",when i reload window,y?

### Expected Behavior

reload can get store value

### Actual Behavior

can't get store value,when reload,and it redirect to 'login'

**Comment by timdorr** [comment]
This has nothing to do with React Router. You need to initialize your store before rendering the router.
