### ISSUE TITLE
[Bug]: A history supports only one prompt at a time

### ISSUE THREAD

**Issue by diesel167** [remix-run/react-router#12230]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

Put `<Prompt/>` component from react-router-dom to render method. And after that i got warning: Warning: _A history supports only one prompt at a time Error Component Stack from Lifecycle (react-router.js)_. Everything works perfectly but this message in the console annoys me. Actually in the page there is only one Prompt component all the time. No any Prompt components anywhere.

### Expected Behavior

One <Prompt/> on the page - no any problems. 

### Actual Behavior

Warning that there is more than one prompt on the page.

**Comment by timdorr** [comment]
Most likely this is caused by `StrictMode`. If you're able to reproduce this without `StrictMode` in place, please submit a reproduction on CodeSandbox or StackBlitz.

**Comment by diesel167** [comment]
No, i don't use Strict mode. But i've found that the line `this.props.history.block(this.callback);` causes the issue (when it is used with `Prompt` ath the same time). Are they something equal?
