### ISSUE TITLE
[Bug]: Too many v7 warnings

### ISSUE THREAD

**Issue by ebnazmul** [remix-run/react-router#12250]
### What version of React Router are you using?

react-router-dom@6.28.0

### Steps to Reproduce

![Screenshot 2024-11-08 105940](https://github.com/user-attachments/assets/100cd8df-2c84-4167-abf6-093b7f35c339)

I tried 

![Screenshot 2024-11-08 110115](https://github.com/user-attachments/assets/a5bd4b03-4446-4adb-b151-681827c63d14)

### Expected Behavior

No warning

### Actual Behavior

Too much warnings

**Comment by Eghizio** [comment]
@ebnazmul see https://github.com/remix-run/react-router/issues/12245

**Comment by timdorr** [comment]
For the moment, the best course of action is to downgrade to `6.27.0` and lock your version to that release. [The only things added in 6.28.0 are these warnings](https://github.com/remix-run/react-router/compare/react-router%406.27.0...react-router%406.28.0), so you're not missing any features or fixes by downgrading to that version.

**Comment by jbblanchet** [comment]
I know it's not explicit here, but it would be nice if explicitly opting out the flags (i.e. `v7_skipActionErrorRevalidation: false`) would stop the warning. It's my way of saying "I got the message, I created a ticket to follow up on this, please stop warning me."

**Comment by dd-jonas** [comment]
I don't see the reason for adding these warnings. This seems to belong in a changelog, not in the console. None of these feature flags have any impact on my application. Why should I enable them all explicitly, only to remove them again in v7?

**Comment by brookslybrand** [comment]
> I don't see the reason for adding these warnings. This seems to belong in a changelog, not in the console. None of these feature flags have any impact on my application. Why should I enable them all explicitly, only to remove them again in v7?

You should enable them if you plan to upgrade to v7. Each of these flags opts you into behavior that you cannot opt out of in v7. Adopting each flag allows you to test, commit, and deploy 1 by 1. If you're happy with bumping from v6 to v7 without using the flags, then you can just do that. If you don't intend to go to v7 for whatever reason, just pin your version to `6.27.0` like @timdorr suggested.

[step-by-step v6 upgrade guide](https://reactrouter.com/upgrading/v6)

**Comment by jbblanchet** [comment]
@brookslybrand I'm sorry, but that's not a great solution. What if there's a security patch in 6 months? You don't get it because you pinned your version? Or you upgrade it manually and then get the warnings? I think the community has been providing feedback that's helpful and constructive, and dismissing it by telling us to pin our version is not the best part forward.

**Comment by jbblanchet** [comment]
I appreciate it, thanks.

**Comment by brookslybrand** [comment]
Thanks again for the suggestion @jbblanchet, you will be able to opt out of warnings by setting flags to `false` in in the next patch release

**Comment by rakleed** [comment]
@brookslybrand why don't you want to remove warnings in the production build by default? All other libraries that I use do this - React, MobX, Ant Design.

**Comment by brookslybrand** [comment]
> @brookslybrand why don't you want to remove warnings in the production build by default? All other libraries that I use do this - React, MobX, Ant Design.

I have no idea if that was intentional or not, feel free to open up a PR that removes them from production.

However, now that you can turn them off it's probably not as necessary
