### ISSUE TITLE
[Bug]: Unable to get full param with specific symbols such as #, ? from URL params by useParams

### ISSUE THREAD

**Issue by WuBanga** [remix-run/react-router#12265]
### What version of React Router are you using?

6.28.0

### Steps to Reproduce

This is [CodeSandbox](https://codesandbox.io/p/sandbox/2cy4yl?file=%2Fsrc%2FApp.js%3A36%2C40) with examples of reproducing bug:
1) Example with "#" in param
2) Example with "?" in param
3) Example with "&" in param
4) Example of encoded string with "#" 
5) Example of encoded string with " "

### Expected Behavior

Result of `useParams` has full param

### Actual Behavior

Result of `useParams` truncates everything after specific symbol

**Comment by timdorr** [comment]
The segments after those characters are not parts of the path. The `?` specifies the query string and the `#` specifies the fragment. The router extracts params only from the path.

**Comment by WuBanga** [comment]
I found a solution for my problem

If you need to use symbols like `#`, `?` in your param you need to use [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) instead of [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) because it supports more symbols
