### ISSUE TITLE
[Docs] v7:  Cloudflare proxy doesn't work with react-router v7

### ISSUE THREAD

**Issue by vladinator1000** [remix-run/react-router#12302]
### Describe what's incorrect/missing in the documentation

Hi y'all, I'm testing out v7, because I want to port my remix project to it. I can't find [instructions in the docs](https://reactrouter.com/dev/upgrading/remix) or [the Cloudflare proxy](https://github.com/remix-run/remix/blob/39d50b1fe84fd4d7c9696be71e84415017357e29/packages/remix-dev/vite/cloudflare-proxy-plugin.ts#L34) in the new packages, am I missing something here?

Here's my config:
```ts
import { reactRouter } from "@react-router/dev/vite"
// Couldn't find this in any other package, so I imported from @remix-run/dev
import { cloudflareDevProxyVitePlugin } from "@remix-run/dev"
import { defineConfig } from "vite"

export default defineConfig({
	plugins: [
		cloudflareDevProxyVitePlugin(),
		reactRouter({
			ssr: true,
		}),
		tsconfigPaths(),
	],
})
```

When I run the above I get this error
```
✘ [ERROR] No matching export in "node_modules/react-router/dist/index.mjs" for import "UNSAFE_logV6DeprecationWarnings"
...
```

When I try
```ts
import { cloudflareDevProxyVitePlugin } from "@react-router/dev"
```

I get
```
Failed to resolve entry for package "@react-router/dev". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@react-router/dev" package [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1225:27:
      1225 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46637:15)
    at resolvePackageEntry (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46632:5)
    at tryNodeResolve (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:46450:16)
    at resolveByViteResolver (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66585:20)
    at file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66618:28
    at requestCallbacks.on-resolve (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:1225:28)
    at handleRequest (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:647:17)
    at handleIncomingPacket (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:672:7)
    at Socket.readFromStdout (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:519:28)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66606:18)
    at handlePlugins (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:699:5)
    at /home/vlady/code/vis/node_modules/esbuild/lib/main.js:2023:15
    at new Promise (<anonymous>)
    at Object.build (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:2022:25)
    at build (/home/vlady/code/vis/node_modules/esbuild/lib/main.js:1873:51)
    at bundleConfigFile (file:///home/vlady/code/vis/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66561:24)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:1:283:
      1 │ ...eta_url = "file:///home/vlady/code/vis/vite.config.ts";import { cloudflareDevProxyVitePlugin } from "@react-router/dev"
        ╵                                                             
```

Here's my `package.json`:
```json
{
	"name": "vis",
	"private": true,
	"sideEffects": false,
	"type": "module",
	"scripts": {
		"build": "react-router build",
		"dev": "react-router dev",
		"start": "npm run dev",
		"gen": "wrangler types",
		"typecheck": "react-router typegen && tsc",
		"typegen:watch": "react-router typegen --watch",
		"preview": "pnpm build && wrangler pages dev ./build/client",
		"deploy": "pnpm build && wrangler pages deploy ./build/client"
	},
	"dependencies": {
		"@react-router/cloudflare": "^7.0.0-pre.5",
		"@react-router/node": "7.0.0-pre.5",
		"@react-router/serve": "7.0.0-pre.5",
		"@remix-run/dev": "^2.14.0",
		"class-variance-authority": "^0.7.0",
		"clsx": "^2.1.1",
		"isbot": "^5.1.17",
		"lucide-react": "^0.456.0",
		"react": "^18.3.1",
		"react-dom": "^18.3.1",
		"react-router": "7.0.0-pre.5",
		"tailwind-merge": "^2.5.4",
		"tailwindcss-animate": "^1.0.7",
	},
	"devDependencies": {
		"@biomejs/biome": "1.9.4",
		"@cloudflare/workers-types": "^4.20241112.0",
		"@react-router/dev": "^7.0.0-pre.5",
		"@types/react": "^18.3.9",
		"@types/react-dom": "^18.3.0",
		"autoprefixer": "^10.4.20",
		"postcss": "^8.4.47",
		"sharp": "^0.33.5",
		"tailwindcss": "^3.4.13",
		"typescript": "^5.6.2",
		"vite": "^5.4.8",
		"vite-tsconfig-paths": "^5.0.1",
		"wrangler": "^3.87.0",
	},
	"engines": {
		"node": ">=20.0.0"
	}
}
```

**Comment by sergiodxa** [comment]
You need to import the Vite plugin for the Cloudflare proxy from `@react-router/dev/vite/cloudflare`

**Comment by cwagner22** [comment]
Same issue for:
`Internal server error: [vite] Named export 'renderToReadableStream' not found. The requested module 'react-dom/server' is a CommonJS module, which may not support all module.exports as named exports.`

`import { renderToReadableStream } from 'react-dom/server.browser';` indeed worked for some reason.

**Comment by thiagodebastos** [comment]
@vladinator1000 thank you, much appreciated! 🙏

**Comment by thiagodebastos** [comment]
If anyone else gets stuck, you may also need to add `react-router-dom`, particularly if you are getting errors around node-js modules (such as `path`) not being found.

**Comment by ameerkabir** [comment]
Now that react-router v7 is officially released are the above still relevant for migration or is there official guides from the react-router community/team

**Comment by jiangsi** [comment]
cloudflare new vite plug is  @cloudflare/vite-plugin  ,this plugin use [workerd](https://github.com/cloudflare/workerd) runtime as local dev, replace miniflare

worderd support cloudflare workflow ,miniflare don't

I build a demo to  Tried to solve it, not perfect, but it works

https://github.com/jiangsi/vite-plugin-cloudflare-template

**Comment by hyusetiawan** [comment]
@jiangsi what is missing from it? since you said it's not perfect

**Comment by jiangsi** [comment]
> [@jiangsi](https://github.com/jiangsi) what is missing from it? since you said it's not perfect？

1: missing cloudflareDevProxy (use miniflare, not support cf workflow), don't know how to import cf context into remix
2 Two wrangler.toml are required

I really hope that react router supports the new @cloudflare/vite-plugin so that I can use all the cloudflare features such as workflow

**Comment by jiangsi** [comment]
React Router 7.4 +  @cloudflare/vite-plugin@0.1.13 is working very well.
see my update demo
https://github.com/jiangsi/cloudflare-workflow-rr7

**Comment by hyusetiawan** [comment]
Looks legit!!

**Comment by iceniveth** [comment]
Not sure if this helps, I went to Cloudflare Worker & Pages > Create > Workers > Browse all templates > React Router Framework Starter.

It suggested to run this command: 

```bash
npm create cloudflare@latest -- --template=cloudflare/templates/react-router-starter-template
```

**Comment by kziemski** [comment]
@jiangsi has anyone gotten prerender to work with rr7 and  @ cloudflare/vite-plugin? 
I managed to get cloudflare and vite working using the old plugins but now i'm hitting on issues that make me want to use both and the new features inside miniflare.  

Production wise i'm still good by making cloudflare:* external and using wrangler native types but vite dev is so annoying
