### ISSUE TITLE
[Bug]: 'RouterProvider' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by kelvinwop** [remix-run/react-router#12328]
### What version of React Router are you using?

6.28.0

### Steps to Reproduce

package.json versions
```
"dependencies": {
    "@esbuild-plugins/node-globals-polyfill": "^0.2.3",
    "jotai": "^2.10.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.28.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.13.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "eslint": "^9.13.0",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.14",
    "globals": "^15.11.0",
    "typescript": "~5.6.2",
    "typescript-eslint": "^8.11.0",
    "vite": "^5.4.10"
  }
```

main.tsx
![image](https://github.com/user-attachments/assets/ca790f72-e2e1-41cc-803c-80dbd457c65e)

error:
![image](https://github.com/user-attachments/assets/9d077c1c-3e87-4df5-9ac9-6639d415f287)
```
'RouterProvider' cannot be used as a JSX component.
  Its type '({ fallbackElement, router, future, }: RouterProviderProps) => ReactElement<any, string | JSXElementConstructor<any>>' is not a valid JSX element type.
    Type '({ fallbackElement, router, future, }: RouterProviderProps) => ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
        Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
```

### Expected Behavior

no type error

### Actual Behavior

an error

**Comment by timdorr** [comment]
I just installed these same versions in [our example project](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/data-router?file=README.md) and it worked fine. I think you have something installed incorrectly and should delete your `node_modules` folder and reinstall. This doesn't appear to be an issue with the library.

**Comment by Morantron** [comment]
i had this error as a result of a mismatch between `react` and `@types/react` in my `package.json` 🫠
