### ISSUE TITLE
[Bug]: Type of loaderData wrong when returning redirect in the loader (action as well)

### ISSUE THREAD

**Issue by mrNuTz** [remix-run/react-router#12335]
### What version of React Router are you using?

7

### Steps to Reproduce

```tsx
export const loader = () => {
  if (Math.random() < 0.5) {
    return redirect('/')
  }
  return {some: 'data'}
}

export default function Home() {
  const data = userLoaderData<typeof loader>()
  return <>{data.some}</> // ERROR: some not in type {headers: ...}
}
```

### Expected Behavior

`some` should be defined on the loaderData

### Actual Behavior

there is a typescript error

**Comment by Moonflower-labs** [comment]
Hi, I  had a similar issue. If you throw the redirect instead of returning it, the typescript error should go away.

**Comment by goamaan** [comment]
Facing the same problem - just migrated from remix to rr7 and the inferred return types for actions/loaders are messed up. I'm returning a `redirect` / `createUserSession` from my actions and this used to work but shows a type error in RR7

**Comment by brookslybrand** [comment]
Since `redirect` returns a response, you'll want to throw it to get the proper types, otherwise the inference thinks you're returning an object

**Comment by goamaan** [comment]
Confused as to why this did work in Remix though?

**Comment by brookslybrand** [comment]
> Confused as to why this did work in Remix though?

Good point, not sure if there was something we should be carrying over from Remix

c.c. @pcattori

**Comment by goamaan** [comment]
Also, if I need to redirect the user after logging in, I do something like this in my action
```tsx
return createUserSession({
            request,
            userId: user.id,
            email,
            roles,
            remember: true,
            redirectTo: redirectTo ?? "/app",
            isAdmin: user.isAdmin,
        })
```
 where `createUserSession` is this 
```tsx
async function createUserSession({
    request,
    userId,
    remember,
    redirectTo,
    roles,
    email,
    isAdmin,
}: {
    ...
}) {
    const { session } = await getSession(request)
    ...
    session.set(IS_ADMIN, isAdmin)
    return redirect(redirectTo, {
        headers: {
            "Set-Cookie": await commitSession(session, {
                maxAge: remember
                    ? 60 * 60 * 24 * 2 // 2 days
                    : undefined,
            }),
        },
    })
}
```
in this case throwing doesn't seem work

**Comment by Varkoff** [comment]
> Also, if I need to redirect the user after logging in, I do something like this in my action
> 
> ```tsx
> return createUserSession({
>             request,
>             userId: user.id,
>             email,
>             roles,
>             remember: true,
>             redirectTo: redirectTo ?? "/app",
>             isAdmin: user.isAdmin,
>         })
> ```
> 
> where `createUserSession` is this
> 
> ```tsx
> async function createUserSession({
>     request,
>     userId,
>     remember,
>     redirectTo,
>     roles,
>     email,
>     isAdmin,
> }: {
>     ...
> }) {
>     const { session } = await getSession(request)
>     ...
>     session.set(IS_ADMIN, isAdmin)
>     return redirect(redirectTo, {
>         headers: {
>             "Set-Cookie": await commitSession(session, {
>                 maxAge: remember
>                     ? 60 * 60 * 24 * 2 // 2 days
>                     : undefined,
>             }),
>         },
>     })
> }
> ```
> 
> ~in this case throwing doesn't seem work~ Nvm it does work, I just have to throw from createUserSession instead of from the action

I had the same issue. In Remix 2.x, returning a redirect somehow worked and didn't mess with the loader / action types. 

Having to " throw " a successful authentication request seems a bit weird to me. And it introduces a strange behavior in my app, I need to fully reload before showing the authenticated user info.

**Comment by sdifru** [comment]
Is it the recommended practice to throw `redirect`? I read the docs and it shows that it returns `redirect`, not throwing it.

**Comment by GrahamQuan** [comment]
same here, i end up with `undefined` | `dataType` like
```ts
import { redirect } from 'react-router';
import type { Route } from './+types/blog';

type BlogType = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

export async function loader({ params }: Route.LoaderArgs) {
  const data = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${params.id}`
  );
  if (!data) {
    redirect('/');
    return; // return undefined as default
  }

  return (await data.json()) as BlogType;
}

export default function Blog({
  params,
  loaderData,
}: Route.LoaderArgs & Route.ComponentProps) {
  // check if loaderData is undefined
  if (!loaderData) {
    return null;
  }

  return (
    <div>
      <h1>blog id: {params?.id}</h1>
      <p>{loaderData.title}</p>
      <p>{loaderData.body}</p>
    </div>
  );
}
```

**Comment by MattyBalaam** [comment]
If you throw a redirect instead of returning in an action or loader when using `createRoutesStub` this causes the tests to show an error boundaty.
