### ISSUE TITLE
[Docs]: React Router v6 Documentation Removed – Request to Restore

### ISSUE THREAD

**Issue by AlexMelw** [remix-run/react-router#12345]
### Describe what's incorrect/missing in the documentation

Hello React Router team,

I noticed that the documentation for React Router v6 has been removed from the official site and replaced with the documentation for v7 (which is now in TypeScript). While I understand the transition to v7 is designed to be non-breaking, I am currently working on a project that does not use TypeScript, and the v6 documentation was vital for development.

Would it be possible to restore the v6 documentation to the website or provide an easy-to-find link to an archived version?

![image](https://github.com/user-attachments/assets/82766008-5bd2-4342-a4d1-65b6f6788042)
![image](https://github.com/user-attachments/assets/430dfb8e-137e-49e9-aadd-99f88f9063f9)

**Comment by vinsonw** [comment]
You could visit https://reactrouter.com/en/6.28.0 for the moment. It seems the doc swap caused a bug.

**Comment by worst-developer** [comment]
Please fix it ASAP cause it is very important
