### ISSUE TITLE
[Bug]: RouterProvider missing fallbackElement in v7?

### ISSUE THREAD

**Issue by leepowelldev** [remix-run/react-router#12350]
### What version of React Router are you using?

7.0.0

### Steps to Reproduce

v6 Had a prop on the RouterProvider called `fallbackElement` which was consumed when I was patching routes via `patchRoutesOnNavigation`. This prop seems to have been removed, and now while `patchRoutesOnNavigation` is running to patch the routes (it async loads a module federated remote) the wildcard route of "*" not found is being displayed instead.

### Expected Behavior

A suspense boundary or similar should be shown while `patchRoutesOnNavigation` is running.

### Actual Behavior

Wildcard route for not found is displayed instead until the route it patched and the route component is loaded.

**Comment by brookslybrand** [comment]
It was deprecated and replaced with `HydrateFallback`/`hydrateFallbackElement`

[docs](https://reactrouter.com/upgrading/v6#v7_partialhydration)

**Comment by moeabdol** [comment]
@brookslybrand Thank you. This explains everything.
However, now I have to provide `hydrateFallbackElement` to all my lazy loaded paths :(
The original v6 approach dealt with all of them.
