### ISSUE TITLE
[Docs]: Module augmentation example in upgrade docs wrong

### ISSUE THREAD

**Issue by lensbart** [remix-run/react-router#12356]
### Describe what's incorrect/missing in the documentation

The module augmentation example in https://reactrouter.com/upgrading/remix#9-update-types-for-apploadcontext shows the following code snippet for `app/env.d.ts`:

```ts
declare module "react-router" {
  // Your AppLoadContext used in v2
  interface AppLoadContext {
    whatever: string;
  }
}
```

It should show this instead:
```ts
declare module "react-router" {
  // Your AppLoadContext used in v2
  interface AppLoadContext {
    whatever: string;
  }
}

export {}
```

to ensure it’s a module.

**Comment by pcattori** [comment]
Fixed by #12394
