### ISSUE TITLE
[Bug]:  ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by remarkablemark** [remix-run/react-router#12363]
### What version of React Router are you using?

7.0.1

### Steps to Reproduce

https://github.com/remarkablemark/mui-template/pull/1082

```sh
git clone https://github.com/remarkablemark/mui-template.git
cd mui-template
git checkout dependabot/npm_and_yarn/react-router-dom-7.0.1
npm install
npm test
```

I tried replacing `react-router-dom` with `react-router` but got the same error

### Expected Behavior

Jest tests pass with latest `react-router` version

### Actual Behavior

Jest tests failing with error:

```
      ReferenceError: TextEncoder is not defined
  
        2 | import type { ReactElement, ReactNode } from 'react';
        3 | import { Provider } from 'react-redux';
      > 4 | import { createMemoryRouter, RouterProvider } from 'react-router-dom';
          | ^
        5 | import { resetActions, store } from 'src/store';
        6 |
        7 | export { store };
  
        at Object.<anonymous> (node_modules/react-router/dist/production/index.js:8368:15)
        at Object.<anonymous> (node_modules/react-router-dom/dist/index.js:39:38)
        at Object.<anonymous> (test/helpers.tsx:4:1)
        at Object.<anonymous> (test/setupTests.ts:7:1)
```

**Comment by timdorr** [comment]
What versions of Node, jest, and jsdom are you using?

**Comment by remarkablemark** [comment]
I'm using:

| Dependency | Version |
| --- | --- |
| Node.js | 20.18.0 |
| Jest | 29.7.0 |
| jsdom | 20.0.3 |

Let me try upgrading Node.js from 20 to 22

**Comment by timdorr** [comment]
It looks like [jsdom doesn't implement TextEncoder yet](https://github.com/jsdom/jsdom/issues/2524), but there is [a PR](https://github.com/jsdom/jsdom/pull/3791) out there for it. 

In the meantime, you can use [the same workarounds we do in our test setup](https://github.com/remix-run/react-router/blob/94d4351290267f1a7ed93f8639a588e7a901d24f/packages/react-router/__tests__/setup.ts#L4).

**Comment by dani-shopery** [comment]
> I'm using:
> 
> Dependency	Version
> Node.js	20.18.0
> Jest	29.7.0
> jsdom	20.0.3
> Let me try upgrading Node.js from 20 to 22
> 
> Update 1: upgrading Node.js didn't fix it, but I noticed that `jsdom` is currently v25 so let me try to update that in my project
> 
> Update 2: I tried upgrading `jest-environment-jsdom` from `29.7.0` to `30.0.0-alpha.6` but it still failed locally for me. I can confirm the `jsdom` version did go up:
> 
> $ npm ls jsdom
> └─┬ jest-environment-jsdom@30.0.0-alpha.6
>   ├─┬ @jest/environment-jsdom-abstract@30.0.0-alpha.6
>   │ └── jsdom@25.0.1
>   └── jsdom@22.1.0
> Update 3: I set package.json `overrides` to ensure `jsdom` is 25 but tests still failed locally
> 
> Update 4: I fixed the error in my [PR](https://github.com/remarkablemark/mui-template/pull/1168/files) and wrote a [blog post](https://remarkablemark.org/blog/2025/02/02/fix-jest-errors-in-react-router-7-upgrade/) about it.

Thank you.
I has been able to allow the project I am working on to work thanks to your blog post. Importing TextEncoder from 'utils' was allowing the tests to work, but the build to fail ([CRA](https://react.dev/learn/creating-a-react-app)). But locally adding the text-encoding package and importing from there make it all work, test and build.
I hope this message helps someone.

**Comment by yalshaeyr** [comment]
> I'm using:
> 
> Dependency	Version
> Node.js	20.18.0
> Jest	29.7.0
> jsdom	20.0.3
> Let me try upgrading Node.js from 20 to 22
> 
> Update 1: upgrading Node.js didn't fix it, but I noticed that `jsdom` is currently v25 so let me try to update that in my project
> 
> Update 2: I tried upgrading `jest-environment-jsdom` from `29.7.0` to `30.0.0-alpha.6` but it still failed locally for me. I can confirm the `jsdom` version did go up:
> 
> $ npm ls jsdom
> └─┬ jest-environment-jsdom@30.0.0-alpha.6
>   ├─┬ @jest/environment-jsdom-abstract@30.0.0-alpha.6
>   │ └── jsdom@25.0.1
>   └── jsdom@22.1.0
> Update 3: I set package.json `overrides` to ensure `jsdom` is 25 but tests still failed locally
> 
> Update 4: I fixed the error in my [PR](https://github.com/remarkablemark/mui-template/pull/1168/files) and wrote a [blog post](https://remarkablemark.org/blog/2025/02/02/fix-jest-errors-in-react-router-7-upgrade/) about it.

Thanks! I wasn't using `react-router-dom`, but `react-router ^v7.4.0`. Your blog allowed my tests to run again!
