### ISSUE TITLE
[Bug]: useNavigate is failing when running in react testing library on react-router v7

### ISSUE THREAD

**Issue by kelsin** [remix-run/react-router#12368]
### What version of React Router are you using?

7.0.1

### Steps to Reproduce

https://stackblitz.com/edit/vitejs-vite-9tur3x

I created this tiny example to show this error. This app just has two routes and a button to swap between them on each page using useNavigate. The app itself works with a memory router or a browser router.

The tests however don't run with either router. You can run the tests in the above environment with `npm run test`.

Here is a working version (all the same) on react-router v6.28.0: https://stackblitz.com/edit/vitejs-vite-sygeg8

### Expected Behavior

The test is able to render the main page and read the text on it.

### Actual Behavior

We get this error:
```Error: Uncaught [Error: useNavigate() may be used only in the context of a <Router> component.]```

The app doesn't render so the test doesn't pass.

### Info
I saw this tonight while trying to update my react app from 6.28.0 to 7.0.1. This only occurs in tests in react testing library. My larger app behaves identically. This bug only happens in testing and regardless of if I use `createMemoryRouter` or `createBrowserRouter`.

**Comment by jessemyers-lettuce** [comment]
We see a similar error. It's not apparent using the dev server, only after a production build and deploy.

**Comment by timdorr** [comment]
Simple fix. Change your RouterProvider import to this:

```js
import { RouterProvider } from 'react-router';
```

**Comment by kelsin** [comment]
> Simple fix. Change your RouterProvider import to this:
> 
> ```js
> import { RouterProvider } from 'react-router';
> ```

Sounds good. This ties into my other points here: https://github.com/remix-run/react-router/discussions/12370

Should update https://reactrouter.com/upgrading/v6#upgrade-to-v7 as well since that's where I was told to use the current import.

**Comment by timdorr** [comment]
Thanks, I added that now.

**Comment by rothsandro** [comment]
The tests run with jsdom so it's not a "not-DOM context" as mentioned in the docs. Importing from `react-router` breaks other use cases, e.g. when navigating with `flushSync: true`:

> You provided the `flushSync` option to a router update, but you are not using the `<RouterProvider>` from `react-router/dom` so `ReactDOM.flushSync()` is unavailable.

**Comment by teukuamru** [comment]
> Thanks, I added that now.

I'm not an expert in react-router but in that page, it is written that I need to install react-router-dom but the very next step I need to uninstall it? Is there any explanation to this?

![Screenshot 2024-11-26 at 18 12 22](https://github.com/user-attachments/assets/85d8000b-f0e2-4049-9181-72ab9dc999c0)

**Comment by kelsin** [comment]
> I'm not an expert in react-router but in that page, it is written that I need to install react-router-dom but the very next step I need to uninstall it? Is there any explanation to this?

I'm not associated with the project, but I believe the intent is:

1. You can upgrade to v7 - _**App Still Works**_
2. You can replace imports from `react-router-dom` to `react-router` - _**App Still Works**_
3. You can uninstall and replace with the base package - _**App Still Works**_
