### ISSUE TITLE
[Bug]: useEffect + useLocation not work in version 7... was in 6

### ISSUE THREAD

**Issue by passariello** [remix-run/react-router#12361]
### What version of React Router are you using?

version 7

### Steps to Reproduce
```js
  const location = useLocation()

  useEffect(
    () => {
      console.log(location)
    }, [location]
 )
```
### Expected Behavior

useEffect will be fired from location change. Work in 6 ... not in 7
It's a disaster!

### Actual Behavior

no page change if location change. Make the route completely un-useful

**Comment by timdorr** [comment]
This should work just fine. We need to see more context. 

Can you provide a reproduction on Stack Blitz or a similar tool?
