### ISSUE TITLE
[Bug]: clicking link on docs website breaks CSS

### ISSUE THREAD

**Issue by marcospgp** [remix-run/react-router#12365]
### What version of React Router are you using?

docs

### Steps to Reproduce

Click "nesting section" link here: https://reactrouter.com/how-to/file-route-conventions#nested-routes

<img width="698" alt="image" src="https://github.com/user-attachments/assets/2d425932-ddde-431c-9695-e9cea68926f2">

### Expected Behavior

CSS keeps working

### Actual Behavior

CSS breaks:

<img width="729" alt="image" src="https://github.com/user-attachments/assets/abb45b80-1239-4b49-b393-c8fb008f54f9">

**Comment by ngbrown** [comment]
Nothing odd happens for me when clicking on "nesting section". I did notice that lots of the links from that page (https://reactrouter.com/how-to/file-route-conventions) to other pages are broken.

**Comment by timdorr** [comment]
This should be fixed now.

**Comment by zsherman** [comment]
@timdorr what was the issue here, was there a PR that fixed it?

**Comment by timdorr** [comment]
Yes, over on the docs site repo.
