### ISSUE TITLE
[Bug]: ESLint - Unable to resolve path to module 'react-router/dom'.

### ISSUE THREAD

**Issue by Arkellys** [remix-run/react-router#12371]
### What version of React Router are you using?

7.0.1

### Steps to Reproduce

I've followed [upgrading from v6](https://reactrouter.com/upgrading/v6) documentation:

```shell
yarn remove react-router-dom
yarn add react-router@latest
```

And:

```diff
- import { RouterProvider } from "react-router-dom";
+ import { RouterProvider } from "react-router/dom";
```

This is my `jsconfig.json` config:

```js
"compilerOptions": {
  "target": "es2022",
  "checkJs": false,
  "baseUrl": "./",
  "resolveJsonModule": true,
  "moduleResolution": "bundler",
  "jsx": "react-jsx"
}
```

And I'm using [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import/tree/main) `v2.31.0` along with ESLint `v9.15.0`. The relevant rule configuration is:

```js
{
  rules: {
    "import/no-unresolved": ["error", { commonjs: true }]
  }
}
```

### Expected Behavior

I expect ESLint no to flag  `"react-router/dom"` import as unresolved.

### Actual Behavior

I get a ESLint [`import/unresolved`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md) error on the import `"react-router/dom"`. The imports from `"react-router"` are not flagged. This is just a ESLint error, the import works fine and my IDE resolves it correctly. Restarting the IDE and ESLint Server didn't solve the issue.

Honestly, I can't tell if the bad configuration comes from my project, `react-router` or `eslint-plugin-import`?

**Comment by timdorr** [comment]
My best guess is you have a cache somewhere that's out of date. Try deleting your node_modules folder, as it's often stored there. 

Unfortunately, this isn't an issue with the library.

**Comment by teague-mfa** [comment]
I have the same problem after running `rm -rf node_modules` and `npm cache clean --force`.

**Comment by Arkellys** [comment]
@timdorr  Deleting `node_modules` and all cache didn't solve the issue. Can't it be a problem with the way the library exports `dom`?

**Comment by lorondo** [comment]
Need to change the imports "react-router-dom" to "react-router." 

-import { Routes } from "react-router-dom"
+import { Routes } from "react-router"

[Source](https://www.npmjs.com/package/react-router-dom)

**Comment by Arkellys** [comment]
> Need to change the imports "react-router-dom" to "react-router."
> 
> -import { Routes } from "react-router-dom" +import { Routes } from "react-router"
> 
> [Source](https://www.npmjs.com/package/react-router-dom)

As stated in the migration docs:

> `RouterProvider` and `HydratedRouter` come from a deep import because they depend on `"react-dom"`:
>```diff
>-import { RouterProvider } from "react-router-dom";
>+import { RouterProvider } from "react-router/dom";
>```

**Comment by bflemi3** [comment]
@Arkellys did you ever get this resolved? I'm having the same issue after upgrading from v6 to v7.

**Comment by Arkellys** [comment]
> @Arkellys did you ever get this resolved? I'm having the same issue after upgrading from v6 to v7.

No, I excluded it in the rule...

```js
"import/no-unresolved": ["error", {
  ignore: ["router/dom"]
}],
```

**Comment by bflemi3** [comment]
> > @Arkellys did you ever get this resolved? I'm having the same issue after upgrading from v6 to v7.
> 
> No, I excluded it in the rule...
> 
> ```js
> "import/no-unresolved": ["error", {
>   ignore: ["router/dom"]
> }],
> ```

Good enough for me! Thanks 👍

**Comment by Arkellys** [comment]
For the record, the problem is from `eslint-plugin-import`, see [this issue](https://github.com/import-js/eslint-plugin-import/issues/1810).
