### ISSUE TITLE
[Docs]: Wrong Config API link for react-router.config.ts

### ISSUE THREAD

**Issue by nikolailehbrink** [remix-run/react-router#12374]
### Describe what's incorrect/missing in the documentation

In https://reactrouter.com/explanation/special-files#react-routerconfigts the link to the config API is redirecting to a 404.

**Comment by timdorr** [comment]
Knowing the API isn't helpful if you don't understand the concepts behind it. Just producing the right objects (or using the right helpers) doesn't help with someone using that file.
