### ISSUE TITLE
[Docs]: React Router v6.28.0 - Broken Links on Home Page

### ISSUE THREAD

**Issue by AlexMelw** [remix-run/react-router#12383]
### Describe what's incorrect/missing in the documentation

![image](https://github.com/user-attachments/assets/0b2e6216-a709-492b-87f9-a3f4e1a86251)

#### Issue Description:
On the React Router v6.28.0 documentation [Home Page](https://reactrouter.com/6.28.0/home), the following links under the "Getting Started" section are broken and lead to a 404 error:

1. **Ready for Data?**
   - Broken URL: [https://reactrouter.com/6.28.0/dev/getting-started/data](https://reactrouter.com/6.28.0/dev/getting-started/data)

2. **New to React Router?**
   - Broken URL: [https://reactrouter.com/6.28.0/dev/getting-started/tutorial](https://reactrouter.com/6.28.0/dev/getting-started/tutorial)

3. **Faliliar with React Router?**
   - Broken URL: [https://reactrouter.com/6.28.0/dev/getting-started/overview](https://reactrouter.com/6.28.0/dev/getting-started/overview)

4. **Frequently Asked Questions**
   - Broken URL: [https://reactrouter.com/6.28.0/dev/getting-started/faq](https://reactrouter.com/6.28.0/dev/getting-started/faq)

#### Steps to Reproduce:
1. Navigate to the React Router documentation for version 6.28.0: [https://reactrouter.com/6.28.0/home](https://reactrouter.com/6.28.0/home).
2. Click on any of the "Getting Started" links (1-4).
3. Observe that the browser is redirected to a 404 page.

#### Expected Behavior:
These links should navigate to the appropriate documentation pages

**Comment by brookslybrand** [comment]
This was a mistake of directing to this page, it shouldn't be accessible (it is right now from the dropdown)

[Fixed here](https://github.com/remix-run/react-router-website/commit/58317655f277ed19d3b07b0b4c1ce92e1d0b8766)
