### ISSUE TITLE
[Bug]: v7 Not Working with Meteor

### ISSUE THREAD

**Issue by merlinstardust** [remix-run/react-router#12381]
### What version of React Router are you using?

7.0.1

### Steps to Reproduce

1. Install Meteor App
2. Install React Router v7
3. Add `import { createBrowserRouter, RouterProvider } from 'react-router/dom';`
4. App breaks

### Expected Behavior

The Meteor app should work without issue

### Actual Behavior

I'm not sure if this is a Meteor issue or a React Router issue but React Router v6 worked fine but when I upgraded to React Router v7, it broke my app.

I suspect that this is because [v7 is now asking for](https://reactrouter.com/upgrading/v6) a deep import from `react-router/dom` but I'm not sure.

I get these errors in the browser console

```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module 
Uncaught TypeError: Cannot read properties of undefined (reading 'meteorInstall')
Uncaught TypeError: Cannot read properties of undefined (reading 'Mongo')
Uncaught ReferenceError: meteorInstall is not defined
```

And these errors in the server
```
Unable to resolve some modules:
  "react-router/dom" in react-router-dom/dist/index.mjs
```

And this TypeScript error
```
Cannot find module 'react-router/dom' or its corresponding type declarations.
```

I've also posted this on the forums in case the issue is more Meteor related than React Router related: https://forums.meteor.com/t/react-router-v7-not-working-with-meteor/62618

**Comment by timdorr** [comment]
You might try importing `RouterProvider` from `react-router` directly, but this is definitely not something with the library. It seems like you need to check your package.json's module config or your build configuration.

**Comment by paulincai** [comment]
@timdorr this is related to js modules vs commonjs. I checked the change log but could not find mentions of abandoning commonjs in favor of modules.
In fact I renamed all mjs filed in node_modules/react-router/dist/package.json to js and all works ok.
I suspect this is a "mistake" in package.json which renders the package unusable with commonjs.
In the image, a conf that works for me (with Meteor 3.1 on Node 22).
![Screenshot 2024-11-25 at 9 05 20 PM](https://github.com/user-attachments/assets/23d0402c-e6c8-40ba-8cc3-eaec68fbd363)

**Comment by juanpmd** [comment]
I am having the same issue (importing `RouterProvider` from `react-router` directly.

**Comment by pckilgore** [comment]
> definitely not

The workout solved this, but I am not so sure about "definitely" not the library.  I've got a ton of deep imports that work just fine from other libraries but receive the error from OP attempting to follow the v7 migration instructions.
