### ISSUE TITLE
Using with UI library cause errors

### ISSUE THREAD

**Issue by toanil315** [remix-run/react-router#12409]
### I'm using React Router as a...

framework

### Reproduction

https://github.com/toanil315/survey-creator/tree/feat/try-react-router-v7

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.28 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.70
    Safari: 17.6
  npmPackages:
    @react-router/dev: * => 7.0.1 
    @react-router/fs-routes: ^7.0.1 => 7.0.1 
    @react-router/node: * => 7.0.1 
    react-router: * => 7.0.1 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

yarn

### Expected Behavior

I can start my pet project using the @fluentui/react-components UI library. This project worked with Vite v4 before, but after migrating to React Router v7, it is broken

### Actual Behavior

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/eae9a318-8f92-4fc7-b03b-5be019f523d5">

**Comment by 3fuyang** [comment]
Try including them in the [`ssr.noExternal`](https://vite.dev/config/ssr-options.html#ssr-noexternal) option?

**Comment by toanil315** [comment]
@3fuyang thanks, I have added all Fluentui packages into ```ssr.noExternal``` and it worked

```ts
 ssr: {
    noExternal: [
      /@fluentui|@swc|@floating-ui/ ,
      '@griffel/react',
    ],
  },
 ```
