### ISSUE TITLE
v7 - Scripts|Links hydratation error in ErrorBoundary

### ISSUE THREAD

**Issue by 4FunAndProfit** [remix-run/react-router#12400]
### I'm using React Router as a...

framework

### Reproduction

Just add  `<Scripts />` in ErrorBoundary in root.tsx then run dev, example:

```
export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {
  return (
    <html>
      <head>
        <Meta />
      </head>
      <body>
        something
        <Scripts />

      </body>
    </html>
  );
}
```

You will have this hydratation error: 
```
Warning: Expected server HTML to contain a matching <link> in <body>.
  at link
    at Scripts (http://localhost:5173/node_modules/.vite/deps/chunk-F5ZHWI7L.js?v=d43574d5:7879:66)
    at body
    at html
    at ErrorBoundary (http://localhost:5173/app/root.tsx?t=1732631760397:176:3)
```

Which causes `Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`

My use case is to use mantine in error ErrorBoundary which requires scripts (https://mantine.dev/guides/remix/)

### System Info

```shell
Browsers:
  Chrome: 131.0.6778.86
```

### Used Package Manager

pnpm

### Expected Behavior

Should not have hydratation error

### Actual Behavior

hydratation error provoking mantine not working

Seem to have same behavior with <Links> in <head>

**Comment by timdorr** [comment]
The ErrorBoundary doesn't need the full HTML content, as it will pull from the root Layout component. Adding `<Scripts/>` is redundant.

**Comment by 4FunAndProfit** [comment]
@timdorr, Just tried with layout! thanks it resolves a part, but not all.

Now I have the same issue than https://github.com/remix-run/remix/issues/9144

**Comment by 4FunAndProfit** [comment]
@timdorr in fact I Just tested

The issue is the same if you go in layout or out layout 

Please reopen as it is an issue I think

**Comment by msalahz** [comment]
This is happening to me, too
![Uploading image.png…]()

**Comment by myodan** [comment]
Running with the default `create-react-router` template causes the same issue, so please reopen the issue again

**Comment by blandfried** [comment]
Getting this issue now too after upgrading from remix v2 to react router v7. Initial load of the page is fine but if I refresh I get the error and page breaks.

**Comment by ourines** [comment]
try use react@19
```bash
npm install react@19 react-dom@19
```
I solved this problem using React 19.
```ts
  "dependencies": {
    "@react-router/fs-routes": "^7.1.1",
    "@react-router/serve": "^7.1.1",
    "isbot": "^5.1.17",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router": "^7.1.1",
    "react-router-hono-server": "^2.3.0"
  },
  ```

but.. new error:
<img width="1268" alt="SCR-20241229-svbd" src="https://github.com/user-attachments/assets/89df0539-c21c-4e24-a5cd-d8ca0df99841" />

**Comment by jkelin** [comment]
> [@ourines](https://github.com/ourines) that's still the same hydration error, React just moved the message from the console to their website.
> 
> What solved this issue for me was to disable `v3_lazyRouteDiscovery` in the future flags. Sad to miss out on the fog of war benefits, but I'd much rather have my application render correctly.

Hi @ogabrielp , I'm hitting the same issue. How did you disable `v3_lazyRouteDiscovery` in React Router 7? I'm not seeing it in react-router.config.ts and https://remix.run/docs/en/main/guides/lazy-route-discovery claims that this is now a default behavior in RR7

**Comment by jaxonL** [comment]
thank you @ogabrielp for the pointers.

ran into this issue as well; was able to solve by updating to latest 7.6.0 of react-router (+ other dev packages) and disabling `routeDiscovery` by setting it to `initial`.

```ts
// in react-router.config.ts
import type { Config } from '@react-router/dev/config';

export default {
  // ... other options
  routeDiscovery: { mode: 'initial' },
} satisfies Config;

```

hope this helps others who run into the same issue.
