### ISSUE TITLE
Bun Support

### ISSUE THREAD

**Issue by devhindo** [remix-run/react-router#12406]
### I'm using React Router as a...

framework

### Reproduction

```
bun create vite my-app
chose react router v7
bun run dev
```

### System Info

```shell
my used package is bun not in npm
```

### Used Package Manager

npm

### Expected Behavior

I'm using Bun instead on NPM and everything is working okay but this warning shows up while it shouldn't as I'm not using Node and everything is working fine. Am I missing something?

### Actual Behavior

![image](https://github.com/user-attachments/assets/24c492bb-70b7-43c8-9622-43689a079c3e)

**Comment by drewbitt** [comment]
You are on an old version of bun; bun now reports 22.6.0. It maintains a fake version of node in `process.versions.node` for compatibility reasons, and it is lager than node 20.
