### ISSUE TITLE
Resource route handler is not returning response

### ISSUE THREAD

**Issue by tkapitein** [remix-run/react-router#12413]
### I'm using React Router as a...

framework

### Reproduction

Check out this repository: https://github.com/tkapitein/rr-resource-route-bug (Note: StackBlitz is not available due to the Node version).

1. Run `npm run dev`.
2. Open your developer tools.
3. Choose one of the buttons.
4. Observe the following error:

```
The following error is a bug in React Router; please open an issue! https://github.com/remix-run/react-router/issues/new/choose
Error: Expected a Response to be returned from resource route handler
    at invariant3 (/Users/{user}/projects/personal/blog/node_modules/react-router/dist/production/index.js:8684:11)
    at handleResourceRequest (/Users/{user}/projects/personal/blog/node_modules/react-router/dist/production/index.js:9420:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (/Users/{user}/projects/personal/blog/node_modules/react-router/dist/production/index.js:9206:18)
    at nodeHandler (/Users/{user}/projects/personal/blog/node_modules/@react-router/dev/dist/vite.js:1967:30)
    at /Users/{user}/projects/personal/blog/node_modules/@react-router/dev/dist/vite.js:1973:17
```

Note: I attempted to replicate the theme handling approach used by the package remix-themes in my project, as it currently lacks support for React Router v7.

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 132.84 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.1 - ~/.volta/tools/image/node/20.18.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/20.18.1/bin/npm
    pnpm: 7.27.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
  npmPackages:
    @react-router/dev: ^7.0.1 => 7.0.1 
    @react-router/node: ^7.0.1 => 7.0.1 
    @react-router/serve: ^7.0.1 => 7.0.1 
    react-router: ^7.0.1 => 7.0.1 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

I expected the session cookie to be set and the response to be returned.

### Actual Behavior

It seems that the response is not being returned from the action.

**Comment by timdorr** [comment]
The return of an action needs to be a Response of some type. You should wrap the return with `Response.json`.

**Comment by tkapitein** [comment]
Thank you for the quick response. I had understood that the `json` helper previously exported from Remix was replaced by the `data` helper. Using `Response.json` solved my issue. Thank you 🙏
