### ISSUE TITLE
safari reappears in some cases, entering the first page is normal, but skipping any page renders the '/' of the home page.

### ISSUE THREAD

**Issue by ekko2665** [remix-run/react-router#12463]
### I'm using React Router as a...

library

### Reproduction

1. It is only repeated in the safari production environment and other links enter the project
2. Open the non-trace mode of the safari browser to access the web page
3. In some cases, the path will change, but the page will always render only the first page

### System Info

```shell
react-router-dom:
        specifier: ^6.13.0
        version: 6.17.0(react-dom@18.2.0(react@18.2.0))(react@18.2.0)
```

### Used Package Manager

pnpm

### Expected Behavior

Normal route jump

### Actual Behavior

1. It is only repeated in the safari production environment and other links enter the project
2. Open the non-trace mode of the safari browser to access the web page
3. In some cases, the path will change, but the page will always render only the first page

**Comment by timdorr** [comment]
We need some sort of reproduction of this issue to look at. Can you set up something on Stack Blitz?

**Comment by ekko2665** [comment]
my 2 iphone (version:1.8)，if setting : safari - Advanced - Advanced Tracking and Fingeprinting Protection - PrivateBrowsing(if first one :Off， everthing is ok)。 then the error will always happen , when click a link jump to other link jump to my page, and my page react router  only can change path can not change to rigth rendering(only render first '/' page)

**Comment by timdorr** [comment]
This doesn't sound like an issue with the library. It sounds like overly restrictive settings on your device. We can't work around that.

**Comment by ekko2665** [comment]
react-router-dom can listen path change，because other page can jump to '/' page ,
but can only render '/' page , and path also still can change
