### ISSUE TITLE
[React Router V7] Server timeout after 5 seconds

### ISSUE THREAD

**Issue by laimonassutkus** [remix-run/react-router#12467]
### I'm using React Router as a...

framework

### Reproduction

Created a freshly new repository. Created minimal example:
https://github.com/laimonassutkus/ReactRouterV7-HttpStreaming

Just run "npm run dev", open the browser and timeout later happens.

How do I increase the timeout beyond 5 seconds ?

### Code at a glance

Loader:

```javascript
export async function loader({}: Route.LoaderArgs) {
    const msgPromise = new Promise((res) =>
        setTimeout(() => res("Hello World!"), 6_000)
    );

    return {msg: msgPromise};
}
```

Page:

```javascript
export default function MyComponent({loaderData}: Route.ComponentProps) {
    let {msg} = loaderData;

    return (
        <div>
            <React.Suspense fallback={<div>Loading...</div>}>
                <Await resolve={msg}>
                    {(value) => <h3>{value}</h3>}
                </Await>
            </React.Suspense>
        </div>
    );
}
```

### System Info

```shell
Chrome, Mac, dependencies:

    "@react-router/node": "^7.0.2",
    "@react-router/serve": "^7.0.2",
    "isbot": "^5.1.17",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router": "^7.0.2"
```

### Used Package Manager

npm

### Expected Behavior

No timeout happens or at least there is a way to increase it.

### Actual Behavior

Always timeout if promise resolves in more that 5 seconds.

**Comment by laimonassutkus** [comment]
By the way, revealing server file with "npx react-router reveal entry.server" and setting "ABORT_DELAY" to, example, 60 seconds did not help either.

**Comment by vdo9** [comment]
I am receiving a similar issue. All attempts to increase the timeout has been ignored and this message is getting received:

```{
  errorMessage: 'Task timed out after 30.00 seconds',
  errorType: 'TimeoutError',
  stackTrace: [
    'new TimeoutError (/opt/homebrew/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/utils.js:119:28)',
    'Context.<anonymous> (/opt/homebrew/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lib/context.js:113:19)',
    'listOnTimeout (node:internal/timers:614:17)',
    'processTimers (node:internal/timers:549:7)'
  ]
}

**Comment by timdorr** [comment]
You should `export const streamTimeout` from your entry.server.tsx file. While not in the main docs, it is in the API reference: https://api.reactrouter.com/v7/interfaces/react_router.ServerEntryModule.html#streamTimeout

Here's the CHANGELOG entry:

https://github.com/remix-run/react-router/blob/c19a6c545b2dfd7b668915b62929275f80777b06/packages/react-router-dev/CHANGELOG.md#L178

**Comment by laimonassutkus** [comment]
@timdorr can confirm that it worked. This variable should be part of official documentation because it is very likely for any streamed response to take more than 5 seconds.

**Comment by brophdawg11** [comment]
FWIW this was in the Single Fetch docs in Remix (https://remix.run/docs/en/main/guides/single-fetch#streaming-timeout) and referenced in the original issue this stemmed from (https://github.com/remix-run/remix/issues/7991#issuecomment-2105028965).  I think we need to get some of those long form docs moved over to RR still though so we can use this issue as the docs enhancement 👍

**Comment by laimonassutkus** [comment]
@brophdawg11 thank you for the refs! Helpful.

**Comment by qinsong77** [comment]
But what if I don't  reveal the default entry server file, how can I solve it?

**Comment by brophdawg11** [comment]
@qinsong77 https://github.com/remix-run/react-router/pull/12478 updates the default version of that file to use `streamTimeout` so that should be resolved for you with the next release.

**Comment by qinsong77** [comment]
> @qinsong77 #12478 updates the default version of that file to use `streamTimeout` so that should be resolved for you with the next release.

Thanks for the note, seems I must  run `react-router reveal`

**Comment by DanielBaulig** [comment]
Is there any way to override this on a per route basis? I would like to use a resource route to feed into Server Sent Events and the requests time out all the time. I don't just want to increase the timeout for the entire server, but just this one route.

**Comment by seidtgeist** [comment]
@DanielBaulig @brophdawg11 Just my 2 cents:

It's late and I didn't read the docs properly (this also happens in the morning, who am I kidding):

I had wrongly assumed that `streamTimeout` can "simply" be exported on a per-route basis. This is not the case.

While I'm not nearly deep enough in remix or react-router to know if that would make sense or work: That was my intuition.
