### ISSUE TITLE
[Docs]: Wildcard path segments not matching when upgrading from v6 to v7

### ISSUE THREAD

**Issue by mrados7** [remix-run/react-router#12460]
### Describe what's incorrect/missing in the documentation

As previous [issue](https://github.com/remix-run/react-router/issues/12267) that was closed explained that there is issue with the docs on how to upgrade from v6 to v7, I'm opening issue again to hopefully get more clarification on how to upgrade. 

Docs state:
```jsx
<Routes>
  <Route path="/" element={<Home />} />
-  <Route path="dashboard/*" element={<Dashboard />} />
+  <Route path="dashboard">
+    <Route path="*" element={<Dashboard />} />
+  </Route>
</Routes>

// or
createBrowserRouter([
  { path: "/", element: <Home /> },
  {
-    path: "dashboard/*",
-    element: <Dashboard />,
+    path: "dashboard",
+    children: [{ path: "*", element: <Dashboard /> }],
  },
]);
```
This simply does not work for me and reading from previous issues it does not work for a lot of guys. 
[Codesandbox](https://codesandbox.io/p/sandbox/3m5vcx) (thanks to @imjordanxd)

**Comment by jrakotoharisoa** [comment]
Hi, I work on multiple apps built with react-router.

The migration guide works well for apps using RouterProvider with createBrowserRouter but not with BrowserRouter and Route components.

**Comment by timdorr** [comment]
You need an index route. `*` is matching when there's _something_, not when there's _nothing_.

This works in your Codesandbox:

```ts
<Route path="dashboard">
  <Route index element={<Dashboard />} />
  <Route path="*" element={<Dashboard />} />
</Route>
```

**Comment by jrakotoharisoa** [comment]
Thanks @timdorr for your answer. 
This solution fix the display of `index` route. 
But the <Link />  on `index` page seems to be broken with the change of prepending `../` on link.

**Comment by lhartvik** [comment]
> Thanks @timdorr for your answer. This solution fix the display of `index` route. But the `<Link />` on `index` page seems to be broken with the change of prepending `../` on link.
> 
> Here [Codesandbox](https://codesandbox.io/p/sandbox/react-router-forked-ydfwt5)

prepending all links in the Dashboard with /dashboard makes the codesandbox run as expected(but that might not be applicable for everyone) but I am still getting this warning: 
`You rendered descendant <Routes> (or called `useRoutes()`) at "/dashboard/" (under <Route path="">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

Please change the parent <Route path=""> to <Route path="/*">. `
might mislead some users to think that adding the index route is not going to work.

**Comment by jrakotoharisoa** [comment]
> prepending all links in the Dashboard with /dashboard makes the codesandbox run as expected(but that might not be applicable for everyone)
> 

I think this is not suitable solution for migration as the goal is to keep relative path in `<Link />`

@timdorr do you have any another alternative ? Or should we migrate component route to object route ?

**Comment by mauro-ni** [comment]
@incrop many thans, it did the trick for me too.

I thing that migration guide at https://reactrouter.com/upgrading/v6#v7_relativesplatpath could be improved by adding this info.
