### ISSUE TITLE
`npm run build` fails if your html includes unicode character ’ (U+2019)

### ISSUE THREAD

**Issue by ReidCole** [remix-run/react-router#12477]
### I'm using React Router as a...

framework

### Reproduction

Create a default React Router v7 project with `npx create-react-router@latest`.

Go to `app/welcome/welcome.tsx` and paste the ’ character anywhere in the returned jsx.

Run `npm run build`

I get this error: `[vite:css-post] css content for "" was not found`

This may be an issue with vite or postcss but I wasn't able to reproduce the issue with a plain vite + react-ts project with tailwind and postcss.

### System Info

```shell
System:
    OS: Linux 6.8 Linux Mint 22 (Wilma)
    CPU: (12) x64 AMD Ryzen 5 7640U w/ Radeon 760M Graphics
    Memory: 3.20 GB / 14.93 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 23.2.0 - /run/user/1000/fnm_multishells/67093_1733431668543/bin/node
    Yarn: 1.22.22 - /run/user/1000/fnm_multishells/67093_1733431668543/bin/yarn
    npm: 10.9.1 - /run/user/1000/fnm_multishells/67093_1733431668543/bin/npm
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    react-router: ^7.0.2 => 7.0.2
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

I expected the build to succeed.

### Actual Behavior

It failed to build. 

(Note this issue is not blocking me from building my site. I just encountered it and thought it would be useful to submit a bug report)

**Comment by timdorr** [comment]
Do you have any other modifications to your vite config or any non-standard plugins installed? 

As a temporary fix, you can use `&#x2019;` instead of that character directly.

**Comment by ReidCole** [comment]
Nope, it's just a default react router project.

**Comment by ReidCole** [comment]
I saw this thread and was able to resolve the issue by upgrading from node 23.2.0 to 23.3.0.
https://community.render.com/t/issue-with-deploy/26570/10

Builds just fine now.
