### ISSUE TITLE
SPA client side debugging broken

### ISSUE THREAD

**Issue by TobyEalden** [remix-run/react-router#12470]
### I'm using React Router as a...

framework

### Reproduction

Unable to set breakpoints and debug in chrome dev tools (also Safari).

To reproduce:

```
npx create-react-router@latest my-react-router-app
```

Edit `react.router.config.ts` and set `ssr:false`.

Edit `root.tsx` to add some code to the `App` component for breakpoint demonstration:

```
export default function App() {
  const message = "hello world";
  console.log(message);

  return <Outlet />;
}
```

Run:

```
npm run dev
```

Navigate to [http://localhost:5173](http://localhost:5173) and open chrome dev tools and attempt to set a breakpoint on the `const message = "hello world";` line (or the one below).

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 92.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.109
    Safari: 18.1.1
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    react-router: ^7.0.2 => 7.0.2
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

Expect to be able to use browser debugger to set breakpoints and examine variables etc.

### Actual Behavior

Unable to set breakpoints or inspect variables.

**Comment by timdorr** [comment]
Something else must be going on with your system, as we don't have a way to break debugging AFAIK. If you can create a reproduction on Stack Blitz that works on someone else's machine, we can take a look.

**Comment by TobyEalden** [comment]
The reproduction given above takes literally 30 seconds to install whereas the [StackBlitz link](https://remix.new/) provided in the new issue template uses remix rather than react-router v7, and StackBlitz doesn't seem to support node 20 which is required by v7.

Anyway, [here is a reproduction](https://stackblitz.com/edit/github-4tcdcv-aecnec?file=app%2Froot.tsx%3AL32) - try setting a breakpoint on the `console.log(message)` line and/or inspect the `message` variable.

I'm guessing it's a problem with source maps.
