### ISSUE TITLE
useLocation search empty if search string is after hash

### ISSUE THREAD

**Issue by merlinstardust** [remix-run/react-router#12479]
### I'm using React Router as a...

library

### Reproduction

No reproduction but very simple to see the issue in the actual behavior below.

Admittedly, it seems this may not actually be a react-router issue but with the browser implementation. Though I think it would be nice if react-router could add this option since if this a browser implementation issue, it might not be something they want to fix for unknown reasons.

Looking at `window.location` for both kinds of paths, it seems that the browser location object also makes this error

![Screenshot 2024-12-05 205121](https://github.com/user-attachments/assets/4fec64ed-593c-4e2d-9418-c0d3039ae590)

### System Info

```shell
Tested in Chrome Version 131.0.6778.86 (Official Build) (64-bit)
```

### Used Package Manager

npm

### Expected Behavior

When at a URL with a path that has a hash path followed by search params, I would expect `search` from `useLocation()` to have the search params and `hash` to not have search params. 

Example URL path:  `/somePath#afterHash?searchParm=searchValue`

Example code
```
const { hash, search } = useLocation();
console.log(hash); // should log '#afterHash'
console.log(search); // should log '?searchParam=searchValue'
```

### Actual Behavior

Example URL path:  `/somePath#afterHash?searchParm=searchValue`

Example code
```
const { hash, search } = useLocation();
console.log(hash); // should log '#afterHash?searchParm=searchValue'
console.log(search); // logs empty string ''
```

**Comment by timdorr** [comment]
This is a URI specification issue. [The query comes before the fragment (aka hash).](https://www.rfc-editor.org/rfc/rfc3986#section-3) It doesn't parse in the other order because that's how the spec is defined. Anything in the fragment, even query-looking things, will stay in the fragment component.
