### ISSUE TITLE
[v7] ErrorBoundary  loads js even if not in error page

### ISSUE THREAD

**Issue by 4FunAndProfit** [remix-run/react-router#12486]
### I'm using React Router as a...

framework

### Reproduction

Hello, 

First, sorry for the two last issues, I was really looking for the cause of my performance problems and it was hard to find.

I finally found it.

If you had some components like Mantine components Container, Title, etc in your errorboundary, it will be loaded even if you are not in error state, 

That causes performance issue in particular on mobile 

### System Info

```shell
npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2 
    @react-router/node: ^7.0.2 => 7.0.2 
    @react-router/serve: ^7.0.2 => 7.0.2 
    react-router: ^7.0.2 => 7.0.2 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

pnpm

### Expected Behavior

Ressources of errorboundary should be loaded in error state 

### Actual Behavior

Ressources of errorboundary are always loaded

**Comment by timdorr** [comment]
I'm not sure I fully understand without a reproduction to look at. But if your module references parts of the bundle, it doesn't matter what actual functions you use, they will loaded. This isn't a bug with the library, as far as I can tell.
