### ISSUE TITLE
v7: When switching routes, components using useNavigate() will be re rendered

### ISSUE THREAD

**Issue by yibird** [remix-run/react-router#12487]
### I'm using React Router as a...

library

### Reproduction

When switching routes, components using useNavigate() will be re rendered

### System Info

```shell
When switching routes, components using useNavigate() will be re rendered
```

### Used Package Manager

npm

### Expected Behavior

When switching routes, components using useNavigate() will be re rendered

### Actual Behavior

When switching routes, components using useNavigate() will be re rendered

**Comment by timdorr** [comment]
Please don't erase the bug template.
