### ISSUE TITLE
Config ssr=false does not work properly with react-19

### ISSUE THREAD

**Issue by chinfeng** [remix-run/react-router#12498]
### I'm using React Router as a...

framework

### Reproduction

```sh
npx create-react-router my-react-router-app --template remix-run/react-router-templates/javascript
cd my-react-router-app
echo 'export default { ssr: false }' > react-router.config.js
npm i react@19.0.0 react-dom@19.0.0
npm run build
```

### System Info

```shell
react: 19.0.0
react-router: 7.0.2

react-router.config.js: { ssr: false }
```

### Used Package Manager

npm

### Expected Behavior

Build just output "build/client" as spa bundle.

### Actual Behavior

Build output "build/client" and "build/server".

**Comment by timdorr** [comment]
This library isn't yet compatible with React 19.

**Comment by MattyBalaam** [comment]
@timdorr I thought this package would be compatbile from day 1, I guess this has slipped? 

> v7 will support both React 18 and React 19

https://remix.run/blog/incremental-path-to-react-19 `

**Comment by chinfeng** [comment]
> @timdorr I thought this package would be compatbile from day 1, I guess this has slipped?
> 
> > v7 will support both React 18 and React 19
> 
> https://remix.run/blog/incremental-path-to-react-19 `

I think this issue should be reopened.
