### ISSUE TITLE
[Docs]: Missing documentation for components and hooks for library mode router like on v6 docs

### ISSUE THREAD

**Issue by bulicmatko** [remix-run/react-router#12497]
### Describe what's incorrect/missing in the documentation

There's no documentation (and usage examples) for React Router v7 components and hooks on the new docs page.

React Router v6 docs had the whole sidebar full of examples:
- Routers
- Router Components
- Route
- Components
- Hooks
- Fetch utilities
- ...

https://reactrouter.com/6.28.0

New docs focus more on describing the difference between framework and library mode. How-Tos are focused on framework mode and there's no examples for library mode components and hooks.

**Comment by timdorr** [comment]
That is in the API reference, linked at the top of the page: https://api.reactrouter.com/v7/

**Comment by bulicmatko** [comment]
Hi @timdorr,

Thanks so much for the quick response—I really appreciate it!

I noticed the API reference at the top of the page, which is also accessible through the editor's autocomplete feature. However, I feel examples serve a different purpose. They demonstrate how something can be implemented and provide ready-to-use code snippets that developers can easily copy and integrate into their projects.

This was the approach in the old documentation, and I’ve attached screenshots of the same hook from before to better illustrate my point. Hopefully, this helps clarify! 😊

API Reference
<img width="1611" alt="Screenshot 2024-12-08 at 21 13 00" src="https://github.com/user-attachments/assets/56937b91-b149-4865-8ea3-e59acef237bc">

Usage example
<img width="1611" alt="Screenshot 2024-12-08 at 21 13 27" src="https://github.com/user-attachments/assets/8be0b878-ee59-4688-9025-3d2348505ada">

This is just for one hook. There's much more value in old docs that's remove in the new ones.

Hopefully this makes sense. Thanks. :)

**Comment by lhapaipai** [comment]
I completely agree with @bulicmatko, the quality of the reference sections of react router v6 and remix v2 has been degraded with the auto-generated documentation proposed with v7 (maintenance is indeed easier). The documentation work is a job in its own and it takes time...
I wonder however if the proposed solution is temporary or definitive?
