### ISSUE TITLE
[v7] [SPA mode] Hydration error on error page

### ISSUE THREAD

**Issue by sxurik** [remix-run/react-router#12525]
### I'm using React Router as a...

framework

### Reproduction

1. git clone https://github.com/remix-run/react-router-templates repo;
2. cd to `default` directory;
3. change `ssr: true,` to `ssr: false,` on `default/react-router.config.ts:6`;
4. add preview script `"preview": "cross-env NODE_ENV=production vite preview",`;
5. run `build` script;
6. run `preview` script;
7. navigate to http://localhost:4173/this-page-does-not-exist;
8. open console;

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 8.81 GB / 31.59 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @react-router/dev: * => 7.0.0
    @react-router/node: * => 7.0.0
    @react-router/serve: * => 7.0.0
    react-router: * => 7.0.0
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

pnpm

### Expected Behavior

No errors in console.

### Actual Behavior

![image](https://github.com/user-attachments/assets/539d7811-eae2-4262-b18f-604e8fa0caca)

**Comment by kazu-2020** [comment]
hi, @sxurik 

In SPA mode, `react-router build` creates the artifacts under `build/client`.
Therefore, the preview script with `cross-env NODE_ENV=production vite preview --outDir build/client` should work! 👍🏻
