### ISSUE TITLE
[v7] Fails to build on Cloudflare

### ISSUE THREAD

**Issue by yankustefan** [remix-run/react-router#12529]
### I'm using React Router as a...

framework

### Reproduction

1. Commit github repo
2. Trigger Build on Cloudflare

### System Info

```shell
Cloudflare Pages
node: >=22.12.0
Build command: npm run build
Build output directory: /build/client
Build system version: 2 (latest)
Root directory:



  "scripts": {
    "dev": "react-router dev",
    "build": "react-router build",
    "deploy": "wrangler pages deploy ./build/client",
    "lint": "eslint --ignore-path .gitignore --cache --cache-location ./node_modules/.cache/eslint .",
    "start": "react-router-serve build/server/index.js",
    "typecheck": "react-router typegen && tsc",
    "typegen": "wrangler types"
  },
  "dependencies": {
    "@isaacs/ttlcache": "^1.4.1",
    "@react-router/cloudflare": "^7.0.2",
    "@supabase/supabase-js": "^2.47.3",
    "classnames": "^2.5.1",
    "isbot": "^5.1.17",
    "lodash": "^4.17.21",
    "micromark": "^4.0.1",
    "micromark-extension-directive": "^3.0.2",
    "miniflare": "^3.20240404.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router": "^7.0.2"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20241205.0",
    "@react-router/dev": "^7.0.2",
    "@react-router/fs-routes": "^7.0.2",
    "@remix-run/eslint-config": "^2.15.1",
    "@tailwindcss/typography": "^0.5.15",
    "@types/lodash": "^4.17.13",
    "@types/marked": "^6.0.0",
    "@types/react": "^18.3.16",
    "@types/react-dom": "^18.3.5",
    "@types/validator": "^13.12.2",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "autoprefixer": "^10.4.20",
    "classnames": "^2.5.1",
    "eslint": "^8.57.1",
    "eslint-import-resolver-typescript": "^3.7.0",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^4.6.2",
    "node-fetch": "^3.3.2",
    "postcss": "^8.4.49",
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "schema-dts": "^1.1.2",
    "tailwindcss": "^3.4.16",
    "typescript": "^5.7.2",
    "vite": "^5.4.11",
    "vite-tsconfig-paths": "^5.1.4",
    "wrangler": "^3.95.0"
  },
  "engines": {
    "node": ">=22.12.0"
  }
```

### Used Package Manager

npm

### Expected Behavior

Sucessful deployment  on Cloudflare pages.

### Actual Behavior

I have upgraded Remix to react-router v7.
It works fine locally.

Now I am trying to deploy react-router v7 on Cloudflare pages. But I get this error:
[ERROR] Could not resolve "@react-router/cloudflare-pages"

I am not sure, but should't that be "@react-router/cloudflare"?

```
17:59:20.827 | build/server/index.js                      762.36 kB
-- | --
17:59:20.828 | ✓ built in 1.51s
17:59:20.885 | Finished
17:59:20.885 | Found Functions directory at /functions. Uploading.
17:59:20.892 | ⛅️ wrangler 3.92.0
17:59:20.892 | -------------------
17:59:21.997 | ✘ [ERROR] Build failed with 1 error:
17:59:21.997 |  
17:59:21.998 | ✘ [ERROR] Could not resolve "@react-router/cloudflare-pages"
17:59:21.998 |  
17:59:21.998 | [[path]].ts:1:43:
17:59:21.998 | 1 │ ...createPagesFunctionHandler } from "@react-router/cloudflare-pages";
17:59:21.998 | ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:59:21.998 |  
17:59:21.998 | You can mark the path "@react-router/cloudflare-pages" as external to exclude it from the bundle, which will remove this error.
``` 
I am also using:
``` 
import { reactRouter } from "@react-router/dev/vite";
import { cloudflareDevProxy } from "@react-router/dev/vite/cloudflare";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  server: {
    port: 8080,
  },
  plugins: [cloudflareDevProxy(), reactRouter(), tsconfigPaths()],
});
```

**Comment by yankustefan** [comment]
It works when I change the import `"@react-router/cloudflare-pages"` in `functions/[[path]].ts` to `"@react-router/cloudflare"` 

**functions/[[path]].ts**
```
import { createPagesFunctionHandler } from "@react-router/cloudflare";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
```

Probably not a bug, but I missed it in the upgrade documentation.

**Comment by timdorr** [comment]
This is discussed right at the top of the upgrade docs: https://reactrouter.com/upgrading/remix#2-update-dependencies

**Comment by whiskerside** [comment]
@yankustefan I did the same thing, but after deploying to pages, a 500 error was displayed. Running `wrangler pages dev ./build/client` locally also gave errors. Did you do anything else besides the above modifications when deploying to pages? Thanks

**Comment by yankustefan** [comment]
Hi @whiskerside
No, that one change did it for me.

**Comment by whiskerside** [comment]
> Hi @whiskerside No, that one change did it for me.

I've created a project by template https://github.com/remix-run/react-router-templates/tree/main/cloudflare, then add the file `functions/[[path]].ts` with the following content:
```
import { createPagesFunctionHandler } from "@react-router/cloudflare";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
```
then, change the wrangler.toml like this:

```
name = "reactrouter-demo"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
```
, it's deployed, but when I access it raise 500 error and no more error information.

**Comment by Johnmcoro** [comment]
Also facing similar issue when upgrading from Remix to RR7. Cloudflare deplyoment suceeeds, but receive 500 for each url. In local wranger, same result with error below.


      [ERROR] TypeError: (0 , import_server.renderToPipeableStream) is not a function
      at null.<anonymous> (file:///Users/johncoronel/quetzal/web/build/server/index.js:33:29)
      at new Promise (<anonymous>)
      at handleRequest (file:///Users/johncoronel/quetzal/web/build/server/index.js:29:10)
      at handleDocumentRequest

**Comment by IbrahimOwner2020** [comment]
The `@react-router/cloudflare-pages` is a typo in the codemon command

**Comment by cthlo** [comment]
> Also facing similar issue when upgrading from Remix to RR7. Cloudflare deplyoment suceeeds, but receive 500 for each url. In local wranger, same result with error below.
> 
> ```
>   [ERROR] TypeError: (0 , import_server.renderToPipeableStream) is not a function
>   at null.<anonymous> (file:///Users/johncoronel/quetzal/web/build/server/index.js:33:29)
>   at new Promise (<anonymous>)
>   at handleRequest (file:///Users/johncoronel/quetzal/web/build/server/index.js:29:10)
>   at handleDocumentRequest
> ```

You need to overwrite the default `entry.server.ts` as shown in the new Cloudflare RR7 template:
https://github.com/cloudflare/templates/blob/staging/react-router-starter-template/app/entry.server.tsx
