### ISSUE TITLE
package.json development exports only

### ISSUE THREAD

**Issue by tomchochola** [remix-run/react-router#12532]
### I'm using React Router as a...

library

### Reproduction

Goto https://www.npmjs.com/package/react-router?activeTab=code and see the package.json or the dist folder. In the package.json only the dist/development is in use. The dist/production is not in use. Webpack bundle analyzer reports the development files used in the production bundle.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 25.30 GB / 31.22 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.18.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.2 - /usr/bin/npm
  npmPackages:
    react-router: ^7.0 => 7.0.2
```

### Used Package Manager

npm

### Expected Behavior

Expect then the NODE_ENV=production that the dist/production files should be in use.

### Actual Behavior

The dist/development files are used for both development and production builds.

**Comment by timdorr** [comment]
This is due to #12437, which is intended to be temporary.

**Comment by ilijaNL** [comment]
Any status on this since the dev bundle includes some nasty console.warns (becasue of ENABLE_DEV_WARNINGS)

**Comment by tlvince** [comment]
@timdorr could this be reopened or is there another issue tracking #12437?
