### ISSUE TITLE
unstable_composeUploadHandlers and siblings not migrated to React Router

### ISSUE THREAD

**Issue by ZeldOcarina** [remix-run/react-router#12550]
### I'm using React Router as a...

framework

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-d1xeymsx?file=react-router-test%2Fapp%2Froutes%2Fhome.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2 
    @react-router/node: ^7.0.2 => 7.0.2 
    @react-router/serve: ^7.0.2 => 7.0.2 
    react-router: ^7.0.2 => 7.0.2 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

I am trying to migrate from Remix to React Router and I would need the uploads to keep working

### Actual Behavior

These unstable_upload functions seem to have been left off the migration.

**Comment by dralletje** [comment]
I couldn't find any docs about which is a bit confusing, but it seems the closest equivalent is https://github.com/mjackson/remix-the-web/tree/main/packages/form-data-parser .
Api is actually pretty nice now.

**Comment by ZeldOcarina** [comment]
Thanks! This is an additional package from @mjackson but this uploader was in Remix as part of the core so it should be migrated otherwise apps on Remix v2 that were using it cannot be migrated. This is effectively preventing me from upgrading :(

**Comment by dralletje** [comment]
They do refer to it in the documentation!
https://reactrouter.com/how-to/file-uploads

You could install the additional package to upgrade.

**Comment by ZeldOcarina** [comment]
Oh ok so this is probably now the suggested way of doing file uploads. Maybe this could be quoted in the Remix-RR migration guide by @brookslybrand

**Comment by brookslybrand** [comment]
> Oh ok so this is probably now the suggested way of doing file uploads. Maybe this could be quoted in the Remix-RR migration guide by @brookslybrand

That's correct, good point though that we should call this out. I'm going to add it to the Remix future flags guide, since it already discusses APIs we deprecated/intended to remove in React Router

**Comment by brookslybrand** [comment]
Done!

[PR](https://github.com/remix-run/remix/pull/10338)

**Comment by ZeldOcarina** [comment]
Thank you!
