### ISSUE TITLE
React Router running code in the server even with `ssr: false`

### ISSUE THREAD

**Issue by Alan-Gomes** [remix-run/react-router#12553]
### I'm using React Router as a...

framework

### Reproduction

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-oqt6kncm?file=app%2Froutes%2Fhome.tsx

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 168.64 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.9.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 131.0.2903.99
    Safari: 18.1.1
  npmPackages:
    react-router: ^7.0.2 => 7.0.2 
    vite: ^5.4.2 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

I am migrating an existing react router v6 application to work with the new framework model. Since I already have an SPA, my code is heavily dependent on Browser APIs.

If I opt out of SSR, the framework should not run the code in the server as it may be incompatible (and not necessary).

### Actual Behavior

Even with SSR disabled, the code still runs on the server. In the StackBlitz example an error is thrown because `localStorage` is not available in the server, but on the browser.

**Comment by chinfeng** [comment]
Same as #12498

**Comment by Alan-Gomes** [comment]
> Same as #12498

It looks similar, but i’m actually using react 18

**Comment by chinfeng** [comment]
Try to remove localStorage? Or wrap with `typeof document !== 'undefined'` guard?

**Comment by timdorr** [comment]
The server is still used in dev as a framework to be able to serve up your application and do things like HMR. In production, you'll just take the build output and serve that up directly (routing all requests to `index.html`)

You should be loading data in a `clientLoader`, since you won't be using the server in production: https://reactrouter.com/start/framework/data-loading#client-data-loading

**Comment by aleclarson** [comment]
Hey @timdorr, is this a temporary compromise, or is there a technical limitation in Vite that is preventing a purely client-side rendering DX? It'd be great to have dev/prod work the same (or as close to that as Vite allows).

**Comment by diego-toro** [comment]
I'm having the same issue with Localstorage. We use it for various things, and we even save some session info. So @timdorr what will be the proper way to handle client browser data with SPA + framework? I tried the client-data-loading but got the same issue with Localstorage.
