### ISSUE TITLE
[BUG]Accessing parant route loader data in childs, the loader type falls into unknown in typescript

### ISSUE THREAD

**Issue by mjjabarullah** [remix-run/react-router#12555]
### I'm using React Router as a...

framework

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-2tg5ibkf?file=my-react-router-app%2FREADME.md

cd my-react-router-app
npm i 
npm run dev

### System Info

```shell
Win 11
node 20.17.0
react-router 7.0.2
```

### Used Package Manager

npm

### Expected Behavior

should be same as parent loader type

### Actual Behavior

type is unknown

**Comment by timdorr** [comment]
I don't think TS can narrow types that way because `matches.find()` may return undefined. 

It may be easier to just overload the type with `as HomeInfo["loaderData"];` after adding `import type { Info as HomeInfo } from './+types/home';` to your imports.
