### ISSUE TITLE
shouldRevalidate does not stop the loader from revalidating

### ISSUE THREAD

**Issue by aland-x** [remix-run/react-router#12551]
### I'm using React Router as a...

framework

### Reproduction

Getting started template modified to add another route and a link for testing purposes with ssr disabled.

https://github.com/aland-x/should-revalidate-test

https://stackblitz.com/github/aland-x/should-revalidate-test

### System Info

```shell
Not relevant
```

### Used Package Manager

npm

### Expected Behavior

When navigating to `/test` from the link the loader should not revalidate because the shouldRevalidate export is false.

### Actual Behavior

When navigating to `/test` the loader revalidates.

**Comment by timdorr** [comment]
`shouldRevalidate` doesn't prevent the initial `loader` call. It's used when the loader might be invalidated after an `action` call. Hence it takes `actionResult` as one of its params.
