### ISSUE TITLE
renderToPipeableStream export missing in production build when starting production server with Bun

### ISSUE THREAD

**Issue by meetdave3** [remix-run/react-router#12568]
### I'm using React Router as a...

framework

### Reproduction

When using React Router with Bun, the production server fails to start due to a missing export. While the development server and production build work fine, running the production server results in an error regarding the renderToPipeableStream export not being found.

## Reproduction

1. Clone the repository:
   ```bash
   git clone https://github.com/meetdave3/remix-hono-on-bun.git
   cd remix-hono-on-bun
   git checkout bug/react-router
   ```

2. Install dependencies:
   ```bash
   bun install
   ```

3. Set the .env:

  ```dotenv
  NODE_ENV=production
  ```

4. Build the project:
   ```bash
   bun run build
   ```

5. Try to start the production server:
   ```bash
   bun run start
   ```
You will encounter the following error:
```
Export named 'renderToPipeableStream' not found in module '/node_modules/react-dom/server.bun.js'
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 113.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    bun: 1.1.38 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.140
    Edge: 115.0.1901.188
    Safari: 17.4.1
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2 
    @react-router/fs-routes: ^7.0.2 => 7.0.2 
    @react-router/node: ^7.0.2 => 7.0.2 
    @react-router/serve: ^7.0.2 => 7.0.2 
    react-router: ^7.0.2 => 7.0.2 
    vite: ^6.0.2 => 6.0.2
```

### Used Package Manager

npm

### Expected Behavior

- The production server should start successfully after building the project
- The renderToPipeableStream export should be properly resolved from react-dom/server

### Actual Behavior

```
Export named 'renderToPipeableStream' not found in module '/node_modules/react-dom/server.bun.js'
```

**Comment by timdorr** [comment]
This appears to be a React and Bun issue, not anything specific to React Router. 

I did find some fixes here: https://github.com/oven-sh/bun/issues/9949 And this also appears to be fixed in React 19, which should be supported soon.

**Comment by sergiodxa** [comment]
You need to customize the entry.server to use renderToReadableStream

If you don't have that file use `npx react-router reveal` to get them.

**Comment by TheRealFlyingCoder** [comment]
@simonsmith just as another option I've found if you resolve react-dom/server to server.node it works fine 🤷

vite.config.ts

```
	resolve: {
		alias: {
			'react-dom/server': 'react-dom/server.node',
		},
	},
```

@sergiodxa might have thoughts on whether this is a suitable workaround or not 👀

**Comment by luisrudge** [comment]
@TheRealFlyingCoder thanks for the workaround! I'm also facing this issue with react-router+bun

**Comment by TheRealFlyingCoder** [comment]
I'll be honest though @luisrudge - Even with the workaround i'm still having a lot of issues randomly so something is still up 😄😄

The above workaround bypasses the main problem but then I still hit random errors like

```
 5 | 
 6 | var l, s;
 7 | if (process.env.NODE_ENV === 'production') {
 8 |   l = require('./cjs/react-dom-server-legacy.node.production.js');
 9 |   s = require('./cjs/react-dom-server.node.production.js');
10 |   l = require('./cjs/react-dom-server-legacy.node.development.js');
                  ^
ReferenceError: Can't find variable: require
```

If I try going the renderToReadableStream method that @sergiodxa  suggests I hit

```
SyntaxError: [vite] Named export 'renderToReadableStream' not found. The requested module 'react-dom/server' is a CommonJS module, which may not support all module.exports as named exports.
```

Then I delete it all including the alias workaround and it goes back to working fine in dev but breaks in prod 🤷🤷

The workaround i'm currently sitting on is to only alias on prod because `bunx --bun vite` seems to handle things without the alias but it fails on `bun ./build/server/index.js` without it

```
	resolve:
		process.env.NODE_ENV === 'development'
			? {}
			: {
					alias: {
						'react-dom/server': 'react-dom/server.node',
					},
			  },
```

**Comment by ShlokDesai33** [comment]
Implementing the fix at https://github.com/oven-sh/bun/issues/9949 breaks the dev server. @timdorr any other fixes that might work?

**Comment by olliepotter** [comment]
@TheRealFlyingCoder solution is a good workaround and works for me. Just not ideal that we have to add config to vite to get it to work.

**Comment by superjose** [comment]
Dang, the resolve workaround worked!

**Comment by niyrme** [comment]
> 
> ```
> 	resolve:
> 		process.env.NODE_ENV === 'development'
> 			? {}
> 			: {
> 					alias: {
> 						'react-dom/server': 'react-dom/server.node',
> 					},
> 			  },
> ```

great workaround! though a somewhat cleaner solution would be checking the `config.command` property when passing a function to `defineConfig`, which works as well (at least for me)

```ts
export default defineConfig((config) => {
	resolve: {
		config.command === "build"
			? {
					alias: {
						"react-dom/server": "react-dom/server.node",
					},
				}
			: undefined,
	}
})
```

**Comment by RigoOnRails** [comment]
Here's a neater format instead of abusing ternaries:

```ts
resolve: {
    alias: (() => {
      if (env.command === 'build') {
        return {
          // TODO: Remove this when `renderToPipeableStream` is available in the `server.bun` build.
          'react-dom/server': 'react-dom/server.node',
        };
      }
    })(),
  },
```

**Comment by sudomaxime** [comment]
Resolve workaround worked for me as well !
