### ISSUE TITLE
Do we need to put actions in route files?

### ISSUE THREAD

**Issue by mschipperheyn** [remix-run/react-router#12567]
### I'm using React Router as a...

framework

### Reproduction

We have a Remix project. All of our actions are stored with the Form components. Our routes import and then export the actions from those form files. 

```
[route file]
import { Form, action } from '~modules/account/forms/Edit'

export { action }

[...]
```

Form components as such contain the client side form, the server side action and the validation. The route imports them but doesn't contain the code in-line. It keeps everything neatly separated.

We did a test upgrade from Remix to React Router and it now seems to be required to store actions in line in the routes themselves? Is this correct? If so, why? Is this related to the framework vs library choice?

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M4
    Memory: 212.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.12.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1.1
```

### Used Package Manager

yarn

### Expected Behavior

The upgrade should not impose any changes to existing Remix projects that require major refactorings. Also, Remix already is an extremely opinionated framework. Please leave some space for individual preferences and architectural choices.

### Actual Behavior

It seems we have to inline actions in routes.

**Comment by sergiodxa** [comment]
The code itself doesn't need to be in the route file, but it needs to be exported from a route file

**Comment by camhammel** [comment]
We're experiencing this issue as well when upgrading from remix v2 to react-router 7, - `export { action } from './action'` for instance doesn't seem to work from the route file. We get the following error from vite:

```
[vite] Error when evaluating SSR module /app/routes/request-quote.$token._index/route.tsx:
|- ReferenceError: _action is not defined
```
