### ISSUE TITLE
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css  using RRv7

### ISSUE THREAD

**Issue by matagaralph** [remix-run/react-router#12597]
### I'm using React Router as a...

framework

### Reproduction

``` jsx
<ThemeProvider>
      <BaseStyles>{children}</BaseStyles>
 </ThemeProvider>
```  
Wrapping the app with the Github Primer React [ThemeProvider](https://primer.style/guides/react) causes the error happen.

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 10.44 GB / 15.51 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.12.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /usr/local/bin/npm
    bun: 1.1.40 - ~/.bun/bin/bun
    Watchman: 20240414.112832.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 131.0.6778.204
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2 
    @react-router/node: ^7.0.2 => 7.0.2 
    @react-router/serve: ^7.0.2 => 7.0.2 
    react-router: ^7.0.2 => 7.0.2 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

React router should work with GitHub Primer without issue. I tested the design system without using react router with just React using Vite everything was working.

### Actual Behavior

```
05:52:34 [vite] Error when evaluating SSR module /components/PrimerProvider.tsx: failed to import "@primer/react 
[vite] Error when evaluating SSR module /app/root.tsx: failed to import "@primer/react"
|- TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/mataga/Music/works/primer/node_modules/@primer/react/lib-esm/BaseStyles-5241cbb5.css
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:218:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:244:36)
    at defaultLoad (node:internal/modules/esm/load:122:22)
    at async nextLoad (node:internal/modules/esm/hooks:748:22)
    at async Hooks.load (node:internal/modules/esm/hooks:385:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18)
"
```

**Comment by timdorr** [comment]
This is a Vite issue, not one with the library. Because Primer is `import`ing a CSS file directly, this is causing a loading issue within Node/SSR. You may be able to work around this with something like this: https://github.com/vitest-dev/vitest/issues/5283#issuecomment-1962265873

**Comment by matagaralph** [comment]
> This is a Vite issue, not one with the library. Because Primer is `import`ing a CSS file directly, this is causing a loading issue within Node/SSR. You may be able to work around this with something like this: [vitest-dev/vitest#5283 (comment)](https://github.com/vitest-dev/vitest/issues/5283#issuecomment-1962265873)

Thanks champion.
