### ISSUE TITLE
Memory leak when navigating

### ISSUE THREAD

**Issue by faridsaid20** [remix-run/react-router#12629]
### I'm using React Router as a...

library

### Reproduction

Source code is here:
https://stackblitz.com/edit/github-txkpx7fm-e7hpkuvb?file=src%2Fapp.tsx

Check video for reproduction steps.

https://github.com/user-attachments/assets/175bc732-f608-478b-97fe-2f61b22c4426

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 20.43 GB / 30.99 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  npmPackages:
    @react-router/dev: ^7.1.0 => 7.1.0
    @react-router/node: ^7.1.0 => 7.1.0
    @react-router/serve: ^7.1.0 => 7.1.0
    react-router: ^7.1.0 => 7.1.0
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

Should not generate detached nodes

### Actual Behavior

On navigation creates detached nodes

**Comment by faridsaid20** [comment]
I could reproduce similar bug with Tanstack router
https://github.com/TanStack/router/issues/3056

The problem might be with React itself, but I'm not sure

**Comment by timdorr** [comment]
Since we're not creating DOM nodes directly, it would stand to reason this is about some internal React behavior. But this isn't a bug with the library.

**Comment by faridsaid20** [comment]
The reason why I opened it here, is because the nodes are getting detached only when you navigate from parent to child, but not sibling to sibling or sibling to parent. My bad not providing complete example.

Of course you don't create dom nodes, but you might have reference to unmounted components somehow.
I will update the example code and video. But if you are not interested, then I won't bother
