### ISSUE TITLE
ClientAction revalidates when a 400 Bad Request response is returned

### ISSUE THREAD

**Issue by meln1k** [remix-run/react-router#12643]
### I'm using React Router as a...

framework

### Reproduction

1. Add the following route:

```ts
import { Form, data } from "react-router";

export async function loader() {
    return { foo: "bar" };
}

export async function action() {
    return { foo: "bar" };
}

export async function clientAction() {
    const error = { error: "foo" };
    console.log("returning error", error);
    return data(error, { status: 400 });
}

export default function ClickMeForm() {
    return (
        <Form method="post">
            <button>
                Click me
            </button>
        </Form>
    )
}
```

2. Submit the form

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 13.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.4.0 - /opt/homebrew/bin/node
    npm: 10.9.2 - /opt/homebrew/bin/npm
    pnpm: 9.12.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 131.1.73.104
    Chrome: 131.0.6778.205
    Safari: 18.2
  npmPackages:
    @react-router/dev: ^7.0.1 => 7.1.1 
    @react-router/express: ^7.0.1 => 7.1.1 
    @react-router/node: ^7.0.1 => 7.1.1 
    react-router: ^7.0.1 => 7.1.1 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

A new revalidation request should not be sent when the form is submitted because the client action returned an error.

### Actual Behavior

When the form is submitted, a new revalidation request is sent:

<img width="452" alt="image" src="https://github.com/user-attachments/assets/167e4b50-0f00-478d-947f-a03c5e1cee96" />

**Comment by timdorr** [comment]
The default behavior is to revalidate, even if there is an error. You can customize this behavior with `shouldRevalidate`: https://reactrouter.com/start/framework/route-module#shouldrevalidate

**Comment by meln1k** [comment]
But this is then inconsistent with how server actions work: they do not revalidate if there is a non-200 response code.
