### ISSUE TITLE
[Docs]: Ctrl+K search ignores version selector and always get to the latest version docs

### ISSUE THREAD

**Issue by AlexYegupov** [remix-run/react-router#12650]
### Describe what's incorrect/missing in the documentation

![image](https://github.com/user-attachments/assets/ef4670e7-07d6-41ec-9089-9d1cbce6736e)

How to reproduce: 
1) open docs and select "6.28.1" version
2) search "clientLoader" 
3) go to results

What I get: clientLoader docs for v7 and reseting top page version filter to "latest"

What I expect: keep top page version filter non-changed (6.28.1) and display no results  because clientLoader feature wasn't present in v 6.28

**Comment by timdorr** [comment]
The search indexer only allows us to index one set of documents. It can't work with prior versions, as they don't support that functionality.
