### ISSUE TITLE
Console errors when using dangerouslySetInnerHTML with invalid html

### ISSUE THREAD

**Issue by Maskoe** [remix-run/react-router#12653]
### I'm using React Router as a...

framework

### Reproduction

https://github.com/Maskoe/rr7-invalid-html

If I have a p tag and I set the html to something invalid, I get a console error on initial load.

- It does not happen on client side navigation.
- It does not happen if there is no html following the broken one.
- The console message in the repro is actually useful, but in my real app with a lot more html its just cryptic hydration errors that seem to pick a random element to complain about.
- `suppresssHydrationWarning` has no effect.
- it actually looks and works fine, including the SSR. Its just the console error. 

The easy answer is "just correct the html", but thats not really a reasonable expectation. It could be external from a cms and I could have no control over it.

A workaround I found is using `html-react-parser`. `<p>{parse(brokenHtml)}</p>` works just fine

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 28.42 GB / 63.75 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @react-router/dev: ^7.1.1 => 7.1.1
    @react-router/node: ^7.1.1 => 7.1.1
    @react-router/serve: ^7.1.1 => 7.1.1
    react-router: ^7.1.1 => 7.1.1
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

No console errors.

### Actual Behavior

Console errors.

**Comment by timdorr** [comment]
This isn't a bug with React Router. 

React is doing its best to match the rendered HTML to the resulting DOM, but the way it's parsed will likely end up with a hydration error due to the mismatch. There isn't much you can do about this, but I would recommend the `html-react-parser` solution. 

Related issue: https://github.com/facebook/react/issues/19901
