### ISSUE TITLE
Unexpected 500 Error with React Router Resource Routes

### ISSUE THREAD

**Issue by Moonnz** [remix-run/react-router#12665]
### I'm using React Router as a...

framework

### Reproduction

# Bug Report: Unexpected 500 Error with React Router Resource Routes  

## Description  

When creating a route with the following structure:  

```js  
export async function action(args: ActionFunctionArgs) {  
    return data({  
        test: true,  
    });  
}  
```  

A 500 error is triggered, and the console logs the following message:  

```
The following error is a bug in React Router; please open an issue! https://github.com/remix-run/react-router/issues/new/choose
Error: Expected a Response to be returned from resource route handler
    at invariant3 (react-router/dist/development/index.js:8682:11)
    at handleResourceRequest (react-router/dist/development/index.js:9418:5)
    at requestHandler (react-router/dist/development/index.js:9204:18)
    at nodeHandler (@react-router/dev/dist/vite.js:1980:30)
    at @react-router/dev/dist/vite.js:1986:17
```  

### Observed Behavior  
- The 500 error occurs when there is no default export in the route module.  
- The error message suggests this is a bug in React Router.  

### Workaround  
Adding a default export resolves the issue:  

```js  
export default function() {  
    return <></>;  
}  
```  

With the above addition, the error no longer occurs, and the route functions as expected.  

## Steps to Reproduce  

1. Create a resource route with only the `action` function, as shown in the first code block.  
2. Access the route in your application.  
3. Observe the 500 error in the console.  

## Additional Information  
This issue occurs even when the `action` function returns valid data. Adding an unused default export should not be necessary to prevent errors.  

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 16.14 GB / 30.99 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.volta/tools/image/node/20.16.0/bin/node
    Yarn: 4.5.3 - ~/.volta/tools/image/yarn/4.5.3/bin/yarn
    npm: 10.8.1 - ~/.volta/tools/image/node/20.16.0/bin/npm
    pnpm: 9.15.2 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.204
  npmPackages:
    @react-router/dev: ^7.0.0 => 7.1.1 
    @react-router/node: ^7.0.0 => 7.1.1 
    @react-router/remix-routes-option-adapter: ^7.0.0 => 7.1.1 
    @react-router/serve: ^7.0.0 => 7.1.1 
    react-router: ^7.0.0 => 7.1.1 
    vite: ^5.1.0 => 5.4.1
```

### Used Package Manager

npm

### Expected Behavior

The `action` function should handle the route correctly without requiring a default export.  

### Actual Behavior

- The 500 error occurs when there is no default export in the route module.  
- The error message suggests this is a bug in React Router.

**Comment by Moonflower-labs** [comment]
Hi, in a resource route you should be returning a Response.json() instead of data()

**Comment by timdorr** [comment]
That is the correct answer. Replace `data()` with `Response.json()`.
