### ISSUE TITLE
renderToPipeableStream is not found when using cloudflareDevProxy()

### ISSUE THREAD

**Issue by nozaq** [remix-run/react-router#12660]
### I'm using React Router as a...

framework

### Reproduction

1. Clone https://github.com/nozaq/rrv7-cf-err
1. Run `npm install`
2. Run `npm run dev`
3. Open http://localhost:5173/

### System Info

```shell
System:
    OS: Linux 6.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (10) arm64 unknown
    Memory: 13.40 GB / 15.60 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.9.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.3 - /usr/local/bin/npm
    pnpm: 9.12.1 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @react-router/dev: ^7.1.1 => 7.1.1 
    @react-router/node: ^7.1.1 => 7.1.1 
    @react-router/serve: ^7.1.1 => 7.1.1 
    react-router: ^7.1.1 => 7.1.1 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

Default react-router demo site is displayed.

### Actual Behavior

Failed with the following error.

```
[vite] Named export 'renderToPipeableStream' not found. The requested module 'react-dom/server' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-dom/server';
const {renderToPipeableStream} = pkg;

    at analyzeImportedModDifference (file:///workspaces/rrv7-cf-err/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52057:15)
    at nodeImport (file:///workspaces/rrv7-cf-err/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53060:5)
    at ssrImport (file:///workspaces/rrv7-cf-err/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52914:16)
    at eval (/workspaces/rrv7-cf-err/node_modules/@react-router/dev/dist/config/defaults/entry.server.node.tsx:8:31)
    at instantiateModule (file:///workspaces/rrv7-cf-err/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5

Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.
```

### Additional Information

- This project is almost identical to what `npx create-react-router@latest {project_name}` produces except that `cloudflareDevProxy` is added to vite plugins and `wrangler` package is installed ([diff](https://github.com/nozaq/rrv7-cf-err/commit/4000aea31e60a5a29cc4ebe72b45265ab489170a)).
- It does not fail if `cloudflareDevProxy` is not added to vite plugins.
- #12568 is very similar issue and closed since the issue was about React & Bun rather than react-router. But this issue happens with npm, not Bun.

**Comment by sergiodxa** [comment]
It's the same issue that happens with React and Bun, the issue is not with Bun in particular, but with React

The React team only exports `renderToPipeableStream` if you use Node, but CF doesn't use Node so like with Bun you need to customize the entry.server to use `renderToReadableStream`

**Comment by nozaq** [comment]
@sergiodxa Ah, that makes sense. Thank you for your prompt answer!
