### ISSUE TITLE
transition.redirect() not passing params 

### ISSUE THREAD

**Issue by afreix** [remix-run/react-router#136]
I tried to create a simple auth-flow using a mixin, which passes the attemptedTransition as a param to the login endpoint

``` xml
<Routes>
        <Route handler={MainApp}>
            <Route handler={DeveloperPortal} username={username}>
                <Route handler={ContentArea}>
                    <Route name="overview" path="/overview" handler={Overview}/>
                    <Route name="apis" path="/apis" handler={Api}/>
                    <Route name="applications" path="/applications" handler={Application}/>
                    <Route name="experiments" path="/experiments" handler={Experiment}/>
                </Route>
            </Route>
            <Route name="login" path="/login" handler={LoginArea}/>
        </Route>
      </Routes>
```

``` js
var AuthenticatedRoute = module.exports = {
    statics: {
        willTransitionTo: function(transition) {
            console.log("AuthenticatedRoute");
            if(!UserStore.isLoggedIn()) {
                transition.redirect('/login', {attemptedTransition: transition});
                console.log(transition);
            }
        }
    }
};
```

Both "/applications" and "/experiments" use the AuthenticatedRoute mixin, so that when I try to click on links to them they are redirected to login, but when I output the params that should have been passed in the render function of LoginArea they aren't there

```
render: function () {
        console.log("LoginArea- " + UserStore.isLoggedIn());
        console.log(this.props.params);

        return (
  <Button bsStyle="primary" style={loginButtonStyles} onClick={this.handleClick}>
     Log In
  </Button>            
        );
    }
```

**Comment by andresgutgon** [comment]
> You need to store that transition somewhere in your app and look it up again later

For me one problem is to know what's the best way to store this kind of cross component status in my application. Your auth-flow example is all in the same file. But for me is hard to understand having my code in AMD modules.

@rpflorence can you point to an example of how to use react + react-router and AMD modules to store application state?

Thank you a lot for all the hard work

**Comment by paraboom** [comment]
@andresgutgon Have you solved your problem? 
I have same issue with storing somewhere `transition` and i can't reach `this.props.params` after `transition.redirect` was called.

**Comment by andresgutgon** [comment]
Hi @paraboom I pass the transition to the login view. You can see my code here:
https://github.com/aulasenelaire/binding-vas-experiments/blob/master/src/javascripts/react-mixins/dropbox-auth.js 
follow the files :)

**Comment by paraboom** [comment]
Thanx, for answer @andresgutgon. But you pass transition with query (third argument), but what about params, that assigned to `this.props.params`? I can't do this in my code.

**Comment by andresgutgon** [comment]
@paraboom what do you have in `this.props.params`?

**Comment by paraboom** [comment]
@andresgutgon your first question in this thread was about passing parameters to render function, right? I'm asking about that :smile:

**Comment by gaearon** [comment]
Just to note, you won't get `this.props.params` automatically since RR 0.12, you need to either pass them yourself to `<RouteHandler>` from `state` you get in `Router.run` callback, or use `State` mixin and `this.getParams()`.

**Comment by paraboom** [comment]
@gaearon, @andresgutgon  Thank you very much, guys! This is exactly what i need.

**Comment by paraboom** [comment]
I think this information should be in documentation

**Comment by gaearon** [comment]
It is. If you see any references in docs to `this.props.params`, just let us know and we'll update them to current API.
