### ISSUE TITLE
More powerful/flexible path matching

### ISSUE THREAD

**Issue by mjackson** [remix-run/react-router#142]
Let's make string-based pattern matching more flexible to accommodate some of the use cases we're starting to see.

In particular, I'd like to propose we [follow Sinatra's lead here](http://www.sinatrarb.com/intro.html#Routes) and:
- Allow `?` to mean "match the previous thing 0 or 1 time"
- Modify `*` to **not** match . since it can be excluded using `?`

By just doing these two changes, we can support the following kinds of URLs:
- `/posts/:slug.?:format?` (make the `.html` portion of a URL optional)
- `/files/*.*` (get the file extension in a separate `splat`)
- `/archive/?` (optional trailing slash)

I've [already got this functionality in mach](https://github.com/mjackson/mach/blob/master/spec/router-spec.js) and it's working really well. I rarely (read: haven't yet needed to) use a regular expression to match on a URL path. I realize that this discussion will probably evolve to include supporting full-blown regular expressions, but I'd like to discuss that in a separate issue if people are interested.

**Comment by davidhq** [comment]
is `<Routes ignoreTrailingSlash={true}>` supposed to work in 1.0 ? Doesn't seem so :/ What is the optimal way to achieve optional trailing slashes? `/?` also doesn't work...

**Comment by commandtab** [comment]
Is `ignoreTrailingSlash` on by default? Seems to me like that would be the most sane default.

**Comment by davidhq** [comment]
@commandtab doesn't look like it is, but it would be great!
