### ISSUE TITLE
Specifying default sub-routes and redirecting when there is no activeRouteHandler match

### ISSUE THREAD

**Issue by JedWatson** [remix-run/react-router#149]
Not sure if I missed something obvious about how to do this, but here's what I'm trying to achieve:

Say there's a `User` route that has two sub-routes: `UserDetails` and `UserActivity`.

The `User` route draws common UI (name, navigation, etc) and needs to know the `userId` in order to do so.

So I set them up like this:

``` xml
<Router.Routes>
  <Router.Route handler={App}>
    <Router.Route name="user" path="user/:userId" handler={User}/>
      <Router.Route name="user-details" path="user/:userId/details" handler={UserDetails} />
      <Router.Route name="user-activity" path="user/:userId/activity" handler={UserActivity}/>
    </Router.Route>
  </Router.Route>
</Router.Routes>
```

`App` draws the surrounding UI, `User` draws the common UI for the current user (name, subnav), and `UserDetails` and `UserActivity` draw their specific UI.

The `User` view doesn't have any 'inner' UI and requires either the `UserDetails` or `UserActivity` view to be rendered inside it, but it seems reasonable that a) someone may visit the url `/user/1`, and b) the default redirect should be encapsulated somewhere.

What I can't work out is how to best ensure that any requests to `/user/1` _either_ render the `UserDetails` handler by default, or automatically redirect to `/user/1/details`.

I've (sort of) been able to hack it by adding a `willTransitionTo` static on the `User` component, like this:

``` js
willTransitionTo: function (transition, params) {
  if (transition.path.split('?')[0] === '/user/' + params.userId) {
    transition.redirect('user-details', params);
  }
}
```

...but that's messy, and breaks the encapsulation of the routes / paths, among other things.

It seems that there are a few additions to the API that could make it cleaner, including:
- Add a property to `Route` that lets you specify a default sub-route handler (these could cascade, and wouldn't cause a redirect)
- Add a property / argument / etc. available in `willTransitionTo` that indicates this is the 'final' matched route; i.e. no child routes will also be rendered

Maybe a nice thing to have available generally would be an array of the matched routes, starting with the upper parent; this would be useful in both `willTransitionTo` and `willTransitionFrom`.

Alternatively, I may be going in completely the wrong direction here; If I could get the `:userId` param into the `User` route without specifying the path, I could make the path of the `user-details` route `/user/:userId`, and that would be fine.

**Comment by d4nyll** [comment]
For those coming in 2016, you'd use [`<Indexredirect>`](https://github.com/reactjs/react-router/blob/master/docs/API.md#indexredirect)

```
<Route path="/" component={App}>
  <IndexRedirect to="/welcome" />
  <Route path="welcome" component={Welcome} />
  <Route path="about" component={About} />
</Route>
```

**Comment by yoiang** [comment]
How does one accomplish this layered rendering in React 4? When doing similar one is told that components are not allowed children (nested routes). When one follows the new scheme and moves 

```
  <IndexRedirect to="/welcome" />
  <Route path="welcome" component={Welcome} />
  <Route path="about" component={About} />
```

 into App I get errors: 

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Index`
```

and 

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Index`.
```

Thanks for the help!

**Comment by pratikt-cuelogic** [comment]
I assume IndexRedirect is not available now, 
what would be the best way to achieve the same; ie.
If I have config like this.. 
```
<Route name="user" path="user/:userId" handler={User}>
  <Route name="user-details" path="user/:userId/details" handler={Details}/>
  <Route name="user-activity" path="user/:userId/activity" handler={Activity}/>
</Route>
```
and want to take user directly to /details url
