### ISSUE TITLE
Extracting Sub-Routers to separate component.

### ISSUE THREAD

**Issue by mattatcha** [remix-run/react-router#15]
Is there any way to do the following?

Main

```
      <Routes handler={App}>
        <Profile path="profile" />
        <Explore path="explore" />
      </Routes>
```

Profile

```
        <Route>
          <Route name="dashboard" handler={ProfileDashboard} />
          <Route name="repos" handler={ProfileRepos} />
        </Route>
```

Explore

```
        <Route>
          <Route name="home" handler={ExploreHome} />
          <Route name="showcase" handler={ExploreShowcase} />
        </Route>
```

I would like to do this to separate my app out so i don't have to include every component/route in the Main handler.

**Comment by AlastairTaft** [comment]
I think I have an interesting use case for this. I have a website where users get their own '/mypage' type thing. Depending on what they've configured they may wish to serve up a different react application. e.g. they may have ticked 'portfolio' which means a portfolio react app will be served up, or they may have ticked 'blog' which means a blog react app should be served up.

I currently have this code on my router but I can't see how I can accomplish my sub react apps to have their own router definitions.

```
on('/:handle', async (state) => {
    let handle = await getSiteHandleByName(state.params.handle)
    if (! handle)
      return <NotFoundPage />

    // I could return an app, but how do I configure custom routes at this point?
    return <p>{handle.userId}'s page</p>
});
```

**Comment by taion** [comment]
This is totally server-side no? You'd just serve two entirely separate apps. Or use the async routes stuff to only load the one you need.

**Comment by AlastairTaft** [comment]
It's server and client. I've been using [this starter kit](https://github.com/kriasoft/react-starter-kit) which seems to handle routing totally different with a method like below.

```
await Router.dispatch({ path: req.path, context }, (state, component) => {
  data.body = ReactDOM.renderToString(component);
  data.css = css.join('');
});
```

After your comment I've been reading all the tutorials on async routes. Looks like what I'm asking is completely possible, but I can't see how it fits in with the method used above. I've asked a [more relevant question](https://github.com/kriasoft/react-starter-kit/issues/308) over on the react starter kit repo though.

Cheers.

**Comment by rodrigoruiz** [comment]
The huge-apps example is a good one to demonstrate were routes in separate files makes sense.
How do I achieve that writing the routes with JSX?

**Comment by rockymontana** [comment]
I totally agree.

I'm building an application which is basically an administration system for whatever modules I might build (custom CMS anybody? ;) ), when I install a certain module I might, or might not want a section for that specific module, and it would be awesome to be able to route that from its own isolated environment without having to generate code that does that for me.

But maybe async and dynamically load the needed routes and whatnot is the way to go?

**Comment by eagsalazar** [comment]
Compartmentalizing routes with the corresponding components is very analogous to what a lot of express middleware do where internally they define a ```app = new express.Router()```, then route relative to that, then you can mount that middleare anywhere you want.  I agree 100% with the idea that this would be extremely useful in react-router.   If someone creates a cool image navigation component where in theory I could have nested routes like /user/81 with /images/[12|new|12/edit] etc but without me having to do that wiring myself that would be awesome.  The usefulness of this use case well demonstrated in express as an example.

Also compartmentalizing need not mean coupling.  If you can require then mount the set of routes, there is no reason you couldn't require each component independently if you wanted to and wire them up however you wanted.

**Comment by taion** [comment]
The problem on the client side is that, with the way React mounts components, using nested components and React lifecycle hooks for data fetching will lead to waterfalled requests.

As a different pattern, we support highly compartmentalized route configs. This lets you isolate specific portions of your application (and embed them as sub-applications on specific paths), while not losing the benefits of top-level routing.

**Comment by taion** [comment]
(see e.g. the huge-apps example to see how this works in practice)

**Comment by mgwhitfield** [comment]
@ryanflorence Merge conflicts?  That seems like an easy answer.
