### ISSUE TITLE
Replacing query string without knowledge of other url components

### ISSUE THREAD

**Issue by nhunzaker** [remix-run/react-router#167]
Is there a good way at the moment to replace a query string parameter without prior knowledge of other URL properties? Ideally, I'd love to be able to do something like:

``` javascript
Router.mergeQuery({ filter: 'value' })
```

Thoughts?

**Comment by whather** [comment]
+1 on being able to do Router.transitionTo(null, null, {dialog: 'bar'})

Any updates on this? I have the same problem.

**Comment by uberllama** [comment]
Just ran into the same thing. I have a data table mixin that handles sorting, and I need to change the query string without having knowledge of the current route (or, alternately, being able to access the current route name so I can assemble a link).

```javascript

var DataTableMixin = {
  queryState: {},

  handleSort: function(attr) {
    // ... figure out sort and direction
    this.queryState = _.extend(this.queryState, { sort: attr, direction: direction, page: 1 });
    this.replaceWith('posts', {}, this.queryState);
  }
}
```

In the example above, I would like to be able to say `this.replaceWith(this.queryState)`, `this.replaceWith(this.props.routeName, {}, this.queryState)` or the like.

**Comment by gaearon** [comment]
You can access route name from `Router.State` mixin via something like `_.last(this.getRoutes()).name`.
I agree it's not ideal but doable:

```js
    var routeName = _.last(this.getRoutes()).name,
        params = this.getParams(),
        query = this.getQuery();

    query = assign({}, query, {
      sort: 'something'
    });

    this.replaceWith(routeName, params, query);
```

**Comment by uberllama** [comment]
Thanks Dan, that'll do the trick. Maybe I need to delve into the code and submit more doc PRs :)

**Comment by gaearon** [comment]
I'm sure that will be appreciated!

**Comment by NgKhanh** [comment]
I'm using `browserHistory` to navigate in my app like "foo/:id?q=barId"
That's ok on ContainerComponent where I can access this.props.location.pathname
`<Button onClick={()=>browserHistory.push(this.props.location.pathname+ '?q=foo')}>`
But on children component which hasn't props.location, it's complicate, like that
`<Button onClick={()=>browserHistory.push('foo/' + this.props.fooId+ '?' + this.props.barId)}>`

Any solution to append query to **current pathname**, as
 `browserHistory.appendQuery({'q':'barId'}) `
