### ISSUE TITLE
Animated transitions

### ISSUE THREAD

**Issue by mjackson** [remix-run/react-router#17]
It should be really easy to animate between routes when the URL changes, preferably using `ReactCSSTransitionGroup`.

**Comment by romeovs** [comment]
so this won't work with animations between pages that are handled by the same handler?`/users/john` and `/users/mike` or do I just need to make sure the `john` and `mike` part are in the keys?

**Comment by stefandraht** [comment]
I tried building a version of the example using TransitionGroup's lifecycle hooks rather than CSSTransition and the hooks don't seem to get called. Am I missing something, or is this behavior only supposed to work with CSSTransitionGroup at the moment?

**Comment by anthonator** [comment]
Is there a way or a pattern to make this more flexible? I don't necessarily want everything under a `RouteHandler` to transition.

**Comment by luisrudge** [comment]
Any guidance on this?

**Comment by belohlavek** [comment]
I'm interested in this too, current example seems outdated #1194

**Comment by ryanflorence** [comment]
working on this in the 1.0 branch, there's no more RouteHandler stuff going
on, its all just props (props.children usually) and so animating between
routes should be identical to any other component that's animating
children. there will be much better documentation/examples for animation
too. thanks for your patience :)

On Tue, May 19, 2015 at 8:45 PM, Daniel Belohlavek <notifications@github.com

**Comment by luisrudge** [comment]
I created a pen with a working example:
http://codepen.io/luisrudge/pen/QbEeOR

**Comment by belohlavek** [comment]
Hey @luisrudge thanks for your answer! I got *that* far myself but I got several warnings and an error when trying to run the code :(
```
Warning: Failed Context Types: Required context `routeDepth` was not specified in `RouteHandler`.
Warning: Failed Context Types: Required context `router` was not specified in `RouteHandler`.
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `1`) for key (routeDepth) while mounting RouteHandler (see: http://fb.me/react-context-by-parent)
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context) [...long code...]

Uncaught TypeError: Cannot read property 'getRouteAtDepth' of undefined
```
I read somewhere that might have to do with having duplicate React instances. I'm using Browserify!

**Comment by luisrudge** [comment]
Never saw that. I'm using webpack, but this pen also doesn't throw this errors

Enviado pelo meu Windows Phone
________________________________
De: Daniel Belohlavek<mailto:notifications@github.com>
Enviada em: ‎20/‎05/‎2015 00:27
Para: rackt/react-router<mailto:react-router@noreply.github.com>
Cc: Luís Rudge<mailto:luis@luisrudge.net>
Assunto: Re: [react-router] Animated transitions (#17)

Hey @luisrudge thanks for your answer! I got *that* far myself but I got several warnings and an error when trying to run the code :(
```
Warning: Failed Context Types: Required context `routeDepth` was not specified in `RouteHandler`.
Warning: Failed Context Types: Required context `router` was not specified in `RouteHandler`.
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `1`) for key (routeDepth) while mounting RouteHandler (see: http://fb.me/react-context-by-parent)
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context) [...long code...]

Uncaught TypeError: Cannot read property 'getRouteAtDepth' of undefined
```
I read somewhere that might have to do with having duplicate React instances. I'm using Browserify!

---

**Comment by donaldpipowitch** [comment]
How is the progress with animations in `1.0`? :)

**Comment by LestaD** [comment]
![googleplus-transition](https://cloud.githubusercontent.com/assets/5620073/12952518/c82d5954-d027-11e5-8c55-a6249f3d5d11.gif)
I want to create that transition.
How can i do it with react@0.14.7, react-router@1.0.3 ?

**Comment by luandro** [comment]
Check out the oficial [example](https://github.com/reactjs/react-router/blob/master/examples/animations/app.js). There are alternatives to [react-addons-css-transition-group](https://www.npmjs.com/package/react-addons-css-transition-group) such as [velocity-react](https://github.com/twitter-fabric/velocity-react) and others.

**Comment by misterfresh** [comment]
If like me you're just trying to get simple CSS transitions to work (especially fade-out) with react-router 2.0, and you don't need the heavy artillery, you can use "[react-easy-transition](https://github.com/misterfresh/react-easy-transition)", a very lightweight module that I wrote to solve that. 
```jsx
<EasyTransition 
    path={location.pathname}
    initialStyle={{opacity: 0}}
    transition="opacity 0.3s ease-in"
    finalStyle={{opacity: 1}}
>
    {this.props.children}
</EasyTransition>
```
The [demo](http://misterfresh.github.io/react-easy-transition) with redux integration

**Comment by irudoy** [comment]
@misterfresh huge thanks!

**Comment by Amazing-Space-Invader** [comment]
@misterfresh many thanks!

**Comment by sergio11** [comment]
thanks!!!!

**Comment by AlastairTaft** [comment]
None of these examples work with asynchronous routing, has anyone got any examples of that?

Looking for something that starts fading out before the next chunk has loaded.

**Comment by joncursi** [comment]
Has anyone been able to crossfade with React Router? Every example I've seen will not fade in the new route until the old route is fully faded out, which flashes the screen in a jarring way. Looking for a crossfade solution!

**Comment by taion** [comment]
The bundled animation example shows that.

**Comment by donaldpipowitch** [comment]
Following the [canonical example](https://github.com/reactjs/react-router/tree/master/examples/animations) for animation I noticed that the _leave animation_ is called when the new route could be resolved (e.g. when `onEnter` is async). Say I switch from `route-a` to `route-b` and `route-b` fetches resources, which this takes 4 seconds nothing will be animated in these 4 seconds. The `onLeave` of `route-a` is called immediately however.

For me this is very surprising. Is there any way to trigger the _leave animation_ for `route-a` immediately just like `onLeave` is called immediately for `route-a`?

**Comment by AlastairTaft** [comment]
I managed it in the end. Although for my use case I had a swiping transition. Things I learnt:

- Don't use `ReactTransitionGroup` or `ReactCSSTransitionGroup`, these animations aren't interruptible, makes it feel clunky if the user navigates quickly. The `componentWillEnter` won't fire until it's `componentWillLeave` method has finished completing if the user navigates forward and then back to the same component (means they have to wait for the fade to complete)

- Avoid using the asynchronous `getComponent` in react-router, seems like this isn't interruptible. I.e. if I navigate to a new page which calls `getComponent` and then the user presses back before `getComponent` resolves, they will end up with the wrong component loaded for the current url when `getComponent` does resolve. Didn't test this to much so could be wrong.

I went with [react-motion](https://github.com/chenglou/react-motion), it's the only library that seems to exist that allows you to interrupt animations, even native css animations can't do it, seems animation on the web is seriously lacking, happy to be told I'm wrong.

I have an App component that renders all the child components (pages) within it. I added some logic (using [redux](https://github.com/reactjs/redux)) that would unmount the current page when a script chunk was loading, this would give me my page swipe out animation before the next chunk has started loading.

Then my navigation code looked something like this, i.e. the user would click a 'Next' button and it would fire the below code.

```
dispatch({
  type: 'UPDATE_SCRIPT_CHUNK_IS_LOADING',
  value: true,
})
// Webpack loading of the next chunk needed to display the next page
require.ensure([], (require) => {
  this.context.router.push(`Personal/Index`)
  dispatch({
    type: 'UPDATE_SCRIPT_CHUNK_IS_LOADING',
    value: false,
  })
}, "personal")  
```

The dispatch updates my app redux state so that my App component knows to unmount it's current page. When the next chunk has loaded 'script chunk loading' is turned off in state and the next page is animated in. react-motion takes care of the animating quite elegantly, although it took me a fair bit of time figuring out their `<TransitionMotion />` api worked.

**Comment by donaldpipowitch** [comment]
@AlastairTaft That's gold! Especially the parts about what is interruptible and what not. Thank you. I also tried `react-motion` today and struggled with its API. Do you have an example for that, too?

**Comment by AlastairTaft** [comment]
I created a `PanelsTransition` component that would animate a panel in and out when the user navigates. 

```js
import React, { Component } from 'react'
import { TransitionMotion, spring, presets } from 'react-motion'
// These are just some convenience functions to help calculate the left position of the
// animation
import { getPanelWidth, calculatePanelToEdgeOfScreenDistance } from './../../Panel'

// The css just makes the leaving component `position:absolute` so that it doesn't 
// take up space in the document
require('./PanelsTransition.css')

const calculatePosition = (x, delta) => {
  // If we're not in a browser environment don't do anything
  if (typeof window === 'undefined') return 0;
  const dist = calculatePanelToEdgeOfScreenDistance()
  return dist * x * delta
};

class PanelsTransition extends Component {

  static propTypes = {
    /**
     * The direction of navigation, 1 for forwards, -1 for backwards
     */
    delta: React.PropTypes.number,

    /**
     * Set this to true to animate on initial render
     */
    animateOnInitialRender: React.PropTypes.bool,
  };

  static defaultProps = {
    animateOnInitialRender: false,
  };

  willLeave = () => {
    return { 
      transitionAmount: spring(-1, {stiffness: 300, damping: 26}),
      finalAmount: -1,
    }
  };

  willEnter = () => {
    return { 
      transitionAmount: 1,
      finalAmount: 1,
    }
  };

  render = () => {
    const { pathname, delta, animateOnInitialRender } = this.props

    // If it isn't an initial render then animate in the first component
    if (animateOnInitialRender){
      var defaultStyles = [{
        key: pathname,
        style: {
          transitionAmount: spring(1, presets.gentle),
          finalAmount: 1,
        },
        data: {
          component: this.props.children,
        },
      }]
    }

    return <TransitionMotion
      willLeave={this.willLeave}
      willEnter={this.willEnter}
      defaultStyles={defaultStyles}
      styles={[{
        key: pathname,
        style: {
          transitionAmount: spring(0, presets.gentle),
          finalAmount: 0,
        },
        data: {
          component: this.props.children,
        },
      }]}>
      {interpolatedStyles => {
        return <div>
          {interpolatedStyles.map(config => {
            const isLeaving = config.style.finalAmount == -1
            return <div 
              // Makes leaving components absolute so they don't take up space
              // in the document
              className={`PanelsTransition${isLeaving ? '-leaving' : ''}`}
              key={config.key} 
            >
              <div style={{
                position: 'relative',
                left: calculatePosition(config.style.transitionAmount, delta),
              }}>
                {config.data.component}
              </div>
            </div>
          })}
        </div>
      }}
    </TransitionMotion>
  }
}

export default PanelsTransition
```

In my App component I then had something like this
```js
class App extends Component {

   render = () => {
       const { scriptChunkIsLoading } = this.props
    
       var pathname = this.props.location.pathname
       // Ensure the path always starts with a slash, I've seen it be inconsistent
       // sometimes
       if (pathname.startsWith('/') == false)
          pathname = '/' + pathname

        // Make sure our child element has a key that relates to our page
        // this is important
        var child  = React.cloneElement(this.props.children, {
          key: pathname,
        })

        if (scriptChunkIsLoading){
           // This is kind of crude, it's just means we override our child element and
           // render an empty div that takes up space in the document, 
           // helps with the unmount animation.
           var child = <div 
              style={{
                height: (typeof document !== 'undefined') ? document.body.clientHeight : 1280
              }}
           />
           pathname = "animationPlaceholder"
        }

    return <div>
          ...
          <PanelsTransition 
            pathname={pathname} 
            delta={delta}
          >            
            {child}
          </PanelsTransition>
          ...
       </div>
   }
}
```

It doesn't work perfectly, I plan on improving it, the direction of the animation is wrong when the animation get's interrupted, but apart from that it seems to work well, the finalAmount bit is a bit of a hacky work in progress, that would likely change once I fix this up.

The react-motion api feels a bit awkward and that maybe I'm not using it the way it's intended especially with the way I've hijacked their data key to keep a reference to the component which then gets rendered, but hell it works.

**Comment by stooboo** [comment]
We looked at a few libs out there for this 
currently we're using
https://github.com/maisano/react-router-transition 
Great so far ;-)

**Comment by donaldpipowitch** [comment]
@stooboo `react-router-transition` sadly has the same limitation I [mentioned earlier](https://github.com/reactjs/react-router/issues/17#issuecomment-238490681). I tried it today.

**Comment by stooboo** [comment]
@donaldpipowitch cheers I missed that - thanks for the heads-up

**Comment by suhaotian** [comment]
In the new version 4.x: how to  detect forward or backward ?
