### ISSUE TITLE
Something similar to a 500 response but on the client.

### ISSUE THREAD

**Issue by mtscout6** [remix-run/react-router#179]
So, I did something stupid (meh, it's bound to happen). Which caused the following in my console:

![error](http://f.cl.ly/items/3B1P1P1l0H0F2y0v2i1o/Screen%20Shot%202014-08-07%20at%209.32.12%20AM.png)

Granted, I know this means that I need to add better error handling, and I will. However, when something like this happens in production then the screen is just blank, which is not ideal for an end user.

It'd be nice if there was an error handler that got called that could deal with it so the page is not just blank. Similar to how some web servers serve up a custom page for a 500 response.

Something like `<UnhandledErrorRoute handler={CustomerErrorHandler} />` no path needed since it would stand at whatever url had the error.

**Comment by azaharakis** [comment]
Hi guys, looking at:
https://github.com/rackt/react-router/blob/4ec1f289962217dbd84a8f60d306cfd4d45bf561/UPGRADE_GUIDE.md#routes-ontransitionerror-onabortedtransition
the above technique is removed? Do you recommend another approach? Thanks heaps

**Comment by kellyrmilligan** [comment]
+1 on this, if i'm doing some async work between screens, and there is an error, i'd like to render something but keep the url that was pushed into history as is. similar to displaying an error page from the server.

**Comment by rattrayalex** [comment]
Since this has been un-fixed, can the issue be re-opened?
