### ISSUE TITLE
How to determine pathname without using window.location?

### ISSUE THREAD

**Issue by iamrandys** [remix-run/react-router#184]
I've looked and looked, and I'm unable to find a way to determine the active pathname from the main 
App Route component without using window.loation.pathname.  I will need it in the browser and for server side rendering, so I really don't want to use window.

**Comment by thomasmodeneis** [comment]
hi @iamrandys would you mind sharing this work around here ? I'm also facing same issue and would like to see how you manage to solve it.
Thanks
