### ISSUE TITLE
Multiple routers on the same page?

### ISSUE THREAD

**Issue by hakanderyal** [remix-run/react-router#187]
Is there a way to have multiple routers on the same page, like react-router-component (http://andreypopp.viewdocs.io/react-router-component/multiple)?

Lets say I have a sidebar and a main content area on the same page, how can I have both of them to render a different react component based on the route?

**Comment by mkotsbak** [comment]
See also how this is possible in scalajs-react: https://github.com/japgolly/scalajs-react/blob/master/extra/ROUTER2.md#nested-routes-modules

**Comment by jeremejevs** [comment]
In case anybody stumbles into this issue, looking for a way to have multiple components per route, check [this sidebar example](https://github.com/rackt/react-router/blob/master/examples/sidebar/app.js) (found [here](https://github.com/rackt/react-router/issues/427)).

**Comment by lokaltrav** [comment]
I accomplish this behavior using <RouteHandler />. I have a dashboard with navs down the side, then when you click one, it fills in the main area, and some of those have RouteHandlers, where if you select the next level, it populates the details. Think of gmail, select folder, then message from the list then it shows the message. Only one Router.

**Comment by nuclearspike** [comment]
I accomplish this behavior using . I have a dashboard with navs down the side, then when you click one, it fills in the main area, and some of those have RouteHandlers, where if you select the next level, it populates the details. Think of gmail, select folder, then message from the list then it shows the message. Only one Router.

**Comment by larsnystrom** [comment]
I'm currently migrating an old backbone app to react. To do that I have to render react components at different places in the backbone views, so there are multiple `ReactDOM.render()` calls per page.

Unless there's a way to render the `<Router>` component multiple times I won't be able to incorporate react-router until I've migrated the entire codebase to a single page react app. Being able to render the router multiple times would make the migration go so much smoother. The end game would still be a single `ReactDOM.render()` call (and thus only one router element) but I just can't do that yet.

Is rendering multiple routers something react-router might support in the future?

**Comment by timdorr** [comment]
You can do this with multiple memory history instances.

**Comment by MichaelArnoldOwens** [comment]
```
var routes = (
  <Routes>
    <Route path="/" handler={Main} />
    <Route name="user" path="users/:userId" handler={User}/>
  </Routes>
);
```
What is <Routes> ? How is it different from <Router>? Cannot find it in the docs: https://github.com/ReactTraining/react-router/blob/master/docs/API.md
