### ISSUE TITLE
Routing does not work with location="history"

### ISSUE THREAD

**Issue by shilpan** [remix-run/react-router#199]
``` javascript
<Routes>
  <Route handler={Home}>
    <Route name="about" handler={About}/>
  </Route>
</Routes>
```

Going to `localhost:8000/#/` & `localhost:8000/#/about` do the right thing

Adding `location = "history"` to routes breaks down `localhost:8000/about` throwing `404`

**Comment by pxwise** [comment]
For others who get stuck while adding server side pushState with nginx, the directive in the readystate4 link above does not work for me. For me, the working nginx.conf looks like:
```nginx
# set root and index
root /var/www/approot/;
index  index.html;

# route all requests that don't serve a file through index.html
location / {
   if (!-e $request_filename){
      rewrite ^(.*)$ /index.html break;
   }
}
```
See [this stackoverflow answer](http://stackoverflow.com/a/18076907/1774183).

**Comment by sethen** [comment]
@pxwise confirm works.

**Comment by sheeley** [comment]
If looking for something a little more flexible, this also works:
```
server {
      root /usr/share/nginx/html;

      location ~ (?:.+\/)((?:.+)\.(?:.+)) {
        # $1 is the filename
        try_files $uri /$1 /css/$1 =404;
      }

      location / {
        try_files $uri /index.html;
      }
    }
```

**Comment by Authorlove** [comment]
Since there may be ajax request api, the following suits for this case,

    server {
        listen 80;
        server_name example.com;
        root /var/www/example.com;
    
        # Any route containing a file extension (e.g. /devicesfile.js)
        location ~ ^.+\..+$ {
            try_files $uri =404;
        }
    
        # Any route that doesn't have a file extension (e.g. /devices)
        location / {
            try_files $uri /index.html;
        }

        # The location block above provides the shortest prefix, of length one, 
        # and so only if all other location blocks fail to provide a match, 
        # this block will be used.
    
        # Ajax api starts with /v1/ will be proxied
        location /v1/ {
            proxy_pass http://proxy;
        }
    }

**Comment by perfectfoolish** [comment]
@ryanflorence your project http://github.com/rackt/react-boilerplate could not be accessed now.

**Comment by tanmynguyen** [comment]
@pxwise  Thanks. Worked (y)
