### ISSUE TITLE
Make `to` optional on `Link`

### ISSUE THREAD

**Issue by appsforartists** [remix-run/react-router#218]
In my workflow it's not uncommon for me to insert an icon on the page before I'm ready to have it link anywhere.  This lets me prototype the UI to see how it feels.

[This IconButton component](https://github.com/appsforartists/isomorphic-react-test/blob/master/application/components/generic/IconButton.jsx) originally used `<Link>` instead of `<a>`; however, I hated getting errors every time I made an `IconButton` and wasn't ready to add a `link_to` prop.  Therefore, I swapped it out.  Now that I'm using `<a>`, I no longer have access to the benefits of ReactRouter on the client-side.

Can we please make `Link.to` optional, the same way that `a.href` is?

**Comment by hellojwilde** [comment]
Can we throw a warning here? (Or specify isRequired as a PropType on it?) 

"[TypeError: Cannot call method 'charAt' of undefined]" is a pretty scary message that makes a pretty trivial user error seem like a library error. Thanks! :)

**Comment by gaearon** [comment]
Agreed! @ryanflorence, why is `to` not required?
