### ISSUE TITLE
Match more than one route

### ISSUE THREAD

**Issue by itrelease** [remix-run/react-router#241]
Suppose there is a page with list of articles and it lives at `/` (root page) and when user click on some article url should change to `/post/something` and the component that represent specific article is layout above the current component like popup and if user open direct link `/post/something` I need to render the list of articles and the popup component. So is there a way to do this?

**Comment by kompot** [comment]
Any thoughts on this, guys?

Seems like a major use case to me (exactly what @gaearon described above).

**Comment by knowbody** [comment]
isn't this what [Pinterest example](https://github.com/rackt/react-router/commits/master/examples/pinterest) does?

**Comment by andreechristian** [comment]
Any updates on this one? It is a major use case to me too

**Comment by gaearon** [comment]
@andreechristian https://github.com/reactjs/react-router/issues/241#issuecomment-149580100
