### ISSUE TITLE
Support for dynamic routes

### ISSUE THREAD

**Issue by ryanatkn** [remix-run/react-router#243]
Is dynamically creating routes based on application state a supported or planned feature? [This jsfiddle](http://jsfiddle.net/u9bt290o/2/) shows an example of props being resolved only the first time. Perhaps there's a better pattern I haven't found.

The use case I'm after is explained in [the docs](http://andreypopp.viewdocs.io/react-router-component) for react-router-component, which supports dynamic routes:

> Having routes defined as a part of your component hierarchy allows to dynamically reconfigure routing based on your application state. For example you can return a different set of allowed locations for anonymous and signed-in users.

**Comment by emmenko** [comment]
@zackfern any luck on your problem? I also need to implement some similar solution for a plugin system and I am also struggling with the setup. If you could shred some light or if you found some solution it would be awesome, thanks ;)

**Comment by revolunet** [comment]
hey :) i'd like to handle infinite nested states in my app, for example i open a "card" and another one can open inside it, and on and on, on-demand.
So all these states cannot be predicted, they depend on the user interactions, ex :

technology > javascript > web > css...

any idea how to implement this in a clean way ?

**Comment by pawawat** [comment]
@zackfern have you got a solution on your problem? I have the similar problem, thanks

**Comment by ryanflorence** [comment]
use a wild-card path, and then parse it yourself.

<Route path="*">

this.props.params.splat

And then nest the Card view over and over for your parsed path.

**Comment by zackfern** [comment]
@pawawat I ended up creating my own registration system for registration into the routes. When it came time to generate the Route JSX I looped over my registration array and generated the Route object on the fly.

**Comment by revolunet** [comment]
@zackfern any code sample ?

**Comment by vcarl** [comment]
I'm in a weird spot where I'd love support for this, but only so that we can phase it out little by little in the existing application. We're using backbone routes, with subroutes being dynamically added when a route is loaded--which is super gross. I'm pushing for moving to react-router, but having to migrate all at once makes the task a lot more imposing.

**Comment by bishopZ** [comment]
I too have this issue where my routes are stored in an immutable map. Even converting the map to an array, react-router still does not resolve the routes.

```javascript
ReactDOM.render(
  <Router history={history}>
      {state.pages.toSeq().toArray().map((item) =>
        <Route 
          key={item.get('route')} 
          path={item.get('route')} 
          component={require(item.get('component'))} />
      )}
  </Router>
  , target
);
```

Any help appreciated.

**Comment by incubus8** [comment]
any update on @bishopZ code? i also can't do the dynamic routes with `map`.

**Comment by 10thfloor** [comment]
+ 1

**Comment by 10thfloor** [comment]
Adding dynamic routes using `map` would be a great feature. The comment about server-side applications not supporting dynamic routes seems a bit dismissive; there is no reason I can see for enforcing the same paradigm in browser apps.

Use case: I'm building a quiz app where each question gets a route (on client), and users can add questions (by pushing an object into an array), thereby (in a perfect world) adding routes to access those questions via `map` ...

What are the drawbacks I'm not seeing?

**Comment by kanedaki** [comment]
Dynamic routes would be also very helpful when loading async modules that also have some routes.

**Comment by taion** [comment]
Dynamic routes are supported for the async case. You just can't change your root route ATM.

**Comment by eloiqs** [comment]
I had a problem while trying to generate routes based on my state. I'm dumping that here in case someone stumble upon this post like I did earlier.
```javascript
const routes = [
  this.state.routes.map(
    route => {
        {
          path: route.path,
          component: route.component,
        }
    }
  )
]
```
and later when you declare your router:
```javascript
<Router routes={routes} history={browserHistory} />
```

from the [docs](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#configuration-with-plain-routes)

**Comment by ranizi** [comment]
Hello @ryanflorence 
Is it still the case that you 
> believe that you should declare all your routes up front
?
or is there a new way now to manipulate the route list according to app state?
