### ISSUE TITLE
Change URL without triggering re-route

### ISSUE THREAD

**Issue by johnthedebs** [remix-run/react-router#266]
I'm trying to implement a gallery that behaves like Instagram's, but I'm having trouble due to the fact that I can't change the URL without triggering a full re-route.

What I'd like to be able to do is open a modal from an image gallery and change the URL such that copying/pasting the URL results in displaying just that image and not the gallery behind it.

In other words, I have a set of routes that looks like this:

```
<Routes location="history">
    <Route name="index" path="/" handler={App}>
        <Route name="featuredGallery" path="/items/featured/" handler={FeaturedGallery} />
        <Route name="itemDetail" path="/items/:id/" handler={ItemDetail} />
        <DefaultRoute handler={Homepage} />
    </Route>
</Routes>
```

And I'd like to be able to visit `/items/featured/` and click an item to open a modal that changes the URL to, eg, `/items/10/?modal=true` without triggering the `ItemDetail` handler (I will render it inside the modal in `FeaturedGallery` when an item in the gallery is clicked).

However, if `/items/10/?modal=true` were to be pasted into a new browser window, it _should_ trigger the `ItemDetail` handler rather than `FeaturedGallery`.

If there's a way to do this already, I haven't been able to figure it out. Any help is appreciated!

**Comment by adcooley** [comment]
hey guys, I'm trying to accomplish this exact thing, but since the issue is two years old I'm not surprised I'm having trouble solving it the same way. I added the static `willTransitionTo` method and am having no luck with it getting called. Should I be using the `onEnter` hook instead? If so, how can I determine whether it's a first render or not?

Any help is appreciated!

**Comment by flux627** [comment]
I'd recommend opening a new issue with you exact use-case, I think that would have a higher probability for finding the help you need.

**Comment by adcooley** [comment]
@flux627 thanks for the tip. I ended up using onEnter (it appears that is only called on first render) so I'm all set!

**Comment by flux627** [comment]
@adcooley, so you were able to accomplish what was described by the OP?

**Comment by adcooley** [comment]
@flux627 I believe so, yes. Happy to share more details if anyone is interested.

**Comment by Pines-Cheng** [comment]
I have this demand too.

**Comment by vijay-vadlamani** [comment]
@adcooley could you post a few more details about this if you can? I am sailing in the same boat and would like to know if you used history.pushState or did you come up with a different solution for your usecase? any help would be greatly appreciated, Thank you.
