### ISSUE TITLE
Not working with browserify with the minifyify plugin active

### ISSUE THREAD

**Issue by mariusk** [remix-run/react-router#273]
I have a simple component that builds and runs fine using browserify, but fails as soon as I add the minifyify step (using the browserify plugin). With minifyify the following error shows in the browser console when the app is loaded:

```
Uncaught Error: Cannot find module './makePromise' 
```

I can only speculate that some of the browserify "require" magic fails internally in react-router as it seems to use other syntax and/or magic for doing something similar internally.

UPDATE: Did a little digging. In the working code, the following stuff gets added to support the "require" magic (when no minifcation is used):

``` javascript
(function(define) { 'use strict';
define(function (require) {

    var makePromise = require('./makePromise');
    var Scheduler = require('./Scheduler');
    var async = require('./async');

    return makePromise({
        scheduler: new Scheduler(async)
    });

});
```

In addition there is the actual definition of the makePromise function itself, which uses the proper name "makePromise" as well.

When minified, the _only_ mention of makePromise is inside the following minified code:

``` javascript
38:[function(require,module,exports){
!function(e){"use strict";e(function(e){var n=e("./makePromise"),i=e("./Scheduler"),r=e("./async");return n({scheduler:new i(r)})})}("function"==typeof define&&define.amd?define:function(e){module.exports=e(require)});
},{}],39:[function(require,module,exports){
```

My guess is that the require magic done by browserify isn't working very well with minification...

**Comment by bentayloruk** [comment]
Thanks for fixing this @mjackson!  I ran into this problem this very morning.  Grabbing master and installing has set me on my way.  There is a :beer: in London with your name on it (or a carbonated drink of your preference).

**Comment by mjackson** [comment]
@bentayloruk Looking forward to it! :)

**Comment by garthk** [comment]
> This shouldn't be a problem anymore because we don't depend on when.js in master

That's true if I switch my dependency to master. I'd rather not; are you planning a release soonish?

**Comment by rpflorence** [comment]
yeah, sorry holidays and such, should be really soon.
