### ISSUE TITLE
Question: recommended way to maintain the page title

### ISSUE THREAD

**Issue by nemtsov** [remix-run/react-router#288]
**Note:** This is a question, and not an issue. Please close it if this isn't the appropriate place for it.
**Question:** Can you recommend a way to maintain the page title with `react-router`?

**Comment by ivan-kleshnin** [comment]
**react-document-title** is good, though it would be better to support SEO titles in **react-router** since **react-document-title** just duplicates its hierarchy. SEO title is a navigational aspect and can be lifted to router IMO.

**Comment by gaearon** [comment]
I probably subliminally got the idea from this thread and later forgot about it.

**Comment by alanhogan** [comment]
Ivan, your point makes a lot of sense to me

**Comment by gaearon** [comment]
I think it's best left in userland though. It's trivial to make a function to wrap your route handlers into react-document-title or whatever else comes along.

**Comment by xpepermint** [comment]
Anything new here? I'm banging my head against the wall because of this ;).

**Comment by jaraquistain** [comment]
^I'm wondering the same thing as well. As of now I've yet to find a solution for rendering route-specific meta tags on the server.

**Comment by ivan-kleshnin** [comment]
@jaraquistain try https://github.com/gaearon/react-side-effect 
It was created for such tasks

**Comment by jaraquistain** [comment]
@ivan-kleshnin Thanks for the tip, I'll check it out

**Comment by rafinskipg** [comment]
React helmet is great! Check it out https://github.com/nfl/react-helmet

**Comment by jaraquistain** [comment]
I second react-helmet, I actually ended up using that in my implementation
