### ISSUE TITLE
improper routing when the param contains a slash

### ISSUE THREAD

**Issue by ztmr** [remix-run/react-router#313]
Let `item/:id` be a route and `item.id` a key used to lookup the item in a database. If the `item.id` contains special characters barring the slash, the URL is being generated correctly. If the `item.id` contains one or more slashes `/`, none of them is escaped and causes routing issues -- especially when there is another route of `item/:id/...`.

I have experimented with the following:

```
--- Path.js     2014-09-24 12:17:32.944015842 +0200
+++ Path.js.new 2014-09-24 12:16:51.104016891 +0200
@@ -52,7 +52,7 @@
     }

     var compiled = compilePattern(pattern);
-    var match = URL.decode(path).match(compiled.matcher);
+    var match = path.split('/').map(URL.decode).join('/').match(compiled.matcher);

     if (!match)
       return null;
@@ -97,7 +97,7 @@
       );

       // Preserve forward slashes.
-      return String(params[paramName]).split('/').map(URL.encode).join('/');
+      return URL.encode (params[paramName]);
     });
   },
```

...but there is still regex that matches params, so I stopped hacking the project and started to ask why the hell somebody took so much of the special care to preserve the slashes in the parameters.

In general, we don't use slashes in object identifiers but we're currently doing migration of some ancient data where the slash sometimes appear in the object id and it is not feasible to remove it across all the object references. Also, doing extra param encoding/decoding when passing it to the link and withdrawing it from the target component properties would work, but it is a serious nuisance.

Is there any special reason for keeping the original behavior? Can we work it out somehow?

**Comment by mingfang** [comment]
I'm still seeing this problem with the latest version.
Was there a fix?

**Comment by bripkens** [comment]
We are running into this issue as well and we will also need to encode and decode URI params manually. Unfortunately this is not a scalable solution as @ztmr has mentioned.

**Comment by michaelperrin** [comment]
I ended up encoding my route parameter in my link:

    <Link to={"/my/path/" + mySlugString.replace(/\//g, '%2F')}>link</Link>

**Comment by coolblabla** [comment]
+1

**Comment by mertkahyaoglu** [comment]
Have the same problem 😞

**Comment by taion** [comment]
`pathname` is just a string; obviously we can't blindly encode all the `/` characters in the string, so you'll need to call `encodeURIComponent` yourself on any params that need to be escaped

**Comment by ifokeev** [comment]
@taion why we can't match routes with regex?

**Comment by taion** [comment]
Because it's just not a feature yet. And won't be unless we have a way to move to path-to-regexp entirely for path regexps.

**Comment by bl-nero** [comment]
We've been just struck by this. We have a splat that contains a breadcrumb of product categories; the thing is, one of the category IDs has a slash that is encoded as %2F, and the react-router "intelligently" decodes it, corrupting our IDs. Is there any way to turn off this behavior?

**Comment by Brisros** [comment]
I had an issue like that, the solution was

item/:id*

**Comment by ChadRidings** [comment]
Actually some id's do have slashes and it's more common than you'd think (whether it's best practice or not.  Take the Entertainment Identifier Registry for example.  Every EIDR has a slash in it.  This is troublesome when setting up param's in the route... as it treats everything before the slash in the EIDR as a directory.

**Comment by catonymous** [comment]
Why this one is closed? There is a lot of other kinds of params that have to contain slashes. Express router decodes them correctly, but react-router doesn't yet. Shame on you, guys.

P.S. You can fix this by replacing `%2F` with `/` for `values[index]` at https://github.com/ReactTraining/react-router/blob/f24fb54323245db093b8658d6338c019148642da/packages/react-router/modules/matchPath.js#L51 because `decodeURI` keeps `%2F` encoded at https://github.com/ReactTraining/history/blob/4aeb6693758bbaf221274b5894218e8e0b057db4/modules/LocationUtils.js#L37.

P.P.S. For now I import following `monkey-patch.js` into my index file:


```javascript
import { Route } from 'react-router';

const matchEncodedSlashes = Route.prototype.computeMatch;
Route.prototype.computeMatch = function() {
  const match = matchEncodedSlashes.bind(this)(...arguments);
  if(match && match.params) {
    const params = match.params;
    for(const key in params) {
      params[key] = params[key].replace('%2F', '/');
    }
  }
  return match;
};
```

**Comment by flavio-dev** [comment]
What about `.` in the url... ?
example: blabla/token.id.with.dots
