### ISSUE TITLE
Using the Navigation mixin in a Flux architecture versus the removed `Router` transition methods

### ISSUE THREAD

**Issue by ryanatkn** [remix-run/react-router#380]
I'm having trouble seeing how replacing the functions `Router.transitionTo`, `replaceWith`, and `goBack` with the Navigation mixin is compatible with a Flux architecture. Let's say I have a component that creates a new post. I hit the create button and a component responds by firing off an action. In 0.7.x or before, I'd use `Router.transitionTo` in either the action or store layers when the action was successful. In 0.9.x and beyond, a component needs to do this. How should the component know to make the transition?

One solution would be to pass the actions all the way through so the component knows what to do. Another solution would be to provide a callback from the component when the action is created that would be called when the transition should happen. Yet another would be to have some special store state that the component would read to trigger the transition, and then immediately reset that state. None of these solutions seem particularly elegant or fluxy to me, but I'd be interested in hearing any recommendations. A callback is probably my favorite of the three but it feels like a reversal of data flow - Flux heresy?

**Comment by 2color** [comment]
> I guess I can speak briefly to this. All the flux demos I've seen do data fetching in componentDidMount of a component. If some higher level component is already mounted, and the route changes, and the component is still active, componentWillReceiveProps will be called, but componentDidMount will not, and so it's not going to refetch the data

@rpflorence 
What's your recommendation in this context?

**Comment by JoelOtter** [comment]
@Atu Did you solve your issue? I've run into exactly the same thing using rpflorence's given code.

**Comment by gaearon** [comment]
@JoelOtter I use this:

```js
'use strict';

var router;

// Here's the trick: assign to module.exports before any require()s
module.exports = {
  getCurrentPath() {
    return router.getCurrentPath();
  },

  makePath(to, params, query) {
    return router.makePath(to, params, query);
  },

  makeHref(to, params, query) {
    return router.makeHref(to, params, query);
  },

  transitionTo(to, params, query) {
    router.transitionTo(to, params, query);
  },

  replaceWith(to, params, query) {
    router.replaceWith(to, params, query);
  },

  goBack() {
    router.goBack();
  },

  run(render) {
    router.run(render);
  }
};

var routes = require('./routes'),
    Router = require('react-router');

router = Router.create({
  routes: routes,
  location: Router.HistoryLocation
});
```

**Comment by JoelOtter** [comment]
@gaearon - Brilliant, thank you.

**Comment by michalradziwon** [comment]
@gaearon - nice, thanks!

**Comment by rseymour** [comment]
@gaearon what is the name of the file you are creating there and what does it do? Could you put it in your flux docs now that you are a contributor (as of today)? Our team now has two solutions one of which involves nested routing and a lot of {...routerState} param passing (which makes the react dev tool not very neat and tidy) and another that uses a routeStore which is apparently not the way y'all do it (although it feels like the most elegant option to me).

**Comment by gaearon** [comment]
>what is the name of the file you are creating there and what does it do? 

I call it `router.js`. It just proxies calls to the real router instance, but unlike the real instance, it is available as `module.exports` right away, so action creators can `require` it without a problem.

Should we document this @ryanflorence? I understand we want #755 to fix this.

**Comment by rseymour** [comment]
Keep working on #755 because that is the bigger issue.  I will see if I can get by without this for now.

**Comment by ryanflorence** [comment]
@gaearon sure, we can add it to the `flux.md`

**Comment by gaearon** [comment]
@ryanflorence https://github.com/rackt/react-router/pull/769

**Comment by moklick** [comment]
@gaearon I tried your solution but router.getCurrentPath() for example does not work for me. Only the Navigation methods seem to work.

**Comment by gaearon** [comment]
It probably changed to getPath in 0.12. If it works, can you please amend the docs?

**Comment by moklick** [comment]
It does not work with getPath() either. Only the Navigation Mixin functions seem to work with that solution but not the State Mixin functions.

**Comment by moklick** [comment]
@gaearon these are the functions/props we have access to:

```
childContextTypes
recordScrollPosition
getScrollPosition
displayName
isRunning
cancelPendingTransition
clearAllRoutes
addRoutes
replaceRoutes
match
makePath
makeHref
transitionTo
replaceWith
goBack
handleAbort
handleError
handleLocationChange
dispatch
run
refresh
stop
propTypes
isReactLegacyFactory
type
```

**Comment by gaearon** [comment]
@moklick 

You're right. This method no longer works (it worked when `router` was an actual instance, I copied this code from pre-0.12 times). I removed it from docs: https://github.com/rackt/react-router/commit/d03b968ef4b52a489cbb2830ab716acb8d9f118e

Instead, to access current path from somewhere other than component, have your own custom action and store: https://github.com/rackt/react-router/blob/master/docs/guides/flux.md#accessing-route-and-params-from-action-creators

**Comment by moklick** [comment]
@gaearon Awesome! Thanks!

**Comment by e-monson** [comment]
https://github.com/rackt/react-router/blob/master/docs/guides/flux.md no longer exists. Is there an updated version somewhere?

**Comment by 5h1rU** [comment]
@gaearon Do you have this documentation link working somewhere? Is 404 now

https://github.com/rackt/react-router/blob/master/docs/guides/flux.md#accessing-route-and-params-from-action-creators

**Comment by adavkay** [comment]
I don't know if this is guide is still relevant but you can access an old version here: https://github.com/rackt/react-router/blob/d03b968ef4b52a489cbb2830ab716acb8d9f118e/docs/guides/flux.md

**Comment by anthonator** [comment]
What's the preferred way to access the router from an action creator in 1.0?

**Comment by LeBlaaanc** [comment]
I'm curious how this is done as well. Seems like the only way to access the router is via mixins/props now.

**Comment by zuhairnaqvi** [comment]
What's the preferred way to access the router from an action creator in 1.0?

**Comment by tsing** [comment]
https://github.com/rackt/react-router/blob/master/docs/advanced/NavigatingOutsideOfComponents.md

**Comment by vtambourine** [comment]
None of the upper links works now. Here is the proper link to the guide:
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/NavigatingOutsideOfComponents.md

**Comment by icodeforlove** [comment]
man they just keep changing it heres the new one

https://github.com/reactjs/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md

**Comment by ksrawat** [comment]
@ryanflorence How can i add dynamic route with component. Assuming i have 'Page2' as component but want to load it dynamically without defining it very first time. But on some event i would like to add this route entry and it should render my component. Is it possible to add following entry dynamically?

<Route path={runtimepath} component={runtimecomponent}/>
