### ISSUE TITLE
[async-props] Warning: Required context `activeDelegate` was not specified in `Link`.

### ISSUE THREAD

**Issue by natew** [remix-run/react-router#383]
Not sure how this started happening, it seems like at one point it was working fine and all of a sudden it's broken. Getting a stack trace is being difficult as it's just warning me not erroring (it also seems ReactPerf is running on my stack, and I didn't explicitly enable it anywhere so I'll have to see whats up there).

Anytime I use a `<Link />` now it seems to give this warning, but it also breaks my application.  You can see it happening with my repo: http://github.com/natew/react-base.

Console warning is: `Warning: Required context activeDelegate was not specified in Link.`

**Comment by chaliy** [comment]
I have this issue in tests, where I do not have <Routes> component. I test logic that is not related to routing. Is there any way to workaround this requirement in tests?

**Comment by gaearon** [comment]
@chaliy For 0.13, see https://github.com/rackt/react-router/blob/v0.13.3/docs/guides/testing.md. It should be similar for 1.0 beta if that's what you use, although the exact methods may differ.

**Comment by chaliy** [comment]
@gaearon  thanks,  that's helpful
