### ISSUE TITLE
Regex in path?

### ISSUE THREAD

**Issue by jenil** [remix-run/react-router#391]
Hello,

Is there a provision for something like `<Route name="EventListing" path={/\/(movies|concerts|plays)/} handler={EventsList} />`?

**Comment by phun-ky** [comment]
Hm, this is an old issue, but in my current team we have this issue:

    <Route path={'/apples/:appleId'} component="AppleComponent"/>
    <Route path={'/apples/:appleId/otherstuff/**/'} component="AppleComponent"/>
    <Route path={'/apples/:fruidId/someotherstuff/**/'} component="AppleComponent"/>
    <Route path={'/apples/:fruidId/someotherstuff/**/'} component="AppleComponent"/>

or

    <Route path={'/apples} component="AppleComponent">
      <Route path={':appleId'} component="AppleComponent">
        <Route path={'otherstuff/**/'} component="AppleComponent"/>
      </Route
      <Route path={':fruidId/otherstuff/**/'} component="AppleComponent"/>
      <Route path={':fruidId/otherstuff/**/'} component="AppleComponent"/>
    </Route

The first one works, but not providing a meaningful path for packages/components relying on the path hierarchy, for example `react-breadcrumbs`

If the path had regex support, we could solve this in a better way (with correct hierarchy)

**Comment by sassanh** [comment]
@ryanflorence sorry for mentioning you here. But as this thread is closed I just wanted you to notice it again or maybe reopen it. There are things that can be done easily by regex and to so with current wildcard used in `react-router` developer needs hacks and duplicating code, etc.

I guess you're aware of this but let me know if we need a list of things that current wildcard system fails to do and regex can. If we try to expand its functionality as discussed here https://github.com/reactjs/react-router/issues/142 we'll end up reinventing regex. I think best would be to support regex just like Django does for example: https://docs.djangoproject.com/en/1.10/topics/http/urls/

**Comment by jalooc** [comment]
For me too, dealing with `path` not being able to accept a regex is a pain for it enforces some hackish solutions for things that could be handled with regex in one line. What is more, the [docs](https://reacttraining.com/react-router/web/api/Route/path-string) suggest, that `path` can be anything that [path-to-regexp](https://github.com/pillarjs/path-to-regexp#usage) understands, so I guess regex should be included. 

The most interesting part is, as far as I can see, that `path` **does** work with regex, only the PropType is `string`. @ryanflorence  How about changing the PropType then? :)

**Comment by harlantwood** [comment]
react router 4 support regex paths, eg:

```jsx
<Route exact path="/commit/:git_commit([0-9a-fA-f]{40})" component={ViewCommit} />
```

more info here: https://egghead.io/lessons/react-use-regular-expressions-with-routes-with-react-router-v4

**Comment by albertstill** [comment]
I don't think it does support Regex, the link above requires payment, and I only see `path-to-regexp` in the [source](https://github.com/ReactTraining/react-router/blob/v4.2.2/packages/react-router/modules/matchPath.js#L16).

A React Router 4 solution using string paths and a Regexp in the `render` prop can look like this:

```js
<Route
  path="/:slug"
  render={({ match }) => {
    if (!/^[A-Za-z0-9]{6}$/.test(match.params.slug)) {
      return <NotFound />;
    }
    return <CommitmentPage />;
  }}
/>
``` 

Here `/about-us` does not match but `/fU3oE8` does.

**Comment by sassanh** [comment]
React Router 4 does support regex. He provided an example apart from the link.

**Comment by albertstill** [comment]
Ah oops nice one, the `path-to-regexp` library React Routers uses supports [custom match parameters](https://github.com/pillarjs/path-to-regexp#custom-match-parameters) in string. Thanks

**Comment by polkovnikov-ph** [comment]
Can we please remove the shameless ad up there?

**Comment by polkovnikov-ph** [comment]
@timdorr Can we please remove the shameless ad up there with paywalled article on egghead?

**Comment by Mindaugas-Jacionis** [comment]
Hi, any option for negative regexp. I have 2 routes `/subscribe/:token` && `/subscribe/success`, I would like to have something: `/subscribe/:token(*|!success)` to exclude `success` from route with `:token`. Otherwise I get the one with token param rendered & not the one for the success.  
  
I've tried this: `/subscribe/:token((?!success).*)`, but got some crazy error.

**Comment by cowCrazy** [comment]
@Mindaugas-Jacionis I guess it is not the solution you wanted but will work.
`
    <Route path="/subscribe/success" exact component={Success} />
    <Route path="/subscribe/:token" exact component={Token} />
`
When you place it like this in the switch component, the `success` path will be matched before the `:token` path is.

**Comment by dachinat** [comment]
@Mindaugas-Jacionis hi, did you find a solution yet?

@cowCrazy this does not work for me, both components get rendered in my case. Using switch and exact.

**Comment by kalimk** [comment]
<div className='hide_class'>
        <Header />
</div>
