### ISSUE TITLE
Smarter goBack

### ISSUE THREAD

**Issue by simenbrekken** [remix-run/react-router#408]
Currently one has to use `ActiveState` with a `willTransitionTo` hook to know if `Navigation.goBack` will do anything. It would be nice if `goBack` returned a boolean that tells you wether it there's anything in history (as managed by react-router).

**Comment by ganmor** [comment]
Maybe it should be propagated by the Navigation mixin.
Currently it does not return anything.

```js
goBack: function () {
    this.context.goBack();
 }
```

**Comment by gaearon** [comment]
@ganmor Good catch, care to submit a PR?

**Comment by taurose** [comment]
It's fixed in master. 62c49d2925785a4184860accdc125fdeb0ad4806

**Comment by ganmor** [comment]
Yep jus seen that,  had an old version sorry.
My mistake, fixed by #825

**Comment by dmr** [comment]
Is there a way to do a "canGoBack"?

**Comment by giantelk** [comment]
@dmr try this:
```
  handleBackClick() {
  	if ( this.goBack() ) {
  		console.log ("Can Go Back");
  	}
  	else {
  		console.log("Can't go back"); 
  		this.transitionTo('/'); // App root.
  	}  	
  }
```

**Comment by dmr** [comment]
Thank you, this works ok for now

**Comment by carnevalle** [comment]
I am using the latest beta3 and I am trying to only show a back button if it is relevant, like so:

```
if (history.length > 0)
  // show the back button
```

Is this possible in beta3 and if so, could anyone show an example of how it would work in a component?

**Comment by giantelk** [comment]
I was trying to get this working too. See below... A hack is to save the existing window.history.length in `this.state`; otherwise all previous web site/app history (i.e. if you surf YouTube before loading your app into the same browser tab) will be reflected in `window.history.length`. 

```
// In in your root component/app.
   getInitialState: function() {
      return {
        myWindowHistoryStart: window.history.length // Could also just put this into an object, see below.
      };
   },

// Somewhere else in your code, to check if you should show Back button.
if ( window.history.length > this.state.myWindowHistoryStart  ) {
  // show the back button, i.e. setState( {isShowBackButton: true} );
}
```

Why even use state, since myWindowHistoryStart is static, just want to capture starting length when your app loads:
```
MyThing = React.createClass({
   myWindowHistoryStart: window.history.length, // Could also put this in ComponentWillMount 
                           // depending on how you want to organize things, may be more explicit that way.

   render: function() {
      return (
         <div>
            { (window.history.length > this.myWindowHistoryStart) ? showBackButton : null }
         </div>
  }
});
```

More info on window.history:
https://developer.mozilla.org/en-US/docs/Web/API/Window/history

**Comment by giantelk** [comment]
Update: I tried the example above and fails. window.history.length isn't getting updated when going back with react-router's goBack() or with window.history.back(). I'm have `location: ReactRouter.HistoryLocation` set in ReactRouter.create(), also using Chrome on MacBook (in case that makes a difference).

**Comment by Lacerda** [comment]
I'm having some troubles with `goBack()`. How can I know  if the user hit the page directly in version 2.0.0?
Does it makes sense to make `goBack()` smarter like suggested in this issue?

I'm not sure if this is the correct place to put this question, with everything growing so fast, sorry in advance! :)

**Comment by s-ol** [comment]
I agree, this should be reopened as far as I can tell?

**Comment by gdenisov** [comment]
goBack does not seem to return the boolean as described above anymore. Issue should be reopened.

**Comment by timdorr** [comment]
Please open a new issue. Much of the discussion here is pre-1.0 and is no longer relevant.

**Comment by pke** [comment]
So is there actually a way to find out if `goBack` is available?

**Comment by gdenisov** [comment]
It does not seem that there is a method for that any longer. I ended up
just keeping a local log of previously navigated to url. If there is none
then the user just entered the site and should not be able to go back.

**Comment by nickvoronin** [comment]
Actually goBack returns boolean, but even when it returns false, it takes you back to the previous location, which seems to be buggy.

**Comment by trevordmiller** [comment]
It seems there is no longer functionality for a smart `goBack` in v4?

I'm trying to create a 404 page where it has a "Go home" button if user landed from outside the app, or "Go back" button if going back in history will keep them in the app:

```
const NoMatch = ({ history }) => {
  const canGoBackInsideApp = ???

  return (
    <View>
      <Text>404 error</Text>
      {canGoBackInsideApp
        ? <Button onClick={history.goBack}>
            Go back
          </Button>
        : <Link to="/">
           <Button>Go home</Button>
          </Link>
      }
    </View>
  )
}
```

Not sure what can be used for the `???` here; I've checked out the docs and the `goBack` function no longer returns a boolean, `history` no longer has a `canGoBack`, and `history.length` includes history from outside the app; I thought about grabbing the last location and checking `lastUrl.split("/")[0].contains("appRootOfUrl")`, but there seems to be no way of getting the last location without mutating history (there used to be a `history.entries` but this no longer exists as far as I can see in v4).

**Comment by rakibulalam** [comment]
```
dispatch => {
        return {
            canGoBack: () => {
                dispatch((window.history.length > 2 || document.referrer.length > 0 ? goBack(false) : push('/')))

            }
        }
```

**Comment by pke** [comment]
Not sure, but isn't the `window.history` for all URLs not only the current app ones? Or does it not contain URLs from other domains?

**Comment by btiwaree** [comment]
Hey @trevordmiller, did you figure out how to make `goBack` work?

**Comment by trevordmiller** [comment]
@btiwaree Nope - I’ve since started using Next.js instead of React Router: https://nextjs.org
