### ISSUE TITLE
Can I have the same route handler for two routes?

### ISSUE THREAD

**Issue by bernadetteguinan** [remix-run/react-router#410]
I have these two routes defined:

```
<Route name='register' handler={Register} >
    <Route name='registerpromotion' path='/registerpromotion/:promotionCode' handler={Register}/>
</Route>
```

So both routes use the same handler called Register.

In the case of the registerpromotion route, I pass in a property and in the case of the register route, I do not.

I could not get this to work - the promotionCode property is always undefined.

Does anyone know if you can use the same handler for two routes?

Many thanks!

**Comment by GurpreetSran** [comment]
Interesting, I actually tried this: 
 ```
<Route handler={AppRoot}>
     <Route name="projects" handler={Projects} >
         <Route name="experiments" path=":experiments" handler={Projects} />
     </Route>
</Route>
```

and this: 

 ```
<Route handler={AppRoot}>
     <Route name="projects" handler={Projects} />
     <Route name="experiments" path="/projects/:experiments" handler={Projects} />
</Route>
```

and it doesn't seem to work. The component doesn't update on URL change (hash change). Am I missing something?

**Comment by ilyai** [comment]
So is this possible to remount a component when navigating from one route to another which are handled by the same handler?
