### ISSUE TITLE
With optional params, should all links be "active"

### ISSUE THREAD

**Issue by rickharrison** [remix-run/react-router#429]
If I have a route like this:

```
<Route name="list" path="/path/?:param?" handler={require('./route')} />
```

my goal is to support the following urls:

```
/path
/path/filterOne
/path/filterTwo
```

On this route handler, I have a tab bar which can be used to switch between these 3 url's. When the path is at `/path` only the link to `/path` has the active class attached. However, when the url is `/path/filterOne` both the link to `/path/filterOne` _and_ `/path` have the active class attached.

Is this the expected behavior? or should the link without any params not have the active class (my desired behavior).

**Comment by rickharrison** [comment]
Do you have a suggestion on the best way to handle this when a child route is involved? I basically have one view with 3 possible filter toggles, and this view can display a modal. Here is one way of doing it:

```
<Route name="things-all" path="/things handler={Thing}>
  <Route path="modal" handler={Modal} />
</Route>

<Route name="things-filterOne" path="/things/filterOne handler={Thing}>
  <Route path="modal" handler={Modal} />
</Route>

<Route name="things-filterTwo" path="/things/filterTwo handler={Thing}>
  <Route path="modal" handler={Modal} />
</Route>
```

Is there a more condense way of defining this using `DefaultRoute` or some combination?

**Comment by rpflorence** [comment]
I have no idea when we'll get to this, but we eventually want to allow you to mount sub routes, which will give you this dynamic way to mount a set of routes anywhere else in a route hierarchy, but for now you have to repeat yourself a lot. You can of course, write some code to generate these kinds of routes if you'd like.
