### ISSUE TITLE
Method for reload all active routes data on client

### ISSUE THREAD

**Issue by klimashkin** [remix-run/react-router#431]
Hello!
It is very necessary to have method to reload all data on page, i.e. call willTransitionTo of all active routes (yes, we use willTransitionTo to fetch data from server, since there is no proper alternative).
For example, if the the user was offline and then connection restored, we must to request all data without location.reload()

**Comment by yaru22** [comment]
@rpflorence What API would that be and is it available now?

**Comment by gaearon** [comment]
While this is a different problem, if #658 gets merged, I think `router.refresh()` will do the thing you wanted.
