### ISSUE TITLE
Any example of Lazy loading route components with Webpack's require.ensure?

### ISSUE THREAD

**Issue by sanketsahu** [remix-run/react-router#463]
First of all, great work there!

As Webpack provides [require.ensure()](http://webpack.github.io/docs/code-splitting.html]) for code-splitting, any idea how to use that with the react-router so that I can lazy load all the components of the routes?

Please help!

**Comment by djanosik** [comment]
It seems the link is no longer working. Is there any other example?

**Comment by cody** [comment]
@djanosik 
The example is for 0.13 and can still be found here: https://github.com/rackt/react-router/tree/v0.13.3/examples/partial-app-loading
