### ISSUE TITLE
Testing React Components that use React-Router

### ISSUE THREAD

**Issue by an1lam** [remix-run/react-router#465]
I'm having issues getting Jest to deal with the react-router components. I tried the `makeStubbedDescriptor` method, suggested in [#437](https://github.com/rackt/react-router/issues/437) as displayed below:

```
/** @jsx React.DOM */
jest.dontMock('jquery');
jest.dontMock('../test_helpers.jsx');
jest.dontMock('../js/components/CategoryPage.jsx');

describe('Category Page', function() {
  var React = require('react/addons');
  var TestUtils = React.addons.TestUtils;
  var helpers = require('../test_helpers.jsx');
  var makeStubbedDescriptor = helpers.makeStubbedDescriptor;
  var CategoryPage = require('../js/components/CategoryPage.jsx');


  it('renders into the page correctly', function() {
    // Render the CategoryPage into the document
    var TestCategoryPage = makeStubbedDescriptor(CategoryPage, {});
    var page = TestUtils.renderIntoDocument(TestCategoryPage);

    expect($.ajax).toBeCalled();
    expect(div).toBeDefined();
  });
});
```

And getting the following error:

```
● Category Page › it renders into the page correctly
   - Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.
```

**Comment by curthoyt** [comment]
Jest is indeed complaining with the new code. There seems to be almost no way around this problem. What's more, your tests use a ton of "private" utility functions, so how could they possibly be of help to your users?

**Comment by SLonoed** [comment]
@rpflorence hi, this error still filed when test react components, that uses Link inside.

**Comment by rpflorence** [comment]
@SLonoed check out the new testing guide: https://github.com/rackt/react-router/blob/master/docs/guides/testing.md

**Comment by DannyAdmedo** [comment]
Hi Ryan,

The above guide really isn't clear at all. I'd recommend writing it in a bit more detail so it makes sense to the average user. Please remember when writing READMEs that your audience doesn't understand the architecture like you do.

An error I'm getting is "Unexpected token >" when including your script.

Regards

**Comment by bobeagan** [comment]
Dear Danny,

Patches welcome.

Sincerely,

**Comment by mjackson** [comment]
@DannyAdmedo That's probably the JS parser choking on your JSX. You probably want to check out React's [documentation on using JSX](http://facebook.github.io/react/docs/tooling-integration.html) and make sure you're correctly compiling JSX (either pre-compiling or compiling in the browser in a dev environment) before the JS parser gets it.

**Comment by ryanflorence** [comment]
> The above guide really isn't clear at all

You want more explanation about how `context` works? Or the concept of stubbing? What is unclear about it for you?

**Comment by rande** [comment]
@DannyAdmedo the code is using Ecma Script 6, here a javascript one: https://gist.github.com/rande/cbdd61017f4e2a83b2eb

**Comment by DelvarWorld** [comment]
I'm chewing through some of this, and having the issue that the component returned by `stubRouterContext`, when rendered into the document, doesn't have any of the methods of the Component that it wraps.

**Comment by DelvarWorld** [comment]
It does if I change the render method to:

    render: function() {
      return Component;
    }

and pass in a `<Component />` instead of `Component` however then I still get the error

    Required context `makePath` was not specified in `Link`. Check the render method of `HomeView`.

**Comment by kellyrmilligan** [comment]
````
TypeError: Cannot read property '_mockedReactClassConstructor' of undefined
````

I get this when trying to render the component after being stubbed out. 

````
var React = require('react/addons');
    var stubRouterContext = require('../../../../mock/stubRouterContext');
    var EpisodeTile = require('../../../../routes/shows/components/EpisodeTile');
    var mockState = require('../../../../mock/episodeDetailData');
    var StubbedComponent = stubRouterContext(EpisodeTile, {
      episode: mockState.data.selectedEpisode,
      season: mockState.data.selectedSeason,
      show: mockState.data.show
    });
    var TestUtils = React.addons.TestUtils;

    var episodeTile = TestUtils.renderIntoDocument(
      <StubbedComponent/>
    );
````
the stubb did get me closer though....

**Comment by alanrubin** [comment]
Also experiencing the same here:
```
TypeError: Cannot read property '_mockedReactClassConstructor' of undefined
```
Using react 0.12.2 + react-router 0.12.4 + jest-cli 0.4.0. Relevant files are here: https://gist.github.com/alanrubin/da3f740308eb26b20e70 . Any ideas ?

**Comment by alanrubin** [comment]
Ok, I was able to figure out what was the problem - it seems Jest was mocking the stubRouterContext require, so I have added it to the "unmockedModulePathPatterns" Jest configuration and the TypeError disappeared (alternatively you could call Jest.dontMock(...) in each test file as well). 

Also using ES6 in the stubRouterContext was causing issues (although I use Babel the file is not converted to ES5), so I converted it manually to ES5 (without lodash that was being used in a link above)

I have update the gist with the full solution (including my gulpfile.js syntax) - https://gist.github.com/alanrubin/da3f740308eb26b20e70 - hope that will be useful.

**Comment by mattnorris** [comment]
I'm running into the `undefined` issues as well. I've tried these approaches: 

- https://labs.chie.do/jest-testing-with-react-router/
- https://gist.github.com/alanrubin/da3f740308eb26b20e70

Is there a definitive example? All links to https://github.com/rackt/react-router/blob/master/docs/guides/testing.md I can find are broken.

**Comment by chiedojohn** [comment]
Hey again @mattnorris and whoever else. Ran into some more issues using my posted solution for jest testing with react-router. Currently, I've been having luck by instead adding the following to the top of my tests to ensure that react-router is mocked.

```js
jest.mock('react-router');
```

This is the first day I'm trying this but so far so good. Curious to see if other people have the same results.

**Comment by szalishchuk** [comment]
To anyone who happens to stuck with this problem.
Here's the setup that I've ended up with for my context dependent components (stripped down for simplicity, of course):
```
// dontmock.config.js contains jest.dontMock('components/Breadcrumbs')
// to avoid issue with hoisting of import operators, which causes jest.dontMock() to be ignored
import dontmock from 'dontmock.config.js';

import React from "react";
import { Router, createMemoryHistory } from "react-router";
import TestUtils from "react-addons-test-utils";

import Breadcrumbs from "components/Breadcrumbs";

// Create history object to operate with in non-browser environment
const history = createMemoryHistory("/products/product/12");

// Setup routes configuration.
// JSX would also work, but this way it's more convenient to specify custom route properties (excludes, localized labels, etc..).
const routes = [{
  path: "/",
  component: React.createClass({
    render() { return <div>{this.props.children}</div>; }
  }),
  childRoutes: [{
    path: "products",
    component: React.createClass({
      render() { return <div>{this.props.children}</div>; }
    }),
    childRoutes: [{
      path: "product/:id",
      component: React.createClass({
        // Render your component with contextual route props or anything else you need
        // If you need to test different combinations of properties, then setup a separate route configuration.
        render() { return <Breadcrumbs routes={this.props.routes} />; }
      }),
      childRoutes: []
    }]
  }]
}];

describe("Breadcrumbs component test suite:", () => {
  beforeEach(function() {
    // Render the entire route configuration with Breadcrumbs available on a specified route
    this.component = TestUtils.renderIntoDocument(<Router routes={routes} history={history} />);
    this.componentNode = ReactDOM.findDOMNode(this.component);
    this.breadcrumbNode = ReactDOM.findDOMNode(this.component).querySelector(".breadcrumbs");
  });
  
  it("should be defined", function() {
    expect(this.breadcrumbNode).toBeDefined();
  });
  
  /**
   * Now test whatever you need to
   */

```

**Comment by ThrowsException** [comment]
When rendering a child component in the router is there anyway to have this.props.route passed automatically? when I use this setup my this.props.route is undefined in my component

**Comment by bondarewicz** [comment]
@szalishchuk awesome tip! 👍 

Given that my component use:
```
LandingComponent.contextTypes = {
  router: PropTypes.object
};
```
and contains a button which redirects the user on click (calls below func)
```
redirect(mode) {
   this.context.router.push('/some_url/'+mode);
}
```

*Question: How can I test that on click the redirection occurs?*

**Comment by bondarewicz** [comment]
does below looks acceptable?

```
/**
 * Now test whatever you need to
 */
  
btn.simulate('click');

history.listen(function(ev) {
  assert(ev)
});

// test if redirect occured
function assert(ev) {
  console.log('listen', ev.pathname);
  expect(ev.pathname).toMatch('/some_url/mode');
}

**Comment by Luna2442** [comment]
Like @chiedo said, I used `jest.mock('react-router');`

I made another setup file which is pulled into jest config setup so its available for all files.
