### ISSUE TITLE
activeClassName not working

### ISSUE THREAD

**Issue by mxaly** [remix-run/react-router#471]
using React 0.12.0 when navigating, class to selected link is not added.

**Comment by areim3r** [comment]
@ryanflorence is there a way to set the activeClassName for the containing <li> ? its working fine so I didn't feel it was worth opening a new issue but say for bootstrap pills navigation, you set the active class on the <li> not the <a>, which means that by default the bootstrap active class won't work. there is [https://github.com/insin/react-router-active-component](this) component which is supposed to do that but it seems it doesn't work as of react-router v1.0
