### ISSUE TITLE
Recommended way to set document.title?

### ISSUE THREAD

**Issue by sophiebits** [remix-run/react-router#49]
Is there a recommended way to set document.title upon routing? I suppose one could just set it in all of the componentDidMount handlers, but it might be nice if there was a general strategy for this. (For example, maybe one page doesn't really care about title, in which case we'd want to fall back to the default.)

(Someone was also asking in IRC about this last night right after you left, @rpflorence.)

**Comment by rajeshkw** [comment]
```
class Layout extends React.Component {
  constructor(props){
    super(props);
    document.title = this.props.title;
  }
  render(){
    return(
      <div>
        <Header active={this.props.active} />
        { this.props.children }
        <Footer />
      </div>
    );
  }
}
```

then <Layout title="My Title"/> it works!

**Comment by Aeonrush** [comment]
Hi @rajeshkw 
I found better solution, that works with fetching data and Redux
```javascript
import React from 'react';

export default class Layout extends React.Component {
  constructor(props){
    super(props);
  }
  componentWillUpdate(nextProps) {
    document.title = nextProps.title;
  }
  render(){
    return null;
  }
}
```

**Comment by marcogreselin** [comment]
How do you do this in stateless functional components? I tried this but it doesn't work:
`ComponentName.componentDidMount = () => document.title = "Who's Marco?"`

**Comment by tmkasun** [comment]
@marcogreselin , As I know we can't create lifecycle hooks in a stateless functional component, These functional components don't have backing instances, and do not have the component lifecycle methods too. So better to convert it to stateful class style component.

**Comment by ssmith-wombatweb** [comment]
@marcogreselin not sure if it's the right way but I believe you can do something like this.

```
export const Life = ({sayHello="Ciao"}) => {
  document.title='Your title.';
  return (
    <Your JSX>
  );
}
```

**Comment by swapnil95** [comment]
Another alternative - https://github.com/kodyl/react-document-meta

**Comment by liamm12** [comment]
When you want to change the title from React components, you can use [React Helmet](https://github.com/nfl/react-helmet), a third party library.

https://github.com/nfl/react-helmet
