### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defaultProps' of undefined 

### ISSUE THREAD

**Issue by jeberly** [remix-run/react-router#512]
I am sure this is something simple I am missing, but after upgrading and following the shared root example (https://github.com/rackt/react-router/blob/master/examples/shared-root/app.js) I keep getting Uncaught TypeError: Cannot read property 'defaultProps' of undefined 

Any help for what to look for would be appreciated.

Thanks, John

**Comment by gs-akhan** [comment]
Or use Babelify for better good. .. :)
