### ISSUE TITLE
Path matching for path that ends with question mark

### ISSUE THREAD

**Issue by all-you-need-is-laugh** [remix-run/react-router#517]
I stack with some problem using simple routes hierarchy below:

``` html
<Route name="login" handler={DefaultLayout}>
    <DefaultRoute handler={LoginPage}/>
    <NotFoundRoute handler={NotFound}/>
</Route>
```

But router matches paths differently on server and client, when I use question mark in address (not Route's "path" property):

| Path | Server | Client |
| --- | --- | --- |
| /login | LoginPage | LoginPage |
| /login/a | NotFound | NotFound |
| /login?a=1 | LoginPage | LoginPage |
| /login?a | LoginPage | LoginPage |
| /login? | **NotFound** | **LoginPage** |

I don't know is it a bug or I just have to set "path" property of <Route name="login" /> with some specific value.

**Comment by komocode** [comment]
Chiming in. This happens when I'm using gulp-connect.

It works fine if you're using the deprecated way
`````
Router.run(routes, function (Handler) {
  React.render(<Handler/>, document.body);
});
`````
Which has a /#/ in the URL

But if you're using 
`````
Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(<Handler/>, document.body);
});
`````
Which removes the /#/, having a question mark in the suffix of the URL will cause it to not be found.
