### ISSUE TITLE
Async data and Flux stores

### ISSUE THREAD

**Issue by ksesong** [remix-run/react-router#530]
I am using the Flux architecture. Each time I visit a page, the page requests data from a Store, but as the action is created (eg. REQUEST_TODO), there is no explicit callback triggered, but another action will be  created once the request is completed (eg. REQUEST_TODO_COMPLETED).

I am trying to implement something similar to (https://github.com/rackt/react-router/blob/master/docs/api/run.md or https://github.com/rackt/react-router/blob/master/examples/async-data/app.js), I get the principles, but I struggle adapting with the concept of actions. Should I consider my actions differently, by adding some sort of callback, but this would make the dataflow more complex?

I am just starting, so this is likely I have missed something.
Thanks

**Comment by wmyers** [comment]
@gaearon thanks for this technique.

I have a login with an async call to fetch user data with a token (which might be stored locally). I'm using the `observeStore` in a `willTransitionTo` for a page that requires authentication as follows.

```javascript
 static willTransitionTo(transition, params, query, callback) {
      if (!LoginStore.isLoggedIn()) {
        //store next path in RouterStore for redirecting after authentication
        let transitionPath = transition.path;
        RouterActionCreators.storeRouterTransitionPath(transitionPath);

        //check if still waiting for a user data request
        observeStore(LoginStore, s => !s.isRequestingUserData())
        .then(() => {
          if (!LoginStore.isLoggedIn()) {
            transition.redirect('/login');
          }
        })
        .finally(callback);
      }else{
        callback();
      }
    }
```
