### ISSUE TITLE
ReactCSSTransitionGroup does not work anymore with the new RouteHandler

### ISSUE THREAD

**Issue by johanneslumpe** [remix-run/react-router#531]
Since the new api, a component nested in a `ReactCSSTransitionGroup` does not receive the appropriate classes on its DOM node if it is wrapped within a `RouteHandler`, since `ReactCSSTransitionGroupChild` expects the child to not be wrapped. I'm not sure yet how to approach this issue, just wanted to bring it up.

**Comment by mtford90** [comment]
Hey @johanneslumpe, @rpflorence.

Just came across this whilst attempting to figure out how to use animations with the router. I'm relatively new to React and this router library. Would one of you mind explaining why adding the key works? 

Cheers!
