### ISSUE TITLE
Use standard Promise, drop When

### ISSUE THREAD

**Issue by klimashkin** [remix-run/react-router#542]
Hello!
Why do we need [when](https://github.com/cujojs/when)?
Developers prefer different implementation of Promises/A+. For example, we prefer Bluebird
But for client, I think better to use standard [Promise](http://caniuse.com/#search=Promise) to decrease bundle size with small [polyfill](https://github.com/jakearchibald/es6-promise). In any case, it is better not to impose a particular library

**Comment by nelix** [comment]
Seems like a very round about way of doing things. Personally I want babel to polyfill promises for me.
