### ISSUE TITLE
Question - Nesting route with DefaultRoute

### ISSUE THREAD

**Issue by Javey** [remix-run/react-router#554]
I have a route setting like this

```
    <Route path="/" handler={Main}>
        <Route name="nutrition" path="nutrition" handler={Nutrition}>
            <Route name="nutritionDay" path="day" handler={NutritionDay}/>
            <Route name="nutritionWeek" path="week" handler={NutritionWeek}/>
        </Route>
        <DefaultRoute handler={NutritionDay} />
    </Route>
```

`NutritionDay` will be executed when it has matched `DefaultRoute` . But it's parent route `nutrition` does not be executed.

**Comment by bizmurr** [comment]
@Javey @ryanflorence any answers for this?

How would you get `nutrition/nutritionDay` to render at `/`?

**Comment by bizmurr** [comment]
Ah hah, @mjackson answered it: #867 

> What I mean is that if you have a `<DefaultRoute>` and you feel like it needs children, you should probably just make it a regular `<Route>`, e.g.

```xml
<Route handler={App}>
  <DefaultRoute handler={Dashboard}/>
</Route>
```

> becomes

```xml
<Route handler={App}>
  <Route handler={Dashboard}>
    <DefaultRoute handler={Inbox}/>
    <Route name="feed" handler={NewsFeed}/>
  </Route>
</Route>
```

---

So in this case, I believe it would be something like:

```xml
<Route path="/" handler={App}>
  <Route handler={Nutrition}>
    <DefaultRoute handler={NutritionDay} />
  </Route>
</Route>
```
