### ISSUE TITLE
Server rendering

### ISSUE THREAD

**Issue by simenbrekken** [remix-run/react-router#57]
[Route.spec.js](https://github.com/rpflorence/react-nested-router/blob/master/specs/Route.spec.js#L112) contains a commented out test for server rendering but it seems, server rendering would at least require exposing `findMatches` in the main module. 

Any plans for reintroducing server rendering support?

**Comment by pedronauck** [comment]
Hey @ryanflorence, the same that ocurred with @th0r throw is ocurring here. That error makes a 500 throw on server routes...

```
ReferenceError: window is not defined
```

**Comment by burakcan** [comment]
Hello, 
I found a way to render on the server with desired data. I don't have time to document is but the idea is basically: 
1) Generate a route list
2) Spawn a temporary server that serves your app
3) Visit every route in the list with `jsdom` https://www.npmjs.com/package/jsdom
4) Throw an event from your app whenever it feels it's ready to be rendered
5) Listen that event in jsdom and get the html when the event is fired
