### ISSUE TITLE
Circular dependencies in a Flux app

### ISSUE THREAD

**Issue by merk** [remix-run/react-router#575]
The documentation that suggests how to set up the Router in a flux application seems to end up with a browserify/require circular reference:

https://github.com/rackt/react-router/blob/master/docs/guides/flux.md

If you have a Handler that will call SomeActions.doSomeTransitionThing() the router returned in the require() call in SomeActions will be null/undefined.

Am I missing something with regards to how SomeActions will be called if it depends on the router?

**Comment by bezreyhan** [comment]
@rpflorence do you mind elaborating on what you mean by creating an app container?

rickharrison's method worked but you mentioned that you can get by without the get and set methods. Thanks.

**Comment by gaearon** [comment]
>@rpflorence do you mind elaborating on what you mean by creating an app container?

I think something in this vein https://github.com/rpflorence/create-container
