### ISSUE TITLE
Run without node

### ISSUE THREAD

**Issue by max-mykhailenko** [remix-run/react-router#580]
Can you add builded version of module for using in browser without `require(...)` like React?

**Comment by stevermeister** [comment]
@max-mykhailenko 
thank you for your last message!

**Comment by thiagolocatelli** [comment]
using the following build: https://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.3/ReactRouter.js

var Route = ReactRouter.Route;
var Router = ReactRouter.Router;
var DefaultRoute = ReactRouter.DefaultRoute;
var RouteHandler = ReactRouter.RouteHandler;
var Handler = ReactRouter.Handler;

Router.run(routes, function (Handler) {
  React.render(<VisualGuide/>, document.body);
});

it gives me: Uncaught TypeError: Cannot read property 'run' of undefined

Any ideas?

**Comment by Eagllus** [comment]
Maybe I'm doing something wrong but I get the react-router from the cdn and when I do
```
import React from 'react'
import { Router, Route, Link } from 'react-router'

console.log(Router);

....
React.render((
  <Router>
    <Route path="/" component={App}>
      <Route path="about" component={About}/>
      <Route path="users" component={Users}>
        <Route path="/user/:userId" component={User}/>
      </Route>
      <Route path="*" component={NoMatch}/>
    </Route>
  </Router>
), document.body)
```
this code is from the `README.md`

the console.log returns `undefined`
