### ISSUE TITLE
React component context is not passed down to subroutes

### ISSUE THREAD

**Issue by luigy** [remix-run/react-router#60]
> context is determined by where a component is created ~~(in your mount() function)~~, not where it is rendered (in your App component). Also note that context is experimental and likely to change in future versions. -- [@spicyj](https://github.com/facebook/react/issues/1634#issuecomment-44790643)

Context is not passed down to subroutes, because [the handler component is created outside the rendering component.](https://github.com/rpflorence/react-nested-router/blob/master/modules/components/Route.js#L444)

Thoughts on having access to `activeRouteHandler` & `activeRouteProps` or some function to create the component explicitly?

**Comment by derekdowling** [comment]
What ever happened with this?
