### ISSUE TITLE
Refresh gives 404 error on webpack v4 production build for react router v4

### ISSUE THREAD

**Issue by prepaka** [remix-run/react-router#6329]
I am using React-Router v4 version along with Webpack v4 in my application and running the application in SailsJS. When I ran my application in Webpack dev mode, it is running properly and even if I refresh the page it loads the same page properly. So, I don't have any problem with Webpack dev mode.

I am facing issue with Webpack production mode. When I build my application in production mode and using SailsJS if I open the application the UI is showing properly, but when I refresh the page I am getting following error

**This localhost page can’t be found
No webpage was found for the web address: http://localhost:1340/ida/views
HTTP ERROR 404**

Here is my code
**Samplecontainer.js**

import React, { Component } from 'react';
import {
  Router, Route, Switch, Redirect
} from 'react-router-dom';
import { injectIntl, intlShape } from 'react-intl';
import App from 'grommet/components/App';
import Split from 'grommet/components/Split';
import ViewComponent from './viewpage/ViewComponent';
import HeaderPanel from './common/HeaderPanel';
import '../../scss/index.scss';

class sampleContainer extends Component {
  render() {
    const rootUrl = 'ida';
    return (
      <Router history={this.props.history}>
        <App inline={true} centered={false}>
          <Split flex="right" priority="left" className="main-frame">
            <NavigationSidebar
              loggedInUser={barUser}
              historyProvider={this.props.history}>
            </NavigationSidebar>
            <div className="hercules-page ida-page">
              <HeaderPanel />
              <Switch>
                <Route exact path="/" render={() => (<Redirect push to={`${rootUrl}/views`} />)} />
                <Route exact path={rootUrl} render={() => (<Redirect push to={`${rootUrl}/views`} />)} />
                <Route path={`${rootUrl}/views`} component={ViewComponent} />
              </Switch>
            </div>
          </Split>
        </App>
      </Router>
    );
  }
}

sampleContainer.propTypes = {
  intl: intlShape.isRequired
};

export default (injectIntl(sampleContainer));

**ViewComponent.js**

import React, { Component } from 'react';
import { Route, Switch, withRouter } from 'react-router-dom';
import Box from 'grommet/components/Box';
import ViewListPage from './viewslist/ViewListPage';

class ViewComponent extends Component {
  render() {
    return (
      <Box pad={{ horizontal: 'small', vertical: 'small' }} direction="column" colorIndex="neutral-4">
        <Switch>
          <Route exact path={`${this.props.match.path}`} component={ViewListPage} />
        </Switch>
      </Box>
    );
  }
}
export default withRouter(ViewComponent);

**Webpack.config.js**
const path = require('path')
const webpack = require('webpack')
const merge = require('webpack-merge');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

const devMode = process.env.NODE_ENV !== 'production';
var envParams = require('./webpack.params').getEnv(process.env.NODE_ENV);

const commonConfig = {
    entry: [
        'whatwg-fetch', // necessary for loading with IE11
        "babel-polyfill", // To work in IE 11
        "./client/js/index.js",
    ],
    output: {
        filename: devMode ? '[name].js' : 'js/[name].[contenthash:8].js',
        chunkFilename: devMode ? '[name].js' : 'js/[name].[contenthash:8].js',
        path: path.join(__dirname, '.tmp/public'),
        publicPath: '/'
    },
    plugins: [
        new webpack.DefinePlugin(envParams),
        new HtmlWebpackPlugin({
            inject: true,
            template: 'client/index.ejs',
            filename: 'index.html',
            minify: {
                collapseWhitespace: true,
                removeComments: true,
                removeRedundantAttributes: true,
                useShortDoctype: true,
                removeEmptyAttributes: true,
                removeStyleLinkTypeAttributes: true,
                keepClosingSlash: true,
                minifyJS: true,
                minifyCSS: true,
                minifyURLs: true,
            },
        }),
    ],
    target: 'web',
    resolve: {
        extensions: [
            '.js',
            '.scss',
            '.css',
            '.json'
        ],
        modules: [
            'node_modules',
            'node_modules/@micro-focus'
        ],
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env', 'stage-0', 'react']
                    }
                }
            },
            {
                test: /\.(sa|sc|c)ss$/,
                use: [
                    devMode ? { loader: 'style-loader' } : MiniCssExtractPlugin.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            minimize: true,
                        },
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                            minimize: true,
                            outputStyle: 'compressed',
                            includePaths: [
                                './node_modules',
                                './node_modules/@micro-focus',
                            ]
                        }
                    }
                ]
            }
        ]
    }
}

const devConfig = {
    devtool: 'cheap-module-source-map',
    mode: 'development',
    entry: [
        'webpack/hot/dev-server',
    ],
    devServer: {
        port: 8081,
        historyApiFallback: true,
        hot: true,
        inline: true,
        compress: true,
        clientLogLevel: 'error',
        open: true,
        openPage: 'ida/',
        publicPath: '/',
        quiet: true,
        disableHostCheck: true,
        contentBase: path.resolve('.tmp/public'),
        },
    },
    plugins: [
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin(),
    ]
}

const prodConfig = {
    mode: 'production',
    bail: true,
    optimization: {
        runtimeChunk: false,
        minimizer: [
            new UglifyJSPlugin({
                sourceMap: false,
                compress: {
                    warnings: false,
                    comparisons: false,
                  },
                  mangle: {
                    safari10: true,
                  },
                  output: {
                    comments: false,
                    ascii_only: true,
                  }
            }),
        ],
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /[\\/]node_modules[\\/]/,
                    name: 'vendors',
                    chunks: 'all',
                },
            },
        }
    },
    plugins: [
        new webpack.optimize.OccurrenceOrderPlugin(true),
        new OptimizeCSSAssetsPlugin(),
        new MiniCssExtractPlugin({
            filename: 'css/[name].[contenthash:8].css',
            chunkFilename: 'css/[name].[contenthash:8].css'
        }),
        new webpack.optimize.AggressiveMergingPlugin(),
    ]
}
if (process.env.MODE === 'analysis') {
    commonConfig.plugins.push(new BundleAnalyzerPlugin());
}
module.exports = (devMode ? merge(commonConfig, devConfig) : merge(commonConfig, prodConfig));

**Versions using in the project**
"react": "^16.4.1",
"react-dom": "^16.4.1",
"react-intl": "^2.4.0",
"react-redux": "^5.0.7",
"react-router-dom": "^4.3.1",
"react-router-redux": "^4.0.8",
"webpack": "^4.14.0",

I observed that if I open my application in production mode like "localhost:<port>" then it is working fine, but if I tried to open the direct route page which already defined in my routing like "http://localhost:<port>/ida/views" then I am getting 404 error. That means react router is identifying "/" only. 

Please let me know how I can fix the refresh issue in webpack production mode for react-router

**Comment by The-Code-Monkey** [comment]
this is an nginx issue replace your location with this 
`location / {
    try_files /index.html =404;
}`
