### ISSUE TITLE
[Urgent]Can NOT match 'http://abc.com?trackingid=abc123'

### ISSUE THREAD

**Issue by camsong** [remix-run/react-router#636]
I tried to use 
`
<Route name='app' handler={App} path='*' />
`

`*` is supposed to match anything, but it can not match the url in title, and it will make a redirection to 
http://abc.com#/ and lost the `debug` parameter. which is quite unfortunate.
I'm deadly need to fix this in my PRODUCTION env, thanks for your help guys.

**Comment by saulshanabrook** [comment]
Are query strings still persisted on changing links?
