### ISSUE TITLE
Feature Request: Redirect callback

### ISSUE THREAD

**Issue by haxxxton** [remix-run/react-router#6484]
**Synopsis**

It would be great to be able to pass a prop to `<Redirect />` that would allow a callback to be fired when the redirect occurs.

----

**Suggested prop name and arguments**

`onRedirect` which would return the following information `(willPerformRedirect: boolean, to: string | object, push: boolean)`.

- *willPerformRedirect* is the result of `locationsAreEqual(prevProps.to, location)`
- *to* is the redirect `to` prop passed back to the callback
- *push* is the redirect `push` prop passed back to the callback

----

**Motivation**

I have a scenario where I am rendering a series of links that update some urlParameters that in turn renders a scene. You can imagine this series of links like 'tabs' within a route. Some of these tabs are access controlled by a list of permissions i am managing about a particularly user. As such, I generally link to the route with a urlParameter of 'default', which my tabs recognise as an indicator that they should determine if the user can see at least one of the tabs, and redirect to that ('default' is then replaced with 'general', for example). It would be great to be able to determine, when this "redirect to default" action actually takes place, so that i can perform some subsequent actions without having to take snapshots of the passed in `computedMatch` and do comparisons.

I am sure there are other use cases, where being able to be notified of a redirect occurring would be useful, this is just my immediate experience.

Comments/Criticisms/Other work arounds welcome :)

**Comment by timdorr** [comment]
I'm not sure I'm understanding your use case here. It sounds like your rendering only works correctly when coming in from this redirect, which in turn sounds like an imperative style. In general, your components shouldn't care how they came to be, just with whatever the current props are. That's a declarative style, which jives with how React works and makes for good, sustainable code. 

At the very least, whenever you determine you're going to render a Redirect, that would be the point at which you can signal out some sort of preparatory action to your system that one is about to occur. No callback API needed.

**Comment by haxxxton** [comment]
@timdorr apologies if my use case isnt explained correctly. Trying to distill it down without specifics is difficult. Assume for the moment a different use case.

if that callback were to want to update a state value on the component that was rendering the Redirect when it performs its redirect, it is my understanding that calling the setState directly in the render method is something of an anti-pattern/frowned upon. However, providing it as part of a callback, for when a subsequent action occurs is performed is okay. If this still an anti-pattern?

Similarly this could be useful when a Redirect is rendered as a child of a Switch for the purposes of logging attempts to access old routes, i think?
