### ISSUE TITLE
useRouteMatch not exported

### ISSUE THREAD

**Issue by smmoosavi** [remix-run/react-router#7133]
## Version
```
=> Found "react-router@6.0.0-alpha.1"
=> Found "react-router-dom@6.0.0-alpha.1"
```

## Test Case

I can't find `useRouteMatch` in https://unpkg.com/browse/react-router-dom@6.0.0-alpha.1/react-router-dom.js

```ts
import { useRouteMatch } from 'react-router-dom';
         ^^^^^^^^^^^^^
```

maybe it is a documentation bug and should be fixed in [migration guid](https://github.com/ReactTraining/react-router/blob/dev/docs/guides/migrating-5-to-6.md#what-did-we-miss).

**Comment by timdorr** [comment]
The migration path is shown under the relative routes section.

**Comment by smmoosavi** [comment]
It's not about relative routes migration.

`useRouteMatch` is needed to detect active tab

```js

// parent route is <Route path="/some-page/*" element={<Child />} />
// Child:
const match = useRouteMatch(':tab') // relative to parent route
const tab = match ? null : match.params.tab
// @material-ui/core tab
<Tabs value={tab}>
  <Tab
    component={Link} // react router link
    value="one" // used for tab
    to="one" // used for link
  />
  <Tab component={Link} value="two" to="two" />
</Tabs>
<Routes>
  <Route path="one" element={<One />} />
  <Route path="two" element={<Two />} />
  <Redirect path="/" to="one" />
</Routes>

```

**Comment by helenhayley** [comment]
Is there a fix for this? I'm going down a version because of this issue.

**Comment by timdorr** [comment]
If someone wants to make a PR, we can look into adding it or an equivalent back.

**Comment by xsteadybcgo** [comment]
I come across the same problem when processing my typescript-react project, I think it is a issue about the @types/react-router-dom,  now I can fix it with `import { useRouteMatch } from 'react-router' ` instead , either other router hooks!

**Comment by smmoosavi** [comment]
> If someone wants to make a PR, we can look into adding it or an equivalent back.

#7142

**Comment by o-alexandrov** [comment]
Not stale

**Comment by vjpr** [comment]
So currently there is no way to get the matched route from the component. 

You could do something like the following as a workaround, but its hacky...

```
const match = useRoutes([{path: ':tab'}]) // relative to parent route
console.log(match.props.value.tab) // will return the param tab
```

`match.props.value` also gives you the other params in the entire path which could be useful for breadcrumbs.

```
// parent route is <Route path="/some-page/*" element={<Child />} />
```

Also:

`useParams` contains `{'*': 'the child page'}`, so you could modify your parent route to include another param to match with this.

---

`useMatch(':tab')` does seem like it is suppose to solve your use case though, but it requires you to write the full path, not relative to parent. This is unexpected given the description.

> Returns match data about a route at the given path relative to the current location.

**Comment by benneq** [comment]
@vjpr 
> const match = useRoutes([{path: ':tab'}]) // relative to parent route
> console.log(match.props.value.tab) // will return the param tab

I guess It should be `match.props.value.params.tab`. Then it works! 👍 

And this is at least much more usable than my hacky workaround...
<details>
  <summary>Spoiler: The ugly piece of code</summary>

```
const MyTabs = () => {
  const { tab } = useParams();

  return (
    <Tabs value={tab}>
      <Tab component={Link} to="../tabname1" label="Label 1" value="tabname1" />
      <Tab component={Link} to="../tabname2" label="Label 2" value="tabname2" />
    </Tabs>
  );
}

const MyComponent = () => {
  return (
    <>
      <Routes>
        <Route path=":tab/*" element={<MyTabs />} />
      </Routes>
      <Routes>
        <Route path="tabname1" element={<TabContent1 />} />
        <Route path="tabname2" element={<TabContent2 />} />
      </Routes>
    </>
  )
}
```
</details>

Anyways, I totally agree with your other points and concerns!

**Comment by uptonking** [comment]
- in v6, [useMatch](https://github.com/ReactTraining/react-router/blob/dev/docs/api-reference.md#usematch)  can replace [useRouteMatch of v5](https://reactrouter.com/web/api/Hooks/useroutematch)
- their parameters are the same

**Comment by rfcota** [comment]
Is there any update on this thread? I used to use `useRouteMatch` to build breadcrumbs. `useMatch` needs a pattern, it doesn't makes sense to me to use `useMatch` if you need to know the exact pattern that the route should match to. 
![image](https://user-images.githubusercontent.com/30241128/127927347-788dd4c3-36fe-4bcf-8a6d-0e73e732ada0.png)

I.E. I need to get the route match for `/users/...` What am I supposed to do? `/*/*/users/:userID`?

**Comment by chaance** [comment]
If anyone is still having issues with `useMatch` as a replacement for `useRouteMatch`, I'd like to help. If you do and can spin up a CodeSandbox that illustrates the problem, I'll take a look next week,

**Comment by chaance** [comment]
I'm going to close this, as the official recommendation is to `useMatch` in place of `useRouteMatch`. If you have issues with that, please open a new issue so we can help!

**Comment by eps1lon** [comment]
> I'm going to close this, as the official recommendation is to `useMatch` in place of `useRouteMatch`. If you have issues with that, please open a new issue so we can help!

@chaance FYI the [migration docs](https://reactrouter.com/docs/en/v6/upgrading/v5) do not mention `useRouteMatch` is gone. They even explicitly say to use it:

> Replace any <Route>s that are not inside a <Switch> with useRouteMatch, or wrap them in a <Switch>

-- https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v51

**Comment by chaance** [comment]
@eps1lon that specific note is about updating to 5.1 *before upgrading to v6,* but larger point taken! I'll create a separate issue to update the docs.

**Comment by igorpupkinable** [comment]
I am just left with the last component to upgrade to v6. Can anyone help with `useRouteMatch` please?

Fallback route v5 component:
```
import React from 'react';
import type {
  FC,
} from 'react';
import {
  Redirect,
  Route,
  useRouteMatch,
} from 'react-router-dom';
import type {
  RouteProps,
} from 'react-router-dom';

export type FallbackRouteProps = RouteProps & {
  to: string;
};

const STATE = {
  isRedirect: true,
};

/**
 * @visibleName Route.Fallback
 */
const FallbackRoute: FC<FallbackRouteProps> = ({
  to: pathname,
  ...rest
}) => {
  const {
    path,
  } = useRouteMatch();

  return (
    <Route
      {...rest} // eslint-disable-line react/jsx-props-no-spreading
      path={path}
    >
      <Redirect
        to={{
          pathname,
          state: STATE,
        }}
      />
    </Route>
  );
};

export default FallbackRoute;
```

Fallback route v6 component:
```
import type {
  FC,
} from 'react';
import {
  Navigate,
  Route,
  useRouteMatch,
} from 'react-router-dom';
import type {
  RouteProps,
} from 'react-router-dom';

export type FallbackRouteProps = RouteProps & {
  to: string;
};

const STATE = {
  isRedirect: true,
};

/**
 * @visibleName Route.Fallback
 */
const FallbackRoute: FC<FallbackRouteProps> = ({
  to,
  ...rest
}) => {
  const {
    path,
  } = useRouteMatch(); <== what should I use here? useMatch is not the same.

  return (
    <Route
      {...rest} // eslint-disable-line react/jsx-props-no-spreading
      path={path}
    >
      <Navigate
        replace
        state={STATE}
        to={to}
      />
    </Route>
  );
};

export default FallbackRoute;
```
