### ISSUE TITLE
[v6-alpha.3] Route with empty path does not render nested route with empty path

### ISSUE THREAD

**Issue by amarczinek** [remix-run/react-router#7239]
## Version

6.0.0-alpha.3

## Test Case

```
<BrowserRouter>
  <Routes>
    <Route path="" element={(
        <Outlet />
      )}>
       <Route path="imprint" element={<p>Imprint</p>} />
       <Route element={<p>Landing Page</p>} />
    </Route>
  </Routes>
</BrowserRouter>
```

## Steps to reproduce

Launch the application and visit the root page and the imprint page.

## Expected Behavior

Going on the "root" page does render the "Landing Page".
Going on the "imprint" page does render the "Imprint Page".

## Actual Behavior
Going on the "root" page does NOT render the "Landing Page".
Going on the "imprint" page does render the "Imprint Page".

**Comment by SevenOutman** [comment]
Same problem here. The use case is to render a common layout component for all routes, then a route component for index path.

```jsx
<Route path="" element={<Layout />}>
  <Route path="" element={<IndexPage />} /> // this never renders
  <Route path="login" element={<LoginPage />} />
</Route>
```

**Comment by NormySan** [comment]
I'm having this issue as well. I've put up a simple codesandbox illustrating the issue.
https://codesandbox.io/s/react-router-6-issue-kkbr0

**Comment by ksmzn** [comment]
I faced the same problem.

I've solved it as a makeshift like this, but it looks ugly.
Does anyone have other solutions?

```
<Route path="/" element={<Layout><IndexPage /></Layout>} />
<Route path="/" element={<Layout><Outlet /></Layout>}>
  <Route path="login" element={<LoginPage />} />
</Route>
```
Full example: https://codesandbox.io/s/react-router-6-issue-3oh1f

**Comment by aloker** [comment]
I'm having the same issue. @ksmzn Thanks for the workaround. It's not beautiful but it keeps me going.

**Comment by kcsujeet** [comment]
any updates on this issue?

**Comment by eliseumds** [comment]
Ye, it's a shame that doesn't work anymore. An alternative is to write your own version of `matchRoutes`, but then you wouldn't be able to write your routes in JSX.

**Comment by chaance** [comment]
This should be fixed in the latest beta! https://codesandbox.io/s/react-router-6-issue-forked-dvp01?file=/src/App.js
