### ISSUE TITLE
[v6] Path ranking - :splat beats * on same level with nested <Routes> with exact match

### ISSUE THREAD

**Issue by davnicwil** [remix-run/react-router#7423]
## Version

6.0.0-alpha.5

## Test Case

https://codesandbox.io/s/zealous-spence-v71fy

## Steps to reproduce

I have a sub-route, `/sub` which has some static routes beneath it like `/sub/static-1`, `/sub/static-2` that I want to render under a shared layout.

Anything else under `/sub` I want to dynamically pull out as a path param (splat) as an input to render a different page, not under that shared layout.

I've noticed that when I configure my Routes nested directly and use an `<Outlet />`, this works fine! For instance:

```
<Route path="sub/*" element={<LayoutUsingOutlet />}>
  <Route path="static-1" ... <-- /sub/static-1 matches here
  <Route path="static-2" ...
</Route>
<Route path="sub/:splat" ... <-- /sub/foo matches here

...

const LayoutUsingOutlet = () => (
  <div>
    ...shared stuff that shouldn't re-render on each navigation...

    </Outlet>
  </div>
)
```

However, if I try to do this by embedding `<Routes>` into the shared layout (which I would prefer to do, rather than use `<Outlet />`, for the organisation of this particular code) as in the linked code sandbox, it doesn't work - the splat route always 'wins'. Navigating to `/sub/static-1` for instance renders the splat route with the path param value as `"static-1"`.

This seems like a possible bug in the path ranking for the nested `<Routes>` pattern? My assumption is that this pattern vs directly nested routes with `<Outlet>` is a matter of style and there should be no functional difference between them, but please disregard if I have this wrong and it's intentional behaviour.

## Expected Behavior

Both styles described above behave the same - they both always rank an exact match above a splat on the same sub route.

## Actual Behavior

The direct nesting with `<Outlet />` style ranks wildcard-nested exact match routes above the splat on the same level as the wildcard (this is the desired behaviour). The deep nesting `<Routes>` style does not, the splat on the same level as the wildcard always wins.

**Comment by davnicwil** [comment]
Just bumping this to prevent it from getting auto-closed

**Comment by timdorr** [comment]
I added the fresh label so it doesn't go stale.

**Comment by brophdawg11** [comment]
This is unavoidable since when you put the static routes down inside a nested component via `<Routes>` - the router does not know they exist until it renders the component.  

So at the time of matching `/sub/static-1` react router is only aware of:

```jsx
<Route path="sub/*" />
<Route path="sub/:splat" />
```

So it will always match the param if there is only a single URL segment after `sub/`.  It can't know _what_ specific routes are down inside the splat.
