### ISSUE TITLE
[v6] `Link` component `to` prop can no longer receive function

### ISSUE THREAD

**Issue by OliverJAsh** [remix-run/react-router#7465]
In v5 we could pass a function (which would receive a `location` param) to the `to` prop. This no longer seems to be supported in v6, judging by the types:

https://github.com/ReactTraining/react-router/blob/262b45dd8d6cbdc3a984259c5591ffc3de80d600/packages/react-router-dom/index.tsx#L229

There doesn't seem to be any mention of this breaking change in the migration guide? Is it intentionally left out or do you plan to restore it for v6? FWIW I found this very useful, so that components don't have to manually read the location. IIRC there is more justification for this feature in the PR which initially added it in v5.

https://github.com/ReactTraining/react-router/pull/5368
https://github.com/ReactTraining/react-router/issues/5331

**Comment by smashercosmo** [comment]
Oh, no, not again 🤦🏻‍♂️ Last time it took two years to merge my PR for v5, which implemented this functionality.

**Comment by timdorr** [comment]
Can we get a PR to add it back? V6 is a rewrite, which is why it didn't come over.

**Comment by OliverJAsh** [comment]
We should keep this open because it represents a breaking change and many people could be effected.

**Comment by mjackson** [comment]
You needed this in v5 because we didn't have hooks back then, so the router had to give you function props so you could access the router's state. In this case, you needed to set the `<Link to>` value based on the current location.

In v6, this is really easy to do yourself:

```tsx
import type { Location } from "history";
import { useLocation } from "react-router-dom";

interface MyLinkProps extends Omit<LinkProps, "to"> {
  to(location: Location): string;
}

function MyLink({ to: toCallback, ...props }: MyLinkProps) {
  let location = useLocation();
  return <Link to={toCallback(location)} {...props} />
}
```

**Comment by brophdawg11** [comment]
I'm going to close this out since it seems we have a path forward.  If this is still a requested feature, please open a [Proposal](https://github.com/remix-run/react-router/discussions/new?category=proposals) over in the Discussions tab so it can go through our new [Open Development](https://remix.run/blog/open-development) process.  Thanks!
