### ISSUE TITLE
[v6] Export private contexts behind an underscore

### ISSUE THREAD

**Issue by gaearon** [remix-run/react-router#7545]
V5 exported its internal context as `__RouterContext`.

While it's not covered by semver, it's useful to be able to read from it opaquely and then pass it down into another tree. Such as when dealing with multiple renderers (https://github.com/facebook/react/issues/17275#issuecomment-550322731) or multiple versions of React. This mechanism is going to be an important part of our strategy for [gradual React upgrades](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#gradual-upgrades) in the future.

My proposal is to re-add exports for internal contexts. It's good to keep them behind an underscore so that it's clear their contents aren't bound by semver. However, this still lets you pass bridge them through the renderers or different versions of React.

**Comment by jedwards1211** [comment]
@mjackson @timdorr right now the router state is inaccessible to custom hooks.

But in general if there's a way to get values from context as component props, there should be a way for hooks to get those values too.  `react-router` is one of the few libs I use that still doesn't provide this capability.

Can you either export the context, or a hook that wraps `React.useContext(__RouterContext)` as part of public API?

**Comment by timdorr** [comment]
You can get access to those bits of information via our own hooks. You shouldn't go directly to the context, as it may break between versions if we make some sort of internal change.

If there isn't a hook that gives you the data you need, then that would be a care for a new hook to be made. 

I do agree this escape hatch is needed for communicating through multiple trees. But this should only affect that particular use case, not creating custom hooks or any other work within the same tree.

**Comment by jedwards1211** [comment]
Ah, my apologies, I didn't notice that hooks had been added since I last dealt with this.

**Comment by gaearon** [comment]
@timdorr Any chance we could reconsider this? It’s the recommended approach we suggest in our Gradual Upgrades demo. I’m not sure what other approach we could suggest there, and it would be unfortunate if React users were locked out of Gradual Upgrades by this change in V6.

**Comment by timdorr** [comment]
Yep, I added the right labels so the bot doesn't close it again.

**Comment by Darkylin** [comment]
It's very useful for me to get the current active routes' config object from the RouteContext.
In my scenario, I have the app frame with menu on the top, I need to style them when they are active and report page view with the parameters from the route's config.

**Comment by chaance** [comment]
Hey @gaearon sorry for the rather long wait here. I'm helping @mjackson on the backlog as we approach a stable release for v6. Heard you loud and clear, we're going to continue to expose this (but probably with a somewhat scary sounding name). 

Ideally we'd love to hear a little more about *how* folks are using private data so we can create a more stable path where it makes sense. Michael said you both talked about your use case in some detail a while back, but if you do end up recommending this as a tool for gradual upgrades I'd love to see what that looks like.

**Comment by jgoux** [comment]
@chaance This is a great news!

I exposed my use-case here : https://github.com/ReactTraining/react-router/issues/7933#issuecomment-894963638

I need to create a whole new context because I'm sending components into another part of the component tree but I still want them to be in the same "routing context" when dealing with relative links and useParams. In order to do that I need to consume the current `RouteContext`'s value and pass it to a new `RouteContext.Provider` which will be the new starting point where my components are sent.

I consider the `RouteContext`'s value to be totally opaque here, I just pass it from a consumer to a provider.

**Comment by mjackson** [comment]
Another note here: we may end up with two separate context objects up top, one for the current location (the state) and one for the navigator (state changer) and one down low (the route context). So we'll probably have three total.
