### ISSUE TITLE
Release date/rough time estimate before React Router 6 will be released

### ISSUE THREAD

**Issue by DeadManPoe** [remix-run/react-router#7613]
Is it possible to have a rough time estimate before React Router 6 will be released? I noticed it has been in beta 0 since January.

**Comment by MeiKatz** [comment]
Good question. I also want to know this. But @mjackson and @ryanflorence are kind of silent in the last weeks and months.

**Comment by timdorr** [comment]
They're working on [Remix](https://remix.run/), so who knows.

**Comment by Zertz** [comment]
Don't let the pre-release tag stop you from using v6, it's an excellent release as-is! We have been using beta0 in production for a while now without any issues.

**Comment by beckerei** [comment]
For those of you who don't follow Ryan on twitter, or missed it: https://twitter.com/ryanflorence/status/1317168547064238081 and https://twitter.com/ryanflorence/status/1317215384710250497

So what @Zertz said 👍

**Comment by ancs21** [comment]
@beckerei Good news. 
> Release v6 won't change API.

**Comment by joacub** [comment]
sao it is been Lon long time..., next time I will think more before use react router next version, I was thinking they will release sooner.

btw good project.

**Comment by plandem** [comment]
> Release v6 won't change API.
yeah, but the funny part is - before matching was built around `path-to-regexp` package, but in v6 they gonna use their own implementation instead of that package.

**Comment by pshrmn** [comment]
@plandem, "v6 won't change API" is a reference from the current beta to release candidate.

**Comment by beckerei** [comment]
I hope it's okay to keep the thread updated with information from twitter.

> Excited to get back to shipping React Router v6 stable soon. We know what it needs after using it to build Remix.
>
>Better API, more features, and only 3.1kb over the network!
>
>Far cry from v5 that's like 12kb or 14kb or something ridiculous (embarrassing?) like that.
https://twitter.com/ryanflorence/status/1337512362014752768

And some more

> But we'll be bringing over some of the remix data loading APIs and other small features from Remix.
https://twitter.com/ryanflorence/status/1337517106007474176

**Comment by MeiKatz** [comment]
@beckerei now @ryanflorence and @mjackson only have to merge the pending pull requests and change the confusing part with the root route definition. I mean, what the h**l is `<Route path="/" />` and why is it not `<Route path="" />`? It's totally inconsistent!

**Comment by shulcsm** [comment]
I have multiple projects blocked by #7423 and #7216. Second one seems to have a solid pull request.
How about merging what is merge-able and releasing a new beta for now?

**Comment by dantman** [comment]
😑 Should probably be marked fresh, an issue asking for when v6 will be released shouldn't be auto-closed 
 by a bot just because people are waiting for an update.

**Comment by joacub** [comment]
> 😑 Should probably be marked fresh, an issue asking for when v6 will be released shouldn't be auto-closed
> by a bot just because people are waiting for an update.

I agree

**Comment by evanheckert** [comment]
Recent tweet says hope is to release by Summer 2021. Also linked to transitions page referencing one of the remix features they intend to incorporate: https://gist.github.com/ryanflorence/fc67c2b689c5ecdca7185763a92f120a

**Comment by Aarbel** [comment]
@mjackson  i'm sure many developers would be thrilled to maintain this lib.

Can you open it to other maintainers ?

**Comment by thecodejack** [comment]
Hi Team,

Is there any update related to v6. Has been betav0 for more than an year now with no releases. Would be interested to contribute if required to speed up the release

**Comment by slk333** [comment]
> They're working on [Remix](https://remix.run/), so who knows.

If anything, the way they ignore everyone on this thread is not a good sign as to how they envision communication. I probaby won't touch Remix given how they lag this v6. Most people don't even know that the "dev" branch is the actual v6. And the readme is not giving any help either.

**Comment by liho98** [comment]
React is dead, pls move to vue with awesome vue router (with named routes & so on)

**Comment by mjackson** [comment]
We are picking up work again on v6, should probably release within the next month or so. Thanks for your patience! It’s going to be the best work we’ve ever done on the router, I can promise you that.

**Comment by gsbelarus** [comment]
Is it possible to fix a basename issue first of all? As it is a show stopper for many who try to move existing projects from v5/v4. I mean PR:

https://github.com/ReactTraining/react-router/pull/7462

May be do beta2 ASAP and other issues later?

**Comment by DennisBB** [comment]
> We are picking up work again on v6, should probably release within the next month or so. Thanks for your patience! It’s going to be the best work we’ve ever done on the router, I can promise you that.

cool guys, you are now deleting the comments of others who were not so patient

I think I've seen everything now

**Comment by chaance** [comment]
Just an update on this, I'll be helping Michael on `react-router` full-time starting in a couple of weeks. A v6 major release is my top priority and I'm helping him organize/prioritize issues in the mean time. We appreciate your patience, but know that v6 stable is as crucial for Remix as it is for all of you, and we're very excited to roll it out soon. 🥳

I suspect you'll see one more beta with lots of known bug fixes, but we also need to finish up the docs so there's still a bit of work to be done. I'll try to keep this issue updated as we move in that direction.
