### ISSUE TITLE
Minor v5 release?

### ISSUE THREAD

**Issue by gileswells** [remix-run/react-router#7647]
Would it be possible to potentially cut a 5.2.1 release of `react-router-dom` from what's currently on master? There's some accessibility changes that were merged to master back in July and we're hoping to get it included without having to lock the package to a commit hash.

Thank you.

**Comment by gileswells** [comment]
Without tagging maintainers I'm just bumping this because there is a need for a new minor release if possible.

**Comment by gileswells** [comment]
Sorry to tag you @timdorr, would it be possible to look at cutting a minor release of v5? Specifically looking to see if the PR you merged for me last summer might get a tag so that I can more cleanly close our an accessibility issue on a project I work on. Thank you.

**Comment by timdorr** [comment]
We do releases via CI and I'm not 100% sure if Travis is working at the moment (with all their OSS changes, in particular). I'd like to get that into GitHub Actions, but I don't have access to the token that's stored in Travis. My hands are kind of tied at the moment.

**Comment by gileswells** [comment]
Thanks for the insights on that. Looks like I'll lock our packages file to a commit hash in the meantime.

**Comment by gileswells** [comment]
The last release on master was in May of last year and there have been more PRs merged to master since I last poked at this request for a minor release at 5.2.1. In addition, and something I hadn't noticed, @anied in #7794 noted that the updates on master are on the [docs](https://reactrouter.com/web/api/NavLink/aria-current-string) in prod despite not being included in a release as of yet causing expected behavior to not match actual behavior. 

_moved this comment here as I had originally posted it on the merged PR_

**Comment by sapkra** [comment]
@mjackson Do you have any updates? And maybe publish something which informs the community about the future of the project because currently it doesn't seem to be actively maintained anymore.

**Comment by IanVS** [comment]
I'm a bit nervous to add react-router in a new project because I think maybe the maintainers are spending their time on Remix these days.  Which is cool and I wish them luck, but I hope they don't forget about react-router entirely.  There hasn't been a beta release of v6 in almost a year, and it seems that a minor of the 5.X branch is also stalled out.  Some kind of announcement regarding the future of the project would be much appreciated by a lot of people, I think.

**Comment by gileswells** [comment]
If there isn't a minor release coming could someone please point me in the direction on how to include the latest master commit into my project? Since there isn't an included set of built files on master it seems that I need to do some form of postinstall process to make it build the project for me and I cannot get it figured out. Thank you.

**Comment by chaance** [comment]
Closing because we've cut a few new releases for the v5 branch, and will continue doing so as the need arises.

**Comment by gileswells** [comment]
@chaance thank you for the update!
