### ISSUE TITLE
Protected Routes with Context

### ISSUE THREAD

**Issue by MrBr** [remix-run/react-router#7722]
I've read about protected routes in the issues but I came up with a way which is pretty generic, maybe you'll find it useful.

Here is a proposal, let me know if you think it's fit.

By adding `ProtectedRoutesContext` which has `redirect` path as a value `Route` component could have a mechanism to protect itself out of the box.

Context:
```
const ProtectedRoutesContext = React.createContext(false);

const ProtectedRoutesProvider = ({ children, value }) => (
  <ProtectedRoutesContext.Consumer>
    {(parentRedirect) => (
      <ProtectedRoutesContext.Provider value={parentRedirect || value}>     // Preserve redirect hierarchy
        {children}
      </ProtectedRoutesContext.Provider>
    )}
  </ProtectedRoutesContext.Consumer>
);
```

Route changes (example):
```
const ProtectedRoute = ({ component: Component, ...routeProps }) => { // Should be Route actually
  return (
    <Route {...routeProps}>
      <ProtectedRoutesValidatorConsumer> // Should be internal implementation
        {(redirect) => (redirect ? <Redirect to={redirect} /> : <Component />)}
      </ProtectedRoutesValidatorConsumer>
    </Route>
  );
};
``` 

Usage example:
```
// Validator component
const AuthValidator = ({ isAuthenticated, children }) => {
  const redirect = !isAuthenticated && '/login';

  return (
    <SafeRouteValidatorProvider value={redirect}>
      {children}
    </SafeRouteValidatorProvider>
  );
};

// In the Router tree
<Router>
  <AuthValidator>
    <ProtectedRoute component={SafePage} path="/safe-page">
  </AuthValidator>
  <ProtectedRoute component={LoginPage} path="/login">
</Router>
```

Ideally there is no need for new component, `Route` could extend its knowledge a bit and support `ProtectedRoutesContext`. Seems like a clean way to do it.

**Comment by MrBr** [comment]
I've created lib with working implementation as a point of reference.

https://github.com/MrBr/react-router-protected-switch

**Comment by chaance** [comment]
Doing a little cleanup of issues. This looks like it could be a useful pattern, but something we'll probably leave for users to implement as needed. Happy to reopen if we decide to explore this further!
