### ISSUE TITLE
[V6] useResolvedPath() has wrong return type

### ISSUE THREAD

**Issue by damikun** [remix-run/react-router#7736]
**Description:**
Return type of useResolvedPath()  Hook is badly interpreted

**Expected:** return Path object as PartialPath 
**Current:** Returning string

From code types it return Path object... which type at the end is string in type definition...
  
`export declare function useResolvedPath(to: To): Path` which is `export type Path = History.Path;` and at the end  `  export type Path = string;`

But  function itself under the hood calls resolvePath and that return  `return { pathname, search, hash }`

```
export function resolvePath(to: To, fromPathname = '/'): Path {
  let { pathname: toPathname, search = '', hash = '' } =
    typeof to === 'string' ? parsePath(to) : to;

  let pathname = toPathname
    ? resolvePathname(
        toPathname,
        toPathname.startsWith('/') ? '/' : fromPathname
      )
    : fromPathname;

  return { pathname, search, hash };
}
```

https://github.com/ReactTraining/react-router/blob/6e13acf6b9c0101bcffb67a236f29226c18c2a6b/packages/react-router/index.tsx#L956

So the response type is badly interpreted as sting and not as PartialPath ..

Correct type comes from history package
```
export interface PartialPath {
  /**
   * The URL pathname, beginning with a /.
   */
  pathname?: Pathname;

  /**
   * The URL search string, beginning with a ?.
   */
  search?: Search;

  /**
   * The URL fragment identifier, beginning with a #.
   */
  hash?: Hash;
}
```

**Version**
React Router v6.0.0-beta.0

**Comment by chaance** [comment]
I don't believe this is still an issue in the last few releases, but please let me know if so and I can take another look.
