### ISSUE TITLE
Prompt not working as intended for history.push and browser back button

### ISSUE THREAD

**Issue by BrinsterAman** [remix-run/react-router#7865]
## Version

5.2.0

## Steps to reproduce
We are using `Prompt` for `history.push` and `browser back button`. When we are clicking on either of them, and then click on `Cancel`, the url first changes to new url. Then it gets back to previous url, but the `state` is `reset`. Due to this, we are losing the progres.

## Expected Behavior
By clicking on `cancel`, the state should not get reset, it should maintain itself. While only when we click on `OK`, state should reset and view should be forwarded to new view (according to url).

## Actual Behavior
State is getting reset, with url being changed even though we are clicking on `cancel`.

**Comment by myNameIsDu** [comment]
If you use window.history.go, you will have the problem of switching between old and new URLs. The browser will display the new URL, but inside the React -Router, it is still the old URL, so its state is old

**Comment by saramorsi** [comment]
How can I resolve this issue? Running into it

**Comment by myNameIsDu** [comment]
> How can I resolve this issue? Running into it

Do not use window.history

**Comment by damoncasale** [comment]
> > How can I resolve this issue? Running into it
> 
> Do not use window.history

That's the same as putting a piece of tape over a brake warning light.  NO, NO, NO.

We want the browser's url to not change.  In my case, it's causing a video HTML element to spontaneously redraw as soon as the user clicks the cancel button on the prompt.

PLEASE FIX.

**Comment by jakub-bao** [comment]
Hi, I am facing the same issue.

----------
#### Proposed solution in: https://github.com/remix-run/react-router/issues/7865#issuecomment-861992029
> Do not use window.history

**Result** I've tried to avoid relying on window.history but it doesn't bypass the problem.

I really believe this has to be fixed. Since it's a real issue in `react-router.`

----------------
#### Demo reproducing the issue


I was able to put together a demo which reproduces the bug: https://stackblitz.com/edit/react-ts-qfjexz
Follow the steps on the right side and keep note of current url (in the embedded browser window)

**Comment by myNameIsDu** [comment]
> Hi, I am facing the same issue.
> 
> #### Proposed solution in: [#7865 (comment)](https://github.com/remix-run/react-router/issues/7865#issuecomment-861992029)
> > Do not use window.history
> 
> **Result** I've tried to avoid relying on window.history but it doesn't bypass the problem.
> 
> I really believe this has to be fixed. Since it's a real issue in `react-router.`
> 
> #### Demo reproducing the issue
> I was able to put together a demo which reproduces the bug: https://stackblitz.com/edit/react-ts-qfjexz
> Follow the steps on the right side and keep note of current url (in the embedded browser window)

I think you can this:

![image](https://user-images.githubusercontent.com/53305259/134761252-7e78716d-f344-4504-a273-f803c6c6c37e.png)
