### ISSUE TITLE
[v5] Not compatible with React 18 StrictMode

### ISSUE THREAD

**Issue by Jack-Works** [remix-run/react-router#7870]
## Version

v5.2.0

React 18 with StrictMode, see https://github.com/reactwg/react-18/discussions/19

## Test Case

https://codesandbox.io/s/react-router-forked-1s3zi

## Steps to reproduce

Click around

## Expected Behavior

Works

## Actual Behavior

Not working

**Comment by Jack-Works** [comment]
Tested with v6, seems OK

**Comment by patrikniebur** [comment]
I had the same issue. It's not working when used in `React.StrictMode`

**Comment by popuguytheparrot** [comment]
Yes. Same
https://codesandbox.io/s/react-router-sidebar-forked-mzyvs?file=/index.js
With v6 OK

**Comment by popuguytheparrot** [comment]
In my case, updating to version 6 is impossible, because there is no way to control history outside of react

**Comment by DeividasBakanas** [comment]
Just to clarify the issue: with React 18 StrictMode, react-router does not perform the transition when navigation occurs. The route is stale when the path is changed: https://codesandbox.io/s/dreamy-andras-hbuco1?file=/src/index.tsx

The behavior occurs in v5.3.0 too.

As React 18 is officially released and the StrictMode is preferred in many cases as default in a development environment, this issue should become more relevant.

As there is still no backwards compatibility package, can we expect the patch release of v5 for the issue?

**Comment by timdorr** [comment]
If someone wants to make a PR, I'd be happy to do a patch release for v5.

**Comment by rahulppatidar** [comment]
It is not working if BrowserRouter is a child of StrictMode. So, to make it work we can put StrictMode as child of BrowserRouter.
i.e. Instead of `<React.StrictMode><BrowserRouter>...</BrowserRouter><React.StrictMode>`
we can  `<BrowserRouter><React.StrictMode>...<React.StrictMode></BrowserRouter>`
That way it worked for me.

**Comment by jgoz** [comment]
I think I've got a fix for this in https://github.com/remix-run/react-router/pull/8831

**Comment by yoerivdm** [comment]
> 

This solves it BUT we are experiencing mout-unmounts-mount cycles for each component. This rerender behaviour is solved when removing the strictmode.

**Comment by awreese** [comment]
Following this issue: https://stackoverflow.com/a/71833424/8690857

**Comment by phanimurari** [comment]
> I had the same issue. It's not working when used in `React.StrictMode`

Thanks for the help

**Comment by fajria96** [comment]
Omg big thanks. I was so stressed out for few days cause of it

**Comment by chollid** [comment]
Wish I had discovered this sooner, wow, thanks!
