### ISSUE TITLE
[v6] `useResolvedPath` says it returns a `Path` but it's just the pathname

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#7924]
### What version of React Router are you using?

v6

### Steps to Reproduce

```tsx
// url like /foo?bar=baz
let to = useResolvedPath();
to.search // undefined!
to.hash // undefined!
```

### Expected Behavior

I'd expect all of the `Path` to be there.

### Actual Behavior

It is not there, only `path.pathname`

**Comment by chaance** [comment]
@ryanflorence any chance you could re-create what you're seeing here? I'm not seeing an issue https://codesandbox.io/s/use-resolved-path-bug-db7tu?file=/src/App.tsx
