### ISSUE TITLE
[v6] [Feature]: usePrompt() should have callback to check 'desired' path before warning 

### ISSUE THREAD

**Issue by onionhammer** [remix-run/react-router#7926]
### What is the new or updated feature that you are suggesting?

Currently usePrompt gives no way to not show the prompt if the user is simply navigating to another path in the same area where a warning wouldnt necessarily be needed or wanted.. for example, if I have 3 tabs on the same page in the same form, navigating between tabs does not clear the state (the user loses no data), but if they navigate out a level ('..') they would lose state.

It would be great to be able to check the 'next' path that the user is trying to go to to decide if they should be prompted.

```ts
function usePrompt(message: string, when?: boolean | (to: To) => boolean): void
```

### Why should this feature be included?

This would allow users to change to SOME paths without prompting, but but prompt instead when users are fully leaving an area of your application

**Comment by timdorr** [comment]
That's what the `to` argument is on the function version of the `when` parameter. It represents the next location you're going to.

**Comment by onionhammer** [comment]
@timdorr that's the *proposed* function signature, not the current signature

**Comment by timdorr** [comment]
Sorry, wasn't paying attention...

**Comment by philals** [comment]
Hi. Where are the docs for usePrompt? I cannot find it in the repo or on the dev branch. Thanks

**Comment by onionhammer** [comment]
@philals I've only been using this ancient blob post as a reference:

https://reacttraining.com/blog/react-router-v6-pre/

**Comment by timdorr** [comment]
Closing since this API is no longer in the library. #8139 will track when it's added back.

**Comment by uthbees** [comment]
usePrompt was added back in #9932, any chance this can be reopened?
