### ISSUE TITLE
[Feature]: Allow to override the location in the Routes in V6, like in the modal example in V5

### ISSUE THREAD

**Issue by fgatti675** [remix-run/react-router#7949]
### What is the new or updated feature that you are suggesting?

I have migrated my app to v6 but there is one feature I am missing.
In v5, you could specify the location, allowing you to build different cases depending on how you got there, like in the modal example.
https://reactrouter.com/web/example/modal-gallery
I haven't been able to find that feature in `Routes` or any equivalent way of achieving the same.
Sorry if I missed something!

### Why should this feature be included?

It is useful for complicated navigation use cases

**Comment by fgatti675** [comment]
I created a PR :)
https://github.com/remix-run/react-router/pull/7969
Thanks for the awesome work!

**Comment by timdorr** [comment]
See the discussion in #7946
