### ISSUE TITLE
[Bug]: useParams potentially undefined with noUncheckedIndexedAccess enabled in TypeScript

### ISSUE THREAD

**Issue by zimme** [remix-run/react-router#7950]
### What version of React Router are you using?

6

### Steps to Reproduce

Enable "noUncheckedIndexedAccess" in tsconfig.json and try accessing a param via `useParams` in a component that only renders on a route that require's a param.

### Expected Behavior

I expect TypeScript to infer `string` type instead of `string | undefined` from useParams for params that is know to exist on the route.

### Actual Behavior

The variable have a type of `string | undefined` as TypeScript isn't able to properly infer that the param actually exists on the route and set a type of `string`.

I have a vague sense of this being impossible or very hard to fix as it might be impossible to hook up type definitions that allow this to be statically analysed because of the param names being setup inside a string using ":variablesNames".

**Comment by zimme** [comment]
Also, this might not actually be a bug but a feature request.

**Comment by timdorr** [comment]
useParams may have a runtime type of `string` for the params it knows about in a certain context, but it doesn't have a static type that can be inferred based on the context it's used within. TypeScript isn't capable of that.

Instead, just assert it to your params type with `useParams() as MyParamsType`
