### ISSUE TITLE
[Bug]: documentation, the topics under web > examples are not getting populated

### ISSUE THREAD

**Issue by cch5ng** [remix-run/react-router#7951]
### What version of React Router are you using?

5.2.0 (n/a)

### Steps to Reproduce

From the training website, click the Web tab.

Then click any topic under Examples. For example, Basic

https://reactrouter.com/web/example/basic

The body is not getting populated with the code example

In the console, there is a message like

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

### Expected Behavior

Expect the right side of the window to be populated with a code sample.

### Actual Behavior

The body is not getting populated with the code example

**Comment by timdorr** [comment]
It looks like you have third-party cookies blocked. You'll need to unblock them for the examples to work: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document
