### ISSUE TITLE
[v6] React.Lazy type error

### ISSUE THREAD

**Issue by thecodejack** [remix-run/react-router#7955]
### What version of React Router are you using?

v6

### Steps to Reproduce

Getting type error with following code

```
import React from 'react';
import { Routes, Route } from 'react-router-dom';



//Lazy is not working yet with react-router-dom v6 yet.
const Home = React.lazy(() => import('../Homepage'));
const NotFoundPage = React.lazy(() => import('../NotFoundPage'));

export default function App() {
  return (
    <>
      <div id="page-container">
        <React.Suspense fallback={<h1>Loading</h1>}> 
          <Routes>
            <Route path="/" element={Home} />
            <Route path="*" element={NotFoundPage} />
          </Routes>
         </React.Suspense>
      </div>
    </>
  );
}

```

Error is 

```
Type 'LazyExoticComponent<() => Element>' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | null | undefined'.
  Type 'ExoticComponent<unknown> & { readonly _result: () => Element; }' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, keyts(2322)
```

### Expected Behavior

There shouldn't be any error

### Actual Behavior

Error is 

```
Type 'LazyExoticComponent<() => Element>' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | null | undefined'.
  Type 'ExoticComponent<unknown> & { readonly _result: () => Element; }' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, keyts(2322)
```

**Comment by timdorr** [comment]
Your routes are wrong. The element prop expects an element, not a component:
```js
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="*" element={<NotFoundPage />} />
          </Routes>
```

**Comment by hsbtr** [comment]
This is how I implemented it. There are some differences between element and component. What is needed is an element, and the component will report a warning.

`
// routes.config.js
import { lazy } from "react";
// import Login from "../pages/Login";
const Login = lazy(() => import("../pages/Login"));

const routes = [
    {
        path: "/login",
        name: "登录",
        element: Login
    }
]


export default routes;
`
`
import { useState, lazy, Suspense } from "react";
import { Routes, Route, useRoutes } from "react-router-dom";
const RouterView = (props) => {
    const { routes } = props || {};
    return (
         <Suspense fallback={<div>Loading..</div>}>
             <Routes>
                 {
                     routes.map((item)  => (
                         <Route
                             path={item.path}
                             key={item.path}
                             element={<item.element />}
                         />
                     ))
                 }
             </Routes>

         </Suspense>
    )
};

export default RouterView;
`
