### ISSUE TITLE
[Bug]: useNavigate with basename behaves differently outside of a route

### ISSUE THREAD

**Issue by dhulme** [remix-run/react-router#7957]
### What version of React Router are you using?

6.0.0-beta.1

### Steps to Reproduce

Create a basic app with the following code (or see https://codesandbox.io/s/nifty-sky-opm13?file=/src/App.js)

```js
import { BrowserRouter } from "react-router-dom";
import { useNavigate, Routes, Route } from "react-router";

function SidePanel() {
  const navigate = useNavigate();
  return <button onClick={() => navigate("/page")}>Side panel link</button>;
}

function Home() {
  const navigate = useNavigate();
  return <button onClick={() => navigate("/page")}>Home page link</button>;
}

function Page() {
  return <div>Page</div>;
}

export default function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <SidePanel />
        <div className="content">
          <Routes basename="/app">
            <Route path="/page" element={<Page />} />
            <Route path="/" element={<Home />} />
          </Routes>
        </div>
      </BrowserRouter>
    </div>
  );
}
```

### Expected Behavior

When navigating to /app and clicking the home page and side panel links, I would expect both to take you to /app/page

### Actual Behavior

The link in the SidePanel component (outside of Routes/Route components) doesn't use the basename and navigates to /page. This does make sense, but differs from 6.0.0-beta.0 where they would both ignore the basename. Is there another way I should use useNavigate in app wide components?

**Comment by wojtekmaj** [comment]
I think I have related issue. 

I have a bunch of nested routes. In /form/, I have something along the lines

```jsx
    <Routes>
      {paths.map((path) => (
        <Route
          key={path}
          path={path}
          element={<p>Step {path}</p>}
        />
      ))}
      <Route path="*" element={<Navigate to={resolvedPaths[0]} />} />
    </Routes>
```

where

```
paths = ['1', '2', '3']
resolvedPaths = ['/form/1', '/form/2', '/form/3']
```

so that when you enter `/form` you're automatically redirected to `/form/1`.

When updating from 6.0.0-beta.0 to 6.0.0-beta.1, this stopped working, and redirected me to `/form/form/1` instead. `navigate()` has the same problem.

**Comment by caseyjhol** [comment]
Does something like this work for you?

```js
export default function App() {
    return (
        <div className="App">
            <BrowserRouter>
                <Routes basename="/app">
                    <Route
                        path="/*"
                        element={
                            <>
                                <SidePanel />
                                <div className="content">
                                    <Outlet />
                                </div>
                            </>
                        }
                    >
                        <Route path="/page" element={<Page />} />
                        <Route path="/" element={<Home />} />
                    </Route>
                    <SidePanel />
                </Routes>
            </BrowserRouter>
        </div>
    );
}
```

**Comment by dhulme** [comment]
Yes this works, thank you!

**Comment by dhulme** [comment]
Note, this example will no longer work as of 6.0.0-beta.4 because absolute child routes are no longer supported.

Either the child routes should use relative paths, or in my case I have included the sidebar in each `element` prop
