### ISSUE TITLE
[Bug]: RegEx does not work in route

### ISSUE THREAD

**Issue by Stunext** [remix-run/react-router#7967]
### What version of React Router are you using?

6

### Steps to Reproduce

You can use this codesandbox to test. Routes with regular expressions do not work correctly

https://codesandbox.io/s/v6-regex-does-not-work-w45i0

### Expected Behavior

The route component is rendered correctly

### Actual Behavior

The NotFound component is rendered instead

**Comment by timdorr** [comment]
These kinds of regexp patterns aren't supported in v6: https://github.com/remix-run/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#note-on-route-path-patterns
