### ISSUE TITLE
[Bug]: React-router docs page examples showing empty pages.

### ISSUE THREAD

**Issue by JESii** [remix-run/react-router#7973]
### What version of React Router are you using?

This is the documentation page at https://reactrouter.com/web/guides/quick-start

### Steps to Reproduce

- Visit the docs page https://reactrouter.com/
- Click 'web'
- Click on any of the "Examples" pages
- E.g., 'Basic"

### Expected Behavior

should see the examples

### Actual Behavior

Get an empty page -- 
![2021-08-24 at 6 58 AM](https://user-images.githubusercontent.com/486/130630795-317736aa-83a4-4bf4-85eb-d140ce34e0ca.png)

**Comment by pshrmn** [comment]
Duplicate of https://github.com/remix-run/react-router/issues/7951 (or possibly you have privacy badger running and that is blocking codesandbox)

**Comment by JESii** [comment]
Nope — no privacy badger and I get to code sandbox everywhere else… thanks
