### ISSUE TITLE
[v6] [Feature]: Allow callback for message property of Prompt

### ISSUE THREAD

**Issue by vmlopezr** [remix-run/react-router#7974]
### What is the new or updated feature that you are suggesting?

The docs in  https://reactrouter.com/core/api/Prompt mention that the Prompt component allows a callback for the message property.

Looks like the `Prompt` component still exists In V6 beta's, but it only allow passing a string for the message property.

### Why should this feature be included?

This would allow to prevent the prompt based on some logic on the next path. For example we could update url search params with out getting the prompt.

**Comment by fgatti675** [comment]
I think my question is related to this. 
I am trying to show a prompt only on `POP` actions, which was posisble in v5.
Is it also possible in v6? I can't seem to find a way
Thanks!

**Comment by timdorr** [comment]
Closing since this API is no longer in the library. #8139 will track when it's added back.
