### ISSUE TITLE
[Feature]: Reduce useRoutes warning

### ISSUE THREAD

**Issue by labriola** [remix-run/react-router#7977]
### What is the new or updated feature that you are suggesting?

Right now useRoutes_ warns anytime it is called within a parent that does not express the ability to have child routes. However, hooks can't be called conditionally. So in truly dynamic situations we may need to call useRoutes with an empty array of routes to keep the hooks in the right order. 

Could the warning in useRoutes_ only occur _if_ there are actually routes passed in? Meaning that if the array of RouteObjects is empty do not warn.

### Why should this feature be included?

In very dynamic routing situations it seems (if I am not doing something wrong) to clutter the output with warnings that cannot be addressed. The extra clutter just makes it less likely to see a problematic issue

**Comment by mjackson** [comment]
Can you please say more about why you have to call useRoutes without any routes? That’s definitely not the intended usage.

**Comment by labriola** [comment]
Sure... and, again, no expectations of you accommodating my use case, but if this was generally applicable I wanted to make the suggestion.

Its more or less a workflow concept and, as always, might be tricky to explain, but we receive potential new routes for a child node depending on server state. 

While its not totally accurate, imagine some form of unique ticketing system and, when the ticket is first rendered, you have the option of routing between several subviews to see more data and perhaps perform actions on the ticket. However, as it moves through a workflow, state changes and so do the subsequent possible routes. So, useRoutes() is called with a projection of server data. However, eventually we might reach a state where you can see the summary information but there are no more subroutes to be had. In this case, we end up (today) calling useRoutes() with no additional routes. While I am perhaps being over-precise, we also ensure the parent route no longer has an '*' as there are truly no subroutes. 

Now, that said, obvious other approaches include always leaving the '*" on the parent route, I was avoiding this only as it expresses something somewhat inaccurate, or rendering two different 'subview' components one of which does or does not call the useRoutes() hook. Clearly this can be done just turns out the everything is identical save for the useRoutes() call.

Just ends up in my use case that I can treat everything completely fractally (the tree gets deep in our use case), and have an infinite number of subroutes all defined by the server, that can change over time.... but I need to deal with some development warnings. So, all of that said: ignore this as needed. I can work around it, t'was only a thought as expressions a useRoute() with no viable routes didn't seem wholly incompatible with a parent route that did not end in an '*'

Thanks for taking the time to read the babble above.

**Comment by labriola** [comment]
Side note: I settled on a Branch versus Leaf component being the right approach for now
