### ISSUE TITLE
[v6] Nested Routes - useNavigate doesn't respect basename of parent Routes

### ISSUE THREAD

**Issue by crutch12** [remix-run/react-router#7980]
### What version of React Router are you using?

v6.0.0-beta.2

### Steps to Reproduce

Just make nested Routes:

```js
import { useNavigate } from "react-router-dom";

export default function Nested() {
  const navigate = useNavigate();
  return <div>
    <button onClick={() => navigate('/')}>tryNavigate('/')</button>
    </div>
}
```
```jsx
<Routes basename="/base">
  <Routes basename="/nested">
    <Nested />
  </Routes>
</Routes>
```

### Expected Behavior

`navigate('/')` should open `/base/nested`

### Actual Behavior

`navigate('/')` opens `/nested`

Reproduction:
https://codesandbox.io/s/react-router-v6-forked-6hrki

**Comment by timdorr** [comment]
`basename` isn't intended to be nested. Using it like that will overwrite the value of any ancestor in the tree. This isn't expected behavior.

**Comment by crutch12** [comment]
> `basename` isn't intended to be nested. Using it like that will overwrite the value of any ancestor in the tree. This isn't expected behavior.

Ok, but nested <Route> links works as I expected, it's strange.

And if I use <Routes> with `basename`, should I always set absolute value? In my codesandbox example <Routes basename="absolutePath"> just doesn't work

What is right way to nest <Routes>?

**Comment by timdorr** [comment]
You shouldn't be nesting `<Routes>`, just use `<Route path="/nested">`.

**Comment by crutch12** [comment]
> You shouldn't be nesting `<Routes>`, just use `<Route path="/nested">`.

I use <Routes> to wrap each my microfrontend app

Isn't right way?

**Comment by timdorr** [comment]
Yes, but you don't need a basename in that case. It comes automatically from the ancestor `<Routes>` it's nested under.
