### ISSUE TITLE
[Bug v5.2.1]: withRouter regression on upgrade from 5.2.0

### ISSUE THREAD

**Issue by johnhunter** [remix-run/react-router#7981]
### What version of React Router are you using?

5.2.1

### Steps to Reproduce

Using withRouter within a BrowserRouter throws an error after update from 5.2.0 to 5.2.1

The following is a simplified example of the failing code:

**RouteStart.jsx**
```jsx
import { withRouter } from 'react-router';
...
const RouteStart = ({ location }) => {
    // do something with location
};

export default withRouter(RouteStart);
```

**App.jsx**
```jsx
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
...
const App = () => (
  <Router>
    <RouteStart />
    <Switch>
      <Route path="/welcome/" component={Welcome} />
      ...
    </Switch>
  </Router>
);
```

### Expected Behavior

On App mount the example RouteStart component receives a location prop from the withRouter HOC.
This is the behaviour prior to v5.2.1

### Actual Behavior

On App mount the example throws the error:
`Invariant failed: You should not use <withRouter(RouteStart) /> outside a <Router>`

**Comment by timdorr** [comment]
If you have both `react-router` and `react-router-dom` as deps on your project, make sure they are both at the exact same version. You can find incorrect versions with `npm ls react-router`.
