### ISSUE TITLE
[Bug]:  Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

### ISSUE THREAD

**Issue by thatguyjono94** [remix-run/react-router#7984]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

Fresh install and inspect console.

### Expected Behavior

Console shouldnt have this warning message.

### Actual Behavior

Warning message appears in browser.

**Comment by timdorr** [comment]
What browser are you using?

**Comment by thatguyjono94** [comment]
@timdorr latest chrome.

**Comment by timdorr** [comment]
This isn't caused by this library. We don't make any calls to those APIs.

**Comment by thatguyjono94** [comment]
It's from the history dependancy that this library is using.
