### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by AadilVarsh** [remix-run/react-router#7986]
### What version of React Router are you using?

^5.2.1

### Steps to Reproduce

```jsx
import "./App.css";

import { useEffect, useState } from "react";

import { Router, Route, Switch } from "react-router";

function Hello() {
  return <div>HEllo</div>;
}

function App() {
  return (
    <Router>
      <Switch>
        <Route path="/about" component={<Hello />} />
      </Switch>
    </Router>
  );
}

export default App;
```

### Expected Behavior

I just wrote the above code and this error is repeatedly showing up.
![image](https://user-images.githubusercontent.com/72086030/131661624-58fb3f46-c2d8-409a-8db9-d51939e11581.png)

### Actual Behavior

There shouldn't be an error by the tutorial I'm following!

**Comment by timdorr** [comment]
You shouldn't be using just `Router`. Use a `BrowserRouter` or `HashRouter`.
