### ISSUE TITLE
[V6] [Bug]: useBlocker breaks after setting window.location manually

### ISSUE THREAD

**Issue by Animalmix55** [remix-run/react-router#7990]
### What version of React Router are you using?

6.0.0-beta.2

### Steps to Reproduce

1. Configure useBlocker to block when a form has unsaved changes at a given route
2. Configure a button to navigate to that route from another route, but not using useNavigate, using window.location.href = 'form' (or window.location.assign(), or .replace(), etc.).
3. Modify the form to enable the blocker
4. Navigate away from the blocker using a button configured with useNavigate() to return to another route.

### Expected Behavior

Using window.location.href = <href> should update the view rendered by the router and useBlocker should continue working as expected after that view loads (meaning, it should block navigation when enabled and run the blocker function).

### Actual Behavior

At step four the URL changes, but the view does not update, and the blocker function passed into useBlocker is not executed.

This behavior can only be resolved by closing the browser and reopening (reloading does not resolve it)

**Comment by timdorr** [comment]
`useBlocker` uses [`history.block()`](https://github.com/remix-run/history/blob/main/docs/api-reference.md#historyblockblocker-blocker) under the hood, which only blocks navigations that come from the history instance itself. If you're navigating outside of the Router, then there's no way for it to know about that navigation event. You should disable the blocker before manipulating `location.href`.

**Comment by Animalmix55** [comment]
@timdorr I do not expect useBlocker to block a window.location update, i understand that it does not track them… the issue is that the window.location update causes the useBlocker hook to stop functioning on calls that use the useNavigate hook. After changing window.location, useBlocker no longer calls the blocker function passed in for routes navigated to with useNavigate until the browser is restarted.
