### ISSUE TITLE
[v6] [Bug]: 6.0.0-beta.3 changes relative `NavLink` behavior

### ISSUE THREAD

**Issue by david-crespo** [remix-run/react-router#8004]
### What version of React Router are you using?

v6 beta 3

### Steps to Reproduce

Start at root, then click metrics, then click settings.

https://codesandbox.io/s/react-router-v6-beta-3-bug-mh54b?file=/src/App.js

### Expected Behavior

In v6 beta 2, you can navigate back and forth between the links and they're all relative to `/`. So if you click Settings when you're on `/metrics` you land on `/settings`.

### Actual Behavior

In v6 beta 3, if you click Settings when you're on `/metrics` you land on `/metrics/settings`. What's especially odd is that the `href` on the link is correct (according to my expectation anyway): it says `/settings`. I have a hunch this is related to https://github.com/remix-run/react-router/pull/7982.

**Comment by micha149** [comment]
I can confirm the same buggy behavior on the `Link` component…

**Comment by Rafael-Dabrowski** [comment]
Me too.

**Comment by chaance** [comment]
This should fix `Link` too 🙂

**Comment by k-maekawa** [comment]
> #8026 should fix `Link` too 🙂

@chaance 
Thanks for fixing the bug.
`useNavigate` has the same problem.  Will It be solved by #8026 ?

**Comment by david-crespo** [comment]
> > #8026 should fix `Link` too 🙂
> 
> @chaance
> Thanks for fixing the bug.
> `useNavigate` has the same problem. Will It be solved by #8026 ?

Yes. All the [changes](https://github.com/remix-run/react-router/pull/8026/files#diff-b60f1a2d4276b2a605c05e19816634111de2e8a4186fe9dd7de8e344b65ed4d3) are in `useNavigate`.

**Comment by david-crespo** [comment]
Confirmed this is fixed in beta 4.
