### ISSUE TITLE
[Bug]: wrong parameters of `className` and `style` prop function

### ISSUE THREAD

**Issue by MikeSha** [remix-run/react-router#8028]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

Simply use ```<NavLink className={({isActive}) => `class-name ${isActive ? active : ''}`}>Link</NavLink>```
or
```<NavLink to="/url" style={({isActive}) => ({ color: isActive ? 'yellow' : 'blue' })}>Link</NavLink>```.
This is how it should be according to the release notes:
https://github.com/remix-run/react-router/releases/tag/v5.3.0
In these cases `isActive` is always `undefined`

Also, I've made a PR to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55637. But types there respect the actual behaviour

### Expected Behavior

I don't really know what is better to be fixed: release notes or function parameters :)

So there are two ways:
1) Change the release notes, but v6.0 should be considered
2) Change the code

Also, shouldn't this feature be described in the docs?

### Actual Behavior

So, obviously it works if:
```<NavLink className={(isActive) => `class-name ${isActive ? active : ''}`}>Link</NavLink>```
or
```<NavLink to="/url" style={(isActive) => ({ color: isActive ? 'yellow' : 'blue' })}>Link</NavLink>```

**Comment by timdorr** [comment]
I updated the release notes to have the right params for the function prop. It is a boolean in v5 and an object in v6. Sorry about the confusion!
