### ISSUE TITLE
[Bug]: Redirect `from` propType also supports array

### ISSUE THREAD

**Issue by santiagoGuti** [remix-run/react-router#8029]
### What version of React Router are you using?

V5

### Steps to Reproduce

Given I am using <Redirect> component 
When I pass an array of string in the form property
Then the propTypes don't throw an error

in react-router/packages/react-router/modules/Redirect.js

replace this

```
 Redirect.propTypes = {
    push: PropTypes.bool,
    from: PropTypes.string,
    to: PropTypes.oneOfType([PropTypes.string, PropTypes.object]).isRequired
  };
```

for 
```
 Redirect.propTypes = {
    push: PropTypes.bool,
    from: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.arrayOf(PropTypes.string)
    ]),
    to: PropTypes.oneOfType([PropTypes.string, PropTypes.object]).isRequired
  };
```

as the `from` prop from redirect behaves the same way as 'path' in route (react-router/packages/react-router/modules/Switch.js#31)

### Expected Behavior

<Redirect from={['/path1', 'path 2']} /> should not throw a propType error

### Actual Behavior

<Redirect from={['/path1', 'path 2']} /> throws a propType error

**Comment by timdorr** [comment]
You shouldn't use an array for that prop. Just use multiple Redirect's. They PropTypes are correct.

**Comment by santiagoGuti** [comment]
Hello, I was wondering why we treat the `from` property differently to the `path` property at the end of the day they both use the same strategy. I would expect to either don't use array in both of them or either do. On the other hand using an array already works for <Redirect/> is just the propType seems to be the only one disagreeing. Thank for the quick answer @timdorr  and sorry for any inconvenience.

**Comment by timdorr** [comment]
It's a feature of the underlying library we use for matching paths. We pass along the same inputs. It's not something we like to support or really advertise as the way to do routes, as it's simpler to keep everything in the same structure throughout your route tree.
