### ISSUE TITLE
[v6][Bug]: Code Splitting Not Working 

### ISSUE THREAD

**Issue by aress31** [remix-run/react-router#8032]
### What version of React Router are you using?

v6

### Steps to Reproduce

`routes.js` redacted content:
```js
import React from 'react';
import { lazily } from 'react-lazily';

const {
  Foo,
  Bar,
  Foobar,
} = lazily(() => import('../pages'));

export default [
  {
    element: (
      <Bar/>
    ),
    label: 'Bar',
    path: '/',
  },
  {
    element: (
        <Foo/>
    ),
    label: 'foo',
    path: '/foo',
  },
  {
    element: (
        <Foobar/>
    ),
    path: '*',
  },
];
```

`App.js` redacted content:
```js
import {
  Box,
  CircularProgress,
  Typography,
} from '@material-ui/core';
import { useLocation, useRoutes } from 'react-router-dom';

import { routeConfig } from './config';


const LoadingSpinner = () => (
  <Box>
    <CircularProgress />
    <Typography variant='subtitle1'>Loading...</Typography>
  </Box>
);

export default () => {
  const location = useLocation();
  const routeResult = useRoutes(routeConfig);

  return (
        <React.Suspense fallback={<LoadingSpinner />}>
              {routeResult}
        </React.Suspense>
  );
};
```

### Expected Behavior

`JS chunks` to load on the relevant route only and all other codes to be deferred for later loading when user browses another route.

### Actual Behavior

All the `JS chunks` are loaded at once rather than the relevant `elements` for the relevant route, see:

![image](https://user-images.githubusercontent.com/11601622/133006533-5c369a2b-548d-4c18-ac78-9f548990dbb4.png)

**Comment by timdorr** [comment]
This doesn't have anything to do with React Router. You're instantiating your route elements in your routes.js module, which is causing them to resolve immediately. You need to figure out some other way to have them resolve lazily, when the route is rendered.
