### ISSUE TITLE
[Feature]: useMatch take in array like useRouteMatch

### ISSUE THREAD

**Issue by chaserda** [remix-run/react-router#8038]
### What is the new or updated feature that you are suggesting?

useMatch able to take an array of different paths to match like useRouteMatch

### Why should this feature be included?

Allowing for possible match conditions to meet instead of just one

example: 

```  
const routeMatch = useRouteMatch(['/inbox/:id', '/drafts', '/trash']);
  const currentTab = routeMatch?.path;

  return (
    <Tabs value={currentTab}>
      <Tab label="Inbox" value="/inbox/:id" to="/inbox/1" component={Link} />
      <Tab label="Drafts" value="/drafts" to="/drafts" component={Link} />
      <Tab label="Trash" value="/trash" to="/trash" component={Link} />
    </Tabs>
  );
}```

**Comment by timdorr** [comment]
Unfortunately, this would make #8030 significantly more difficult to implement.

Since `useMatch` just wraps `matchPath` with a call to `useLocation`, I would just do this yourself in a map or find loop:

```js
const paths = ['/inbox/:id', '/drafts', '/trash']
const location = useLocation()
const match = paths.find(path => matchPath(path, location.pathname))
```

I don't think this is something we're going to support in the library itself.
