### ISSUE TITLE
[Feature]: useMatch able to meet param conditions for active links

### ISSUE THREAD

**Issue by chaserda** [remix-run/react-router#8039]
### What is the new or updated feature that you are suggesting?

let match = useMatch(to)

Will only meet 

path="/Devices" condition, however if we went into a nested route like "Devices/:id" this match is no longer met and therefore active link is not longer active.

### Why should this feature be included?

To include active menu link styling for nested routes

**Comment by timdorr** [comment]
I think you're missing some context on your example code. What is the value of `to` in this case? I'm sorry, but I'm not groking what you're asking otherwise.

**Comment by chaserda** [comment]
@timdorr sorry let me try explaining a use case:

If I have a navigation aside, with menu links like so: 

```
const AsideMenuItem = ({ title, icon, to }) => {
  let match = useMatch(to);
  
  return (
      <ListItem
        component={Link}
        sx={{
          color: "primary.400",
          paddingLeft: "3.6rem",
          height: "5.6rem",
          "&:hover": {
            color: "primary.600",
          },
          "&.Mui-selected": {
            color: "primary.main",
            backgroundColor: "transparent",
          },
        }}
        to={to}
        selected={match ? true : false}
      >
        <ListItemIcon sx={{ minWidth: "3.2rem" }}>{icon}</ListItemIcon>
        <ListItemText>{title}</ListItemText>
      </ListItem>
 
  );
};```

and if that route was "/Devices" it would apply the active styling to the menu item, however if I go to "/Devices/:id" for example the styles are no longer applied to the menu item even though the parent route is still "Devices"

**Comment by timdorr** [comment]
`useMatch` is for matching a route pattern. You want to use `useResolvedPath` and just do simple string matching instead. You can crib [this code from NavLink](https://github.com/remix-run/react-router/blob/dev/packages/react-router-dom/index.tsx#L251-L263):

```js
    let location = useLocation();
    let path = useResolvedPath(to);
    let selected = location.pathname.startsWith(path.pathname);
```
