### ISSUE TITLE
[Bug]: Route children are no longer rendered

### ISSUE THREAD

**Issue by multiwebinc** [remix-run/react-router#8040]
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

I'm not sure if this is a bug or intentional, however in 6.0.0-beta.3, this worked:

```jsx
<Route path="path">
  <Component />
</Route>
```

However in 6.0.0-beta.4, rendering of children like this appears to have been removed, and you are now required to use the `element` property:

```jsx
<Route path="availability" element={<ReservationForm />} />
```

I don't see anything about this in the [release notes](https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.4).

### Expected Behavior

Unsure

### Actual Behavior

Children are no longer rendered.

**Comment by timdorr** [comment]
That is not intentional behavior and was probably a result of the "secret menu" behavior we had before. The migration guide mentions this: https://github.com/remix-run/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#upgrade-to-react-router-v6

**Comment by cooper667** [comment]
This caught me out to (although obviously I should have done it correctly in the first place)

Should there be an error or warning if a `Route` has a child passed to it?
