### ISSUE TITLE
[Bug]:  useParams types not satisfying string constraint

### ISSUE THREAD

**Issue by chaserda** [remix-run/react-router#8041]
### What version of React Router are you using?

v6.0.0-beta.4

### Steps to Reproduce

  ```const { id } = useParams<{ id: string }>();```
  
  Property 'id' does not exist on type 'Readonly<Params<{ id: string; }>>'
  Error: Type '{ id: string; }' does not satisfy the constraint 'string'.ts(2344)

### Expected Behavior

Type should satisfy useParams string constraint

### Actual Behavior

Type not satisfying useParams string constraint

**Comment by timdorr** [comment]
That's not the right type signature for the generic. See the release notes: https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.4

**Comment by chaserda** [comment]
@timdorr excuse my lack of understanding but is this not statically typing it as a string then?

 const { id } = useParams<"id">();
 
 Where I am passing it is expecting a string but it is erroring out because it says it can possibly be undefined obviously per the types however, I don't want undefined to be possible in the function I am passing id to.

**Comment by timdorr** [comment]
Yes, that is the correct form to use. The generic takes a string constant, which can be a union of several constants: `useParams<"id" | "team_id" | "user_id">()`. The value is always an optional string, so we don't let you override that. We only take the keys.
