### ISSUE TITLE
[Bug]: generatePath requires even optional parameters

### ISSUE THREAD

**Issue by labriola** [remix-run/react-router#8044]
### What version of React Router are you using?

v6.0.0-beta.4

### Steps to Reproduce

* Create a path expressing optional params
* Call generatePath without one of those optional params

`const blah = generatePath('/foo/:bar?', {});`

### Expected Behavior

This is tricky and perhaps there is a reason it should not work (multiple layers of params come to mind), but I would think that optional params would be pruned, ignore or otherwise not required in generatePath

### Actual Behavior

You will receive an error about the param missing

**Comment by timdorr** [comment]
Optional parameters aren't supported in v6: https://github.com/remix-run/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#note-on-route-path-patterns

**Comment by labriola** [comment]
Thank you for taking the time to respond. I missed the implication of that before, but appreciate the efforts
