### ISSUE TITLE
[Feature]: support "Named Routes"

### ISSUE THREAD

**Issue by bigmeow** [remix-run/react-router#8045]
### What is the new or updated feature that you are suggesting?

Hope to be designed like vue-router：
https://router.vuejs.org/guide/essentials/named-routes.html

### Why should this feature be included?

When I migrate the file path, in addition to changing the routing configuration, I also need to globally replace the "path" in all codes, which is very unreasonable

**Comment by TyroneYvesChen** [comment]
I have the same confusion. I think the feature is reasonable

**Comment by timdorr** [comment]
React Router doesn't have a centralized route config, so there's nothing to name. The architecture of this library makes it fundamentally impossible.

**Comment by gamegee** [comment]
@timdorr is that something you plan to implement in a future major version ?
Named route with typesafe path/search would be great for code maintenance in large codebase, also it helps developers to centralize their routes configuration

**Comment by timdorr** [comment]
Nope, but you're free to set something up using `useRoutes`: https://github.com/remix-run/react-router/blob/v6.0.0-beta.4/docs/advanced-guides/migrating-5-to-6.md#use-useroutes-instead-of-react-router-config

**Comment by gamegee** [comment]
I read a bit about useRoutes and relative routing, good job 🎉 
I am wondering if I can by myself add the abstraction I want to do something like this:

```tsx
const elements = useRoutes([
    { name: 'root', path: "/", element: <Index  /> },
    {
      name: 'path1'
      element: <Path1  />,
      children: [
        {
          name: 'path1Index'
          path: "/",
          element: <Path1Index  />
        },
        {
          name: 'path1ById'
          path: "/:id",
          element: <Path1Id  />
        }
      ]
    }
  ]);
```

Then when I want to navigate:
```tsx
// using JSX
<Navigate toRouteName="path1ById" /> // typescript error missing pathParams with property id
<Navigate toRouteName="path1ById" pathParams: { id: 123 } />

// using programmatic routing
history.push({ routeName: "path1ById", pathParams: { id: 123 } })
```

**Comment by gamegee** [comment]
I know this issue is closed, but I was trying to do a small wrapper on top of react-router v6, but it's kinda hard since the architecture does not allow you to export `<Route>` wrappers.

But the wrapper may work for :
- Custom typed hooks
- <Link> wrappers
- <Navigate> wrappers


```tsx
const { routeApi, Routes, Links } = defineRouterConfig({
  routes: {
    user: defineRoute<{pathParams: {id: string}}>({ path: '/users/:id' }),
    books: defineRoute<{searchParams: {filter: boolean}}>({ path: '/books' })
  }
})

const MyApp = () => {
  const { id } = routeApi.userPage.useParams() // typed with { id: string }
  const [params] = routeApi.books.useSearchParams() // typed with { filter: boolean }

  return (
    <div>
      <Routes>
        <Routes.User element={User} />
        <Routes.Books element={Books} />
      </Routes>
      
      <Links.User /> // no need to pass path props
    </div>
  );
}
```
