### ISSUE TITLE
Duplicate active link on NavLink

### ISSUE THREAD

**Issue by mtr1990** [remix-run/react-router#8046]
### What version of React Router are you using?

^6.0.0-beta.4

### Steps to Reproduce

Using props 'end' 

```js
  <NavLink end style={({ isActive }) => ({ color: isActive ? 'green' : 'blue' })} to={item.path}>
            {item.name}
          </NavLink>
```

+ **Home** > 
+ **About** => Not Active when  'About 1' or  'About 2' Selected
   - About 1 => 
   - About 2
+ **Contact**

https://codesandbox.io/s/react-router-forked-64hrx?file=/index.js 

---

Not Using props 'end' 

```js
  <NavLink style={({ isActive }) => ({ color: isActive ? 'green' : 'blue' })} to={item.path}>
            {item.name}
   </NavLink>
```

+ **Home** > =>  Active when  'About 1' or  'About 2' Selected
+ **About** => Active when  'About 1' or  'About 2' Selected
   - About 1 => 
   - About 2
+ **Contact**

https://codesandbox.io/s/react-router-forked-j7ygu?file=/index.js

### Expected Behavior

+ **Home**
+ **About** => Active only when  'About 1' or  'About 2' Selected
   - About 1
   - About 2
+ **Contact**

### Actual Behavior

Please help with this case, Thanks!

**Comment by timdorr** [comment]
You need to render your "Home" link with the `end` prop. It's matching all routes otherwise.
