### ISSUE TITLE
[Bug]: Active no longer triggered after lib update

### ISSUE THREAD

**Issue by Nico924** [remix-run/react-router#8047]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

After I updated the library (both router & router-dom to 5.3.0), I switched as explained in the release log from static className to function className for the NavLink with the isActive parameter that I logged in the following printscreen.

![image](https://user-images.githubusercontent.com/3044305/133575649-6a3ad171-b2cf-463f-a115-7722242d6d62.png)

I have obviously the same result if I go to the other pages and if I use the NavLink activeClassName param.

As a workaround, I wrote my own isActive function to make it work but I have no idea why it stopped working with the "normal" way
Does someone have any idea ? 
This is my isActive function where to is the routes that are logged above.
`
isActive={(match, loc) => {
            if (loc.pathname === to && exact) return true;
            if (loc.pathname.indexOf(to) >= 0) return true;
            return false;
}}
`

### Expected Behavior

Having either NavLink className with isActive param or activeClassName working.

### Actual Behavior

NavLink className isActive param is always false and activeClassName is never triggered while being on the right route.

**Comment by timdorr** [comment]
First, I think that `isActive` function is probably redundant. It's roughly describing how NavLink works right now.

Can you share more of your `<NavLink>` usage? I'm not seeing what's wrong here, but that may be because I can't see the full set of props you're using.

**Comment by Nico924** [comment]
Hello @timdorr, thank you for your reply. I finally found the solution and it was absolutely not linked to react-router. 

For the record, it was linked to a wrong webpack dependencies config that was not allowing my vendor bundle to take node_modules inside of node_modules (that happens when different deps need different version of the same package).
A nightmare to understand but now everything is working well 👍
