### ISSUE TITLE
[Feature]: Exact path matches on Route

### ISSUE THREAD

**Issue by CrankyUnicorn** [remix-run/react-router#8051]
### What is the new or updated feature that you are suggesting?

I think that Route should be created with the intend of always search for an exact path. 

### Why should this feature be included?

In a sense it should follow the same logic as node.js routing for ease of use.

Also since Switch/exact is used for more complex structures it would make more sense. 
'exact' shouldn't be needed but rather there should exist as  a reverse function as 'matchFirst'. 

Since replacing the functionality of this functions is not possible a new one could be created to so. 
'ExactRoute' could be a possible name since it describes clearly what it does.

**Comment by mjackson** [comment]
I agree that the default behavior is confusing in v5. We fixed it in v6. In v5 you should use `<Route exact>` if you want exact matching behavior.

**Comment by jampy** [comment]
So, how to match a non-exact route (`matchFirst` as called here)?

I want...
```
<Route path="/info" element={<InfoModule/>} />
```

...to also match `/info/contact`.

**Comment by jampy** [comment]
Okay, I think I figured it out by reading through the source code.

Apparently one has to add a trailing `/*` in such cases:

```
<Route path="/info/*" element={<InfoModule/>} />
```

I could not find that in the documentation.
