### ISSUE TITLE
[Bug]: Returning Route from component not working.

### ISSUE THREAD

**Issue by danyhiol** [remix-run/react-router#8054]
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

https://codesandbox.io/s/youthful-minsky-2q8rp?file=/src/App.js:455-459

### Expected Behavior

1. Create a react component return a `Route`:

`const Test = () => <Route path="test" element={<h2>TEST</h2>} />;`

2. Render component inside `Routes`

```
<Routes>
      ...
      <Test />
</Routes>
```
3. Go to /test.
Test should be rendered on route chancge.

### Actual Behavior

Test is not rendered. 

Just occurred since the last update.

**Comment by timdorr** [comment]
Duplicate of #8050
