### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by SohelIslamImran** [remix-run/react-router#8055]
### What version of React Router are you using?

^5.3.0

### Steps to Reproduce

.

### Expected Behavior

.

### Actual Behavior

×
TypeError: Cannot read properties of undefined (reading 'pathname')
createPath
C:/Development/Web/Projects/shopkpr/node_modules/history/esm/history.js:47
  44 |   };
  45 | }
  46 | function createPath(location) {
> 47 |   var pathname = location.pathname,
  48 |       search = location.search,
  49 |       hash = location.hash;
  50 |   var path = pathname || '/';
![image](https://user-images.githubusercontent.com/76745339/133938691-340530b1-3122-4d0d-ad3d-66bfd8c27e8a.png)

**Comment by YuanTian1991** [comment]
I encountered the same error in **react-router-dom. 5.3.0**. Then I downgraded it into **5.2.0**, no errors anymore. I don't know the detail though...
