### ISSUE TITLE
[Bug]: useParams type has changed from `string` to `string | undefined`

### ISSUE THREAD

**Issue by tim-field** [remix-run/react-router#8056]
### What version of React Router are you using?

v6

### Steps to Reproduce

If I have a route `/:id`

### Expected Behavior

Its not possible for the component assigned to render with `id` as `undefined`  

### Actual Behavior

But since this PR was merged, id is typed as `string | undefined` 

https://github.com/remix-run/react-router/pull/8019#issuecomment-913301835

This is breaking a fair few things for us, and AFAIK its not possible to have optional parameters in V6 so the `undefined` type here isn't correct ?

**Comment by timdorr** [comment]
v6 is still in beta, so breaking changes are still acceptable.

Regardless, there's no way for the type system to know at compile time (not run time) that the provided URL *must* include that parameter. Hence, to avoid bugs from the type system lying to you, it should be marked as Optional.
