### ISSUE TITLE
[Feature]: Shallow routing

### ISSUE THREAD

**Issue by nanafan93** [remix-run/react-router#8058]
### What is the new or updated feature that you are suggesting?

I want to be able to do` history.push(url)` without causing the component to remount. 
Something like https://nextjs.org/docs/routing/shallow-routing.

### Why should this feature be included?

I want to have sub-routes which depend on big queries which I don't want to run every time the history props change in my component. 
Something like 
```javascript
const MyComponent: React.FC<RouteComponentProps> = ({history}) => {
  const {data,loading,error} = someExpensiveQuery({...});
  return(
    <Switch>
     <Route path='/somePath'>
     // A huge list of all items in expensive query onClick = history.push('path to below component')
     <Route path='somePath/edit/27523'>
    // A component to edit ONE of the items in the big list
    </Switch>
)}
```

**Comment by timdorr** [comment]
This isn't something React Router can do because it doesn't manage state data like that. Next.js can do it because they do provide a data fetching/management solution. It's up to you as to how to handle this. Something like a Redux store would be a common solution.

**Comment by mvattuone** [comment]
@timdorr Is this still true?

I'm just thinking, now that we have `loaders` and seemingly there is a data fetching/management solution now, is that something that could be considered?

For example, something like `useSearchParams(newParams, { shallow: true })`
