### ISSUE TITLE
[v5.2.1][Bug]: Broken backward compatibility with v5.2.0

### ISSUE THREAD

**Issue by jyte** [remix-run/react-router#8059]
### What version of React Router are you using?

v5.2.1

### Steps to Reproduce

I don't really know, my app just fail with v5.2.1

### Expected Behavior

That my app work with 5.2.1 like it does with 5.2.0

### Actual Behavior

![image](https://user-images.githubusercontent.com/7738906/134194257-11d3bb67-7545-4c54-ae30-842c9bb8ea5e.png)

I can provide more info if you guide me to look for some more specific things

**Comment by timdorr** [comment]
You likely have mixed versions of react-router and react-router-dom. Make sure they are the exact same version, as they need to communicate via the same Context instance. 

You can find duplicate or mis-matched versions with `npm ls react-router`.

**Comment by jyte** [comment]
That was it. I had the following in my package.json

```
"react-router": "5.2.0",
"react-router-dom": "^5.2.0",
```
which led to 
```
npm ls react-router
...
├── react-router@5.2.0 
└─┬ react-router-dom@5.3.0
  └── react-router@5.2.1 
```

Would using the following always work ?
```
"react-router": "^5.2.0",
"react-router-dom": "^5.2.0",
```
or should I rather fix the version completely by removing ^ character ?

**Comment by Gjb7598189** [comment]
> 你可能有 react-router 和 react-router-dom 的混合版本。确保它们是完全相同的版本，因为它们需要通过相同的 Context 实例进行通信。
> 
> 您可以找到重复或不匹配的版本`npm ls react-router`。



> You likely have mixed versions of react-router and react-router-dom. Make sure they are the exact same version, as they need to communicate via the same Context instance.
> 
> You can find duplicate or mis-matched versions with `npm ls react-router`.

so, why react-router-dom@5.3.0 depend on react-router@5.2.1 ?
