### ISSUE TITLE
[v6][Feature]: Type assigned to ```path``` 'string[]' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by julioflima** [remix-run/react-router#8064]
### What is the new or updated feature that you are suggesting?

I was using this amazing feature in **v5**, pretty good could have more and one route for the same component. Follow in below a case of use.

But **v6** is so better, so I migrate, but getting there, I got a typescript error saying that I couldn't use multiple paths to a ```<Route/>``` anymore.

#### Error:
``` typescript
Type 'string[]' is not assignable to type 'string'.ts(2322)
index.d.ts(68, 5): The expected type comes from property 'path' which is declared here on type 'IntrinsicAttributes & RouteProps'
(JSX attribute) RouteProps.path?: string | undefined
No quick fixes available
```

#### Case of use:
``` typescript
import React from 'react';
import { Route } from 'react-router-dom';
import Home from 'src/pages/home';

const HomeRoute = (): JSX.Element => (
  <Route path={['/', '/home']}>
    <Home />
  </Route>
);

export default HomeRoute;
```

### Why should this feature be included?

Should be included because was included before in Version 5.2.0. I could be wrong, but I think if there isn't any business rule in architecture that could avoid that, this is kind of simple.

I'd like to do it and sent a PR if this is not scheduled to be delivered yet.

Follow in below the reference of the previous feature:
https://reacttraining.com/react-router/web/api/Route/path-string-string

**Comment by timdorr** [comment]
This is only a feature of v5 because of the underlying matching library we used in that version (path-to-regexp). We're no longer using that library in v6, so we don't have support for that feature anymore.

**Comment by exKAZUu** [comment]
@timdorr How can we achieve to render a same component (with a single component instance) from multiple paths in v6?

**Comment by zandiarash** [comment]
> @timdorr How can we achieve to render a same component (with a single component instance) from multiple paths in v6?

I have same question.
Can Someone help please?
