### ISSUE TITLE
[Bug]: License violation: NPM packages are missing LICENSE files

### ISSUE THREAD

**Issue by PhilippWendler** [remix-run/react-router#8075]
### What version of React Router are you using?

5.2.1

### Steps to Reproduce

Download [NPM package `react-router` 5.2.1](https://registry.npmjs.org/react-router/-/react-router-5.2.1.tgz) from the registry and open it.

### Expected Behavior

The package should contain a `package/LICENSE` file (next to `package/package.json`).

Shipping the full text of the MIT license in the package is actually required by the license:
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

### Actual Behavior

The package does not contain a `LICENSE` file in any location, nor is the full license text and copyright notice available anywhere else (`package.json`, `README.md`, etc.).

The package [`react-router 5.2.0`](https://registry.npmjs.org/react-router/-/react-router-5.2.0.tgz) does contain the `LICENSE` file, so this is a recent change.

Note that the same problem also exists at least for `react-router-dom` 5.3.0 (and probably all other packages created from this repository after 5.2.0).

**Comment by timdorr** [comment]
Looks like this was a subtle Lerna feature that we had when we were using it to publish. I'll pop the LICENSE files into the package directories as a quick fix.

@chaance Do we want to add back in Lerna to the publish process? I know you've got something custom now, but any reason it can't manage that process for us?

**Comment by michaelbull** [comment]
Any update on this? I am using this in conjunction with the `license-webpack-plugin` and it's failing to fetch the full LICENSE fill because it's not shipped to npm anymore.

**Comment by chaance** [comment]
Added in v5.3.1
