### ISSUE TITLE
[Bug]: useParams behavior different when upgrading from 6.0.0-beta.4 to 6.0.0-beta.5

### ISSUE THREAD

**Issue by multiwebinc** [remix-run/react-router#8083]
### What version of React Router are you using?

6.0.0-beta.5

### Steps to Reproduce

I have the following routes.

```jsx
  <Router>
    <Routes>
      <Route path="/" element={<NoProperty />} />
      <Route
        path="/:property/*"
        element={
          <LanguageWrapper>
            <Provider store={store}>
              <App />
            </Provider>
          </LanguageWrapper>
        }
      />
    </Routes>
  </Router>
```

Then in a sub-component:

```
const params = useParams();
```

### Expected Behavior

`params` should contain the `property` property. This was the behavior in 6.0.0-beta.4. Previously, I did the following to extract the `property` property:

```
const { property } = useParams();
```

### Actual Behavior

If you do:

```
const params = useParams();
```
`params` is  `{*: ''}`

It does not contain a `property` property.

**Edit (FYI):**

If I do the following in the subcomponent:

```
const match = useMatch('/:property');
```

Then `match.params.property` contains the correct value.

**Comment by andycarrell** [comment]
@mjackson - can confirm this is fixed (at least in my project) 🙌  Thanks

**Comment by multiwebinc** [comment]
@mjackson Yes, it appears to be fixed now. Thanks.
