### ISSUE TITLE
[Bug]: URIError: Pathname "/-^&^%&^%" could not be decoded. This is likely caused by an invalid percent-encoding.

### ISSUE THREAD

**Issue by syamjayaraj** [remix-run/react-router#8084]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

category_permalink: "-^&^%&^%"

### Expected Behavior

URIError: Pathname "/-^&^%&^%" could not be decoded. This is likely caused by an invalid percent-encoding.

### Actual Behavior

URIError: Pathname "/-^&^%&^%" could not be decoded. This is likely caused by an invalid percent-encoding.

**Comment by timdorr** [comment]
We don't decode pathnames for you. That is an invalid pathname without encoding. You should run it through `encodeURIComponent`.
