### ISSUE TITLE
[Bug]:  Please keep the functionality that allowed custom Route components 

### ISSUE THREAD

**Issue by tim-field** [remix-run/react-router#8101]
### What version of React Router are you using?

6

### Steps to Reproduce

This pattern is common and has a number of advantages.

```TS
type RouteProps = {
  path: string
  render: (params: Params) => JSX.Element | null
}

const Route = ({render}: RouteProps) => {
  const pathParams = useParams()

  return render(pathParams)
}

<Routes>
    <Route path="/" render={() => <FrontPage />} />
    <Route path="/feature/:id" render={({id}) =>  <Feature id={id} />}  />
</Routes>
```

1.  Most importantly The `<Feature` component doesn't need to know about react-router, it doesn't have to run somewhere where `useParams` can be called. 
2. This enables people to easily build authentication checks ( yes work arounds exist, also large `@reach/router` apps are being converted to `react-router` and depend on the existing behavior )  behavior that existed in recent betas.
3. This technique provides some level of proxy to shelter from React Routers never ending rewrites  

The change to strictly render RR routes breaks a lot of things, please consider the large user base of this library, and those moving from Reach

### Expected Behavior

A custom Route implementation renders

### Actual Behavior

Nothing rendered, no console warnings, wailing and gnashing of teeth 

#8033 #8066

**Comment by mjackson** [comment]
> please consider the large user base of this library, and those moving from Reach

I just want to assure you that almost all of our conversations around v6 have some component of "how do we make this easy for people to upgrade from v5/Reach?". It is something we think about constantly.

We are working on backwards compat libraries for both v5 users and Reach Router users. We'll have more to say about it very soon. If you can wait to upgrade to v6, I'd recommend waiting a bit. We are still in beta. v5 and Reach will continue to be supported in the meantime.
