### ISSUE TITLE
[Bug]: `useLocation()` can crash when `useContext(RouterContext)` returns undefined

### ISSUE THREAD

**Issue by MarcelWaldvogel** [remix-run/react-router#8104]
### What version of React Router are you using?

5.2.1

### Steps to Reproduce

I have a component watching for location changes. When switching from `useHistory()` to the more appropriate `useLocation()`, the app started crashing *inside `useLocation()`*, with `TypeError: useLocation(…) returning undefined`. Apparently, during initial renders, `RouterContext` may be undefined and dereferencing `.location` can therefore fail.

I fixed it by monkey-patching [the `useLocation()` hook](https://github.com/remix-run/react-router/blob/main/packages/react-router/modules/hooks.js#L29) to `return useContext(RouterContext)?.location;` (and also `.match` further down).

However, today, I cannot reproduce this anymore. Nevertheless, the question marks might be prudent to add.

But I would not be upset if, after someone with more React experience had a look at it, you decided this was a spurious behavior on my side and closed this issue without action.

### Expected Behavior

Always return a valid value (or at least `undefined`/`null`).

### Actual Behavior

Throws an exception.

**Comment by timdorr** [comment]
We actually do have this solved in v6, so a fix is coming when that releases: https://github.com/remix-run/react-router/blob/v6.0.0-beta.5/packages/react-router/index.tsx#L415-L420
