### ISSUE TITLE
[Feature]: Support for mixing BrowserRouter and HashRouter in v6

### ISSUE THREAD

**Issue by tomekpaszek** [remix-run/react-router#8108]
### What is the new or updated feature that you are suggesting?

I'm currently mixing both BrowserRouter and HashRouter to achieve links like: `:repository/:branch#overview-:id` 
In v6 when trying to use both router I'm getting `You cannot render a <Router> inside another <Router>. You never need more than one.` message. Would a scenario where you can use both browser and hash routing be possible in the new version?

### Why should this feature be included?

To be able to cover scenario mentioned above

**Comment by timdorr** [comment]
This is fundamentally not possible because there are two different `history` implementations and instances under the hood. They don't compose together. I'm not sure how you have that working, as the context from one Router is going to be overwritten by the next descendant Router.
