### ISSUE TITLE
[Bug]: history.push results in empty search value

### ISSUE THREAD

**Issue by D-Pagey** [remix-run/react-router#8119]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

1. Navigate to any route with a query param in the url
2. User click to navigate to a different url with a query parameter
```
history.push(`www.example.com/some/route?target=${uuid}`)
```
3. The location.search field will be empty in the route despite being in the url

![Screenshot 2021-10-08 at 11 06 45](https://user-images.githubusercontent.com/26827986/136538810-566908c4-648f-43aa-8a97-6798721b5faa.png)

### Expected Behavior

The search field should be populated with `?target=dad...` and not empty

### Actual Behavior

The search field is empty

**Comment by timdorr** [comment]
I just tested this and it works fine. If you can recreate it on codesandbox, it's something we can look into. But I believe the issue isn't with the library.
