### ISSUE TITLE
[v6] [Bug]: auth example has no index route

### ISSUE THREAD

**Issue by lucasvienna** [remix-run/react-router#8120]
This fix broke the newly released auth example: it doesn't render anything since there is no index route for that example.

The other examples with a layout (basic and SSR) do work, as they have `'/'` as the layout path and an index route.

### What version of React Router are you using?

6.0.0-beta.6

### Steps to Reproduce

Open the new auth example (https://github.com/remix-run/react-router/tree/dev/examples/auth) on stackblitz and wait for it to install and launch the dev server.

### Expected Behavior

The example should render correctly.

### Actual Behavior

The page is blank and the console spits out "No routes match '/'".

**Comment by mjackson** [comment]
This was fixed in ee21f9f
