### ISSUE TITLE
Does v6 drop support for class components?

### ISSUE THREAD

**Issue by AbrahamLopez10** [remix-run/react-router#8146]
First of all, thank you for making react-router available to the world :)

I'm not sure if this is the best place to ask about this but given that this is monitored by the maintainers I figured I could put my question here.

My question is around the fact that based on the currently available documentation for v6 (the migration/upgrade guide) react-router v6 seems to drop out-of-the-box support for class components and all the codebases that already have plenty of them (like ours) due to the following changes:

1. Dropping support for the `render` prop in the `Route` component, which we are using with react-router v5 to pass params to the component (through `props.match.params`) of the route.

2. Replacing the use of `History` (which was passed as a prop to our components automatically in v5) with the new `NavigateFunction` and the fact that it's only available through the `useNavigate` hook which of course is not accessible to class components.

Could someone shed the light on this and the future of react-router for all of us who are using class components and will most likely stick with using them for the foreseeable future?

Thanks in advance.

**Comment by afoures** [comment]
I think that they are aware of this, and willing to do their best to make the transition as smooth as possible, check this tweet: https://twitter.com/mjackson/status/1448107013741989888?s=20

**Comment by timdorr** [comment]
Hooks are the preferred API nowadays and are the main API surface in v6. The easiest way to get access to them is the same as any other hook, just wrap your class component with a functional component that passes along hook values as props:

```js
const WrappedComponent = props => {
  const history = useHistory()
  const location = useLocation()

  return <Component history={history} location={location} {...props} />
}
```

You can also use more generic HOCs, like `withRouter` from v5, to pass along hooks to any component. This applies to any hook, not just React Router's.

**Comment by timdorr** [comment]
I don't know if it will be available in v6. Likely it will be provided in some sort of support package to aid with the transition to the v6 APIs (`react-router-compat`, `react-router-extras`, or something like that).

**Comment by AbrahamLopez10** [comment]
@mjackson Many thanks for the detailed clarification and the specific examples you provided, they were really helpful to clear my doubts.

I think if this info could be included in the v6 documentation to give peace of mind and direction to other developers who want or need to stick with class components it would be awesome so no one is left confused or discouraged by the hooks-centric approach in v6 😄

**Comment by ynhhoJ** [comment]
Working example using Typescript:

```tsx
// hoc.tsx

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';

export const withParams = (WrappedComponent) => function (properties) {
  const parameters = useParams();
  // etc... other react-router-dom v6 hooks

  return (
    <WrappedComponent
      {...properties}
      params={parameters}
    />
  );
};

export const withNavigation = (WrappedComponent) => function (properties) {
  const parameters = useNavigate();

  return (
    <WrappedComponent
      {...properties}
      params={parameters}
    />
  );
};
```

```tsx
import { withParams } from './hoc';

class App extends React.Component<Properties, State> {
// ...
}

export default withParams(App);
```

**Comment by paztis** [comment]
It is easy to type it in javascript.
But less in typescript. Can you provide the correct signature for this ?

something like this ?
```
function withParams(Component: ComponentClass<P>): ComponentClass<Omit<P, 'params'>> {
  return props => <Component {...props} params={useParams()} />;
}
```

**Comment by yazdog8** [comment]
> We are absolutely not dropping support for class-based components, @AbrahamLopez10, but I think the API changes you pointed out do tend to illustrate some of the value of hooks.
> 
> For example, in a world without hooks it makes a lot of sense to use render props instead of a hook. This is because the router knows some state and it needs a way to expose it to you so it can pass it through to your component, so a render prop makes it easy to do so.
> 
> ```tsx
> <Route
>   path="posts/:id"
>   render={({ match }) => <BlogPost id={match.params.id} />}
> />
> 
> class BlogPost extends React.Component {
>   render() {
>     let { id } = this.props;
>     // ...
>   }
> }
> ```
> 
> However, in a world with hooks, we don't need a render prop for exposing state. Instead, you can just use the hook in your component directly.
> 
> ```tsx
> <Route path="posts/:id" element={<BlogPost />} />
> 
> function BlogPost() {
>   let { id } = useParams();
>   // ...
> }
> ```
> 
> In addition to eliminating the need for render props for sharing state, hooks also eliminate a lot of other prop-passing boilerplate code in other components that are rendered by `<BlogPost>`. For instance, without hooks if you wanted to pass the `id` URL param down to another component, you'd probably do something like this:
> 
> ```tsx
> class BlogPost extends React.Component {
>   render() {
>     return (
>       <div>
>         <PostHeader id={this.props.id} />
>         {/* ... */}
>       </div>
>     );
>   }
> }
> 
> class PostHeader extends React.Component {
>   render() {
>     let { id } = this.props;
>     // ...
>   }
> }
> ```
> 
> But with hooks, it's as simple as:
> 
> ```tsx
> function BlogPost() {
>   return (
>     <div>
>       <PostHeader />
>       {/* ... */}
>     </div>
>   );
> }
> 
> function PostHeader() {
>   let { id } = useParams();
>   // ...
> }
> ```
> 
> Anyway, that's my sales pitch for using hooks. I totally understand if you don't want to use them, but I think you could probably eliminate some of the boilerplate from your code if you did.
> 
> As for shipping a `withRouter`-style HOC with v6, we can probably do that if you really need one. But we would probably spend a bunch of time bike-shedding all the stuff you want to include in your HOC props (do you want the history? the match? just the params?) when in reality it's **really easy** to just make your own HOC that is custom designed for the pieces you need.
> 
> For example, you could make your own `withNavigation` or `withParams` HOC in a one-liner (again, thanks to the power of hooks!):
> 
> ```tsx
> // in hocs.js
> function withNavigation(Component) {
>   return props => <Component {...props} navigate={useNavigate()} />;
> }
> 
> function withParams(Component) {
>   return props => <Component {...props} params={useParams()} />;
> }
> 
> // in BlogPost.js
> class BlogPost extends React.Component {
>   render() {
>     let { id } = this.props.params;
>     // ...
>   }
> }
> 
> export default withParams(BlogPost);
> ```
> 
> Hopefully that helps you understand what we are thinking with v6. It's a low-level library and the hooks are a nice low-level abstraction that should allow you to build whatever you can think of and use whatever API you're most comfortable with, even if you decide to stick with class components.

For some of us it's a matter of transitioning a code base that had used class to use hooks and it all can't be transitioned at once. We need the support for classes until we can remove them in favor of all hooks. This is common for a multitude of code bases.

**Comment by tumisangStarfire** [comment]
if you ever get stuck 
//hooks js
import React,{ Component} from "react";
import { useNavigate } from "react-router-dom";
export const  withNavigation = (Component : Component) => {
  return props => <Component {...props} navigate={useNavigate()} />;
} 

//classComponent  
class LoginPage extends React.Component{

submitHandler =(e) =>{
  //successful login 
this.props.navigate('/dashboard');
}
}
 export default withNavigation(LoginPage);

**Comment by jefferson-liew** [comment]
> if you ever get stuck
> 
> ```js
> import React,{ Component} from "react";
> import { useNavigate } from "react-router-dom";
> 
> export const  withNavigation = (Component : Component) => {
>   return props => <Component {...props} navigate={useNavigate()} />;
> } 
> 
> //classComponent  
> class LoginPage extends React.Component{
> 
> submitHandler =(e) =>{
>     //successful login 
>     this.props.navigate('/dashboard');
>   }
> }
>  export default withNavigation(LoginPage);
> ```

Is there a javascript alternative for this?

**Comment by kikonen** [comment]
> if you ever get stuck
> 

Ah thanks for this, took plenty of time on some strong words until finally finding this and getting react router to work. While it might sound.

**Comment by TechQuery** [comment]
Official dropped, but we the people save ourselves: https://github.com/idea2app/React-Router-class-tools

**Comment by MDGFUKAS** [comment]
@paztis... this works for me

```tsx
export const withRouter = (Component: React.ComponentType<any>) => {
  const WithRouter = (props: any) => {
    const location = useLocation();
    const navigate = useNavigate();
    const params = useParams();
    return <Component {...props} location={location} navigate={navigate} params={params} />;
  }
  return WithRouter;
}
```

**Comment by paztis** [comment]
> @paztis... this works for me
> 
> ```tsx
> export const withRouter = (Component: React.ComponentType<any>) => {
>   const WithRouter = (props: any) => {
>     const location = useLocation();
>     const navigate = useNavigate();
>     const params = useParams();
>     return <Component {...props} location={location} navigate={navigate} params={params} />;
>   }
>   return WithRouter;
> }
> ```

Any is not a solution in typescript.

**Comment by TechQuery** [comment]
> Official dropped, but we the people save ourselves:
> 
> * https://github.com/idea2app/React-Router-class-tools
> * https://codesandbox.io/s/react-class-router-1y99mv?file=/src/Detail.tsx

@MDGFUKAS You may use my package directly.

@paztis You may create a pull request to my package to enhance the generic of it.

**Comment by davidhicks980** [comment]
Here is an alternative that uses generics. Let me know if there are any issues.

```tsx

//Can add or remove props as needed
interface RouterProps {
  navigate: NavigateFunction;
  readonly params: Params<string>;
  location: Location;
}

export type WithRouterProps<T> = T & RouterProps;

export function withRouter<T>(Component: React.ComponentType<WithRouterProps<T>>) {
  return (props: T) => {
    const location = useLocation();
    const navigate = useNavigate();
    const params = useParams();
    return (
     //Keep in mind that you will override navigation if you pass in redundant props
     //Feel free to add error handling as needed
      <Component
        location={location}
        navigate={navigate}
        params={params}
        {...props}
      />
    );
  };
}

/************* 
    Usage 
 *************/

interface TestProps {
  howdy: boolean;
  partner: boolean;
}

interface TestState {
  howdyPartner: string;
}

class TestComponent extends React.Component<
  WithRouterProps<TestProps>,
  TestState
> {
  state = { howdyPartner: "" };
  render() {
    return <h1>{this.props.location.pathname}</h1>;
  }
}

export default withRouter(TestComponent);
```

**Comment by RichardTMiles** [comment]
> Here is an alternative that uses generics. Let me know if there are any issues.
> 
> ```tsx
> interface RouterProps {
>   navigate: NavigateFunction;
>   readonly params: Params<string>;
>   location: Location;
> }
> 
> export type WithRouterProps<T> = T & RouterProps;
> type OmitRouter<T> = Omit<T, keyof RouterProps>;
> 
> export function withRouter<T>(
>   Component: ComponentType<OmitRouter<T> & RouterProps>
> ) {
>   return (props: OmitRouter<T>) => {
>     const location = useLocation();
>     const navigate = useNavigate();
>     const params = useParams();
>     return (
>       <Component
>         location={location}
>         navigate={navigate}
>         params={params}
>         {...props}
>       />
>     );
>   };
> }
> 
> 
> /************* 
>     Usage 
>  *************/
> 
> interface TestProps {
>   howdy: boolean;
>   partner: boolean;
> }
> 
> interface TestState {
>   howdyPartner: string;
> }
> 
> class TestComponent extends React.Component<
>   WithRouterProps<TestProps>,
>   TestState
> > {
>   state = { howdyPartner: "" };
>   render() {
>     return <h1>{this.props.location.pathname}</h1>;
>   }
> }
> 
> export default withRouter(TestComponent);
> ```

TS2322: Type '{ location: Location; navigate: NavigateFunction; params: Readonly<Params<string>>; } & OmitRouter<T>' is not assignable to type 'IntrinsicAttributes & OmitRouter<T> & RouterProps'.   Type '{ location: Location; navigate: NavigateFunction; params: Readonly<Params<string>>; } & OmitRouter<T>' is not assignable to type 'RouterProps'.     Types of property 'location' are incompatible.       Type 'Location' is missing the following properties from type 'Location': ancestorOrigins, host, hostname, href, and 6 more.

______________________________________

This backward incompatible lack-of-support for class components is rough.  Completely not a fan.

```
passPropertiesAndRender = (Component: React.ElementType, props: object = {}) => {

        return <Component
            authenticate={this.authenticate}
            changeLoggedInStatus={this.changeLoggedInStatus}
            codeBlock={this.codeBlock}
            semaphoreLock={this.semaphoreLock}
            passPropertiesAndRender={this.passPropertiesAndRender}
            setCurrentUserObject={this.setCurrentUserObject}
            switchDarkAndLightTheme={this.switchDarkAndLightTheme}
            testRestfulPostPutDeleteResponse={this.testRestfulPostPutDeleteResponse}
            updateUser={this.updateUser}
            {...this.props}
            {...this.state}
            {...props} >
            <Outlet/>
        </Component>

}
....

return <BrowserRouter>
            <Routes>
                <Route path='/*' element={ppr(DropInGaming, {})}/>
                <Route path='wp-admin/*' element={ppr(WpAdmin, {})}/>
            </Routes>
            {alert}
            <ToastContainer/>
        </BrowserRouter>
}    
```


I pass all state/props down using a this wrapper method. I'm just trying to figure out this url...

**Comment by RichardTMiles** [comment]
```js
import React from 'react';

import {
    BrowserRouter,
    Outlet,
    Route,
    Routes,
    useLocation,
    useNavigate,
    useParams
} from "react-router-dom";

import swal from '@sweetalert/with-react';

import {toast, ToastContainer} from 'react-toastify';

import 'react-toastify/dist/ReactToastify.min.css';

.....

import {AxiosResponse} from "axios";
import WpAdmin from "src/components/WpAdmin/WpAdmin";

export function startInputChangeUpdateRoutine(
    shouldContinueAfterTimeout: () => boolean,
    cb: () => void,
    timeoutMs: number = 3000): () => void {

    const timer = () => setTimeout(() => {

        if (false === shouldContinueAfterTimeout()) {

            return;

        }

        cb();

    }, timeoutMs);

    const timerId = timer();

    return () => {
        clearTimeout(timerId);
    };

}

interface iBootstrapProperties extends iWebsocketState {
    children?: React.ReactNode | React.ReactNode[] | undefined;
}

interface iBootstrapState {
    id: string,
    axios: import("axios").AxiosInstance,
    authenticateURI: string,
    authenticated?: boolean,
    alert?: boolean,
    ....
}

interface iBootStrapPublicFunctions {
    authenticate: () => void,
    changeLoggedInStatus: () => void,
    codeBlock: (markdown: String, highlight: String, language: String, dark: boolean) => any,
    passPropertiesAndRender: (Component: React.ElementType, props?: object) => any,
    semaphoreLock: Function,
    switchDarkAndLightTheme: () => void,
    testRestfulPostPutDeleteResponse: (response: AxiosResponse, success: Function | string | null, error: Function | string | null) => boolean,
}

export type iAmBootstrapDescendant = iBootstrapProperties & iBootstrapState & iBootStrapPublicFunctions;

function withRouter(Component: React.ComponentType<any>) {
    return (props: any) => {
        const location = useLocation();
        const navigate = useNavigate();
        const params = useParams();
        return (
            <Component
                location={location}
                navigate={navigate}
                params={params}
                {...props}
            />
        );
    };
}

class Bootstrap extends React.Component<iBootstrapProperties, iBootstrapState> implements iBootStrapPublicFunctions {

    constructor(props) {

        super(props);

        const contextAxios = context.axios;

        contextAxios.interceptors.request.use(
            req => {
                if (req.method === 'get' && req.url.match(/^\/rest\/.*$/)) {
                    req.params = JSON.stringify(req.params)
                }
                return req;
            },
            error => {
                return Promise.reject(error);
            }
        );

        contextAxios.interceptors.response.use(
            response => {
                // Do something with response data
                console.log(
                    "Every Axios response is logged in Bootstrap.tsx :: ",
                    response
                );
                if (response?.data?.alert) {
                    console.log("alert ∈ response");
                    this.handleResponseCodes(response);
                    return (response?.data?.alert?.error || response?.data?.alert?.danger) ?
                        Promise.reject(response) :
                        response;
                }
                return response;
            },
            async error => {

                /* Do something with response error
                   this changes from project to project depending on how your server uses response codes.
                   when you can control all errors universally from a single api, return Promise.reject(error);
                   is the way to go.
                */
                this.handleResponseCodes(error.response);

                console.log("Carbon Axios Caught A Response Error response :: ", error.response);

                return Promise.reject(error); // return error.response;

            });

        this.state = {
            id: '',
            axios: context.axios,
            authenticateURI: '/authenticated/',
            authenticated: null,
            alert: false
        };

    }
 
    passPropertiesAndRender = (Component: React.ElementType, props: object = {}) => {

        return <Component
            authenticate={this.authenticate}
            changeLoggedInStatus={this.changeLoggedInStatus}
            codeBlock={this.codeBlock}
            semaphoreLock={this.semaphoreLock}
            passPropertiesAndRender={this.passPropertiesAndRender}
            setCurrentUserObject={this.setCurrentUserObject}
            switchDarkAndLightTheme={this.switchDarkAndLightTheme}
            testRestfulPostPutDeleteResponse={this.testRestfulPostPutDeleteResponse}
            updateUser={this.updateUser}
            {...this.props}
            {...this.state}
            {...props} >
            <Outlet/>
        </Component>

    }

    testRestfulPostPutDeleteResponse = (response: AxiosResponse, success: Function | string | null, error: Function | string | null): boolean => {

        if (undefined !== response?.data?.rest
            && (('created' in response.data.rest)
                || ('updated' in response.data.rest)
                || ('deleted' in response.data.rest))
        ) {

            if (typeof success === 'function') {

                return success(response);

            }

            if (success === null || typeof success === 'string') {

                toast.success(success, this.state.toastOptions);

            }

            return response.data.rest?.created ?? response.data.rest?.updated ?? response.data.rest?.deleted ?? true;

        }

        if (typeof error === 'function') {

            return error(response);

        }

        if (error === null || typeof error === 'string') {

            toast.success(error, this.state.toastOptions);

        }

        return false;

    };


    render() {

        console.log("BOOTSTRAP TSX RENDER");

        const {alert} = this.state

        // Routes that belong to the public and private sector
        if (false === this.state.isLoaded) {

            switch (window.location.hostname) {
                case 'localhost': {

                    const center = {
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        height: '100%',
                        '&:hover': {color: 'blue !important'},
                    };

                    const onMouseEnter = (e) => {
                        const target = e.target as HTMLElement;
                        target.style.backgroundColor = '#e13570';
                        target.style.border = '2px solid rgb(31, 0, 69)';
                        target.style.boxShadow = '-2px 0px 7px 2px #e13570';
                    };

                    const onMouseLeave = (e) => {
                        const target = e.target as HTMLElement;
                        target.style.backgroundColor = 'rgb(31, 0, 69)';
                        target.style.border = '2px solid #593676';
                        target.style.boxShadow = '-2px 0px 7px 2px #e13570';
                    };

                    return <>
                        <h1 style={center}>Whoa, where we dropping?</h1>
                        <a onMouseEnter={onMouseEnter}
                           onMouseLeave={onMouseLeave}
                           style={center} href={'//local.dropingaming.gg:3000/'}>GG</a>
                        <a onMouseEnter={onMouseEnter}
                           onMouseLeave={onMouseLeave}
                           style={center} href={'//local.dropingaming.com:3000/'}>COM</a>
                    </>;
                }

                default: {

                    const letUsBeHappyStyle = {
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        height: '100%'
                    };

                    if (this.state.bricked504) {

                        if ('3000' === window.location.port) {

                            return <>
                                <br/>
                                <h1 style={letUsBeHappyStyle}> 504 - Sorry friend, we are bricked!</h1>
                                <h1 style={letUsBeHappyStyle}>An unknown issue, programmed around, just to tell you to
                                    restart your computer.</h1>
                                <h1 style={letUsBeHappyStyle}>But first, make sure apache is running using (<b>sudo
                                    apachectl start</b>).</h1>
                                <h1 style={letUsBeHappyStyle}>@link
                                    https://github.com/netlify/create-react-app-lambda/issues/19</h1>
                            </>;

                        } else {

                            return <h1 style={{
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                height: '100%'
                            }}>504 - An unknown issue occurred, please contact us if this persists.</h1>

                        }

                    }

                    return <h1 style={letUsBeHappyStyle}>Dropping In...</h1>;
                }

            }

        }

        const ppr = this.passPropertiesAndRender;

        return <BrowserRouter>
            <Routes>
                <Route path='/*' element={ppr(withRouter(DropInGaming), {})}/>
                <Route path='wp-admin/*' element={ppr(withRouter(WpAdmin), {})}/>
            </Routes>
            {alert}
        </BrowserRouter>
    }

}

// @ts-ignore
export default Bootstrap;

```

^^ full call impl

**Comment by davidhicks980** [comment]
I think you replied with an error earlier which may have been removed. My mistake if you didn't! I saw it in my email. Make sure you are importing Location from "react-router-dom". Otherwise, let me know. I'll include in my implementation above.

It's different from the native window.Location (I had the same problem a while back)

```
import React, { ComponentType } from "react";
import {
  NavigateFunction,
  Params,
  useLocation,
  useNavigate,
  useParams,
  Location,
} from "react-router-dom";
```

**Comment by vijaya-lakshmi-venkatraman** [comment]
> if you ever get stuck
> 
> ```js
> import React,{ Component} from "react";
> import { useNavigate } from "react-router-dom";
> 
> export const  withNavigation = (Component : Component) => {
>   return props => <Component {...props} navigate={useNavigate()} />;
> } 
> 
> //classComponent  
> class LoginPage extends React.Component{
> 
> submitHandler =(e) =>{
>     //successful login 
>     this.props.navigate('/dashboard');
>   }
> }
>  export default withNavigation(LoginPage);
> ```

Thank you for this.
Please can you let me know how to pass data along with navigate() and then get it in the consuming class?

**Comment by rajat153** [comment]
how to use route props in render like:
{/* <Route path = "/food/:name" render={(props) => <Food text="Hello, " {...props} />} /> */}
i dont know why mine isnot working

**Comment by Johnne25** [comment]
Although its said support for Class Components isn't being dropped, the fact that you have to wrap your class in a HOC in order to get it to work doesn't support that statement.

**Comment by h110m** [comment]
@Johnne25 
Its like saying you not dropping it but dropping it...

**Comment by MTraveller** [comment]
> ```js
> const WrappedComponent = props => {
>   const history = useHistory()
>   const location = useLocation()
> 
>   return <Component history={history} location={location} {...props} />
> }
> ```

Works great, even dynamic components:

// Routes
```js
import MovieForm from "./components/movieForm";
import ElementWrapper from "./components/elementWrapper";

<Route path="/movies/new" element={<ElementWrapper routeElement={MovieForm} />} />
```
  
// Wrapper 
```js
import React from "react";
import { useLocation, useParams } from "react-router-dom";

const ElementWrapper = (props) => {
  const params = useParams();
  const locations = useLocation();
  const { routeElement } = props;

  return <routeElement params={params} locations={locations} {...props} />;
};

export default ElementWrapper;
```

**Comment by Hamadasatco** [comment]
I have this code but i couldn't update it i wrapped the shop Component with WithRoute it didn't work 
I don't know what Component should i wrap. 
Please help. 



import React, { Component } from "react"; import { Switch, Route, Redirect } from "react-router-dom" import { connect } from "react-redux"; import { loadData } from "../data/ActionCreators"; import { DataTypes } from "../data/Types"; import { Shop } from "./Shop";

const mapStateToProps = (dataStore) => ({ ...dataStore }) const mapDispatchToProps = { loadData } const filterProducts = (products = [], category) => (!category || category === "All") ? products : products.filter(p => p.category.toLowerCase() === category.toLowerCase()); export const ShopConnector = connect(mapStateToProps, mapDispatchToProps)( class extends Component { render() { return <Switch> <Route path="/shop/products/:category?" render={ (routeProps) => <Shop { ...this.props } { ...routeProps } products={ filterProducts(this.props.products, routeProps.match.params.category) } />} /> <Redirect to="/shop/products" /> </Switch> } componentDidMount() { this.props.loadData(DataTypes.CATEGORIES); this.props.loadData(DataTypes.PRODUCTS); } } )

**Comment by MTraveller** [comment]
> // I have this code but i couldn't update it i wrapped the // shop Component with WithRoute it didn't work 
> // I don't know what Component should i wrap. 
> // Please help. 
> 
> 
> 
> import React, { Component } from "react";
> import { Switch, Route, Redirect } from "react-router-dom";
> import { connect } from "react-redux"; 
> import { loadData } from "../data/ActionCreators"; import { DataTypes } from "../data/Types";
> import { Shop } from "./Shop";
> 
> const mapStateToProps = (dataStore) => ({
>  ...dataStore })
> 
> const mapDispatchToProps = {
>  loadData
>  } 
> 
> const filterProducts = (products = [], category) => (!category || category === "All") ? products : products.filter(p =>
> p.category.toLowerCase() === category.toLowerCase());
> 
> export const ShopConnector = connect(mapStateToProps, mapDispatchToProps)( class extends Component {
> render() {
> return <Switch> 
> <Route path="/shop/products/:category?" 
> render={ (routeProps) => 
> <Shop { ...this.props } { ...routeProps } products={ filterProducts(this.props.products, routeProps.match.params.category) } />} /> 
> <Redirect to="/shop/products" /> 
> </Switch> } 
> 
> componentDidMount() { this.props.loadData(DataTypes.CATEGORIES); this.props.loadData(DataTypes.PRODUCTS);
>  } } )

You are using react router v5 where as this thread is for v6.

**Comment by NickCarducci** [comment]
To be clear: 

>You [can't use Hooks inside a class component, but you can](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both) definitely mix classes and function components with Hooks in a single tree.

````
class App extends React.Component {render(){return <div/>}}
const ClassHook = () => {
  return <App paths={useParams()} l={useLocation()} n={useNavigate()} />;
}; // "cannot be called inside a callback" <Hook/>
createRoot(document.getElementById("root")).render(
  <BrowserRouter>
    <Routes>
      <Route
        //exact
        path="/*"
        //children,render
        element={<ClassHook />} //Initelement
      />
    </Routes>
  </BrowserRouter>
);
````

**Comment by Hamadasatco** [comment]
> 

thanks

**Comment by yhojann-cl** [comment]
I use react-router-dom 7.5 and for me is very hard redirect user to home when success login in login page. For now use a single `window.location.href ='/'`.
