### ISSUE TITLE
State is undefined at first rendering

### ISSUE THREAD

**Issue by myNameIsDu** [remix-run/react-router#8147]
## Version
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
## Test Case

https://stackblitz.com/edit/react-ts-z13elr?file=index.tsx

## Expected Behavior
State is undefined and there is no key attribute, which is not consistent with the documentation
## Actual Behavior
I think it can be compatible with the state "{}" to maintain the unity of the data, or remind users in the document

**Comment by timdorr** [comment]
The initial location is the one defined by the browser, which doesn't have a native concept of `key` and should have no `state` (that is application-defined). We're just copying it into the Router history as the first entry. You can use this to distinguish between a browser navigation and a Router navigation.
