### ISSUE TITLE
react router docs page via duckduckgo

### ISSUE THREAD

**Issue by mok-liee** [remix-run/react-router#8154]
hello, i hope it is okay to give my feedback via github issues.

i would let u know, that the page https://reactrouter.com/ is nearly impossible to find via duckduckgo's search engine.
i know the url is to easy and i can go directly, but often i use my search engine to find the official docs of something.

greetings mok

**Comment by timdorr** [comment]
Thanks, but I'm not sure how we would directly affect the results of a search engine. If we could do that, we would be a lot richer.
