### ISSUE TITLE
[BUG]: Link to with pathname has different behaviour than Link to with string

### ISSUE THREAD

**Issue by GiovanniIncammicia** [remix-run/react-router#8175]
## Version

**6.0.0-beta.8**

## Test Case

https://codesandbox.io/s/fervent-morning-eri0v?file=/src/App.js

## Steps to reproduce
1. Click the "Start" link, it goes to /outer/internal
2. There are two Links, one that uses to=".." and the other one that uses { pathname: ".." }
3. Notice that when you hover on the two links they point to different URLs (the correct one should be the one with to="..")

## Expected Behavior
Both the links should point to the same URL (which should be /outer being the path ".."

Also, I tried creating the codesandbox with just react-router-dom, but for some reason, it requires the "history" package. Is there a reason for that?

**Comment by loun4** [comment]
Is there any plan to fix this ?

**Comment by vsaarinen** [comment]
I'm also seeing similar behaviour when I'm trying to link to a sibling page using `to={{ pathname: '../siblingPage' }}` instead of `to="../siblingPage"`. I'd prefer to use the former because I'm also passing in a `search` property.

**Comment by loun4** [comment]
@GiovanniIncammicia can you add "bug" label please ?

**Comment by GiovanniIncammicia** [comment]
@loun4 Sure, but I'm not sure how to do that, I tried editing the name looking at the other "bug" issues, but I don't see the label. I guess that's not the way to add a label

**Comment by loun4** [comment]
> @loun4 Sure, but I'm not sure how to do that, I tried editing the name looking at the other "bug" issues, but I don't see the label. I guess that's not the way to add a la
![labels](https://user-images.githubusercontent.com/1511512/146745936-ce0b8dd1-35cc-415d-9eae-727a25003d28.png)
bel

**Comment by brophdawg11** [comment]
I'm not seeing this on 6.7.0 so I'm going to close this out: https://codesandbox.io/s/affectionate-ardinghelli-gqd7kn?file=/src/App.js
