### ISSUE TITLE
getting 27 vulnerabilities when running react-router-dom command for adding into the project

### ISSUE THREAD

**Issue by MatinT-SA** [remix-run/react-router#8176]
i am new to react and i'm trying to add react-router-dom into my react app but when i run this command:
`npm i -D react-router-dom`
in the terminal of the root directory from the application, i get these warning/errors saying that there are 27 vulnerabilities (8 moderate, 18 high, 1 critical) and they don't allow me to add this library into my project.
i have also tried the following command:
`npm i react-router-dom`
i got the same errors and those 27 vulnerabilities again.
here is the full message i get in my terminal when i run these commands:

> npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
> npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})    
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})     
> 
> + react-router-dom@5.3.0
> updated 1 package and audited 1922 packages in 9.701s
> 
> 153 packages are looking for funding
>   run `npm fund` for details
> 
> found 27 vulnerabilities (8 moderate, 18 high, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details

i have also tried `npm audit fix` and it didn't fix anything for me.
does anyone know how to fix this?

**Comment by timdorr** [comment]
This isn't coming from React Router. We don't depend on those packages, so something else is asking for them.
