### ISSUE TITLE
[V6] Diffrent behavior for route rendering after v6.0.0-beta.3

### ISSUE THREAD

**Issue by msalahz** [remix-run/react-router#8180]
## Version

React Router version v6.0.0-beta.8

## Test Case

https://codesandbox.io/s/react-router-v6-beta-8-94y3y

## Steps to reproduce

- Open the sandbox linked above
- You will see a home page with a link to login and an `isAuth` label with value false

## Expected Behavior (This works fine until v6.0.0-beta.3)

- If you checked the App.js you should notice that the 
   - The home route is utilizing the PrivateRoute component which is a wrapper component for the Route component but It only opened when isAuth is set to true and redirects to the login page if isAuth is set to false.
   - Login route is utilizing the PublicRoute component which is a wrapper component for the Route component but It only opened when isAuth is set to false and redirects to the home page if isAuth is set to true.

## Actual Behavior

- Navigation from home route to login route & vis versa is working regardless isAuth value while the exact same functionality was working fine as expected until v6.0.0-beta.3 as you can see on the following [sandbox](https://codesandbox.io/s/react-router-v6-beta-3-m68md)

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8111#issuecomment-934784147

and 

https://github.com/remix-run/react-router/issues/8092#issuecomment-933940126

**Comment by msalahz** [comment]
Thank you @timdorr. Here are my implementation for it
```
// src/componeonts/PrivateRouteRPC.tsx

import { Navigate, useLocation } from 'react-router-dom'
import { useAuth } from '../containers/AuthContainer'

interface Props {
  render: () => JSX.Element | null
  loginPath?: string
}

function PrivateRouteRPC(props: Props): JSX.Element | null {
  const location = useLocation()
  const { isAuthenticated } = useAuth()

  const { loginPath = '/login', render } = props
  // if user is not auth redirect to loginPAth
  if (!isAuthenticated()) return <Navigate to={loginPath} state={{ from: location }} />

  return render()
}

export default PrivateRouteRPC
```

```
// src/componeonts/PublicRouteRPC.tsx

import { Navigate } from 'react-router-dom'
import { useAuth } from '../containers/AuthContainer'

interface Props {
  render: () => JSX.Element | null
  defaultPath?: string
}

function PublicRouteRPC(props: Props): JSX.Element | null {
  const { defaultPath = '/', render } = props
  const { isAuthenticated } = useAuth()
  if (isAuthenticated()) return <Navigate to={defaultPath} />

  return render()
}

export default PublicRouteRPC
```
```
<Routes>
    <Route element={<PrivateRouteRPC render={() => <Auth />} />}>
        <Route index element={<PrivateRouteRPC render={() => <Prospects />} />} />
    </Route>
    <Route path="login" element={<PublicRouteRPC render={() => <Login />} />} />
    <Route path="*" element={<NotFound />} />
</Routes>
```
