### ISSUE TITLE
Permanent redirect with Navigate (V6)

### ISSUE THREAD

**Issue by theoavoyne** [remix-run/react-router#8181]
I noticed that the new `<Navigate>` element doesn't have the `from` prop that was pretty useful when used in the `<Redirect>` element (V5) for setting up a permanent redirect (e.g. `/` to `/dashboard`). It seems anyway that a `<Navigate>` element can't be used directly inside a `<Routes>` element—whereas a similar behaviour was possible in V5 using `<Switch>`/`<Redirect>`.

Is the code below the recommended way to go to mimic the old behaviour?
```
<Route element={<Navigate to="/dashboard" />} index /> // index can be replaced with path="/anything"
```

If yes, it'd be worth mentioning that in the v5-to-v6 migration doc. I can prepare a PR if needed.

**Comment by david-crespo** [comment]
That’s correct. I agree the docs would benefit from that example. Not just the migration one, also the API reference.

**Comment by mjackson** [comment]
I wrote about why we don't support `<Redirect>` in a `<Routes>` in v6 [in this gist](https://gist.github.com/mjackson/b5748add2795ce7448a366ae8f8ae3bb). tl;dr is that if you need to redirect on the initial render, you are better served doing the redirect on your server so you can send the proper status codes.

It is still possible to do a client-side redirect by putting a `<Navigate>` inside your `<Route element>`, but it won't happen until `useEffect()` kicks in immediately after the initial render. So you may see a flash of the old page before you end up at the new URL.

We should definitely link to my gist in the upgrade docs. I'll do that now. Thanks for the reminder.

**Comment by theoavoyne** [comment]
@mjackson Thanks for the clarifying this. You're completely right.
