### ISSUE TITLE
[V6] Module '"history"' has no exported member 'State'.

### ISSUE THREAD

**Issue by memark** [remix-run/react-router#8183]
## Version

6.0.0-beta.8

## Steps to reproduce

`yarn create vite react-router-test --template react-ts`
`cd react-router-test`
`yarn`
`yarn add react-router-dom@6.0.0-beta.8 history@5.0.3`
`echo "import { BrowserRouter } from 'react-router-dom'" > src/test.tsx`
`yarn build`

## Expected Behavior

The app builds successfully.

## Actual Behavior

Errors:
```
node_modules/react-router-dom/index.d.ts:3:15 - error TS2305: Module '"history"' has no exported member 'State'.

3 import type { State, To } from "history";
                ~~~~~

node_modules/react-router/index.d.ts:3:54 - error TS2305: Module '"history"' has no exported member 'State'.

3 import type { History, InitialEntry, Location, Path, State, To } from "history";
                                                       ~~~~~
```

Edit: Fixed typo.

**Comment by timdorr** [comment]
You have an extra `@` in your install link for the library. You probably have the wrong version.

**Comment by memark** [comment]
@timdorr Sorry, that was only a typo when writing it up. I have version 6.0.0-beta.8 installed and it gives this error. Please try the steps.

**Comment by timdorr** [comment]
Nevermind. There was a breaking change to the types released in history 5.0.2 and 5.0.3. I'm going to push a 5.0.4 to fix this.

**Comment by timdorr** [comment]
OK, 5.1.0 is about to be published: https://github.com/remix-run/history/releases/tag/v5.1.0

**Comment by memark** [comment]
Thanks, now it works!
