### ISSUE TITLE
PrivateRoute in Routes

### ISSUE THREAD

**Issue by goshua13** [remix-run/react-router#8186]
v6 beta8

"^6.0.0-beta.8",

https://codesandbox.io/s/lucid-wind-krczw?file=/src/gameComponent.jsx

this codesandbox should block the route is isAuth is set to false in App.js, but the PrivateRoute component wont render correctly in Beta8 if you switch it to Beta 0 then it works correctly.

Switch to Beta0 for correct behavior on blocking routes

Switch to Beta8 for BAD behavior on blocking routes

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8111#issuecomment-934784147

and 

https://github.com/remix-run/react-router/issues/8092#issuecomment-933940126
