### ISSUE TITLE
CDN urls are broken for react-router-dom 6.0.0 release

### ISSUE THREAD

**Issue by NathanBWaters** [remix-run/react-router#8193]
## Version

6.0.0

## Test Case

The main url for react-router-dom was https://unpkg.com/react-router-dom/umd/react-router-dom.min.js.  This link is now broken.

If you followed the previous pattern in 5.0.0 of:
https://unpkg.com/react-router-dom@5.0.0/umd/react-router-dom.min.js
But replace it with 6.0.0:
 https://unpkg.com/react-router-dom@6.0.0/umd/react-router-dom.min.js
it is also a broken url.

The issue seems to be that `production` is now at the end of the url:
https://unpkg.com/react-router-dom@6.0.0/umd/react-router-dom.production.min.js

## Steps to reproduce

Go to https://unpkg.com/react-router-dom@6.0.0/umd/react-router-dom.min.js or https://unpkg.com/react-router-dom/umd/react-router-dom.min.js

## Expected Behavior

I expected the url would work like it does for 5.0.0:
https://unpkg.com/react-router-dom@5.0.0/umd/react-router-dom.min.js

## Actual Behavior

Broken url.

**Comment by NathanBWaters** [comment]
This behavior is not specific to unpkg.  jsdelivr and cdnjs have the same issue.

**Comment by mjackson** [comment]
You should always include the version number in your unpkg URLs because the location of a file within a given package may change between releases of that same package. The unpkg URL structure just mirrors whatever is in the package tarball.

Did you see that CDN link on some v6 documentation page? Or were you just assuming the v6 package would be structured the same as v5?

**Comment by timdorr** [comment]
We currently have version-specific URLs with the install guide: https://github.com/remix-run/react-router/blob/main/docs/getting-started/installation.md

The prior README was unversioned, unfortunately: https://github.com/remix-run/react-router/tree/v5.3.0/packages/react-router#installation

That's definitely our bad, but I don't think we can rectify it. Even if the URL was restored, the code you're using it with would break anyways. You should just switch to a versioned URL that has the version of Router your code supports.

**Comment by Orion-Technologies** [comment]
Thanks for this information.
