### ISSUE TITLE
What happend with BrowserRouter.getuserconfirmation?

### ISSUE THREAD

**Issue by martinfcd2** [remix-run/react-router#8203]
Looks like it's been removed but I can't find replace

**Comment by timdorr** [comment]
Removed in beta.7: https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.7

It will make a return in some form eventually.

**Comment by martinfcd2** [comment]
> Removed in beta.7: https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.7
> 
> It will make a return in some form eventually.

is there any alternative methods we can use in V6? i need a customize prompt. now i can't find a way to do it

**Comment by timdorr** [comment]
Follow along in #8139

**Comment by Hendry5479** [comment]
> Removed in beta.7: https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.7
> 
> It will make a return in some form eventually.

Is there any similar methods we can use in v6 now？
