### ISSUE TITLE
[Docs] Layout of code snippets in guides pages is broken for a certain resolution

### ISSUE THREAD

**Issue by rohankokane** [remix-run/react-router#8208]
## Version

v5 Documentation : https://v5.reactrouter.com/web/guides/primary-components

## Steps to reproduce

1. Issue can be seen while reading documentation on a 720p resolution screen 
or 
1. can be reproduce using device toolbar in browser dev tools for custom dimension of 1271px x 650px

## Expected Behavior
Code snippets should be aligned to the right half of the page. As they are correctly aligned above horizontal resolution of 1287px.

![image](https://user-images.githubusercontent.com/58681372/140303742-daa416ce-716a-4b0b-a760-e5b2fa54b809.png)

## Actual Behavior
some code snippets are aligned below the paragraphs

![image](https://user-images.githubusercontent.com/58681372/140303710-96ef9c17-bc93-41b0-8aa7-c30e89f35293.png)

**Comment by timdorr** [comment]
I can't reproduce this locally.

![rr](https://user-images.githubusercontent.com/17882/140337578-6f6af482-61ee-4994-9d84-0a9471e1876c.gif)

My best guess is some other extension is messing with the layout. I ran mine from an incognito window to be sure.

Your fix doesn't seem to have much of an impact, though. I'll merge it in.

**Comment by rohankokane** [comment]
@timdorr thanks for merging. 
You can reproduce it by changing your device type to desktop. 

![bandicam 2021-11-05 00-20-31-239](https://user-images.githubusercontent.com/58681372/140404255-4fa856cf-2fb9-40b4-aa2f-194d15223693.gif)
