### ISSUE TITLE
react-router-dom Route error

### ISSUE THREAD

**Issue by nomanabid123** [remix-run/react-router#8210]
If we replace <Route path="/" children={<Home/>}>   with  

<span path="/" children={<Home/>}> 
it works as Route why?

**Comment by nomanabid123** [comment]
import React from 'react';
import './style.css';
import { BrowserRouter, Routes, Route, Link, Outlet } from 'react-router-dom';

function Home() {
  return <h1>Home</h1>;
}

function Dashboard() {
  return (
    <div>
      <h1>Dashboard</h1>
      <nav>
        <Link to="invoices">Invoices</Link> <Link to="team">Team</Link>
      </nav>
      <hr />
      <Outlet />
    </div>
  );
}
export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <span path="/" element={<Home />} />
        <Route path="dashboard" element={<Dashboard />} />
      </Routes>
    </BrowserRouter>
  );
}


![Screenshot (8)](https://user-images.githubusercontent.com/78290209/140316366-948d26d7-208c-4048-8a9c-8700837ea3ea.png)

**Comment by Grapedge** [comment]
It is not an error, in fact, there is no rendering in Route, it is only used to pass props.
```tsx
export function Route(
  _props: PathRouteProps | LayoutRouteProps | IndexRouteProps
): React.ReactElement | null {
  // do nothing...
}
```

and in Routes:

```tsx
export function Routes({
  children,
  location
}: RoutesProps): React.ReactElement | null {
  return useRoutes(createRoutesFromChildren(children), location);
}
```

`createRoutesFromChildren` will recursively traverse the child nodes and create routes based on the props of the child nodes, so no matter what node it is, as long as the props are in the shape of `RuleObject`
```tsx
export function createRoutesFromChildren(
  children: React.ReactNode
): RouteObject[] {
  let routes: RouteObject[] = [];

  React.Children.forEach(children, element => {
    // ......
    let route: RouteObject = {
      caseSensitive: element.props.caseSensitive,
      element: element.props.element,
      index: element.props.index,
      path: element.props.path
    };
    if (element.props.children) {
      route.children = createRoutesFromChildren(element.props.children);
    }
    routes.push(route);
  });

  return routes;
}

```

**Comment by nomanabid123** [comment]
**thank you**

**Comment by priyeshshah147** [comment]
I am having this error 
Error: A <Route> is only ever to be used as the child of <Routes> element, never rendered directly. Please wrap your <Route> in a <Routes>

![image](https://user-images.githubusercontent.com/15977970/140435720-c079897f-22d1-4599-8e8c-310ea4ae8df6.png)

index.js
![image](https://user-images.githubusercontent.com/15977970/140436549-0b413c61-be95-4271-82b1-4d7b7f465f05.png)

App.js
![image](https://user-images.githubusercontent.com/15977970/140436597-8a22267e-c1ac-4642-87d7-5fcba430d9b3.png)

**Comment by mjackson** [comment]
Just FYI we added an `invariant` that will yell at you about this in #8238

**Comment by nomanabid123** [comment]
okay thank you
