### ISSUE TITLE
useNavigate() does not support replacements of search-params

### ISSUE THREAD

**Issue by sm3sher** [remix-run/react-router#8212]
I am following the Migration Guide v5.1 to v6, which states that `useNavigate` should be used instead of `useHistory`.

With `useHistory` it was possible to pass in an `URLSearchParams` object to only replace the searchParams like so:
```js
// This is a React Router v5 app

const history = useHistory();

history.replace({
  search: modifiedUrlParams,
});
```

`useNavigate` does not have an option like that, as far as I've tried you can only do it like this:
```js
// This is a React Router v6 app

const navigate = useNavigate();
const location = useLocation();

navigate(`${location.pathname}?${modifiedUrlParams.toString()}`, {
    replace: true,
});
```

Is it intentional or am I missing something?

**Comment by timdorr** [comment]
You want to use useSearchParams. It has a setter function that does this for you: https://reactrouter.com/docs/en/v6/api#usesearchparams

**Comment by sm3sher** [comment]
Thanks, this makes it much easier.
