### ISSUE TITLE
[v6][Feature]Generic createRoutesFromChildren

### ISSUE THREAD

**Issue by Grapedge** [remix-run/react-router#8213]
Maybe there are some usages like this, we can customize our own Route, 

```tsx
type MyRouteProps = (PathRouteProps | LayoutRouteProps | IndexRouteProps) & {
  title?: string
  meta?: RouteMeta
  // ...
}

const MyRoute: React.FC = (props: MyRouteProps) => {
  throw new Error()
}
```

and then use `createRoutesFromChildren` to create an array of routes:
```tsx
// src/routes.ts
export default createRoutesFromChildren(
  <>
    <MyRoute path="posts">
      <MyRoute
        index
        title="PostIndex"
        element={<PostPage />}
        breadcrumb={<PostBreadCrumb />}
      />
    </MyRoute>
    <MyRoute path="*" element={<NotFoundPage />} title="Not Found" />
  </>
)
```

This use case requires the `createRoutesFromChildren` function to return props correctly. But now it only strictly returns `RouteObject`.

Maybe this feature can be added? This will make routing configuration more flexible.

```ts
function <T extends RouteObject = RouteObject>createRoutesFromChildren(children: React.ReactNode): <T[]>;
```

**Comment by timdorr** [comment]
Custom Route objects aren't supported anymore.

https://github.com/remix-run/react-router/issues/8111#issuecomment-934784147

and 

https://github.com/remix-run/react-router/issues/8092#issuecomment-933940126

**Comment by Grapedge** [comment]
> Custom Route objects aren't supported anymore.

No, I think you misunderstood what I mean, this is not a real custom Route.

As described above, it will not be used for rendering, but **only for building the routes array**. Also, these `Route`s are not used in `Routes`:

```tsx
function App() {
  // just used for create routes
  // that's just a configure style
  const routes = createRoutesFromChildren(
    <>
      <MyRoute path="posts">
        <MyRoute
          index
          title="PostIndex"
          element={<PostPage />}
          breadcrumb={<PostBreadCrumb />}
        />
      </MyRoute>
      <MyRoute path="*" element={<NotFoundPage />} title="Not Found" />
    </>
  )
  const element = useRoutes(routes)
  return (
    <>
      <header>Title</header>
      {element}
      <footer>Footer</footer>
    </>
  )
}
}
```
