### ISSUE TITLE
Generic API for controlled routers.

### ISSUE THREAD

**Issue by davbrito** [remix-run/react-router#8215]
I have a use case where the app uses modal windows to display data about an entity. There are different types of entities so there are different modal windows of these.
One of the requested requirements was that it be possible to stack these windows in order of opening, so as to keep behind the modal from which it was opened, and it was also required that when sharing the url to another person, said url should open the modals that were open (so a solution like managing open modals in redux was not worth it).

My solution to the problem of using the url to find out which modals are open was to use the query parameters of the url. In a similar way to this:
`modal.product=<product_id>&modal.customer=<customer_id>`

By not being able to use the url path, I have lost the benefit of being able to use react-router to manage navigation within the modal, which was necessary since each of these modalities has its own structure and complex internal navigation.

What currently I would like to be able to do is generate a controllable Router, to which I can deliver the current route and an event handler that manages the navigation and updates the current route independently.

A possible API could be the following:

```jsx
const ProductModalRouter = createControlledRouter();

const ProductModal = props => {
  const [path, setPath, removePath] = useQueryParameter('modal.product');

  const handleNavigation = (/* params */) => {
    /* Do something with setPath */
  };

  return (
    <Modal open={Boolean(path)} onHide={removePath}>
      <ProductModalRouter location={path} onNavigation={handleNavigation}>
        <ModalHeader>
          <ModalTitle>
             <Routes>
                {/* Set a title according to the route */}
             </Routes>
          </ ModalTitle>
        </ModalHeader>
        <ModalBody>
          <h5>Product</ h5>
          <Routes>
            {/* Show content according to the route */}
          </Routes>
        </ModalBody>
      </ ProductModalRouter>
    </ Modal>
  );
}
```

**Comment by timdorr** [comment]
You don't need a second Router (this isn't supported anyway), you just need the `location` prop on `<Routes>`. This will force a location for that subtree, overriding whatever is in the actual top-level Router.

**Comment by davbrito** [comment]
Thank you so much for pointing out the correct way for me to do it.
