### ISSUE TITLE
Error with downloading

### ISSUE THREAD

**Issue by oletsky** [remix-run/react-router#8219]
Hello. A strange error happened. Downloading the library by the usual address

<script  src="https://unpkg.com/react-router-dom/umd/react-router-dom.min.js"></script>

reported an error

Cannot download.

This never happened before, everything worked well. Could you help?

**Comment by timdorr** [comment]
There is a new version that has a different file layout. You should lock your URL to particular version:

```
<script src="https://unpkg.com/react-router-dom@5/umd/react-router-dom.min.js"></script>
```
