### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by ignaciomartinelias** [remix-run/react-router#8220]
Neither the development bundle nor the production one has IE11 support. The v6 beta version was transpiled with Babel I guess but for some reason, this stable version is not. Once I try to use the v6 stable version in IE11 you'll get an `Expected identifier` error because of object destructuring... Really hope this is a bug and not an arbitrary decision to ditch IE11 support.

**Comment by jacob-ebey** [comment]
I can't speak to the decision, but IMO it's time to let IE die. If you need to support IE you can always transpire your node_modules for IE and either ship those transpired bundles to everyone or ship a "fallback" bundle just for IE.

**Comment by ignaciomartinelias** [comment]
I'd love to ditch support for IE11, but unfortunately, we still need to give support in many cases. Still, it's a bit weird to me that the beta version was transpiled while this one is not.

**Comment by timdorr** [comment]
We're no longer building with IE support. You'll either need to stick to an older version or vendor this version and transpile with support for IE.
