### ISSUE TITLE
Can't import the named export 'Action'

### ISSUE THREAD

**Issue by paul-mesnilgrente** [remix-run/react-router#8221]
## Version

6.0.0

## Steps to reproduce

Install react-router and react-router-dom on rails react app using webpacker.

Create a component like this:

```jsx
import { BrowserRouter, Route } from 'react-router-dom';
import { StaticRouter } from "react-router-dom/server";

const MyComponent = () => {
  const Router = inBrowser() ? BrowserRouter : StaticRouter;

  return (
    <Router>
      <Routes>
        <Route path="/users" />
        <Route path="/search" />
      </Routes>
    </Router>
  )
}
```

## Expected Behavior

The component should work fine

## Actual Behavior

Getting this compilation error:

```
ERROR in ./node_modules/react-router-dom/server.mjs 18:15-21
Can't import the named export 'Action' from non EcmaScript module (only default export is available)
```

I guess it's because of the webpacker configuration?

**Comment by timdorr** [comment]
You probably have an older version of `history` installed. Install version 5.1.0 and you'll have the needed types.

**Comment by paul-mesnilgrente** [comment]
I checked my `yarn.lock` and I have

```
history@^5.1.0:
  version "5.1.0"
  resolved "https://registry.yarnpkg.com/history/-/history-5.1.0.tgz#2e93c09c064194d38d52ed62afd0afc9d9b01ece"
  integrity sha512-zPuQgPacm2vH2xdORvGGz1wQMuHSIB56yNAy5FnLuwOwgSYyPKptJtcMm6Ev+hRGeS+GzhbmRacHzvlESbFwDg==
  dependencies:
    "@babel/runtime" "^7.7.6"
```

Looks like you closed this issue way too quickly, without even waiting for a confirmation (feels a bit rude to be honest).
