### ISSUE TITLE
[[v6]] 'Switch' is not exported from 'react-router-dom'.

### ISSUE THREAD

**Issue by xld1393679430** [remix-run/react-router#8226]
I introduced the React V6 version and it looks like the react-router-dom export Switch is missing

![image](https://user-images.githubusercontent.com/22445609/140454354-c73bea93-cd62-4f1e-92fc-7dc605013c37.png)

![image](https://user-images.githubusercontent.com/22445609/140454519-d16d6efd-2bca-4247-a274-bb6ff5a8659c.png)

**Comment by Grapedge** [comment]
You should use `Routes` instead of `Switch`: [upgrade-all-switch-elements-to-routes](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-all-switch-elements-to-routes)

**Comment by mjackson** [comment]
Thanks for the answer, @Grapedge

**Comment by douglasfarias** [comment]
Thanks, solved my problem.
Can anyone update the tutorial in the website, please?
