### ISSUE TITLE
Upgrade guide to v6 should mention needed history update

### ISSUE THREAD

**Issue by bthorben** [remix-run/react-router#8232]
I have just upgraded from v5 to v6 and got stuck using version 4.x of history. It would be nice to mention to upgrade to history 5.x in the upgrade guide.

**Comment by devinjameson** [comment]
How did you fix the history issue? I'm seeing a `Could not resolve "history"` error, is that the error you had as well?

**Comment by mjackson** [comment]
History is now a direct dependency of the router, not a peer dep. You shouldn't be installing or directly using it with v6. Everywhere you used `history.push()` or `history.replace()` you can now use `navigate()`. I'll add some notes to the migration docs to make this more clear.
