### ISSUE TITLE
[Bug]: No default `location` set in `<StaticRouter>`

### ISSUE THREAD

**Issue by birdofpreyru** [remix-run/react-router#8243]
According to [docs](https://reactrouter.com/docs/en/v6/api#staticrouter):
> `<StaticRouter location>` defaults to `"/"`

In the actual implementation if `location` is undefined the code arrives to the line 26 and crashes on the attempt to read `pathname` of undefined object:

https://github.com/remix-run/react-router/blob/760f63d26ffd4994032df9ca120e09ab52d48a8a/packages/react-router-dom/server.tsx#L15-L31

**Comment by mjackson** [comment]
This was released in 6.0.1
