### ISSUE TITLE
[Bug]: v6 redirect - navigate doesn't work.

### ISSUE THREAD

**Issue by blaxk** [remix-run/react-router#8248]
### What version of React Router are you using?

v6.0.1

### Steps to Reproduce

**App.js**
```js
import React from 'react'
import { BrowserRouter, Route, Routes, useNavigate } from 'react-router-dom'

function App () {
   const navigate = useNavigate()

   return (
      <Routes>
         <Route path="/" element={<Index navigate={navigate} />} />
         <Route path="/next" element={<Next navigate={navigate}/>} />
      </Routes>
   )
}

export default () => (
   <BrowserRouter>
      <App />
   </BrowserRouter>
)
```

**Index.js**
```js
class Index extends Component {

   componentDidMount () {
      const { navigate } = this.props
      ...
      if (!params.myName) {
         // redirect navigate
         navigate('/next')
      }
   }

   render () {
      return <div>Index Page!</div>
   }
}

export default Index
```

> When executing `navigate('/next')` function in Index.js Component, it does not work.
> It works if you use the `setTimeout` function as shown below.
```js
setTimeout(() => {
   navigate('/next')
}, 1)
```

### Expected Behavior

When the navigate('/next') function is executed, it should navigate to the "/next" page.

### Actual Behavior

It doesn't work anything.

**Comment by timdorr** [comment]
Your `useNavigate` call is outside the `<Routes>`, so it's under the wrong internal context.

You should wrap your class components with a functional component to get access to the hooks: https://github.com/remix-run/react-router/issues/8146#issuecomment-947860640

**Comment by blaxk** [comment]
@timdorr 
Even if `useNavigate` is called inside the function as shown below, `navigate('/next')` does not work.

```js
function App () {
   return (
      <Routes>
         <Route path="/" element={<Index />} />
         <Route path="/next" element={<Next />} />
      </Routes>
   )
}

function Index () {
   const navigate = useNavigate()
   // redirect navigate
   navigate('/next')

   return <div>Index page</div>
}

function Next () {
   return <div>Next page</div>
}

export default () => (
   <BrowserRouter>
      <App />
   </BrowserRouter>
)
```

**Comment by timdorr** [comment]
You shouldn't be calling navigate inside of your render function. You need to wrap it with a useEffect or call it in an event handler.

**Comment by chetan5896** [comment]
@timdorr Why doesn't it work inside the render function though?

**Comment by g-wozniak** [comment]
@chetan-raina because render function should return JSX Element or null and because redirecting is usually a side-effect or "reaction". If you need to use it in render then should use `<Navigate to={uri} />` instead, also supplied by react router

**Comment by IbrahimO123** [comment]
![navigate](https://github.com/remix-run/react-router/assets/80628436/73b50483-8e9d-4289-8a06-d79e34a4ab2d)


Kindly help look at this code, in development mode , the replace option works fine but after hosting on vercel, it is not working, user can still go back to the home page after signing out....what did I do wrong or am I missing something.. I will really appreciate any form of assistance here. Thank you in advance
