### ISSUE TITLE
[Bug]: StaticRouter not found in Typescript

### ISSUE THREAD

**Issue by krishnaTORQUE** [remix-run/react-router#8250]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

`import { StaticRouter, matchPath } from 'react-router-dom';`

Just this line

### Expected Behavior

It should be found

### Actual Behavior

Not found

**Comment by timdorr** [comment]
You have the wrong import:
```js
import { StaticRouter } from "react-router-dom/server";
```

**Comment by zaydek** [comment]
> You have the wrong import:
> 
> ```js
> import { StaticRouter } from "react-router-dom/server";
> ```

This is undocumented in the docs. See https://reactrouter.com/docs/en/v6/guides/ssr. Thanks!
