### ISSUE TITLE
[Bug]: Validations in createRoutesFromChildren ("breaking change" introduced in v6.0.1)

### ISSUE THREAD

**Issue by artola** [remix-run/react-router#8251]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

Validations for <Routes> children do not allow to implement `MyRoute` while it was allowed in former versions and even during this beta up to v6.0.0-beta.8 and even on v6.0.0 !!!

release: https://github.com/remix-run/react-router/blob/d6650e2c1ea23256f87096d734b4ca41d2577658/packages/react-router/index.tsx#L707

beta: https://github.com/remix-run/react-router/blob/262b45dd8d6cbdc3a984259c5591ffc3de80d600/packages/react-router/index.tsx#L949

### Expected Behavior

Avoid this checking or allow some flag/prop to handle it.

### Actual Behavior

Invariant throws an error in development.

**Comment by timdorr** [comment]
This isn't a breaking change. The bug of accepting non-`<Route>` elements in children was fixed. We didn't intend for this to work and it may have stopped working silently at any time. This was also in the documentation on release: https://reactrouter.com/docs/en/v6/api#createroutesfromchildren

**Comment by artola** [comment]
@timdorr This "strict" mode makes that we must pin v6.0.0, fork the project or find some workaround.
We have a component `MyRoute` that implements the same API that `Route`. Do you have some idea/hack to allow it?
