### ISSUE TITLE
[Bug]: no routes matched location "/"

### ISSUE THREAD

**Issue by jsstackdevelopers** [remix-run/react-router#8253]
### What version of React Router are you using?

6.0.0

### Steps to Reproduce

What is the problem to the hell? My project has stoped!! How i can resolve this error?.. Routes are not matching ?😒

### Expected Behavior

NO

### Actual Behavior

NO

**Comment by jacob-ebey** [comment]
Very descriptive and insightful bug report 😅 Please re-file an issue with a reproduction or detailed description of your issue. Thanks.
