### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mauricearida** [remix-run/react-router#8262]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

just import {
  BrowserRouter as Router,
  Route,
  Switch,
  Redirect,
} from "react-router-dom";

### Expected Behavior

everything wroking fine

### Actual Behavior

Attempted import error: 'Switch' is not exported from 'react-router-dom'.

**Comment by sergeu90** [comment]
@mauricearida  You can replace Switch to Routes.

**Comment by ryanflorence** [comment]
install react-router-dom@v5
