### ISSUE TITLE
[Bug]: Homepage routing issue

### ISSUE THREAD

**Issue by akhilmhdh** [remix-run/react-router#8271]
### What version of React Router are you using?

NA

### Steps to Reproduce

1. Go to [Homepage](https://reactrouter.com/)
2. Click on **Read the Docs** button
3. The url changes to `https://reactrouter.com/docs/en/v6`, but the page doesn't change
4. Refresh the page and the ui changes

### Expected Behavior

1. Page should render properly when url changes

### Actual Behavior

1. Page didn't change at all

**Comment by akhilmhdh** [comment]
Video

https://user-images.githubusercontent.com/31166322/140687727-9e64b3ae-8b49-4579-8f46-eb536f87c53a.mov

**Comment by akhilmhdh** [comment]
Video:

https://user-images.githubusercontent.com/31166322/140688314-768d7b54-46a6-4ec5-bc86-320c87ef1485.mov

Browser: Mozilla latest

**Comment by timdorr** [comment]
I can't reproduce this in Firefox 94. Have you tried from a private window, where your extensions will be disabled? It may be one of them interfering.

**Comment by akhilmhdh** [comment]
@timdorr Tried in incognito. Still same issue. Not sure why this happening, need to try in a downgraded version i guess.

**Comment by iainsimmons** [comment]
I'm seeing a 404 page when clicking on either of the docs links.
