### ISSUE TITLE
[Bug]: Maximum update depth exceeeded inside Navigate component

### ISSUE THREAD

**Issue by jmadelaine** [remix-run/react-router#8272]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

Create an error boundary component like so:

```tsx
import { Component } from 'react'
import { Navigate } from 'react-router-dom'

export class ErrorBoundary extends Component {
  state = {
    hasError: false,
  }

  static getDerivedStateFromError = () => {
    return { hasError: true }
  }

  componentDidCatch = (error: unknown) => {
    // Error gets sent to server here
  }

  render = () => {
    const { hasError } = this.state
    const { children } = this.props
    return hasError ? <Navigate to="/something-went-wrong" /> : children
  }
}
```

Create an error component that will throw an error on render:

```tsx
// Error component
  const ErrorComponent = () => {
    throw new Error('oh dear')
  }
```

Render the error component wrapped in the error boundary:

```tsx
ReactDOM.render(
  <BrowserRouter>
    <Routes>
      <Route
        path="/"
        element={
          <ErrorBoundary>
            <ErrorComponent />
          </ErrorBoundary>
        }
      />
      <Route
        path="/something-went-wrong"
        element={
          <ErrorBoundary>
            <div>{'something went wrong'}</div>
          </ErrorBoundary>
        }
      />
    </Routes>
  </BrowserRouter>,
  document.getElementById('root')
)
```

### Expected Behavior

I load the app to the root `/`, and I get redirected to `something-went-wrong`, and see the text "something went wrong".

### Actual Behavior

Console errors "Maxiumum update depth exceeded" in the `Navigate`component.

Here's a [code sandbox](https://codesandbox.io/s/affectionate-meadow-kth7e?file=/src/App.tsx) showing the issue. Head to the root `/`, and check the console for errors.

**Comment by liuhanqu** [comment]
When it navigation to `something-went-wrong`, the `ErrorBoundary` component is reused, so in the render function, `hasError` is always true, and is would render `<Navigate />`. 
 The inner of `Navigate`, it use `navigate` function in `React.useEffect, the result of `navigate` would cause `Navigate` render, and then `React.useEffect` be called again.  Loop over and over again, so the error happen.

**Comment by timdorr** [comment]
Yup, this isn't an issue with the library.

**Comment by jmadelaine** [comment]
Thanks guys. Fixed this with the following in the `ErrorBoundary`:

```tsx
import { Component } from 'react'
import { Navigate } from 'react-router-dom'

export class ErrorBoundary extends Component {
  state = {
    hasError: false,
  }

  static getDerivedStateFromError = () => {
    return { hasError: true }
  }

  componentDidCatch = (error: unknown) => {
    // Error gets sent to server here

    // Set error state to false here
    this.setState({ hasError: false }) 
  }

  render = () => {
    const { hasError } = this.state
    const { children } = this.props
    return hasError ? <Navigate to="/something-went-wrong" /> : children
  }
}
```
