### ISSUE TITLE
[Feature]: add useStatic function

### ISSUE THREAD

**Issue by liuhanqu** [remix-run/react-router#8285]
### What is the new or updated feature that you are suggesting?

The `Router` component have `static` prop, and we can use it to judge it's in server side or client side. 
I wonder if we can add function like below
```js
function useStatic() {
  const { static } = React.useContext(NavigationContext);
  return static;
}
```
to judge the environment we are

### Why should this feature be included?

To judge the environment.

I don't know it's necessary or not, just a proposal.

**Comment by timdorr** [comment]
Thanks for the idea, but there are probably better ways to handle this. Your code should be written in a way to handle server-side rendering without a specific check for your environment. This is going to be more important later with React Server Components. For now, this is probably not a thing we should encourage.
