### ISSUE TITLE
[Feature]: Navigation Guards

### ISSUE THREAD

**Issue by heyFahad** [remix-run/react-router#8290]
### What is the new or updated feature that you are suggesting?

I have been working in **Vue.js** for 2 years and shifted to React quite recently. When I got started with **React Router**, there came a time when I had to implement route guards to prevent unauthorized access to any protected route. But to my shock, there was no built-in support for guarding our routes in React Router.

### Why should this feature be included?

In Vue, this [route guarding](https://router.vuejs.org/guide/advanced/navigation-guards.html#navigation-guards) is pretty much straightforward and easy because they have built-in support for protecting app routes through [Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#navigation-guards).

But when I started looking for something similar in **React Router**, I was in dismay not to find such a crucial security feature in any routing library. I suppose it would be a basic need for any React project out there to protect their application routes. There are some third-party libraries available for implementing route guarding (notably [react-router-guards](https://github.com/upstatement/react-router-guards)) but I'm not really confident enough using any of this third-party code knowing that **React** is always evolving itself and its APIs keep on changing to better improve their performance. Who knows when those third-party library owners decide to stop improving their package and my app starts to suffer.

Therefore, I think that the **React Router** team should provide either built-in support for guarding our app routes or they must provide some extended library (like a plugin) to enable these route guarding in our React app.

Do let me know what you guys think about this suggestion.

**Comment by heyFahad** [comment]
The benefit of this guarding feature is that we can actually restrict the access based on varying conditions rather than restricting based only on the user's authentication state. For example, we can check in [beforeEnter](https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard) route-hook whether the given user has particular permission to access a route or not, like an admin route maybe?

**Comment by outbackStack** [comment]
have a look here for an example.
https://reactrouter.com/docs/en/v6/examples/auth

You could add in more conditions and lock down each route base on other permissions and not just user's auth.

**Comment by timdorr** [comment]
Yeah, we're specifically not doing this kind of thing. It runs into the issue of knowing when exactly to fire the `beforeEnter`-style hook in relation to the React lifecycle, which is an even more complex problem under React Suspense.

It's recommended you handle it like this: https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f
