### ISSUE TITLE
[Bug]: Error: [AuthorizeRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

### ISSUE THREAD

**Issue by odmion** [remix-run/react-router#8294]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

1. Open Visual studio
2. Create Project ASP.NET Core with React.js
3. Select in **Authentication Type**: individual accounts
4. Update packages to the latest version ClientApp\package.json
5. run **npm install** in package manager console
6. Run Project

### Expected Behavior

successful launch

### Actual Behavior

Error: [AuthorizeRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

**Comment by mjackson** [comment]
You can't use non-`<Route>` children in `<Routes>`. Do your auth composition in the `<Route element>` prop instead of creating your own custom routes.

See https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f for more info on how to do this.

**Comment by anvk** [comment]
I know that it is closed yesterday but I have a quick note about this issue.

Not sure how DX was taken into consideration here, but custom Route Components and Route wrappers is a pretty handy pattern that allows you not to copy-paste complicated/nested logic into every `element` property. At first, I was super excited for the v5->v6 upgrade but it quickly became a pretty cumbersome and unpleasant experience. The project I'm working on has eight different useful Route Components doing their things: ACLs, Feature Flags, Redirects, unique functionality based on user roles, and much more. Moving all that logic into the `element` property makes code so less readable and every route massive React Tree.

Would love to hear your thoughts on this topic.

p.s.
@mjackson just want to say big thanks for everything you do for the JavaScript community! I truly enjoyed and used your early videos on `render props` before it became a common pattern.

**Comment by mjackson** [comment]
@anvk I think I already said everything I have to say in https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f.

You don't have to to a bunch of copy/paste if you don't want to. Your routes could be as simple as:

```tsx
<Routes>
  <Route path="/admin" element={<RequireAuth />}>
    <Route path="dashboard" element={<AdminDashboard />} />
  </Route>
</Routes>
```

So you can use some routes sort of as custom "middleware" if you like. Maybe that will help you save some copy/pasting. But the composition of your routes is completely in your hands.

**Comment by riccoski** [comment]
> @anvk I think I already said everything I have to say in https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f.
> 
> You don't have to to a bunch of copy/paste if you don't want to. Your routes could be as simple as:
> 
> ```tsx
> <Routes>
>   <Route path="/admin" element={<RequireAuth />}>
>     <Route path="dashboard" element={<AdminDashboard />} />
>   </Route>
> </Routes>
> ```
> 
> So you can use some routes sort of as custom "middleware" if you like. Maybe that will help you save some copy/pasting. But the composition of your routes is completely in your hands.

Yeah I've managed to refactor my v5 style which I believe is similar to what the OP is looking for. Basic example (also just like the quoted example)

```
<Routes>
      <Route path="/" element={<ProtectedRoute />}>
        <Route index element={<Dashboard />} />
        <Route index element={<Account />} />
      </Route>
      <Route path="/login" element={<Login />} />
      <Route path="/logout" element={<Logout />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
```

**Comment by anvk** [comment]
Oh I see! This is a nice solution actually. Much better than adding more complexity and hierarchy into the `element` property. Thanks for the answers! @riccoski @mjackson

**Comment by marr** [comment]
@riccoski Can you share what the `ProtectedRoute` looks like? I am trying to achieve a similar pattern to what you have, but since the child routes are not children of `ProtectedRoute`, I am having some difficulty.
Thanks!

**Comment by marr** [comment]
Nevermind! Got it working.  Basically I used something like:
```
return user ? (
        <React.Fragment>
            <Header pageTitle={pageTitle} />
            <Outlet />
        </React.Fragment>
    ) : (
        <Navigate
            replace
            to={{
                pathname: '/signin',
                state: { from: location }
            }}
        />
    )
```
for my _ProtectedRoute.js_ file.. in case anyone is wondering what that looks like.

**Comment by world56** [comment]
I was also very confused，I was also very confused

![image](https://user-images.githubusercontent.com/37354312/148078255-2b83f895-c23e-466f-aeac-8018169e5306.png)

**Comment by riccoski** [comment]
> Nevermind! Got it working. Basically I used something like:
> 
> ```
> return user ? (
>         <React.Fragment>
>             <Header pageTitle={pageTitle} />
>             <Outlet />
>         </React.Fragment>
>     ) : (
>         <Navigate
>             replace
>             to={{
>                 pathname: '/signin',
>                 state: { from: location }
>             }}
>         />
>     )
> ```
> 
> for my _ProtectedRoute.js_ file.. in case anyone is wondering what that looks like.

@marr Sorry I missed the noti but yes like so:

```js
export const ProtectedRoute: FC = () => {
  const { isLoggedIn } = useCurrentUser();

  if (isLoggedIn) return <Outlet />;
  return (
    <Navigate
      to="/login"
      state={{
        redirectTo: window.location.pathname
      }}
    />
  );
};
```
