### ISSUE TITLE
[Bug]: meta.relativePath.startsWith is not a function

### ISSUE THREAD

**Issue by kevinRoomies** [remix-run/react-router#8299]
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

- Update to v6 from v5
- Update your Switch to a Routes
- Update all the Route to replace the render prop with the element prop and turn every component to JSX element
- Start the app

### Expected Behavior

My routing would work as it did in v5

### Actual Behavior

App is crashing
![image](https://user-images.githubusercontent.com/65670017/140955421-e920b5fb-2720-45d2-afb2-345dfcb0cdb8.png)

**Comment by kevinRoomies** [comment]
It appears that it was caused by me still using relative paths. I removed all the / and nested my routes and it seems to work correctly now.

**Comment by matttturnbull** [comment]
If it ever helps I was still trying to use arrays for multiple paths in my routes.

`path={['/search/:id', '/search']}`
