### ISSUE TITLE
[Bug]: Redirect throws an error if parentheses exist in search string

### ISSUE THREAD

**Issue by ClaysonIO** [remix-run/react-router#8300]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

Place the following code in any switch block: 

`<Redirect path={"/"} to={'/?foo=(bar)'}/>`

This looks like it's an issue with React Router's use of the path-to-regexp package.

### Expected Behavior

The application should be redirected to `/?foo=(bar)`

### Actual Behavior

The application throws the following error: 

TypeError: Expected "0" to be defined
(anonymous function)
<pathToApplication>/node_modules/react-router/node_modules/path-to-regexp/index.js:179

**Comment by timdorr** [comment]
The `to` prop is parsed by path-to-regexp, so it functions the same way as `path` on a `<Route>`. We do this so you can pass along parameters. 

You can work around this by URL encoding your `to`:
```js
<Redirect path={"/"} to={encodeURIComponent('/?foo=(bar)')}/>
```

**Comment by CHOYSEN** [comment]
hi @timdorr , i got the same error when i pass `(xxx)`. Did i doing anything wrong?

```js
<BrowserRouter>
  <Switch>
    <Route path="/:id" children={<div>success</div>} />
    <Redirect to="/foo(bar)"></Redirect>
  </Switch>
</BrowserRouter>
```
