### ISSUE TITLE
[Bug]: `useNavigationType()` returns `POP` on the initial page load

### ISSUE THREAD

**Issue by birdofpreyru** [remix-run/react-router#8303]
### What version of React Router are you using?

v6.0.1

### Steps to Reproduce

On the initial page load the `useNavigationType()` hook returns `POP`. I believe, it should return `PUSH` (or `REPLACE`?).

### Expected Behavior

See above.

### Actual Behavior

See above.

**Comment by timdorr** [comment]
This has always been the case: https://github.com/remix-run/history/issues/96#issuecomment-147446262
