### ISSUE TITLE
[Bug]: setSearchParams() from useSearchParams() can add trailing slash to pathname in some circumstances

### ISSUE THREAD

**Issue by Monstrel** [remix-run/react-router#8312]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

With a BrowserRouter configured with a basename of `/foo/bar` and the browser pointed at `site.com/foo/bar`, use the `setSearchParams` function returned by the `useSearchParams()` hook to set search parameters such as:

`setSearchParams({ name: 'Bob' })`

### Expected Behavior

The browser URL should update to `site.com/foo/bar?name=Bob`

### Actual Behavior

The browser URL updates to `site.com/foo/bar/?name=Bob`

Note the trailing slash at the end of the path.

**Comment by senseibarni** [comment]
Created CodeSandbox for this: https://codesandbox.io/s/react-router-issue-8312-63qqc7
I think I will try to contribute to this one.

**Comment by brophdawg11** [comment]
This should be fixed by #8861 - this should be included in the next `6.4.0` prerelease (hopefully this week)
