### ISSUE TITLE
[Feature]: Make clear what is a dev dependency is what is not in package.json file

### ISSUE THREAD

**Issue by andremarcondesteixeira** [remix-run/react-router#8315]
### What is the new or updated feature that you are suggesting?

I am trying to create a project with Deno and React. Thing is Deno does not use package.json, BUT package.json is a good place to look for when I want to check what files the final bundle actually depends on. Having this information would allow me to quicker address how to approach making a bundle compatible with Deno

### Why should this feature be included?

Because of Deno

**Comment by timdorr** [comment]
We don't have any devDependencies in our packages. We have the single dep of history, a cross-package dep of react-router for the -dom and -native packages, and peer deps on React itself.
