### ISSUE TITLE
[Bug]: issue with getting images located in public folder

### ISSUE THREAD

**Issue by Code0Breaker** [remix-run/react-router#8318]
### What version of React Router are you using?

"react-router-dom": "^6.0.0-beta.8"

### Steps to Reproduce

add images to public folder
create routing on first level without child routes
create routing with child routes
render the image on route without children for example 'images/logo.png'
when trying to render the image on child route, should to do like that '../images/logo.png'

### Expected Behavior

thought that can render the images same way as 'images/logo.png'

### Actual Behavior

the rendering images whit importing them works okay, but will be better to fix this issue, because, imagine that there is many photos and I don't want to do imports for each of them

**Comment by timdorr** [comment]
This has nothing to do with React Router.
