### ISSUE TITLE
[Feature][v6][doc]: Document How `basename` Is Used with `useRoutes` Hook

### ISSUE THREAD

**Issue by burakozdemir32** [remix-run/react-router#8321]
### What is the new or updated feature that you are suggesting?

We have migrated our application to v6 and started using `useRoutes` hook. Our application previously had `basename` defined, though I could not find direction in documentation on how to use `basename` with `useRoutes` hook. I tried to provide it as a second argument to the hook, though it seems to be not working.

### Why should this feature be included?

To give people clear overview for `useRoutes` hook.

**Comment by haiderali22** [comment]
strangely it was working on 6.0.0-beta.0

**Comment by wangel13** [comment]
When i use it like:

```
useRoutes(routes, 'pathname')
```

Error occurs: 

```
No routes matched location "pathnameundefinedundefined"  
```

version:  "react-router-dom": "^6.2.1",

**Comment by GraxMonzo** [comment]
You must wrap your component that uses the `useRoutes` hook with the `BrowserRouter` or `HashRouter` components. Then you can pass `basename` to those components (`BrowserRouter`, `HashRouter`).

`Routes.tsx`:

```tsx
const Routes = () => {
  return useRoutes([
    {
      path: '/',
      element: <Dashboard />
    }
    {
      path: 'users',
      children: [
        {
          index: true,
          element: <UsersList />
        },
        {
          path: 'create',
          element: <UsersCreate />
        }
      ]
    },
    {
      path: '*',
      element: <NotFound />
    }
  ]);
};

export default Routes;
```

`App.tsx`:

```tsx
import { BrowserRouter as Router } from 'react-router-dom';
// or HashRouter as Router
import Routes from './Routes';

const App = () => {
  return (
    <SomeProviders>
      <Router basename='admin'>
        <Routes />
      </Router>
    </SomeProviders>
  );
};

export default App;
```

Resulting routes:
| Route | Component |
| - | - |
| /admin | Dashboard |
| /admin/users | UsersList |
| /admin/users/create | UsersCreate |
| any | NotFound |

**Comment by fl0wx** [comment]
@GraxMonzo , thanks, that worked for me :)
