### ISSUE TITLE
[Feature]: v6: Routes children allow Higher-Order Route Component

### ISSUE THREAD

**Issue by nekko1119** [remix-run/react-router#8322]
### What is the new or updated feature that you are suggesting?

The following code is invalid since v6.
I want the code to be valid:

```tsx
const SentryRoute = Sentry.withSentryRouting(Route);
...
<Routes>
  <SentryRoute path="/top" element={<Top /> />
</Routes>
```

`withSentryRouting` is higher-order component.
ref: https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#react-router-v4v5

I would appreciate if `Routes` allow higher-order `Route` component.

### Why should this feature be included?

When I was migrating from v5 to v6, I faced a problem that `Routes` children don't allow higher-order Route component.
I use some higher-order `Route` components in my application.
So, if higher-order Route component is supported, I'm so happy.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8294#issuecomment-964187831

**Comment by nekko1119** [comment]
Thank you for your quick response.
I'll try to avoid using HOC.
