### ISSUE TITLE
[Bug]: Updating search params removes hash?

### ISSUE THREAD

**Issue by mrlubos** [remix-run/react-router#8323]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. Create a route with the ability to change search params. A good example is a route displaying a table with URL-persisted configuration (page number, page size, etc)
2. Perform the action triggering search params update. In our example, it would be changing the page number.

### Expected Behavior

The URL search params change while the path and hash remain unchanged.

### Actual Behavior

The URL search params change while the path remains unchanged, but the hash disappears.

**Comment by mrlubos** [comment]
Note: It is likely I am missing something from the new API and this can be configured, but I am yet to figure it out. Also, what's the best approach to updating a single search parameter?

**Comment by gpoulet** [comment]
+1

**Comment by pineshmenat** [comment]
Hey @mrlubos could you please share code sandbox of updating search params in react router v6, I am struggling to make it work. Thank you

**Comment by mrlubos** [comment]
> Hey @mrlubos could you please share code sandbox of updating search params in react router v6, I am struggling to make it work. Thank you

Hey Pinesh! Can you show me your CodeSandbox with the code you're trying? I should be able to help from there

**Comment by pineshmenat** [comment]
Hey @mrlubos  thank you for offering help but I am good now, found one nice [example](https://reactrouter.com/docs/en/v6/getting-started/tutorial#search-params) in docs
