### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by jcovington16** [remix-run/react-router#8326]
### What is the new or updated feature that you are suggesting?

In v5 if I wanted to do conditional rendering then I'm able to have an if statement within the `<Route>`. To paint a picture I'm creating a register / login page. With my routes I have set up whereas if there's a legitimate user logging in then send that user to the home page, else return back to the login page.
```js
<Route path="/home" render={props => {
       if(user) {
                return <MainPage user={user} />
       } else {
                return <Route element={<Login />} />
```
### Why should this feature be included?

I believe this allows the user to conditionally render a page based off of the state variable if it was set with valid data.

**Comment by timdorr** [comment]
You can do this with an `<Outlet>`, choosing whether or not to render it or some fallback component.
