### ISSUE TITLE
[v6]: Please sort out the google links for the documentation

### ISSUE THREAD

**Issue by MartinDawson** [remix-run/react-router#8329]
### What is the new or updated feature that you are suggesting?

https://reacttraining.com/blog/react-router-v6-pre/#nested-routes-and-layouts

The above is the top google link and the example simply does not work.

https://v5.reactrouter.com/web/guides/quick-start

This is the top link in google and it took me a long time to realise that this is v5, not v6. The top links should default to v6, not v5 as it's old.

### Why should this feature be included?

Stop people wasting time with wrong versions.

**Comment by MartinDawson** [comment]
This is the correct example for layout: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/basic?file=src/App.tsx

But because google has old links at the top I ended up wasting a bunch of time.

**Comment by timdorr** [comment]
Unfortunately, we can't control what Google chooses to link to. If we could, we would be a lot richer as SEO consultants and probably not be making this library...

**Comment by MartinDawson** [comment]
@timdorr Doesn't remix-run own both of the above domains? I was under the impression you did. Maybe if react-router was the main domain instead of v5 you would be able to immediately switch to the correct docs on new major version changes instead of google indexing old docs.
