### ISSUE TITLE
v5 to v6 upgrade guide should mention that usePrompt and <Prompt> have been removed

### ISSUE THREAD

**Issue by evoyy** [remix-run/react-router#8330]
### What is the new or updated feature that you are suggesting?

There is no mention in the v5 to v6 upgrade guide that ````<Prompt>```` has been removed.

### Why should this feature be included?

 I discovered the following in the release notes for v6.0.0-beta.7:

> We removed ````useBlocker()````, ````usePrompt()````, and ````<Prompt>```` for now. We will revisit these post 6.0 when we have more time to get it right.

It might be a good idea to mention this at the beginning of the guide because people who are using ````<Prompt>```` are unable to upgrade to v6 at the moment.

**Comment by pluma** [comment]
It would be nice if this was mentioned in the API docs too. I realize the URL indicates they're the v5 docs but the link to them suggests they're also the v6 docs and staring at it trying to figure out why the import no longer works isn't a fun way to find out about this change.

**Comment by minnyww** [comment]
anyone know how can block navigation in v6 ?

**Comment by rmorse** [comment]
I'm in need of this too - I tried looking though the code but I can't find anything that would allow me to do something before navigation (like blocking)...

**Comment by pluma** [comment]
FWIW I've decided to use this opportunity to migrate from RRv5 to Next since the move to RRv6 would already involve a number of breaking changes.

**Comment by ylin0811** [comment]
Is there an eta on bringing up the usePrompt with 6.2.x?  Thanks.
