### ISSUE TITLE
Electron app not working with React-Router using browserHistory [Bug]: 

### ISSUE THREAD

**Issue by lqd1434** [remix-run/react-router#8331]
### What version of React Router are you using?

v6

### Steps to Reproduce

I use vite to build my react app with react router v6,it will appear,the window is blank

### Expected Behavior

it will work just like i use it in broswer

### Actual Behavior

it is blank and the console is no errors

**Comment by lqd1434** [comment]
if i use the <code>HashRouter</code>  it work correctly

**Comment by timdorr** [comment]
Electron doesn't work with the BrowserRouter (because there isn't a true browser). Using a HashRouter or MemoryRouter will work.

**Comment by mjackson** [comment]
For future reference: you can make Electron work with a `<BrowserRouter>` but you have to configure it to use the same HTML file no matter what the URL is. I can't remember off the top of my head how to do this exactly but I've done it before.

**Comment by lqd1434** [comment]
@mjackson what do you mean that i just use the loadUrl method to load my app ? and i deploy my react app on the remote server?
