### ISSUE TITLE
[Feature]: useNavigate in Class Component

### ISSUE THREAD

**Issue by aromal-sasidharan** [remix-run/react-router#8333]
### What version of React Router are you using?

React Router 6 

### Steps to Reproduce

I have used useNavigate in functional Component. Is it possible to use navigate in class component or any alternative is available?

Please let know

### Expected Behavior

I have used useNavigate in functional Component. Is it possible to use navigate in class component or any alternative is available?

Please let know

### Actual Behavior

I have used useNavigate in functional Component. Is it possible to use navigate in class component or any alternative is available?

Please let know

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8146#issuecomment-947860640

**Comment by Junfeizhao** [comment]
@aromal-sasidharan Do you have a solution

**Comment by Gayathridevi8** [comment]
use Navigate component instead of useNavigate in class
