### ISSUE TITLE
[Bug]: Link with reloadDocument reloads "in page" navigation with #hash parameter

### ISSUE THREAD

**Issue by Sannnao** [remix-run/react-router#8338]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-cdufdg-f94qwt?file=src%2FApp.tsx
2. Add a search param to the end of the path: `?search=param`
3. Confirm leave
4. Try to in page navigate with `Link reloadDocument`, see that it is trying to reload the page
5. Try to in page navigate with `a` tag, see that it is not trying to reload the page

### Expected Behavior

`Link reloadDocument` shouldn't try to reload when it is used to in page navigation

### Actual Behavior

`Link reloadDocument` is trying to reload the page in page navigation with search parameters

**Comment by gbatterbee** [comment]
I have a similar problem with
    "@remix-run/node": "^1.9.0",
    "@remix-run/react": "^1.9.0",

**Steps**
Place this snippet in a Remix route.
```
      <form method="get">
        <div><a href="#input">Focus</a></div>
        <div><input type="text" name='input' id='input'></input></div>
      </form>
```
Click on focus, focuses the input.
Click on focus again.

**Expect** 
It to re-focus the input.

**Actual**
With javascript enabled - Reloads the page 
With javascript disabled -Re-focuses the input.


Works fine in a a plain old react app
Also with react-router-dom.
But, plays up with Remix. (works correctly with JS turned off)

Code for react-router-dom
```
//  "dependencies": {
//    "react": "^18.2.0",
//  "react-dom": "^18.2.0",
//   "react-router-dom": "^6.7.0",
//  },
```

import * as React from "react";
import { Routes, Route, Outlet, Link, BrowserRouter } from "react-router-dom";

export default function App() {
  return (
    <BrowserRouter>
      <div>
        <h1>Basic Example</h1>
        <Routes>
          <Route path="/" element={<Layout />}>
            <Route path="about" element={<About />} />
            <Route path="*" element={<NoMatch />} />
          </Route>
        </Routes>
      </div>
    </BrowserRouter>
  );
}

function Layout() {
  return (
    <div>
      <nav>
        <Link to="/about">About</Link>
      </nav>
      <Outlet />
    </div>
  );
}

function About() {
  return (
    <div>
      <h2>About</h2>
      <form method="get">
        <div><a href="#input">Focus</a></div>
        <div><input type="text" id='input'></input></div>
      </form>
    </div>
  );
}

function NoMatch() {
  return (
    <div>
      Nothing to see here!
    </div>
  );
}
```

**Comment by brophdawg11** [comment]
Search params are not automatically preserved in `<Link to>`, so when you are on `/page?search=param` and you render a `<Link to="#hash">`, since there are no search params specified it will generate a link to `/page#hash` on click so it's changing the search params and that is causing a page reload with `reloadDocument=true`.

If you want to preserve the search params you can add the current `location.search` into the Link:

```jsx
let location = useLocation();
...
<Link reloadDocument to={`${location.search}#${link.pathname}`}>
```

**Comment by brophdawg11** [comment]
@gbatterbee I'm not able to reproduce your issue -- if you're still seeing it, would you be able to open a new issue with a reproduction?  Thanks!
