### ISSUE TITLE
[Feature]: Omit parent paths in absolute paths

### ISSUE THREAD

**Issue by noiseymur** [remix-run/react-router#8346]
### What is the new or updated feature that you are suggesting?

When rendering a page with Route and then rendering some other components with other Route components which have sub paths, I would like to omit the parent path (make the path relative).

For example:

```
// App.js

<Switch>
    <Route path="/profile">
        <Profile />
    </Route>
</Switch>

```

```
// Profile.js

<Switch>
    <Route path="/profile/posts">   // Omit "/profile" part of the path, since it is repetitive and if Profile page is already rendered it means "/profile" part already exists
        <Posts />
    </Route>
    <Route path="/profile/comments"> // Omit "/profile" part of the path ....
        <Comments />
    </Route>
</Switch>
```

### Why should this feature be included?

Because it gets repetitive and annoying to write the parent paths over and over again

**Comment by timdorr** [comment]
Correct, relative/nested routing is a feature of React Router v6. It won't be a feature of v5.
