### ISSUE TITLE
[Bug]: Generic of hook useParams require string type

### ISSUE THREAD

**Issue by TbIKoBKa** [remix-run/react-router#8347]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. Add route with dynamic params
2. Create page component as prop element to route from step 1
3. Import useParams from react-router to module with page
4. Call useParams with generic type object to get a few params

### Expected Behavior

Destruct return object from useParams

### Actual Behavior

Got an error
![image](https://user-images.githubusercontent.com/53538417/142185778-d0ac9e2d-922a-43d8-9b43-11348d9b3164.png)
because of generic type
![image](https://user-images.githubusercontent.com/53538417/142185978-8f71fac5-e7e9-4d5a-a2ee-27627e9830de.png)

**Comment by kresli** [comment]
you need to use it as
```javascript
const {id} = useParams<"id">()
```
in a case of multiple params
```javascript
const {name, age} = useParams<"id" |"age">();
```
