### ISSUE TITLE
[Bug]: NavLink with QueryParameter marks index as active

### ISSUE THREAD

**Issue by micneuge** [remix-run/react-router#8348]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. Create routing with index page, and any other page. 
2. Add NavLinks with query parameters in it. 
3. Go to page with query parameters other from index.

[Example](https://stackblitz.com/edit/github-oc32gg?file=src/App.tsx)

### Expected Behavior

Only active nav link is marked as active.

### Actual Behavior

Active link is marked as active, and index page is marked as active as well. It makes it impossible to go to index page then.

**Comment by timdorr** [comment]
You need to add a leading slash, otherwise it becomes a relative path: `to="/?queryParam=true"`
