### ISSUE TITLE
[Bug or Help]: Link not work at React Native

### ISSUE THREAD

**Issue by chenkaiC4** [remix-run/react-router#8351]
### What version of React Router are you using?

v6.0.2 （react-native）

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/7543145/142340465-e2b79bb6-c6bb-4360-b09a-500ee403e63e.png)

### Expected Behavior

suceess run

### Actual Behavior

```
Error: React.Children.only expected to receive a single React element child.

This error is located at:
    in TouchableHighlight
    in Unknown (at react-router-native/index.tsx:151)
    in Link (created by Home)
    in RCTView (created by View)
    in View (created by Home)
    in Home (created by App)
    in Outlet (created by Layout)
    in Layout (created by App)
    in Routes (created by App)
    in Router (created by MemoryRouter)
    in MemoryRouter (at react-router-native/index.tsx:122)
    in NativeRouter (created by App)
    in RCTSafeAreaView
    in SafeAreaView (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

**Comment by chenkaiC4** [comment]
remove all the useless code, just render a route.
if i delete the `Link` at `Home.tsx`, everything is ok. seems like the `Link` is not ok ?
 
![image](https://user-images.githubusercontent.com/7543145/142341349-c4e04256-375c-4433-b7cf-df7cc18dd164.png)

**Comment by timdorr** [comment]
You have only text as the child of your Link. You need to have a single child element (not text) for the Link, as it's using TouchableHighlight under the hood:
```js
<Link to="/login">
  <View style={styles.button}>
    <Text>Login</Text>
  </View>
</Link>
```

**Comment by Mahedimm** [comment]
same problem i don't  find solutions

**Comment by zoorura** [comment]
Same problem here. Even if I wrap, link doesn't work. Did anyone find a solution?
