### ISSUE TITLE
[Bug]: Error: useNavigate() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by yunfeng-Harris** [remix-run/react-router#8355]
### What version of React Router are you using?

^6.0.2

### Steps to Reproduce

"mobx-react": "^7.2.1";
When I use mobx-react to wrap the function component, and then I can't use usenavigate for route hops

```ts
const App: React.FC = observer(() => {
  const navigate = useNavigate();
  console.log(navigate);
  return (
    <Provider {...rootStore}>
      <StoresContext.Provider value={rootStore}>
        <BrowserRouter>
          <div className={style.App}>
            <Routes>
              <Route path="/" element={<Layout />}>
                <Route path="home/*" element={<HomePage/>}/>
              </Route>
              <Route path="login" element={<LoginPage />} />
              <Route path="*" element={<NotFoundPage />} />
            </Routes>
          </div>
        </BrowserRouter>
      </StoresContext.Provider>
    </Provider>
  );
})
```
It is normal for me to use useNavigate in components that do not use Mobx
```tsx
const LoginPage: React.FC = () => {
  const navigate = useNavigate();
  console.log(navigate);
  return (
    <div>login
      <Outlet />
    </div>
  )
}
export default LoginPage;
```

### Expected Behavior

I can use the useNavigatemethod normally after using mobx

### Actual Behavior

The console then reports an error

```ts
index.tsx:19 Uncaught Error: useNavigate() may be used only in the context of a <Router> component.
    at invariant (index.tsx:19)
    at useNavigate (index.tsx:457)
```

**Comment by timdorr** [comment]
This doesn't have anything to do with mobx-react. You're using `useNavigate` outside of your `<BrowserRouter>` context. You need to put that component somewhere outside and above the App component for you to make use of it there.

**Comment by yunfeng-Harris** [comment]
OK，thankful。So I can't use some  funtions of react-route  when the router aren't be created.
