### ISSUE TITLE
[Feature]: revisit "match object is always newly created #5099"

### ISSUE THREAD

**Issue by JasonKleban** [remix-run/react-router#8365]
### What is the new or updated feature that you are suggesting?

Please revisit/reopen #5099 "match object is always newly created"

### Why should this feature be included?

#5099 is locked but not truly resolved.  There were some compelling suggestions in the discussion that were never responded to.

**Comment by timdorr** [comment]
My old comment still stands. Simple equality checking of the match object is misleading. If we retain the object across renders, but the contents of it change, this could result in missed updates. You should not rely on match, but one of its properties which are scalar values that don't have referential equality.
