### ISSUE TITLE
[v6][Bug]: Route doesn't match anymore pattern like '/:basePathname*/my-route/:id'

### ISSUE THREAD

**Issue by Guymestef** [remix-run/react-router#8382]
### What version of React Router are you using?

6

### Steps to Reproduce

Create a route matching the pattern '/:basePathname*/my-route/:id'
Navigate to urls:
- /my-route/3
- /category/my-route/3
- /category/sub-category/my-route/3

### Expected Behavior

Urls should match the pattern as with v5, or provide a way to match all urls ending with '/my-route/:id'

### Actual Behavior

None match the pattern

**Comment by timdorr** [comment]
Duplicate of #8359 and #8288

**Comment by Guymestef** [comment]
Hello,

I'm not sure it's a duplicate since the - in my route on my example was just to illustrate the issue.
On my real route, I don't have dashes.
The issue here is that :basePathname* doesn't match anymore the beginning of the route (ie: /category/sub-category)
I think now the * on :basePathname* is not a supported format

On our app, we were using this feature to create a route matching all urls ending with /publications/:id
