### ISSUE TITLE
[v6][Bug]: Routes don't accept Route elements returned by other component

### ISSUE THREAD

**Issue by vocko** [remix-run/react-router#8386]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

Routes tag doesn't allow to render a component that only returns `Route` components within a `React.Fragment`.

Example:
```react
<Routes>
    <MyRoutes />
</Routes>
```

```react
const MyRoutes: React.FC = () => {

    return <>
        <Route path="path1" element={<Component1 />} />
        <Route path="path2" element={<Component2 />} />
    </>;
};

export default MyRoutes;
```

### Expected Behavior

It should allow to render the component as long as the returned element(s) are `<Route>` (or `<Fragment>`).

### Actual Behavior

It gives an error:
`Uncaught Error: [ComponentName] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>`.

**Comment by MeiKatz** [comment]
`<Routes />` only accepts `<Route />` and `<Fragment />` as child components. Your example creates a virtual dom like the following:

```jsx
<Routes>
  <MyRoutes>
    <Fragment>
      <Route path="path1" element={<Component1 />} />
      <Route path="path2" element={<Component2 />} />
    </Fragment>
  </MyRoutes>
</Routes>
```
Therefore neither `<Route />` nor `<Fragment />` is a direct child of `<Routes />`.

**Comment by vocko** [comment]
I have ended up creating an array and then calling `.map` within the `Routes`. It was just the thing that it worked in v5 and suddenly stopped and would be actually nice if you can wrap it in a component. But this is not a big deal, there are things they hurt me more, like the missing optional parameters.

Also `useLocation`'s pathname returns the path including all the parameter values (was not the case in v5), but I think I will create a separated ticket for it.

**Comment by timdorr** [comment]
https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f
