### ISSUE TITLE
[v6][Bug]: Routing with factories and array of paths seems to not work anymore

### ISSUE THREAD

**Issue by balboFK** [remix-run/react-router#8387]
### What version of React Router are you using?

"react-router-dom": "^6.0.2"

### Steps to Reproduce

When upgrading from 5.2.1 to 6.0.2, i find that array paths are no longer working, and also when you try to use factorys to return your components, it throws a lot of errors 'All component children of 'Routes' must be a 'Route' or 'React.Fragment'

My router on v5.2.1 was simply making the exact component for 3 routes: login, forgot-password and change-password, and on the login factory "makeLogin" , i use routes to tell which child should I render.
Also on the router, i'm making a <'PrivateRoute'> to check if the user would have access to said route based on a Recoil state, if he has no access i would redirect him back to login.

My application router is this:

```ts
<BrowserRouter>
  <Switch>
     <Route path={['/login', '/forgot-password', '/change-password']} exact component={makeLogin} />
      <PrivateRoute path='/' exact component={makeMainPage} />
   </Switch>
</BrowserRouter>
```
The <'PrivateRoute'> setup was this (it changes based on the state of the userAccount): 

```ts
const PrivateRoute: React.FC<RouteProps> = (props: RouteProps) => {
  const { getCurrentAccount } = useRecoilValue(currentAccountState)
  return getCurrentAccount()?.accessToken
    ? <Route {...props} />
    : <Route {...props} element={<Navigate to='/login' />} />
}
```

And my loginFactory is this: 
```ts
<Row gutter={[0, 24]}>
  <Col xs={24} sm={24} md={8} xxl={8} className={Styles.layoutLogin}>
    <Routes>
      <Route path="/login" element={<LoginForm validation={validation} authentication={authentication} machineHostname={machineHostname} />} />
      <Route path="/forgot-password" element={<ForgotPasswordForm forgotPassword={forgotPasswordRemote} validation={forgotPasswordValidation} />} />
      <Route path="/change-password" element={<ChangePasswordForm changePasswordRemote={changePasswordRemote} />} />
    </Routes>
  </Col>
</Row>
```

### Expected Behavior

Work like it did on previous version.
I know this is a very isolated case but I'm a bit lost in how to achieve this now, i saw the migration guide and wasnt able to achieve the behaviour of this setup with the new API.

Should I change what I did or is there some way to make this sort of setup work on V6?
Should I wait for the backwards compatibility package to be released?

### Actual Behavior

Receiving errors and not being able to use the same kind of implementation.

**Comment by timdorr** [comment]
gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f
