### ISSUE TITLE
[v6][Feature]: Support query param routes like `/?/route/123`

### ISSUE THREAD

**Issue by pascalgn** [remix-run/react-router#8388]
### What is the new or updated feature that you are suggesting?

I think this could actually be a bug or undefined behaviour, but in v5, BrowserRouter supports setting e.g. `basename="/prefix/?"` (note the `?` at the end). This will then create routes like `/prefix/?/route/1`: https://codesandbox.io/s/react-router-url-parameters-forked-vlz4g?file=/example.js

When doing the same thing in v6 (6.0.2), no route is matched and we get a warning `<Router basename="/view/?"> is not able to match the URL "/view/" because it does not start with the basename, so the <Router> won't render anything.`

Alternatively, maybe there is another solution for achieving these kinds of query parameter paths?

### Why should this feature be included?

This can be useful if one only has a static index.html without a dynamic backend such as Express. For example, without additional server support, having a page https://example.com/index.html would mean that users could bookmark e.g. https://example.com/?/route/1 but _not_ `https://example.com/route/1` (the server would return 404, because directory "route" does not exist)

**Comment by timdorr** [comment]
I'm actually surprised this worked before. But what you're doing is a bug in pathname parsing in v5. The question mark is the `search` delimiter, so we shouldn't be routing based on anything in it. Routes match only based on the pathname alone.

**Comment by pascalgn** [comment]
@timdorr Would it be possible to implement it in v6? I've written some motivation for it in the "Why should this feature be included?" section and with the popularity of static sites, I think it might be useful. Or should people use the [HashRouter](https://v5.reactrouter.com/web/api/HashRouter) instead? But the docs say "this technique is only intended to support legacy browsers, we encourage you to configure your server to work with &lt;BrowserHistory&gt; instead"
