### ISSUE TITLE
[Bug]: route path never match if basename include #

### ISSUE THREAD

**Issue by diondirza** [remix-run/react-router#8391]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

code: 
```js
<BrowserRouter basename={'/base#/test'}>
  <Routes>
    <Route path="/" element={<Layout />}>
      <Route index element={<Home />} />
    </Route>
  </Routes>
</BrowserRouter>
```
- navigate to the `/base#/test`

### Expected Behavior

Should render the element just fine like v5

### Actual Behavior

it won't render the Home component, instead it says
![image](https://user-images.githubusercontent.com/10954870/143370780-013b7198-ba17-4656-9dc6-839087d95f90.png)

**Comment by timdorr** [comment]
That is not a valid pathname, so this is working as intended. The hash is a separate part of the URL structure, so you cannot include it in the base URL.
