### ISSUE TITLE
[Bug]: useSearchParams removes hash from URL

### ISSUE THREAD

**Issue by lukemorales** [remix-run/react-router#8393]
### What version of React Router are you using?

v6

### Steps to Reproduce

On a page that has a hash in the URL, `localhost:3000/home#hash`, update the search params with the setter from `useSearchParams`

### Expected Behavior

As mentioned on #7718, useSearchParams should not interfere with hash navigation, and hash should remain in the URL

### Actual Behavior

Hash is removed from the URL

**Comment by timdorr** [comment]
Thinking about this in more detail, this is correct as is. 

Changing the search parameters should result in a new page (or route, in our case, but it functions the same). The hash is intended as a reference to the contents of the current page. So, when you're navigating to a new page, it shouldn't maintain the same hash as that may no longer exist in the new page's contents. It would not be semantically valid to retain it between page views. `setSearchParams` is doing a navigation, so you are ending up on a new page.

**Comment by johnflux** [comment]
Is there any workaround for this?

**Comment by lecoqlibre** [comment]
If you control the url generation, you could encode your url with base64.

**Comment by SimonGodefroid** [comment]
In 2024 having the same issue we have a drop down component with react-select that sets some search params (the id of the selected resource for fetching its details) and if a page using that selector component has tabs which means hashes, they get wiped on the setSearchParams. Nice to see you here @lukemorales 😄

**Comment by penx** [comment]
> Thinking about this in more detail, this is correct as is.
> 
> Changing the search parameters should result in a new page (or route, in our case, but it functions the same). The hash is intended as a reference to the contents of the current page. So, when you're navigating to a new page, it shouldn't maintain the same hash as that may no longer exist in the new page's contents. It would not be semantically valid to retain it between page views. `setSearchParams` is doing a navigation, so you are ending up on a new page.

This seems to have had a lot of thumbs down, but to add to (and in defence of) this logic - I am currently working on an app which _doesn't_ remove the hash from the URL when search params change. This has resulted in a bug where, when the hash relates to an element id on the page (often the intended purpose of using a hash), the viewport jumps to that element whenever the search params change.

I don't want this behaviour - the search params are controlled via a toolbar at the top of the page, if a user has previously visited a hash location within the document, I don't want to refocus it whenever a user interacts with the toolbar.

**Comment by dbalatero** [comment]
> Thinking about this in more detail, this is correct as is.

I would say:

- Sometimes you want this behavior
- Sometimes you do not

and the `setSearchParams()` API should allow the caller to _choose_ what they want (and feel free to default to whatever you believe is the best default).

**Comment by vincerubinetti** [comment]
> Changing the search parameters should result in a new page 

No. That has never been a requirement. Search params can just encode some change in the current page, like a selected tab. They do not have to represent a completely new route. 

> It would not be semantically valid to retain it between page views. 

This is mental gymnastics.

---

[Here is an alternative](https://github.com/pbeshai/use-query-params) for people looking for more control, but unfortunately [it still suffers from the same issue](https://github.com/pbeshai/use-query-params/issues/229).

**Comment by DoctypeRosenthal** [comment]
> Thinking about this in more detail, this is correct as is.
> 
> Changing the search parameters should result in a new page (or route, in our case, but it functions the same). The hash is intended as a reference to the contents of the current page. So, when you're navigating to a new page, it shouldn't maintain the same hash as that may no longer exist in the new page's contents. It would not be semantically valid to retain it between page views. `setSearchParams` is doing a navigation, so you are ending up on a new page.

What about single page applications where every route is the same page?

**Comment by laurelthorburn** [comment]
Would be nifty if this was an option in the `navOptions` like `{retainHash: true}`

**Comment by mttetc** [comment]
Please add an option to either manually set the hash with setSearchParams({foo: "bar"}, { hash }) or another option to just retain it

**Comment by danny-does-stuff** [comment]
Yes please add an option to retain the hash! I understand the argument of new query params being new pages, but it seems to be difficult and unintuitive for certain use cases. Here's the page I'm working on:

<img width="1429" height="602" alt="Image" src="https://github.com/user-attachments/assets/6b945d8f-06d3-48fa-9567-853d706676f7" />

I want the filters (subject, grades, search) to use search params, and the tabs to use the hash. What would be the recommended way to do this? For now I opted to just use query params for everything, but it makes sense to me that the tabs would use the hash. Let me know if you have any insights.
