### ISSUE TITLE
[Bug]: Redirecting to sub routes from the main route on the page load is not working

### ISSUE THREAD

**Issue by manjureddy7** [remix-run/react-router#8395]
### What version of React Router are you using?

v6

### Steps to Reproduce

In my root file where I have all other routes, I have the following code

`<Route path="main/*" element={<Main />}/> // When the path is '/Main' go to Main component.`

I have the below code in my Main.jsx file

```jsx
const Main = () => {
  return(
    <div>
      <h1>I'm mains page</h1>
       <Routes>
          <Route path="" render={() => <Navigate to='landing' />} />
          <Route path="xyz" element={<h1>From xyz</h1>} />
          <Route path="landing" element={<h1>From landing page</h1>} />
      </Routes>
      <Outlet />
    </div>
  )
}

```
The behavior I'm trying to achieve here is, when the user goes to /main page, I want them to redirect to '/main/landing', but the redirection is not working ,

### Expected Behavior

Redirection on the subroutes has to work

### Actual Behavior

Redirection on the subroutes is not working

**Comment by liuhanqu** [comment]
The `Route` component do not have `render` prop in v6, use `element` instead.

**Comment by manjureddy7** [comment]
Thank you @liuhanqu  that worked, don't how did I miss that 

`<Route path="" element={<Navigate to='landing' />} />`

**Comment by manjureddy7** [comment]
closed
