### ISSUE TITLE
Broken routing at the React Router website

### ISSUE THREAD

**Issue by visortelle** [remix-run/react-router#8401]
### What version of React Router are you using?

-

### Steps to Reproduce

See attached video. https://reactrouter.com/

https://user-images.githubusercontent.com/9302460/143742094-51eed8cd-328b-4fe0-aae6-1753f21c04f1.mov

### Expected Behavior

-

### Actual Behavior

-

**Comment by andrei9669** [comment]
huh, ironic

**Comment by timdorr** [comment]
I'm not able to reproduce this myself. But this may be more of a Remix bug than a Router bug.

**Comment by visortelle** [comment]
Checked today. Now it works as expected.
