### ISSUE TITLE
[Bug]: useSearchParams' setter resets hash

### ISSUE THREAD

**Issue by Ayc0** [remix-run/react-router#8405]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

The code is available here: https://codesandbox.io/s/react-router-6-use-search-params-hash-uu6yy?file=/src/App.js

https://user-images.githubusercontent.com/22725671/143776011-fc56aee2-d18e-4aaa-94c2-eb2608a7375e.mov

### Expected Behavior

When the search params are updated, I'd assume that only the search params would have been updated, not the hash.

### Actual Behavior

The hash is reset

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8393#issuecomment-979676684

**Comment by johnflux** [comment]
Is there any work around for this?
