### ISSUE TITLE
[Bug]: StaticRouter's context is missed in v6

### ISSUE THREAD

**Issue by wood1986** [remix-run/react-router#8406]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. use the sample code from https://v5.reactrouter.com/web/guides/server-rendering
```jsx
function Status({ code, children }) {
  return (
    <Route
      render={({ staticContext }) => {
        if (staticContext) staticContext.status = code;
        return children;
      }}
    />
  );
}
```

2. read the `code` from `staticContext`

### Expected Behavior

I can read the context object

### Actual Behavior

I cannot read the `code` because v6 implementation does not support `context`

**Comment by timdorr** [comment]
This is correct. It was removed in v6. Just use [a React Context](https://reactjs.org/docs/context.html) directly.

**Comment by wood1986** [comment]
But as it is not inside the react tree. How do you read the context value outside the react tree? How does it look like? Like this. if so, it will be odd

![image](https://user-images.githubusercontent.com/5212215/143808253-b2fec253-a510-4c75-8e15-84c4af201fdc.png)

**Comment by qjd-yyds** [comment]
> This is correct. It was removed in v6. Just use [a React Context](https://reactjs.org/docs/context.html) directly.

I'm working on it, too. That's a great way to do it

**Comment by supermanklk** [comment]
solution 1: https://github.com/supermanklk/custom-ssr-server/commit/4f6c1164046603814ba54150f1dfa6c314a96c72

**Comment by webholics** [comment]
Also stumbled upon this. I think it was a mistake to remove this from react router because now everyone has build his own solution. And basically every SSR application will need this.

At least it should be mentioned in the migration guide.

**Comment by tomtom94** [comment]
I just found pretty alternative.

Just create a new file `StaticContext.tsx`

```
import React, { createContext, FC, ReactNode } from 'react'

export const StaticContext = createContext<null | {
  statusCode?: number
}>(null)

type Props = {
  children: ReactNode
  staticContext: { statusCode: number }
}

const StaticContextProvider: FC<Props> = ({ children, staticContext }) => {
  return <StaticContext.Provider value={staticContext}>{children}</StaticContext.Provider>
}

export default StaticContextProvider
```

In your server file `server.tsx`

```
import StaticContextProvider from './StaticContext'
...
const staticContext = { statusCode: 200 }

const html = renderToString(<StaticContextProvider staticContext={staticContext}>
  <StaticRouter location={req.url}>
    ...
  </StaticRouter>
</StaticContextProvider>)

res
  .status(staticContext.statusCode)
  .send(renderFullPage(html, css, ...))
```

Then in your component page `Movies.tsx`

```
import { StaticContext } from '../../server/StaticContext'

const Movies: FC<Props> = ({ children, ...props }) => {

  const staticContext = useContext(StaticContext)

  if (!process.env.BROWSER && staticContext && movies.error) {
    staticContext.statusCode = movies.error.status
  }

  return null
}
```

If ever you got stuck, I recommend you to clone my boilerplate repository https://github.com/tomtom94/react-easy-ssr

**Comment by wood1986** [comment]
You can take a look my plugin and example I made. https://assets.woodfung.dev/react-ssr-webpack-plugin/

I see several things in repo.
- you have multiple webpack configs. Mine is using one.
- you use react helmet to handle the head tag. Mine is using react to handle the head tag
- you need two process to generate CSR and SSR bundle. Mine is using one process


My plugin also has some other benefits, in-line the javascript in the head tag, chunk integrity...

Here is an example to how data fetching look likes in SSR scenario 
https://assets.woodfung.dev/react-ssr-webpack-plugin/docs/examples/relay

You can see my demo
server side rendering webpack plugin for react app
https://youtu.be/3oixZZHacjQ

**Comment by wood1986** [comment]
For the routing stuff, you check this example https://assets.woodfung.dev/react-ssr-webpack-plugin/docs/examples/app#advanced-and-single-entry-with-react-router-app30
