### ISSUE TITLE
[Bug]: Docs or types are wrong on `To` of `Link`

### ISSUE THREAD

**Issue by meesvandongen** [remix-run/react-router#8411]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

Using the link component
```ts
<Link
  to={{
    state: {
      someProp: "1"
    }
  }}
>
  Some Text
</Link>
```
TypeScript will complain that type To does not have a property state. The docs however, do state that this is possible:
```ts
type To = Partial<Location> | string;
```
With Location being 
```ts
{
    pathname: Pathname;
    search: Search;
    hash: Hash;
    state: any;
    key: Key;
}
```

However; the type of Link is 
```
type To = Partial<Path> | string;
```

With Path being 
```ts
{
    pathname: Pathname;
    search: Search;
    hash: Hash;
}
```

So, the docs and the types are inconsistent. One should be updated (The types I think?).

### Expected Behavior

One of the following:
* `State` is accepted as type for `To`
*  The docs have 
   ```ts
   type To = Partial<Path> | string;
   ```

### Actual Behavior

Docs say
```ts
type To = Partial<Location> | string;
```
But types say
```ts
type To = Partial<Path> | string;
```

**Comment by harxki** [comment]
In v6, "to" no longer includes Location.So I think the state has to be passed to Link as an independent object.

```tsx
<Link
  to="/my"
  state={{ 
     someProp: "1"
   }}
>
  Some Text
</Link>
```

See the Link type in the [doc](https://reactrouter.com/docs/en/v6/api#link)

**Comment by brophdawg11** [comment]
Going to close this out since the current [docs](https://reactrouter.com/en/6.7.0/components/link) include the proper `To` type.  I did notice that we don't have a section for the `state` prop so adding that in https://github.com/remix-run/react-router/pull/9971.
