### ISSUE TITLE
[Bug]: Error: [ProxyFacade] is not a component. All component children of must be a or <React.Fragment>

### ISSUE THREAD

**Issue by haixiangyan** [remix-run/react-router#8415]
### What version of React Router are you using?

v6.0.2

### Steps to Reproduce

Here's the error message I got: **Error: [ProxyFacade] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>**.

I found the same question on [stackoverflow](https://stackoverflow.com/questions/70037167/error-proxyfacade-is-not-a-route-component-all-component-children-of-rout) without the answers.

### App.tsx
```tsx
import * as React from "react";
import "./index.less";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { hot } from "react-hot-loader";
import SignIn from "../sign-in";
import SignUp from "../sign-up";

const App = () => {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<SignIn />} />
        <Route path="/signup" element={<SignUp />} />
      </Routes>
    </BrowserRouter>
  );
};
declare let module: Record<string, unknown>;

export default App;
```

### SignIn.tsx

```tsx
import { hot } from 'react-hot-loader/root';
import * as React from "react";
const SignIn = () => {
  return (
    <React.Fragment>
      <div>
        <p>Sign In</p>
      </div>
    </React.Fragment>
  );
};

export default hot(SignIn);
```

### Expected Behavior

No errors.

### Actual Behavior

**Error: [ProxyFacade] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>**.

I tried remove the `react-hot-loader`'s `hot` function, and it works. So I think maybe `react-router@v6` is not compatiable with `react-hot-loader` right now? 🤔  If `<Routes>` component can accept the other component should work fine?

**Comment by Saltallica** [comment]
I just ran in to this as well in the process of upgrading from v4 to v6. Totally not a React Router issue :-|

**Comment by asleepysamurai** [comment]
Yes ran into the same issue while upgrading from v4 to v6. react-router seems to have an extremely strict class type check which is breaking because react-hot-loader wraps the class in a `ProxyFacade`.

**Comment by haixiangyan** [comment]
I know it's a compatibility problems. Hopefully someone could handle this issue (sad 😔)

**Comment by Hujianboo** [comment]
> I know it's a compatibility problems. Hopefully someone could handle this issue (sad 😔)

The introduction of React-Hot-Loader hopes to be replaced by React Fast Refresh in the future.

**Comment by robyoder** [comment]
I'm currently using `react-router-dom-v5-compat@6.11.2`, and switching to `react-refresh` with `@pmmmwh/react-refresh-webpack-plugin` and `react-refresh-typescript` worked for me. Thank you!
