### ISSUE TITLE
[Bug]: child component onMount hook runs before parent onMount in create-react-app when running npm run build

### ISSUE THREAD

**Issue by dmr07** [remix-run/react-router#8421]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

When using create-react-app, I have the following setup: 

```js
const Account = ({token, user, setToken, setUser}) => {
  const [view, setView] = useState("portfolio");
  let navigate = useNavigate();

  useEffect(() => {
        console.log('this runs before the onmount in app content')
        if (!token) return navigate('/signin')
  }, []);
... 
};

const AppContent = () => {
    useEffect(() => {
        console.log('this runs after account for some reason on production');
    }, []); 

   return (<>
      <Routes>
          <Route exact path="/account" element={<Account token={token} user={user} setToken={setToken} setUser={setUser}/>} />
...
      </Routes>
   </>)
}

const App = () => (
        <Router>
            <AppContent />
        </Router>
)
```

### Expected Behavior

Child component (Account) onmount hook should run after the parent component (AppContent) in both production (yarn start) and build (npm run build). 

### Actual Behavior

Child component (Account) onmount hook runs after parent component (AppContent) in development environment (yarn start) but runs before parent component in production (npm run build).

**Comment by timdorr** [comment]
This is just how React itself works. See facebook/react#15281
