### ISSUE TITLE
[Feature]: Stateful nested route child elements *conditionally rendered* in the parent

### ISSUE THREAD

**Issue by parkournerd** [remix-run/react-router#8426]
### What is the new or updated feature that you are suggesting?

Suppose we have the following structure:
```
<Routes>
    <Route path = "explore" element = {<ExplorePage/>}>
        <Route path = "groups" element = {<GroupsModule/>}/>
        <Route path = "events" element = {<EventsModule/>}/>
    <Route/>
</Routes>
```
And the following parent component:
```
const ExplorePage = () => {
    const module = useOutlet();
    const mobile = useMobile();

    if(mobile){
        return (<MobileView>{module}</MobileView>);
    } else {
        return (<DesktopView>{module}</DesktopView>);
    };
};
```
-
Problem: every time the view changes, module will be rebuilt destroying the state.
-
Request: I would like an elegant way to deal with these stateful nested route child elements *conditionally rendered* in the parent. Perhaps allowing modules to be hooks instead of only React.Components and storing the state while the match is valid? I know ways to do this without nested Routes and Outlets, but I do like this very clear declarative style introduced in V6.

On top addition to this simple case, I really want use GroupsModule as a data source, so just one component will not do.

### Why should this feature be included?

I cannot be the only one doing conditional rendering with Outlets.

**Comment by timdorr** [comment]
I'm not sure exactly what you're asking for here, but how you structure your components and use Outlet is up to you. How you have it structured is the generally intended way to deal with this kind of condition.
