### ISSUE TITLE
[Bug]: V6 with TypeScript Route Config not possible

### ISSUE THREAD

**Issue by bnheise** [remix-run/react-router#8429]
### What version of React Router are you using?

6+

### Steps to Reproduce

1. Create a React App and configure TypeScript.
2. Install react-router-dom version 6 (any).
3. Follow the steps here: https://v5.reactrouter.com/web/example/route-config

You will see a TypeScript error saying that render does not exist on the type Route.
When you view the definition you see that indeed the type definition is not correct--the definition loaded cannot work with the example provided in the documentation.
Switching back to version 5 fixes the error.

Additionally, importing Route from react-router rather than react-router-dom also fixes the issue. However, one shouldn't need to do that.

### Expected Behavior

I expect that, as with version 5, render is an expected prop of Route without importing directly from react-router.

### Actual Behavior

The TypeScript type for Route packaged with react-router-dom version 6 does not contain the correct type definition.

**Comment by timdorr** [comment]
You shouldn't be using the v5 docs with v6 of the library. Follow the upgrade guide: https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by bnheise** [comment]
> You shouldn't be using the v5 docs with v6 of the library. Follow the upgrade guide: https://reactrouter.com/docs/en/v6/upgrading/v5

V5 Docs are not labeled as V5 docs. You have to notice that it says V5 in the URL.

If you search for react router dom, you get the v5 docs by default.

If you run ```npm install react-router-dom``` you get version 6 by default.

Perhaps you could consider putting a note on the v5 docs saying that v6 is out and doesn't work with v5 so here's the link to the v6 docs?
