### ISSUE TITLE
export '__RouterContext' (imported as '__RouterContext') was not found in 'react-router' 

### ISSUE THREAD

**Issue by code-masala** [remix-run/react-router#8430]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

node version-
14.17

### Expected Behavior

.

### Actual Behavior

.

**Comment by code-masala** [comment]
@mjackson

**Comment by timdorr** [comment]
Please don't tag people to try and get their response. That is rude. This isn't a React Router bug, so I'm closing it.
