### ISSUE TITLE
[Bug]: TS2305: Module '"react-router"' has no exported member 'Switch'.

### ISSUE THREAD

**Issue by SinLess-Games** [remix-run/react-router#8439]
### What version of React Router are you using?

react-router=6.0.2  and react-router-dom=6.0.2

### Steps to Reproduce

I have uninstalled and reinstalled both, I have tried each individually as well I get the same error saying there is no switch function.

### Expected Behavior

I was expecting it to work, as i was following a video only 4 months old

### Actual Behavior

./src/router.tsx
Attempted import error: 'Switch' is not exported from 'react-router'.
Compiling...
Failed to compile.

**Comment by SinLess-Games** [comment]
The  way i am using it is as follows:

`
import react from "react";
import { Route, Switch } from "react-router";
import { BrowserRouter } from "react-router-dom";
import { Homepage } from "./Homepage";

export const Router: React.FC = () => {
    return (
        <BrowserRouter>
            <Switch>
                <Route path="/" component={Homepage} />
            </Switch>
        </BrowserRouter>
    )
}
`

**Comment by liuhanqu** [comment]
Use `Routes` instead of `Switch`.

**Comment by timdorr** [comment]
V6 has different components and APIs. Please read the migration guide.

**Comment by dweng0** [comment]
Think you need to update your guides, most people will just look at your initial guides. I'm not migrating from anything and had this issue....

**Comment by WesleyKapow** [comment]
Highly recommend updating the guides. Currently following the "quick start" guide just flat out fails because of this.

**Comment by artismarti** [comment]
I wasn't migrating anything & ran into this issue, whilst literally following the [Quick Start](https://v5.reactrouter.com/web/guides/quick-start) page. Another vote for updating the docs.

**Comment by timdorr** [comment]
That is the docs for v5. The guide on v6 is what's linked on https://reactrouter.com.

**Comment by WesleyKapow** [comment]
Ah yes the v6 docs are correct!

Hmm not sure if homepage got updated recently or this is an issue of going from google directly to the v5 quick start guide.

**Comment by artismarti** [comment]
Interesting! Thanks for your response, @timdorr. 
As @WesleyKapow suggested, this is a Google redirecting to the old docs issue.
