### ISSUE TITLE
[Feature]: Update react-router-config for v6 of react-router

### ISSUE THREAD

**Issue by darkcattz** [remix-run/react-router#8443]
### What is the new or updated feature that you are suggesting?

Hello, 

I have this error with react-router-config (V5) and react-router (v6) : 

file : react-router-config/esm/react-router-config.js
`Attempted import error: 'Switch' is not exported from 'react-router'.`

Is it possible to update react-router-config to react-router v6 ?

Thanks

### Why should this feature be included?

React-router update to v6 in react-router-config

**Comment by timdorr** [comment]
We are not keeping react-router-config as a separate package because we now have useRoutes built-in. You should only use it with v5.

**Comment by jainChetan81** [comment]
hi @timdorr , I am stuck on this problem as well, is there any example or migration path for react-router-config to builtin`useRoutes` or anything similar?
