### ISSUE TITLE
[Bug]: RouteObject type seems to be slightly different from Route props

### ISSUE THREAD

**Issue by realamirhe** [remix-run/react-router#8445]
### What version of React Router are you using?

6

### Steps to Reproduce

This is [`RouteObjcet`](https://github.com/remix-run/react-router/blob/d02f13cff0b0a5470be994d7b79c26635bb62e5a/packages/react-router/index.tsx#L197-L203) which is used as validation type for `useRoutes` 

```ts
export interface RouteObject {
  caseSensitive?: boolean;
  children?: RouteObject[];
  element?: React.ReactNode;
  index?: boolean;
  path?: string;
}
```
By type definition  the combination of having both `index:true` and `path: "some-path"` is supported. but the rendered output respect `path` and ignore index behavior, which seems to be default and the behavior is fine but the type not :). 

### Expected Behavior

The type issue has been solved for Route component, and it works as expected, but using `RouteObject` for `useRoutes` seems to be inconsistent with the default [Route types](https://github.com/remix-run/react-router/blob/d02f13cff0b0a5470be994d7b79c26635bb62e5a/packages/react-router/index.tsx#L229)

### Actual Behavior

There is no error when you use `index: true` and `path: "some-path"` in `useRoutes` hooks.

**Comment by brophdawg11** [comment]
Per https://github.com/remix-run/react-router/issues/8143 - `index` routes can have a `path` so I think the types are accurate.
