### ISSUE TITLE
 Is router-keepalive supported? I am from China

### ISSUE THREAD

**Issue by chinaxcy** [remix-run/react-router#8448]
### What version of React Router are you using?

 Is router-keepalive supported? I am from China

### Steps to Reproduce

 Is router-keepalive supported? I am from China

### Expected Behavior

 Is router-keepalive supported? I am from China

### Actual Behavior

 Is router-keepalive supported? I am from China

**Comment by timdorr** [comment]
Please don't open issues not related to the React Router library itself.
