### ISSUE TITLE
[Bug]: __RouterContext is no longer being exported in v6

### ISSUE THREAD

**Issue by geoff-harper** [remix-run/react-router#8453]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

Attempt to import `__RouterContext`

### Expected Behavior

In v5.x this was being exported for external use. I am using two react renderers in the same project and previously I was able to pass the context object down into the second renderer (see https://github.com/pmndrs/drei#usecontextbridge). This enabled navigating within the three.js tree. Redux and styled-components allow this sort of usage as well. I'm hoping this is an oversight instead of a hard technical limitation and that it can be re-exported in an upcoming version. This is a big blocker for me and I'm locked into v5 indefinitely if it isn't changed

### Actual Behavior

Failure to import.

**Comment by timdorr** [comment]
This was never a supported API. react-router-dom no longer uses this and [actually uses only public APIs from react-router](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L4-L27). 

What you're likely going to need is #8264. In that issue are some potential workarounds for you, so you can use a common `history` instance.
