### ISSUE TITLE
[Feature]: Add A Chinese Version to React Router

### ISSUE THREAD

**Issue by mffy** [remix-run/react-router#8454]
### What is the new or updated feature that you are suggesting?

Hello, as a chinese native speaker, I's like to contribute a chinese translated verision of docs in Chinese.

### Why should this feature be included?

SInce there are many chinese-speaking reader of the doc, it's necessary to add a Chinese version of the doc.

**Comment by timdorr** [comment]
Thanks, but no one here (that I know of) is fluent in Mandarin or Cantonese. So, we would have no way of knowing when the docs are out of date or say something incorrectly. 

It's probably best that this is left to third-party projects, [much like we do with Redux](https://github.com/camsong/redux-in-chinese).
