### ISSUE TITLE
[Bug]: Attempted import error: 'Outlet' is not exported from 'react-router-dom'.

### ISSUE THREAD

**Issue by farukbigez** [remix-run/react-router#8469]
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

`Attempted import error: 'Outlet' is not exported from 'react-router-dom'.` I'm only exporting 'Outlet' and building it and using on a package from on dist folder with typescript

### Expected Behavior

It should be imported when it's built 

### Actual Behavior

No error showing or wrong package issue. All thing happens when I tried to build it.

**Comment by Lijiaoa** [comment]
@farukbigez so how to fix this bug? I also met the same issue. Could you help me?

**Comment by farukbigez** [comment]
@Lijiaoa I solved this problem, `rm -rf yarn.lock && rm -rf node_modules` then `yarn install` or `npm install` , finally importing `Outlet` like this: `import { Outlet } from 'react-router-dom'`

This solved my issue
