### ISSUE TITLE
[Feature]: Export PathPattern, ParamParseKey and possibly ParamParseSegment

### ISSUE THREAD

**Issue by evantrimboli** [remix-run/react-router#8472]
### What is the new or updated feature that you are suggesting?

The `PathPattern`, `ParamParseKey` and possibly `ParamParseSegment` should be exported so they can be used in client libraries.

### Why should this feature be included?

I wanted to write a context aware `useMatch`, so that if I was already inside the `orders/` route, I could use the following without needing to include the full path:

```typescript
const match = useResolveMatch(':orderId');
```

The resolved match works fine, but I'm unable to type it correctly without those types exported

```typescript
// Want to be able to use ParamParseKey here
export const useResolvedMatch = <
  ParamKey extends ParamParseKey<Path>,
  Path extends string,
>(
  to: Path,
  end = true,
): PathMatch<ParamKey> | null =>
  useMatch({ path: useResolvedPath(to).pathname, end })
```

**Comment by brophdawg11** [comment]
Closed in #8911
