### ISSUE TITLE
[Feature]: Export NavigationType enum as value.

### ISSUE THREAD

**Issue by latin-1** [remix-run/react-router#8475]
### What is the new or updated feature that you are suggesting?

Export NavigationType enum as value.

### Why should this feature be included?

.

**Comment by timdorr** [comment]
This just comes from `history`, so the underlying type isn't controlled here: https://github.com/remix-run/react-router/blob/997b4d67e506d39ac6571cb369d6d2d6b3dda557/packages/react-router/index.tsx#L11

**Comment by latin-1** [comment]
@timdorr `history` exports it as value, so the thing we need to do is change the `export type` to `export` for it.

**Comment by latin-1** [comment]
More precisely, change
```ts
export type { Location, Path, To, NavigationType };
```
to
```ts
export { NavigationType };
export type { Location, Path, To };
```
