### ISSUE TITLE
[Bug]: `useMatch` always returning null

### ISSUE THREAD

**Issue by ldeveber** [remix-run/react-router#8485]
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

1) have app running 5.2
2) upgrade to 6, follow guide, including replacing `useRouteMatch` with `useMatch`
    a) api documentation doesn't say anything about what patterns are supported https://reactrouter.com/docs/en/v6/api#matchpath

for the following routes:
* /my/path/cat/:catId
* /my/path/task/:taskId/cat/:catId

the following doesn't work and always returns null
```js
const match = useMatch('*/cat/:catId');
```
NOTE: this `useMatch` is above all the routes, as it handles looking for the cat before loading any of the routes

### Expected Behavior

the following code returns a match
```js
const match = useMatch('*/cat/:catId');
```

and if this is not expected behavior, the api docs explain more about what patterns are supposed to be used

### Actual Behavior

the following code returns null:
```js
const match = useMatch('*/cat/:catId');
```

**Comment by hornta** [comment]
@Ideveber
Try to either append /* at the end of the pattern OR pass an object with `end: false`

```js
useMatch("XXX/*");
```
OR
```js
useMatch({ path: "XXX", end: false });
```

**Comment by thany** [comment]
Same problem here, with identical circumstances: a path match BEGINNING with an asterisk. Solution doesn't work.

No amount of combining flags and asterisks yield any result from `useMatch`. The only thing that works, is an absolute path, which (pardon the pun) is absolutely not workable in our scenarios.

**Comment by hornta** [comment]
@thany Does this match your use case? https://codesandbox.io/s/naughty-water-fb8lb

**Comment by thany** [comment]
Can this bug be reopened please? Thanks.

**Comment by ldeveber** [comment]
> @ldeveber Try to either append /* at the end of the pattern OR pass an object with `end: false`
> 
> ```js
> useMatch("XXX/*");
> ```
> 
> OR
> 
> ```js
> useMatch({ path: "XXX", end: false });
> ```

I'm confused...how would appending `/*` fix needing the `*` at the beginning? Shouldn't it be prepended? This doesn't fix it at all.

**Comment by thany** [comment]
Exactly my thoughts. And then I started digging and found out how severely limited route matching has become 😕

**Comment by thany** [comment]
Alright, fine. Recreated.

See #8684

**Comment by thany** [comment]
Next time, please respond at the very least. Radio silence is *even worse* than a negative response.
