### ISSUE TITLE
[Bug]: state update up the tree causes Route to remount

### ISSUE THREAD

**Issue by AlonBru** [remix-run/react-router#8486]
### What version of React Router are you using?

latest

### Steps to Reproduce

1. have a state up in component tree
2. have Switch with Routes inside
3. Route should use "Component" prop for child
3. change state in top of tree component

### Expected Behavior

state changes, route will not remount child

### Actual Behavior

route does remount, thus destroying any inner state.
example provided here:[codesandbox](https://codesandbox.io/s/react-router-basic-forked-s66c2?file=/example.js).
in the example shown are two methods, in both pressing the "test" button sets the high-up state to what's in the input :
1. page  1, using the Component prop in the Route and displaying the bug
2. page 2, where the bug does not happen because the child is given differently

both routes have a Profiler Component, so you can see whether they are remounted

**Comment by timdorr** [comment]
You are creating a new component function inline. When it re-renders due to the state update, it sees a "new" component and remounts it fresh in the tree. This is just how React works.

**Comment by AlonBru** [comment]
In my project it happens also when not using an arrow function, but could not reproduce in codesandbox.
thanks anyway
