### ISSUE TITLE
[Feature]: Redirect from redux-store

### ISSUE THREAD

**Issue by Kamran95** [remix-run/react-router#8488]
### What is the new or updated feature that you are suggesting?

before you could redirect from redux actions using history.push() method but it doesn't seem to be possible as useNavigate can only be used in react functional component

### Why should this feature be included?

there should be a method to redirect user from redux store as it used to be done by history.push(). now if we use history.push() it changes route but component remains the same as route change is not detected.

**Comment by umermughal1** [comment]
facing same issue

**Comment by filzahamjad** [comment]
facing same issue

**Comment by timdorr** [comment]
Please search before posting a new issue. This has already been answered: https://github.com/remix-run/react-router/issues/8481#issuecomment-993519524

**Comment by Kamran95** [comment]
Your proposed solution doesn't work in redux store as route changes but components doesn't re render
the page remains same

### APP.js

import "./App.css";
import Routes from "./Routes/router";

import {
  unstable_HistoryRouter as HistoryRouter,
  BrowserRouter,
} from "react-router-dom";
import { createBrowserHistory } from "history";

let history = createBrowserHistory();

function App() {
  return (
    <HistoryRouter history={history}>
      <Routes />
    </HistoryRouter>
  );
}

export default App;


**Redux Store actions**
import { createBrowserHistory } from "history";
let history = createBrowserHistory();


export const Login = (data) => (dispatch) => {
  console.log("Welocme to login Action");
  public_url
    .post("auth", data)
    .then((res) => {
      let data = {
        userDetails: res.data.data,
        token: res.headers["x-auth-token"],
      };
      dispatch(LoginSuccess(data));
      ### history.push("welcome");
    })
    .catch((err) => {
      if (err.response) {
        const errors = err.response.data.errors;
        dispatch(LoginFailed(errors));
      }
    });
};
