### ISSUE TITLE
[Feature]: continuing support for v5? (Due to deprecation of features in v6.)

### ISSUE THREAD

**Issue by daisy88888888** [remix-run/react-router#8490]
### What is the new or updated feature that you are suggesting?

I am really upset to see so many major features removed in version 6 of this software. It is simply unusable to us without regular expression paths. Please consider adding these back OR support v5 indefinitely. 

### Why should this feature be included?

Will v5 continue to be maintained? I feel as though the maintainers did not listen to the "customers" of this product and have made sacrifices that might be okay for that projects, but that are really terrible for those of us that rely on these features.

**Comment by timdorr** [comment]
Yes, it will be maintained. I wouldn't expect major feature additions, but we'll still provide bug fixes as needed.
