### ISSUE TITLE
[Feature]: Documentation update for v6

### ISSUE THREAD

**Issue by suyashvash** [remix-run/react-router#8494]
### What is the new or updated feature that you are suggesting?

Documentation Update for V6. As the current official site/docs gives doc about V5 but command installs v6

### Why should this feature be included?

Please update the documentation on main site for V6 react-router. It is totally based on V5 but `npm install react-router-dom` install the v6. There are some common issues like Switch and component prop  replacement.

**Comment by timdorr** [comment]
Not sure what you mean. The current docs are for v6: https://reactrouter.com/

**Comment by suyashvash** [comment]
Ohhh. Actually I was talking about the one which comes up at top of google search. You should add some kind of pop up or alert to direct the users to V6 docs
[](https://v5.reactrouter.com/web/guides/quick-start)
This one

**Comment by timdorr** [comment]
We can't control Google's search rankings. If we did, we'd probably be rich off SEO contracting and not building this library :)
