### ISSUE TITLE
Private routing[Feature]: 

### ISSUE THREAD

**Issue by belisky** [remix-run/react-router#8495]
### What is the new or updated feature that you are suggesting?

Private routing to prevent unauthorised users to certain routes. All the implementations ive seen so far doesnt use your latest version. Please if you have any idea to implement it, I'd love to learn it. Thanks

### Why should this feature be included?

to prevent unauthorised users to certain routes.

**Comment by timdorr** [comment]
This is already one of the examples: https://reactrouter.com/docs/en/v6/examples/auth

**Comment by veloware** [comment]
Apologies for commenting on a closed issue, but can I ask - the comment here - https://stackoverflow.com/a/69592617/1849358 seems to offer a much 'nicer' approach to private routes, with no replication of having to wrap each private element. Does this seem like a valid solution?
