### ISSUE TITLE
[Bug]: react-router-dom build empty index.html

### ISSUE THREAD

**Issue by HeiShuXianSheng** [remix-run/react-router#8496]
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

file：`https://github.com/HeiShuXianSheng/react-build/blob/master/src/App.tsx`
![image](https://user-images.githubusercontent.com/57590348/146482251-bffd5fd3-faec-4c8b-b984-5eb3eddf7149.png)
1. Comment out the above part
2. Open the lower part
3. yarn run `build`
4. chrome open index.html in the build folder
5. find empty page

### Expected Behavior

i need step 5 find a normal page, not empty page.
Because i need build folder to build a cordova `.apk` file, so i need  index.html in the build folder is not empty.

### Actual Behavior

![image](https://user-images.githubusercontent.com/57590348/146483317-3e2717b3-5c17-4351-bd19-f6a86ddc2b51.png)
when i build with only section A ,the index.html is a normal page; when i use router in section B, i comment section A and open section B,then i run `build`, index.html is a empty page.

By th way, i added code `"homepage": "./"` in `package.json`,and  both section A and section B is all right in dev.

**Comment by timdorr** [comment]
This isn't a React Router bug. Check your build tooling.
