### ISSUE TITLE
[Bug]: useParams should not return `undefined`

### ISSUE THREAD

**Issue by tzachov** [remix-run/react-router#8498]
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

Define a route with param (e.g. `user/:id`)
Use `useParams`:
```tsx
const UserPage = () => {
  const { id } = useParams<'id'>()
  return <Profile userId={id} />
}

const Profile: React.FC<{ userId: string }> = ({ userId }) => {...}
```

This won't compile because `id` is possibly undefined and `Profile` expects `string`

### Expected Behavior

`id` should not be `string | undefined` because `/user` should match a different route than `/user/123`

### Actual Behavior

`id` is `string | undefined` unless you use cast:
```tsx
interface UserParams {
  id: string
}

const UserPage = () => {
  const { id } = useParams<keyof UserParams>() as UserParams
  ...
}
```

**Comment by timdorr** [comment]
You cannot know at compile time the component will be contained within any Route. Hence, the params _must_ be partial. We have specifically chosen this type because anything else would encourage unsafe behavior and produce types that essentially lie to you.

**Comment by tzachov** [comment]
It's a route param - not query string. If the parameter doesn't exist it means the route is different.
Let's say you have this configuration: `/group/:groupId/post/:postId`
If groupId is undefined the route will be `/group/post/<postId>` and if postId is undefined the route will be `/group/<groupId>/post`
These two examples should match different routes than `/group/:groupId/post/:postId`

A common convention is that path/route params are manditory while query params are optional.

**Comment by EnesKilicaslan** [comment]
I totally agree with @tzachov , this issue should be resolved instead of being closed.

**Comment by sagiMorPlanck** [comment]
I agree witch tzach.
The convention is that path/route params are mandatory while query params are optional

**Comment by talks2much** [comment]
@timdorr I think that decision was **completely wrong**, https://github.com/remix-run/react-router/issues/8498#issuecomment-997176141 already explained why. By default params **must** be mandatory. Let developer choose when to use optional params:
```ts
const Post: React.FC = () => {
    const params = useParams<{ groupId: string, postId?: string }>()
    // expected: groupId is required and postId not
    // actual: both are optional ...
    /* ... */
}
```

You make `useParams` generic useless and in 100% cases its much easier to cast the type:
```ts
const Post: React.FC = () => {
    const params = useParams() as { groupId: string, postId?: string }
    /* ... */
}
```

Why don't make `useParams` accept two args in generic:

- First one for mandatory params
- Second one for optional

And in case of passing an object force devs that want old behavior to write `?`.

**Comment by vadimshvetsov** [comment]
I've found the most handy way for myself in using `invariant` here from [tiny-invariant](https://www.npmjs.com/package/tiny-invariant) library.
```
import invariant from 'tiny-invariant'

interface UserParams {
  id: string
}

const UserPage = () => {
  const { id } = useParams<UserParams>()
  invariant(id, 'User id isn't set within the route')
  // After `invariant` id considering as existing
  return <Profile userId={id} />
}
```

**Comment by spiropoulos94** [comment]
> 

Hello, I was wondering about why do we have to explicitly set `<keyof UserParams>` as a type to pass on useParams.

I think that just casting it to our  custom `UserParams ` interface makes our code work propertly and also forces the return value to have the properties of the `UserParams` . Could you please explain? Maybe I am missing something.

Thank you for your time, this is really important for me, I have been searching an answer for ages.

**Comment by spiropoulos94** [comment]
> ### What version of React Router are you using?
> 6.1.1
> 
> ### Steps to Reproduce
> Define a route with param (e.g. `user/:id`) Use `useParams`:
> 
> ```tsx
> const UserPage = () => {
>   const { id } = useParams<'id'>()
>   return <Profile userId={id} />
> }
> 
> const Profile: React.FC<{ userId: string }> = ({ userId }) => {...}
> ```
> 
> This won't compile because `id` is possibly undefined and `Profile` expects `string`
> 
> ### Expected Behavior
> `id` should not be `string | undefined` because `/user` should match a different route than `/user/123`
> 
> ### Actual Behavior
> `id` is `string | undefined` unless you use cast:
> 
> ```tsx
> interface UserParams {
>   id: string
> }
> 
> const UserPage = () => {
>   const { id } = useParams<keyof UserParams>() as UserParams
>   ...
> }
> ```

Hello, I was wondering about why do we have to explicitly set <keyof UserParams> as a type to pass on useParams.

I think that just casting it to our custom UserParams interface makes our code work propertly and also forces the return value to have the properties of the UserParams . Could you please explain? Maybe I am missing something.

Thank you for your time, this is really important for me, I have been searching an answer for ages.

**Comment by alex3wielki** [comment]
My solution is just a custom hook. It's not perfect, but it works

```
function useRequiredParams<T extends Record<string, any>>() {
  const params = useParams<T>();
  return params as T;
}
```

**Comment by ilbrando** [comment]
> My solution is just a custom hook. It's not perfect, but it works
> 
> ```
> function useRequiredParams<T extends Record<string, any>>() {
>   const params = useParams<T>();
>   return params as T;
> }
> ```
> 
> Usage:
> 
> ```
> export default function App() {
>   const { id } = useRequiredParams<{ id: string }>();
>   return <>test</>;
> }
> ```

I agree, `useParams` shouldn't force us to make casts everywhere. Your work around solves the problem. Just for your information it can be written a bit shorter and you can avoid `any` by using `unknown`.

```typescript
export const useRequiredParams = <T extends Record<string, unknown>>() => useParams() as T;
```

**Comment by ArturKustyaev** [comment]
> > My solution is just a custom hook. It's not perfect, but it works
> > ```
> > function useRequiredParams<T extends Record<string, any>>() {
> >   const params = useParams<T>();
> >   return params as T;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usage:
> > ```
> > export default function App() {
> >   const { id } = useRequiredParams<{ id: string }>();
> >   return <>test</>;
> > }
> > ```
> 
> I agree, `useParams` shouldn't force us to make casts everywhere. Your work around solves the problem. Just for your information it can be written a bit shorter and you can avoid `any` by using `unknown`.
> 
> ```ts
> export const useRequiredParams = <T extends Record<string, unknown>>() => useParams() as T;
> ```

how to pass an interface to a generic, an error pops up?

**Comment by enablonian** [comment]
Version 7 and still facing this.
