### ISSUE TITLE
[Bug]: Link to "../" not working properly

### ISSUE THREAD

**Issue by Zodiase** [remix-run/react-router#8499]
### What version of React Router are you using?

6.1.1

### Steps to Reproduce

1. Go to a route that's deep enough, like "domain.com/a/bout".
2. Render `<Link to="../">Parent</Link>`.
3. See the final link is `"/"` instead of `"/a"`.

### Expected Behavior

`to="../"` should link to one level above the current location, not to the root.

### Actual Behavior

`to="../"` seems to always go to root.

**Comment by Isammoc** [comment]
Please, explicit your RouteObject.
Is it nested as expected by the library to perform what you desire?

**Comment by kjschiroo** [comment]
I think the unfortunate answer here is that this is a feature not a bug.

https://reactrouter.com/docs/en/v6/upgrading/v5#note-on-link-to-values

`..` within a link now is in reference to the router, not the url. So if the route to the parent component spans multiple parts the `..` will pop all those parts off.

**Comment by Zodiase** [comment]
@kjschiroo I see. So basically `..` always goes up a `Route`, and if I want more granular levels to go up to I'd break, for example, `domain.com/some-app/resource/:id` into:

```
Route path="some-app"
    Route path="resource"
        Route path=":id"
            Link to="../some-id" //=> domain.com/some-app/resource/some-id
```

Because otherwise I get this issue:
```
Route path="some-app"
    Route path="resource/:id"
        Link to="../some-id" //=> domain.com/some-app/some-id
```
