### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rakesh151994** [remix-run/react-router#8502]
### What version of React Router are you using?

react-router-dom@5

### Steps to Reproduce

The `BrowserRouter` when enabled with the root App.js component it allows to use all the react-router-dom features like using `Route`, `Switch` components but there is one strange case as described below.

```
import './App.css';
import ColorAdder from './ColorAdder';
import {Switch,Route} from 'react-router-dom';
function App() {
  
  return (
  <Switch>
     <ColorAdder/>
     <Route path="/hello" exact>
        <p>Hello</p>
    </Route>
   </Switch>    
  );
}

```
export default App; 

Now some Route components are inside the ColorAdder component as below.

```
import { Route } from "react-router-dom";
const ColorAdder = ()=>{
  return (
    <Route path="/hi" exact>
        <p>Hi</p>
    </Route>
  )
}
export default ColorAdder;
```

When we run the app and test it only recognizes the Route with path "/hi" in the `ColorAdder` component. Its not even displaying for the path with "/hello" although its wrapped by Switch component and even App.js is wrapped by `BrowserRouter` in index.js

```
ReactDOM.render(
    <BrowserRouter>
     <App />
    </BrowserRouter>
  ,
  document.getElementById('root')
);
```

### Expected Behavior

All the Routes defined should be identified irrespective of the routes declared inside the `ColorAdder.js` component or not as long as the Routes are available in the `Switch` component and when `App.js` is wrapped with `BrowserRouter`

### Actual Behavior

The Route with path "/hello" is not recognized by react routing.

**Comment by timdorr** [comment]
You cannot use non-Route components under a Switch.

**Comment by Rakesh151994** [comment]
@timdorr Thanks, so even when the Route components are rendered inside another component that is enclosed in a Switch is not allowed ? Please redirect me to documentation for reference. I'm under the impression that its allowed as BrowserRouter is generally used at the App.js level resulting in identifying Routes across the react app.
