### ISSUE TITLE
[Bug]: useLocation state unknow type in typescript

### ISSUE THREAD

**Issue by alirezamaleky** [remix-run/react-router#8503]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

tsc --noEmit

### Expected Behavior

```
const { state } = useLocation();
console.log(state.userId); // ERROR: Object is of type 'unknown'
```

### Actual Behavior

useLocation must have a generic like this:

```
const { state } = useLocation<{ userId: number }>();
console.log(state.userId);
```

**Comment by timdorr** [comment]
This is due to an underlying change in the history library: https://github.com/remix-run/history/releases/tag/v5.2.0

**Comment by vitorbertolucci** [comment]
> This is due to an underlying change in the history library: https://github.com/remix-run/history/releases/tag/v5.2.0

Could you please demonstrate how to bypass this issue in the described situation?

**Comment by timdorr** [comment]
You should use type narrowing: https://www.typescriptlang.org/docs/handbook/2/narrowing.html

**Comment by QuintonC** [comment]
> You should use type narrowing: https://www.typescriptlang.org/docs/handbook/2/narrowing.html

After looking through documentation and looking at the details that are supplied [here](https://github.com/remix-run/history/blob/main/docs/api-reference.md#state), this isn't the most helpful response.

It might be helpful to people who are unfamiliar with history and history state if you could provide an example of what a history State object might look like so we can have something to use when type narrowing.

**Comment by ali-target** [comment]
> > You should use type narrowing: https://www.typescriptlang.org/docs/handbook/2/narrowing.html
> 
> After looking through documentation and looking at the details that are supplied [here](https://github.com/remix-run/history/blob/main/docs/api-reference.md#state), this isn't the most helpful response.
> 
> It might be helpful to people who are unfamiliar with history and history state if you could provide an example of what a history State object might look like so we can have something to use when type narrowing.

right on

**Comment by larsenwork** [comment]
@ali-target @QuintonC I did something like this — feels a bit clunky but was how I could get around with without any type casting: 
```ts
type From = {
  pathname: string
}
type StateWithFromPathname = {
  from: From
}

const isStateWithFromPathname = (value: unknown): value is StateWithFromPathname => {
  function isSomethingLike<T>(
    given: unknown
  ): given is Partial<Record<keyof T, unknown>> {
    return typeof given === 'object' && given !== null
  }

  return (
    isSomethingLike<StateWithFromPathname>(value) &&
    'from' in value &&
    isSomethingLike<From>(value.from) &&
    'pathname' in value.from
  )
}
```

and then

```ts
  const location = useLocation()

  const redirectTo =
    (isStateWithFromPathname(location.state) && location.state.from.pathname) ||
    PATH.HOME.getPath()
```

**Comment by larsenwork** [comment]
But I'd love to learn/get a cleaner way to do it. 

It'd be nice if the example was updated: https://github.com/remix-run/react-router/blob/9cc42139acd0317a5bfc8ad7aa2dd8e6d573505a/examples/auth/src/App.tsx#L150

**Comment by vitorbertolucci** [comment]
> But I'd love to learn/get a cleaner way to do it.
> 
> It'd be nice if the example was updated:
> 
> https://github.com/remix-run/react-router/blob/9cc42139acd0317a5bfc8ad7aa2dd8e6d573505a/examples/auth/src/App.tsx#L150

I ended up doing it like this:

```
const location = useLocation();

  const navigatePathname = useMemo(() => {
    const state = location.state as { from: string };

    if (state && state.from) {
      return state.from;
    }

    return '/';
  }, [location]);
```

**Comment by larsenwork** [comment]
@vitorbertolucci yeah but then you opt out of any compile time type safety by doing `as { from: string }` 
see [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoUWVB7ArpKAGWwTjGGxGQG8AoZZABzIAsQ4BbCALmQGcwUUAHMA3PX4YoCFrwFCQYiSzh9Z-QSPEMBZHslwgA1iGwB3ENuRGIATzmbF4gL61aCSgORQMCLHgJiUnJKXnRMHHxoILIKKgBeGglmMDZOfQByAHoMgBoJPikZXgy85VV1UvydMD0SsxVIADdoMoYbe2QMmEMM2ld3TzANPWREnwiA6JJYygA6XUhkVRpkGChsDgcFYWRncUWIOfXNubBsGIAbCABVRkZoAGFVCAAKAEpaIA) as example. Anyway we should probably move this to https://github.com/remix-run/react-router/discussions to limit issue noice 🎅  😄

**Comment by Stepmixx** [comment]
> 

Thanks for the hint, but the `{ from: string }` isn't the correct type, you can use `{ from: Location }` instead and it works perfectly.

**Comment by fedefrei** [comment]
Thanks @Stepmixx and @vitorbertolucci for the suggestions. 👍on adjusting the example here: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src/App.tsx

To match what the call should look like.

**Comment by coldwaterfish** [comment]
const state = location.state as { from: string };
work well!thanks
