### ISSUE TITLE
[Bug]: useRoutes will not renderer child page

### ISSUE THREAD

**Issue by southwhale** [remix-run/react-router#8506]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

```js
[
  {
    "element": <Home />
    "path": "/home"
  },
  {
    "element": <About />
    "path": "/about",
    "children": [
      {
        "element": <AboutTesta />
        "path": "testa"
      }
    ]
  }
]
```

### Expected Behavior

when browser url is '/about/testa', it should render `<AboutTesta />`.

### Actual Behavior

did not render the `<AboutTesta />`.

**Comment by Isammoc** [comment]
Try with:

```
[
  { element: <Home />, path: "/home" },
  { path: "/about", children: [
    { element: <About />, index: true },
    { element: <AboutTesta />, path: "testa" } 
  ] }
]
```

Or ensure you have an `<Outlet />` in your `About` component

**Comment by timdorr** [comment]
Without seeing your About component, I can't know this for sure. But you're probably missing an Outlet inside of it.

**Comment by southwhale** [comment]
> Try with:
> 
> ```
> [
>   { element: <Home />, path: "/home" },
>   { path: "/about", children: [
>     { element: <About />, index: true },
>     { element: <AboutTesta />, path: "testa" } 
>   ] }
> ]
> ```
> 
> Or ensure you have an `<Outlet />` in your `About` component

yes, you are right, thanks.

**Comment by southwhale** [comment]
> Without seeing your About component, I can't know this for sure. But you're probably missing an Outlet inside of it.

Thanks, I have got it.

**Comment by xiezhiyi163** [comment]
> > Try with:
> > ```
> > [
> >   { element: <Home />, path: "/home" },
> >   { path: "/about", children: [
> >     { element: <About />, index: true },
> >     { element: <AboutTesta />, path: "testa" } 
> >   ] }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or ensure you have an `<Outlet />` in your `About` component
> 
> yes, you are right, thanks.

I can't change the subroute without index:ture
