### ISSUE TITLE
[Bug]: Using useLocation the type of location.state is unknown

### ISSUE THREAD

**Issue by larsenwork** [remix-run/react-router#8508]
### What version of React Router are you using?

Latest

### Steps to Reproduce

Open the stackblitz auth example: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src/App.tsx

### Expected Behavior

No type errors

### Actual Behavior

TS complains about `location.state` being unknown: 

![image](https://user-images.githubusercontent.com/3859425/146741537-5a40a467-5f8e-439d-b353-6b39a3b305d3.png)

I can see it's from this recent change: https://github.com/remix-run/history/commit/8117ab21f5e339fabaa6ed1d80290fe3cee40c27#diff-1caf4c08131a3efeb1e49c0ce896aa4a488a13b1b743613a99f4a5c5aff91d8fR55-R58 so I'm assuming we should do redirects in a different way now but I'm unsure how?

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8503#issuecomment-997543520
