### ISSUE TITLE
[Bug]: Layout routes does not work

### ISSUE THREAD

**Issue by sbayrak** [remix-run/react-router#8513]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

1. Go to App.js 
2. You will notice `<Route element={<Layout />}  <Route path='/' element={<Home /> </Route>` , Layout component is a _layout_ component but the browser just renders Layout component, not <Layout /> component along with <Home /> component.

### Expected Behavior

to render;

`<Layout>
      <Home />
</Layout>`

### Actual Behavior

instead, it just renders `<Layout />` component

you may refer to my github repo for this 
https://github.com/sbayrak/nasdaq-stock-exchange-charts-react

**Comment by liuhanqu** [comment]
can not reproduce.
I have clone your repo and it work correctly.

**Comment by sbayrak** [comment]
Yes because I have wrapped `Router` component with `<Layout />` . please try again with new pushed version

**Comment by liuhanqu** [comment]
```typescript
const Layout = () => {
    return (
        <div className="layout">
            <Outlet />
        </div>
    );
};
```

Use `Outlet` component.

**Comment by sbayrak** [comment]
It works now! thank you but I haven't seen that I need such a implementation in the documentation; 
[Layout Routes](https://reactrouter.com/docs/en/v6/getting-started/concepts#layout-routes)

**Comment by liuhanqu** [comment]
https://reactrouter.com/docs/en/v6/getting-started/concepts#outlets
