### ISSUE TITLE
[Bug]: <Route path="/"><Route path="*" /><Route /> doesn't match

### ISSUE THREAD

**Issue by AlishaHawkward** [remix-run/react-router#8517]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Case 1:
```
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route path="a" element={<Custom text="a" />}>
          <Route path="b" element={<Custom text="b" />} />
          <Route path="*" element={<Notfound />} />
        </Route>
        <Route path="*" element={<Notfound />} />
      </Route>
    </Routes>
```

Case 2:
```
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route path="a/*" element={<Custom text="a" />}>
          <Route path="b" element={<Custom text="b" />} />
          <Route path="*" element={<Notfound />} />
        </Route>
        <Route path="*" element={<Notfound />} />
      </Route>
    </Routes>
```

### Expected Behavior

Case 1 === Case 2

### Actual Behavior

Visit path `/a` it response:

Case 1:
```
Layout
a
```

Case 2:
```
Layout
a
NotFound
```

**Comment by Yegorich555** [comment]
Moreover NavLink returns `isActive: false` for child routes

**Comment by kmkhami** [comment]
I am also encountering this issue

**Comment by brophdawg11** [comment]
I'm going to close this out as expected, since splats change the behavior of the matching logic - and we specifically have tests that repeated splats should continue matching: https://github.com/remix-run/react-router/blob/1143652/packages/react-router/__tests__/path-matching-test.tsx#L234
