### ISSUE TITLE
[Bug]:  useLocation() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by liqueflies** [remix-run/react-router#8518]
### What version of React Router are you using?

6

### Steps to Reproduce

When I try to call the react hook useLocation inside <BrowserRouter></BrowserRouter> children that is not directly descendant of it it throws this error.

index.js
```
    <BrowserRouter>
      <App />
    </BrowserRouter>
```

App.js
```
<div className="App">
  <Header />
  <Routes> { /* routes */ } </Routes>
</div>
```

Header.js
```
const location = useLocation()
return <header><Logo /></header>
```

### Expected Behavior

I expect that can work also on not directly descendant children of the BrowserRouter

### Actual Behavior

It throws an error: Error: useLocation() may be used only in the context of a <Router> component.

**Comment by namiduru** [comment]
I was facing the same issue while writing the unit test and I came here and solved it by doing this on my unit test.
My problem was while rendering a component if you have useLocation hook inside a component, you need to make sure to wrap your component by Browser.

```
render(
      <BrowserRouter>
        <Routes>
          <Route path="*" element={<PlayScreen />}></Route>
        </Routes>
      </BrowserRouter>
    );
    const playScreen = screen.getByRole("play-screen");
    expect(playScreen).toBeInTheDocument();
```

**Comment by tito300** [comment]
I solved this issue by importing `useLocation` from `react-router-dom` instead of `react-router`.

**Comment by shilongjaycui** [comment]
> I was facing the same issue while writing the unit test and I came here and solved it by doing that on my unit test. My problem was while rendering a component if you have useLocation hook inside a component, you need to make sure to wrap your component by BrowserRouter.
> 
> ```
> render(
>       <BrowserRouter>
>         <Routes>
>           <Route path="*" element={<PlayScreen />}></Route>
>         </Routes>
>       </BrowserRouter>
>     );
>     const playScreen = screen.getByRole("play-screen");
>     expect(playScreen).toBeInTheDocument();
> ```

Thank you! This solved my problem.

**Comment by danno2000** [comment]
> importing

This solved my issue, importing from `react-router-dom` vs 'react-router`

**Comment by Nabeel-Mufin** [comment]
how to use useLocation with RouterProvider

**Comment by khedau1** [comment]
> how to use useLocation with RouterProvider

https://reactrouter.com/en/main/upgrading/v6-data#but-ive-got-stuff-between-browserrouter-and-routes
