### ISSUE TITLE
[Bug]: Mismatch of window.location values with react router's location values

### ISSUE THREAD

**Issue by ramagirish123** [remix-run/react-router#8519]
### What version of React Router are you using?

5.2.1

### steps to reproduce
Add the hash route programmatically using history.push({hash route}) and add query parameters to url using history.push(?{query params})

![image](https://user-images.githubusercontent.com/36559685/146972998-4bf027fe-6eb1-4f9e-8d9a-c398eb85e765.png)

![image](https://user-images.githubusercontent.com/36559685/146973160-0916bc5f-ce71-4684-8c8a-4a943fc5297b.png)
Actual Url is https://m365x997228.sharepoint.com/sites/collab_test_content_manager/sitepages/ideaapp.aspx#/view/Top%20Ideas?=&appFilter=%257B%2522SaketaIdeaStage%2522%253A%255B%2522Active%2522%255D%257D

### Expected Behavior

values in the browser location object should match with the values in react routers location object

### Actual Behavior

the hash, search, path are completely different between window.location and react router location

**Comment by timdorr** [comment]
If you're using a HashRouter, this is expected. The HashRouter is parsing the `hash` of `window.location` to support the history elements of something like BrowserRouter.
