### ISSUE TITLE
[Bug]: location.state - Object is of type 'unknown'

### ISSUE THREAD

**Issue by AdamMurray** [remix-run/react-router#8522]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

The [Authentication example](https://reactrouter.com/docs/en/v6/examples/auth) on the v6 docs site is incorrect.
For v6.0.2, the example code worked fine, but in v6.2.1 we get the following error:
![Screenshot 2021-12-21 at 21 03 35](https://user-images.githubusercontent.com/4741427/146997693-6d5bad75-69ad-45f0-a125-3302b5f5010e.png)

Go to the StackBlitz example [here](https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth?file=src%2FApp.tsx) and wait for the project to complete installation.

### Expected Behavior

`location.state` is not `unknown`.

### Actual Behavior

`location.state` is `unknown`.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8503#issuecomment-997543520
