### ISSUE TITLE
[Feature]: Add invariant if history is not passed to HistoryRouter

### ISSUE THREAD

**Issue by wojtekmaj** [remix-run/react-router#8523]
### What is the new or updated feature that you are suggesting?

Add invariant if history is not passed to HistoryRouter

### Why should this feature be included?

Currently, using HistoryRouter without passing `history` prop ends with `TypeError: cannot read property action of undefined`, which isn't very helpful and looks like an error on RR's side, when in reality it's dev's fault.

**Comment by acidcrash2005** [comment]
Have same problem!

**Comment by brophdawg11** [comment]
I'm not sure we want to get into the business of adding an `invariant` to every required component prop - you can prevent these issues with Typescript if prop validation is important for your app.
