### ISSUE TITLE
[Feature]: Add methods to access history stack in React Router 6

### ISSUE THREAD

**Issue by lynxtaa** [remix-run/react-router#8527]
### What is the new or updated feature that you are suggesting?

I think we should be able to access history stack in React Router 6

### Why should this feature be included?

With react-router@5 I'm rendering a `GoBackButton` like this:

```jsx
const history = useHistory()
return <Button onClick={history.goBack} disabled={history.length < 2}>Go Back</Button>
```

As far as I see there no way to access a history stack in react-router@6 to correctly disable this button. Is there an alternative way? Maybe I'm missing something?

**Comment by timdorr** [comment]
Use the HistoryRouter that was added with the unstable_ flag.

**Comment by vault-developer** [comment]
First of all thank you for a such great library.

Just bumped into the same problem and asking for your advice :) 
Is it safe to use 'unstable' version? Will it be stabilized in the future releases?
What is the best approach for long-term production code should I choose?
Thanks in advance.

**Comment by liuhanqu** [comment]
why not add `unstable_HistoryRouter` to doc @timdorr
