### ISSUE TITLE
[Bug]: can react support the keep-alive style for project？v5 plugins can't use in V6

### ISSUE THREAD

**Issue by xiezhiyi163** [remix-run/react-router#8528]
### What version of React Router are you using?

can react support the keep-alive style for project？v5 plugins can't use in V6

### Steps to Reproduce

can react support the keep-alive style for project？v5 plugins can't use in V6

### Expected Behavior

can react support the keep-alive style for project？v5 plugins can't use in V6

### Actual Behavior

can react support the keep-alive style for project？v5 plugins can't use in V6

**Comment by timdorr** [comment]
This has nothing to do with React Router.
