### ISSUE TITLE
[Bug]: [v6] <Route path="/" element={React.lazy(() => import('./examplePage'))}> does not work

### ISSUE THREAD

**Issue by kensukesaito** [remix-run/react-router#8546]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

https://codesandbox.io/s/recursing-mcclintock-fr1lm

### Expected Behavior

To be Worked this:
```typescript
<Route path="/" element={React.lazy(() => import('./examplePage'))} />
```

### Actual Behavior

Console error:

> Uncaught Error: Objects are not valid as a React child (found: object with keys {$$typeof, _payload, _init}). If you meant to render a collection of children, use an array instead.

**Comment by liuhanqu** [comment]
This is not the bug of `react-router`.

**Comment by timdorr** [comment]
You're not providing an element, you're providing a component. You need to create an element by creating a component instance.

```js
const Comp = React.lazy(() => import('./examplePage'))

<Route path="/" element={<Comp/>} />
```

**Comment by manojsethi** [comment]
This used to work fine with v5 Component. We are using a JSON for looping over the routes, so how do you suggest working around this?

Looking forward to your response.
