### ISSUE TITLE
[Feature]: useMatchedRoute()

### ISSUE THREAD

**Issue by jampy** [remix-run/react-router#8547]
### What is the new or updated feature that you are suggesting?

I would suggest adding a hook that basically does this:

```js
function useMatchedRoute() {

  const { matches } = useContext(RouteContext);

  const n = matches.length;

  if (!n)
    throw new Error("Apparently not below a <Route>");

  return matches[n - 1].pathnameBase;

}
```

So, a component below a `<Route>` could know the route `path` without it needing to be hardcoded.

Use case: You have an app that manages users. A specific user is displayed in `/users/123`. One can click on a button and show the users avatar in a popup which is displayed at `/users/123/avatar`. On the user page you want to display the user permalink.

AFAIK with current react-router API you would need to hardcode the path base `"/users/"` in `<Permalink>`.

```jsx
function Application() {

  return <Routes>
    <Route path='/users/:id' element=<UserPage/> />
  </Routes>;

}

function UserPage() {

  const { id } = useParams();

  return <div>
    <h1>This is user number {id}</h1>
    <Permalink/>
    <Routes>
      <Route path='avatar' element=<AvatarPopup userId={id} />>
    </Routes>
  <div>;

}

function Permalink() {
  const myPath = useMatchedRoute();
  return <div>Permalink: {myPath}</div>;
}

// ...whereas currently I need to do this AFAIK:
function Permalink_currentAPI() {
  const { id } = useParams();
  return <div>Permalink: /users/{id}</div>;
}


```

- `useMatch()` is useless because it requires a `pattern` parameter
- `useLocation()` can't be used because it would return the avatar URL when the popup is open, but the permalink should not contain the avatar URL
- `useParams()` gets close but only returns params, not the path name
- `useResolvedPath` didn't work for me either

If what I suggest can be done with current (safe) API, then please let me know, thanks.

### Why should this feature be included?

Well, I think it would be useful in some cases and easy to implement.

**Comment by liuhanqu** [comment]
#8477

**Comment by timdorr** [comment]
You want to use `useHref`: https://reactrouter.com/docs/en/v6/api#usehref

**Comment by jampy** [comment]
@liuhanqu 
>#8477
>You can use useOutlet to indicate there is a child route or not.

What do you mean? I don't need/want to indicate anything in the parent component (`<Application>` in the example),

---

@timdorr 
> You want to use `useHref`: https://reactrouter.com/docs/en/v6/api#usehref

Thanks four you reply, but either that's for a different problem or I fail to understand how it is supposed to be used.

[`useHref()`](https://reactrouter.com/docs/en/v6/api#usehref) expects a `to` parameter, but I rather need a *"where am I"* information (with just the path of the parent matched route).

When navigating to `/users/123/avatar` that would be just `/users/123` because that's the matched `<Route>` on `UserPage`.

With other words, `<Permalink>` would just display `<div>Permalink: /users/123</div>` without needing to know anything about the routes (hence no `to` parameter necessary or reasonable).

That's more **similar** to [`useLocation()`](https://reactrouter.com/docs/en/v6/api#uselocation) but not quite the same, because `useLocation()` would return `/users/123/avatar` and the `avatar` part is not part of the route path base.

My proposed hook does this. If this can be done with existing hooks, I would be happy to learn more about it.

**Comment by elijahrdorman** [comment]
This seems similar to an issue I'm having with some Ant Design stuff.

The project uses the Ant `<Menu>` and `<Menu.Item>` components.  You must provide the `<Menu>` component with the currently selected key. My keys are the sub-route fragments so the current match can be highlighted. 

I need to know which one is the current match so Ant can apply its several layers of styling. We're using `<NavLink>` as the content inside the `<Menu.Item>`, but this is a child and doesn't propagate up to the `<Menu>`. 

This seems like an incredibly common problem in navigation using URL fragments.

**Comment by teroko** [comment]
@jampy 
> [`useHref()`](https://reactrouter.com/docs/en/v6/api#usehref) expects a `to` parameter, but I rather need a _"where am I"_ information (with just the path of the parent matched route).
Try useHref(''), it should return the url where your component is in path.

**Comment by jampy** [comment]
> > [`useHref()`](https://reactrouter.com/docs/en/v6/api#usehref) expects a `to` parameter, but I rather need a _"where am I"_ information (with just the path of the parent matched route).
> 
> Try useHref(''), it should return the url where your component is in path.

Okay, thanks, this works indeed! :-)

However, is it by design, that it returns the leading `#` when using `<HashRouter>`?

See https://stackblitz.com/edit/github-p5zupx?file=src/main.tsx then navigate to`#/users/123/avatar`:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/820758/148110009-f2fb8baa-9161-4bbe-bbf1-a42842be1549.png">
