### ISSUE TITLE
[Bug]: Optional path parameter not working

### ISSUE THREAD

**Issue by themgoncalves** [remix-run/react-router#8554]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

```jsx
<Routes>
      <Route path="/:lang?" element={<App />} />
</Routes>
```

### Expected Behavior

Optional path to work and render target component.

Both paths should match.
```bash
/en
/
```

### Actual Behavior

Optional path not working, that was a breaking change on the v6.

The question mark `?` to mark an optional parameter breaks the framework.

**Comment by Haraldson** [comment]
This is not a bug, but a conscious decision; see #8381 and #8254.
