### ISSUE TITLE
[Bug]: [v6 Doc] How do I access the history object outside of components?

### ISSUE THREAD

**Issue by nulltoken** [remix-run/react-router#8556]
### What version of React Router are you using?

v6

### Steps to Reproduce

The [applicationinsights-react-js](https://www.npmjs.com/package/@microsoft/applicationinsights-react-js) npm package expects a `history` parameter.

The [documentation](https://github.com/microsoft/ApplicationInsights-JS/tree/master/extensions/applicationinsights-react-js#configuration) refers to the react-router [FAQ](https://github.com/remix-run/react-router/blob/main/FAQ.md#how-do-i-access-the-history-object-outside-of-components) which showcases the following:

![image](https://user-images.githubusercontent.com/92363/148065575-3c96ecae-4466-482a-9bab-c7634915b760.png)

This was working in v5. However, once migrated to v6, it looks like the `Router` component doesn't accept an `history` prop anymore.

Any chance this FAQ could be updated to explain how to achieve this in v6?

/cc @MSNev

### Expected Behavior

Maybe an updated FAQ describing how to access the history object outside of a component in v6?

### Actual Behavior

Current FAQ only explains how to achieve this in v5.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8264#issuecomment-991271554

**Comment by nulltoken** [comment]
@timdorr Thanks a lot for the pointer.
