### ISSUE TITLE
[Bug]: Quick Start Documentation (first link in google search) redirects to v5 docs

### ISSUE THREAD

**Issue by dosaki** [remix-run/react-router#8560]
### What version of React Router are you using?

V6

### Steps to Reproduce

Go to https://reactrouter.com/web/guides/quick-start

### Expected Behavior

Expect to be redirected to the latest version of Getting Started (i.e. v6): https://reactrouter.com/docs/en/v6/getting-started/tutorial

### Actual Behavior

Am redirected to v5's docs: https://v5.reactrouter.com/web/guides/quick-start

**Comment by timdorr** [comment]
That is intended. We don't want old blog posts or tweets based on v5 pointing to that URL to provide conflicting information. We're preventing link rot.

**Comment by nthitz** [comment]
Perhaps could add a large notice / warning to the v5 quickstart pointing to the upgraded version/docs?
