### ISSUE TITLE
Can useNavigate provide a configuration that can configure <a traget=''_blak"></a> tag attributes

### ISSUE THREAD

**Issue by lgf196** [remix-run/react-router#8562]
### What is the new or updated feature that you are suggesting?

Can useNavigate provide a configuration that can configure `<a traget=''_blak"></a>` tag attributes, I want to open a new window

### Why should this feature be included?

Can useNavigate provide a configuration that can configure `<a traget=''_blak"></a>` tag attributes, I want to open a new window

**Comment by timdorr** [comment]
NO, it cannot. useNavigate wraps around the History API, which doesn't provide this kind of functionality.
