### ISSUE TITLE
[Bug]: Link to the same route doesn't work. 

### ISSUE THREAD

**Issue by mhmdmu** [remix-run/react-router#8572]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Assume I have a component that displays a list of the tickets. 

And also I have a route to the Ticket component (Single Ticket Page) 

In the Tickets components, I click on a link of a ticket and it goes to the Ticket component (Single Ticket Page)

And now we're on the Single Ticket Page. It works fine till now.

But here in the SIngle Ticket Page, I have a sidebar with a list of other tickets which when I click on the sidebar links nothing will change and it is stuck on the same page.

Here are the routes

```
<Routes>
    <Route path="/" element={ <Tickets /> } />
    <Route path="ticket/:id" element={ <Ticket /> } />
</Routes>
```

Link example in both components

```
<Link to={ `/ticket/${ ticket.id }` }>
    <h4 className="ticket-title">
        { ticket.title.rendered }
    </h4>
</Link>
```

### Expected Behavior

It has to change the page content when I click on the other tickets link.
For instance, currently, I'm in the /ticket/55/ when I click on / ticket/70/ it should open up the ticket 70

### Actual Behavior

-

**Comment by timdorr** [comment]
This is just how React works. React Router is matching the same component, so React is doing what it's designed to do and keeping the same component instance in place. 

You need to use the hooks in a way that causes the component to update when they change. This is most likely making something like useParams a part of a useEffect dependency.
