### ISSUE TITLE
[Bug]: internal links isn't redirecting in the reactrouter website

### ISSUE THREAD

**Issue by od-c0d3r** [remix-run/react-router#8579]
### What version of React Router are you using?

6

### Steps to Reproduce

1. open `https://reactrouter.com`
2. press on any internal link like `Read the Docs` or anything related to the route `/docs`

### Expected Behavior

The link should redirect me to the desired destination 

### Actual Behavior

The `Link` is manipulating the browser URL, but doesn't redirect the page

**Comment by timdorr** [comment]
Doesn't happen with either Chrome or Firefox for me. It's probably a browser extension or something local to your system.

**Comment by od-c0d3r** [comment]
Thanks for your feedback @timdorr, I will check it out again.
