### ISSUE TITLE
[Bug]: Higher-Order Nesting doesn't work

### ISSUE THREAD

**Issue by elijahrdorman** [remix-run/react-router#8580]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Here's a trivially modified version of your default StackBlitz. All that I've done is move two routes to a fragment and move that fragment into a component (which may or may not be a HOC)

```Typescript
const Nested = () => (
  <>
    <Route path="about" element={<About />} />
    <Route path="dashboard" element={<Dashboard />} />
  </>
)

export default function App() {
  return (
    <div>
      <h1>Basic Example</h1>

      <p>
        This example demonstrates some of the core features of React Router
        including nested <code>&lt;Route&gt;</code>s,{" "}
        <code>&lt;Outlet&gt;</code>s, <code>&lt;Link&gt;</code>s, and using a
        "*" route (aka "splat route") to render a "not found" page when someone
        visits an unrecognized URL.
      </p>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<Home />} />
          <Nested />
          <Route path="*" element={<NoMatch />} />
        </Route>
      </Routes>
    </div>
  );
}
```

### Expected Behavior

Detect that the actual return value is a fragment with only `<Route>` children.

### Actual Behavior

Blows up because it does a direct check on the child to see if the type is a `React.Fragment` or `Route`

**Comment by timdorr** [comment]
This isn't a bug. `Routes` only allows `Route` components as its direct children. You cannot wrap them in other components.

**Comment by elijahrdorman** [comment]
Feature perhaps? Without this, it is a leaky abstraction.

**Comment by andrewplummer** [comment]
Those are big words 😉 

But indeed this was always a problem with react-router, ie. why do router components not behave like normal React components? It seems unlikely they'll be willing (or able) to change it at this point though...

**Comment by mahnunchik** [comment]
@timdorr do I understand correctly that it is impossible to implement the following logic in current router design:

```js
import { Route as ReactRoute } from 'react-router-dom';
import { RequireAuth } from '../contexts/AuthContext';


export default function Route(props) {
  if (props.auth === true) {
    return (
      <ReactRoute path={props.path} element={<RequireAuth>{ props.element }</RequireAuth>}></ReactRoute>
    );
  } else {
    return (
      <ReactRoute path={props.path} element={ props.element }></ReactRoute>
    );
  }
}

```

**Comment by timdorr** [comment]
Correct, as `Routes` only accepts `Route`s for its children. It's not the name, but the actual component instance that is accepted. 

You can do this pattern, however:

```js
<Routes>
  <Route path="/" element={<PublicPage />} />
  <Route path="/login" element={<LoginPage />} />
  <Route element={<RequireAuth/>}>
    <Route path="/protected" element={<ProtectedPage />} />
  </Route>
</Routes>
```

Wrapping in a layout route also can achieve the same thing without boilerplate.

**Comment by GideonMax** [comment]
while you cannot have a nested component which is invoked as a jsx element (i.e. <Nested/>), you can call it as a function, since it doesn't use any hooks (i.e. {Nested()}).
I would just recommend using the new data routers
