### ISSUE TITLE
[Feature]: Include the error message for Route invariant also on production build

### ISSUE THREAD

**Issue by danielo515** [remix-run/react-router#8585]
### What is the new or updated feature that you are suggesting?

Hello. I am a bit tired of several hours of troubleshooting this. I was getting a blank error on my production bundle and it was being very daunting. Only happened on production because it was rendering a route conditionally in case the user was not logged in, so never happened on local.

I don't understand why the invariant is ommiting the error message on production builds, it is a very small addition and will save a lot of frustration.
This is how it looks right now:

```
function Route(_props) {
   process.env.NODE_ENV !== "production" ? invariant(false, "A <Route> is only ever to be used as the child of <Routes> element, " + "never rendered directly. Please wrap your <Route> in a <Routes>.") : invariant(false) ;
}
```

Can't it just be added the error in any case?

### Why should this feature be included?

The gains of not including this on production are ridiculous versus the pain it can cause trying to debug an empty error.

**Comment by timdorr** [comment]
We specifically strip most warnings from the production builds to save on file size and also because they are not relevant to users of your application. You should be catching these error messages in development and in your tests.

**Comment by danielo515** [comment]
> We specifically strip most warnings from the production builds to save on file size and also because they are not relevant to users of your application. You should be catching these error messages in development and in your tests.

This is not a warning, this is throwing an error.
There is also no documentation nor any indication that such component will break your app without even providing an error message.
Users of my application will be presented with a white screen, so being able to at least report the console error will be relevant.
