### ISSUE TITLE
[Feature]: API Documentation for v6

### ISSUE THREAD

**Issue by DukePuddingtonV** [remix-run/react-router#8586]
### What is the new or updated feature that you are suggesting?

Hi there, I'm looking to upgrade to v6, but not finding lower-level API documentation.  I'm looking for the API docs akin to something like version 5's: https://v5.reactrouter.com/web/api/Route. I realize this isn't a bug, but I don't feel like this should fall on the StackOverflow or Google community to be answered via the "support" link option.

Am I missing the new API doc location, or did we just replace that with "examples" and "migration" tutorials? I'd love to have some deeper guidance on these components given the breaking changes between 5 and 6. My understanding is that version 6 not in beta, right? 

Apologies in advance if this has been answered here before. Thanks in advance for the guidance!

### Why should this feature be included?

As a developer I'd like to not guess or infer usage of the framework I'm using.

**Comment by timdorr** [comment]
It's under API Reference near the top of the left menu: https://reactrouter.com/docs/en/v6/api
