### ISSUE TITLE
[Bug]: deleting search params in parallel

### ISSUE THREAD

**Issue by mrlubos** [remix-run/react-router#8587]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

See [CodeSandbox](https://codesandbox.io/s/react-router-v6-extending-search-params-instead-of-replacing-it-forked-rpiit?file=/src/App.tsx), press the "clear (broken)" button.

1. Have a custom hook with method that clears a specific search param when called
2. Import multiple instances of the same hook
3. Execute both clear methods

### Expected Behavior

Both "a" and "b" search params get cleared

### Actual Behavior

Only the second search param gets cleared ("b" in my example).

My guess is this happens because useSearchParams/searchParams holds reference to the old state, disregarding the call that cleared the "a" param from the URL. If I call the same method twice with different values, this works as expected (press the "clear (OK)" button). However, I cannot be expected to pass the searchParams instance throughout the application, that's what hooks are for. So If multiple components call the same method simultaneously, weird things can ensue.

Am I using this hook incorrectly or is this a bug? Thanks!

**Comment by timdorr** [comment]
This isn't really a bug. You're using two instances of the useSearchParams hook (`clearA` and `clearB`), so they aren't referring to the same internal instances of `navigate` and some other things. 

You should use one instance of the useSearchParams hook and do all of your manipulation of the `searchParams` before calling `setSearchParams` to avoid any overwriting or conflicts.

BTW, you can notice a subtle bug on your "OK" case if you hit the back button. Each deletion is a separate navigation, so you have to hit back twice to get to the original URL.

**Comment by mrlubos** [comment]
> This isn't really a bug. You're using two instances of the useSearchParams hook (`clearA` and `clearB`), so they aren't referring to the same internal instances of `navigate` and some other things.
> 
> You should use one instance of the useSearchParams hook and do all of your manipulation of the `searchParams` before calling `setSearchParams` to avoid any overwriting or conflicts.
> 
> BTW, you can notice a subtle bug on your "OK" case if you hit the back button. Each deletion is a separate navigation, so you have to hit back twice to get to the original URL.

Hi @timdorr, thank you for the reply! What's the reason for not using one instance of `navigate`? I now understand how this issue happens, just find it interesting I need to share `searchParams` between components that might be in very different places in the application. Ideally, there would be a way to force reusing a single instance of `navigate`. What side effects could that produce (why is this not a good idea)?

**Comment by timdorr** [comment]
Each hook has no way of communicating between each other. They are just plain function calls and don't consult some sort of global state.  We can't re-use the navigate instance from `useNavigate` because it's being called twice and that's just how React's core hooks work (which are what provides the core instances these hooks use)
