### ISSUE TITLE
[Feature]: backwards compatibility package link

### ISSUE THREAD

**Issue by abernier** [remix-run/react-router#8597]
### What is the new or updated feature that you are suggesting?

In the migration guide from v5 to v6, we can find [this red WARNING](https://reactrouter.com/docs/en/v6/upgrading/v5#:~:text=We%20recommend%20waiting%20for%20the%20backwards%20compatibility%20package%20to%20be%20released%20before%20upgrading%20apps%20that%20have%20more%20than%20a%20few%20routes.):

> We recommend waiting for the backwards compatibility package to be released before upgrading apps that have more than a few routes.

Is there an issue/PR opened for it ?

### Why should this feature be included?

I think you could add a link to the documentation to that "backwards compatibility package" PR in order we can follow its ETA.

**Comment by timdorr** [comment]
No, we don't have an open issue for it. But you can see the work so far in the compat branch: https://github.com/remix-run/react-router/tree/compat

**Comment by abernier** [comment]
Thank you for the branch link.

I think it could help other devs to put that branch link into the doc, in
the migrating section where you talk about the upcoming compatibility
package:
https://reactrouter.com/docs/en/v6/upgrading/v5#:~:text=We%20recommend%20waiting%20for%20the%20backwards%20compatibility%20package%20to%20be%20released%20before%20upgrading%20apps%20that%20have%20more%20than%20a%20few%20routes
.

Thank you for the great work

**Comment by derekju** [comment]
Is there any update on how progress on the compatibility layer is going?
