### ISSUE TITLE
[Feature]: Export history object to avoid the possibility of having two versions of 'history' when using HistoryRouter

### ISSUE THREAD

**Issue by weilandia** [remix-run/react-router#8598]
### What is the new or updated feature that you are suggesting?

[This](https://github.com/remix-run/react-router/blob/9cc42139acd0317a5bfc8ad7aa2dd8e6d573505a/packages/react-router-dom/index.tsx#L205) comment in `packages/react-router-dom/index.tsx` warns that using `HistoryRouter` is discouraged because it could lead to multiple versions of `history` being used. Could `packages/react-router-dom/index.tsx` just export a history object that could then be imported for folks using `HistoryRouter` instead of importing it directly from `history`?

### Why should this feature be included?

Using HistoryRouter is necessary for legacy redux apps that use history to navigate in actions.

**Comment by timdorr** [comment]
The history instances used by the various Router types is created when they are rendered. We can't export it because it's not a static instance.
