### ISSUE TITLE
Link: Make `active` class configurable

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#86]
`Link.activeClassName = "somethingElse"`

and

`<Link activeClassName="somethingElse"/>`

**Comment by christianv** [comment]
@mjackson @ryanflorence It looks like `transferPropsTo ` has been removed from React, any suggestions on how to do this in a different way?

Found some good docs at https://gist.github.com/sebmarkbage/a6e220b7097eb3c79ab7 but wasn't able to make the example (overwriting `activeClassName` for `CustomLink`) work yet.

**Comment by spicyj** [comment]
This is equivalent to what mjackson said:```
var CustomLink = React.createClass({
  getDefaultProps: function () {
    return { activeClassName: 'custom-active-classname' };
  },
  render: function () {
    return <Link {...this.props}>{this.props.children}</Link>;
  }
});
```

**Comment by christianv** [comment]
@spicyj Thanks, that works beautifully!
