### ISSUE TITLE
[Bug]: Navigate(0) won't work on Safari

### ISSUE THREAD

**Issue by wlcharlie** [remix-run/react-router#8600]
### What version of React Router are you using?

v6

### Steps to Reproduce

```
const Navigate = useNavigate()

<IconButton onClick={() => Navigate(0)}>
  <RefreshIcon />
</IconButton>
```

### Expected Behavior

I was trying to refresh by clicking a button with useNavigate and it worked on my laptop (chrome).
Hoping it will also work on iPad (safari, chrome).

### Actual Behavior

The refresh won't work on iPad (safari, chrome)

**Comment by tzikheng** [comment]
Hello @wlcharlie 

This seems to be working for me on the (simulator) iPad's I've tested.

Which iOS/safari version is your iPad using, and are you able to provide a minimal working repo of your project?

**Comment by mesopa** [comment]
Same problem here, IOS 12.5.5 Safari does not reload, navigate(0) is ignored.

**Comment by jiteshgolecha** [comment]
+1 Does not work on iOS (Cordova)

**Comment by dreadwood** [comment]
The problem is still relevant
