### ISSUE TITLE
[Bug]: useResolvedPath is causing 'Rendered more hooks than during the previous render.' if number of rendered links change

### ISSUE THREAD

**Issue by JohnMarsden24** [remix-run/react-router#8603]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Create a list of `<Link />` to loop through and create a button to toggle the amount of links. Inside the `<Link />` component use the `useResolvedPath` hook.

[Stackblitz example here](https://stackblitz.com/edit/github-5kdbjy-wxdtk5?file=src%2FApp.jsx) 

### Expected Behavior

Toggling between the number of `<Link />` rendered which use the `useResolvedPath` should not crash

### Actual Behavior

When you change the number of `<Link />` rendered you'll get the `"Rendered more hooks than during the previous render."` error.

**Comment by timdorr** [comment]
Your code is incorrect. It's rendering out the raw component functions, not element instances of that component: 
```jsx
<ul>{navLinks.map(MyLink)}</ul>
// should be:
<ul>{navLinks.map(link => <MyLink {...link} />)}</ul>
```
