### ISSUE TITLE
[Feature]: path prop should has opportunity get array of strings, but not only string

### ISSUE THREAD

**Issue by xCTAPx** [remix-run/react-router#8609]
### What is the new or updated feature that you are suggesting?

This feature was in v5 of library and it was very useful, but removing this good feature stop me from migration to 6th version

### Why should this feature be included?

I wanna have opportunity set some routes for one Route component

**Comment by timdorr** [comment]
This was a side effect of us using the `path-to-regexp` library in v5, which we no longer use in v6. It's not something we're looking at supporting, because it would prevent nested routing and some of the hooks from functioning correctly.
