### ISSUE TITLE
[Feature]: Redirect component

### ISSUE THREAD

**Issue by xCTAPx** [remix-run/react-router#8610]
### What is the new or updated feature that you are suggesting?

Redirect has been removed in v6, but it was very convenient use it for redirects and different kinds of private routes

### Why should this feature be included?

This component (Redirect) has been removed in 6th version but was very useful for my current project. Without it I can't implement custom logic with permissions and private routes and I didn't understand why this feature was deleted.

**Comment by MoNSTRiKcom** [comment]
```jsx
import { BrowserRouter, Navigate, Routes, Route, Link  } from "react-router-dom";

<Route path="/" element={<Navigate to="/sheduler" />} />
<Route path="/sheduler" element={<Sheduler />} />
```

**Comment by timdorr** [comment]
Please read the migration docs: https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-usehistory
