### ISSUE TITLE
[Bug]: Cannot resolve symbol 'useNavigate' on WebStorm 2021.3.1

### ISSUE THREAD

**Issue by DYW972** [remix-run/react-router#8616]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

import { useNavigate } from 'react-router-dom'

### Expected Behavior

I expect that importing `useNavigate` not turning into a warning.

### Actual Behavior

WebStorm is warning `useNavigate` in the import with this message  : ` Cannot resolve symbol 'useNavigate'`

**Comment by timdorr** [comment]
This isn't a React Router bug.

**Comment by DYW972** [comment]
@timdorr Thanks for your answer but can you provide more information?
