### ISSUE TITLE
[v6][Feature]: Notification of navigation before render

### ISSUE THREAD

**Issue by RandScullard** [remix-run/react-router#8617]
### What is the new or updated feature that you are suggesting?

I suggest that react-router expose a way for applications to get a notification on every navigation before rendering occurs.

**Context:**

I have implemented a simple mechanism to save and restore scroll position in my SPA, which uses react-router v6. When the user returns to a page via the browser's back/forward button, I am restoring that page to the scroll position it had before they navigated away. To make this work, I need to save the scroll position whenever navigation occurs but **before** the destination page is rendered. (It must be before rendering because the destination page could be much shorter in height than the source page. In this case rendering the destination page will instantly cause the browser to scroll and thus lose the original scroll position. This means that `useEffect` runs too late for this purpose.)

I have been able to get this working by doing the following in my app's render function:

    const prevLocationKey = useRef("")
    const location = useLocation()

    if ((location.key !== prevLocationKey.current) && (prevLocationKey.current !== ""))
        saveScrollPos(prevLocationKey.current, window.scrollY)

    prevLocationKey.current = location.key

This is working in my app, but I know it is not a good practice to have side effects in a render function. It would be better if react-router exposed some officially-supported navigation event that I can hook into to call my `saveScrollPos` function.

### Why should this feature be included?

I agree with the documentation [here](https://v5.reactrouter.com/web/guides/scroll-restoration) that it would be problematic for react-router to implement a generic solution for scroll restoration. However, by adding this suggested feature, react-router would enable apps to implement scroll restoration according to their own specific requirements, and in a way that complies with React best practices.

**Comment by timdorr** [comment]
You can do this now with `HistoryRouter`. Just `listen` to your history instance before passing it into HistoryRouter's props. The listener will be called first, before React even knows about it.

**Comment by RandScullard** [comment]
@timdorr Two things concern me about this idea:

1. HistoryRouter doesn't seem to be documented.
2. This comment appears in the code for HistoryRouter (my italics):

> A `<Router>` that accepts a pre-instantiated history object. It's important
> to note that _using your own history object is highly discouraged_ and may add
> two versions of the history library to your bundles unless you use the same
> version of the history library that React Router uses internally.

So is it really a good idea to rely on HistoryRouter?

**Comment by timdorr** [comment]
Yes, it's quite fine. In fact, the trick you can do to alleviate some of those concerns is not even put `history` as a dependency in your project. It will come in via `react-router`, so you'll be getting the exact same version it uses internally.

The messaging there is really just to head off any potential bug reports before they're filed.

**Comment by RandScullard** [comment]
@timdorr Oh man, I have to import it as `unstable_HistoryRouter`. That really does not make me feel good about using this... What is the plan for the future of this class? Is it going to be fully documented and supported or am I going out on a limb here?
