### ISSUE TITLE
[Feature]: Is it possible for v3 to support React 17?

### ISSUE THREAD

**Issue by varunarora** [remix-run/react-router#8620]
### What is the new or updated feature that you are suggesting?

I am using v3.2.6 and want to upgrade to React v17.0.1. Is there a plan to support version 17? The problem that I am having is these warnings:

![image](https://user-images.githubusercontent.com/629203/151098965-544835d8-c496-4e13-8dd7-d973a32e8e39.png)

This seems like it is related to not testing on React 17. `prop-types` was removed earlier, so I think the complex stuff is already taken of.

### Why should this feature be included?

I believe that React 17 and React 16 are very similar, so I imagine that there is not huge of work needed to get there. Apps like ours need to do a lot work to move from v3 to v4, so if this can be supported, it would be very helpful!

**Comment by varunarora** [comment]
Actually, downgrading to v16.14.0, and same problem persists.

**Comment by timdorr** [comment]
Unfortunately, we're not really working on supporting v3 anymore. If you want to make a PR to fix this, we can see about getting it merged in and released, but it's not something we're working on ourselves.
