### ISSUE TITLE
[Bug]: [v5]useLocation returns different data structure

### ISSUE THREAD

**Issue by kingller** [remix-run/react-router#8626]
### What version of React Router are you using?

5.2.1

### Steps to Reproduce

react-router: 5.2.1
react-router-dom: 5.3.0
history: 5.2.0

```
<Router history={history}>
    <MainWithRouter />
</Router>
````

```
let location = useLocation();
console.log('location', JSON.stringify(location));
```

When open the website for the first time, the value of location is `{"pathname":"/components/button/button","search":"","hash":"","state":null,"key":"default"}` 
and jump to another page with history.push, then its value is changed to 
```
{"action":"PUSH","location":{"pathname":"/components/button/button-group","search":"","hash":"","state":null,"key":"7feqomqt"}}
```

### Expected Behavior

Keep the data structure unchanged whenever I use it.

When I want to fetch the pathname, I can fetch the value by location.pathname any time.

### Actual Behavior

When I want to fetch the pathname, I can fetch the value by location.pathname first time, but I must fetch the value by location.location.pathname second time.

**Comment by timdorr** [comment]
You can't use history v5 with React Router v5. Use v4 of history.

**Comment by kingller** [comment]
Thanks. But how to use history v5 with react-router v6?
