### ISSUE TITLE
[Feature]: [v6] useBlock() or useHistory() for blocking transition

### ISSUE THREAD

**Issue by suppayami** [remix-run/react-router#8627]
### What is the new or updated feature that you are suggesting?

Includes either `useBlock()` or `useHistory()` explicitly for blocking transition. To do this now, we have to use HistoryRouter which is unstable.

### Why should this feature be included?

Blocking transition is pretty important for many web apps.

**Comment by timdorr** [comment]
Duplicate of #8139
