### ISSUE TITLE
Did V6 give up support for class component? All the methods provided are hooks

### ISSUE THREAD

**Issue by Junfeizhao** [remix-run/react-router#8628]
### What version of React Router are you using?

Did V6 give up support for class component? All the methods provided are hooks

### Steps to Reproduce

Did V6 give up support for class component? All the methods provided are hooks

### Expected Behavior

Did V6 give up support for class component? All the methods provided are hooks

### Actual Behavior

Did V6 give up support for class component? All the methods provided are hooks

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8146#issuecomment-947860640
