### ISSUE TITLE
[Bug]: Cannot remove a search param from URL using the `useSearchParams` hook.

### ISSUE THREAD

**Issue by mattkauffman23** [remix-run/react-router#8629]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

1. Add a search param to the URL using the `setSearchParams` function provided by `useSearchParams` hook.
2. Attempt to remove the param name from the URL using the provided API.
3. Observe that params once present in the URL may not be removed.

### Expected Behavior

Calling `setSearchParams({ foo: undefined })` would remove the `foo` param from the URL if it was present.

### Actual Behavior

Added `foo=undefined` to the URL.

**Comment by timdorr** [comment]
You're still creating an object with the `foo` key in this case, which must be represented in the URL in some form. If you want to remove that key, just remove it from the params object: `setSearchParams({})`

**Comment by mattkauffman23** [comment]
Ok, sorry about that. I misunderstood the API. My incorrect assumption was that `setSearchParams` mutated the existing params instead of replacing.

**Comment by m-hatch** [comment]
The way you can accomplish this using the API is:
```
const [searchParams, setSearchParams] = useSearchParams();
...
searchParams.delete('foo');  // delete foo on searchParams object
setSearchParams(searchParams);  // reset URL searchParams to object with foo removed
