### ISSUE TITLE
[Bug]: App is not working when importing BrowserRouter

### ISSUE THREAD

**Issue by JulSeb42** [remix-run/react-router#8640]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Create a new react app with `create-react-app`

Import BrowserRouter in `index.js`

### Expected Behavior

Enable routing

### Actual Behavior

I'm getting this error when I import the `BrowserRouter` component, even before using it in the return function

```
Compiled with problems:

ERROR in ./node_modules/history/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
```

This is my `index.js` code:

```
import React from "react"
import ReactDOM from "react-dom"
import App from "./App"
import { BrowserRouter } from "react-router-dom"

ReactDOM.render(
    <App />,
    document.getElementById("root")
)
```

**Comment by Youngbae-Jeon** [comment]
I've got same error.

In my project, I'm using react-router-dom@6.2.1 and it worked well.
But today, I've got the error during my docker build.

In fact, local computer build worked successfully.
But I deleted package-lock.json and node_modules
and reinstall packages by "npm install"
and then build failed with the error

I think some dependency of react-router-dom has been updated and it makes the error.
The following is my error stack
```
ERROR in ./node_modules/history/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /home/whale/shintsmrp/sales/client/node_modules/history/index.js: Cannot read properties of undefined (reading 'originalPositionFor')
    at SourceMapTree.originalPositionFor (/home/whale/shintsmrp/sales/client/node_modules/@ampproject/remapping/dist/remapping.umd.js:159:27)
    at trace (/home/whale/shintsmrp/sales/client/node_modules/@ampproject/remapping/dist/remapping.umd.js:102:37)
    at EncodedSourceMapImpl.map (/home/whale/shintsmrp/sales/client/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:347:36)
    at TraceMap.map (/home/whale/shintsmrp/sales/client/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:430:31)
    at SourceMapTree.traceMappings (/home/whale/shintsmrp/sales/client/node_modules/@ampproject/remapping/dist/remapping.umd.js:85:34)
    at remapping (/home/whale/shintsmrp/sales/client/node_modules/@ampproject/remapping/dist/remapping.umd.js:258:36)
    at mergeSourceMap (/home/whale/shintsmrp/sales/client/node_modules/@babel/core/lib/transformation/file/merge-map.js:19:30)
    at generateCode (/home/whale/shintsmrp/sales/client/node_modules/@babel/core/lib/transformation/file/generate.js:72:39)
    at run (/home/whale/shintsmrp/sales/client/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)
 @ ./node_modules/react-router-dom/index.js 12:0-78 84:25-45 118:25-42 306:37-47 306:62-72
 @ ./src/index.tsx 11:0-49 16:33-46
```

**Comment by cheddarwhizzy** [comment]
Hit the same issue. The following fixed my setup. Reverted a release in @babel/core
```
npm i @babel/core@7.16.12
```

**Comment by VictorLi2** [comment]
Yes, looks like there was an update 3 hours ago that caused the issue. Downgrading the version directly in the package.json works

```json
  "devDependencies": {
    "@babel/core": "7.16.12"
  }
```

https://www.npmjs.com/package/@babel/core

**Comment by freaksauce** [comment]
> 

I tried downgrading @babel/core, nuked my node_modules and reinstalled but I still get the same error, I checked the node_modules and it did say `7.16.12` as I had set.

**Comment by Metroxe** [comment]
> > Yes, looks like there was an update 3 hours ago that caused the issue. Downgrading the version directly in the package.json works
> > ```json
> >   "devDependencies": {
> >     "@babel/core": "7.16.12"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://www.npmjs.com/package/@babel/core
> 
> I tried downgrading @babel/core, nuked my node_modules and reinstalled but I still get the same error, I checked the node_modules and it did say `7.16.12` as I had set.

Try the following...
1. make sure to remove the `^` from `7.16.12` in the `package.json`
2. remove the node_modules
3. remove the `package-lock.json`
4. run `npm install`

After that, try running. If you are using `yarn`, its also possible there is local caching, so use `npm` instead.

**Comment by iamyohann** [comment]
can confirm `@babel/core@7.16.12` fixes the issue for now...

**Comment by shtbik** [comment]
https://github.com/babel/babel/issues/14229

**Comment by nicolo-ribaudo** [comment]
This was a bug in a new Babel dependency, it has been fixed now (make sure to update `@jridgewell/trace-mapping` in your lockfile).
