### ISSUE TITLE
[Bug]: Peer dependency breaking npm install for react@17 and react@18

### ISSUE THREAD

**Issue by grzegorzjudas** [remix-run/react-router#8641]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

1. Create a simple react app using react (version 17 or 18.0.0-rc.0)
2. Run `npm install --save react-router-dom

### Expected Behavior

`react-router-dom` is installed and added to package.json

### Actual Behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@1.0.0
npm ERR! Found: react@18.0.0-rc.0-next-fe905f152-20220107
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0-rc.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.8" from react-router-dom@6.2.1
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by grzegorzjudas** [comment]
Caused by outdated peer dependency in `packages/react-router-dom/package.json`. Also, happens only when using npm 7, which tries to install peer dependencies by default, unless using `--legacy-peer-deps` flag (which by the way is workaround for this bug).

**Comment by timdorr** [comment]
This isn't a bug with React Router.

**Comment by grzegorzjudas** [comment]
@timdorr can you elaborate? From what I can see, the package.json that defines old react as peer dependency is in this repo.

**Comment by nbkhope** [comment]
I'm having the same problem. How did you fix it, @grzegorzjudas ?
