### ISSUE TITLE
[Bug]: No way to access previous route?

### ISSUE THREAD

**Issue by asjustis** [remix-run/react-router#8643]
### What version of React Router are you using?

Latest, whatever

### Steps to Reproduce

...

### Expected Behavior

Since we can navigate to other pages, we should be able to access which page we are coming from. How is there no way to access last/previous route anywhere in the plugin?

### Actual Behavior

Only navigate navigate navigate, but no history at all.

**Comment by timdorr** [comment]
Correct, we don't intend there to be access to the previous location. If you need it, use a ref and `useLocation`.

**Comment by rubenyeghikyan-highway** [comment]
I struggle with the exact same problem, I want to see history object, and pick one from it, I can't use navigate(-1/-2...)

**Comment by bel0v** [comment]
same here, I need to access history to check what the latest entry is
