### ISSUE TITLE
[Feature]: Allow URLs to be skipped from react-router and passed to server (2)

### ISSUE THREAD

**Issue by OnkelTem** [remix-run/react-router#8649]
### What version of React Router are you using?

React Router: 5.2.0
Chrome: 98.0.4758.74

### Steps to Reproduce

This is just a follow-up to https://github.com/remix-run/react-router/issues/3109
(I would have definitely commented there if the thread hadn't been locked)

For some reason `target="_self"` doesn't make any difference (anymore?) and the only way to short circuit the routing is to open the link in a new page e.g.:

```ts
function myPassthrouhLink() {
  return <RouterLink target="_blank" to="/api.html">{t`Show API Docs`}</RouterLink>
}
```

### Expected Behavior

I would expect to have a way to skip routing and instead just make a request to the server.

### Actual Behavior

It gets into the router and I cannot fetch a page from the server.

**Comment by timdorr** [comment]
Just use a normal `<a>` element.
