### ISSUE TITLE
[Bug]: useParams

### ISSUE THREAD

**Issue by ameralshabebi** [remix-run/react-router#8652]
### What version of React Router are you using?

v6

### Steps to Reproduce

So I faced this issue where if I try to grab values form nested route in the component it self not as child it will not work
as an example check the below
in the Component.js : 
 ```
 <h1>page</h1>
        <Routes>
        <Route path=":statId" element={...}/>
         </Routes>
        </>
```

in the app.js : 
 `    <Route path="/component/*" element={<Component/>}/>`

by the above way I will not access to the params but if change the nested route to children it will work and I can't grab the param.

### Expected Behavior

get access to the params 

### Actual Behavior

not reachable

**Comment by timdorr** [comment]
This is something we specifically test against: https://github.com/remix-run/react-router/blob/main/packages/react-router/__tests__/descendant-routes-params-test.tsx

Check your route paths, as they're not being set up correctly if this is happening.
