### ISSUE TITLE
[Bug]: Weird positioning bug after adding extra route

### ISSUE THREAD

**Issue by adrianbartyczak** [remix-run/react-router#8660]
### What version of React Router are you using?

17.0.2

### Steps to Reproduce

Create a React app with react-router-dom and add two routes.

### Expected Behavior

The component should be aligned based on the specified styles (currently doesn't do anything when you adjust the style).

### Actual Behavior

The component moves to the left off the browser when you add a second component.

![screenshot](https://user-images.githubusercontent.com/26193935/153919638-a56503f4-c802-481d-885d-06e61d80bab7.png)

**Comment by timdorr** [comment]
This isn't a React Router bug.
