### ISSUE TITLE
[Bug]: HashRouter not working in BrowserRouter for v6

### ISSUE THREAD

**Issue by paul-mesnilgrente** [remix-run/react-router#8664]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Here's the working code in the version 5.2.1 of react-router: https://codepen.io/DoctorRobot/pen/WNXXqbE. See that I have a working HashRouter inside a BrowserRouter. 

When I try to upgrade this code in v6.2.1: https://codepen.io/DoctorRobot/pen/GROObMr. The error which is given to me:

> Error: You cannot render a `<Router>` inside another `<Router>`. You should never have more than one in your app.

### Expected Behavior

I know that v6 isn't supposed to be backward compatible. But as this is not mentioned in the docs, it could  be treated as a bug? Or maybe I didn't see it in the docs :/ 

I also wonder if there's any chances to get the same behavior as before in v6. ie: in the URL `/a#/sub`, `/a` is treated by BrowserRouter and `/sub` is treated by the HashRouter

### Actual Behavior

Error given:

> Error: You cannot render a `<Router>` inside another `<Router>`. You should never have more than one in your app.

**Comment by timdorr** [comment]
Particularly because of the way nested routes work, this is no longer possible. If you want to submit a PR to add something to the docs, we can look at adding it. But the old behavior won't be returning.

**Comment by ElaineDelgado** [comment]
I have same error here, the docs should be updated.
