### ISSUE TITLE
[Bug]: Nested Routes cannot be reached

### ISSUE THREAD

**Issue by kpkonghk01** [remix-run/react-router#8670]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Example:
https://stackblitz.com/edit/github-fde24r?file=src/App.tsx
adjusted from
https://stackblitz.com/github/remix-run/react-router/tree/main/examples/basic?file=src/App.tsx

### 1. Create a Browser Router with a nested route, where includes and is another React Component that has its own routes.

```jsx
import * as React from 'react';
import { Routes, Route, Outlet, Link } from 'react-router-dom';

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route path="nested" element={<NestedRoute />} />
      </Route>
    </Routes>
  );
}

function NestedRoute() {
  return (
    <Routes>
      <Route element={<Layout />}>
        {/* this works */}
        <Route index element={<Nested />} />
        {/* this not work, even with path="*" */}
        <Route path="something" element={<Something />} />
      </Route>
    </Routes>
  );
}
```

### 2. Try these cases:
1. /nested
2. /nested/something

### Expected Behavior

both two nested routes should work

### Actual Behavior

1 works while 2 can't be reached

**Comment by kpkonghk01** [comment]
Actually it is #8648, but it was closed without any follow up

**Comment by timdorr** [comment]
Your `nested` is matching _only_ the `nested` URL segment. You need a wildcard to match additional segments: `<Route path="nested/*" element={<NestedRoute />} />`
