### ISSUE TITLE
[v6][Feature]: Provide a way to access the internal `history` instance

### ISSUE THREAD

**Issue by WoodyWoodsta** [remix-run/react-router#8671]
### What is the new or updated feature that you are suggesting?

If it is [discouraged](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L205-L210) to use our own instance of `history`, then provide a way for us to access your internal instance.

### Why should this feature be included?

Use cases of the `history` API go way beyond the repackaged `navigate` method, and `location` hook. If it is discouraged to use the only possible way for us to implement these use cases, then there should be an escape hatch for this which does not require us to hardwire package tooling to ensure that the same instance is used externally and internally.

If re-enabling the `useHistory` hook muddies the validity of the new `useNavigate` hook, then this is indicative of a flaw in either the API design or the responsibilities of the router as a package.

**Comment by timdorr** [comment]
We're not planning on doing this primarily for React Suspense. We have wrapped `history` specifically to make it Suspense-aware. Allowing direct access to history would create situations where you'd have subtle and hard to track bugs, especially with suspended components.

**Comment by lcdss** [comment]
> > We're not planning on doing this primarily for React Suspense. We have wrapped `history` specifically to make it Suspense-aware. Allowing direct access to history would create situations where you'd have subtle and hard to track bugs, especially with suspended components.
> 
> I need to access history object and pick some specific route, but currently there is no way to do so. There are tons of use cases based on history, not exposing history object for some weird reason makes your lib totally useless. `window.history` do not work either, because you decided to create your own historyContext, I don't know man, I really don't know, creating router without access to history really?? maybe next release you can remove functionality to define routes? seriously, why developers need that? seems you know better :)

You could, probably, easily do what you want, creating a custom BrowserRouter that uses your own history instance. So it's not a useless library after all.

**Comment by WoodyWoodsta** [comment]
@lcdss While that is technically true, you run the risk of using a different instance of `history`. So in order to make sure that doesn't happen, you have to make sure the same version of `history` is depended upon by your project and `react-router-dom` - and without a peer-dependency binding, it's unsafe to have to be responsible for that.

**Comment by bendenoz** [comment]
What is the recommended way to access history.block then? Is it possible through useNavigation?
