### ISSUE TITLE
[Feature]: Provide a mechanism to delete navigation state properties

### ISSUE THREAD

**Issue by peteragarclover** [remix-run/react-router#8673]
### What is the new or updated feature that you are suggesting?

Currently you can pass state to a route via the navigate `state` property. This is really useful if you want to navigate to a page in a specific starting state (e.g. displaying an alert, selecting an option, pre-filling a form, etc).

If you refresh the page the route is loaded with that state again. If you don't want that behaviour it isn't obvious what the best approach to handle that is.

It also gets complicated if you navigate to a route where different state properties are consumed by different components. If each is responsible for deleting their own known state properties that shouldn't survive a refresh, and each tries to replace the current route, only one of them will work.

It would be helpful if react-router provided a mechanism to support this use case.

In my own project I have implemented a context provider with a hook, which stores in its component state each navigation state property to remove, and in a single `useEffect` replaces the current navigation with those properties removed from the current `state` provided from `useLocation`.

### Why should this feature be included?

Other people are [asking in StackOverflow](https://stackoverflow.com/questions/40099431/how-do-i-clear-location-state-in-react-router-on-page-reload/66359848) how to do this. The answers are varied, not ideal (e.g. they suggest deleting all state), or only work for v5.

Also, I'm raising this because the v6 types for `useLocation` have this note:
> Note: If you're using this it may mean you're doing some of your own
> "routing" in your app, and we'd like to know what your use case is. We may
> be able to provide something higher-level to better suit your needs.

**Comment by timdorr** [comment]
`location.state` is intended for storage of state data that is related to the current location. While it was cleared on refresh in prior versions, that was actually unintentional behavior. Under v6, it sticks around as intended. 

If you need state that clears on reload, you should use `useState`. If you want it to persist on reload, use `location.state`.
