### ISSUE TITLE
[Feature]: Access history action

### ISSUE THREAD

**Issue by adred** [remix-run/react-router#8674]
### What is the new or updated feature that you are suggesting?

Provide an API from which I access the action. Before v6, I can access it using `useHistory` hook.

### Why should this feature be included?

I'm doing a page transition feature that requires me to know the action performed by the router.

**Comment by vukadinFE** [comment]
You can use `useNavigate` instead:
https://github.com/remix-run/react-router/blob/main/docs/upgrading/v5.md#use-usenavigate-instead-of-usehistory

**Comment by rnantes** [comment]
There is no way to know using `useNavigate` wether the action [POP, PUSH, or REPLACE ](https://reactrouter.com/docs/en/v6/getting-started/concepts#history-and-locations).

A common use case is scrolling to the top of the page when the user does a PUSH action (i.e clicks a Link) but not it was a POP or REPLACE. There is no easy way to do this in react-router v6

**Comment by timdorr** [comment]
Correct, this is implemented as `useNavigationType`.
