### ISSUE TITLE
[Bug]: Route.index attribute does not accept "true" in TypeScript

### ISSUE THREAD

**Issue by michael-schmid1** [remix-run/react-router#8675]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

The compilation target for TypeScript is set to "ES2021" in tsconfig.json. In your Typescript project add routes to your App.tsx as follows:

```js
export default function App() {

    <BrowserRouter>
        <Routes>
            <Route path="/" element={...some element...}>
                <Route index element={...some element...} path="path1" />
                <Route element={...some element...} path="path2" />
            </Route>
        </Routes>
    </BrowserRouter>
}
```

### Expected Behavior

The above example should compile, however the Typescript compiler does not accept the "<Route index". The exact error message is: "Type 'true' is not assignable to type 'false | undefined'".

### Actual Behavior

The example should compile, the route marked with "index" should be selected by default.

**Comment by timdorr** [comment]
You have a `path` prop on that Route. The types don't allow you to have both a `path` and `index` prop.

**Comment by michael-schmid1** [comment]
A right, thanks!
