### ISSUE TITLE
[Bug]: Back button not working

### ISSUE THREAD

**Issue by patientplatypus6** [remix-run/react-router#8676]
### What version of React Router are you using?

v6

### Steps to Reproduce

Using  `navigate("../"+routename, { replace: true });` a route can be pushed to the stack and redirected to a new page when making a page on localhost, however if the browsers back button is clicked then the page is redirected to a previous website (and not the previous route on the stack). I am aware of navigate(-1), navigate(1) etc, but I want to use the back and forward buttons of the browser which don't appear to be working.

### Expected Behavior

See above

### Actual Behavior

See above

**Comment by patientplatypus6** [comment]
OK - so how do I add to the stack?

**Comment by girishk21** [comment]
remove `{ replace: true }` from `navigate("../"+routename, { replace: true });` and just use `navigate("../"+routename);`
