### ISSUE TITLE
[Bug]: Open Bracket after every route

### ISSUE THREAD

**Issue by FelixSelter** [remix-run/react-router#8681]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Create a simple home route
```js
<BrowserRouter>
      <Routes>
            <Route path="/" element={<p>home</p>} />
      </Route>
</Routes></BrowserRouter>
```

### Expected Behavior

Render like this:
```html
<div id="root"><p>home</p></div>
```

### Actual Behavior

Actually it ads a bracket. This happens with every component
```html
<div id="root"><p>home</p>)</div>
```

**Comment by liuhanqu** [comment]
I think the bracket is added by your code.
Maybe you should check your code first.

**Comment by FelixSelter** [comment]
Yes I thought this as well but my code is literally what I posted aboce

**Comment by timdorr** [comment]
React Router doesn't add anything to the elements provided to it. This is either something wrong with your code, or your tooling is adding this. It's not the library doing it.

**Comment by FelixSelter** [comment]
Ok guys. I reinstalled the library and the problem was gone. Very strange. Might I accidentally inserted something into the source files. Thank you for your help and the great tool. Keep up the great work
