### ISSUE TITLE
[Bug]: Outlet forces to rebuild from scratch react.memo component on route change.

### ISSUE THREAD

**Issue by hadson172** [remix-run/react-router#8682]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-koswk8-4ldrjr?file=src/App.jsx
2. Type in url /collection
3. You will see to buttons. When you are clicking between buttons (first, second). Every time HeavyRenderingGrandChildMemo is build from scratch (ignoring memo). On each click the log "This log should be display only once" is logged. 

### Expected Behavior

I would expect to not to render from scratch `HeavyRenderingGrandChildMemo `if state is not changed. 

### Actual Behavior

 Router is ignoring React.memo caching, rebuilds component each time which breaks my optimization.

**Comment by timdorr** [comment]
You're generating a new array on each render of Parent. This fixes it:

```js
const Parent = () => {
  const [state, setState] = React.useState([[1, 2, 3, 4]]);
  console.log(useOutletContext);

  return <Outlet context={state} />;
};
```

**Comment by hadson172** [comment]
@timdorr Unfrotunately the sollution you show does not work. Take a look:
![image](https://user-images.githubusercontent.com/8881977/155691221-1970b790-b978-45fd-b918-0205e20bc6fe.png)

On each button click component is still rerendered. It seems like react-router is creating two separate components for each route, and each of them i living on their one.

**Comment by wiktormorawski** [comment]
+1, I would like to know what I can do to prevent this rerender, because what u wrote @timdorr is not useful and does not fix the problem. :)

**Comment by Magyar-Peter-22** [comment]
My costly header re-render every time I switch between pages.
The answer of @timdorr does not solves the issue.
