### ISSUE TITLE
[Bug]: useMatch with wildcard always returning null

### ISSUE THREAD

**Issue by thany** [remix-run/react-router#8684]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

Write a `useMatch` with the intend to match at the END of a url. You don't care /about/anything/before/cat/42.

```
const match = useMatch('*/cat/:catId');
```

### Expected Behavior

It matches.

### Actual Behavior

Returns `null`.

**Comment by timdorr** [comment]
A leading star is not a valid or supported pattern element. useMatch and matchPath are not aware of nesting. They are intended to be used with the absolute pattern, not a relative or partial one.

**Comment by thany** [comment]
Please reopen.

This used to work fine, and was not mentioned as a breaking change. Therefor, this has to be a valid bug.
On top of that, it is how we (and several others) want to use React Router, and have been using it up to v5. So please do not brush it off.

**Comment by timdorr** [comment]
Path matching has changed overall in v6. This was mentioned in the upgrade notes.

**Comment by thany** [comment]
It was not mentioned that a wildcard at the start is not longer supported. In fact it is stated nowhere in the documentation what *is* supported exactly. Only that regexes are no longer supported, which is another big disappointment.

Anyhow, stating "it's changed, deal with it", which is essentially what you're doing, is not the way to go. Clearly, from this and the previous issue, you can see that there is demand for more complex path matching, as this was entirely possible in v5, so folks where using it.

You can't just severely limit one of the core concepts of a package and say "deal with it", because not every application is simple enough to adapt to this. You should either fix it so existing path matching can still be used (even if in a different form), or provide a "way out", perhaps by allowing folks to hook in a different path matching algorithm which is currently impossible.
