### ISSUE TITLE
[Feature]: Compatibility layer that implements the v5 API

### ISSUE THREAD

**Issue by mg-83** [remix-run/react-router#8695]
### What is the new or updated feature that you are suggesting?

We want to upgrade to Router v6 but our application has tones of routes, redirects and other stuff. In the migration guide you are talking about a "compatibility layer that implements the v5 API". Are you currently working on this, when can we expect it?  

### Why should this feature be included?

Because people will not be able to upgrade their bigger applications to v6 without it.

**Comment by clivetong** [comment]
There's this discussion https://github.com/remix-run/react-router/discussions/8444 which has been unanswered for four months

**Comment by rj-david** [comment]
https://github.com/remix-run/react-router/discussions/8753

**Comment by timdorr** [comment]
Yup, we've got `react-router-dom-v5-compat`, so this is now a thing :)
