### ISSUE TITLE
[Bug]: useNavigate() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by tgb1413** [remix-run/react-router#8701]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

This is part of my index.tsx.
```javascript
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <ScreenContextProvider>
        <ReduxProvider>
          <App />
        </ReduxProvider>
      </ScreenContextProvider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById("root")
);
```

This is part of my App.tsx.
```javascript
return (
    <ToastContextProvider>
      <ToastContainer
        successImg={checked}
        confirmImg={question}
        failureImg={warning}
        toastPosition="top-right"
      />
      <Routes>
        <Route path="/" element={<LoginPage />} />
        <Route path="/main/*" element={<MainPage />} />
      </Routes>
    </ToastContextProvider>
  );
```

This is part of my MainPage.tsx
```javascript

function MainPage() {
  useCheckLoggedin();

  return (
    <LeftRightLayout
      style={{ backgroundColor: "rgb(79, 127, 98)", borderRadius: "25px" }}
      leftStyle={{ width: "15%" }}
      rightStyle={{ width: "85%", padding: "1rem 1rem 1rem 0" }}
      left={<SideBar />}
      right={
        <Routes>
          <Route path="/" element={<SmartFarmList />} />
          <Route path="/status" element={<FarmStatus />} />
        </Routes>
      }
    />
  );
}
```

And This is part of my useCheckLoggedin().
```javascript
import { useNavigate } from "react-router";

function useCheckLoggedin() {

  ...

  const reduxDispatch = useThunkDispatch();
  const toastDispatch = useToastDispatchContext();

  const navigate = useNavigate(); // line where the error happens

  ...

}
```

When i go to the main page from login page, 
```
Uncaught Error: useNavigate() may be used only in the context of a <Router> component.
```
this error shows up.

I definitely used useNavigate inside of <BrowserRouter />.

Did my nesting routing code cause a problem?

### Expected Behavior

I can go to MainPage from LoginPage

### Actual Behavior

```
Uncaught Error: useNavigate() may be used only in the context of a <Router> component.
```

**Comment by ZinkNotTheMetal** [comment]
I'm running into the same issue. I have a top level component that needs to define Authorization and it the examples use useHistory. Migrating this to useNavigate gets me the above error.

**Comment by tgb1413** [comment]
@ZinkNotTheMetal
```
npm list react-router react-router-dom
```
Try to use above command to check your `react-router` and `react-router-dom` version. In my case, different versions of the two modules caused problem.

Before
```
├─ react-router-dom@6.2.2
│  └─ react-router@6.2.2
└─ react-router@6.2.1
```

After
```
├─ react-router-dom@6.2.1
└─ react-router@6.2.1
```

**Comment by ZinkNotTheMetal** [comment]
├─┬ @okta/okta-react@6.4.3
│ └── react-router-dom@6.2.2 deduped
└─┬ react-router-dom@6.2.2
  └── react-router@6.2.2

This is what mine looks like, should I remove react-router-dom?

**Comment by tgb1413** [comment]
@ZinkNotTheMetal 
I think duplicated `react-router-dom` is the problem. Removing `react-router-dom` can be the solution, but I'm not sure.

**Comment by Basudev1** [comment]
Me too facing the same problem

Uncaught Error: useNavigate() may be used only in the context of a <Router> component.

└─┬ react-router-dom@6.2.2
  └── react-router@6.2.2

**Comment by tgb1413** [comment]
@Basudev1 
`useNavigate()` must be inside of `<Router>` component. I think you should check where your `<Router>` component and `useNavigate()` are.

**Comment by Basudev1** [comment]
It was solved somehow, wrapped Browser router in index.js and done routing in app

**Comment by adamnowocin** [comment]
check if you got version 6.2.1 in your package.json and if so update it to 6.2.2:
```
"react-router": "6.2.2",
"react-router-dom": "6.2.2",
```
