### ISSUE TITLE
[Bug]: The matchRoutes function does not match routes if there is cyrillic symbol at the beginning.

### ISSUE THREAD

**Issue by nvdxdy** [remix-run/react-router#8703]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

```
const routes = [
	{
		element: <AppContainer />,
		children: [
			{
				path: "/:lang",
				element: <Search />
			}
		]
	}
];

/** matchedRoutes is null */
const matchedRoutes = matchRoutes(routes, "/base/ы", "/base");
```

### Expected Behavior

`/base/ы` - Matched

### Actual Behavior

`/base/s` - Matched
`/base/ы` - Not matched

**Comment by brophdawg11** [comment]
This should be fixed since the changes for special character handling in [6.4.3](https://github.com/remix-run/react-router/releases/tag/react-router%406.4.3)
