### ISSUE TITLE
[Bug]:  export 'Switch' (imported as 'Switch') was not found in 'react-router-dom'

### ISSUE THREAD

**Issue by ShubhamSehra** [remix-run/react-router#8704]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

`import {BrowserRouter as Router, Switch, Route, Link} from "react-router-dom";`

but the browser throwing an err says

**export 'Switch' (imported as 'Switch') was not found in 'react-router-dom'**

 (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, NavigationType, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createPath, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, parsePath, renderMatches, resolvePath, unstable_HistoryRouter, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams)

### Expected Behavior

Expected behaviour to work this code as in your documentation 

https://v5.reactrouter.com/web/guides/quick-start

### Actual Behavior

**export 'Switch' (imported as 'Switch') was not found in 'react-router-dom'**

**Comment by MeiKatz** [comment]
RRv6 has no `<Switch />` component. It got replaced by `<Routes />`.

**Comment by ShubhamSehra** [comment]
my bad.. Thank You!!

**Comment by foxorajack** [comment]
Docs need updating

**Comment by Prachi2002** [comment]
after using routes also nothing is visible on the screen but in console it's showing
error: is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

**Comment by patelrohan750** [comment]
Refer to this article to solve the issue[ ‘Switch’ is not exported from ‘react-router-dom’](https://reactjsguru.com/switch-is-not-exported-from-react-router-dom/)
