### ISSUE TITLE
[Bug]: Router ignoring basename when matching route

### ISSUE THREAD

**Issue by rrs-bg** [remix-run/react-router#8705]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

Go to https://codesandbox.io/s/keen-lamport-lbki3l?file=/src/App.js
Try out these routes:
/test
/base/test

They will give same result: Show 'test page' text.

### Expected Behavior

I would expect /test to go to fallback to '/' route as basename is defined to be 'base'.

### Actual Behavior

I would expect Router to not match routes if they don't have basepath. This could be the expected behavior tho, it just weird for me that this is the case. Our use case is we need to dynamically serve the app in different base paths. I would like urls that do not contain the basename to fallback to a page not found component.

**Comment by timdorr** [comment]
The basename is not for matching, it's for links on the page. It functions much like `<base name="...">` in HTML.
