### ISSUE TITLE
[Bug]: useResolvedPath('#') return location router?

### ISSUE THREAD

**Issue by pumpkindev** [remix-run/react-router#8707]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

const path=  useResolvedPath('#')
console.info(path)
path.pathname===location.pathname

### Expected Behavior

path.pathname=='#'

### Actual Behavior

 path.pathname===location.pathname

**Comment by timdorr** [comment]
The hash part of a URL isn't part of the path. It shouldn't be in the resolved path.
