### ISSUE TITLE
[Feature]: Export the Router Context Consumer

### ISSUE THREAD

**Issue by wkrasnicki** [remix-run/react-router#8708]
### What is the new or updated feature that you are suggesting?

I am using a framework for working with the Canvas API using React components called `react-konva`, which unfortunately causes some scoping issues with the Context API. Because of that, it is required to manually *bridge* Providers into the canvas using a pattern proposed by its maintainer [here](https://github.com/konvajs/react-konva/issues/188#issuecomment-478302062). 

### Why should this feature be included?

I have managed to bridge all my providers except for React Router as it does not export a Context Consumer, required to implement this workaround and because of that I cannot use hooks inside my components, but rather have to resort to prop drilling. I looked at the code and noticed that there are actually several context constituting the Router context and I'm not sure if bridging them one by one won't cause any issues, especially that using them explicitly is not documented.

**Comment by timdorr** [comment]
The `<Router>` component provides this context automatically. We don't export the Router context directly because doing so would create edge case issues with Suspense and other asynchronous APIs.

**Comment by nigel-loops** [comment]
Did you ever get a work around for this @wkrasnicki having the same issue with react-pixi
