### ISSUE TITLE
[Bug]: Routes "key" prop breaks CSS animation

### ISSUE THREAD

**Issue by peniswafflexd** [remix-run/react-router#8712]
### What version of React Router are you using?

6

### Steps to Reproduce

1. Create a route that has an outlet in another component
2. Create a component that implements a CSS transition that is affected by the outlets route parameters:
```jsx
 const { width, height } = useParams();
  return (
    <>
      <div className="container">
        <div
          style={{ width: `${width}px`, height: `${height}px`, transition: 'all 250ms ease' }}
          className="dynamicBox"
        />
      </div>
      <Outlet />
    </>
```
3. Observe that CSS is animated when navigating to that route with different parameters.
4. Add a key={location.pathname} or key={location.key} prop to Routes component
5. Observe CSS transitions are no longer animated.

I've created a minimum code reproduction [here](https://codesandbox.io/s/autumn-moon-t4o6v8?file=/src/App.js:619-870), you can see the difference between having the key prop and removing it.

### Expected Behavior

CSS transitions would continue to function

### Actual Behavior

CSS transition don't function

**Comment by timdorr** [comment]
Using useLocation will cause your component to update on every location change. If you need the previous location for an animation, you should use a ref, so you can access the prior value.

**Comment by peniswafflexd** [comment]
Ahh I see, how would I go about using a ref for CSS animation?
