### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by habibulislam6862** [remix-run/react-router#8714]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

```
const id = 2;

<NavLink to={id}>test link</NavLink>
```

### Expected Behavior

`<a href="current_path/2">test link</a>`

### Actual Behavior

`<a href="current_path">test link</a>`

**Comment by Slapbox** [comment]
Please use a title.

**Comment by timdorr** [comment]
The `to` prop needs to be a string.

**Comment by habibulislam6862** [comment]
> The `to` prop needs to be a string.

if we need a dynamic things in "to={ }", then what to do?

**Comment by DianomiJH** [comment]
You can still do that, but your id is of number type, not string type. You could do `to={'/' + 2}`
