### ISSUE TITLE
[Feature]: expose current route object in a safe way

### ISSUE THREAD

**Issue by soolidtech** [remix-run/react-router#8716]
### What is the new or updated feature that you are suggesting?

Hi !

I use `useRoutes` to define my routes as an array of objects. Very useful.
The thing is that i'm adding some additional data in these route objects.

I would like to be able to retrieve this data in react components, but i didn't find an official way to do that.

Is it technically possible ? would it be a good practice ? what are the alternatives ? I hope I'll get your advice on this.

### Why should this feature be included?

The pros of this feature would be to take advantage of a declarative way to define routes with extra information, and then access it inside components

**Comment by timdorr** [comment]
Just put it as props on the route's `element`. It will be passed in directly there.
