### ISSUE TITLE
[Feature]: Improve error message

### ISSUE THREAD

**Issue by KristerL** [remix-run/react-router#8721]
### What is the new or updated feature that you are suggesting?

I ran into an error, and the error message was not really helpful. Only in inspecting the code did the TODO message lead me on the correct path. 

Not sure if just updating the error message is the optimal solution, because this is a really common error that users forget to add Router component. Adding the 2 versions of router loaded, might confuse a lot.

React throws an error when two Reacts are detected, maybe similar logic could be added to react-router

In https://github.com/remix-run/react-router/blob/main/packages/react-router/index.tsx#386
```
export function useLocation(): Location {
  invariant(
    useInRouterContext(),
    // TODO: This error is probably because they somehow have 2 versions of the
    // router loaded. We can help them understand how to avoid that.
    `useLocation() may be used only in the context of a <Router> component.`
  );

  return React.useContext(LocationContext).location;
}
```

Side note. The issue tracker links don't work:

- https://reactrouter.com/docs/en/v6/getting-started/faq - 404 error
- hhttps://reactrouter.com/docs/en/v6/examples/basic - invalid url
- https://stackoverflow.com/questions/ask?tags=react-router - requires to log in, maybe this is better https://stackoverflow.com/questions/tagged/react-router

### Why should this feature be included?

Nice to have feature to help developers debug.

**Comment by timdorr** [comment]
Thanks for pointing out the issue links. Those are fixed now!

I think for this it would best be discussed via PR, where we can discuss a concrete change to the message and iterate from there. I'll close this out, but feel free to open one up for discussion.
