### ISSUE TITLE
[Bug]: NavLink with end prop doesn't match url with trailing slash 

### ISSUE THREAD

**Issue by mqklin** [remix-run/react-router#8724]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

https://codesandbox.io/s/bold-monad-0rwec7?file=/src/App.js

Imagine there is a NavLink:
```
<NavLink 
  to="example" 
  end 
  style={({ isActive }) => ({ color: isActive ? 'green' : 'blue' })}
>
  Example
</NavLink>
```

### Expected Behavior

NavLink should match on `example/` url (same for `to="example/"` and `"example"` url).

### Actual Behavior

If you go to `example/` url, the link won't match, despite there is no matched descendant paths.

**Comment by timdorr** [comment]
This is expected behavior. Another `/` establishes a new path segment, so it is a materially different path. It shouldn't match for NavLink's active state.

**Comment by emilte** [comment]
Is there any way around this?

**Comment by mqklin** [comment]
@emilte I do this in the app root (just remove trailing slash):
```
  useEffect(() => {
    if (location.pathname !== '/' && location.pathname.slice(-1)[0] === '/') {
      navigate(`${location.pathname.slice(0, -1)}${location.search}${location.hash}`, {state: location.state, replace: true});
    }
  }, [location]);
```
