### ISSUE TITLE
[Bug]: Wildcard (not-found) route doesn't catch orphan url  

### ISSUE THREAD

**Issue by mqklin** [remix-run/react-router#8726]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

Simple example:
```
import { Routes, Route, Link } from "react-router-dom";

export default function App() {
  return (
    <div>
      <Routes>
        <Route path="/*" element={null} />
        <Route path="*" element={<div>Not found</div>} />
      </Routes>
      <Link to="example">Click me to see the bug (should show Not found page)</Link>
    </div>
  );
}
```

More real example: https://codesandbox.io/s/happy-mclean-rvgoe2?file=/src/App.js
```
import { Routes, Route, Link } from "react-router-dom";

export default function App() {
  return (
    <div>
      <Routes>
        <Route index element={<Link to="/user">User</Link>}/>
        <Route path="/user/*" element={<User/>} />
        <Route path="*" element={<div>Not found</div>} />
      </Routes>
      
    </div>
  );
}

function User() {
  return (
    <div>
      <Routes>
        <Route index element={<div>User page<div><Link to="/user/balance">Balance</Link></div></div>}/>
        <Route path="balance" element={<div>Balance subpage</div>}/>
      </Routes>
      <div><Link to="example">Click me to see the bug (should show Not found page from the root route)</Link></div>
    </div>
  );
}
```

In the User component there is only /balance route, so seems like it should show Not Found on all others (including /example) urls.

### Expected Behavior

Clicking on the "/example" link shows "Not found" page as there is no `/example` routes

### Actual Behavior

Orphan link isn't caught despite there is wildcard route that should catch it

**Comment by timdorr** [comment]
This is expected behavior. Nested instances of `<Routes>` don't report up to their ancestors that they don't match. There is no concept of a root "catch-all" route.
