### ISSUE TITLE
[Bug]: Access to history.listen as in docs doesn't work as described

### ISSUE THREAD

**Issue by TruePath** [remix-run/react-router#8728]
### What version of React Router are you using?

6.22

### Steps to Reproduce

In the v6 [docs](https://reactrouter.com/docs/en/v6/getting-started/concepts#matching) it describes accessing the history.listen callback using the following code:

```
let history = createBrowserHistory();
history.listen(({ location, action }) => {
  // this is called whenever new locations come in
  // the action is POP, PUSH, or REPLACE
});
```

Unfortunately, this code doesn't work as it creates a new history object which only observes back/forward transitions and doesn't execute on link clicks.  I've worked around the problem by creating a custom router by following [poyoman's suggestion](https://stackoverflow.com/questions/63471931/using-history-with-react-router-dom-v6) here which lets me gain independent access to the *same* history object used by the Router. Looking at the various FAQs about moving to v6 it suggests moving to useNavigate but I've not found anything that provides the history.listen functionality.  

I'm filing this as a bug rather than a feature request because the v6 docs seem to clearly indicate that this should work (if there is a way to pass/extract the history object from the BrowserRouter it's not stated) so it's at least a bug in the documentation.

### Expected Behavior

history.listen should fire on both link clicks and forward/back navigation.

### Actual Behavior

Only the back/forward buttons register if the code described in the v6 docs is followed.

**Comment by timdorr** [comment]
This documentation isn't describing how to set up a `history` instance outside of React Router, it's just describing the `history` API in isolation. It says in the very next line:

> Apps don't need to set up their own history objects - that's the job of `<Router>`.

Which indicates you don't need to run that code and it probably wouldn't work anyways.

**Comment by TruePath** [comment]
I see your point, but I think it i at least implies that said functionality (history.listen) is available.  If this isn't functionality that is capable of being used in react-router it seems very confusing to include that in the docs.  If there was some other way mentioned in the docs to achieve the same effect then sure.  

And that remark about creating the history object isn't really something that the reader of the docs is going to understand if they aren't familiar with how react-router handles history.  Now that I've been through the code I see why you say it that way but until I dived into the code I didn't know whether createBrowserHistory was always creating a new instance of a history object or, if the history already existed, would just grab whatever history object that react router had created if it already existed.

I'd be happy to create a pull request either removing that section or indicating that this isn't something one can accomplish without diving into the implementation but only that's something you'd be interested in changing.  

Anyway, just my .02 cents based on the fact that the stackoverflow question and other reported issues suggest I'm not the only one finding it a bit confusing.
