### ISSUE TITLE
[Bug]: Runtime error when using React.Fragement as child of Routes component

### ISSUE THREAD

**Issue by saharis9988** [remix-run/react-router#8732]
### What version of React Router are you using?

6

### Steps to Reproduce

I try to render the route component from another component in order to implement dynamic routing recursively and I add it as a child component of the routes component with React Fragment.
```
export type AppRoute = {
  label: string;
  path: string;
  page?: React.ReactElement;
  subRoutes?: AppRoute[];
};
function AppRoutes() {
  return (
    <Routes>
      <React.Fragment>
        <GetRoutes routes={AppRouteItems} />
      </React.Fragment>
    </Routes>
  );
}

const GetRoutes = ({ routes }: { routes: AppRoute[] }): React.ReactElement => {
  return (
    <>
      {routes.map((route) => (
        <Route key={route.path} path={route.path + (route.subRoutes ? "/*" : "")} element={route.page}>
          {route.subRoutes && <GetRoutes routes={route.subRoutes} />}
        </Route>
      ))}
    </>
  );
};
```
### Expected Behavior

The routes have to be created.

### Actual Behavior

I get runtime error: ```[GetRoutes] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>```

**Comment by liuhanqu** [comment]
```js
function AppRoutes() {
  return (
    <Routes>        
         {GetRoutes({routes: AppRouteItems})}
    </Routes>
  );
}
```
try this ?

**Comment by timdorr** [comment]
Correct, the direct descendants of Routes cannot be non-Route components.

**Comment by saharis9988** [comment]
> Correct, the direct descendants of Routes cannot be non-Route components.

So you have problem with the error that is outputed to the screen because it states that you can add fragment as a child which is not true..

**Comment by timdorr** [comment]
You can have a fragment included in the subtree. But you can't have any other kind of component provided as `children` to `<Routes>`. This would also be valid:

```js
function AppRoutes() {
  return (
    <Routes>
      <>
        {routes.map((route) => (
          <Route key={route.path} path={route.path + (route.subRoutes ? "/*" : "")} element={route.page}>
            {route.subRoutes && <GetRoutes routes={route.subRoutes} />}
          </Route>
        ))}
      </>
    </Routes>
  );
}
```

**Comment by saharis9988** [comment]
> You can have a fragment included in the subtree. But you can't have any other kind of component provided as `children` to `<Routes>`. This would also be valid:
> 
> ```js
> function AppRoutes() {
>   return (
>     <Routes>
>       <>
>         {routes.map((route) => (
>           <Route key={route.path} path={route.path + (route.subRoutes ? "/*" : "")} element={route.page}>
>             {route.subRoutes && <GetRoutes routes={route.subRoutes} />}
>           </Route>
>         ))}
>       </>
>     </Routes>
>   );
> }
> ```

OK..  I still can't understand why  it's not possible to add other component that renders routes in its template, but there are workarounds..
