### ISSUE TITLE
[Bug]: '..' doesn't work when used with search in a to object 

### ISSUE THREAD

**Issue by hornta** [remix-run/react-router#8737]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

https://github-6zmcyd--3000.local.webcontainer.io

1. Open test case
2. Go to dashboard
3. Click on the first link -> redirected to dashboard
4. Go back to dashboard
5. Click on second link -> not redirected to dashboard

### Expected Behavior

I expect by clicking on both links that it will take me to the dashboard.

`./..` works for some reason but `..` doesn't work. However both these variants work when written as `to=".."` and `to="./.."` without a `to` object.

**Comment by timdorr** [comment]
Location objects aren't parse the same as strings for the `to` prop. You can combine the search as a part of the string form, as it will be parsed into the resulting location object: `<Link to="..?abc=123">`

**Comment by hornta** [comment]
I still think it's a bug and not a expected behaviour. Switching between object form and string form shouldn't matter in this case.
