### ISSUE TITLE
[Bug]: v6 not work on Firefox 34

### ISSUE THREAD

**Issue by fynncfchen** [remix-run/react-router#8741]
### What version of React Router are you using?

v6.2.1

### Steps to Reproduce

1. Install react-router-dom v6.2.1
2. Have some code
3. Setup webpack
4. Run with webpack
5. Open Firefox 34.0
6. Open console, it display `SyntaxError: let is a reserved identifier`

### Expected Behavior

The page display normally after transpile with Webpack and Babel.

### Actual Behavior

Firefox 34 display `SyntaxError: let is a reserved identifier` in console with white screen.

**Comment by timdorr** [comment]
Sorry, but that is a very old version of Firefox. You should transpile your entire codebase with something like Babel to support it.
