### ISSUE TITLE
[Bug]:  vite: No matching export in "node_modules/react-router/index.js" for import "Switch"

### ISSUE THREAD

**Issue by Keekuun** [remix-run/react-router#8743]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

My dependencies:

`  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-loadable": "^5.5.0",
    "react-router-config": "^5.1.1",
    "react-router-dom": "^6.2.2"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.0.7",
    "vite": "^2.8.0"
  }`

when I run `npm run dev`,  result is :

![image](https://user-images.githubusercontent.com/39521977/160590513-21af5b82-c361-4d75-a699-3d9c451c5730.png)

I found in version 6.2.2, there is no esm:

![image](https://user-images.githubusercontent.com/39521977/160590674-5a447f53-9f7a-4522-8ef6-8fbfd747510d.png)

but in version 5.2.1, it`s ok:
![image](https://user-images.githubusercontent.com/39521977/160590846-23c13e4c-1a9b-4955-9da1-fffe21f02d32.png)

![image](https://user-images.githubusercontent.com/39521977/160592310-1632cc42-e6ea-44ee-8a78-ff99d4792177.png)

### Expected Behavior

no errors

### Actual Behavior

ERROR: No matching export in "node_modules/react-router/index.js" for import "Switch"

**Comment by timdorr** [comment]
There is a new API in v6. Switch has been replaced. Please see the upgrade guide: https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by Keekuun** [comment]
I see, when React Router v6 had deleted react-router-config package

**Comment by Keekuun** [comment]
here is the answer:
![image](https://user-images.githubusercontent.com/39521977/160738993-653c1f24-a916-4f91-ad90-4b796d81f264.png)
https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by Keekuun** [comment]
> johnrails

https://github.com/remix-run/react-router/issues/8743#issuecomment-1082551758

**Comment by Keekuun** [comment]
> Use useRoutes instead of react-router-config

[Use useRoutes instead of react-router-config](https://reactrouter.com/docs/en/v6/upgrading/v5)
