### ISSUE TITLE
[Bug]: StaticRouter does not support HashRouter

### ISSUE THREAD

**Issue by Jack-Works** [remix-run/react-router#8757]
### What version of React Router are you using?

v6

### Steps to Reproduce

use a StaticRouter to SSR

### Expected Behavior

It will render links like `#/abc` because we're using `HashRouter` in the client

### Actual Behavior

There is no way to specify the behavior of StaticRouter.

**Comment by timdorr** [comment]
This has never worked. HashRouter is only for server-less apps, usually with local files. If you want to use StaticRouter, it should be paired with BrowserRouter.
