### ISSUE TITLE
[Bug]: Route transition flickers with React 18 when loading data asynchronously.

### ISSUE THREAD

**Issue by acelaya** [remix-run/react-router#8759]
### What version of React Router are you using?

6.3

### Steps to Reproduce

* Set-up some routes with components that load data asynchronously on `useEffect`, and have loading state.
* Navigate between routes.
* Observe routes with loading state have a flickering for a fraction of a second, where you see the previous state, and then it transitions to loading state.

The behavior can be seen here: https://stackblitz.com/edit/github-j7dttb?file=src/App.tsx

* Navigate to `About`. It will be loading for 2 seconds (via `setTimeout` inside `useEffect`) and then display a list of items.
* Navigate to any other route.
* Navigate back to `About`. It will show a glipse of the list, then transition to loading state, and after 2 seconds, show the list again.

For the sake of simplicity, `setTimeout` has been used to fake asynchronous load of data. Also, the list of items is static.

### Expected Behavior

No flickering happens, as with React 17

### Actual Behavior

There's flickering between previous state and loading state when a route is loaded, if its component loads data asynchronously via `useEffect`.

**Comment by timdorr** [comment]
This isn't a bug in React Router itself. It's just how React now handles these kinds of things in 18. You have state that's stored in your App component, which doesn't get removed between renders. The momentary flash is React rendering that stale state from the last time you rendered the component.

Ultimately, you should probably not be storing that state in App, but inside of the About component directly. That way when it's rendered, it will have a fresh state with the initial value. Outside of that, you may want to consider using some of the new Suspense hooks and APIs, especially if you have async data loading. 

However, ultimately, this doesn't have anything to do with React Router. It's just how you're managing state.

**Comment by acelaya** [comment]
> This isn't a bug in React Router itself. It's just how React now handles these kinds of things in 18. You have state that's stored in your App component, which doesn't get removed between renders. The momentary flash is React rendering that stale state from the last time you rendered the component.

I suspected this might be the case. I'll check what's the best way to handle this on React 18.

> Ultimately, you should probably not be storing that state in App, but inside of the About component directly. That way when it's rendered, it will have a fresh state with the initial value.

In my app I use redux. I did that in the example to simplify it, but still mimic a use case in which the state is handled externally and injected via props.

> Outside of that, you may want to consider using some of the new Suspense hooks and APIs, especially if you have async data loading. 

Thanks! I will give that a try.

**Comment by acelaya** [comment]
> In my app I use redux

For those who end up here, looks like the state handling has changed in react-redux 8.0.0 (currently in beta) to work as it used to with React 17, preventing this flickering.
