### ISSUE TITLE
[Bug]: target= '_top' inside a <link /> component doesn't work as expected

### ISSUE THREAD

**Issue by BorjaRuizReverter** [remix-run/react-router#8760]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

I am using target='_top' inside a  `<Link />` component at my website's footer in order to navigate to the top of the document, but the result is not what it should be expected.

This is the code:

`<Link  target="_top" to="/">{'whatever'} </Link>`

Strangely, if target="_blank" is used instead, a new browser window is opened as it is expected. 

### Expected Behavior

What I expected to happen is to respawn at the top of the document when clicking the link.

### Actual Behavior

When clicking the link it just does nothing.

**Comment by timdorr** [comment]
That's not what `_top` is for. It's for navigating to the top-level document of an iframe or series of nested iframes.
