### ISSUE TITLE
[Feature]: Delete function of location state

### ISSUE THREAD

**Issue by alchemist0404** [remix-run/react-router#8762]
### What is the new or updated feature that you are suggesting?

We can update or clear the value of state when we use `useLocation`;

### Why should this feature be included?

Now we are passing the parameters using state when we navigate the page.
`<Link to='/search' state={{ data: 'example' }} />` or `navigate('/search', { state: { data: 'example' } })`
and we get the data in search page using `useLocation`;
and I implemented a feature on that page with the data in this case.

But in other cases, I go to search page without data. Then because the state value is still remained, the feature is run, but it should not be run.

For this, I needed to clear the state of location, but I couldn't find the way. Is there any way for this, or do we need to create?

**Comment by timdorr** [comment]
You simply need to `navigate` or `Link` to that same URL without the state set. According to the History API, which we're wrapping around here, [every location is actually an arbitrary state with an optional URL associated](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState). So, returning to a prior URL is supposed to restore this state. If you don't want it, you need to navigate to the same URL with the state removed.

**Comment by dreddy-conga** [comment]
how to clear location state on component render
