### ISSUE TITLE
[Bug]: Cannot read properties of null (reading 'useContext') when using BrowserRouter on Stackblitz

### ISSUE THREAD

**Issue by DiestroCorleone** [remix-run/react-router#8765]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

- Create a new React (JavaScript) project on [StackBlitz](https://stackblitz.com).
- Install dependency 'react-router-dom', it automatically goes with the latest version (6.3.0).
- Import `BrowserRouter` from 'react-router-dom'.
- When I wrap my `App` component in `BrowserRouter`, I get an error: _Error in /turbo_modules/react@18.0.0/cjs/react.development.js (1613:21) Cannot read properties of null (reading 'useContext')_
- You can see an example app [here](https://stackblitz.com/edit/react-6mwukx?file=src%2Findex.js).
- This **does not happen** when using React Router 6.2.2.

### Expected Behavior

No error should pop up, it should just let me move on and use `Routes`, `Route`, `Link` and so on.

### Actual Behavior

- When I wrap my `App`  component in `BrowserRouter`, I get an error: _Error in /turbo_modules/react@18.0.0/cjs/react.development.js (1613:21) Cannot read properties of null (reading 'useContext')_
- You can see an example app [here](https://stackblitz.com/edit/react-6mwukx?file=src%2Findex.js).
- This **does not happen** when using React Router 6.2.2.

**Comment by timdorr** [comment]
This is a StackBlitz issue, not a React Router issue. It looks like you have different versions of React in your tree (17.0.2 vs 18.0.0). That is up to however StackBlitz resolves your dependencies, which isn't part of this library.
