### ISSUE TITLE
[Feature]: namespaces urls/paths

### ISSUE THREAD

**Issue by GiancarlosIO** [remix-run/react-router#8774]
### What is the new or updated feature that you are suggesting?

I want to be able to navigate to a page/route/url by using a namespace.

**Context:**
In the python Django framework we have something called url-namespaces which is useful to navigate to a specific url by using only a "namespace". You can read more about it [here](https://docs.djangoproject.com/en/4.0/topics/http/urls/#url-namespaces).

I think it would be nice to have something like:
```tsx
// having:
type NewRouteObject = RouteObject & { name?: string }
const routes: RouteObject[] = [{
    path: '/',
    children: [{
        index: true,
        name: 'homepage'
    }, {
        path: 'products/:productId',
        name: 'productDetail'
    }]
}]

// it would be good to be able to do:
type navigateWithNamespace = (namespace: string, parameters?: {[key: string]: string }) => void
// namespace only
navigateWithNamespace('homepage')

// namespace with path parameters
navigateWithNamespace('productDetail', { productId: '8823' })
```

Ideally, (and this is a tricky part) the `navigateWithNamespace` could be typed automatically using the react-router context data (assuming that the path/routes data lives inside the context):
```tsx
type navigateWithNamespace =
  | (namespace: 'homepage') => void
  | (namespace: 'productDetail', { productId: string }) => void
```

### Why should this feature be included?

* Improves DX routing
* Devs don't make mistakes/typos when trying to navigate to a page/url
* No need to create a custom util/context/hook to make sure that the page/url/path that I wan to navigate exists

what do you think? 🤔 

Thanks!

**Comment by timdorr** [comment]
These are "named routes", which we used to have in the past. Because of the more dynamic nature of the current version of the library, this isn't possible and isn't something we're going to implement.

**Comment by MoInnovates** [comment]
@timdorr is the "named routes" feature still not possible now in v7 with the typegen and the new centralized routes config in **routes.ts**?

**Comment by timdorr** [comment]
You can do this via a route's generated `id` and `useRouteLoaderData`, along with importing their types if you need something more specific.
