### ISSUE TITLE
[Bug]: 【AppDelegate.h、AppDelegate.m、main.m、 ReactRouterNativeTests.m has wrong License declaration】

### ISSUE THREAD

**Issue by tongle1** [remix-run/react-router#8776]
### What version of React Router are you using?

v5.2.1

### Steps to Reproduce

AppDelegate.h、AppDelegate.m、main.m、 ReactRouterNativeTests.m has wrong License declaration
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
There is only MIT License file  in the root directory of this source tree.

### Expected Behavior

React-router has MIT License，but 
v5.2.1/packages/react-router-native/ios/ReactRouterNative/AppDelegate.h
v5.2.1/packages/react-router-native/ios/ReactRouterNative/AppDelegate.m
v5.2.1/packages/react-router-native/ios/ReactRouterNative/main.m
v5.2.1/packages/react-router-native/ios/ReactRouterNativeTests/ReactRouterNativeTests.m
declare [BSD-3-Clause ]
 Facebook Additional Grant of Patent Rights Version 2. Which declaration need to be removed.

### Actual Behavior

There are some License which is not MIT License in the project.

**Comment by timdorr** [comment]
This is just boilerplate code for testing purposes, it's not part of the distributed code in react-router-native.

**Comment by tongle1** [comment]
> This is just boilerplate code for testing purposes, it's not part of the distributed code in react-router-native.

Thank you very much.
