### ISSUE TITLE
[Bug]: navigate replace state nests the replacing state `state` but search has been stripped out the top level

### ISSUE THREAD

**Issue by Jackbennett** [remix-run/react-router#8778]
### What version of React Router are you using?

react-router-dom@6.3.0

### Steps to Reproduce

Redirect from 

```javascript
const nav = useNavigation()
const loc = useLocation()

// protected route component

console.log(loc)
{
  hash: ""
  key: "default"
  pathname: "/demo/scripts"
  search: "?file=c5f16c7b-2f53-4982-84a1-f037c91a4fe2"
  state: null
}
const redirected = {
  ...loc,
  message: "Needed to login custom message"
}
return <Navigate replace to={"/login"} state={redirected} />;
```

Within the login component, do login then `navigate(next.pathname, { replace: true, state: next })` seems to be where the extra layer comes from.

Do I fundamentally misunderstand what `replace:true` is supposed to imply? It means my components can't `useSearchParams` because if the user has been bounced through a login then those params are empty (in the state layer below)

### Expected Behavior

```javascript
// navigation happens...
/// protected route component:
const loc = useLocation()

console.log(loc)
{
  hash: ""
  key: "2s2xuhxe"
  pathname: "/demo/scripts"
  search: "?file=c5f16c7b-2f53-4982-84a1-f037c91a4fe2"
  message: "Needed to login custom message"
  state: null
}
```

### Actual Behavior

```javascript
// navigation happens...
/// protected route component:
const loc = useLocation()

console.log(loc)
{
  hash: ""
  key: "2s2xuhxe"
  pathname: "/demo/scripts"
  search: ""
  state: {
    hash: ""
    key: "default"
    message: "No user"
    pathname: "/demo/scripts"
    search: "?file=c5f16c7b-2f53-4982-84a1-f037c91a4fe2"
    state: null
  }
}
```

**Comment by timdorr** [comment]
You should pass `navigate` the full location object, not just the pathname: `navigate(next, { replace: true, state: next })`

**Comment by Jackbennett** [comment]
My mistake, answer was in the type definitions all along, sorry about that.
