### ISSUE TITLE
[Feature]: Allow for non-route components and nested Routes as children to Route to facilitate animation inside a layout component.

### ISSUE THREAD

**Issue by Asghwor** [remix-run/react-router#8781]
### What is the new or updated feature that you are suggesting?

Allow non-route components and nested `Routes` to be put inside `Route` to facilitate the usage of animations only for the inner routes, without unmounting its parent route:

```tsx
export const AnimatedRoutes = () => {
  const location = useLocation();

  return (
    <Routes>
      <Route element={<Layout />}>
        <AnimatePresence exitBeforeEnter>
          <Routes location={location} key={location.pathname}>
            <Route path="/" element={<Home />} />
            <Route path="about" element={<About />} />
          </Routes>
        </AnimatePresence>
      </Route>
      {/* Other layouts here... */}
    </Routes>
  );
};
```

### Why should this feature be included?

I have a project where a few pages are under the same layout, having a sidebar and top-bar, something like this:

![image](https://user-images.githubusercontent.com/30949004/162354977-0ce62f7d-c766-4c52-8228-32612478c916.png)

Following the documentation for v6 and the documentation for animating pages, adapting them for Framer Motion, I did this:

```tsx
export const AnimatedRoutes = () => {
  const location = useLocation();

  return (
    <AnimatePresence exitBeforeEnter>
      <Routes location={location} key={location.pathname}>
        <Route element={<Layout />}>
          <Route path="/" element={<Home />} />
          <Route path="about" element={<About />} />
        </Route>
        {/* Other layouts here... */}
      </Routes>
    </AnimatePresence>
  );
};

```tsx
export const Home = () => {
  const pageMotion = {
    initial: { opacity: 0 },
    animate: { opacity: 1 },
    exit: { opacity: 0 }
  };

  return (
    <motion.div
      initial="initial"
      animate="animate"
      exit="exit"
      variants={pageMotion}
    >
      <div className="about">
        <div>home page</div>
        <Link to="/about">Go to about page</Link>
      </div>
    </motion.div>
  );
};
```

This, however, caused the whole layout to be remounted for some reason.

It would be great if we could do something like:

```tsx
export const AnimatedRoutes = () => {
  const location = useLocation();

  return (
    <Routes>
      <Route element={<Layout />}>
        <AnimatePresence exitBeforeEnter>
          <Routes location={location} key={location.pathname}>
            <Route path="/" element={<Home />} />
            <Route path="about" element={<About />} />
          </Routes>
        </AnimatePresence>
      </Route>
      {/* Other layouts here... */}
    </Routes>
  );
};
```

so only the animations within Layout got animated.

Making `<Route element={<Layout />}>` a wildcard wouldn't work because there could be other layouts in similar positions, and they aren't supposed to have different sub-routes.

**Comment by timdorr** [comment]
You would put this inside of your `Layout` component, not in your route tree.

**Comment by Asghwor** [comment]
@timdorr Do you mean, like this?

```tsx
<AnimatePresence exitBeforeEnter>
  <Outlet />
</AnimatePresence>
```

This doesn't seem to work, though.

**Comment by Asghwor** [comment]
@timdorr, I don't really think what I suggested can be done right now, given that I couldn't get any answers in any platform.

Are you really sure that this can already be done and that the issue should have been closed?

**Comment by skaltenegger** [comment]
@Asghwor have you been looking at [this example,](https://codesandbox.io/s/framer-motion-nested-routes-react-router-forked-kqmzse) which uses react-router v5? I worked on converting/upgrading it to use RRv6 and it seems to break the animated transitions. Any findings?

**Comment by shennan** [comment]
I'm really struggling with this issue right now and I think this should be opened again. I can't seem to get nested animated routes working without re-rendering the whole component tree (which breaks animations) or getting this error:

```
When overriding the location using `<Routes location>` or `useRoutes(routes, location)`, the location pathname must begin with the portion of the URL pathname that was matched by all parent routes. The current pathname base is "/a" but pathname "/b" was given in the `location` prop.
```

@timdorr seems to suggest that this can be done currently, but I don't think it can. There is a [discussion](https://github.com/remix-run/react-router/discussions/8008) here about animation in general, but it doesn't seem to address nested animated routes.
