### ISSUE TITLE
[Feature]: nested path and catch all routes

### ISSUE THREAD

**Issue by jdeniau** [remix-run/react-router#8783]
### What is the new or updated feature that you are suggesting?

Ignore the catch all routes when matching absolute routes.

### Why should this feature be included?

#7992 add the availability to declare absolute path for nested routes, this way we can do that : 

```js
const ROUTE_USER = '/users';
const ROUTE_USER_DETAIL = '/users/show/:id';
const ROUTE_USER_NEW = '/users/new';


<Route path={ROUTE_USER}>
  <Route path="" element={<UserList />} />
  <Route path={ROUTE_USER_DETAIL} element={<UserDetail />} />
  <Route path={ROUTE_USER_NEW} element={<UserNew />} />
</Route>
```

it's great, but if you do this:

```js
const ROUTE_USER = '/users';
const ROUTE_USER_DETAIL = '/users/show/:id';
const ROUTE_USER_NEW = '/users/new';


<Route path={ROUTE_USER}>
  <Route path="*" element={<UserWrapper />}>
    <Route path="" element={<UserList />} />
    <Route path={ROUTE_USER_DETAIL} element={<UserDetail />} />
    <Route path={ROUTE_USER_NEW} element={<UserNew />} />
  </Route>
</Route>
```

Then the following error is thrown:

>Absolute route path "/users/new" nested under path "/*" is not valid. An absolute child route path must start with the combined path of all its parent routes.

**Comment by timdorr** [comment]
Wildcards aren't intended for nested routes. They're for trailing segments to indicate acceptance of further nested URLs. You would get the same results with `path=""` or no `path` prop at all, but no error message.
