### ISSUE TITLE
[Bug]: HashRouter (v6.3) does not launch app on correct URL

### ISSUE THREAD

**Issue by pedrodlmatos** [remix-run/react-router#8790]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

The new version of react-router-dom, mainly the release 6.3.0, does not launch the application on the URL https://host:port/#/ when using a HashRouter.
Instead launches the application on URL https://host:port/ . 

I am working on a app that listens to the URL and if it does not contain the hash, it cannot match any route and does not render the components. 

I've created two codesandboxes that simulate the steps to reproduce the issue since it was necessary to change the versions and some of the code.

[react-router-dom v5.3.0](https://codesandbox.io/s/react-router-dom-v5-3-cro85z?file=/src/App.js)

[react-router-dom v6.3.0](https://codesandbox.io/s/9kbqfp?file=/src/App.js)

__Note:__ These codesandboxes are just dummy apps to show the issue. The one with version 6.3.0 works fine, including the redirects, even if the initial URL is not the desired one but the approach is not feasible in the real project.

### Expected Behavior

When using a HashRouter with the default properties, launch application on URL https://host:port/#/ .

![v5 3](https://user-images.githubusercontent.com/38213436/163006640-e04cffd9-4946-429f-ada9-90eb174334ab.PNG)

### Actual Behavior

When using a HashRouter with the default properties, the application launches on URL https://host:port/ .

![v6 3](https://user-images.githubusercontent.com/38213436/163007439-2302d7e6-39b6-43f6-89cd-388d5e12c6ac.PNG)

**Comment by lynnaeferguson** [comment]
Any movement on this? I'm having the same issue.

**Comment by brophdawg11** [comment]
I don't see this as any different from a router matching `http://domain.com` or `http://domain.com/`.  The lack of a hash + slash matches the root route the same as would `#/`.  If your application requires the hash be present in the browser URL bar, I would redirect if you detect this scenario:

```
const Routing = () => {
  let location = useLocation();

  // Ensure we always have a hash in the browser URL
  if (
    location.pathname + location.search + location.hash === "/" &&
    window.location.hash === ""
  ) {
    return <Navigate to="" replace={true} />;
  }

  ...
};
```

https://codesandbox.io/s/react-router-dom-v6-3-forked-zfw1kl
