### ISSUE TITLE
[Bug]: useNavigate reloads page when provided with complex state

### ISSUE THREAD

**Issue by ReeceXW** [remix-run/react-router#8792]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Create a set of routes

```
<Routes>
    <Route path="/"          element={<LoginForm />}/>
    <Route path="/reset"  element={<LoginResetPassword />} />
    <Route path="/mfa"    element={<LoginMultiFactor />} />
</Routes>
```

Pass some complex object, for example I used CognitoUser from amazon-cognito-identity-js.

In any route
`navigate("/login/mfa", { state: { SOME_OBJECT } });` 

### Expected Behavior

Navigate with state should navigate normally

### Actual Behavior

Navigate with state reloads the page during navigation

**Comment by timdorr** [comment]
You must only pass serializable objects to state, as per the HTML standard: https://html.spec.whatwg.org/multipage/history.html#serialized-state
