### ISSUE TITLE
[Bug]: Navigate to some route showing just blank page until I refresh the page

### ISSUE THREAD

**Issue by VovaK1** [remix-run/react-router#8798]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

```
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link} from 'react-router-dom';
import './App.css';
import CreatePost from './pages/CreatePost.jsx';
import Home from './pages/Home.jsx';

function App() {
  return (
    <div className="App">
      <Router>
          <Link to='/' >Home page</Link>
          <Link to='/createpost' >Create post page</Link>
        <Routes>
            <Route path='/' element={<Home />} />
            <Route path='/createpost' element={<CreatePost />} />
        </Routes>
      </Router>
    </div>
  );
}

export default App;
```

### Expected Behavior

When I click on _'Create post page'_ I expect to go to this route and see the **CreatePost** component.
Accordingly, when I click on _'Home page'_ I expect to go to the main route to see the **Home** component.

### Actual Behavior

Instead, when I click on _'Create post page'_ I change the route from **localhost:3000** to **localhost:3000/createpost** but I see just a blank page. I need to refresh the page to see the component. After refresh, I can click on _'Home page'_ and see the home component immediately.

**Comment by timdorr** [comment]
It sounds like something else is going on. Unless you can reproduce this on Codesandbox or StackBlitz, it looks to be a build setup or tooling issue.

**Comment by tayabsoomro** [comment]
I am having sort of similar issue, but when I click on `Link` component, I don't get a blank page, but just the same page it is currently on. The URL changes, but the content only changes until I refresh the page.

I am able to replicate it on [Codesandbox](https://codesandbox.io/s/upbeat-goldwasser-x5kve6)

Try the above link and try clicking on "About Us" or "Contact" while you're on  `/`. You'll notice that the AboutUsComponent doesn't render until you refresh the page, even though the URL in address bar has changed.

**Comment by shahankur32** [comment]
I am also facing the same issue.

**Comment by adhamhassan99** [comment]
facing the same issue here. Navigating to a specific route renders an empty page and when i check react dev tools it shows the parent element and no children elements. I will attach both examples. It happened to me when trying to Redirect a User suing `<Navigate to='/dashboard' replace/>` after successful login but it shows [this](https://drive.google.com/file/d/1UMpwp5mj2lTkhjTpzOSDHR1hu7_iaQgG/view?usp=sharing) .

however when i reach the url manually it shows normally like illustrated [here](https://drive.google.com/file/d/1L_X4MriYn8CbKTMwkJ5abRltIXLyOOWq/view?usp=sharing)

**Comment by Juliangzr** [comment]
Hello, i am having a very similar problem. 

CodeSandBox: https://codesandbox.io/s/practical-haslett-w3jkqg?file=/src/App.tsx

**Expected Behaivior** 
Navigate to login page it the url path is different than "/login".

**Actual Behavior:**
When the url path is different than "/login", it changes correctly the route, but renders a blank page. After that, If i refresh the page it works.
