### ISSUE TITLE
[Bug]: Incorrect release version?

### ISSUE THREAD

**Issue by morleytatro** [remix-run/react-router#8800]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Install the package locally.

### Expected Behavior

The latest release should be 6.3.1.

### Actual Behavior

The latest release is 5.3.1.

**Comment by maxbirimkulov** [comment]
+ i think it's a bug

**Comment by timdorr** [comment]
I've fixed this on npm now. The older automatic publishing system released the v5 branch under the `latest` dist-tag. I switched it back to 6.3.0 now.
