### ISSUE TITLE
[Bug]: Using a Monorepository doesn't work properly

### ISSUE THREAD

**Issue by Meierschlumpf** [remix-run/react-router#8801]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Open the command line and run the following commands
```
git clone https://github.com/Meierschlumpf/react-router-dom-issue.git
cd react-router-dom-issue
yarn
cd apps\example
yarn start
```
The React application should open on port 3000

### Expected Behavior

Both links, the one defined in the UI-Libary and the direct link in the example app should work.

HomePage in [apps/example/src/app/pages/home.tsx](https://github.com/Meierschlumpf/react-router-dom-issue/blob/main/apps/example/src/app/pages/home.tsx)
```tsx
import { UILink } from "@template/ui";
import { Link } from "react-router-dom";

export const HomePage = () => {
	return (
		<div>
			<h1>Home</h1>
			<UILink />
			{/*<Link to='/other'>Go to other Link</Link>*/}
		</div>
	);
};
```

UILink in [libs/ui/src/index.tsx](https://github.com/Meierschlumpf/react-router-dom-issue/blob/main/libs/ui/src/index.tsx)
```tsx
import { Link } from "react-router-dom";

export const UILink = () => {
	return <Link to='/other'>Go to other Page</Link>;
};
```

### Actual Behavior

Only the direct Link works. The Link that is used in the external libary throws the following errors:
![image](https://user-images.githubusercontent.com/63781622/163733388-f75657e7-45a1-4fe6-9a1f-22969a4423fa.png)

That is in my opinion a wrong behaviour as it should just render the link as normal.

**Comment by timdorr** [comment]
You likely have two copies of React Router included in your projects. This isn't a bug in React Router, but indicates a problem with your monorepo/build setup.

**Comment by Meierschlumpf** [comment]
Thanks god, thank you very much! I wouldn't been able to consider that fact. 🙏
