### ISSUE TITLE
[Feature]: Outlet component allows a generic type

### ISSUE THREAD

**Issue by LissetteIbnz** [remix-run/react-router#8803]
### What is the new or updated feature that you are suggesting?

I think it would be interesting to have a generic Outlet component.
Currently, we can use a context hook as generic props, but the Outlet component does not allow a generic type to pass props to the context provider.

Changing `components.tsx` file:

**components.tsx**

```diff
- export interface OutletProps {
-   context?: unknown;
+ export interface OutletProps<Context = unknown> {
+  context?: Context;
}

- export function Outlet(props: OutletProps): React.ReactElement | null {
+ export function Outlet<Context = unknown>(props: OutletProps<Context>): React.ReactElement | null {
  return useOutlet(props.context);
}
```

This way, we can use an Outlet component with infer types directly as follows:

```tsx
import * as React from "react";
import type { User } from "./types";
import { Outlet, useOutletContext } from "react-router-dom";

type ContextType = { user: User | null; updateUser: (user: User) => void; };

export default function Dashboard() {
  const [user, setUser] = React.useState<User | null>(null);

  return (
    <div>
      <h1>Dashboard</h1>
      <Outlet<ContextType> context={{ user, updateUser: setUser }} />
    </div>
  );
}

export function useUser() {
  return useOutletContext<ContextType>();
}
```

### Why should this feature be included?

I think this change improves the use of the library with TypeScript. It is a direct way to use a generic provider.

A sample

![generic-outlet-sample](https://user-images.githubusercontent.com/11260313/164205084-cd1f653d-3c9b-4da2-aac7-740f2b1d5c64.gif)

**Comment by timdorr** [comment]
TIL JSX elements can have generics!

This sounds like a decent idea. If you want to submit a PR, we can take a look at including it.

**Comment by LissetteIbnz** [comment]
Great! I'm going to do it 👍 
Thanks!

**Comment by brophdawg11** [comment]
I'm going to close this out since a preferred approach was outlined in the above PR
