### ISSUE TITLE
[Bug]: Prompt firing when submitting with React 18

### ISSUE THREAD

**Issue by TrySpace** [remix-run/react-router#8804]
### What version of React Router are you using?

5.3.1

### Steps to Reproduce

```tsx
 ...
 <Prompt
   when={dirty}
   message={() =>
   `You have unsaved changes, sure you want to go to leave this page? `
  }
 />
```

This doesn't work either (but I don't know if it should)

```tsx
 const hasAnyValue = !!(values.title || values.text)
 ...

 <Prompt
   when={hasAnyValue && !submitting}
   message={() =>
   `You have unsaved changes, sure you want to go to leave this page? `
  }
 />
```

### Expected Behavior

I expected this to only Prompt when I navigate away, not when I submit the form.

### Actual Behavior

This will show a prompt when I submit the form. 

Previously, using `when={dirty}` would have been enough. 

Something changed with react 18, I reverted to `17.0.2` and it was fixed...

**Comment by Kost927** [comment]
@TrySpace I set submitting to useRef(false) and when running submit function rewrite submitting.current to true. That helped me.

**Comment by DercilioFontes** [comment]
I used this example, and it works fine.
https://michaelchan-13570.medium.com/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39
