### ISSUE TITLE
[Bug]: Nested not match route not working

### ISSUE THREAD

**Issue by hadson172** [remix-run/react-router#8808]
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

My route looks like this:

```
      <BrowserRouter>
        <Header />
        <Routes>
          <Route path="/data" element={<Data/>}>
            <Route path="*" element={<SomeComponent/>} />
          </Route>
        </Routes>
      </BrowserRouter>
```

### Expected Behavior

I would expect that if i go to the both urls: `/data` and` /data/something` I will see the `<SomeComponent/>` but this not the case.

I know that i can do something like this:
```
 <Route path="/data" element={<Data/>}>
            <Route index element={<SomeComponent/>} />
            <Route path=":id" element={<SomeComponent/>} />
 </Route>
```

But this will mount and unmount my component on each route change between `/data` and `/data/something` which i dont want

### Actual Behavior

```
I have to chose between either not to using react router or agree with duplicated mounting of component
```

**Comment by timdorr** [comment]
This is not the actual behavior. Nor is this the expected actual behavior. You're rendering the same component tree between routes, so React itself will re-use the same component instances to render them. I've also verified this in a test project.

If something is causing this, it's not a part of the listed code.
