### ISSUE TITLE
[Bug]: forceRefresh is not possible after upgrading to v6

### ISSUE THREAD

**Issue by anark** [remix-run/react-router#8812]
### What version of React Router are you using?

6.3

### Steps to Reproduce

Use the `forceRefresh` parameter on `BrowserRouter`

### Expected Behavior

When navigating to a different route the page should refresh the same way it did when using react router v5

### Actual Behavior

The page does not refresh.  `forceRefresh` prop has no effect when using v6

**Comment by timdorr** [comment]
This is not a feature implemented in v6.

**Comment by anark** [comment]
I understand that it is not there now, however it was available in v5.  Are there any plans to re-add this or is this deprecated for the time being?

I know there is a todo in the history library for this https://github.com/remix-run/history/blob/8bef6f4d50548f46ab7c97e171b3d8634093e7a7/packages/history/index.ts#L489 and it was requested before via https://github.com/remix-run/react-router/issues/8242, but there has been no progress or information and all the issues are closed.

If this is not going to be added to re-added to v6 it would be good to know so we can attempt a different approach

**Comment by jitendra-gosavi** [comment]
Yes, I am also curious to know how I can achieve this functionality in v6 similar to `forceRefresh` in v5. I want to reload the page on route change.

**Comment by nhhabc** [comment]
you can use "reloadDocument" instead

**Comment by uKiJo** [comment]
`export const useReload = () => {
  const navigate = useNavigate();
  // const history = useHistory();
  const location = useLocation();
  useEffect(() => {
    navigate(location.pathname);
  }, [navigate, location]);
};
`

**Comment by uKiJo** [comment]
`
export const useReload = () => {
  const navigate = useNavigate();
  // const history = useHistory();
  const location = useLocation();
  useEffect(() => {
    navigate(location.pathname);
  }, [navigate, location]);
};

`

**Comment by uKiJo** [comment]
```
export const useReload = () => {
  const navigate = useNavigate();
  const location = useLocation();
  useEffect(() => {
    navigate(location.pathname);
  }, [navigate, location]);
};
```

**Comment by AjithPG** [comment]
You can use <Link reloadDocument> to skip client side routing and let the browser handle the transition normally (as if it were an <a href>).
it's working for me

**Comment by idembele70** [comment]
Hi everyone, i found a solution may it help you: https://stackoverflow.com/a/73415351/14516628
There you have the current Link component documentation : https://reactrouter.com/en/6.8.1/components/link
