### ISSUE TITLE
[Feature]: Providing Routing Data and Functions Through Props for Class-Based Components in React Router

### ISSUE THREAD

**Issue by Code-Mythos** [remix-run/react-router#8813]
### What is the new or updated feature that you are suggesting?

# Supporting Class Components in V7.0.0
Providing Routing Data and Functions Through Props for Class-Based Components

### Why should this feature be included?

#  Providing Routing Data and Functions Through Props for Class-Based Components
## Why Class-Based Components?
Many applications over the network are implemented using class concepts. And obviously, classes provide some considerable additional functionality to the applications. Then it is crystal clear that there are and there will be applications with classes.

## [Existing Wrapping Solution for Classes](https://reactrouter.com/docs/en/v6/faq)
While there is a way to add the functionality of hooks to the classes by wrapping the original component with a function, there is a strong controversy against it because it is against the clean coding concepts.

## Props for both _Class_ and _Functional_ Components
Providing data and functions through props is a capability for both Class and Functional Components. With this approach, instead of importing Hooks separately through the import statements, we can directly implement and perform them within a function. Indeed props and hooks can live alongside each other like what is implemented in react library.

### Considering what is mentioned above, supporting class components will be a great functionality for all developers in the upcoming version of React Router.

Best regards.

**Comment by timdorr** [comment]
Thanks, but we're moving towards function components and hooks like React itself is doing.

**Comment by Code-Mythos** [comment]
Thank you for your reply.
However, as mentioned in react official documentation, they do not get rid of classes, but they want to provide similar functionality for functional components:

“We intend for Hooks to cover all existing use cases for classes, but we will keep supporting class components for the foreseeable future. 
### At Facebook, we have tens of thousands of components written as classes, and we have absolutely no plans to rewrite them.
Instead, we are starting to use Hooks in the new code side by side with classes.”

To add more to what they have stated, it is logical to expect in the near future, more existing browsers will support ES7 and even newer standards. And I'm sure you know classes in newer standards provide even more improvement, which not only introduces additional functionality but also eases programming for developers.

Please consider my request and discuss it with the other main team developers.
