### ISSUE TITLE
[Bug]: SSR example

### ISSUE THREAD

**Issue by Moraiene** [remix-run/react-router#8815]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Build SSR example and start production version.

### Expected Behavior

The "Home" page must be rendered on the server.

### Actual Behavior

"Home" page not rendering by server.

**Comment by timdorr** [comment]
It's working just fine in StackBlitz: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/ssr?file=src/App.tsx
