### ISSUE TITLE
[Bug]: Router inside a Router unavailable

### ISSUE THREAD

**Issue by fecheromero** [remix-run/react-router#8817]
### What version of React Router are you using?

v6

### Steps to Reproduce

Use a MemoryRouter inside a Router

### Expected Behavior

You can model a structure with deep linking  between some pages and memory routes (without change the URL) between some others.

### Actual Behavior

Error: [You cannot render a `<Router>` inside another `<Router>`]

**Comment by gbiryukov** [comment]
is there chance to reconsider this one? `MemoryRouter` inside `BrowserRouter` is really useful for wizard-like UI when all stages should stay on the same url like complex form
