### ISSUE TITLE
[Feature]: Allow users to animate nested routes without affecting container.

### ISSUE THREAD

**Issue by Asghwor** [remix-run/react-router#8818]
### What is the new or updated feature that you are suggesting?

Allowing the user to animate / update a nested route without affecting the parent element.

Allowing components other than Route or Routes might be needed.

It would work something like this:

```tsx
export const AnimatedRoutes = () => {
  const location = useLocation();

  return (
    <Routes>
      <Route element={<Layout />}>
        <AnimatePresence exitBeforeEnter>
          <Routes location={location} key={location.pathname}>
            <Route path="/" element={<Home />} />
            <Route path="about" element={<About />} />
          </Routes>
        </AnimatePresence>
      </Route>
      {/* Other layouts here... */}
    </Routes>
  );
};
```

### Why should this feature be included?

So that a containing component, which might have logic and state of its own, doesn't get reset every time the route is changed.

### Other info

[demo on an example that reloads the containing element](https://codesandbox.io/s/react-router-v6-forked-3z1h4w)

I opened this second issue because the [first one](https://github.com/remix-run/react-router/issues/8781) was closed without an explanation on how this can be achieved, if it's already implemented, or if it wouldn't be implemented at all.

I'm sure many people might want to do the same thing I do, so having an answer on this subject would help us to know if we should give up, wait or if there is a way to do this.

**Comment by timdorr** [comment]
This is already being discussed in #8008

**Comment by shennan** [comment]
I believe this needs to be re-opened. There doesn't currently seem to be a way of animating nested routes. You can animate the main route, but if you attempt to animate nested routes (using `<Routes location={location}/>` the entire tree is re-rendered or errors are thrown when switching between parent routes.

Nested animated routes are not discussed in the [aforementioned discussion](https://github.com/remix-run/react-router/discussions/8008).
