### ISSUE TITLE
[Bug]: passing function in navigate's state causes full page reload

### ISSUE THREAD

**Issue by MikolajMGT** [remix-run/react-router#8820]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Navigate programmatically to some page and pass any function in the state:

```
navigate('/info', {
	state: {
		message: 'some msg',
		action: () => { return 'test'}
	}
});
```

### Expected Behavior

Router navigates to the page without full browser's refresh

### Actual Behavior

Router navigates to the page with full browser's refresh. It works fine without passing a function in state, but when you do so, router performs full refresh, and all state get lost

**Comment by timdorr** [comment]
You can only put serializable entries into state. A function is not serializable, so this is not supported.
