### ISSUE TITLE
[Bug]: History convert weird urls

### ISSUE THREAD

**Issue by BiancaArtola** [remix-run/react-router#8821]
### What version of React Router are you using?

5.3.0

### Steps to Reproduce

```
import { useHistory } from "react-router-dom";

const Container: React.FC = () => {
  const history = useHistory();

  useEffect(() => {
      const test = url(encodeURIComponent(selectedOption?.name!)); // The result of this is  /provisioning/device/AutomatedTest_-()%3A.%2C%2B%3D%40*%2F%5C%3B637311263053095415
      history.push(test);
    }
  }, []);
.. 
}

```

### Expected Behavior

The expected url is _/provisioning/device/AutomatedTest_-()%3A.%2C%2B%3D%40*%2F%5C%3B637311263053095415_

### Actual Behavior

Received URL: _/provisioning/device/AutomatedTest_-()%3A.%2C%2B%3D%40*%2F/%3B637311263053095415_

The issue is that the `history` converts in some way the received sting and put it a `/` that breaks my URL

**Comment by timdorr** [comment]
This is a known issue in the `history` library: https://github.com/remix-run/history/issues/505
