### ISSUE TITLE
[Bug]: <Link> Usage causing an unexpected refresh

### ISSUE THREAD

**Issue by bobber205** [remix-run/react-router#8822]
### What version of React Router are you using?

5.2.1 (also tried 5.3.1)

### Steps to Reproduce

I have this function that clears some cookies then navigates using history.push()

```js
    const go_to_beta = function () {
        myStorage.setItem('draft_dm_text', '');
        myStorage.setItem('dm_link_saved', null);
        myStorage.setItem('draft_dm_title', '');
        myStorage.setItem('dm_only_text_saved', '');
        myStorage.setItem('savedEditorContents', '');
        myStorage.setItem('saved_selected_image_data', '');
        myStorage.setItem('draft_dm_image', '');
        history.push("/dashboard/posts/new");
    }
```
This causes a refresh at the same time the view is changed to `/dashboard/posts/new`

```js
<Link onClick={go_to_beta} className="btn btn-success btn-sm"><i className="fas fa-plus-square"></i> New</Link>
```
So does this (avoiding calling the function at all)

```js
<Link to="/dashboard/posts/new" className="btn btn-success btn-sm"><i className="fas fa-plus-square"></i> New</Link>
```

I think it's tied to my usage of <Link> because this works as intended.

```js
<Button onClick={go_to_beta} className="btn btn-success btn-sm"><i className="fas fa-plus-square"></i> New</Button>
```

I've tried as specified above 5.2.1, 5.3.0 and 5.3.1

What could be causing this? We just noticed it started a few days ago and are anxious to fix it but I'm not sure what to do.

### Expected Behavior

Shouldn't refresh the page

### Actual Behavior

Any usage of <Link> refreshes the page, even without a `to` property or `onClick` property attached.

**Comment by dmccarey** [comment]
Experiencing the same issue for a few days.

```
5.1.2 / React 16.12.0
```

**Comment by timdorr** [comment]
Can you create a reproduction on StackBlitz or somewhere else?

**Comment by microlabig** [comment]
Similar behavior
```
react-router 5.1.2, React 16.10.2
```

**Comment by AndyMeps** [comment]
Same issue here on an older version of `react-router` / `react`, I'm trying to put together a StackBlitz but so far not able to reproduce with the basic react-router example (https://v5.reactrouter.com/web/example/basic)

`react-router 4.3.1, React 16.8.6`

**Comment by dmccarey** [comment]
> Experiencing the same issue for a few days.
> 
> ```
> 5.1.2 / React 16.12.0
> ```

Interesting that I only see this in Chrome, not Safari.

**Comment by AndyMeps** [comment]
> > Experiencing the same issue for a few days.
> > ```
> > 5.1.2 / React 16.12.0
> > ```
> 
> Interesting that I only see this in Chrome, not Safari.

Just tried on Safari and can still reproduce the issue on our hosted website. I've given up trying to reproduce the issue in StackBlitz, I also created in a new app locally and that worked fine too. I also tried upgrading to 5.1.0 from 4.3.1 and still had the issue.

Very confusing.

**Comment by bobber205** [comment]
> > Experiencing the same issue for a few days.
> > ```
> > 5.1.2 / React 16.12.0
> > ```
> 
> Interesting that I only see this in Chrome, not Safari.

I've seen it so far in Chrome and Firefox. I'll have to try Safari!

**Comment by mwjaco** [comment]
```
3.2.4 / React 16.11.6
```
My stack is on a much older version of `react-router` so I was surprised to see the exact same issue described here. But like @AndyMeps said, I removed Google Tag Manager and the issue went away.

**Comment by bobber205** [comment]
> ```
> 3.2.4 / React 16.11.6
> ```
> 
> My stack is on a much older version of `react-router` so I was surprised to see the exact same issue described here. But like @AndyMeps said, I disabled Google Tag Manager (specifically the [`react-gtm` module](https://github.com/alinemorelli/react-gtm) and the issue went away.

Fixed it for me too! Crazy -- hoping to keep this open for awhile for visibility.

**Comment by bobber205** [comment]
Anyone know if this is worth reporting to Google?

**Comment by mwjaco** [comment]
@bobber205 [I posted about this issue in the Tag Manager Help community](https://support.google.com/tagmanager/thread/161637068?hl=en). Please feel free to upvote/reply

**Comment by AndyMeps** [comment]
> @bobber205 I don't know if this was the quickest way to get a response, but [I posted about this issue in the Tag Manager Help community](https://support.google.com/tagmanager/thread/161637068?hl=en). Please feel free to upvote/reply

Upvoted, thanks for raising; I wasn’t sure where to raise it either.

**Comment by bobber205** [comment]
Updated -- I'm gonna mark this as closed and fixed because afaik it is.

**Comment by bobber205** [comment]
@khani3s Agreed -- I noticed that the history hook (`useHistory`) and calling `push()` doesn't cause the same conflict with GTM

**Comment by williamkehl** [comment]
Also suffering from this issue the past week. Multiple searches led me here.  
`react-router-dom 5.1.2` with manually inserted GTM code. We're suspecting that it's caused by a global 'History Change' trigger in GTM.

**Comment by yarl** [comment]
Does anyone know if this is related to OS? We see similar behaviour on Chrome + Windows users, we are not able to reproduce it on Chrome + macOS.

**Comment by bobber205** [comment]
Yeah I was experiencing it on all platforms including Phones

**Comment by aabuhijleh** [comment]
Still facing the same GTM full page load issue in 2023 with the latest React Router v6.

Is there any specfic trigger casuing this issue?

**Comment by aabuhijleh** [comment]
Google locked the [original community post](https://support.google.com/tagmanager/thread/220921856?hl=en) without providing any explanation or discussion. I reported the issue in a [new post here](https://support.google.com/tagmanager/thread/220921856?hl=en)

**Comment by caweidmann** [comment]
> Still facing the same GTM full page load issue in 2023 with the latest React Router v6.
> 
> Is there any specfic trigger casuing this issue?

Same issue here. What resolved it for me was to go into Google Tag Manager and under "Triggers" modify all the triggers of the type "Just Links" and uncheck the "**Wait for Tags**" checkbox.

<img width="361" alt="GTM" src="https://github.com/remix-run/react-router/assets/1684894/4c77978b-3d42-4cf9-a224-33c9b8bb2f15">
