### ISSUE TITLE
[Bug]: 建议react-router-dom v6版本在android百度浏览器最新版上使用一下，会出现history.length>2时，无法跳转

### ISSUE THREAD

**Issue by Vickshine** [remix-run/react-router#8823]
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

页面层级超过2层时，页面无法再跳转，在android百度浏览器(下载量最多的，注意别下载错误，有三个百度浏览器app呢)最新版

### Expected Behavior

页面可以跳转成功

### Actual Behavior

实际无法跳转成功，只有使用{replace:true}每个页面跳转下个页面重置路由才可以跳转成功。{replace:false}则无法跳转成功

**Comment by Grs24** [comment]
why close?

**Comment by zhaoxuxin** [comment]
如何解决百度浏览器无法跳转
