### ISSUE TITLE
[Feature]: Incoming post requests 

### ISSUE THREAD

**Issue by bymustfa** [remix-run/react-router#8833]
### What is the new or updated feature that you are suggesting?

Capturing incoming post requests and payload data.
It makes things very easy especially for virtual pos integrations.
Ex:
`<Route type="post" path="checokout-price" component={Price} />
`

### Why should this feature be included?

Especially when using a third-party application, many of these applications return post requests and it is impossible to catch this with the existing features.

**Comment by timdorr** [comment]
React Router is a client-side router. It has no concept of a request type. This would be handled by whatever server framework you have.
