### ISSUE TITLE
[Bug]: reactrouter.com throws exception in Safari 13.1

### ISSUE THREAD

**Issue by anddoutoi** [remix-run/react-router#8836]
### What version of React Router are you using?

N/A

### Steps to Reproduce

Go to [reactrouter.com](https://reactrouter.com) using Safari 13.1.

### Expected Behavior

The page should load without error.

### Actual Behavior

<img width="1098" alt="Screenshot 2022-05-03 at 09 40 53" src="https://user-images.githubusercontent.com/204784/166422085-58110852-a6dd-407b-988a-87a5490caa67.png">

**Comment by timdorr** [comment]
Sorry, but that's a very old version of Safari and isn't supported.
