### ISSUE TITLE
[Bug]: navigate(/same-route) not re-rendering as V5

### ISSUE THREAD

**Issue by mskzo** [remix-run/react-router#8849]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Programmatically call navigate (using useNavigate) with the same current route at the first parameter.

### Expected Behavior

In V5 the component is remounted and mounted,

### Actual Behavior

Not remounting.  Only location.key is changing

**Comment by timdorr** [comment]
This isn't the expected behavior of either v5 or v6. It's how React itself is supposed to work. If you render the same component tree, it will re-use the same component instances between renders.
