### ISSUE TITLE
[Feature]: react-router to work with react-native-screens

### ISSUE THREAD

**Issue by veeramarni** [remix-run/react-router#8856]
### What is the new or updated feature that you are suggesting?

Will there be support for `react-native-screens` to work with multiple screens rendered at the same time for switching tabs and navigation between next and back screens? In another word, can you build an alternative to `react-navigation` using `react-router-native`?

### Why should this feature be included?

without this feature, all users are forced to use two different methods for rendering routes. In web react-router and in mobile most are using react-navigation. If we could support mobile with react-native-screens then we have a champion

**Comment by timdorr** [comment]
We're not planning on integrating directly with external libraries. That is up to other library authors or the user to implement.
