### ISSUE TITLE
[Bug]: excessive invariant that breaks an option for GitHub-like preloading 

### ISSUE THREAD

**Issue by jayarjo** [remix-run/react-router#8858]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Put a non Route component under Routes.

### Expected Behavior

Nothing.

### Actual Behavior

An [exception is thrown](https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/components.tsx#L291): 

 `...not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>`

What exactly does this invariant guard? What bad can happen if a child component will be composed on top of  `<Route>`?

We used to compose our ProtectedRoute on top of the Route component and this is now impossible. But while in this case there's a workaround, the logic for [GitHub-like page preloader](https://www.npmjs.com/package/react-router-loading) seems to be irreversibly broken. That library (e.g. react-router-loading) is React Router version 5 based, however [I now refactored it to be compatible with React Router 6](https://github.com/jayarjo/react-router-loading/pull/1), but that single invariant, breaks the whole thing.

Any ideas on how to implement something like this, without dropping above mentioned exception?

![example](https://user-images.githubusercontent.com/150075/167878725-39278d90-e40c-4ac1-93c2-881d9c1724e0.gif)

**Comment by timdorr** [comment]
This is intentional. You can only use `<Route>` under the `<Routes>` component. This is explained here: https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f

**Comment by humanchimp** [comment]
in my opinion, using nominal typing like this goes against the grain of javascript. If i pass an object that is indistinguishable other than, it came from a different factory, it should still work in place of whatever the library expects. as written, i have to put the authorization check in the outer component, where it doesn't belong. it's forcing me to write bad code. Can we please switch to duck-typing instead? I will write the PR
