### ISSUE TITLE
[Bug]: navigate(-1) Returns to the Google homepage

### ISSUE THREAD

**Issue by ashuvax** [remix-run/react-router#8859]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

https://codesandbox.io/s/laughing-blackwell-t296ko?file=/src/App.js

### Expected Behavior

Stay on site without being thrown out
Maybe we can check if navigate (-1); Worth something that will pass and if not pass to the main page

### Actual Behavior

When I run the code and enter my site then as soon as I click on repeat the site throws me out

**Comment by timdorr** [comment]
This is a security thing that the browsers prevent. We can't know what's on the history stack outside of our own page.

**Comment by ashuvax** [comment]
@timdorr 
Do you have another solution for me?
