### ISSUE TITLE
[Bug]: Link component does not render the component until after reload

### ISSUE THREAD

**Issue by tayabsoomro** [remix-run/react-router#8863]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

I created a basic react project with react-router with routes for `/about` and `/contact`. Then I create `Link` components which points to these above routes. When the `Link` component is clicked, I do not see the component render, only the URL address bar changes. Here's the [Codesandbox](https://codesandbox.io/s/upbeat-goldwasser-x5kve6)

### Expected Behavior

I would expect when I click on "About Us" that it would render the AboutUsComponent.

### Actual Behavior

The URL changes but the component does not render.

**Comment by timdorr** [comment]
Duplicate of #7870

**Comment by Pecl-orlando** [comment]
@timdorr https://vaultedproduction43.github.io/cxml/
