### ISSUE TITLE
[Bug]: useRouteMatch returning null when two parameters are in path but only one matched

### ISSUE THREAD

**Issue by DaliborTrampota** [remix-run/react-router#8870]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

```js

function blogs(){
const params = useRouteMatch({
        path: '/blogs/:category/:id',
        exact: false,
        strict: false
    })
    console.log(params)

    return (
        <>
            <Route path="/blogs" exact={true} render={(props) => <BlogCategories blogs={blogs} categories={categories} {...props} />} />  
            <Route path="/blogs/:category" exact={true} render={(props) => <BlogCategory blogs={getCategoryPosts(params.category)} {...props} />} />
            <Route path="/blogs/:category/:id" exact={true} render={(props) => <BlogPost blog={getPost(params)} {...props} />} />
        </>
    )
}
```

and go to path /blogs/someCategoryName (without the id param)

### Expected Behavior

when on /blogs/categoryName it should return the matched category parameter
when on /blogs/categoryName/someID it returns the matched category and id parameter correctly 

### Actual Behavior

when on /blogs/categoryName it should returns null

**Comment by timdorr** [comment]
You need to mark the `id` param as optional: `/:id?`

**Comment by DaliborTrampota** [comment]
I upgraded to v6 and now its not working at app

const matchCat = useMatch({ path: '/blogs/:category' })
    const matchID = useMatch({ path: '/blogs/:category/:id' })
    const fullMatch = useMatch({ path: '/blogs/:category/:id?' })
    console.log('cat', matchCat)
    console.log('id', matchID)
    console.log('full', fullMatch)
    console.log('loc', useLocation())
    
    
![image](https://user-images.githubusercontent.com/31895316/168677133-8c28eeda-737f-4aac-9904-ecb3e58591be.png)
