### ISSUE TITLE
[Feature]: Add a `handle` or `meta` property to RouteObject type

### ISSUE THREAD

**Issue by airjp73** [remix-run/react-router#8871]
### What is the new or updated feature that you are suggesting?

It would be nice to have first-class support for a `handle` or `meta` in the `RouteObject` type that you can leverage with `matchRoutes`. Adding properties to the route config already works, but it would be nice it would be nice to have it codified in the types somehow.

A common use-case would be implementing breadcrumbs remix-style.

### Current situation

This already works, but requires type casting

```tsx
// Declaring custom route type
interface FooRoute extends Omit<RouteObject, 'children'> {
  handle?: { foo?: string },
  children?: FooRoute[]
};

const myRoutes: FooRoute[] = [
  {
    path: '/home',
    element: <h1>Home</h1>,
    handle: { foo: 'bar' }
  },
  {
    path: '/anotherPage',
    element: <h1>Another page</h1>,
    handle: { foo: 'somethingElse' }
  },
]

const foos = matchRoutes(myRoutes, location)
  .map(match => {
    // matchRoutes sees the route as a plain `RouteObject`
    // The properties are all still there, but we need to cast it to get at them
    return (match.route as FooRoute).handle?.foo;
  })
```

### Suggested changes

These are just ideas. I'd say any version of a feature that lets me do this is A-Okay to me :+1:.

There are two key utils for this feature, I think.

#### Type helper to declare custom routes

```tsx
import { RouteWithHandle } from 'react-router-dom';

// A generic helper to declare route objects with a custom handle type.
type FooRoute = RouteWithHandle<{
  foo?: string;
}>;

// MyRoutes is equivalent to
interface FooRoute extends Omit<RouteObject, 'children'> {
  handle?: { foo?: string },
  children?: FooRoute[]
};
```

#### `matchRoutes` infers type of route object

```tsx
const matches = matchRoutes(fooRoutes, location)
  .map(match => {
    // match.route is correctly inferred to be a `FooRoute`
    return match.route.handle.foo;
  });
```

### Why should this feature be included?

I think this fits right in with the "Remixing React Router" stuff Ryan talks about in [this blog post](https://remix.run/blog/remixing-react-router). After using [useMatches](https://remix.run/docs/en/v1/api/remix#usematches) from remix, it's hard to go back haha.

Since this is purely a change in the types themselves and doesn't risk breaking any actual behavior. I believe this type change can be made in a backwards compatible way as well.

While this technically works today, it's helpful to have it codified in the type system. If the contract of `matchRoutes` doesn't return the enhanced properties, then there's no guarantee that this behavior is intentional or desired. And relying on undefined behavior is dangerous.

**Comment by timdorr** [comment]
This is coming in #8855, so just wait for that release.

**Comment by airjp73** [comment]
Awesome, thanks! I guess I didn't look hard enough at the PRs 😁.

**Comment by vincerubinetti** [comment]
Any update on this? That PR was closed and it doesn't mention where the "newly rebased branch" is.

**Comment by timdorr** [comment]
This was added in 6.4: https://reactrouter.com/en/main/route/route#type-declaration

**Comment by JoshWhiteTTD** [comment]
Please could you give an example of how to define the shape of the `handle` property? To me, it's not clear in the Docs.
