### ISSUE TITLE
[Bug]: Failing to match special characters to the «*» default route

### ISSUE THREAD

**Issue by 0razzu** [remix-run/react-router#8873]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Run any code containing `<Route path="*" element={<DefaultComponent />} />` like this one:
```
createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <BrowserRouter>
            <Routes>
                <Route element={<App />}>
                    <Route index element={<AppIndex />} />
                    <Route path="path1" element={<Component1 />} />
                    <Route path="*" element={<NoSuchPage />} />
                </Route>
            </Routes>
        </BrowserRouter>
    </React.StrictMode>
)
```

Then try to access `/;`, `/:`, `/!`, `/(`, etc.

### Expected Behavior

The default component is rendered. `<NoSuchPage />` in my example.

### Actual Behavior

A blank #root-only page is rendered and a console warning like this one: `No routes matched location "/)"` is shown.

**Comment by timdorr** [comment]
Those characters aren't allowed in URIs, as per [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) (section 2.3)
