### ISSUE TITLE
[Bug]: NavLink with trailing slash doesn't stay active on child routes

### ISSUE THREAD

**Issue by PoByBolek** [remix-run/react-router#8874]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

This is somewhat related to #8724.

1. Create a `<NavLink>` whose `to` prop has a trailing slash, e.g. `<NavLink to="issues/">Issue</NavLink>`.
2. Click on that link and observe how it becomes active.
3. Click on another link that navigates to a child route, e.g. `issues/details/` and observe how the `NavLink` becomes inactive again.

### Expected Behavior

The `NavLink` should be active for all child locations. This used to be the case in v5 (see [Codepen using ReactRouter v5](https://codepen.io/PoByBolek/pen/xxYgqoo)).

### Actual Behavior

The `NavLink` is only active when the current location exactly matches its `to` prop (see [Codepen using ReactRouter v6](https://codepen.io/PoByBolek/pen/KKQaWEo)).

**Comment by timdorr** [comment]
My comment in the linked issue still applies here. This isn't a bug.

https://github.com/remix-run/react-router/issues/8724#issuecomment-1073171819

**Comment by PoByBolek** [comment]
So the bug was in v5 then?

And although, yes, `some/path` and `some/path/` are different paths, I would still argue that `some/path/further/down` is a child path of *both* the former paths and so both `NavLink`s should become active in my opinion...

I'm just trying to understand the reasoning behind your comment. Are you saying that `some/path/` is really `some/path/<empty>`, which should be considered a *sibling* of `some/path/further` and so can't be a *parent* of `some/path/further/down`? That is

```mermaid
graph TD;
    some_(some/)
    some_path(some/path)
    some_path_(some/path/)
    some_path_further(some/path/further)
    some_path_further_(some/path/further/)
    some_path_further_down(some/path/further/down)

    some --> some_
    some --> some_path
    some_path --> some_path_
    some_path --> some_path_further
    some_path_further --> some_path_further_
    some_path_further --> some_path_further_down
```
