### ISSUE TITLE
[Bug]: After Redirect, the useLocation location.pathname value is the previous value 

### ISSUE THREAD

**Issue by PaddyWang** [remix-run/react-router#8878]
### What version of React Router are you using?

5.2.0

### Steps to Reproduce

\<Redirect exact from="/" to="/test" />
When you route to '/', it redirects to '/test'
`useLocation` is then used on the component
`const location = useLocation()`

### Expected Behavior

The `pathname` on the `location` object should be the `pathname` of the current URL '/test'

### Actual Behavior

`location.pathname` is equal to the '/', But when you refresh the page, it's equal to the '/test'

**Comment by timdorr** [comment]
Can you show an example on CodeSandbox or StackBlitz?

**Comment by Meet09** [comment]
I am also facing similar issue, if anyone found any solution please share!!

**Comment by timdorr** [comment]
We need an example. Just saying this is happening isn't helpful without some code to reproduce it.

**Comment by PaddyWang** [comment]
> We need an example. Just saying this is happening isn't helpful without some code to reproduce it.

Ok, I'm still prepare on it. Due to my network problem, I failed to create the example last night. I will paste the link after creating the example, please wait patiently.

**Comment by PaddyWang** [comment]
When I creating the example, I found that the problem was caused by the useEffect without any dependency.
