### ISSUE TITLE
[Bug]: React-router 5.3.2 has broken dependencies which leads to crashes at runtime

### ISSUE THREAD

**Issue by f-roland** [remix-run/react-router#8880]
### What version of React Router are you using?

5.3.2

### Steps to Reproduce

React native app on RN 0.62.2, React 16.11.0, using react-router@5.3.2

The app crashes on launch because react-router-native is referencing react-router@2, which uses React.PropTypes (removed from React 15.5 I believe - react-router@2 uses react@15)

https://github.com/remix-run/react-router/blob/1a69e8a84675f9d1a60e0fe2569b7bcbd5775045/packages/react-router-native/package.json#L35

I'm not sure how this came up in the release process as the PR which triggered the publish didn't make this change to the package.json

but when an app uses react-router-native@5.3.2, this shows up in the lock file
<img width="288" alt="image" src="https://user-images.githubusercontent.com/15126070/169054574-3df38a4b-668c-4aec-8b02-334647284701.png">

and then this
<img width="455" alt="image" src="https://user-images.githubusercontent.com/15126070/169054727-f42b1684-259a-4552-99b3-71b0666e2515.png">

### Expected Behavior

version has correct dependencies and doesn't crash

### Actual Behavior

app crashes on launch

**Comment by timdorr** [comment]
I made a typo. Pushing out 5.3.3 now!
