### ISSUE TITLE
[Bug]: Parent page's NavLink not being active if trailing slashes are used.

### ISSUE THREAD

**Issue by rafalp** [remix-run/react-router#8884]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Given routes with following paths:

1. `/page/`
2. `/page/subpage/`

And navlinks:

```tsx
<NavLink to="/page/">Page</NavLink>
<NavLink to="/page/subpage/">Subpage</NavLink>
```

Repro: https://stackblitz.com/edit/github-363lsk?file=src%2FApp.tsx

### Expected Behavior

If user is on `/page/` path, "Page" link is active, but when they navigate to `/page/subpage/`, both nav links should be active.

<img width="440" alt="Zrzut ekranu 2022-05-19 o 23 13 34" src="https://user-images.githubusercontent.com/750553/169406939-36023f75-6fad-49f8-a355-45518cc9c56a.png">

### Actual Behavior

If user is on `/page/` path, "Page" link is active, but when they navigate to "Subpage", only `/page/subpage/` link is active.

<img width="109" alt="Zrzut ekranu 2022-05-19 o 23 23 49" src="https://user-images.githubusercontent.com/750553/169407072-4229d570-287c-4682-9802-411c7a8b2090.png">

**Comment by timdorr** [comment]
This is expected. A `/` indicates a new path segment, even if it's empty. You shouldn't use trailing slashes on your routes and links.

**Comment by rafalp** [comment]
So basically react-router v6 doesn't officially support trailing slashes?

This sounds like a potential problem. There's plenty of popular websites using this approach and backend frameworks that push people to trailing slash.

**Comment by lqze** [comment]
@timdorr 
> This is expected. A `/` indicates a new path segment, even if it's empty. You shouldn't use trailing slashes on your routes and links.

How would you handle someone navigating to that route by accident? E.g. if they manually typed it in their browser
```
my-domain/page

vs

my-domain/page/
```

**Comment by rafalp** [comment]
@lqze returning redirect from backend is standard practice for those AFAIK.

**Comment by lqze** [comment]
Agreed. How would you handle that in a client-side rendered SPA?
