### ISSUE TITLE
[Bug]: No support for the nested routes in a modal dialog

### ISSUE THREAD

**Issue by egor-sorokin** [remix-run/react-router#8886]
### What version of React Router are you using?

v6

### Steps to Reproduce

1) Create a page with a nested route where the open modal button will be located
2) Add a link to the button to open the modal dialog
3) Create several content components for the modal dialog with links (Link component) for the next content
4) Put routing for the modal in the main component/layout
5) Put <Outlet /> inside of the modal component to display different content 
6) Run the app
7) Open the modal dialog
8) Try to go to the next content within the modal

The possible setup can look like this (the modal comes from "reakit" library)
```
<Routes>
    <Route path="/" element={<Layout />}>
      <Route index element={<Home />} />
      <Route path="dashboard" element={<Dashboard />}>
        <Route path="modal" element={<Modal1 />}>
          <Route index element={<Content1 />} />
          <Route path="content-2" element={<Content2 />} />
          <Route path="content-3" element={<Content3 />} />
          <Route path="content-4" element={<Content4 />} />
        </Route>
      </Route>
    </Route>
</Routes>

const Layout = () => (
    <div>
      <nav>
        <ul>
          <li>
            <Link to="/">Home</Link>
          </li>
          <li>
            <Link to="/dashboard">Dashboard</Link>
          </li>
        </ul>
      </nav>
      <Outlet />
    </div>
  );
      
const Home = () => (
    <div>
      <h2>Home</h2>
    </div>
  );
      
const Dashboard = () => (
    <div>
      <h2>Dashboard</h2>
      <Link to="/modal">Open modal</Link>
    </div>
  );

const Modal1 = () => (
    <Modal visible={true}>
      <div>Modal1</div>
     <Outlet />
    </Modal>
  );

const Content1 = () => (
    <>
      <div>ModalContent1</div>
      <Link to="/content-2">TO ModalContent2</Link>
      <Link to="/content-3">TO ModalContent3</Link>
      <Link to="/content-4">TO ModalContent4</Link>
    </>
  );

const Content2 = () => (
    <>
      <div>ModalContent2</div>
      <Link to="/content-3">TO ModalContent3</Link>
    </>
  );

const Content3 = () => (
    <>
      <div>ModalContent3</div>
      <Link to="/content-4">TO ModalContent4</Link>
    </>
  );

const Content4 = () => (
    <>
      <div>ModalContent4</div>
      <Link to="/content-2">TO ModalContent2</Link>
    </>
  );  
```

### Expected Behavior

The modal dialog should handle the change of the content without being closed or reloaded, as it was possible to do in react-router v5.1. Moreover, the path inside of the mobile should not become longer/deeper, currently the same level routes in the code get nested in the browser (making URL longer and longer), like

Expected:
/modal/content-1
/modal/content-2

### Actual Behavior

Once the button to go to another content is clicked the path becomes 2 levels nested, then 3 levels, and so on, which prevents the rendering of the following content (I believe) so nothing is displayed, that means that routes even on the same level in the code base get nested deeper and deeper in the real app that brokes the routing.

Actual:
/modal/content-1/content-2

**Comment by timdorr** [comment]
I don't see why this would be affected by the modal. Can you put this into CodeSandbox or StackBlitz so we can see the code in action? It sounds like something involving breaking the React context is happening, but that's just speculation.

**Comment by egor-sorokin** [comment]
@timdorr thank you for your reply! Here is the link https://stackblitz.com/edit/github-csc7xs-yzusza?file=src/App.tsx. 
- in this code, if click on **Open Dashboard Modal 1 (works)** the modal dialog appears with the content. If click **TO ModalContent2** and then in updated content click on **TO ModalContent1 (GO back)** everything works as expected, basic back forward navigation. The issue begins once you go deeper or jump over:

- (go deep case) click on **TO ModalContent2** and then on **TO ModalContent3**, modal disappears and layout is broken, console says "No routes matched location "/dashboard/modal/content-2/content-3"

- (jump over) click on **TO ModalContent3** and then on **JUMP TO ModalContent2 (GO back)** (same kinda back button), modal disappears and layout is broken, console says "No routes matched location "/dashboard/modal/content-3/content-2"

**Comment by timdorr** [comment]
You're linking to the wrong routes or routes that don't exist. When you link to `/modal`, this is an absolute link to the root `modal` path. When you link to `something-123`, it's going to nest automatically under the current route. If you want to link to a sibling, you need to link to `../something-123`.
