### ISSUE TITLE
[Bug]: `<Link to={{ pathname: '..' }} />` doesn't navigate one level up

### ISSUE THREAD

**Issue by srmagura** [remix-run/react-router#8887]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Open my [CodeSandbox](https://codesandbox.io/s/react-router-parent-link-bug-7je0zk?file=/src/App.tsx).
2. Click "View team list".
3. Click "Create new team".
4. If you click "Go back to team list", it works. If you click "Go back to team list (object version)", no navigation occurs.

Why do these two cases behave differently?

### Expected Behavior

Clicking a `<Link to={{ pathname: ".." }} />` should navigate one level up in the tree.

### Actual Behavior

Clicking a `<Link to={{ pathname: ".." }} />` does not change the location.

### Additional Context

https://github.com/remix-run/react-router/issues/8350 seems to be related, but deals with index routes. My example does not use index routes.

**Comment by timdorr** [comment]
This is expected. If you provide a Location object, it's assumed it has already been parsed. If you provide a string `to` prop, then it will be parsed and the `..` will be converted to the parent location.

**Comment by srmagura** [comment]
Thanks. What is the recommended way to navigate one level up and add a URL search param? E.g. go from `/teams/new` to `/teams?search=foobar`.

**Comment by timdorr** [comment]
Treat `..` as any other URL segment: `<Link to="..?search=foobar">`
