### ISSUE TITLE
[Bug]: Example react version warning

### ISSUE THREAD

**Issue by harshilparmar** [remix-run/react-router#8895]
### What version of React Router are you using?

5

### Steps to Reproduce

Go to version 5 [doc](https://v5.reactrouter.com/).
Go to examples [section](https://v5.reactrouter.com/web/example/basic)

### Expected Behavior

We should change our code to according to react 18 or We can specify the version of react in codesandbox links.

### Actual Behavior

All the example link of codesandbox are using latest version of react.Due to this we are getting a warning from react 18 [here](https://v5.reactrouter.com/web/example/url-params).
![image](https://user-images.githubusercontent.com/45915468/169851168-e929259e-cd62-4501-9db8-484cf35cf638.png)

**Comment by timdorr** [comment]
This isn't a bug with React Router. You need to switch to React.createRoot.

**Comment by harshilparmar** [comment]
> This isn't a bug with React Router. You need to switch to React.createRoot.

But this is React Router doc example.

**Comment by xobs** [comment]
This is a documentation bug.

You need to switch the documentation to `React.createRoot`:

https://github.com/remix-run/react-router/blob/dc1969df81a2cd21b4e22e0dda577060d10c2647/docs/getting-started/installation.md?plain=1#L61-L63

A workaround is described in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43848#issuecomment-1120406623 that requires '@types/react-dom`:

```javascript
import { createRoot } from 'react-dom/client';
const root = createRoot(
    document.getElementById("root")!
);
```

**Comment by harshilparmar** [comment]
Thanks @xobs I will look into it and make PR for that.
