### ISSUE TITLE
[Bug]: `DataBrowserRouter`'s `fallbackElement` prop is required

### ISSUE THREAD

**Issue by JNaftali** [remix-run/react-router#8896]
### What version of React Router are you using?

6.4.0-pre.2

### Steps to Reproduce

Any server rendering setup

### Expected Behavior

when server rendering it doesn't make sense to give `DataBrowserRouter` a `fallbackElement` (because you already have UI and presumably data to use during hydration)

### Actual Behavior

The docs say the `fallbackElement` prop is optional, but it's required in the `DataBrowserRouterProps` type

**Comment by JNaftali** [comment]
Assuming the desired behavior is for the prop to be optional I'm happy to take a stab at implementing a fix (also happy for y'all to do it if you're in a rush). The simplest fix would be to make the prop optional in `DataBrowserRouter` and `useRenderDataRouter` and throw an error [here](https://github.com/remix-run/react-router/blob/feat/remixing-router/packages/react-router/lib/components.tsx#L90) to ensure the return type of the hook doesn't break. Could also change the return type to `React.ReactNode` instead of `React.ReactElement` but I assume y'all have a reason why that type is the way it is.

**Comment by brophdawg11** [comment]
Thanks @JNaftali!  Just merged the above PR to change this to be optional and of type `React.ReactNode` now.  We should hopefully have a `6.4.0-pre.3` out soon with those changes 👍
