### ISSUE TITLE
[Bug]: Docs API reference link Broken

### ISSUE THREAD

**Issue by rjerue** [remix-run/react-router#8897]
### What version of React Router are you using?

6

### Steps to Reproduce

Go to https://reactrouter.com/docs/en/v6/api

### Expected Behavior

Something like https://web.archive.org/web/20220116143805/https://reactrouter.com/docs/en/v6/api

### Actual Behavior

Redirecting to https://reactrouter.com/docs/en/v6

**Comment by rjerue** [comment]
Sorry if this is a pain, I tried to clone down, but can find nothing on building the docs :(

**Comment by bsides** [comment]
I can attest the link isn't working anymore. For whatever reason, going to /api in the end of the url is rewritten as the parent one. 

Here's the old version working: 
https://web.archive.org/web/20220428203023/https://reactrouter.com/docs/en/v6/api

**Comment by andywillis** [comment]
Even the non-API pages like [https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6) aren't working.

**Comment by Davont** [comment]
v5 works fine.
https://v5.reactrouter.com/web/guides/quick-start

**Comment by reify-rjerue** [comment]
![image](https://user-images.githubusercontent.com/78764801/170045211-cfc7567e-278a-4314-b922-b087aa1f5f3f.png)

Looks like things were moved to the top level nav and the api section/route was removed when I checked this morning.

**Comment by rjerue** [comment]
lol maybe if I did the message with the right account 😆
