### ISSUE TITLE
[Bug]: Previous location is seen on unmount cleanup of `useEffect`

### ISSUE THREAD

**Issue by liorp** [remix-run/react-router#8899]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Create an app with two distinct routes
2. Create a `useEffect` hook in the second component that calls `setSearchParams` in the cleanup
3. When you navigate from the second route to the first route, it will jump back to the first route

### Expected Behavior

The route should be updated 

### Actual Behavior

The route seen by the `navigate` function is the previous route, hence it jumps to the previous component

### Demo
https://stackblitz.com/edit/github-bha8hk?file=src/App.tsx

**Comment by timdorr** [comment]
This is expected. The cleanup function of useEffect is run without a re-render, so any state is expected to be from the last render. This is just how React works.
