### ISSUE TITLE
[Bug]: Router location is not updated if app is accessed through an iframe

### ISSUE THREAD

**Issue by raquelhortab** [remix-run/react-router#8900]
### What version of React Router are you using?

"react-router-dom": "^6.3.0"

### Steps to Reproduce

- create a basic react app with a BrowserRouter and some routes
- access the app through an iframe (basic html file with an iframe inside)

### Expected Behavior

When changing the src prop of the iframe via Javascript and calling location.reload, the component should be updated with the new location

### Actual Behavior

When manually changing the src prop of the iframe (i.e. using dev tools in chrome, for instance), the location of the iframe is correctly updated.

When changing the src prop of the iframe via Javascript and calling location.reload, the location is not updated at all. By inspecting the element I can see the iframe has the new location, but the react app renders the old component. The component re-renders and it feels like the page is reloaded, but the content is the same.

By running `console.log(window.location.href)` in the component, it prints the old location

**Comment by timdorr** [comment]
Changing the location with just the `src` prop and a reload is not sufficient for the library to "see" those changes. You need to actually navigate from within the iframe somehow, which triggers a history event that the library can see.

**Comment by raquelhortab** [comment]
How's it that it does trigger a render though? Is that really the expected behaviour? To re-render but not update the location.
I easily fixed it by replacing the whole iframe with a new one everytime I want to navigate, but stil...
