### ISSUE TITLE
[Feature]: Support the Navigation API

### ISSUE THREAD

**Issue by LifeIsStrange** [remix-run/react-router#8901]
### What is the new or updated feature that you are suggesting?

Chromium 102 has been released stable, which means that Chrome, Edge, Opera, Brave, Vivaldi, etc and Electron supports the Navigation API
https://chromestatus.com/feature/6232287446302720
The Navigation API is the successor of the History API and is better suited for SPAs.
Therefore, routers should allow to target and leverage it.

### Why should this feature be included?

> The existing window.history API is hard to deal with in practice, especially for single-page applications. In the best case, developers can work around this with various hacks. In the worst case, it causes user-facing pain in the form of lost state and broken back buttons, or the inability to achieve the desired navigation flow for a web app.

**Comment by timdorr** [comment]
Thanks, but there is still much broader support of the History API and it works just fine for our purposes.

**Comment by gregmartyn** [comment]
What about integration with the native loading indicator?
https://twitter.com/_developit/status/1625612424576376840?lang=en
