### ISSUE TITLE
[Feature]: Callout inspiration from Ember.js in docs

### ISSUE THREAD

**Issue by drewhamlett** [remix-run/react-router#8902]
### What is the new or updated feature that you are suggesting?

Give a callout to Ember.js inspiration in react-router docs.

Much like the callout for react-router and Ember.js in Next.js RFC for layouts

<img width="928" alt="Screen Shot 2022-05-25 at 11 25 01 AM" src="https://user-images.githubusercontent.com/1056587/170299322-59827786-a186-4d43-92a4-07571e825585.png">

### Why should this feature be included?

Giving shoutouts to previous work is nice :D.  Also gives context to newer developers that might not know the history of frontend technologies/frameworks.

**Comment by timdorr** [comment]
We don't have any Ember-inspired features in this library.

**Comment by drewhamlett** [comment]
https://github.com/remix-run/react-router/issues/15
https://github.com/remix-run/react-router/issues/22
https://github.com/remix-run/react-router/issues/26
https://github.com/remix-run/react-router/issues/187

https://guides.emberjs.com/release/routing/rendering-a-template/
https://reactrouter.com/docs/en/v6/components/outlet

**Comment by timdorr** [comment]
Those are all very old links from when we were still pre-1.0. The router has been through at least 3 major rewrites with entirely new APIs and systems. The Outlet comparison is weak at best, since Michael was the one that implemented it, not Ryan. It also has inspiration points from [Angular](https://angular.io/api/router/RouterOutlet), as well as Ember. I wouldn't attribute it to any particular library.

**Comment by ryanflorence** [comment]
We should definitely have an acknowledgments doc. In our early docs (almost a decade ago) we gave a hat tip to ember, then in v4 we moved to all render/component routing, but with v6 returning to our ember roots we should absolutely acknowledge it, just like in our docs for @reach/router (https://reach.tech/router/credits)

I'll write it next week (as v6 draws from ember and preact router too. Thanks for the nudge @drewhamlett :)

**Comment by brophdawg11** [comment]
🎉 https://reactrouter.com/en/main/start/overview#nested-routes
