### ISSUE TITLE
[Feature]: Similar feature to the <Redirect> component in reach-router

### ISSUE THREAD

**Issue by Becavalier** [remix-run/react-router#8905]
### What is the new or updated feature that you are suggesting?

Similar feature to the <Redirect> component in reach-router.

This could help us to have the ability of conditional routing.

### Why should this feature be included?

This could help us to have the ability of conditional routing (when a particular pattern of URL matches, it could redirect to the specified URL automatically). And I think we are not able to do the same thing with react-router, right?

**Comment by timdorr** [comment]
You're looking for the `<Navigate>` component.
