### ISSUE TITLE
[Feature]: Update doc to put a caution / warning on the number of routes

### ISSUE THREAD

**Issue by ardok** [remix-run/react-router#8918]
### What is the new or updated feature that you are suggesting?

Update documentation to give warnings on the # of Routes that react-router can handle before degrading performance.

### Why should this feature be included?

In v5, we were doing this:
```
<Routes path={[
  '/foo',
  '/fr-FR/foo',
  '/en-US/foo',
  ...50+ more locales...,
  '/bar',
  '/fr-FR/bar',
  ...50+ more locales...,
  ...other routes with locales,
]}
```
We have about ~3000 possible routes in total. It was working fine.

-----

Then comes v6. It no longer supports list of paths. It is recommended to just expand them all into `<Route>` component per this [doc](https://reactrouter.com/docs/en/v6/getting-started/faq#what-happened-to-regexp-routes-paths).

It says:

> These are all actually just static paths, so in v6 you can make three routes and pass the code directly to the component. **If you've got a lot of them, make an array and map it into routes to avoid the repetition.**

So then, we have to do:
```
const paths = [
  '/foo',
  '/fr-FR/foo',
  '/en-US/foo',
  ...50+ more locales...,
  '/bar',
  '/fr-FR/bar',
  ...50+ more locales...,
  ...other routes with locales,
]
paths.map(() => {
  return <Route path={`${path}/*`}>
})
```

Resulting in about ~3000 `<Route>` component.

We are doing Server Side Rendering (SSR).

It degrades our SLA for server request by a lot, from about 800 ms to 4+ seconds.

-----

We fixed it by using `/:locale/foo`, `/:locale/bar`, and do the check for supported locales in the component. If locale is not supported, render 404 page. Then the SLA returned to normal.

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/1380581/171503617-f5d01c85-f567-40f0-950c-66695bbef49d.png">

-----

Can we add more texts or sentences somewhere in the doc, particularly that regex path, to put a warning on this? That is, if you have X+ number of routes, consider to use route params instead.

**Comment by timdorr** [comment]
This isn't something we can really warn about. What you do with the Route component is arbitrary. It's good that you solved the issue, but it's not something we can really "fix".
