### ISSUE TITLE
Useroutes configures the routing table. If it is a delayed loading component, an error is reported

### ISSUE THREAD

**Issue by livelyPeng** [remix-run/react-router#8920]
### What version of React Router are you using?

v6

### Steps to Reproduce

Useroutes configures the routing table. If it is a delayed loading component, an error is reported

![image](https://user-images.githubusercontent.com/32978177/171531058-af2d95ad-0318-4021-80bd-f63f915e9aba.png)

### Expected Behavior

Useroutes configures the routing table. If it is a delayed loading component, an error is reported

### Actual Behavior

Useroutes configures the routing table. If it is a delayed loading component, an error is reported

**Comment by timdorr** [comment]
This isn't caused by the library. You need to wrap things in a Suspense component for React to have a fallback UI.
