### ISSUE TITLE
[Feature]: Export a subcribe function

### ISSUE THREAD

**Issue by Hummel37** [remix-run/react-router#8922]
### What is the new or updated feature that you are suggesting?

Getting it form here: https://github.com/molefrog/wouter/issues/58#issuecomment-1025948175
It would be nice to subcribe to changes in the history.

### Why should this feature be included?

It would be nice to be able to subcribe only to certrian changes on the history.
If I am getting it correct each time if the subcribe function calls the callback the given select function is executed.
Only if the result of the select function changes a rerender would be happen.
If you are okay with the idea I would implement it and open a PR for that.

**Comment by timdorr** [comment]
History is considered an internal implementation detail in v6. If you want to subscribe to location updates, you should do that using the `useLocation` hook from inside some component in your app.
