### ISSUE TITLE
[Bug]: NavLink's "className as a function" api is not working in 3rd-party components

### ISSUE THREAD

**Issue by pvlcor** [remix-run/react-router#8925]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

If we wrap NavLink in any component, which somehow expects `className` prop of its `children` to be a string, NavLink's `className={({ isActive }) => ....}` prop will not work.

Please see this demo with latest MUI Tooltip:
https://codesandbox.io/s/nervous-haslett-n1jjzq?file=/src/App.js

[Here](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Tooltip/Tooltip.js#L537) MUI expects className to be a string.

Quick fix is to create custom NavLink with previous api (example from react-router docs):
```
import * as React from "react";
import { NavLink as BaseNavLink } from "react-router-dom";

const NavLink = React.forwardRef(
  ({ activeClassName, activeStyle, ...props }, ref) => {
    return (
      <BaseNavLink
        ref={ref}
        {...props}
        className={({ isActive }) =>
          [
            props.className,
            isActive ? activeClassName : null,
          ]
            .filter(Boolean)
            .join(" ")
        }
        style={({ isActive }) => ({
          ...props.style,
          ...(isActive ? activeStyle : null),
        })}
      />
    );
  }
);
```

Previous api is much better due to its predictability, so it's kinda odd that previous api is superior to latest.
One needs to write custom wrapper to go back to it. All in the name of keeping className as a function)

### Expected Behavior

`className` is expected to be a string.
`className` as a function for sure will break many 3rd party components, as no-one expects it to be a function.
so I can suggest to go back to previous api with `activeClassName` prop.

### Actual Behavior

`className` as a function is not working in 3rd party wrappers, which expect it to be a string.

**Comment by timdorr** [comment]
If they only expect it to be a string, then just pass strings along. If they don't allow functions to be passed to the wrapper, that's up to them to change the typings or for you to wrap their components. This isn't a problem with the library.

**Comment by allamgr** [comment]
HI @AuthorProxy you can try the following, create your own wrapper. 

```const MyNavLink = React.forwardRef<any, any>((props, ref) => (
  <NavLink
    ref={ref}
    to={props.to}
    className={({ isActive }) => `${props.className} ${isActive ? props.activeClassName : ''}`}
  >
    {props.children}
  </NavLink>
));
```

[StackOverflow Reference](https://stackoverflow.com/questions/71350481/react-router-dom-v6-navlink-and-mui-listitem-not-working-with-classname)

Also I'm not using material ui, I'm using tailwind, postcss, shadcn uii and I'm facing the same problem, here is my solution:

```
import React from "react";
import { NavLink } from "react-router-dom";

type AppLinkProps = {
  to: string;
  className: string;
  activeClassName?: string ;
  children: React.ReactNode;
};

const AppLink = React.forwardRef<any, AppLinkProps>((props, ref) => (
  <NavLink
    ref={ref}
    to={props.to}
    className={({ isActive }) =>
      `${props.className} ${isActive ? props.activeClassName : ''}`
    }
  >
    {props.children}
  </NavLink>
));

export default AppLink

```

PD: I think it could be nice to add something related with 3rd party libraries in documentation @timdorr
