### ISSUE TITLE
[Bug]: Somehow the state of an input is being transfered (against my will) between pages

### ISSUE THREAD

**Issue by ElGatoNinja** [remix-run/react-router#8926]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

[sandbox](https://codesandbox.io/s/blissful-bhabha-jifmbr?file=/src/App.js)

This is a minimal reproduction sandbox. 

### Expected Behavior

If you write something in the box and change the page, the box in the new page should be empty, because it is a new and different input.

### Actual Behavior

If something is written in the input and you go to another page, the input in that page has the same text.

I do not know if it is my fault and there is something I am not understanding about react-router or react in general, or if it is a bug.

Thank you for help

**Comment by timdorr** [comment]
This is just how React works. If you render the same component tree, it will re-use the existing instances of those components. You can force it to discard those instances with the `key` prop.
