### ISSUE TITLE
[Feature]: Providing a `component` instead of an `element`

### ISSUE THREAD

**Issue by devlato** [remix-run/react-router#8943]
### What is the new or updated feature that you are suggesting?

Make Router take a `component` instead of an `element`

### Why should this feature be included?

Hey!

According to the [documentation](https://reactrouter.com/docs/en/v6/components/route), `Route` takes an `element` – meaning that you end up generating an element subtree for routes the user hasn't even visited yet. Is there a chance Route could take a component instead, which React Router would then render?

**Comment by timdorr** [comment]
You don't generate the subtree until it is actually rendered. Until then, it just sits as a small memory structure. It doesn't get a full instance until it is actually rendered.
