### ISSUE TITLE
[Bug]: useParams always return object with {*: 'xxx'}, not the key defined in <Route path=":tagId" />

### ISSUE THREAD

**Issue by zhuliminl** [remix-run/react-router#8963]
### What version of React Router are you using?

"react-router-dom": "^6.3.0",

### Steps to Reproduce
```
<Route path={'/:tagId'} element={<Content />} />


// in Content component 
let p = useParams()
console.log( p)

// 
```

### Expected Behavior

should be {tagId: 'xxx'}

### Actual Behavior

it turns out with {*: 'xxx'}

**Comment by timdorr** [comment]
You don't need the leading slash, just `path=":tagId"`.

**Comment by MaEdAlpha** [comment]
![image](https://user-images.githubusercontent.com/72553021/183846564-7d617e98-46cc-408b-aa4b-cb162f1a5e8f.png)
```
        <Route
            path=":parentCompName-:orgName"
            element={
              <React.Suspense fallback={<>...</>}>
                <EmployerComponent />
              </React.Suspense>
            } 
          />

```
In component  I declare

```
  const params = useParams();

  console.log(params);
```

image at top prints.
