### ISSUE TITLE
Always render twice!

### ISSUE THREAD

**Issue by zhuliminl** [remix-run/react-router#8968]
### What version of React Router are you using?

"react-router-dom": "^6.3.0",

### Steps to Reproduce

```

import React, { useState, useEffect } from "react";
import { BrowserRouter, Routes, Route, Link } from "react-router-dom";

export default function BasicExample() {
  return (
    <BrowserRouter>
      <div>
        <div>
          <ul>
            <li>
              <Link to="/home">Home</Link>
            </li>
            <li>
              <Link to="/about">About</Link>
            </li>
            <li>
              <Link to="/dashboard">Dashboard</Link>
            </li>
          </ul>
        </div>
        <Routes>
          <Route  path="/home" element={<Foo />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

// You can think of these components as "pages"
// in your app.
class Foo extends React.Component {
  componentDidMount = () => {
    console.log('saul bbb')
  }

  render() {
    console.log('saul jjj')
    return (
      <div>HHHHH</div>
    )
  }
}
```

### Expected Behavior

only render onece

### Actual Behavior

console turn out  with  result :
```
saul bbb
saul bbb'
saul jjj
saul jjj 
```

**Comment by zhuliminl** [comment]
where is another example https://stackblitz.com/edit/react-awbiet?file=src/App.js which also has the same problem

**Comment by timdorr** [comment]
This is caused by React Strict Mode, not this library.

**Comment by aakashsardana** [comment]
@zhuliminl it is happening because your `<App />` is wrapped in `<StrictMode />` (see `index.js` in your example). You can read more here You can read more here: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by dakshamdev** [comment]
> This is caused by React Strict Mode, not this library.

Thanks a lot for the clarification :)
And from docs, it is made clear that it won't render twice in the production bundle.
