### ISSUE TITLE
[Bug]: every second call to `router.fetch` will bypass calling `shouldRevalidate` and will revalidate instead

### ISSUE THREAD

**Issue by tchak** [remix-run/react-router#8969]
### What version of React Router are you using?

@remix-run/router 0.2.0-pre.2

### Steps to Reproduce

In a project using `@remix-run/router` without `React` [rails-remix-demo](https://github.com/tchak/rails-remix-demo) I have the following logic:

```ts
route.shouldRevalidate = () => false

router.fetch(fetcherKey, routeId, action, options)
// wait to finish
router.fetch(fetcherKey, routeId, action, options)
// wait to finish
router.fetch(fetcherKey, routeId, action, options)
// wait to finish
router.fetch(fetcherKey, routeId, action, options)
```

### Expected Behavior

`route.shouldRevalidate` should be called 4 times. No revalidation should happen.

### Actual Behavior

`route.shouldRevalidate` only called 2 times on every second call. Revalidation is happening on calls bypassing `route.shouldRevalidate`

**Comment by brophdawg11** [comment]
Fixed in #8969 - should be able to get a new prerelease out hopefully this week
