### ISSUE TITLE
[Feature]: add types for state in useLocation hook in rr6

### ISSUE THREAD

**Issue by popuguytheparrot** [remix-run/react-router#8980]
### What is the new or updated feature that you are suggesting?

add types for state in useLocation hook for not break exist code

for example: 
//in rr6 is broken with types
`const location = useLocation<StateValues>()
`

### Why should this feature be included?

add type for set state values in use place

**Comment by timdorr** [comment]
This would actually remove type safety, as you would be overriding `state` to that type. You should be using type narrowing to determine the type of `state` safely. A generic would be a hack to force that to work.

https://github.com/remix-run/react-router/pull/8370#issuecomment-974578233
https://github.com/remix-run/react-router/issues/8396#issuecomment-980829670
