### ISSUE TITLE
[Bug]: No routes matched location "/$BTC"

### ISSUE THREAD

**Issue by waveiron** [remix-run/react-router#8988]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Just access any path that contains "$".

### Expected Behavior

"$" is a reserved word, but react-router should warn, but still usable.

### Actual Behavior

Blank page, and warns: 
`No routes matched location "/$BTC"`

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8525#issuecomment-1054455573

**Comment by waveiron** [comment]
> [#8525 (comment)](https://github.com/remix-run/react-router/issues/8525#issuecomment-1054455573)

Preventing using special character altogether is not something a router library should do.
Like I said:
"$" is a reserved character, react-router can make a warning, but still usable.
