### ISSUE TITLE
[Feature]: WE NEED NORMAL API WITHOUT HOOKS!

### ISSUE THREAD

**Issue by CainKane** [remix-run/react-router#8992]
### What is the new or updated feature that you are suggesting?

**React Hooks was not omnipotent , In most cases , a normal API is simple&easy to use !!
Example . we need get params , in hooks :** 
```
function ComponentA (){
	const {} = useParams();
}
function ComponentB (){
	const {} = useParams();
}
function ComponentC (){
	const {} = useParams();
}
```
**BUT , WHY NOT THIS ?** 
```
const {id,name,sku} = getParams();


function ComponentA (){
	console.log(id,name);
}
function ComponentB (){
	console.log(name,sku);
}
function ComponentC (){
	console.log(sku);
}
```

**USE HOOKS EVERYWHERE IS VERY STUPID! Hooks only generates value where it fits**

### Why should this feature be included?

All function implemented in HOOKS ! 
like useNavigate , useParams . etc...
(PS:```<Navigate/>``` was too stupid)

**Comment by kiliman** [comment]
Shouting in ALL CAPS and saying something is "VERY STUPID" is definitely not the way to go if you want somebody to take you seriously and consider your request.

**Comment by whiteand** [comment]
@CainKane Just curious, what should be getParams() result if we have several Router components mounted at the same time?
