### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sandrina-p** [remix-run/react-router#8994]
### What version of React Router are you using?

6

### Steps to Reproduce

- [Test case #1 in Stackblitz](https://stackblitz.com/edit/github-k8opfj-ufvisd?file=src%2FApp.tsx)

Goal: Create a "Go Back" link with `<Link>`. I wish to create a "Go back" using `<Link>` instead of `navigate()` because this behavior allows me to use `<a href="xxxx">` instead of a `<button>`, which is the most accessible way of creating links between pages. (More about [button vs links](https://css-tricks.com/buttons-vs-links/))

1. Click "About"
2. Click "Go back" — It goes back to the homepage.

### Expected Behavior

The "Go Back" link has the HTML `<a href="/">Go Back</a>`

### Actual Behavior

The "Go Back" link has the HTML `<a href="/about">Go Back</a>`

----

P.S.1 Initially I asked this question on [Stackoverflow](https://stackoverflow.com/questions/72676015/react-router-go-back-using-link/72676112) but based on some answers, I believe this is a bug (or perhaps a missing feature because `to={-1}` is [not a valid type to TypeScript](https://user-images.githubusercontent.com/14869087/174477765-b34bb574-a28f-4eb2-9a13-2694fddad8ea.png).

P.S.2 In [another codesandbox](https://codesandbox.io/s/react-router-go-back-7oq2vq?file=/src/App.js) the bug is slightly different:

1. Click "Go to destiny"
2. Click "Go back" — It does not work (In the first case, it worked)
4. Click "Go home" instead.
5. Click "Go to destiny"
6. Click "Go back" — Now it works, but the HTML is still incorrect as mentioned in the first case.

**Comment by timdorr** [comment]
While you can technically use Link with `to={-1}`, it's not allowed because the link you're creating appears to be to that same page but results in a "go back" navigation when clicked. We don't parse `-1` as a pathname, as the functions to generate a URL from a pathname don't take into account the history stack.

**Comment by sandrina-p** [comment]
I see. So, what's the best solution to create a "Go Back" link using `<Link />` ?

**Comment by awreese** [comment]
Use an `onClick` handler to "change", or prevent, the default link behavior and issue an imperative back navigation.

```
<Link
  to={'..'}
  onClick={(e) => {
    e.preventDefault();
    navigate(-1);
  }}
>
  Go back (-1)
</Link>
```

I've answered your SO question [here](https://stackoverflow.com/a/72691726/8690857)

**Comment by sandrina-p** [comment]
@awreese, that solution is not accessible, I answered in SO with more details. We can continue there.
