### ISSUE TITLE
[Bug]: TSDoc Links

### ISSUE THREAD

**Issue by ivorscott** [remix-run/react-router#9040]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Use the latest react-router version with the latest types.

Then navigate to node_modules/react-router/lib/hooks.d.ts in your favorite IDE and click the links.

### Expected Behavior

I expect the correct links.

### Actual Behavior

The links are incorrect.

For example: 

This: https://reactrouter.com/docs/en/v6/api#uselocation 

Should be: https://reactrouter.com/docs/en/v6/hooks/use-location

Seems like there was a fix for this but I don't see the changes. 
<img width="1617" alt="Screen Shot 2022-07-08 at 01 04 27" src="https://user-images.githubusercontent.com/1488558/177885707-62bb8979-b8bb-439c-80ce-ce72c28b4d56.png">

https://github.com/remix-run/react-router/commit/9fa54d643134cd75a0335581a75db8100ed42828

**Comment by timdorr** [comment]
This was fixed in #8913, but hasn't been released yet.
