### ISSUE TITLE
[Bug]: I can't use <link to='http://xxxxx.xxx.xx' />, it's look at <link to='/http://xxxxx.xxx.xx'  />

### ISSUE THREAD

**Issue by shuzipai** [remix-run/react-router#9041]
### What version of React Router are you using?

6

### Steps to Reproduce

<link to='http://xxxxx.xxx.xx' />

### Expected Behavior

<a href='http://xxxxx.xxx.xx' />

### Actual Behavior

<a href='/http://xxxxx.xxx.xx' />

**Comment by shuzipai** [comment]
use <link to='http://xxxxx.xxx.xx' />   =====> <a href='/http://xxxxx.xxx.xx' />, it's not i need，i need <a href='http://xxxxx.xxx.xx' />

**Comment by shuzipai** [comment]
the github hidden my code

**Comment by shuzipai** [comment]
use `<<link to='http://xxxxx.xxx.xx' />` =====>`<a href='/http://xxxxx.xxx.xx' />`
i need `<a href='http://xxxxx.xxx.xx' />`

**Comment by timdorr** [comment]
`Link` is only for internal links to other routes. For external URLs, you should use an `<a>`
