### ISSUE TITLE
[Bug]: native docs not reflecting React Router v6 changes

### ISSUE THREAD

**Issue by jayqui** [remix-run/react-router#9046]
### What version of React Router are you using?

n/a

### Steps to Reproduce

1. Visit https://v5.reactrouter.com/native/example/Basic
2. See error:

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/10286362/178163658-794102c7-de92-406b-82b4-acf906545c62.png">

Looks like the documentation needs to be updated to reflect React Router 6...

### Expected Behavior

  Working documentation

### Actual Behavior

Broken documentation

**Comment by timdorr** [comment]
That is the v5 documentation, as per the URL.

**Comment by jayqui** [comment]
Thank you for pointing out my mistake, and I apologize for my obtusensess!
