### ISSUE TITLE
[Bug]: return type for NavLink "style" attribute does not support undefined as stated in the documentation

### ISSUE THREAD

**Issue by radoncreep** [remix-run/react-router#9064]
### What version of React Router are you using?

6

### Steps to Reproduce

`
<NavLink
  className={({ isActive }) => isActive ? {color: '#70EE90'} : undefined>
 Some Link
</NavLink>
`

### Expected Behavior

expected CSSProperties and undefined are valid return types according to the documentation but it prompts an error.

### Actual Behavior

function accepts only CSSProperties as return type which is so on the documentation

**Comment by timdorr** [comment]
You have the wrong prop in your example. The `style` prop only allows CSSProperties as a return of its function form. The `className` prop allows undefined as a return from its function form.

**Comment by radoncreep** [comment]
> You have the wrong prop in your example. The `style` prop only allows CSSProperties as a return of its function form. The `className` prop allows undefined as a return from its function form.

Thanks for your response. Yes, the className prop does, but in the documentation, it is also stated that the style prop can return undefined.

Kindly check it out [here](https://reactrouter.com/docs/en/v6/components/nav-link)
