### ISSUE TITLE
[Feature]: Export OutletContext from react-router-dom

### ISSUE THREAD

**Issue by arindam-ron** [remix-run/react-router#9066]
### What is the new or updated feature that you are suggesting?

The react router Outlet component allows us to pass a context which can be used in components rendered within the Outlet using the useOutletContext hook. However this is only valid when the component rendered is functional. Hooks cannot be used in class based components. To achieve the same I have to use the following workaround of defining my own context. See snippet below:

### Context declaration:
`const ThemeContext = React.createContext('light');`

### Parent component's jsx:
```
<ThemeContext.provider value="dark">
  <Outlet />
</ThemeContext.provider>
```

### Rendered component:
```
class RenderedComponent extends React.Component {
  static contextType = ThemeContext;
  
  // this.context can be used within the class
}
```

This extra context declaration can be avoided if the OutletContext object can be imported in the RenderedComponent. See alternative below
### Parent component's jsx:
```
  <Outlet context="dark" />
```

### Rendered component:
```
class RenderedComponent extends React.Component {
  static contextType = OutletContext;
  
  // this.context can be used within the class
}
```

I could not find any other alternative by going through the docs. Please let me know if something already exists.

### Why should this feature be included?

There is an option to pass context in a functional component by using the **useOutletContext** hook. The same thing should also be possible for class based components which cannot use React hooks. 
The current workaround involves declaring one's own context which, in my opinion, negates the purpose of the **context** prop in **Outlet** component.
Given that a lot of components exist which are class based and it is not always possible to change every component to functional in legacy projects, exporting OutletContext will make working with router v6 much simpler.

**Comment by timdorr** [comment]
`contextType` is an older, unsupported API for class components. You should just wrap your class component with a function component and use `useContext`.

**Comment by arindam-ron** [comment]
Few observations on the suggestion:

1. React still supports `contextType` API for class components. Here is a [doc](https://reactjs.org/docs/context.html#classcontexttype) from v18.2.0. And it will also be required if i want to use `<OutletContext.Consumer>` syntax
2. Even if I want to use `useContext` what should I pass as an argument. Ideally I would want to use `useContext(OutletContext)`. But unfortunately I can't import it. The only option is to use `useOutletContext`
3. This small change will go a long way to support class components. As I mentioned before there are legacy projects where it is not feasible to wrap everything in a function component and this will help in adopting react-router v6

Please reconsider. If needed I can help out by trying to create a PR for this.
