### ISSUE TITLE
[Bug]: Scroll position doesn't change when navigating to another page

### ISSUE THREAD

**Issue by leadream** [remix-run/react-router#9068]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

- Open https://codesandbox.io/s/react-router-scroll-behavior-kb4b3r
- At home page, scroll to the bottom
- Click the link to navigate to `transfer` page
- It will stay at bottom instead of staying at top

### Expected Behavior

Back to the top after navigating

### Actual Behavior

Stay at bottom instead of staying at top

**Comment by timdorr** [comment]
No scroll position management is provided out of the box in React Router. You can manage this yourself either with location `state` or an effect that fires when a page component loads to move the scroll position.

**Comment by willianson** [comment]
Hi there, what commit fix it?
Here the bug persist yet.

**Comment by magicdawn** [comment]
v5 has the scroll restoration guide https://v5.reactrouter.com/web/guides/scroll-restoration
but not in v6 doc

**Comment by brophdawg11** [comment]
`<ScrollRestoration>` is coming in `6.4.0`, you can try it out today in `6.4.0-pre.10` - https://beta.reactrouter.com/en/dev/components/scroll-restoration

**Comment by juniorforlife** [comment]
I'm experiencing the same bug. Did you find the fix @willianson @leadream ?
