### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by emilypmendez** [remix-run/react-router#9072]
### What is the new or updated feature that you are suggesting?

More examples or variations in the documentation about the `<Redirect>` and `<Navigate>` elements when upgrading from v5 to v6.

### Why should this feature be included?

There is only one mention of `<Navigate>` in the upgrade section of the docs, and it is under the umbrella of upgrading to v5.1 (not v6) with more of a focus on the `<Redirect>` element. [Here is the sole reference to the `<Navigate>` component.](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6:~:text=They%20will%20become%20%3CNavigate%3E%20elements%20in%20v6.)

**Comment by timdorr** [comment]
There is a section for this under the `useNavigate` section along with an example: https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-usehistory
