### ISSUE TITLE
[Feature]: Go to router component directly ? 

### ISSUE THREAD

**Issue by shezhangzhang** [remix-run/react-router#9074]
### What is the new or updated feature that you are suggesting?

<img width="406" alt="image" src="https://user-images.githubusercontent.com/26793777/179711968-a2ad9e28-86f6-4421-b3c0-800ab276ba71.png">

As you can see, Is there a way to go to this workflow router component directly ? Or I just only to find this route in router config and find the corresponding component and then jump to it ? 

### Why should this feature be included?

Jump to router component directly.

**Comment by timdorr** [comment]
This doesn't have anything to do with the library. It would be up to your IDE to implement this.

**Comment by shezhangzhang** [comment]
> This doesn't have anything to do with the library. It would be up to your IDE to implement this.

@timdorr Maybe I could write a vscode extension for this. ?
