### ISSUE TITLE
[Bug]: React hooks stop working after navigate to the different route with the same component

### ISSUE THREAD

**Issue by romaleev** [remix-run/react-router#9075]
### What version of React Router are you using?

6.3.0 

### Steps to Reproduce

React hooks stop working after navigate to the different route with the same component.

```
<Routes>
  <Route path="/question/:step" element={<Application />} />
  <Route path="/question" element={<Application/>} />
</Routes>
```

```
export default function Application() {
  const [visible, setVisible] = useState(false);
  const { step } = useParams();
  return <div>
    {visible ? "visible" : "not visible"}
    {step || ""}
    <button onClick=(() => setVisible(true)>Show</button>
  </div>
}
```

**Load page with /question
Navigate to /question/:step using useNavigate**

Same issue with reverse:
Load page with /question/:step
Navigate to /question using useNavigate

react 18.2.0

### Expected Behavior

React hooks in Application component with route `/question/:step` work correctly, on button click "visible" sign displayed.

### Actual Behavior

React hooks within Application component with route `/question/:step` work incorrectly, on button click "visible" sign displayed and immediately replaced with "not visible".
So on every render/state change hooks are reset with initial value (false)

**Comment by romaleev** [comment]
They way I fixed this is below, though it is not the most obvious and optimal solution.
```
  <Route path="/question/:step" element={<Application />} />
  <Route path="/question" element={<div><Application/></div>} />
```

**Comment by imwangming** [comment]
same

**Comment by timdorr** [comment]
Because you're rendering the same component, React is reusing the instance with all its state. This is just how React itself works.

You need to either reset the state based on when the location changes (most likely with an effect), or change to a different component between routes and move these more core elements to a layout route.

**Comment by romaleev** [comment]
How can I accomplish that?

As example I use react-modal within the same `<Application />` component for different routes within: ` <Route path="/question/:step" element={<Application />} />`

When I navigate using react-router from /question/1 to /question2 all modals within Application stop working.
I made a custom hook to see what is happening using:
```
  const [visible, setVisible1] = hook;
  const setVisible = (v) => console.log('modal set to',  v) || setVisible1(v);
```
And see that after navigation within the same Application component all modals visibility is reset to false on every render.
So after navigation whenever I try to setVisibility(true), it becomes true and immediately after - false.

**Comment by romaleev** [comment]
I think I found a solution, inside Application component:
```
export default function Application() {
  let { step } = useParams();
  return (
    <div key={step}>...</div>
}
```

Nevertheless, I think it is worth to mention in the README, that if you reuse the same component for different routes, you should add there the key property.

**Comment by gabrielmicko** [comment]
In my opinion there should be a way to do this in react router.
