### ISSUE TITLE
[DocBug]: 

### ISSUE THREAD

**Issue by Sigfried** [remix-run/react-router#9079]
### What version of React Router are you using?

v6

### Steps to Reproduce

This is just a doc bug for 
https://reactrouter.com/docs/en/v6/hooks/use-location (specifically: https://github.com/remix-run/react-router/blob/f2178b9d093eb43f958815137067649c0335f1bd/docs/hooks/use-location.md)

### Expected Behavior

Where it says:

`React.useEffect(() => {
    ga('send', 'pageview');
  }, [location]);`

what is `ga` supposed to be? As someone new enough to really need the docs, I have no idea how to interpret this example code.

Expected behavior is documentation I understand

### Actual Behavior

Actual behavior is the [current documentation](https://github.com/remix-run/react-router/blob/f2178b9d093eb43f958815137067649c0335f1bd/docs/hooks/use-location.md).

**Comment by timdorr** [comment]
That's Google Analytics. But it can be anything. The example is meant to show what's going on with the useEffect, not the contents of the effect function itself.
