### ISSUE TITLE
[Bug]: Inconsistent behavior of `useParams` btw v5 and v6

### ISSUE THREAD

**Issue by kafkahw** [remix-run/react-router#9083]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Visit the test site (built with react-router v6.3.0): https://react-ts-vqznsw.stackblitz.io/123%2F4 (source code: https://stackblitz.com/edit/react-ts-vqznsw?file=App.tsx,Content.tsx)
2. The content displayed on the screen is decoded (i.e. "123/4" instead of "123%2F4")
3. Visit the test site (built with react-router v5.2.1: https://react-ts-ye1vjg.stackblitz.io/123%2F4 (source code: https://stackblitz.com/edit/react-ts-ye1vjg?file=App.tsx,Content.tsx)
4. The content displayed on the screen is kept as original, not decoded (i.e. "123%2F4).

The contents on both test sites are derived from using `useParams` hook but got different results. If the different behavior is on purpose, then it should be called out in the v5 to v6 migration guide.

### Expected Behavior

Consistent behavior of `useParams` and keep the URL param same as its original value (i.e. keep them encoded if they're encoded).

### Actual Behavior

`useParams` behaves differently in v6 vs in v5.
In v6 `useParams` will auto decode URL params, whereas, in v5 `useParams` keeps the original value of URL params untouched (i.e. encoded).

**Comment by timdorr** [comment]
Can you create a PR to add this to the guide? It's not strictly a "bug", so it shouldn't be tracked as such.

**Comment by kafkahw** [comment]
@timdorr can you explain a bit more before closing this issue? Is the behavior change in v6 expected? If yes, what's the rationale behind that?
I can definitely create a PR to add this to the guide, but I probably need to know the answers to these questions first.
