### ISSUE TITLE
[Feature]: Using route guards in v6

### ISSUE THREAD

**Issue by strivelen** [remix-run/react-router#9084]
### What is the new or updated feature that you are suggesting?

When I looked up the usage of routing guards (or Authentication) in the v6 documentation, I didn't find its documentation, but I looked at the example in `react-router/examples/auth` in the repository. In fact, it was the same usage as v5. I used In the v6 version of the routing configuration object method, I suddenly thought of a relatively simple routing guard configuration method. I don't know what is wrong with this method. I tested it and it is no problem.

```javascript
 {
    element: <RequireAuth />,
    children: [
      {
        element: <Layout />,
        children: [
          {
            path: 'home',
            element: <Home />
          }
        ]
      }
    ]
  }

//  RequireAuth Component
function RequireAuth() {
  const token = 'YOUR TOKEN VALUE'
  if (!token) {
    return <Navigate to="/" replace />;
  }
  return <Outlet />;
}
```

### Why should this feature be included?

I think this authentication method makes it more convenient for me to use, because I only need to configure the RequireAuth component once in the routing configuration.

**Comment by timdorr** [comment]
This is already a feature of the library. I'm not sure what you're asking us to build here, but we already have that and it's a workable solution for most folks.
