### ISSUE TITLE
[Feature]: ssr render Can you make an on-demand plug-in？

### ISSUE THREAD

**Issue by qq281113270** [remix-run/react-router#9087]
### What is the new or updated feature that you are suggesting?

ssr render Can you make an on-demand plug-in？like products   react-loadable  https://github.com/jamiebuilds/react-loadable，It can load components, JS, CSS and IMG on demand in SSR rendering.  I was going to use react-loadable, but because the author doesn't maintain the update, the plugin will give an error in Act18 and Webpack.  Hopefully a similar product will come out officially.

### Why should this feature be included?

ssr render Can you make an on-demand plug-in？like products   react-loadable  https://github.com/jamiebuilds/react-loadable，It can load components, JS, CSS and IMG on demand in SSR rendering.  I was going to use react-loadable, but because the author doesn't maintain the update, the plugin will give an error in Act18 and Webpack.  Hopefully a similar product will come out officially.

**Comment by timdorr** [comment]
This isn't the responsibility of this library. This is something you would implement outside of React Router.
