### ISSUE TITLE
[Bug]: react-router-native not working

### ISSUE THREAD

**Issue by sahilrajput03** [remix-run/react-router#9097]
### What version of React Router are you using?

v6

### Steps to Reproduce

Copy the starter code from https://v5.reactrouter.com/native/guides/quick-start and use that for the new expo snack created.

### Expected Behavior

Should work.

### Actual Behavior

Not working throwing error like that: 
![image](https://user-images.githubusercontent.com/31458531/181029726-329fc5c1-3b98-497b-a1fe-022c00658176.png)

code: https://snack.expo.dev/@sahilrajput03/adequate-pizza

Please help me make it work with version v6 coz there is no detailed usage details for using react-router-native in new docs of v6 atm.

**Comment by timdorr** [comment]
That is the v5 docs and your package.json specifies the version `*` for react-router-native, which is pulling in v6. You need to update your code for v6, which uses new APIs. There isn't much that is RN-specific in the library, other than rendering Views and Texts.
