### ISSUE TITLE
[Feature]: please add a default css class to Link in order to override the default behaviour of "<a>"  

### ISSUE THREAD

**Issue by tlecoz** [remix-run/react-router#9102]
### What is the new or updated feature that you are suggesting?

Hello ! 

I would like to remove  the css property 
`text-decoration:underline;`

applyed by default on every `<a>` 

In an ideal way, I don't want to override the behaviour of `<a>` , I would like to override only `<link>` 
Unfortunately, as far as I know , it's not possible to do it right now. 

Could you please just add a className="reactRouterDomLink"  or the name you want on the objet created with `<link>` in order to be able override the css of `<link>` without modifying anything else. 

If the users don't want to change anything, they won't define the "reactRouterDomLink" and everything will work as expected but if someone like me want to do it, it would be possible to do so. 

It's really a minor change but it could be really usefull. 

I'm not the only one on the internet who would like to override the css of  every `<link>` in a react-project as you can see : 

https://www.google.com/search?q=react+router+dom+link+text+decoration&sxsrf=ALiCzsYeudz19OkzMOU25gHQrEssHZ6v8A%3A1659016635880&ei=u5XiYsWuNYKMa8XFi4gN&oq=react-router-dom+link+text&gs_lcp=Cgdnd3Mtd2l6EAMYADIGCAAQHhAWMgYIABAeEBYyBggAEB4QFjoHCAAQRxCwAzoFCAAQywFKBAhBGABKBAhGGABQ0A5YgxJg6BloAnABeACAAWiIAeQCkgEDMy4xmAEAoAEByAEIwAEB&sclient=gws-wiz 

### Why should this feature be included?

Because it's not logical to consider `<link>`  as a classic `<a>` 

historically `<a>` involved some text and it's "normal" to see a text-link with a `text-decoration:underline` 

But `<Link>`  concerns react-components by default, not text , and it's not very logical to modify every text embedded inside a component contained inside a `<Link>`  

Keep this behaviour as default if you want but please get us a way to override it without overriding the `<a>`

**Comment by timdorr** [comment]
The library isn't adding that style to your `<a>` elements. We don't provide any styles by default. That is coming from something else.

**Comment by tlecoz** [comment]
this is the default style of `<a>`

**Comment by tlecoz** [comment]
I made a minimal example to illustrate the problem. 

I created a new project using `yarn create react-app my-project` 
I remove every useless code from the "react basic template" 
I removed App.css and index.css 

Here is my code inside App.js : 

```
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom"
function App() {
  return (

    <Router>
      <Link to="/test">
        <div style={{ backgroundColor: "#cccccc" }}>
          <p>Line 1</p>
          <p>Line 2</p>
          <p>Line 3</p>
        </div>
      </Link>
      <Routes>
        <Route path="/test" element={<div>Hello World</div>} />
      </Routes>
    </Router>
  );
}

export default App;
```

And here is the result on the screen : 

![image](https://user-images.githubusercontent.com/272817/181788271-5ebfcc7e-37fb-43d5-ab83-66a53d605c96.png) 

As I said previously , because `<Link>` is based on `<a>` , it inherits the default css properties of `<a>` 
It means that the text appears blue and underline. 

That's why I'm asking you to add a default css-class to `<Link>` , for example "reactRouterDomLink". 
So we could be able to override this properties only for `<Link>`  not for every '<a>'  

Right now, if I want to disable the text-decoration:underline  inside my `<Link>` I must add a css-class to the link every time like that : 


<Link className="myClass" to="/test ><div>Hello World</div></Link>

.myClass{
     text-decoration:none;
}

and it's a bit boring to be forced to set this css-class by myself for every `<Link>` 

I think it would be preferable to be able to write that in the css only 

.reactRouterDomLink{
    text-decoration:none;
}

Do you understand what I mean ?

**Comment by awreese** [comment]
@tlecoz AFAIK RRD is unopinionated when it comes to CSS, or rather, they *are* and their opinion is they don't care and stay out of it. If you want styled `Link` components then you should/could handle this yourself. If you don't want to add a `className` prop to each `Link` component you render then create your own custom `Link` component and import and use that instead of RRD's `Link`.
