### ISSUE TITLE
[Bug]: Routes and lazy are used error

### ISSUE THREAD

**Issue by qq281113270** [remix-run/react-router#9107]
### What version of React Router are you using?

 "react": "^18.2.0",     "react-dom": "^18.2.0",

### Steps to Reproduce

An error is reported when using lazy to import components with routing。

![image](https://user-images.githubusercontent.com/20044598/181670393-2420c2f3-36dd-4259-96aa-96c78979f809.png)

code:

import React, {Suspense, lazy} from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
// import  Page1 from  '../pages/page1/index'
// import  Page2 from  '../pages/page2/index'

const Page1 = lazy(() =>
    import('../pages/page1/index')
);
const Page2 = lazy(() =>
    import('../pages/page2/index')
);
 

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Page1 />}></Route>
        <Route path="/page2" element={<Page2 />}></Route>
      </Routes>
    </BrowserRouter>
  );
}

Loading components is fine if you don't use lazy.

### Expected Behavior

Routes is used with lazy

### Actual Behavior

Routes and lazy are used error

**Comment by shreekeshmurkar** [comment]
@qq281113270 
Have you tried wrapping `Routes` inside `Suspense` with fallback property?

try following:

```
import React, {Suspense, lazy} from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';

const Page1 = lazy(() => import('../pages/page1/index'));
const Page2 = lazy(() => import('../pages/page2/index'));

export default function App() {
return (
    <div>
       <Suspense fallback={<div>Loading...</div>}>
         <Routes>
           <Route path="/" element={<Page1 />} />
           <Route path="about" element={<Page2 />} />
         </Routes>
      </Suspense>
    </div>
   );
}
```

**Comment by timdorr** [comment]
Can you please stop posting issues that are support questions? This issue tracker is only for bug reports and feature requests. This is neither. Please stop or I will be forced to block you.

**Comment by qq281113270** [comment]
Where should I mention the bug？

**Comment by qq281113270** [comment]
ok ， thank you
