### ISSUE TITLE
[Bug]: No longer allowed to nest MemoryRouter inside Router

### ISSUE THREAD

**Issue by dw-bayer** [remix-run/react-router#9109]
### What version of React Router are you using?

6

### Steps to Reproduce

```tsx
<Router>
    // all sorts of normal app stuff
    // ...
    // ... deep in a nested component
    <Popup>
        <MemoryRouter initialEntries={[match.url]}>
            <ComponentWithRoutesThatIsAlsoUsedWithNormalRouer />
        </MemoryRouter>
    </Popup>
</Router>
```

### Expected Behavior

We needed a way to take a component that exists in our normal routes with history.back() and redirects and gingerly place it into a dialog popup WITHOUT having any of the routing paths show up in the browsers url and without our in-app back buttons sending the user away from the dialog and still getting to navigate deeper into the component. Wrapping the MemoryRouter around the component nested inside the main Router worked without a hitch. Gave us a little Router sandbox.

### Actual Behavior

Now, in v6, we're barred from doing that. :(
Can this be a warning instead of an error?
Is there something else we could/should be doing?

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/7375#issuecomment-633689016

**Comment by dw-bayer** [comment]
ope. sorry. terrible browsing skills.
