### ISSUE TITLE
[Bug]: On Documentation page, "Docs Navigation" menu is hidden on large screen and not accessible anywhere else

### ISSUE THREAD

**Issue by theFreedomBanana** [remix-run/react-router#9115]
### What version of React Router are you using?

V6

### Steps to Reproduce

Go to the [documentation page](https://reactrouter.com/docs/en/v6).

### Expected Behavior

Being able to access the "Docs Navigation" menu.

### Actual Behavior

the "Docs Navigation" menu is hidden on large screen (it has `class="lg:hidden"`) and not accessible anywhere else to the extend of my knowledge.

**Comment by timdorr** [comment]
That is the same menu that is on the left side of the page. It's got `hidden lg:block` as a class to make it hide on small screens.
