### ISSUE TITLE
[Bug]: v6.4 Redirect loop in loader

### ISSUE THREAD

**Issue by MariusParasca** [remix-run/react-router#9122]
### What version of React Router are you using?

6.4.pre-10

### Steps to Reproduce

In the app that I'm developing, we have some tabs that when you click on them it would change the route. For example, I have the following: `abc/first` and `abc/second`, but somewhere in the app I redirect the user to `abc` then for this route I navigate the user to `abc/first` and from here the loop begins, it's just keep looping from loader to component and so on.

```
<Route path=":workspace" element={<Workspace />}>
  <Route path="abc" element={<Navigate to="first" replace />} />
  <Route
      path="abc/first"
      element={
        <AbcWrapper>
          <First />
        </AbcWrapper>
      }
      loader={FirstLoader}
    />
    <Route
      path="abc/second"
      element={
        <AbcWrapper>
          <Second />
        </AbcWrapper>
      }
     // possible loader here
    />
<Route />
  ```

### Expected Behavior

It should only redirect to `/abc/first` and not going in a loop

### Actual Behavior

It goes in a loop after redirection from `abc` to `abc/first`, basically it keeps going to navigate component and then to the loader and then back to navigate, therefore the loop begins

**Comment by brophdawg11** [comment]
I think this is related to https://github.com/remix-run/react-router/issues/9116, so we can look into it there.

However, in a data router the idiomatic way to do this would be the following - is this an option for you to move to?

```jsx
<Route path="abc" loader={() => redirect("/abc/first")} />
```

**Comment by MariusParasca** [comment]
When I do the redirect, I get the error: `No routes matched location "/abc/first"`. But if I go directly to the route works fine, this happens when the redirect is done

**Comment by brophdawg11** [comment]
oops, I missed the `:workspace` parent.  You'll need to account for that in your loader redirect.  How about:

```js
function abcLoader({ request }) {
  let path = new URL(request.url).pathname;
  return redirect(`${path}/first`);
}
```

**Comment by david-crespo** [comment]
@brophdawg11 is there any way to get a `replace` nav with `redirect()`?

**Comment by brophdawg11** [comment]
@david-crespo yeah - there's a small bug around redirect `historyAction` logic that's fixed in #9117 - should be merged soon!

**Comment by brophdawg11** [comment]
Should be available in the next prerelease (today or tomorrow)

**Comment by brophdawg11** [comment]
This is now released in `6.4.0-pre.12` 👍

**Comment by MariusParasca** [comment]
Great, it works with `<Navigate />` now, but the redirect seems not to do nothing. It does not navigate at all from the loader

**Comment by brophdawg11** [comment]
Could you clarify and/or provide a reproduction?  Are you trying to use both a `redirect()`and a `<Navigate>`?  Or are you saying that you've tried both and only `<Navigate>` is working?

**Comment by MariusParasca** [comment]
Only `<Navigate>` works, using `redirect()` does not redirect me anywhere, althougth the code goes through the loader function. Example:
```
<Route path=":workspace" element={<Workspace />}>
  <Route path="abc" loader={({ request }) => {
    let path = new URL(request.url).pathname;
    return redirect(`${path}/first`);
  }
} />
  <Route
      path="abc/first"
      element={
        <AbcWrapper>
          <First />
        </AbcWrapper>
      }
      loader={FirstLoader}
    />
    <Route
      path="abc/second"
      element={
        <AbcWrapper>
          <Second />
        </AbcWrapper>
      }
     // possible loader here
    />
<Route />
```

In the example when I go to `abc` it will stay on `abc` and not redirect to `abc/first`

**Comment by brophdawg11** [comment]
You have a `:workspace` parent route, are you navigating to `/workspaceId/abc` to trigger the redirect?  It seems to work fine for me here: https://stackblitz.com/edit/github-knme9n

**Comment by MariusParasca** [comment]
Not sure why it didn't work, not it works :sweat_smile:

Thank you for your help man!
