### ISSUE TITLE
[Bug]: useSearchParams initial values are local to the hook

### ISSUE THREAD

**Issue by hspier** [remix-run/react-router#9127]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Create two components A and B, B being a child of A such that:
`<A><B/></A>`.

For component A, use the useSearchParams hook and initialize it with a test value and directly log the resulting searchParams:
```
const [searchParams] = useSearchParams({ test: 'A'});
console.log(searchParams.toString());
```
This will log `test=A&parent=true`.

For component B, use the useSearchParams hook and initialize it with another value and log the resulting searchParam:
```
const [searchParams, setSearchParams] = useSearchParams({ test: 'B', child: 'true'});
console.log(searchParams.toString());
```
This will log `test=B&child=true`.

Now in B, set new parameters:
```
setSearchParams({test: 'B', child: 'true'});
``` 

On re-render, A will log `test=B&parent=true&child=true` while B will log `test=B&child=true` and also in the URL, the search part will have `test=B&child=true`. 

### Expected Behavior

I am expecting the initial values to be persisted in a way that any other component using useSearchParams on initialization will be able to read the values. If this is for performance reason, can another option be added that would act like the second option of the setSearchParams which would do a navigate? 

A workaround would consist in declaring a mount useEffect and simply call setSearchParams instead of providing the values as part of the initial values.

### Actual Behavior

Two components using useSearchParams ends up with their own copy of the values provided on initialization and even after setSearchParams, the values are never synced up with the URL resulting in a different representation of the search parameters.

**Comment by timdorr** [comment]
`defaultInit` is only for setting defaults on every search key if they are not provided. There is no way to communicate changes to your search value between different components, as they have their own independent local state. 

Communication can only be done with `setSearchParams`, which `navigate`s to a new location with the updated search value. But this is one-way; it only communicates the keys known to the navigating component's local state.

Again, there is no way to sync all states across multiple components. One way to illustrate this is with this component structure: `<A><B/><C/></A>` Where you now have two siblings that could have competing defaultInit values. Which one is right? There's no definitive answer for that.

If you mean to communicate state like that, you should be passing common data along props or context. That way anyone manipulating the search values can have the same core data to update.
