### ISSUE TITLE
[Bug]: history push does not match Route but changes url

### ISSUE THREAD

**Issue by sabarishnarain** [remix-run/react-router#9134]
### What version of React Router are you using?

react-router-dom: 6.2.2

### Steps to Reproduce

It appears react-router-dom "6.2.2" uses "history": "^5.2.0" and "react-router": "6.2.2" so not sure if this is a compatibility problem with the history library. 

Steps to repro:
1 invoke history.push to new url.
2. There is no component update so using a forceUpdate but it doesn't match the Route paths. 

### Expected Behavior

Router path should match. 

### Actual Behavior

No path match.

**Comment by timdorr** [comment]
You can't use any old instance of history outside of the router. It maintains its own instance internally. You need to use the APIs of React Router to change history.
