### ISSUE TITLE
[Bug]: broken link on server rendering guide section

### ISSUE THREAD

**Issue by Atabic** [remix-run/react-router#9135]
### What version of React Router are you using?

v5

### Steps to Reproduce

Just go to this [link](https://v5.reactrouter.com/web/guides/server-rendering) and scroll down to the bottom of the page to the last paragraph.

There you can see [React Router Config](https://github.com/remix-run/react-router/tree/main/packages/react-router-config)
Click this link and you will be redirected to a broken page on Github.

### Expected Behavior

It should redirect to the correct link which is maybe in **v5** branch.

### Actual Behavior

404 page

**Comment by Atabic** [comment]
I would like to pick up this issue as well for this change. Please guide me a little on where the docs are located and I will create a PR. Thanks

**Comment by timdorr** [comment]
I removed it from the docs in the repo now. I'm not sure if the rebuild for the website itself is still automatic, but that should get removed the next time it's built.
