### ISSUE TITLE
[Bug]: useParams is returning the value as a number

### ISSUE THREAD

**Issue by a777med** [remix-run/react-router#9136]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Define a route with a route param. E.g. `'/app/shop/:shopId/*'`.
2. Use `useParams` inside a component in the route like `const { shopId } = useParams()`.
3. Go to a route in the browser with the param `shopId` as a number. E.g. `'/app/shop/123/products'`.

### Expected Behavior

The param (shopId) should be a string. At least according to its TS type.

### Actual Behavior

The param (shopId) is actually a number.
`typeof shopId === 'number'`

**Comment by timdorr** [comment]
Something else is converting the type of that param. If you add `console.log(typeof id)` to [the modal example](https://reactrouter.com/docs/en/v6/examples/modal), you get back `string`.
