### ISSUE TITLE
[Bug]: Path score calculation clash

### ISSUE THREAD

**Issue by alex-ketch** [remix-run/react-router#9145]
### What version of React Router are you using?

18

### Steps to Reproduce

This bug report stems from investigating https://github.com/remix-run/remix/pull/3052, so please let me know if there's a better way of handling this issue upstream in Remix.

> Remix incorrectly figures out what to show in the /nested route. Instead of showing nested/index.jsx, it shows an empty nested/__pathless route, i.e. the contents of the nested/__pathless.jsx layout with nothing in the <Outlet />. The misinterpretation is broken down in https://github.com/remix-run/remix/discussions/3014#discussioncomment-2666749.
> 
> This only happens for routes nested at least one level deep, that's why the nested directory is here.

As far as I understood from poking around in the codebase, what happens is that an `index` route and a Pathless Layout Route end up with equal scores. Due to the pathless layout containing children it ends up higher up in the routes array and is matched first.

---

To reproduce:

Create a Remix project with the following routing structure.

```tree
app/routes
└── nested
    ├── __pathless
    │   ├── bar.jsx
    │   └── foo.jsx
    ├── __pathless.jsx
    └── index.jsx
```

Visit `/nested` in a broswer.

---

## Potential solution

I don't have insight into how the values for the scores were determined, but can make a PR with the following changes if this is the way to go.
By bumping the following values by 1, the issue seems to be resolved.
- `dynamicSegmentValue = 4`
- `indexRouteValue = 3`

Current values:
https://github.com/remix-run/react-router/blob/351a2a378880ad2a1704c2acf6c8f4f78b99d0b8/packages/react-router/lib/router.ts#L244-L251

### Expected Behavior

Visit `/nested` in a browser.
Expect to see content from `nested.jsx`

#### Scores
```ts
[{ path: '/nested/bar', score: 24 },
{ path: '/nested/foo', score: 24 },
{ path: '/nested/', score: 15 },
{ path: '/nested', score: 17 }]
```

### Actual Behavior

Visit `/nested` in a browser.
See content from `__pathless.jsx` instead.

#### Scores
```ts
[{ path: '/nested/bar', score: 24 },
{ path: '/nested/foo', score: 24 },
{ path: '/nested/', score: 15 },
{ path: '/nested', score: 15 }]
```

**Comment by brophdawg11** [comment]
This ends up being an issue in the way Remix generates the hierarchical route tree it provides to react router, so fixing on the remix side in https://github.com/remix-run/remix/pull/3986
