### ISSUE TITLE
[Bug]:  I got a problem about  the useNavigationType() give me  a 'pop'  when I click the forward arrow in the browser..

### ISSUE THREAD

**Issue by playerlife** [remix-run/react-router#9147]
### What version of React Router are you using?

react rouer v6

### Steps to Reproduce

useNavigationType() give me a 'pop' value when I click the forward arrow in the top browser bar.

### Expected Behavior

show me a 'push' not a pop

### Actual Behavior

show me a pop

**Comment by timdorr** [comment]
When a user clicks their navigation buttons in the browser UI, that is a `pop` event: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event You are "pop"ing a state onto or off of the stack.

**Comment by yknevenky** [comment]
> ### What version of React Router are you using?
> react rouer v6
> 
> ### Steps to Reproduce
> useNavigationType() give me a 'pop' value when I click the forward arrow in the top browser bar.
> 
> ### Expected Behavior
> show me a 'push' not a pop
> 
> ### Actual Behavior
> show me a pop

I am also experiencing the same error
