### ISSUE TITLE
[Bug]: https://v5.reactrouter.com/web/api/Route/location-object - broken link

### ISSUE THREAD

**Issue by tomlockwood-actu** [remix-run/react-router#9149]
### What version of React Router are you using?

v5

### Steps to Reproduce

Click uponst the link with the url `https://v5.reactrouter.com/location.md` in the `[location: object](https://v5.reactrouter.com/web/api/Route/location-object)` section.

### Expected Behavior

Takes me to the correct document.

### Actual Behavior

Does not take me to the correct document.

**Comment by timdorr** [comment]
I fixed this in the code now. It will be there on the next publish of the docs: 0713737a57ee58bc9035f6f206829f5b0c52c1cd
