### ISSUE TITLE
[Bug]: Documentation page does not replace "Switch" into "Routes" in Basic Examples

### ISSUE THREAD

**Issue by MohaElder** [remix-run/react-router#9152]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

```
npm install --save react-router-dom

//in App.js:
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";

```

### Expected Behavior

In the [npm registry](https://www.npmjs.com/package/react-router-dom), the project's version is 6.3.0, which does not support ``` <Switch> ``` anymore. If the user continues to follow the [tutorial](https://v5.reactrouter.com/web/guides/quick-start), they will expect an import error described in the Actual Behavior below. The Documentation site should change the current example code by replacing  ``` <Switch> ``` with ``` <Routes> ```.

### Actual Behavior

`export 'Switch' (imported as 'Switch') was not found in 'react-router-dom'`

**Comment by timdorr** [comment]
That is the v5 docs site.
