### ISSUE TITLE
[Bug]: useParams returning undefined when it shouldn't

### ISSUE THREAD

**Issue by Johannes5** [remix-run/react-router#9156]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

import {useParams, useLocation} from 'react-router-dom';

export function SomeComponent() {
    let {state, code} = useParams()
    let location = useLocation()
   
   React.useEffect(() => {
        console.log("state, code", state, code)
        console.log("location.seach", location.search)
        
    }, [state, code])
}

### Expected Behavior

The url looks like this:

http://127.0.0.1:3000/twitter-redirect?state=xKehBbyGRlZoIpCk-ry6ub1oXccRKQPc&code=dTA1cGpkQXk2OUxxcVNxVWh3TkZsdWZsalAxUzFlbVAyODlSMDN3WUpqblFEOjE2NjA1NzE2NjY4MzY6MTowOmFjOjE

and it should give me the state and code params

### Actual Behavior

while location.search returns
`?state=xKehBbyGRlZoIpCk-ry6ub1oXccRKQPc&code=dTA1c…AyODlSMDN3WUpqblFEOjE2NjA1NzE2NjY4MzY6MTowOmFjOjE`

state and code are always undefined.

**Comment by timdorr** [comment]
`useParams` is for route parameters, not the search string. You want `useSearchParams`
