### ISSUE TITLE
[Feature]: useLocation supports generics

### ISSUE THREAD

**Issue by guaijie** [remix-run/react-router#9164]
### What is the new or updated feature that you are suggesting?

type State = { from : string; base: string}
const location = useLocation<State>()

// types
export declare function useLocation<T = unknown>(): Location<T>;
export interface Location<T> extends Path {
    state: T;
    key: Key;
}

### Why should this feature be included?

Better type inference experience

**Comment by timdorr** [comment]
This would actually remove type safety, as you would be overriding `state` to that type. You should be using type narrowing to determine the type of `state` safely. A generic would be a hack to force that to work.

https://github.com/remix-run/react-router/pull/8370#issuecomment-974578233
https://github.com/remix-run/react-router/issues/8396#issuecomment-980829670
