### ISSUE TITLE
[Feature]: Add API to get matched route

### ISSUE THREAD

**Issue by mycroes** [remix-run/react-router#9168]
### What is the new or updated feature that you are suggesting?

This feature is similar to the `path` property of `useRouteMatch` in v5. Example:

```tsx
<Routes>
  <Route path="top" element={<Sample />}>
     <Route path="nested" element={<Sample />} />
     <Route path=":p" element={<Sample />} />
  </Route>
</Routes>

...

const Sample: React.FC = () => {
  return (
    <>
        {useRouteMatch()}
        <br />
        <Outlet />
    </>
  );
}
```

Expected output:
```txt
top
top/nested
top/:p
```

### Why should this feature be included?

I previously used `useRouteMatch` `path` property (v5) to get identifiers that user preferences are tied to. `useLocation` for v6 isn't suitable because:
1. When called from *top/nested* would change the identifier requested at *top*
2. Different parameter values would change the identifier (at *top/:p*)

`useHref` also isn't suitable because it suffers from issue 2 above.

For now I have resorted to the following:
```ts
import React from 'react';
import { RouteMatch, UNSAFE_RouteContext as RouteContext } from 'react-router-dom';

function cleanup(route: string) {
  return route.replace(/\/?\*?$/, '');
}

function matchesToPath(matches: RouteMatch<string>[]) {
  console.log(matches);

  if (!matches.length) return '/';

  return matches.reduce((prev, r) => r.route.path ? prev + '/' + cleanup(r.route.path) : prev, '');
}

function useRouteMatch() {
  const { matches } = React.useContext(RouteContext);

  const url = matchesToPath(matches);

  return url;
}

export default useRouteMatch;
```

I have spent a good amount of time searching for a solution, but I couldn't find anything outside of using the `RouteContext` and some manipulation.

I'm also not sure my implementation is perfect, I think it works for my needs, but even that I'm not sure of yet. Since it's based on non-public API I hope this can be implemented in the project.

**Comment by timdorr** [comment]
I think you can do the same thing using props on your element and Outlet's `context` prop.

But I also don't think I fully understand your use case. Why do you need the URL from the matches here? It seems like you're extracting data from the URL structure, which would suggest you should pass that as data via context or props. That's generally more stable to do.

**Comment by mycroes** [comment]
> I think you can do the same thing using props on your element and Outlet's `context` prop.

I'm not sure what the function of context on `Outlet` is, but for one I don't control the usage of `Outlet` where I want to get the routes and second I also need access to the route in hooks.

> But I also don't think I fully understand your use case. Why do you need the URL from the matches here? It seems like you're extracting data from the URL structure, which would suggest you should pass that as data via context or props. That's generally more stable to do.

I just want to get the full URL patterns so I can use them as identifiers. Small example: I have a *users* table with columns `username`, `id`, `firstName`, `lastName`, `memberOf`, .... You can show/hide columns, and because you don't want to choose columns every time you go to the users table the column selection is stored (doesn't really matter where). Now imagine I'm using the same renderer for the table in over 50 projects, often with over 50 different data types. I'd prefer to keep track of which table I want to store the visible columns for using the route from React Router. I'll also have tables like *user actions*, which also have per user routes (so you can add a link in the *user* table to *user actions* for that user). So my per-user-actions will probably live at **/users/:id/actions**. Now if I would take the route from `useLocation`, I'd get **/users/4/actions**, and if I'd use that to store my visible columns preference I'd still have to do that for every user separately.

So of course, I can add another argument to my hook or component for the preference identifier, but since they're one-to-one with the route they're rendered at (at least for my default tables), I'd just prefer to get the pattern from React Router. This also is exactly what I've been doing with React Router v5, but unfortunately I can't find an approach with v6 that works just as well (using the supported API, that is).

I hope this explains my usecase. I could probably properly implement it in React Router as well, instead of the current hacky solution.

**Comment by timdorr** [comment]
It really sounds like you should be doing this via props. You're having to coordinate URL structures in multiple places (both the Route's and within your components). This strongly binds your component rendering to outside state, which is a code smell in my experience. In particular, that makes testing hard, as you need a way to mock that state separately from just rendering the component.

Here's roughly what I mean:

```js
<Routes>
  <Route path="users/:id" element={<Users />}>
     <Route index element={<UsersTable columns={['username', 'firstName', 'lastName']} />} />
     <Route path="actions" element={<UsersTable columns={['username', 'actions']} />} />
  </Route>
</Routes>
```

Now your `UsersTable` component is controlled only via props. If you want to test it, you don't need to mock the URL somehow. This makes it easier to test or use in other contexts where the URL may not be in the structure you want, but you want a particular tweak on the way it renders. You don't need to necessarily change the code of the component to match a new URL structure.

**Comment by mycroes** [comment]
Your sample is lacking the exact thing I'm needing. My `Table` will be like this:

```tsx
const Table: React.FC<TableProps> = (props) => {
  const { columns, ... } = props;
  const route = useRouteMatch();
  const visibleColumns = usePreference(`table.${route}.visibleColumns`) ?? columns;

  return (<>...</>);
}
```

So of course I could move `const route = useRouteMatch();` to a prop (which I would then name `tableIdentifier` to be more specific with regards to it's use), but it would always be very similar to the route. So I would have `users` for the route `users`, I could possibly have `userActions` instead of `users/:id/actions`, `userAdd` for `users/add`, etc. etc., but honestly just using the routes as identifiers would be fine in most cases (and for any other case I could use a override using props anyway). Also, if I'd care about the identifiers to be camelcased instead of route patterns, I could probably get away with a single regex replace to get that sorted as well. Long story short, having access to the route pattern saves me from introducing another property on my component. Introducing another property also introduces the risk of accidental reuse of identifiers.

Last but not least, if my users table opens add or edit in a dlalog, the current location will change to add or edit, but the preference identifier for the table that's now in the background shouldn't change. That shouldn't be much of an issue though, because `useHref` obviously has the same constraint (but doesn't return the URL *pattern*, so won't suffice for parametrized URL's) and the implementation I provided works like that as well.

Also one last thing I want to chime into:

> Now your `UsersTable` component is controlled only via props. If you want to test it, you don't need to mock the URL somehow. This makes it easier to test or use in other contexts where the URL may not be in the structure you want, but you want a particular tweak on the way it renders. You don't need to necessarily change the code of the component to match a new URL structure.

So you recommend to avoid `useParams` because it ties components into React Router? What's the alternative? What's keeping anyone back from mocking `useParams`, or `useRouteMatch` for that matter?

**Comment by timzaak** [comment]
`useRouteMatch` is very useful for breadcrumb component,  just like 
```
url => matched pattern => breadcurmb
/person/2 => person/:id  => People/2
/person/2/relatives => person/:id/relatives => People/2/Friends
```

**Comment by timdorr** [comment]
This is now available via `useMatches`: https://reactrouter.com/en/main/hooks/use-matches

**Comment by delijah** [comment]
@timdorr But `useMatches` does not expose `pathnameBase`, unfortunately.
