### ISSUE TITLE
[Feature]: Search params in route loader function

### ISSUE THREAD

**Issue by ngunna** [remix-run/react-router#9171]
### What is the new or updated feature that you are suggesting?

**What version of React Router are you using?**
- 6.4.0-pre.12
- Using DataBrowserRouter

**Current Behavior**
```
loader: async (route) => {
       return {
             data: await fetchData(route.params.sortBy)
       };
}
```
Where sortBy is a query/search parameter in the URL. It is not included in params in the route loader function, since that appears to be reserved for proper path parameters (ex. id in `/example/:id`).

The definition for the loader function parameter is as follows:
```
interface DataFunctionArgs {
  request: Request;
  params: Params;
}
```

**Expected/Proposed Behavior**
```
loader: async (route) => {
       return {
             data: await fetchData(route.search.sortBy)
       };
}
```

Where `route.search` is an object representing the parsed search parameters in the URL, similar to what you would get from something like the useSearchParams hook.

The definition for the loader function parameter would look like:
```
interface DataFunctionArgs {
  request: Request;
  params: Params;
  search: URLSearchParams;
}
```

Which would apply it for LoaderFunctionArgs and ActionFunctionArgs who extend DataFunctionArgs, since it seems appropriate to have access to search params during actions as well.

### Why should this feature be included?

It should be included so that you can make network requests for data using search params in the route. Currently there is no way to request new data related to the search param that had changed in the component, without having to access the url via request and parsing out search parameters out manually.

This seems like a pretty obvious feature, which makes me suspicious that I am misunderstanding something, or it is currently in development and not yet available since this is all experimental yet.

**Comment by brophdawg11** [comment]
This information is included in the incoming `request` parameter so you can use existing web APIs (`Request`, `URL`, `URLSearchParams`) to get search params:

```js
async function loader ({ request }) {
  const sortBy = new URL(request.url).searchParams.get('sortBy');
  return {
    data: await fetchData(sortBy),
  };
}
```

See https://beta.reactrouter.com/en/dev/route/loader#request for more information
