### ISSUE TITLE
[Bug]: Using state with methods in navigation causes page to reload

### ISSUE THREAD

**Issue by alii** [remix-run/react-router#9172]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

We're fetching from some variables from an SDK that contain methods on them but would like to pass them to state in `useNavigate` calls. For example
```ts
const objectWithAMethod = {
	id: 1,
	getId() {
		return this.id;
	},
};

navigate('/path/to/page', {
	state: objectWithAMethod,
});
```

The navigate call will trigger an entire full page reload (à la `window.location.reload`)

### Expected Behavior

The call to `navigate` doesn't do a full page reload

### Actual Behavior

The page completely reloads

**Comment by timdorr** [comment]
You can't put non-serializable data into `state`. Basically, if it doesn't survive `JSON.parse(JSON.stringify(data))`, it doesn't go in `state`.

**Comment by alii** [comment]
Gotcha. Is there perhaps some more documentation on this? What is supported/not? Thanks :)
