### ISSUE TITLE
[Bug]: Installation with Vite needs an extra double-dash

### ISSUE THREAD

**Issue by Bam92** [remix-run/react-router#9178]
### What version of React Router are you using?

6

### Steps to Reproduce

Just run 

```# vite
npm init vite@latest router-tutorial --template react
```

### Expected Behavior

As of Vite current documation, you have to run 

```# vite
npm create vite@latest router-tutorial -- --template react
```

### Actual Behavior

It's said in your doc that to directly start a react project with Vite, you have to run 

```# vite
npm init vite@latest router-tutorial --template react
```

**Comment by timdorr** [comment]
This is fixed in the dev docs: https://github.com/remix-run/react-router/blob/dev/docs/getting-started/tutorial.md?plain=1#L25
