### ISSUE TITLE
[Bug?]: The doc is missing the summary

### ISSUE THREAD

**Issue by JesusTheHun** [remix-run/react-router#9186]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Visit the official documentation

### Expected Behavior

Having a summary menu to navigate quickly, like before.

### Actual Behavior

Looks like the Bitcoin whitepaper ?

**Comment by timdorr** [comment]
This is on the lefthand side: 

![image](https://user-images.githubusercontent.com/17882/186939606-80ef6f7a-61a3-4247-85ba-4e7bac5328e8.png)

On mobile, just click the caret at the top left: 

![image](https://user-images.githubusercontent.com/17882/186939715-d1ad9b73-6516-4437-a370-30921f80df70.png)

**Comment by JesusTheHun** [comment]
My bad I should have specified the url : https://reactrouter.com/en/v6.3.0/getting-started/tutorial (note the version is explicitly selected and not set to `main`).
On this page there is no menu, I don't know if that's expected or not.
