### ISSUE TITLE
[Feature]: Export internal history object used by react-router

### ISSUE THREAD

**Issue by Mikilll94** [remix-run/react-router#9193]
### What is the new or updated feature that you are suggesting?

Export internal `history` object used by react-router. Thanks to that change we would be able to remove "unstable" prefix from `unstable_HistoryRouter`. This would prevent a situation when there is a mismatch in versions between react-router internal `history` package and `history` installed in package.json.

### Why should this feature be included?

This would make `unstable_HistoryRouter` stable and ready to use in production. Currently developers may be reluctant to use "unstable" features on production.

**Comment by timdorr** [comment]
We can't export these, as [they are created at runtime when the Router is instantiated](https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L155).
