### ISSUE TITLE
[Feature]: hook for getting active subroute

### ISSUE THREAD

**Issue by grigandal625** [remix-run/react-router#9194]
### What is the new or updated feature that you are suggesting?

For example, there is:
```jsx
<Route path="home/*" element={<Home />}>
    <Route index element={<Main />} />
    <Route path="about" element={<About />} />
</Route>
```

I would like to have a hook that I would use inside `Home` like this:
```jsx
const Home = () =>
     useMyHook().activeSubPath === "about" ? (
         <>
             <h1>We are at about page</h1>
             <Outlet />
         </>
     ) : (
         <Outlet />
     );
```

### Why should this feature be included?

I could do that using `useLocation` and `useMatch`, but it requires more hardcode, and I'm looking for more beautiful solution

**Comment by timdorr** [comment]
We can't know that at the `Home` component's level, as we're above `About`'s level and that Route hasn't been matched yet. The closest thing you're looking for is [`useMatch`](https://reactrouter.com/en/main/hooks/use-match), but you should find a way to put that kind of route data within the route elements, not the layout element.
