### ISSUE TITLE
[Feature]: Prevent routing outside of the application context

### ISSUE THREAD

**Issue by AlexDelPab** [remix-run/react-router#9195]
### What is the new or updated feature that you are suggesting?

Custom hook for going back in history (could be a simple wrapper over navigate(-1)) and prevent routing outside application context. Check if we would route outside the origin url and if, go to fallback url (like app home page).

### Why should this feature be included?

Every time a user in our application clicks cancel or save on a detail page, we route them back to the previous page with navigate(-1). If a user would bookmark a detail page and clicks on save, he would be on the same page from where here originally came from (like google, etc.).

**Comment by timdorr** [comment]
You can do this with the `unstable_HistoryRouter` instead. Just pass a history instance that does this behavior into that Router.
