### ISSUE TITLE
[Bug]: Layout route doesn't work as expected with nested routes with dynamic segments

### ISSUE THREAD

**Issue by romanwozniak** [remix-run/react-router#9196]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

I have this simplified application, where the page layout and navigation are defined in the `Shell` component and then the nested application routes are defined in a separate component `App`:

#### src/Shell.js
```js
const Shell = () => (
  <BrowserRouter>
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route element={<PageLayout />}>
        <Route path="/app/*" element={<App />} /> 
      </Route>
  </BrowserRouter>
)
```

#### src/App.js
```js
const App = () => (
  <Routes>
    <Route index element={<Navigate to="projects/0" />} />
    <Route path="projects/:projectId" element={<ProjectDetails />} />
  </Routes>
)
```

The `PageLayout` component is defined as a dynamic segment-aware header and then the `Outlet` with rendered content from the `App`:

#### src/PageLayout.js
```js
const PageLayout = () => {
  const params = useParams();

  return (
    <>
       <h2>Project: {params.projectId}</h2>
       <Outlet />
    </>
  )
}
```

The problem is that the dynamic segment `projectId` is never available in the `params`, and instead, `params` contains only `{"*": "projects/101"}`.

Such a problem only occurs if the routes with the dynamic segments are defined under a nested `Route` element. Meaning, that if all the routes from `App.js` are defined directly in `Shell.js`, then everything works as expected:
```js
# src/Shell.js
const Shell = () => (
  <BrowserRouter>
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route path="/app" element={<PageLayout />}>
        <Route index element={<Navigate to="projects/0" />} />
        <Route path="projects/:projectId" element={<ProjectDetails />} />
      </Route>
  </BrowserRouter>
)
```

The reason why I would prefer to keep the nested routes to be defined via a separate component is that `App` is expected to be a remote component loaded via modules federation.

### Expected Behavior

When the application is accessed at `/app/projects/101`, then it should contain the following header:
```html
<h2>Project: 101</h2>
```

### Actual Behavior

When the application is accessed at `/app/projects/101`, then it should contain the following header:
```html
<h2>Project: </h2>
```

**Comment by timdorr** [comment]
This is how `useParams` is intended to work. It only works for Routes that are underneath a path that captures that parameter.

If you need access to a param higher up in the tree, [use `useMatch`](https://reactrouter.com/en/main/hooks/use-match).
