### ISSUE TITLE
[Bug]: Chrome reqeusts favicon.ico on every navigation change

### ISSUE THREAD

**Issue by jez9999** [remix-run/react-router#9197]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Create basic route setup with links in a navbar above it:

```
export default function Navbar(props) {
    return (
        <nav>
            <Link to="/">Home</Link>{' | '}
            <Link to="/tictactoe">TicTacToe game</Link>
        </nav>
    );
}

export default function App(props) {
    return (
        <BrowserRouter basename={props.baseUrl}>
            <Navbar />
            <Routes>
                <Route path="/" element={<Content />}>
                    <Route index element={<Home />} />
                    <Route path="tictactoe" element={<Game />} />
                </Route>
            </Routes>
        </BrowserRouter>
    );
}
```

When clicking on the links, each time you change to Home or TicTacToe game, Chrome requests favicon.ico (in network, dev tools).

### Expected Behavior

Chrome should only request favicon.ico the first time it needs it.

### Actual Behavior

Chrome requests favicon.ico on every navigation.

**Comment by timdorr** [comment]
It sounds like something else is happening, such as a full page reload. Regardless, this isn't something the library controls or that it can fix.

**Comment by jez9999** [comment]
Where could I get some help on it?  I'm pretty sure a full page load isn't happening.
