### ISSUE TITLE
[Feature]: Support a `reloadDocument` option in `navigate()`

### ISSUE THREAD

**Issue by mtoneil** [remix-run/react-router#9202]
### What is the new or updated feature that you are suggesting?

Support `reloadDocument?: boolean` in the `navigate()` options. It would work the same way that `<Link to="..." reloadDocument />` does (i.e. triggers a full page load).

### Short answer:

For parity with `<Link />`. I believe the only difference between `LinkProps` and `NavigateOptions` is that `NavigateOptions` is missing `reloadDocument`. If reloading the document is valid functionality for `Link`, then I believe it should be supported by `navigate`, too.

### My actual use-case:

My SPA occasionally polls the server to see if there is a new version of the application. Upon detecting a new version, the user's next navigation should cause a document reload so they can download the new version of the application. This is quite seamless and a better UX than rendering a banner asking the user to refresh.

Currently this ability is supported by `<Link />`. I have a custom Link component which wraps react-router's Link, but it consults my own VersionContext (which stores the current version and the server's version from the last poll) to see if it should specify `reloadDocument` or not.

This works great for links, but there is also a lot of navigation via `navigate` (mainly after form submissions or other async processing) which I would like to support this behavior as well. If `navigate` supported something like `navigate(to, { reloadDocument: true })`, then I can make my own wrapper hook which sets `reloadDocument` automatically the same way that I have for `Link`.

**Comment by timdorr** [comment]
All that `reloadDocument` does is remove the special `onClick` handler from the generated `<a>`, turning it into a normal link. You can do this same thing in your code with `location.href = '/path'`. The big difference with `navigate` is that we don't know if you have a DOM available and this will work. You can determine that on your own and make the alternative call.

**Comment by misha-erm** [comment]
@mtoneil hey,
did you find a solution for this? At the moment I'm thinking about calling `window.location.reload()`  as soon as `useNavigation().state` becomes 'idle' after calling `navigate` or just listening to location and using some global state to reload
```
 const location = useLocation();

  useEffect(() => {
    if (shouldReload) {
      window.location.reload()
    }
  }, [location]);
```

**Comment by mtoneil** [comment]
@misha-erm My solution was just to make my own hook which wraps `useNavigate` and also consults my context which tells me if the app is out of date and needs a full page refresh or not. If it does need a refresh, I call `location.href = newPath`, otherwise I call `navigate(newPath)`.
