### ISSUE TITLE
[Bug]: In documentation website

### ISSUE THREAD

**Issue by suraj5969** [remix-run/react-router#9204]
### What version of React Router are you using?

6

### Steps to Reproduce

NO

### Expected Behavior

A Error while browsing through documentaion website

### Actual Behavior

Hi,
I was reading the docs for migrating from v5 to v6 and while navigating to home page I got an Application Error. I have attached the error screenshot below.

I was reading [this](https://reactrouter.com/en/v6.3.0/upgrading/v5) page and gone back (ALT + Left arrow key) to [this](https://reactrouter.com/en/v6.3.0) page and got an error.

![image](https://user-images.githubusercontent.com/58414924/187896626-eecd6689-26ee-4ef0-8989-63f350dc8828.png)

I tried to again go back and forward to see Error still arises but I didn't got any error later.
I am using Microsoft Edge on Ubuntu 22.

Thanks.

**Comment by timdorr** [comment]
I believe this was a temporary issue. I'm unable to reproduce this.
