### ISSUE TITLE
[Bug]: withRouter wrapper from documentation does not work with Typescript

### ISSUE THREAD

**Issue by BearCooder** [remix-run/react-router#9206]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

From the FAQ: https://reactrouter.com/en/v6.3.0/faq

This question usually stems from the fact that you're using React class components, which don't support hooks. In React Router v6, we fully embraced hooks and use them to share all the router's internal state. But that doesn't mean you can't use the router. Assuming you can actually use hooks (you're on React 16.8+), you just need a wrapper.

```
import {
  useLocation,
  useNavigate,
  useParams,
} from "react-router-dom";

function withRouter(Component) {
  function ComponentWithRouterProp(props) {
    let location = useLocation();
    let navigate = useNavigate();
    let params = useParams();
    return (
      <Component
        {...props}
        router={{ location, navigate, params }}
      />
    );
  }

  return ComponentWithRouterProp;
}
```

I use the exact same wrapper but TS is screaming that `Component` and `props` is type of any. Now I can of course just use the type any to get rid of the error and it works but I want to avoid that - thus my issue is what are the correct types? I could not find any information. I tried `React.Component` for `Component` but then I get the error `JSX element type 'Component' does not have any construct or call signatures`

```
function withRouter(Component: **type?**) {
  function ComponentWithRouterProp(props: **type?**) {...
```

### Expected Behavior

With correct types provided it throws no errors.

### Actual Behavior

Parameter 'Component' implicitly has an 'any' type.

Parameter 'props' implicitly has an 'any' type.

The provided wrapper doesnt work with Typescript.

**Comment by timdorr** [comment]
This isn't Typescript code, so getting it to work in another language is left up to the user.

But what you're looking for is React.ComponentType, which is a union of ComponentClass and ComponentFunction.

**Comment by BearCooder** [comment]
Ok thank you for your help. Just last question if you can help please. When I use for Component - `Component: React.ComponentType` then TS throws an error at my router in the return - `router={{ location, navigate, params }}`

```
Type '{ router: { location: Location; navigate: NavigateFunction; params: Readonly<Params<string>>; }; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'router' does not exist on type 'IntrinsicAttributes'.
```

So this throws a new error, I think should not happen?
