### ISSUE TITLE
[Feature]: react-router  asynchronous on-demand load code shards

### ISSUE THREAD

**Issue by qq281113270** [remix-run/react-router#9214]
### What is the new or updated feature that you are suggesting?

I want React-Router to implement on-demand asynchronous loading and code splitting, and to be compatible with SSR-synchronous rendering and client-side asynchronous on-demand loading and rendering, where the client-side needs to implement code splitting.

### Why should this feature be included?

I need this function when using REACT SSR for rendering, because the server needs synchronous rendering, but my client needs asynchronous loading and code splitting. If I do not do this, the homepage loading file will become too large when my project is getting bigger and bigger. Fortunately, I have implemented such a function. I have written such a function package component. I hope you can have a look at it when you are free. I want my Github component to get more stars. My Github component address is ：https://github.com/qq281113270/react-lazy-router-dom ， thank you 。

**Comment by timdorr** [comment]
This isn't the responsibility of a routing library. If you want route elements to be loaded asynchronously (such as with React.lazy), that is left up to you to implement. 

Some of what you may need for this, such as data loading, is already coming in 6.4: https://reactrouter.com/en/dev/getting-started/overview#data-loading

**Comment by qq281113270** [comment]
React.lazy SSR is not supported。loader is promise  Load routes?

**Comment by qq281113270** [comment]
Can you see the routing of my implementation? Make me a friendly connection if you can  ， My Github component address is ：https://github.com/qq281113270/react-lazy-router-dom ， thank you 。

**Comment by qq281113270** [comment]
> I want React-Router to implement on-demand asynchronous loading and code splitting, and to be compatible with SSR-synchronous rendering and client-side asynchronous on-demand loading and rendering, where the client-side needs to implement code splitting.

React.lazy SSR is not supported。loader is promise Load routes?

Can you see the routing of my implementation? Make me a friendly connection if you can ， My Github component address is ：https://github.com/qq281113270/react-lazy-router-dom ， thank you 。
