### ISSUE TITLE
[Bug]: 6 high severity vulnerabilities when I install react-router-dom into my project

### ISSUE THREAD

**Issue by diniduhewage** [remix-run/react-router#9215]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Create a new react app
2. install react-router dom using `npm install 'react-router-dom'`

### Expected Behavior

Install package without any vulnerabilities

### Actual Behavior

The package gets installed successfully. But shows message **6 high severity vulnerabilities**

**Comment by timdorr** [comment]
I just created a fresh package and install the library. I got no vulnerabilities. This is coming from something else you have installed.

```
$ npm i react-router-dom

added 10 packages, and audited 11 packages in 837ms

found 0 vulnerabilities
```

**Comment by leosv123** [comment]
May I know what is the issue, though i have installed in new react app, I am getting this issue.

**Comment by shafferM-eng** [comment]
Having the same problem
Tried updating npm & node to see if an updated version of cra would help but still performs the same.
Initialized a blank node project and react-router-dom installed with no vulnerabilities so it must be cra, but i have no clue how

**Comment by JuniorMKJ** [comment]
Bonjour le team, je me retrouve dans un problème avec react-router-dom, installer avec 116 vulnérabilité et quand j'utilise NavLink ou Link le projet échoué de se lancer et j'ai une erreur du genre : failed to compile
![1714202471840699800938607728471](https://github.com/remix-run/react-router/assets/29332212/bc5ec6cd-c219-40f8-9fcc-58546e7b3771)
