### ISSUE TITLE
[Feature]: ssr rendering  lazy， react-lazy-router

### ISSUE THREAD

**Issue by qq281113270** [remix-run/react-router#9216]
### What is the new or updated feature that you are suggesting?

I want React-Router to implement on-demand asynchronous loading and code splitting, and to be compatible with SSR-synchronous rendering and client-side asynchronous on-demand loading and rendering, where the client-side needs to implement code splitting.

### Why should this feature be included?

I need this function when using REACT SSR for rendering, because the server needs synchronous rendering, but my client needs asynchronous loading and code splitting.   If I do not do this, the homepage loading file will become too large when my project is getting bigger and bigger.   Fortunately, I have implemented such a component.   I have written such a function package component.   I hope you can have a look at it when you are free.  If possible, could you give me a friendship connection?
I want my Github component to get more stars.   My Github component address is ：https://github.com/qq281113270/react-lazy-router-dom ， thank you 。

**Comment by timdorr** [comment]
Please stop opening these duplicate issues.
