### ISSUE TITLE
Route Element By Name

### ISSUE THREAD

**Issue by sarankup** [remix-run/react-router#9230]
### What is the new or updated feature that you are suggesting?

Hi,

In my application, I wish the routes dynamically from the database records. Is it possible to refer Element by string instead of React Element?

For example, here is what available
`<Route path="/apps" element={<Apps />} />`

I wish to have 
`<Route path="/apps" element='MyComponent' />` where MyComponent is a String but the there is a JS Component available in the same name.

Thanks in advance.

### Why should this feature be included?

To add dynamic router.

**Comment by timdorr** [comment]
That isn't how React itself works, as we don't know what component to render from just a string. You would have to implement this lookup yourself:
```js
<Route path="/apps" element={<Lookup component="Apps" />} />
```
