### ISSUE TITLE
[Feature]: Alias for index routes

### ISSUE THREAD

**Issue by jez9999** [remix-run/react-router#9232]
### What is the new or updated feature that you are suggesting?

When I set up an index route at the moment, I can have my `NavLink` get the active class when it is matched but not when any of its children are matched by using the `end` attribute:

```
<NavLink to="." className={applyNavClass} end>Summary</NavLink>
<Routes>
    <Route index element={<Summary />} />
    <Route path="detail" element={<Detail />} />
</Routes>
```

However, if I add an alias (eg. `/summary`) for the index route, the `NavLink` to the index route will not get the active class when the alias is navigated to because of the `end` attribute:

```
<NavLink to="." className={applyNavClass} end>Summary</NavLink>
<Routes>
    <Route index element={<Summary />} />
    <Route path="summary" element={<Summary />} />
    <Route path="detail" element={<Detail />} />
</Routes>
```

I can remove the `end` attribute, but I don't want to do this either because then the `NavLink` will be active for `/detail` as well.

### Why should this feature be included?

There should be a way to have an alias for an index path, whereby you can have the `NavLink` be active for the index path or the alias.

**Comment by timdorr** [comment]
Having two URLs match a NavLink goes against its design. It's also a potentially poor UX, as you now have duplicate URLs that can confuse your users. A better way to handle this is to just redirect from the index route to the specific path:

```js
<Routes>
    <Route index element={<Navigate to="summary" replace />} />
    <Route path="summary" element={<Summary />} />
</Routes>
```

**Comment by jez9999** [comment]
@timdorr Not ideal really, that causes a brief flicker when the route is navigated to as it changes to the /summary path.
