### ISSUE TITLE
[Documentation]: Documentation's links lead to the url's ending with .md, and that doesn't seem to exist

### ISSUE THREAD

**Issue by nemonemi** [remix-run/react-router#9234]
### What is the new or updated feature that you are suggesting?

On the documentation screen Overview: https://reactrouter.com/en/v6.3.0/getting-started/overview
clicking on these links;
![image](https://user-images.githubusercontent.com/77624664/189495165-a5fdedad-15c4-433f-a88a-801be585b7a8.png)
navigates to the corresponding URLs ending with the `.md`, and they don't seem to exist.
e.g. https://reactrouter.com/en/v6.3.0/getting-started/tutorial.md
Accessing the same URL without the extension works.
https://reactrouter.com/en/v6.3.0/getting-started/tutorial

### Why should this feature be included?

Improves documentation usage.

**Comment by Darkmift** [comment]
anyone on the dev team is looking into this?
6.4 changed it all and the least you can do is maintain a link on npm

**Comment by timdorr** [comment]
Unfortunately, we can't change this because it's tied to a git tag. The links are directly to the left in the sidebar, so while this is a minor breakage, it's not the biggest thing in the world and we aren't going to fix it.

**Comment by Darkmift** [comment]
Nothing I can say to demonstrate better than your last reply how much you care about your consumers.
