### ISSUE TITLE
[Feature]: resolve path for delta type navigation

### ISSUE THREAD

**Issue by alexburkowskypolysign** [remix-run/react-router#9235]
### What is the new or updated feature that you are suggesting?

We can currently use optional `state` to track a users navigation and provide some level of accessible back navigation by grabbing the previous path in state and setting that as the `to` prop. This takes a bit of work to get to work consistently, though. 

Navigation through deltas like `navigate(-1)` is already available, so the path string information should be available under the hood in the history API. If react-routers API like `resolvePath` could provide this path string, we could provide to the the `to` prop to provide an accurate generated URL to users for a more accessible navigation experience. 

The best option would be to allow `<Link />` to take a number like `-1` as its `to` prop similar to `navigate` and we can rely on react-router to handle the path resolution

### Why should this feature be included?
Accessibility in delta navigation

```ts
const path = resolvePath(-1)

//OR

const path = useResolvedPath(-1)

// OR - Best option

<Link to={-1} /> 
```

**Comment by timdorr** [comment]
Unfortunately, we can't do this. We can only know about navigations that happen within the same instance of the page, where we are tracking them as changes via the History API. If the user hits refresh in their browser (or visits from another site), we lose access to the previous URL information as a part of standard browser security/privacy measures. That would result in this API returning different results depending on the source of the navigation. 

Also, while the types don't support it, you can do `<Link to={-1} />` currently.

**Comment by alexburkowskypolysign** [comment]
got ya. I kinda figured that was the case, but doesnt hurt to ask :). If the types can be fixed to support the Link usage, that would be sufficient.

**Comment by whyatem** [comment]
> Also, while the types don't support it, you can do `<Link to={-1} />` currently.

@timdorr by "currently" you mean this is this a subject to change? If not, is there a reason the types don't support it and it's not mentioned in documentation?
