### ISSUE TITLE
[Bug]: Memory Router doesn't match initial entries

### ISSUE THREAD

**Issue by AugustoZanoni** [remix-run/react-router#9237]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

I'm using Memory Router to handle routes on my React Web App

I have a few routes

MemoryRouter initialEntry
Route "/" --> <PrivateRoute/>
Route "login"
Route "conference"

Memory router does not allow me to get route from browser url, so I'm getting it through window.location.pathname and passing it to initialEntry parameter on MemoryRouter, but when I pass the "conference" route, it doesn't go to conference (the order doesn't matter, I've tried), it looks on my "/" for internal routes that may match, even if it has a match before

On my "/" route, I have a component that do a Navigate to login when you are not authenticated, but it should not enter this route, because it has a match outside the auth paths. 

It works fine with BrowserRouter, but on MemoryRouter it looks on every possible path, even if it has a match on the top level

### Expected Behavior

initial entry = conference

render conference

### Actual Behavior

initial entry = conference

render privateRoute that leads to login

(private route has a ternary<outlet/>:<navigate to='login'/>

**Comment by brophdawg11** [comment]
👋 I think we need a little more info on your setup and route hierarchy here.  Are you able to provide a simple reproduction of your use case in a codesandbox?  Thanks!

**Comment by AugustoZanoni** [comment]
I was doing the sandbox, then I realize it was my mistake. Thanks for the reply
