### ISSUE TITLE
[Bug]: react-router-dom does not list dependency @remix-run/router

### ISSUE THREAD

**Issue by alok0** [remix-run/react-router#9243]
### What version of React Router are you using?

6.4

### Steps to Reproduce

- install `react-router-dom` with yarn berry.

`react-router-dom` 6.4 now depends on `@remix-run/router` and while `react-router` has it listed as a dependency, `react-router-dom` does not.

### Expected Behavior

bundle correctly.

### Actual Behavior

See warnings like:
```
[vite]: Rollup failed to resolve import "@remix-run/router" from ".yarn/__virtual__/react-router-dom-virtual-104dcc9b05/0/cache/react-router-dom-npm-6.4.0-6eb09f3674-3d78124045.zip/node_modules/react-router-dom/dist/index.js".
```

**Comment by Stijnkool** [comment]
Having the same issue:
```
Cannot find module '@remix-run/router' from '.yarn/__virtual__/react-router-dom-virtual-d44bda6483/0/cache/react-router-dom-npm-6.4.0-6eb09f3674-5595bb168c.zip/node_modules/react-router-dom/dist/umd'
```

**Comment by Stijnkool** [comment]
I am using modern yarn. A temporary fix can be to define the dependency manually in a `.yarnrc` file.
```
packageExtensions:
  react-router-dom@*:
    dependencies:
      "@remix-run/router": "*"
```
See https://yarnpkg.com/configuration/yarnrc/#packageExtensions

**Comment by timdorr** [comment]
If someone could make a PR for this, that would be great!

**Comment by marvinruder** [comment]
@timdorr Here you go!

**Comment by rwb196884** [comment]
Seems to be still broken?
