### ISSUE TITLE
[Preload Option with Link]: 

### ISSUE THREAD

**Issue by MiltonAkash** [remix-run/react-router#9251]
### What is the new or updated feature that you are suggesting?

The react router v6 with data loader is great. It will be better if it also supports preloading them on Link hover or as they enter viewport. 

### Why should this feature be included?

So the data can be fetched cleanly and makes experience for SPA apps better

**Comment by timdorr** [comment]
React Router doesn't serve as a cache. We leave that to other libraries. As such, preloading is not really an optimization we want to get into.

There may also be other actions you wish to run when preloading, such as only requesting partial data to save resources. It would be easier to handle this via an `onHover` on `Link` instead.
