### ISSUE TITLE
[Bug]: MemoryRouter looses state of initial entries in v6.4.0

### ISSUE THREAD

**Issue by ddolcimascolo** [remix-run/react-router#9265]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

See the Sandbox at https://codesandbox.io/s/react-router-issue-9265-p8nx49 and simply downgrade `react-router-dom` to v6.3.0 to see the state value being rendered.

### Expected Behavior

MemoryRouter does not loose state of initial entries.

### Actual Behavior

MemoryRouter looses state of initial entries.

**Comment by ddolcimascolo** [comment]
This breaks Jest tests basically, where we use `<MemoryRouter />`.  
The production application use `<BrowserRouter />` is not impacted and works fine in v6.4.0.

**Comment by ddolcimascolo** [comment]
Am I the only one blocked by this? 

Remix team, do you think this is something that can be fixed by someone that has never contributed to react-router? :)

**Comment by ddolcimascolo** [comment]
@timdorr I saw your answer in https://github.com/remix-run/react-router/issues/9273. Any chance this regression has the same cause?

**Comment by brophdawg11** [comment]
Thanks for the bug report and reproduction!  Pushed a fix for this in #9288 and we should be able to get a patch out early this week 👍

**Comment by ddolcimascolo** [comment]
@brophdawg11 Is a release still planned this week?

**Comment by ddolcimascolo** [comment]
Thx for the release!

**Comment by brophdawg11** [comment]
👍 let us know if you run into any issues in 6.4.1!
