### ISSUE TITLE
[Bug]: idx dissapeared from window.history.state in 6.4.0

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [remix-run/react-router#9273]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

Check that in React Router version 6.4.0 we dont have the property idx in window.history.state

### Expected Behavior

Have property idx in window.history.state

### Actual Behavior

Without property idx in window.history.state

**Comment by timdorr** [comment]
We don't put anything into state. That lives in your own code. Without an example, I have to assume this is on your end.

**Comment by JoseBuendiaDigio** [comment]
@timdorr You can see it here. 

https://codesandbox.io/s/react-router-issue-9265-forked-h5s1yq

If you put react-router-dom 6.3.0 and you refresh the navigator of codesandbox you will see idx.
If you put react-router-dom 6.4.0 and you refresh the navigator of codesandbox you will null.

I think this is a bug

**Comment by tgyou** [comment]
@timdorr 
I understand that we shouldn't rely on it.

but, i'm also using `idx` key, so I cannot update it and keep it at 6.3.0.
is there a way to attach the `history` library like before?

**Comment by timdorr** [comment]
No, 6.4 doesn't use that library at all anymore.

**Comment by tgyou** [comment]
i got it, thanks for the response.  👍

**Comment by JoseBuendiaDigio** [comment]
And how can I know if I have a previous page in the stack? Because when I did it. I only finded this property. Any other property that inform about this?

Thanks.

**Comment by powelski** [comment]
So is it still using `idx` or not? I checked in 6.15 and 6.16 and it still gives me `{idx: 0}`.

**Comment by JoseBuendiaDigio** [comment]
@powelski As I remember they re-added it

**Comment by powelski** [comment]
@JoseBuendiaDigio I see, thanks! Do you know how to reliably update page's state with React Router? Calling `history.replaceState(...)` doesn't seem to go with the flow of the hooks, plus I'm afraid to overwrite the existing state, as I'm not sure if it's required for the library to work properly.

**Comment by JoseBuendiaDigio** [comment]
@powelski mmm, I dont know, add a new issue and the React Router team will reply you
