### ISSUE TITLE
[Bug]: ReloadDocument to treat it  as an href doesn't seem to work

### ISSUE THREAD

**Issue by vidjuheffex** [remix-run/react-router#9281]
### What version of React Router are you using?

6.4dev

### Steps to Reproduce

Have a link, `to` is: `https://twitter.com/(profile)` ,`reloadDocument` is set to `true`, 

Goes to (my-current-route)/https://twitter.com

If I set it to `//twitter.com/(profile)`

the linking works but twitter blocks the loading (same url works if I copy and paste it into a new browser window):
`twitter.com is blocked twitter.com refused to connect.

### Expected Behavior

open twitter.com to the profile properly like using an a tag

### Actual Behavior

twitter blocks connection because of whatever is going on with the Link component

**Comment by kiliman** [comment]
You should only use the `<Link>` component for app routes. To link to an external URL, use the standard `<a>` tag.

```ts
<a href="https://twitter.com/(profile)">Twitter</a>
```

**Comment by vidjuheffex** [comment]
https://reactrouter.com/en/dev/components/link

^ I see I'm misreading the last part of the first paragraph as far as why to do that.
