### ISSUE TITLE
[Bug]: Combining state with params in useNavigate

### ISSUE THREAD

**Issue by matthew1809** [remix-run/react-router#9283]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Try

```
navigate(
  { 
   pathname: "/search",
   search: `?${createSearchParams({ query: someQuery })}`,
   state: { someAttributeName: someAttributeValue }
  }
);
```

Note that the query params are passed in the URL but state will be null.

2. Try

```
navigate(
   "/search",
   {
      search: `?${createSearchParams({query: someQuery})}`,
      state: { someAttributeName: someAttributeValue }
   }
);
```

Note that the state is passed but the query params are not applied

### Expected Behavior

Able to pass state and query params in same navigate call, and have both applied 

### Actual Behavior

One or the other are applied depending on syntax used

**Comment by timdorr** [comment]
`state` is part of the second argument:
```js
navigate(
  { 
   pathname: "/search",
   search: `?${createSearchParams({ query: someQuery })}`
  },
  {
   state: { someAttributeName: someAttributeValue }
  }
);

**Comment by mikeymop** [comment]
Just following up on this, because it might not be obvious.

What ended up connecting is:

`SourceComponent.jsx`
```js
import { useNavigate } from "react-router";
navigate("/success", { state: { ...my.data } });
```
`RecipientComponent.jsx`
```js
import { useLocation } from 'react-router';
const location = useLocation();
const props = location.state.payload;
```

Hope this helps.
