### ISSUE TITLE
[Feature]: Render a JSX while loader is waiting to finish

### ISSUE THREAD

**Issue by iluvkoohi** [remix-run/react-router#9287]
### What is the new or updated feature that you are suggesting?

will simplify things instead of establishing a condition and show a spinner inside the element.

### Why should this feature be included?

When the route loader is not yet finished, it would be excellent to provide a loading animation.

**Comment by timdorr** [comment]
You use the `useNagivation` hook for this. An example is in the tutorial: https://reactrouter.com/en/main/start/tutorial#global-pending-ui

**Comment by iluvkoohi** [comment]
> You use the `useNagivation` hook for this. An example is in the tutorial: https://reactrouter.com/en/main/start/tutorial#global-pending-ui

Hi, timdorr. Thank you for this

**Comment by iluvkoohi** [comment]
> You use the `useNagivation` hook for this. An example is in the tutorial: https://reactrouter.com/en/main/start/tutorial#global-pending-ui

```
path: "/somewhere",
loader: async () => {
  await fetchDataFromSomewhere();
}
```

The thing is, when a route has a "loader" navigating to that particular route, there is a delay. Any ideas on how to navigate smoothly without having a delay due to async await?
