### ISSUE TITLE
[Bug]: path includes CJK characters can not be matched

### ISSUE THREAD

**Issue by yesmeck** [remix-run/react-router#9291]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

1. Visit https://stackblitz.com/edit/github-yjdjq8-upqh4l
2.  Click "你好"

### Expected Behavior

The page shows "你好"

### Actual Behavior

The page shows blank. After refreshing the page, it shows "你好" correctly.

**Comment by timdorr** [comment]
Duplicate of #8577
