### ISSUE TITLE
[Bug]: react-router-dom tried to access @remix-run/router, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by simPod** [remix-run/react-router#9298]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

Require with Yarn pnp which is strict about declaring dependencies.

### Expected Behavior

No issues

### Actual Behavior

Yarn pnp gives:

> react-router-dom tried to access @remix-run/router, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

If a package uses a dependency, it must be declared in that package. Providing it via sub-level dep is not correct.

**Comment by brophdawg11** [comment]
This is a duplicate of #9243  which is fixed in dev and will go out soon in a 6.4.1 release 👍
