### ISSUE TITLE
[Feature]: Support hot loader with react-router ^6.x.x version

### ISSUE THREAD

**Issue by vicodinvic1** [remix-run/react-router#9302]
### What is the new or updated feature that you are suggesting?

It would be great if it is possible to use react-hot-loader (or some another hot loader) and react-router v6 at the same time.

There is an issue about it already, and it is closed but there is no solution though:
https://github.com/remix-run/react-router/issues/8415

Error: [ProxyFacade] is not a component. All component children of must be a or <React.Fragment>

### Why should this feature be included?

Due to the error mentioned above ^
it is not possible to keep use react-hot-loader or as an alternative [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) (as it was suggested in that issue as well) to keep redux store up to date, 'cause without hot-loader your app crashes due to redux state drop when you change redux-related files.

**Comment by timdorr** [comment]
This message comes from when we start traversing the children of your `<Routes>` components: 

https://github.com/remix-run/react-router/blob/1fa73a9a1ba702fc611b6f9c3d57494741c84186/packages/react-router/lib/components.tsx#L575-L580

The only way this can occur is if you are putting something besides a `<Route>` or `<>` inside your `<Routes>` directly. You should only be using the `element` prop of `<Route>` to render components for a route, not it's `children`.

**Comment by CalebJamesStevens** [comment]
> This message comes from when we start traversing the children of your `<Routes>` components:
> 
> https://github.com/remix-run/react-router/blob/1fa73a9a1ba702fc611b6f9c3d57494741c84186/packages/react-router/lib/components.tsx#L575-L580
> 
> The only way this can occur is if you are putting something besides a `<Route>` or `<>` inside your `<Routes>` directly. You should only be using the `element` prop of `<Route>` to render components for a route, not it's `children`.

I'm still seeing this error today. I'm not sure if react-hot-loader is affect the children somehow or not, but if you code shows that Route is the only type of child of Routes, it does not matter.
