### ISSUE TITLE
[Bug]: URL not found after vite build with base option

### ISSUE THREAD

**Issue by NicoBru31** [remix-run/react-router#9318]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

1. In `vite.config.js` set `base: /foo/`
2. Build your project
3. Serve the built project with a `vite preview`
4. Go to `http://localhost:4173/foo` : you'll get a blank page
5. Go to `http://localhost:4173/foo/` : it works fine

My Router :
```javascript
const Router = () => (
    <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/dashboard/:dashboardUuid/tabs" element={<ManageTabs />} />
        <Route path="/dashboard/:dashboardUuid" element={<Dashboard />} />
        <Route path="*" element={<NotFound />} />
    </Routes>
);
```

### Expected Behavior

In previous React Router versions `http://localhost:4173/foo` behaved the same way as `http://localhost:4173/foo/`. I'd like to keep this behaviour

### Actual Behavior

`http://localhost:4173/foo` gives a blank page

**Comment by timdorr** [comment]
This isn't a bug with React Router. It's a Vite thing.
