### ISSUE TITLE
[Bug]: Getting a "useNavigation must be used within a DataRouterStateContext" when using BrowserRouter

### ISSUE THREAD

**Issue by anchann** [remix-run/react-router#9323]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

We use a custom built routing system (Using Fable/F#, want type-safe routes, etc) which is based on having BrowserRouter/NativeRouter as a top level wrapper of the app, and useHistory/useLocation hooks internally to figure out the current route and to do navigation. Now I'm attempting to upgrade to v6, and having done the requisite updates to useNavigation, the app compiles, but when running it in the browser, fails with

```
useNavigation must be used within a DataRouterStateContext
```

on the console. I read through the docs and a bunch of the react-router implementation code. It seems that the context in question is created by the RouterProvider component, which takes an instance of `router` as a prop. One can get hands on such an instance when using the `create.*` series of functions, but while there's a `createBrowserRouter`, there isn't one for NativeRouter, so it seems like this is a no go as far as an upgrade path for us. Still, there seem to be plenty examples of BrowserRouter in the codebase, so I assume it should still work. How do I get the DataRouterStateContext created in this setup?

### Expected Behavior

Either everything just works, with the DataRouterStateContext is created by BrowserRouter/NativeRouter internally, or a clear instruction is given in the docs on to how create it manually.

### Actual Behavior

As described above.

**Comment by brophdawg11** [comment]
We are planning to enhance that error message a bit to avoid the confusion, but the underlying issue is that `useNavigation` is only relevant in a data router landscape where you are executing loaders/actions as part of a navigation.  All navigations in `BrowserRouter` are effectively instantaneous since all fetching happens in the components on the destination route.

See https://reactrouter.com/en/main/routers/picking-a-router for more information

As for the `NativeRouter` - under the hood it's just a `MemoryRouter`, so I would try it with `createMemoryRouter`/`RouterProvider` and see if that is sufficient

**Comment by anchann** [comment]
Thank you for the quick response!

I'm not fully following. I need a programmatic way to manipulate history, basically goBack, push, and replace APIs. The useHistory hook provided me this functionality in the context of the BrowserRouter/NativeRouter in the previous version. The upgrade docs said that useNavigation is the replacement for useHistory, so assumed it would similarly work in the context of BrowserRouter/NativeRouter, but that does not seem to be the case. If so, then what hook (or some other thing) would give me the ability to do goBack/push/replace in the context of BrowserRouter/NativeRouter in v6?

**Comment by brophdawg11** [comment]
Ah - ok you want `useNavigate` then, not `useNavigation` - https://reactrouter.com/en/main/upgrading/v5#use-usenavigate-instead-of-usehistory

With `useNavigate` you're free to remain with `BrowserRouter`/`NativeRouter`

**Comment by anchann** [comment]
Oh wow... thank you, and sorry for wasting your time by not paying enough attention to the docs!

**Comment by braco** [comment]
Getting this error too.

@brophdawg11 is there some equivalent to navigation.location that would let you get the current path of a BrowserRouter or HashRouter and normalize the difference?

ie /foo on BrowserRouter and /#/foo on HashRouter would both yield "/foo"

**Comment by timdorr** [comment]
You want `useLocation`.
