### ISSUE TITLE
[Feature]: Make Implementing RouterProvider & ScrollRestoration more similar to BrowserRouter, Routes, & Route

### ISSUE THREAD

**Issue by spencergray96** [remix-run/react-router#9330]
### What is the new or updated feature that you are suggesting?

Would like a way to implement RouterProvider component and add route agnostic children like headers or footers, OR have a reference to the router context that exists higher in the hierarchy that can be used in multiple places.

Perhaps it's possible with multiple RouterProvider components with "/*" routes, above and below the main one, but that would be clunky.

In order to get the ScrollRestoration features working, as well as website header/footer, etc that require the router context, I've had to write our routing config like this:
```
const App: React.FC = () => {

	return (
	        <main className="app-main">
		        <RouterProvider
			        router={createBrowserRouter([
				        {
					        path: "/",
					        element: <Garbage page={<Home/>}/>,
				        },
				        {
					        path: "/people",
					        element: <Garbage page={<PeoplePage/>}/>,
				        },
				        {
					        path: "/portfolio",
					        element: <Garbage page={<Portfolio/>}/>,
				        },
				        {
					        path: "/contact",
					        element: <Garbage page={<ContactUsPage/>}/>,
				        },
			        ])}
		        />
	        </main>
	);
};
```

Also see the ScrollRestoration implementation in our Garbage component:
```
const Garbage: React.FC<IProps> = (props) => {
	return (
		<React.Fragment>
			<ScrollRestoration/>
			<ErrorManager/>
			<GlobalContactModalManager/>
			<LoadingManager/>

			<Header/>
			<FrameOneSidebar/>
			{props.page}
			<Footer/>
		</React.Fragment>
	);
};
```

### Why should this feature be included?

It would be nice to be able to implement non-route specific components like how I was able to previously in older versions, while still being able to leverage the features from the ScrollRestoration component:
```
const App: React.FC = () => {

	return (
		<BrowserRouter>

			<ErrorManager/>
			<GlobalContactModalManager/>
			<LoadingManager/>

			<main className="app-main">
				<Header/>
				<FrameOneSidebar/>
				<Switch>
					{isDev() && (<Route exact path="/demo" component={ComponentDemoPage}/>)}

					<Route exact path="/" component={Home}/>
					<Route exact path="/people" component={PeoplePage}/>
					<Route exact path="/portfolio" component={Portfolio}/>
					<Route exact path="/contact" component={ContactUsPage}/>
					<Redirect to="/"/>
				</Switch>
				<Footer/>
			</main>
		</BrowserRouter>
	);
};
```

**Comment by brophdawg11** [comment]
You can do headers and footers in a parent/layout route using Outlet: https://reactrouter.com/en/main/components/outlet

**Comment by brophdawg11** [comment]
Closing this as I think `Outlet` handles your use case, but please let us know if not!

**Comment by spencergray96** [comment]
I Think `Outlet` _can_ handle this use case, but seems extraneous to me. If not using any truly "nested" routes (ie, only top level routes as shown in my code), I think I can get by with my `Garbage` component above. But if the `Outlet` is the teams intended answer for this scenario, then so be it. Thanks for the response

**Comment by brophdawg11** [comment]
I'm unsure what you mean by "truly nested" - this looks very much like a nested route setup to me!  You've got a root layout route rendering error/loading/header/sidebar/footer - and it has 4 children (index, people, portfolio, contact).  

I'd recommend against the approach with Garbage above because you forego the benefits of loader/action/errorElement on your root Route
