### ISSUE TITLE
[Feature]: Use useMatches and the createBrowserRouter(router) in storybook

### ISSUE THREAD

**Issue by PanchoutNathan** [remix-run/react-router#9346]
### What is the new or updated feature that you are suggesting?

I upgraded to 6.4.1 in order to use use Matches. However, it has become complicated to use react router dom in storybook to choose path for example. How can I use this new version?

### Why should this feature be included?

Be able to use useMatches and createBrowserRouter(router) in storybook decorators and select the routerPath in parameters

**Comment by timdorr** [comment]
You should ask this on the Storybook repo. This would be up to them to solve.
