### ISSUE TITLE
[Bug]: <Form> navigation doesn't respect `basename`

### ISSUE THREAD

**Issue by janovekj** [remix-run/react-router#9347]
### What version of React Router are you using?

6.4

### Steps to Reproduce

[CodeSandbox](https://codesandbox.io/s/react-router-basename-w2eege?file=/src/App.tsx)

Navigate to `/basename/some-path` in the sandbox browser window and click the submit button. This will trigger a navigation.

### Expected Behavior

I would have expected the basename part of the URL to be preserved, and to stay at `/basename/some-path` 

### Actual Behavior

`/basename` is not preserved, app navigates to `/some-path` instead. To get the desired behavior, I must use the full URL to stay at the current route: `<Form action="/basepath/some-path`>

**Comment by brophdawg11** [comment]
Thanks for the bug report @janovekj! I just merged the fix for this - planning to get a prerelease out today and a stable 6.4.2 next week 👍
