### ISSUE TITLE
[Feature]: Support `<Offscreen />` to work with react-router

### ISSUE THREAD

**Issue by luhc228** [remix-run/react-router#9350]
### What is the new or updated feature that you are suggesting?

Hi~, I am now using react-router-dom@v6 and this is a very excellent package. As we know, react 18 will publish `<Offscreen />` component will is same as vue's <KeepAlive /> soon. Now, I just want to use the `unstable_Offscreen` component to work with the react-router to to preserve my page state across route changes like [nuxt's keep alive](https://v3.nuxtjs.org/guide/directory-structure/pages#keepalive).

So I try to write a demo:

```tsx
<Routes>
  <Offscreen mode={path === "/" ? 'visible' : 'hidden'}>
    <Route path="/" element={<Home />}></Route>
  </Offscreen>
  <Offscreen mode={path === "/dashboard" ? 'visible' : 'hidden'}>
    <Route path="/dashboard" element={<Dashboard />}></Route>
  </Offscreen>
</Routes>
```

But I got an error which is the Routes's children can only inlcude the `<Route />` and `<Fragment />` components.
https://github.com/remix-run/react-router/blob/cb7f5103cf579443d10cf39762b2755a4f31e66a/packages/react-router/lib/components.tsx#L566

I want to know could you remove the check of the Route's children type.  If not, how to I  make `<Offscreen />` to work with `<Route />`?

### Why should this feature be included?

Remove the check of the Route's children type.

https://github.com/remix-run/react-router/blob/cb7f5103cf579443d10cf39762b2755a4f31e66a/packages/react-router/lib/components.tsx#L566

**Comment by timdorr** [comment]
You just need to put the Offscreen component within the `element` of the Route:

```js
<Route path="/" element={
  <Offscreen mode={path === "/" ? 'visible' : 'hidden'}>
    <Home />
  </Offscreen>
}></Route>
```

**Comment by luhc228** [comment]
> You just need to put the Offscreen component within the `element` of the Route:
> 
> ```js
> <Route path="/" element={
>   <Offscreen mode={path === "/" ? 'visible' : 'hidden'}>
>     <Home />
>   </Offscreen>
> }></Route>
> ```

It could not keep the state because the element will unmount.

**Comment by luhc228** [comment]
I write a demo just now, but the component state can not be preserved.
```tsx
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <BrowserRouter>
      <Routes>
        <Route path="/dashboard" element={<CustomOffscreen path="/dashboard"><Dashboard /></CustomOffscreen>} />
        <Route path="/about" element={<CustomOffscreen path="/about"><About /></CustomOffscreen>} />
      </Routes>
    </BrowserRouter>
  </React.StrictMode>
);

function CustomOffscreen({ path, children }: any) {
  const location = useLocation();
  console.log('location==>', location.pathname === path);
  return (
    <Offscreen mode={path === location.pathname ? 'visible' : 'hidden'}>
      {children}
    </Offscreen>
  )
}
```

**Comment by dingziqi** [comment]
我是用 react-freeze 来实现的 keep-alive，可以参考下这个思路。 https://github.com/dingziqi/react-router-v6/blob/main/src/components/KeepAliveOutlet.js
