### ISSUE TITLE
[Feature]: Use Generics to Type state property

### ISSUE THREAD

**Issue by alexburkowskypolysign** [remix-run/react-router#9358]
### What is the new or updated feature that you are suggesting?

Provide a generic to hooks that contain a state property so we can set up TS guardrails. Also make `state` an optional property, because currently it is defaulted to `undefined` if not explicitly set and results in an error if you try to lookup a property in it.

```ts
export declare function useLocation<State = any>(): Location<State>

export interface Location<State> extends Path {
  state?: State
  key: string
}

...

const location = useLocation<{from: string}>()
console.log(location.state?.from)
```

### Why should this feature be included?

Typesafety

**Comment by timdorr** [comment]
This has been suggested many times. 

This would actually remove type safety, as you would be overriding `state` to that type. You should be using type narrowing to determine the type of `state` safely. A generic would be a hack to force that to work.

https://github.com/remix-run/react-router/pull/8370#issuecomment-974578233
https://github.com/remix-run/react-router/issues/8396#issuecomment-980829670

**Comment by alexburkowskypolysign** [comment]
If this is the suggested pattern @timdorr , Would it not make sense to at least type it as a conditional unknown. The first issue with any is that you can attempt to access an object property unsafely without optional chaining. The second option isn't doesn't guide the user towards a type narrowing pattern. Unknown would more effectively steer people in the direction you state
