### ISSUE TITLE
[Feature]: support <Offscreen /> to work with react-router

### ISSUE THREAD

**Issue by luhc228** [remix-run/react-router#9361]
### What is the new or updated feature that you are suggesting?

I just want to use the `<Offscreen />` component to work with the react-router to to preserve my page state across route changes like [nuxt's keep alive](https://v3.nuxtjs.org/guide/directory-structure/pages#keepalive).

I write a demo, but the component state can not be preserved. Could you help me see what is the problem? @timdorr

```tsx
import React from "react";

const { unstable_Offscreen: Offscreen } = React;

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <BrowserRouter>
      <Routes>
        <Route path="/dashboard" element={<CustomOffscreen path="/dashboard"><Dashboard /></CustomOffscreen>} />
        <Route path="/about" element={<CustomOffscreen path="/about"><About /></CustomOffscreen>} />
      </Routes>
    </BrowserRouter>
  </React.StrictMode>
);

function CustomOffscreen({ path, children }: any) {
  const location = useLocation();
  console.log('location==>', location.pathname === path);
  return (
    <Offscreen mode={path === location.pathname ? 'visible' : 'hidden'}>
      {children}
    </Offscreen>
  )
}
```

related issue: https://github.com/remix-run/react-router/issues/9350

### Why should this feature be included?

 support `<Offscreen />` to work with react-router and the state can be preserved

**Comment by timdorr** [comment]
Please do not open duplicate issues. This is a bug tracker, not a support system.
