### ISSUE TITLE
[Bug]: Loader not working on child routes

### ISSUE THREAD

**Issue by Geowan** [remix-run/react-router#9362]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

I have recreated the issue on stackblitz with the url
https://stackblitz.com/edit/github-zgtpop?file=src/App.tsx

On the about page child route i have added a loader but seems never to get executed when i visit the about page.

Visit the about route and check on the console and it doesnt have the loader log.
Also on the about child route i have added a console.log but its never logged

### Expected Behavior

I expected the about page loader to have the data on the about page but its undefined

### Actual Behavior

On the about page the loader data using useLoaderData is undefined

**Comment by brophdawg11** [comment]
Descendant `<Routes>` trees do not participate in data loading (https://reactrouter.com/en/main/components/routes) since they cannot be known ahead of render-time.  You'll need to lift your descendant route definitions up into the `routes` you pass to `createBrowserRouter`.

**Comment by awreese** [comment]
@brophdawg11 I see, the relevant information one would sort of expect to find regarding this rather important distinction in the `createBrowserRouter` and `Route` docs is hidden elsewhere under a different component's documentation. That note would be a great addition to the Data API doc area.

**Comment by Atifarooq** [comment]
@brophdawg11  `loader` function also not working in below mentioned case when we have `children` routes
```
export const BASE_URL = "/";
const router = createBrowserRouter([
  {
    path: BASE_URL,
    element: (
      <Layout>
        <Topbar />
      </Layout>
    ),
    loader: () => ({
      name: "root page",
      searchBar: true,
    }),
    children: [{
      path: USER_ROUTES.DEFAULT,
      element: <UserList />,
      loader: () => ({
        name: "users",
        searchBar: true,
      }),
    },
    {
      path: `${USER_ROUTES.USER}/:userId`,
      element: <User />,
      loader: ({ params }) => ({
        name: params.userId,
        searchBar: false,
      }),
    },
    {
      path: USER_ROUTES.FAVOURITES,
      element: <FavouriteUsers />,
      loader: () => ({
        name: "favourites",
        searchBar: false,
      }),
    }],
  },
]);
export default () => <RouterProvider router={router} />;
```

**Comment by brophdawg11** [comment]
Please do not use closed issues as a help forum.  Please ask your question in the [Remix Discord](https://rmx.as/discord) or open a Q&A discussion on the repository with a minimal reproduction of the issue.
