### ISSUE TITLE
[Bug]: useParams() return empty object

### ISSUE THREAD

**Issue by thomasyu929** [remix-run/react-router#9364]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

``` 
<BrowserRouter>
    <AuthProvider>
      <MapProvider>
        <Routes>
          <Route path="/" element={<IndexPage />} />
          <Route path="*" element={<IndexPage />} />

          <Route path='auth' element={<AuthRoot/>}>
            <Route index element={<AuthLogin />} />
            <Route path='login' element={<AuthLogin />} />
            <Route path='callback' element={<AuthCallback />} />
            <Route path='logout' element={<AuthLogout />} />
          </Route>
        </Routes>
      </MapProvider>
    </AuthProvider>
<BrowserRouter>
```

### Expected Behavior

expected to get params info

### Actual Behavior

Can't get params by `useParams()` in `AuthCallback` or other component. will get `{}`

**Comment by thomasyu929** [comment]
> 
@iambilalriaz Thanks for the clarification.
How can I retrieve parameter like `id` or `text` from `callback?id={id}&text={text}` by using React? 
I know how to get params by using VanillaJS but didn't find a good way of React.

**Comment by kiliman** [comment]
Those are called search params or query string. You can access them via the `useSearchParams` hook. 

https://reactrouter.com/en/main/hooks/use-search-params
