### ISSUE TITLE
[Bug]: react-router-dom-v5-compat misses some exports from react-router-dom v6

### ISSUE THREAD

**Issue by imdongchen** [remix-run/react-router#9368]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

Try to import some new api from react-router-dom v6, e.g.

```
import { Form, useSubmit } from 'react-router-dom-v5-compat'
```

### Expected Behavior

The import should work

### Actual Behavior

`Form` `useSubmit` etc. are not exported, related code in https://github.com/remix-run/react-router/blob/main/packages/react-router-dom-v5-compat/index.ts#L74-L112

**Comment by timdorr** [comment]
react-router-dom-v5-compat is intended for the transition between the non-data components of v6, which map more closely to the components of v5. There is no intended transition path directly from v5 to 6.4's new data components.
