### ISSUE TITLE
[Bug]: using HistoryRouter not working anymore since 6.4.0

### ISSUE THREAD

**Issue by ChristophP** [remix-run/react-router#9385]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

Update to 6.4.0 from a lower version using `unstable_HistoryRouter`.

### Expected Behavior

It continues to work as expected

### Actual Behavior

My bundler complains because there is no `history` package installed.
This is correct because as recommended by the docs when using `unstable_HistoryRouter` I did not separately install an `instance` of history router but used the one from `react-router` router. Apparently since 6.4.0 `react-router` no longer depends on the history package.

**Comment by ChristophP** [comment]
### Clarification:
I'm not sure whether this is actually a bug but it appears to be a breaking change from a users end (although I realize I'm on a slippery slope when I'm using a feature explicitly labelled as `unstable_HistoryRouter`).

I noticed `unstable_HistoryRouter` is no longer documented althoug it still exists in 6.4.1 and appears to work if I install the `history` package myself and pass in an instance.

I have a need to use `navigate` outside of a hook, to make routing work in parts of my app that are not written in react but various other frameworks. If `unstable_HistoryRouter` is no longer a thing, I'd appreciate some guidance on what the new recommended approach for this sort of thing is or if that is supported at all, since I couldn't find anything on this in the docs

**Comment by brophdawg11** [comment]
👋 Hey @ChristophP  - There were a bunch of separate thread about this so I've centralized over in https://github.com/remix-run/react-router/issues/9422#issuecomment-1301182219 and am going to close this one out based on those paths forward
