### ISSUE TITLE
[Bug]: Upgrading to 5.3.4 breaks `useReactRouter` hook

### ISSUE THREAD

**Issue by atomrc** [remix-run/react-router#9389]
### What version of React Router are you using?

5.3.4

### Steps to Reproduce

Hello there 👋 
I just did the update from react-route 5.3.3 to 5.3.4, and this broke my app. 
I now have this error showing up in the console 

```text
Error: useReactRouter may only be called within a <Router /> context.
```

I can confirm that this component is wrapped in a `<Router>` component. 
Reverting to react-router 5.3.3 did fix the problem

STR:
- Have a component that uses `useReactRouter` (https://www.npmjs.com/package/use-react-router) 
- wrap this component in a `<Router>` component
- load your app

### Expected Behavior

The app should load correctly and the component should render. 

### Actual Behavior

The app doesn't render and instead the following error happens:

```text
Error: useReactRouter may only be called within a <Router /> context.
```

**Comment by timdorr** [comment]
That isn't a bug with this library. You need to get that fixed with the use-react-router library.
