### ISSUE TITLE
[Bug]: Not implemented: navigation (except hash changes)

### ISSUE THREAD

**Issue by rferreira98** [remix-run/react-router#9391]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Use "useNavigate" hook on component
2. Programatically navigate
3. Test navigation with react-testing-library + jest
````
userEvent.click(navigationBtn);
//present on target page
expect(await screen.findByTestId("target-page-id")).toBeVisible();
````

4. Error is thrown 

### Expected Behavior

Expected tests to pass.

### Actual Behavior

Error: Not implemented: navigation (except hash changes)

**Comment by rferreira98** [comment]
I've tried mocking `window.location` replace/assign/href and none of this solutions worked. Error was missing but functionality error persists.

**Comment by brophdawg11** [comment]
👋 Can you provide a reproduction of this issue?  We have plenty of unit tests that are using `useNavigate` with `jest` so I'm inclined to think this is something in your local setup: https://github.com/remix-run/react-router/blob/main/packages/react-router/__tests__/useNavigate-test.tsx

**Comment by rferreira98** [comment]
Did a code sandbox and is as you said. Setup is messing with the tests. Sorry!
