### ISSUE TITLE
[Feature]: Pass state on navigate(-1)

### ISSUE THREAD

**Issue by dushajni** [remix-run/react-router#9403]
### What is the new or updated feature that you are suggesting?

Currently, we can send additional state data just if we navigate with exact path like: 
`navigate('/some-route', { state: {data} })`

but if I try something like this:
`navigate(-1, { state: {data} })`
it wont work. 

### Why should this feature be included?

I don't know if that is a bug but this could be a very useful feature, especially when some page can be accessed from several different pages and we need some data sent back from that page.

**Comment by timdorr** [comment]
If you're navigating backwards (which is just `history.back()` under the hood), you can't adjust that location. It becomes a fundamentally different location at that point, so it's actually a forward navigation. Allowing this would create a confusing API.
