### ISSUE TITLE
[Bug]: Route loaders - strange behavior when navigating with search params (query string)

### ISSUE THREAD

**Issue by codeape2** [remix-run/react-router#9404]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

Navigate using search params. This causes unexpected loader execution.

Example application has these routes (full application source in this gist: https://gist.github.com/codeape2/851f31ae5ffab4ca8c72d1cc85d17086):

```
const routes = [
  {
    path: "/",
    loader: () => recordLoaderInvocation("root"),
    element: ...,

    children: [
      {
        path: "children",
        loader: () => recordLoaderInvocation("children"),
        element: ...,
        children: [
          {
            path: ":childid",
            loader: ({params}) => recordLoaderInvocation(`child ${params.childid}`),
            element: ...
          }
        ]
      }
    ]
  }
]
```

Note the devtools console output:
![image](https://user-images.githubusercontent.com/97742/194065359-80d7a9f4-7428-4954-b043-48ddcdeb6dcc.png)

- As expected, the initial page load triggers the `root` loader
- Navigating to `children/1` triggers the `children` and the `child 1` loader. Again, as expected
- Navigating to `children/2` triggers the `child 2` loader. As expected. No need to trigger the `root` and `children` loaders.
- Something weird happens when I then navigate to `children/1?foo=bar`: Notice that the entire loader hierarchy trigger (twice even)

I tried to create a unit test for this but was unable to render a `<RouteProvider>`, i got an error message `An update to RouterProvider inside a test was not wrapped in act(...)` - even if I used `import { act } from "react-dom/test-utils";`. This gist contains my failed attempt at testing: https://gist.github.com/codeape2/53525e071afe13f2e31571bc4d8fc78f

### Expected Behavior

When navigating using search/queryparams, only necessary loaders should trigger.

### Actual Behavior

It seems that if the query params change, then the entire loader hierarchy triggers.

**Comment by timdorr** [comment]
The entire loader heirachy should trigger, as those query params are essentially globals and are available to every loader. They may change the data they load, so calling them is the safe thing to do.

I'm not sure about the double loading though. That may be a real bug here.

**Comment by codeape2** [comment]
Disregard the double loading, I believe the second round was the result of a editor file save triggering webpack's dev server to rebuild and reload.

- Re. "... query params are essentially globals and are available to every loader":
  - I see, thanks!
  - I notice the entire hierarchy triggering also if I change the search params through `useSearchParams() -> setSearch()`.
  - Although I believe the way it works is not optimal (se below)

Issues:
- In many cases I guess only the last/leaf element in the routing hierarchy cares about the query string values.
- I therefore find it unnatural that the interaction between changes in query params and the route/loader hierarchy is the way it is.
- The route URL is "left-to-right", i.e. you start with the root on the left and build towards the leaf on the right. Since the query parameters are on the far right in the URL IMO the most natural way to work with query params is to consider query params "local to the leaf route" (not as global state that could potentially impact all routes). 
- Imagine a blog application with the following routing config:
```
/blogs/
    index      <ListOfBlogs/> loader=fetchListOfBlogs()
    :blogid
        posts   
            index  <ListOfPostTitlesInBlog/> loader=fetchListOfPostTitles()
           :postid <BlogPost/>               loader=fetchBlogPostContents()
```
- Imagine navigating from `/blogs/1/posts` to `/blogs/1/posts?recent=yes`. Given the left-to-right nature of URLs, intuitively the `recent=yes` qparam "belongs" to `/blogs/1/posts` (not to `/blogs/` or `/blogs/1/`).

Would it be possible to create a variation of `useSearch() or useNavigate()` that in this case would not trigger any loaders? 

Something like:

```
const search, setSearch = useSearchParamsButDoNotTriggerAnyRoutingLogicOnSetSearch();
setSearch({recent: "yes"});

// ... or

const navigate = useNavigateButDoNotTriggerAnyRoutingIfOnlySearchParamsChange();
navigate({search: "?recent=yes"});
```

**Comment by timdorr** [comment]
That is correct. We can't know that only the leaf loader needs to reload. You have to tell us with `shouldRevalidate`.

**Comment by codeape2** [comment]
Great thanks a lot! `shouldRevalidate` is exactly what I need.

Two follow-up question:

1. Is this a reasonable `shouldRevalidate`?
```
path: ":someparam",
loader: ({params}) => fetch(`/api/getdata/${params.someparam}`),
shouldRevalidate: ({currentParams, nextParams, defaultShouldRevalidate}) => {
  if (currentParams.someparam === nextParams.someparam) {
    return false;
  } else {
    return defaultShouldRevalidate;
  }
},
```

2. In the case above imagine that I want to re-trigger the loader explicitly for some reason. What would be the best way to do this?
