### ISSUE TITLE
[Bug]: Layout route doesn't work properly with Remix SSR app

### ISSUE THREAD

**Issue by shirshendubhowmick** [remix-run/react-router#9408]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

I am working on migrating a react router based CSR app to SSR using Remix and using the guide mentioned here:
https://remix.run/docs/en/v1/guides/migrating-react-router-app

I have a routing setup like this:

```jsx
<Routes>
  <Route element={<Layout />}>
    <Route path="/" element={<SomeComponent />} />
    <Route path="/user" element={<SomeComponent />} />
    <Route path="/user/profile" element={<SomeComponent />} />
     .....
  </Route>
<Routes>
```

This above route setup works perfectly fine WITHOUT remix. When the same routing is setup is rendered along side Remix
I start getting warnings like this:
```
router.ts:11 You rendered descendant <Routes> (or called `useRoutes()`) at "/" (under <Route path="">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

Please change the parent <Route path=""> to <Route path="/*">.
```

And as the warning says, it doesn't match the routes for `/user/profile`

### Expected Behavior

Using layout routes should work as expected in Remix app just like it works in a regular react router based CSR app.

### Actual Behavior

Layout route breaks when used along side Remix, it mandatorily asks for a `path` prop and if not passed the route match doesn't work as expected.

The same setup of layout route works perfectly fine in regular react router based CSR app

**Comment by timdorr** [comment]
This is best asked in the Remix repo: https://github.com/remix-run/remix
