### ISSUE TITLE
[Bug]: Router motion/animation shows data before animation completes

### ISSUE THREAD

**Issue by Speedy1991** [remix-run/react-router#9412]
### What version of React Router are you using?

6.4 (also testet with 5.x)

### Steps to Reproduce

See [this sandbox](https://codesandbox.io/s/e6ql9e)

### Expected Behavior

Data should not be changed before the animation ends

### Actual Behavior

Currently, the router changes the content _before_ the animation has finished.
If you toggle the "Green/Blue" buttons, the component gets updated data and animates inOut. This leads to a broken UI.
If you check out the console, it looks like the mounting does some weird stuff too.

**Comment by timdorr** [comment]
This isn't a React Router bug. You need to somehow store the previous state and update it once the animation finishes. That's not something the router controls.

**Comment by Speedy1991** [comment]
Hi @timdorr,
thanks for the quick response and for taking a look into it.
I dug deeper into the problem and I'm quite sure there is a bug with the loaders (or I totally misunderstood the usage of them).
I adjust the sandbox with this [fork](https://codesandbox.io/s/data-before-animation-forked-ci5kj6) to demonstrate the problem.
If you toggle the buttons everything works as expected. If you comment the loader in line 58 it's broken again.
So can you please explain to me what's going on here? What's the impact of the loader(-data?) to brick the animation?

**Comment by candy4290** [comment]
> Hi @timdorr, thanks for the quick response and for taking a look into it. I dug deeper into the problem and I'm quite sure there is a bug with the loaders (or I totally misunderstood the usage of them). I adjust the sandbox with this [fork](https://codesandbox.io/s/data-before-animation-forked-ci5kj6) to demonstrate the problem. If you toggle the buttons everything works as expected. If you comment the loader in line 58 it's broken again. So can you please explain to me what's going on here? What's the impact of the loader(-data?) to brick the animation?

https://codesandbox.io/s/stupefied-zeh-ys796y?file=/src/App.js:723-738
