### ISSUE TITLE
[Bug]: Basename is not respected in loaders and actions redirects

### ISSUE THREAD

**Issue by manzano78** [remix-run/react-router#9417]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

1) Create a data browser router with some routes and a basename: `createBrowserRouter(routes, { basename: '/m' });`
2) In any route, attach a loader or an action (both are impacted) which returns or throws (both are impacted) a redirect to another route represented by an absolute path: `throw redirect('/some-route');`

### Expected Behavior

The new browser URL should be **https://example.com/m/some-route**

### Actual Behavior

The new browser URL is **https://example.com/some-route**. The basename (/m) is missing, so we don't see the expected page as it couldn't match.

**Comment by brophdawg11** [comment]
Just merged the PR for this, hoping to get a 6.4.3 prerelease out soon (possibly today) and a stable hopefully next week 👍

**Comment by brophdawg11** [comment]
👋 Just did a prerelease (`6.4.3-pre.0`) which should fix this if you want to give it a shot!
