### ISSUE TITLE
[Bug]: Module '"react-router-dom"' has no exported member 'useSearchParams'

### ISSUE THREAD

**Issue by a2441918** [remix-run/react-router#9421]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Upgrade to react-router-dom 6.4.2 and if you use useSearchParams in your code, you will get an error.

Module '"react-router-dom"' has no exported member 'useSearchParams'

### Expected Behavior

useSearchParams should exist

### Actual Behavior

Typescript fails to compile

**Comment by trim21** [comment]
how did you fix this? I encounter same issue but I found that `useSearchParams` is exported in both js and d.ts.
