### ISSUE TITLE
[Bug]: Documentation bug: v6 changed `render` and `children`, with no documentation on how to migrate to v6

### ISSUE THREAD

**Issue by th317erd** [remix-run/react-router#9428]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Move from v5 to v6.

### Expected Behavior

Deprecated/changed/removed `render` and `children` props for `Route` have no migration documentation for functionality that used to be supported.

### Actual Behavior

I am moving from `react-router-dom` version 5, where the `children` and `render` props were supported.

It is vitally important for my app that I HIDE the routes instead of unmounting, which is what I was using the `children` prop for. I simply provided a method to `children` props, and set a `hide` prop on my page if the `match` was valid or not. However, moving to v6, I see these props have been removed or changed, and I can not find anywhere in the documentation how to accomplish what I was previously doing.

So I feel this is a documentation bug. I get that features change between major versions, but shouldn't it be documented somewhere **how to hide a route instead of unmounting it**? Or is this simply not possible anymore in v6? If so, should the documentation be updated to specifically call that out? In short, I am lost, and I feel features _may_ have been dropped without documentation stating that they were dropped, and alternative approaches that can be used instead. Help!

**Comment by timdorr** [comment]
There is a whole guide for upgrading from v5, including a large section on the new `element` prop: https://reactrouter.com/en/main/upgrading/v5#advantages-of-route-element

**Comment by th317erd** [comment]
Yes, there is, but in the v5 documentation it was specifically called out that you could use `render` or `children` to keep your components in-place (without unmounting), and this functionality has been removed in v6, with no mention of how to migrate for users who were doing exactly this.

https://v5.reactrouter.com/web/api/Route/children-func

I feel the v6 migration guide should call this out, and give examples to users on how to migrate. I have this exact use case, and have already spent hours in v6 trying to figure out how to do it, only to realize that it is no longer possible.

**Comment by fake364** [comment]
@th317erd yep, I got this problem as well. probably they consider this as a challenge "MIGRATE HUNDREDS OF COMPONENTS THAT USE render prop WITHOUT GUIDE!"
