### ISSUE TITLE
[Feature]: opt into routes that dont contribute to naviation hierarchy

### ISSUE THREAD

**Issue by jan-leila** [remix-run/react-router#9429]
### What is the new or updated feature that you are suggesting?

opt in `transparent` prop for `<Route />` components that makes them not match when navigating using `"../"` even when they contribute to the path.

```jsx
<Routes>
  <Route transparent path="overview">
    <Route index element={/**/}/>
    <Route path="activity" element={/**/}/>
    <Route path="followers" element={/**/}/>
  </Route>
  <Route path="home" element={/**/}/>
</Routes>
```

Where navigation to `"home"` from the page `overview/activity` would navigate to `home` instead of `overview/home`

### Why should this feature be included?

In a project im working on we have a a lot of routes that are deeply nested and related to each other and contain that end up looking like this:

```
<Route to="page1"/>
<Route to="page1/overview"/>
<Route to="page1/overview/followers"/>
<Route to="page1/overview/subscribers"/>
<Route to="page1/overview/snapshot"/>
<Route to="page1/overview/snapshot/timeline"/>
<Route to="page1/overview/snapshot/feed"/>
<Route to="page1/preview"/>
```
when it would make much more since for them to be able to build off of each other but cant be done due to them needing to have relieve routes within them

**Comment by timdorr** [comment]
You're asking for a pathless route, which already exists: https://reactrouter.com/en/main/start/concepts#pathless-routes

**Comment by jan-leila** [comment]
im not asking for pathless routes im asking for routes that contain a bath but cant be matched by a navigating when using ".."

right now for the example above if at any point in the future we need to rename "overview" it needs to be changed in all of the related routes, where as what im asking for is a route where they would all be nested under a "overview" route but that "overview" wouldnt get matched by navigation

**Comment by timdorr** [comment]
That would make Link and useNavigate's behavior inconsistent for things configured outside of their usage. The end result would be more confused users and more error-prone code. 

Instead, you should simply link to `/home` to reference a top level route. Or use multiple `..` segments to navigate upwards.

**Comment by jan-leila** [comment]
The behavior of navigation is already defined by factors outside of their definition. All this would do is let you define what factors.
