### ISSUE TITLE
[Bug]: When the components are switched but not uninstalled, the useParams value does not change

### ISSUE THREAD

**Issue by ikangjie** [remix-run/react-router#9431]
### What version of React Router are you using?

v6.4.2

### Steps to Reproduce

https://codesandbox.io/s/hardcore-hooks-hq5e3l?file=/src/App.js

### Expected Behavior

first url change:  /a/hello
get params ==> hello

second url change: /a/hi
get params ==> hi

### Actual Behavior

first url change:  /a/hello
get params ==> hello

second url change: /a/hi
get params ==> hello

**Comment by timdorr** [comment]
Your KeepAlive component is doing this. This isn't caused by the library.
