### ISSUE TITLE
[Bug]: basename is not working with HashRouter

### ISSUE THREAD

**Issue by Mikilll94** [remix-run/react-router#9442]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

1. Open this page
https://stackblitz.com/edit/github-84wfun?file=package.json,src%2Fmain.tsx,src%2FApp.tsx
and visit
https://github-84wfun-ujvwfonr--3000.local-corp.webcontainer.io/app
in the sandbox.

2. As you can see there is a blank screen.
3. Now change `HashRouter` to `BrowserRouter` and again visit
https://github-84wfun-ujvwfonr--3000.local-corp.webcontainer.io/app
in the sandbox

5. Now the page is working.

### Expected Behavior

`HashRouter` should work when using `basename`.

### Actual Behavior

`HashRouter` is not working when using `basename`. Blank page is rendered.

**Comment by brophdawg11** [comment]
When using a `HashRouter`, the _entire_ path comes after the hash so you're hitting an incorrect URL.  You would need to access:

https://github-84wfun-ujvwfonr--3000.local-corp.webcontainer.io/#/app
