### ISSUE TITLE
[Bug]: Loader causes flicker on first hydration cycle in case of SSR rendered page 

### ISSUE THREAD

**Issue by vinaygosain** [remix-run/react-router#9444]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Loader causes flicker on initial hydration cycle in case of SSR rendered page while mounting the same identical react  component tree. 

i have created a bare minimum stackblitz demo here to reproduce the issue
 https://stackblitz.com/edit/github-yuqp1j?file=src%2Fentry.client.tsx,src%2Froutes.tsx

If i remove the loader part, then the app works fine. 

### Expected Behavior

There should be no flicker i guess.

### Actual Behavior

Loader causes flicker on initial hydration cycle in case of SSR rendered page

**Comment by timdorr** [comment]
This isn't a bug with the library. You should build your loader to obtain data from the server-rendered page somehow (some sort of global `initialState` value) and return immediately, so there is no additional flicker.

This is essentially what Remix itself does: https://github.com/remix-run/remix/blob/b35e1355d27353c1946c56842be992bbc5d1d60c/packages/remix-server-runtime/server.ts#L448-L453

**Comment by vinaygosain** [comment]
So there is no way to fetch data on client for a server rendered page before the first hydration cycle.

**Comment by brophdawg11** [comment]
@vinaygosain SSR support isn't yet stable for data routers, but the basic functionality is available if you want to try it out (at your own risk :smile:).  We are planning to release it as stable once we've updated Remix to run on top of react-router 6.4.

The main thing you're missing is supplying your server-side loaded data in `hydrationData` to `createBrowserRouter` which will avoid the initial loader fetch on the client:

```
let router = createBrowserRouter(routes, {
  hydrationData: {
    loaderData: {
      // key/value of routeId -> loaderData from SSR
    },
  }
});
```

There's an [example](https://github.com/remix-run/react-router/tree/main/examples/ssr-data-router) of this in the repo which uses `unstable_createStaticHandler` to do server-side data-fetching and `unstable_StaticRouterProvider` to do server-side rendering.  If you use `unstable_staticRouterProvider` you also get automatic hydration with `RouterProvider` out of the box.
