### ISSUE TITLE
[Bug]: Mistakes in the tutorial

### ISSUE THREAD

**Issue by hrafnkellpalsson** [remix-run/react-router#9445]
### What version of React Router are you using?

6.4

### Steps to Reproduce

Read https://reactrouter.com/en/main/start/tutorial#pathless-routes

### Expected Behavior

At the end of the tutorial when wrapping in a pathless route
the index route `{ index: true, element: <Index /> }` needs to be moved up to be an element of the first children array, not the second children array. 

Also (yes total nitpick), the Route import here appears to be unnecessary
https://reactrouter.com/en/main/start/tutorial#adding-a-router

### Actual Behavior

Docs have bugs, I think 🤔

**Comment by timdorr** [comment]
Can you submit a PR for these changes instead of an issue? Thanks.
