### ISSUE TITLE
[Bug]: Upgrading from version 6.3 to 6.4 throws error

### ISSUE THREAD

**Issue by Dlyx24** [remix-run/react-router#9449]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

If I upgrade my codebase from react-router-dom v6.3 to v6.4 the import of History changes and it seems to be imported from "remix-run/router" now. 

This is fine however there is a new validation on the listener of an history object that throws an error on my code. 

The error I get is "A history only accepts one active listener".

This new validation can be found at @remix-run/router/history.ts:596

My code, written in Typescript, is a custom hook that listens to locations changes of the pop type and allows me to run a callback function. Used in most cases when users press the back button on their browser. 
(You can find similar approaches all over the internet, they all make use of the `.listen` method present on the History interface)

```typescript
export const useBackListener = (callback: (config: { location: Location; action: Action }) => void) => {
  const navigator = useContext(UNSAFE_NavigationContext).navigator as History;

  useEffect(() => {
    const listener = ({ location, action }: { location: Location; action: Action }) => {
      if (action === Action.Pop) {
        callback({ location, action });
      }
    };

    const unlisten = navigator.listen(listener);
    return unlisten;
  }, [callback, navigator]);
};
```

### Expected Behavior

On versions until 6.3 this custom hook lets me listen to location changes and run my callback function before the change.

### Actual Behavior

After upgrading to version 6.4 I get thrown a new error saying "A history only accepts one active listener" wherever I use my custom hook.

**Comment by timdorr** [comment]
The "history" from `@remix-run/router` has a different API than the `history` library. It is not designed to be used in this way, as it is for internal usage in the router. 

Regardless, you are using an `UNSAFE_` API, so behavior changes can happen at any time and this is not considered a bug.
