### ISSUE TITLE
[Bug]: Builded application opens only index page

### ISSUE THREAD

**Issue by im-isidorov** [remix-run/react-router#9452]
### What version of React Router are you using?

"react-router-dom": "6"

### Steps to Reproduce

create application with the same structure

app.ts
<img width="658" alt="image" src="https://user-images.githubusercontent.com/106147668/195437020-dd430507-6ba4-4b25-bf75-fcd5c797267f.png">

index.ts
<img width="475" alt="image" src="https://user-images.githubusercontent.com/106147668/195436944-77143b70-8721-4054-8180-8e83a288310e.png">

build and deploy your application

Try to open any page like this  [env]/somepage

### Expected Behavior

All pages open, components are rendered depending on the selected page

### Actual Behavior

only the index page opens, then we can navigate through the pages using NavLinks
But if we try to reload the page or open any page except the index, we get this:

deployed on AzureDevOps: 

<img width="1792" alt="Screenshot 2022-10-12 at 22 48 12" src="https://user-images.githubusercontent.com/106147668/195434877-db1e1806-7c72-460a-8c6c-b1a45eb37d20.png">

used serve package:
<img width="1233" alt="Screenshot 2022-10-12 at 22 52 53" src="https://user-images.githubusercontent.com/106147668/195435828-3d21dc6c-5ad1-4a24-b68d-3aebf8523fd0.png">

When I go to non index pages these files are not loaded
<img width="640" alt="Screenshot 2022-10-12 at 22 55 06" src="https://user-images.githubusercontent.com/106147668/195435629-4590148a-4dbe-4147-b00f-f597bb2ec2b1.png">

**Comment by brophdawg11** [comment]
This looks like an issue with your server hosting, you likely need to configure your servers to serve the proper HTML for your react-router application for routes other than the root route.
