### ISSUE TITLE
[Bug]: Upgrading react-router-dom from 5.3.3 to 5.3.4 break automating pulling of react-router

### ISSUE THREAD

**Issue by Flaburgan** [remix-run/react-router#9459]
### What version of React Router are you using?

5.3.4

### Steps to Reproduce

In you `package.json`, have a dependency to `react`, `react-dom` (v17) and `react-router-dom` but not to `react-router`.
Run `npm update`
`react-router-dom` is updated from `5.3.3` to `5.3.4`.
Run `npm run build`

### Expected Behavior

`react-router` is pulled, as a dependency of `react-router-dom`

### Actual Behavior

Build is failing saying `Cannot find module: 'react-router'. Make sure this package is installed. `

**Comment by timdorr** [comment]
Soemthing else is going on here outside of the library. This isn't a bug with React Router.
