### ISSUE TITLE
[Bug]: React router build has const and let, no support for Chrome < 49

### ISSUE THREAD

**Issue by MFlyer** [remix-run/react-router#9462]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Build a react app, transpiling with Babel, deploy it on a device with Chrome <49

### Expected Behavior

Chrome not failing because of unsupported variables (let and const) / Avoid to have the webpack build process exclude with a custom rule to transpile react-router and @remix

### Actual Behavior

Chrome is not able to run the app because of unsupported js features (const and let)

To avoid any possible reply with concerns like "why do you care about those really old Chrome versions?" -> TV devices running on Chromium have those old versions too (some countries have 30% TV devices still running Chromium 47/48)

**Comment by timdorr** [comment]
If you're targeting a browser that old, you should be transpiling the entire bundle with Babel. This isn't something the library has to fix.

**Comment by MFlyer** [comment]
@timdorr we already have in place the babel and core-js transpile flow, but to "fix" the react-router issue we have to remove it from the excluded node_modules (both react-router & remix) and it's quite boring...but i get your point. Cheers
