### ISSUE TITLE
[Bug]: the website doesn't list proper installation steps in a simple understandable way

### ISSUE THREAD

**Issue by arunkumar413** [remix-run/react-router#9466]
### What version of React Router are you using?

16

### Steps to Reproduce

 The website doesn't list proper installation steps in a simple understandable way

### Expected Behavior

Installation steps on the home page 

### Actual Behavior

when we visit the home page the first noticeable thing should be installation steps in simple, easily understandable way.

**Comment by timdorr** [comment]
This is in the tutorial: https://reactrouter.com/en/main/start/tutorial
