### ISSUE TITLE
[Bug]: Unexpected token (1105:8) error when trying to run the react app

### ISSUE THREAD

**Issue by arunkumar413** [remix-run/react-router#9469]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Run this code https://github.com/arunkumar413/react-router-v6-example/tree/master/src with the command `npm start`

### Expected Behavior

The app should run correctly and display the components

### Actual Behavior

Throwing this error:
```
Failed to compile.

Error in ./~/@remix-run/router/dist/router.cjs.js
Module parse failed: /home/arun/projects/react-router-v6-example/node_modules/@remix-run/router/dist/router.cjs.js Unexpected token (1105:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1105:8)
 @ ./~/react-router-dom/dist/umd/react-router-dom.development.js 12:125-153
```

**Comment by timdorr** [comment]
That is an extremely old version of react-scripts, which is likely what is causing the problem. This isn't a bug with React Router.

**Comment by zambogo7** [comment]
I'm getting the same problem, any solution to this will actually appreciate.

Error in ./~/@remix-run/router/dist/router.cjs.js
Module parse failed: /home/zeddy/Desktop/zuri/projects/reactprofile/react-portfolio/node_modules/@remix-run/router/dist/router.cjs.js Unexpected token (1105:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1105:8)
 @ ./~/react-router-dom/dist/umd/react-router-dom.development.js 12:125-153
