### ISSUE TITLE
[Bug]: Hashrouter - hash gets included after the query params 

### ISSUE THREAD

**Issue by csrinivasan80** [remix-run/react-router#9476]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

When we get the OAuth callback with code to our application, the hash string gets included after the query params
Below is the url on Redirect to app:
http://localhost:3030/?code=xyz&provider=<<PROVIDER>>

Within react router with hashrouter, we can see it as 
http://localhost:3030/?code=xyz&provider=<<PROVIDER>>#/home

### Expected Behavior

http://localhost:3030/#/home?code=xyz&provider=<<PROVIDER>>

### Actual Behavior

http://localhost:3030/?code=xyz&provider=<<PROVIDER>>#/home

**Comment by timdorr** [comment]
The HashRouter uses the existing URL as a base in its entirety. It can't combine the two parts because they are fundamentally different URL segments.

**Comment by csrinivasan80** [comment]
Yes its different URL segments and when its within the context of SPA it need to begin with the hash bang and the the path and its query params. Otherwise we will not get the query param values as part of the searchParams within router context.
