### ISSUE TITLE
Add docs for JSX parsing details

### ISSUE THREAD

**Issue by ezheidtmann** [remix-run/react-router#9483]
I'm proposing adding a short note to the docs to make users aware of this under-documented behavior of JSX -- that string literals in JSX (`<Route path="..." />`) are parsed similarly to `String.raw` but string literals in JS (`<Route path={"..."} />`) are not. 

The `path-to-regex` docs specifically warn about escaping backslashes in strings, but that advice does not apply to literal JSX props!

For example, to match numeric user id paths like `/user/123`, all of these are equivalent:

- `<Route path="/user/:id(\d+)" />`
- `<Route path={"/user/:id(\\d+)"} />`
 - `<Route path="/user/:id([0-9]+)" />`
 - `<Route path={"/user/:id([0-9]+)"} />`

Note -- I could not find any  documentation describing this behavior of JSX, but it seems to be encoded in my editor's syntax highlighter and I've verified the behavior experimentally.

---

Example from an earlier issue:

 You need to double escape (`\\d`) the regular expression in order for the backslash to exist in the string. You would also run into the issue if you used:
```jsx
<Route path={"/slideshow/:year(\d{4})/:month/:day"} />
```
When you pass a string, the string is automatically double escaped for you.
```jsx
// input
<Test one="\test" two={"\test"} />

// output
React.createElement(Test, {
  one: "\\test",
  two: "\test"
});
```

_Originally posted by @pshrmn in https://github.com/remix-run/react-router/issues/6655#issuecomment-475291170_

**Comment by timdorr** [comment]
We don't use path-to-regexp in v6 and also don't recommend using string literals with JSX. Plus, that's a JSX thing that's not specific to React Router anyways.
