### ISSUE TITLE
[Bug]: Link (and NavLink) strip hash when using createBrowserRouter and RouteProvider

### ISSUE THREAD

**Issue by rehos** [remix-run/react-router#9484]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Context: Landingpage on which a user can navigate to different sections by using anchor tags.

See [Stackblitz](https://stackblitz.com/edit/github-9mhoxc?file=src%2FApp.tsx) for reproduction of the issue. [UPDATE] createMemoryRouter has the same issue as createBrowserRouter.

I have been able to track this issue down to `createHref` in [router.ts](https://github.com/remix-run/react-router/blob/5f3cfb7ac2ad823ecdf69069332567e35ad795c6/packages/router/router.ts#L2725)

```
function createHref(location: Partial<Path> | Location | URL) {
  return (location.pathname || "") + (location.search || "");
}
```

### Expected Behavior

If I specify a Link or NavLink I expect the anchor tag to preserve the hash

Given:
```
<Link to="/#about">About</Link>
```
I expect:
```
<a href="/#about">About</a>
```

Same for NavLink

### Actual Behavior

If I specify a Link or NavLink the anchor tag doesn't preserve the hash

Given:
```
<Link to="/#about">About</Link>
```
I actually get:
```
<a href="/">About</a>
```

Same for NavLink

**Comment by brophdawg11** [comment]
Thanks for the reproduction!  I think this is the same underlying issue as #9392 and it looks like `6.4.3-pre.0` does fix the issue in the stackblitz.  Please re-open the issue if you're still seeing problems on the prerelease!  We hope to have a 6.4.3 stable out soon.
