### ISSUE TITLE
[Bug]: documentation does not explain the *why* of using createElement

### ISSUE THREAD

**Issue by rudolfolah** [remix-run/react-router#9502]
### What version of React Router are you using?

v6

### Steps to Reproduce

Read the docs, all examples use the following code:

```
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
```

### Expected Behavior

For previous users of React Router v5 and previous and for those who use Create React App, the expected pattern does not look like this, it looks more like:

```jsx
function App() {
  return (<Router><Link>Home</Link><main><Switch /><main></Router>);
}
```

Based on that pattern and the usual pattern for providers, the expectation for React Router v6 would be closer to the following:

```jsx
const router = createBrowserRouter([...]);
function App() {
  return (<RouterProvider router={router}><Link>Home><main><Switch /></main></Router>);
}
```

### Actual Behavior

The [tutorial](https://reactrouter.com/en/main/start/tutorial) and the [upgrade from v5 instructions](https://reactrouter.com/en/main/upgrading/v5) do not contain an explanation for this change and how it affects the structure of a top-level App.

**Comment by timdorr** [comment]
The upgrade docs are for going from v5's Router components to v6's. The new RouterProvider component goes along with [the new data routers](https://reactrouter.com/en/main/routers/picking-a-router), which were added in 6.4.0. There isn't a direct upgrade path to them, so the upgrade instructions don't try to jump ahead too far. If you're using v5, you would need to rearchitect much of your app to use them. Sticking with the Router components is a better path to migrate to v6.
