### ISSUE TITLE
[Bug]: createRoutesFromElements is not nesting elements properly [v6.4.2]

### ISSUE THREAD

**Issue by asieraduriz** [remix-run/react-router#9504]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

https://codesandbox.io/s/react-router-createroutesfromelements-bug-v6hznf

### Expected Behavior

When navigating into `/editor` I would expect the `Editor` component to be rendered

### Actual Behavior

When clicking on the `Link` component, the URL updates correctly to `/editor` but the rendered react component is still `Root`

**Comment by brophdawg11** [comment]
👋 It looks like you forgot to include an `<Outlet/>` in your `Root` component to render children routes: https://reactrouter.com/en/main/components/outlet
