### ISSUE TITLE
[Help]: useNavigate ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by ikangjie** [remix-run/react-router#9514]
### What version of React Router are you using?

react-router-dom v6.4.2.  webview android v55

### Steps to Reproduce

If AbortController feature is not supported, useNavigate cannot jump

### Expected Behavior

Graceful degradation normal jump

### Actual Behavior

ReferenceError: AbortController is not defined, useNavigate cannot jump

**Comment by timdorr** [comment]
That is too old of a version of Chromium to support directly. You should be using a polyfill to provide AbortController support.
