### ISSUE TITLE
[Bug]: %2F char in URL generates 404 errors with Apache

### ISSUE THREAD

**Issue by scand1sk** [remix-run/react-router#9515]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

I have a route defined as :
`<Route path="show/:src" element={<ShowImage/>}/>`

":src" can contain arbitrary (relative) URI. To allow the route to match, I use encodeURIComponent, e.g. : 
`<a href={`/show/${encodeURIComponent(image)}`}>`

It replaces "/" with "%2F" chars instead. 

I recently updated React Router from v5 to v6 and simultaneously updated the production server (Apache 2.4.38-3+deb10u6 to Apache 2.4.38-3+debu8). In the previous configuration, it worked.

### Expected Behavior

Load <ShowImage> component with :src param.

### Actual Behavior

Now I get a 404 error when %2F appears in URL, but only in my production environment.

The bug is probably related to Apache, as it appears only in production. On my development environment, pages are served using NodeJS and it works.

**Comment by timdorr** [comment]
This isn't a React Router issue.
