### ISSUE TITLE
[Feature]: Performance improvement

### ISSUE THREAD

**Issue by budarin** [remix-run/react-router#9516]
### What is the new or updated feature that you are suggesting?

Since this package is basic for applications, I suggest using the best constructs in terms of performance in its code

### Why should this feature be included?

When investigating the performance of our application in `SSR`, we see that quite a lot of time is spent on utilities related to the definition of path: `matchPath`, `resolvePath`, `matchRoutes ` ....

![image](https://user-images.githubusercontent.com/8055157/198704568-faccbc2c-337b-4a84-830c-92e8423af9cc.png)
and this is only if there is a flat list of 3 routes !!!

In the code of these methods, we can see several constructions that are not very effective in terms of performance: `reduce`, `forEach`, `join`, `Object.assign` etc.

I will give the results of benchmarks of various constructions when testing on node.js

```
Test: reduce vs for
----------------------------------------------------
reduce x 36,690,248 ops/sec ±3.64% (82 runs sampled)
for x 70,249,367 ops/sec ±2.85% (77 runs sampled)

[ 'for' ] ~2 times faster!

Test: join vs for
-------------------------------------------------
join x 3,973,869 ops/sec ±5.51% (77 runs sampled)
for x 7,649,701 ops/sec ±4.20% (76 runs sampled)

[ 'for' ] ~1.93 times faster!

Test: forEach vs for
------------------------------------------------
map x 6,030,884 ops/sec ±5.40% (73 runs sampled)
for x 9,780,166 ops/sec ±3.32% (81 runs sampled)

[ 'for' ] ~1.62 times faster!

Test: map vs for
------------------------------------------------
map x 6,844,958 ops/sec ±3.21% (75 runs sampled)
for x 9,373,973 ops/sec ±4.72% (75 runs sampled)
 
[ 'for' ] ~1.36 times faster!

Test: spread vs Object.assign({}, obj) (big object)
--------------------------------------------------------
Object.assign x 261,827 ops/sec ±3.90% (80 runs sampled)
spread x 267,121 ops/sec ±5.31% (78 runs sampled)

[ 'spread' ] ~=

Test: spread vs Object.assign({}, obj) (small object)
----------------------------------------------------------
Object.assign x 7,359,946 ops/sec ±3.64% (78 runs sampled)
spread x 26,776,293 ops/sec ±6.28% (66 runs sampled)

[ 'spread' ] ~3.64 times faster !
```

**Comment by timdorr** [comment]
Thanks, but these seem to be micro-optimizations at the expense of possibly clearer code. Personally, I don't find these generally worthwhile, as they're not going to be the source of perceivable performance problems by users. 

If you want to put together a PR with specific changes, that's probably a better format for this. If there is something significant, we can discuss the merits of performance vs maintainability.

**Comment by budarin** [comment]
It 's sad to hear that !

we are fighting for performance on the server in order to use resources to the maximum benefit for us and the user, but you obviously focus only on browser execution where performance flaws are not so obvious

**Comment by kiliman** [comment]
It's not that they aren't focused on performance. But you are running micro-benchmarks, and they have higher priorities than taking a flier on these changes.

As Tim says, if you want to submit a PR that shows these changes make a significant performance improvement, I'm sure the team would gladly reconsider.

**Comment by budarin** [comment]
I did not just write something, but presented a real flamegraph where it is clear that these functions are quite often in the top and take up a significant part of the work of the router

Microbenchmarks, in turn, show that the operation of these functions can be optimized by a factor of 2 in terms of performance

No one suggests using for everywhere in the source code, but for the benefit of users, you can use babel-plugins in building, which will replace slow constructions with faster ones!?

unfortunately, I don't have enough time to do PR - there is a big load on my project and I have to write an issue or do PR in other packages, too, and it takes time :(
