### ISSUE TITLE
[Bug]: Protected Routes are not protected anymore

### ISSUE THREAD

**Issue by MadaShindeInai** [remix-run/react-router#9529]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

1. Use link to reach codesandbox https://codesandbox.io/s/amazing-matsumoto-cdbtow?file=/src/index.tsx
2. In builded app remove `/auth` from url or replace it with `'/test'`
3. Check console to see 'main' or 'test' logs.

### Expected Behavior

Routes `'/'` and `'/test'` are **Protected**.  `loader` is a function that will fetch me some data and require auth token (now do console log).
I expect that ProtectedRoute logic should prevent us from rinning ` loader ` function if user are not authenticated.

### Actual Behavior

Request will be sent (we will see console.log) anyway with token or without. 
This makes ProtectedRoutes - BadlyProtectedRoutes as they generally do not protect us anymore. ¯\_(ツ)_/¯

**Comment by brophdawg11** [comment]
Fetching is decoupled from rendering in 6.4, so loaders run _before_ any rendering logic.  You should lift your "requires authorization" logic out of the `RequireAuth` component and into your loaders and redirect from there.  Redirecting during render is too late 😄 

Also note that all loaders for a matched route route run in parallel, so you should check in each loader for now ([just like in Remix](https://remix.run/docs/en/v1/pages/faq#how-can-i-have-a-parent-route-loader-validate-the-user-and-protect-all-child-routes)).  We plan to make this easier to do in one place in the future.
