### ISSUE TITLE
[Feature]: Multiple actions per page/route.

### ISSUE THREAD

**Issue by Christianey** [remix-run/react-router#9538]
### What is the new or updated feature that you are suggesting?

What happens if you have different actions on a particular page/route? I think it would be nice for pages/routes to be able to get multiple actions for different write requests. Is there any way around this for now? Thank you. 

### Why should this feature be included?

It enables React Router handle different possibilities of actions on a page/route.

**Comment by brophdawg11** [comment]
Most folks accomplish this with a name/value on the submit button or with a hidden input holding an `intent` value:

```jsx
async function action({ request }) {
  let formData = await request.formData();
  let intent = formData.get('intent');
  if (intent === 'add') {
    await addThing(formData);
  } else if (intent === 'delete') {
    await deleteThing(formData);
  }
  return json({ ok: true });
}

function Component() {  
  return isAdding ?
    (
      <Form method="post">
        ...
        <button type="submit" name="intent" value="add">Add Thing</button>
      </Form>
    ) : (
      <Form method="post">
        ...
        <button type="submit" name="intent" value="delete">Delete Thing</button>
      </Form>
    );
}
```

**Comment by Christianey** [comment]
Thank you.

**Comment by joeymigs** [comment]
How to handle this situation idiomatically—where you have multiple non-navigation events to be handled via a route's action, like triggering a record add/delete/edit from the same route component—is actually very difficult to figure out with the current documentation. This seems like a really common scenario, but isn't really documented. If more information/suggestions about how to handle this could be added to the docs, that would be greatly appreciated.

**Comment by brophdawg11** [comment]
Good idea!  Added in https://reactrouter.com/en/main/route/action#handling-multiple-actions-per-route

**Comment by bogdy9912** [comment]
What if i have 2 forms on the same page, and I want to have a placeholder only for the form that I am submiting? Having 2 actions  will solve this because I will check the status of separate actions. 

In the above approach, the submiting state  is not relevant, as submiting a form will make the status of the action(which is shared by both forms) = submit

**Comment by brophdawg11** [comment]
As shown in https://reactrouter.com/en/main/route/action#handling-multiple-actions-per-route, each form should have a unique `intent` (or other field) that lets you determine which action is running.  Then you can look for that:

```js
let navigation = useNavigation();
let isSubmittingAddForm = navigation.state !== "idle" && navigation.formData?.get('intent') === "add";
let isSubmittingEditForm = navigation.state !== "idle" && navigation.formData?.get('intent') === "edit";
```
