### ISSUE TITLE
[Feature]: add persistent query parameters during routing

### ISSUE THREAD

**Issue by IdoWald-TomTom** [remix-run/react-router#9541]
### What is the new or updated feature that you are suggesting?

When using the Link to route between different routes,
It could be nice if there are some settings/configuration to make all the query parameters of the current URL to stay in the browser to the next URL.
Some thing like:
`      <Link to={'/newRoute'} >Go there</Link>
`
from URL 'http:.../oldRoute?myId=12345' will redirect after a click to 'http:.../newRoute?myId=12345'
There are two possible solutions to get this feature.
1. To add some configuration in the app that all rerouting events with Links will keep the url params.
2. To add some property to Link that will persist the query changes like `<Link to='newRoute' persist>...`

### Why should this feature be included?

Many times we have some url parameters that we want to keep during rerouting. 
We need to do it programatically right now
see issue: https://github.com/remix-run/react-router/issues/2185 
It could be nicer to have something build-in that does that.
Keeping the query params is handy when you want to keep some state from urls for example during refresh or sharing the URL with another client.

**Comment by timdorr** [comment]
Thanks, but this doesn't really fit with the idioms of Link. It already does manipulation of the path provided. 

Instead, you can simply do this:
```js
<Link to={'/newRoute' + location.search}>Go there</Link>
```

**Comment by norayr93** [comment]
Then how do you handle a situation where you are redirecting from the loader and don't have access to the location object?
