### ISSUE TITLE
[Bug]: Dev message in prod build

### ISSUE THREAD

**Issue by Speedy1991** [remix-run/react-router#9542]
### What version of React Router are you using?

6.4

### Steps to Reproduce

- Create a minimal app with react router
- Throw an error without an errorElement
- Run a production build

### Expected Behavior

Do not show any dev related information

### Actual Behavior

Currently, there is always some dev information. This is really confusing for customers if the dev is not aware that there is a default error component.
![image](https://user-images.githubusercontent.com/15920408/199459188-bbe7a11e-0835-4ec1-9da8-95dd8317c9a7.png)

Maybe it's a good idea to mount a simplified [DefaultErrorElement](https://github.com/remix-run/react-router/blob/8e09bd601bd7f3066ff598ddd8e23b9b7cc462b3/packages/react-router/lib/hooks.tsx#L441) with only the [message ](https://github.com/remix-run/react-router/blob/8e09bd601bd7f3066ff598ddd8e23b9b7cc462b3/packages/react-router/lib/hooks.tsx#L443) output if `process.env.NODE_ENV !== 'production'`?

**Comment by ScorpAL** [comment]
Same issue in `react-router-dom: 6.7.0`

**Comment by brophdawg11** [comment]
The solution to "don't show dev information" is to implement an `errorElement` of your own and choose what to display.   We explain the reasoning for this suggestion further in the [docs](https://reactrouter.com/en/main/route/error-element#default-error-element).  With the merged PR we have removed the "Hey Developer" language as a middleground though.
