### ISSUE TITLE
[Bug]: `react-router-native` Conflicting peer dependency with `react-native` 

### ISSUE THREAD

**Issue by aajahid** [remix-run/react-router#9549]
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

Try installing `react-router-native` and `react-native` (  0.70.4 ) in  your project using nodejs `16.18.0`

### Expected Behavior

`npm install` finishes installing `react-router-native`

### Actual Behavior

It fails to install `react-router-native` with bellow error. Which make sense as - 
react-router dependency `"react": "^18.2.0"` 
while - react-native dependency `"react": "18.1.0"` 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/1908862/199669147-f73b17c9-d92e-4da5-adcb-47c1e8b2eeb3.png">

Either I've to just wait until react-native update their react dependency or try a work around using `--legacy-peer-deps`. But they are work around - not proper solution.

**Comment by timdorr** [comment]
React Router has a dev dependency on 18.2.0. This doesn't apply when installing the library. 

You have something else going on here with conflicting react versions in your installation. This isn't a React Router bug.

**Comment by aajahid** [comment]
Can you at-least try to recreate the issue yourself?
Here is the package.json - just use node 16.18.0 do a `npm install`. If it works - then please close the issue.

```
{
  "private": true, 
  "dependencies": {
    "react-router": "6.4.1",
    "react-router-dom": "6.4.1",
    "react-router-native": "6.4.1"
  },
  "devDependencies": {
    "glob": "^7.1.3",
    "gulp": "^4.0.0"
  }
}
```

Just to clearify - the issue is on `react-router-native` the range for `peerDependency` are 
<img width="160" alt="image" src="https://user-images.githubusercontent.com/1908862/200102195-79bfda82-e7d9-408e-ac03-9dbc2e139df3.png">

So when NPM look up for latest "react" version - it picks - `18.2.0`. 
And for "react-native"  `17.0.4` - which again have strict peerDependency of react `18.1.0`.
So the conflict happens.
