### ISSUE TITLE
[Bug]: useLoaderData() hook causes rendering before router transition

### ISSUE THREAD

**Issue by gmaxlev** [remix-run/react-router#9551]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

React 18.2.0, strict mode is disabled

I have defined my routes with `createBrowserRouter` function and used `<RouterProvider>` component, so I have got following:

```js
const routes = createBrowserRouter([
    {
      path: "/page-1",
      element: <PageOne />,
      loader() {
        return api.entity.one();
      },
    },
    {
      path: "/page-2",
      element: <PageTwo />,
      loader() {
        return api.entity.two();
      },
    },
])

<RouterProvider router={routes} />
```

My elements are simple React components with the following structure:
```js
function PageOne() {
    const dataFromApi = useLoaderData()
    // ... some rendering
}
```

I use `useLoaderData()` hook to get loaded data from `loader()` function.

### Expected Behavior

I would be happy if `useLoaderData()` hook will cause rendering **ONLY** when `loader()` function is called again and **ONLY** if it is own loader function.

### Expected Log

1. The current route is _/page-1_, the first rendering of `<PageOne/>`
2. Click on the link `<Link/>` to move on _/page-2_ route
3. Call `loader()` function of _/page-2_ route
4. **`<PageOne/>` component do not call rendering because his result of `useLoaderData()` hook returns the same data**
5. ` loader()` from 3 log is completed and `<PageTwo/>` component  of _/page-2_ route renders successfully, transition is completed.

### Actual  Log

1. The current route is _/page-1_, the first rendering of `<PageOne/>`
2. Click on the link `<Link/>` to move on _/page-2_ route
3. Call `loader()` function of _/page-2_ route
4. **`<PageOne/>` component renders again although his route's`loader()` function has not be called and  `useLoaderData()` hook returns the same data!**
5. **The `loader()` function from 3 log can be still not completed (Promise has _pending_ status)**
6.` loader()` from 3 log is completed and `<PageTwo/>` component  of _/page-2_ route renders successfully, transition is completed.

**Comment by timdorr** [comment]
This is expected behavior. When you click the Link, you're starting a navigation. Because loaders are asynchronous, we re-render your tree with the navigation state of "loading" in case you want to show a transitional UI. You can read more about this here: https://reactrouter.com/en/main/start/overview#pending-navigation-ui
