### ISSUE TITLE
🗺 Loader+Action Context (Middleware)

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#9566]
## Progress

- [x] RFC #9564 
- [ ] PR

**Comment by narutosstudent** [comment]
This is exciting! 🔥

**Comment by kentcdodds** [comment]
This will be *super* helpful so I can ditch express and just rely on remix-serve 🔥

My specific use case includes auth (of course), but also I'm working on implementing this: https://fly.io/docs/litefs/files/#using-txid-to-handle-consistency

So, basically, when a user makes a mutation in a non-primary region, I need to force them to wait until that data has been propagated to their region before they can read their local db.

Things get kinda funny when you distribute your data, but want to make sure there's consistency as well as availability & partition tolerance (pick two, add one 😅).

**Comment by narutosstudent** [comment]
Nice! 😄 

Our use case also includes auth, getting the user through the context, in both the actions and loaders. 🔥

**Comment by AMoktar** [comment]
@runarj hey bro, I hope you having a nice day too.
Im sorry but, I believe this is not the right place for suggestions, I mean you are talking about complicated things, you looks a pro dude, are you kidding :)) 
I'm totally know nothing about what you are talking about

look bro There are the https://github.com/remix-run/react-router/discussions and https://github.com/remix-run/react-router/issues
we need to keep this board clean for the great guys here doing a lot for free for us 
Respect bro :) @runarj
Respect and appreciation for you guys (*: @ryanflorence

**Comment by AMoktar** [comment]
Thanks a lot guys for all this effort 👍

**Comment by ryanflorence** [comment]
@jacob-ebey and @brophdawg11 to try to wrap up the adapter/bundling questions, then bring in @ryanflorence and @mjackson for an API review

**Comment by brophdawg11** [comment]
Closing this temporarily since we put this on hold while we finalize Remix v2.  This is early on the roadmap once v2 is out so will re-open then.
