### ISSUE TITLE
[Bug]: Errors in nested <Route> components are not bubbling up to parent routes

### ISSUE THREAD

**Issue by evoyy** [remix-run/react-router#9568]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

An error boundary is specified for the top level data API route, and an error is thrown further down the component tree.

````javascript
function Root() {
  const router = createBrowserRouter([{
    path: "settings/*",
    element: <Settings />,
    errorElement: <div>Error!</div>,
  }]);

  return (
    <RouterProvider router={router} />
  );
}

function Settings() {
  return (
    <Routes>
      <Route path="email-address" element={<EmailAddress />} />
      <Route path="email-preferences" element={<EmailPreferences />} />
      // ...
    </Routes>
  );
}

function EmailAddress() {
  throw 'Some error';
}
````

React Router will catch the error and display an error template. The error does not bubble up to the root error boundary.

The only way that errors reach the root error boundary is if an `errorElement` is specified for every `<Route>` in order to catch and re-throw the error:

````javascript
// catch and re-throw
function ErrorBoundary() {
  let error = useRouteError();
  throw error;
};

function Settings() {
  return (
    <Routes>
      <Route path="email-address" element={<EmailAddress />} errorElement={<ErrorBoundary />} />
      <Route path="email-preferences" element={<EmailPreferences />} errorElement={<ErrorBoundary />} />
      // ...
    </Routes>
  );
}
````

### Expected Behavior

I expect that the error will bubble up the root error boundary if no `errorBoundary` is specified.

According to the documentation:

> When a route does not have an errorElement, errors will bubble up through parent routes. This lets you get as granular or general as you like.
>
> Put an errorElement at the top of your route tree and handle nearly every error in your app in one place. Or, put them on all of your routes and allow the parts of the app that don't have errors to continue to render normally. 

### Actual Behavior

React Router catches the error. It does not bubble up to the root error boundary unless it is re-thrown.

**Comment by timdorr** [comment]
The `Routes` component is separate from the new data router components. It doesn't participate in data loading or error handling ([see the note here](https://reactrouter.com/en/main/components/routes)). As a result, it doesn't know about the data router or pass errors to it.

**Comment by evoyy** [comment]
@timdorr The project direction seems to be pushing towards data router components. Please can you clarify if it is a possibility that the `Routes` component might be deprecated in the future?

I need to use `Routes` because I use the stateful modal technique (passing a previous `location` to the `Routes` behind the modal). I also like to have access to the router instance for asserting tests. It seems "catch and re-throw" is the only way I can unify my error handling.

**Comment by timdorr** [comment]
They won't be deprecated, they are just an older form of using React Router. They essentially exist separately from the data routers, so you should use one or the other. Using both is not recommended, unless you are okay with the limitations.

**Comment by evoyy** [comment]
Got it. Thank you.

**Comment by nishant23122000** [comment]
@evoyy @timdorr so is there any way to handle errors by putting errorElement on the top level?

**Comment by evoyy** [comment]
@nishant23122000 Yes. My issue was mxing the `<Routes>` component with the new data router API. If you define all your routes using the new data router API then you can catch all errors with a single errorElement at the top.

**Comment by nishant23122000** [comment]
Hi, @evoyy can you share any example or link as I am new in react-router?

**Comment by evoyy** [comment]
@nishant23122000 Have you tried the tutorial? https://reactrouter.com/en/main/start/tutorial

**Comment by nishant23122000** [comment]
@evoyy Thanks for sharing this. I got my answer :)

**Comment by timdorr** [comment]
@woodreamz That kind of thing is coming via #9996

**Comment by jasikpark** [comment]
> > The `Routes` component is separate from the new data router components. It doesn't participate in data loading or error handling ([see the note here](https://reactrouter.com/en/main/components/routes)). As a result, it doesn't know about the data router or pass errors to it.
> 
> @timdorr I just wanted to mention that the comment you link to doesn't mention error handling at all. It would've been really helpful if it did when I was doing a migration from v5 over the past few days and ended up catching this while testing all of the changes. Might be worth adding it to the documentation along with the fact that it doesn't participate in data loading.

Just added a PR to update that docs infoblock - #10372

**Comment by jasikpark** [comment]
> @woodreamz That kind of thing is coming via #9996

Is there another PR I can track to see the status of a replacment for `<Routes>`? I'm stuck on RRv5 since <6.4 doesn't provide `useBlocker` and >6.4 doesn't provide `<Routes>`
