### ISSUE TITLE
[Bug]: Defer causes all `useLoaderData` to not revalidate until defer is complete

### ISSUE THREAD

**Issue by fezproof** [remix-run/react-router#9570]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

Stackblitz repro

https://stackblitz.com/edit/github-rrnioq

Click revalidate button and see that the layout loader + the awaited defer data loader does not change until the slow suspended data has completed.

### Expected Behavior

Loaders unrelated to the defer load as fast as they can.

### Actual Behavior

When a deferred data loader is currently mounted, all `useLoaderData` hooks will not update until the slowest part of the defer is complete.

This can cause issues for for updates or just revalidation calls.

**Comment by timdorr** [comment]
This is expected behavior for the default usage of loaders. To handle slow loading data, you should use the components and APIs for deferred data: https://reactrouter.com/en/main/guides/deferred

**Comment by yfa-vagelis** [comment]
> This is expected behavior for the default usage of loaders. To handle slow loading data, you should use the components and APIs for deferred data: https://reactrouter.com/en/main/guides/deferred

Documentation of `useLoaderData` says that it provides the value returned from your route loader. I still can not see why this is expected to get the "old" (fulfilled) Promise instead of the new (Pending) one. Can you please explain it in more detail?

**Comment by michaellow-ca** [comment]
> > This is expected behavior for the default usage of loaders. To handle slow loading data, you should use the components and APIs for deferred data: https://reactrouter.com/en/main/guides/deferred
> 
> Documentation of [useLoaderData](https://reactrouter.com/en/main/hooks/use-loader-data) says that it provides the value returned from your route loader. I still can not see why this is expected to get the "old" (fulfilled) Promise instead of the new (Pending) one. Can you please explain it in more detail?
> 
> **Update**: Finally, I figure it out. The "expected" behavior (i.e. getting the `fallback` Component of `Suspense` show again after clicking the revalidate button) can be achieved simply by removing `defer`! Thanks anyway and sorry for the inconvenience!

Thank you for this. I was stuck on the same thing, and the docs have no mention of how to fix it.
