### ISSUE TITLE
[Bug]: the signal does not indicate that the request is aborted after navigating to another route

### ISSUE THREAD

**Issue by ofirgeller** [remix-run/react-router#9579]
### What version of React Router are you using?

react-router 6.4.2 (dom)

### Steps to Reproduce

* Inside of a route loader capture the request object and log request.signal every second using setInterval.
* navigate away from the route that triggered the loader

### Expected Behavior

I would expect the signal to indicate the request has been aborted so that may multi step loader can stop when the result is no longer needed.

### Actual Behavior

I get
AbortSignal {aborted: false, reason: undefined, onabort: null}

Even after navigating away

**Comment by timdorr** [comment]
Can you share some code, please?

**Comment by ofirgeller** [comment]
this would be the loader:

```js
   loader: ({ request }) => {
                setInterval(() => console.log('request.signal', request.signal), 1000);
                return null;
            }
```

**Comment by ofirgeller** [comment]
@timdorr can you tell me if the expected behavior is correct? that will allow me to move ahead knowing this will get fixed/implemented.

I was basing my expectations on philosophy in the docs. the app is making a request to view a page, the loaders translates the needs of the view into a promise for data. if the page is no longer being loaded the request should be aborted.

**Comment by brophdawg11** [comment]
This is correct in this case because since your `loader` is synchronous, so the navigation completes immediately and when you navigate again there is no in-progress navigation to abort.  If you have an asynchronous loader that takes a while to resolve and you navigate _before_ it resolves, you should see the signal get aborted.

**Comment by ofirgeller** [comment]
Thanks, it does make sense when you think about it like that. @brophdawg11
