### ISSUE TITLE
[Bug]: useNavigate([delta]) remove the last path segment instead of moving down the History stack.

### ISSUE THREAD

**Issue by Lofty-Brambles** [remix-run/react-router#9582]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

__Navigate from:__ 
`/` -> `/page1` -> `/page2`

reverts one to `/` instead of `/page1`

Here is a minimum reproducible example.
https://stackblitz.com/edit/react-ts-69lvcr?file=Page2.tsx

### Expected Behavior

I was initially looking for a way to simply move down the history stack and revert back to the last page visited by the user when we use a delta value of -1 in the `useNavigate()` hook.

### Actual Behavior

However, when used, it simply seems to be removing the last path segment instead of it.

**Comment by brophdawg11** [comment]
This is happening because of `React StrictMode`.  The dual-rendering of your component in strict mode in dev means that you end up calling `navigate(-1)` twice, which is why you end up back at the index page. 

You should be able to address this by guarding the navigation to avoid dual calls:

```jsx
function Page2() {
  const didRedirect = React.useRef(false);
  const navigate = useNavigate();
  React.useEffect(() => {
    if (didRedirect.current) return;
    didRedirect.current = true;
    navigate(-1);
  }, [navigate, didRedirect]);
  ...
}
```

**Comment by Lofty-Brambles** [comment]
Ah, gotcha. Thanks!
