### ISSUE TITLE
[Bug]: Routes defined using useRoutes unable to identify that they are within BrowserRouter

### ISSUE THREAD

**Issue by incorelabs** [remix-run/react-router#9583]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

The steps are pretty simple. I built the example on top of the React Router tutorial found here https://reactrouter.com/en/main/start/tutorial

**Code Sandbox Reproduction:**
[Link to Code Sandbox with buggy version](https://codesandbox.io/p/sandbox/useroutes-bug-react-router-6-v0m39m?selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A2%7D%5D&file=%2Fsrc%2Fmain.jsx&workspace=%257B%2522activeFileId%2522%253A%2522cl9zkf3e80007lqip0mj5gbt7%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fmain.jsx%2522%252C%2522%252Fsrc%252FAppRoutes.jsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522claf3qlnh006al1ipdm122e1m%2522%252C%2522key%2522%253A%2522claf3qlcz00mb3b6n8gj1djpd%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522claf3lknc000n3b6na66p2k35%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

The only changes I made were:
- Pass the `routes` to `useRoutes` instead of `createBrowserRouter`.
- Thus I replaced `createBrowserRouter` with using `<BrowserRouter>` in `main.jsx`

Everything else renders exactly like how the tutorial is.

### Expected Behavior

There should not be any change in behaviour and all the routes should render how they did before.

### Actual Behavior

I encounter an error in the Chrome Dev Tools which says,

`Uncaught Error: useLoaderData must be used within a data router`

<img width="1680" alt="Screen Shot 2022-11-13 at 2 45 32 PM" src="https://user-images.githubusercontent.com/1456419/201514728-9ba98bcf-2552-468c-844f-09e0dc0b2e5f.png">

**Comment by timdorr** [comment]
You're still using a bunch of hooks and APIs that require a data router. You can't swap for a BrowserRouter and have those still work. This is expected behavior.

**Comment by incorelabs** [comment]
#1 I'm curious, how is using `<BrowserRouter />` different from using `createBrowserRouter`? They both seem to have the same name, shouldn't they be doing the same thing?

#2 What would be considered a `data router` if not Browser Router considering the fact that the code works perfectly fine when I use `createBrowserRouter`?

**Comment by incorelabs** [comment]
PS: Read the documentation again seems `<BrowserRouter />` is not supporting data apis. Apologies on that, should have checked. I'll figure something and get back on this. I was assuming that it was the same as using `createBrowserRouter`.
