### ISSUE TITLE
[Bug]: Manual url change and refreshing not working i 6.3.0 - 6.4.3

### ISSUE THREAD

**Issue by malinhanak** [remix-run/react-router#9600]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

* Either create a normal Router setup with <BrowserRouter> containing nested routes, or use RouterProvider with createBrowserRouter.

When running an application using this the first index path of / works in dev, in production I can't even get that to work. You simply get `cannot GET <path>` or if you have a NoMatch or ErrorElement that is displayed. This is also true for any kind of nested routes in dev environment.

NOTE: using HashRouter or createHashRouter works like it should, it just gives a ugly URL, and in your documentation you are advising no to use Hash URLs.

### Expected Behavior

Would be that I can manually type in the URL and the page/path should resolve.

### Actual Behavior

As it is now I cannot send the link to my page to anyone because if they try to open it they will get the `cannot GET` message. It makes it impossible to develop as well when you cannot access anything but the index path.

**Comment by timdorr** [comment]
This is something about your production setup outside of just React Router. This isn't a bug with the library.

**Comment by malinhanak** [comment]
But its not only in production it's the same behaviour in local development environment.

**Comment by timdorr** [comment]
`cannot GET <path>` sounds like you don't have your express server set up correctly. You need a wildcard route in express to send all URLs to your React Router page.

**Comment by kobe651jp** [comment]
I have the same problem.But it's not working only in production environment.It's working fine in development environment.

The strange part is that '/' automatically moves to '/welcome' and works fine.
However, if you enter '/welcome' directly, it will not work.

Sample code as follows.

```
    <Routes>
      <Route path="/welcome" element={<LandingPage />} />
      <Route path="/" element={<Navigate to={'/welcome'} />} />
      <Route path="*" element={<PageNotFound />} />
    </Routes>
```
