### ISSUE TITLE
[Docs]: the image on the line 10 of the tutorial page is broken

### ISSUE THREAD

**Issue by nykhylsharma** [remix-run/react-router#9607]
### What version of React Router are you using?

Latest

### Steps to Reproduce

Go to link https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md
Check the image on line 10

### Expected Behavior

The image shouldn't be broken

### Actual Behavior

The image on #10 of https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md is broken

**Comment by nykhylsharma** [comment]
Hi Mehdi,

Thanks for sharing the URL. In this case, the tutorial URL on React
Router's readme page(https://github.com/remix-run/react-router) should
point to it. It points to
https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md
instead

**Comment by Jagholin** [comment]
Also, the link on https://www.npmjs.com/package/react-router-dom also points to https://github.com/remix-run/react-router/blob/main/docs/start/tutorial.md

**Comment by timdorr** [comment]
That is the intended link.

**Comment by beeburrt** [comment]
What's going on with the web site? I'm getting an error screen. I had to use Wayback Machine to go back to Dec 22nd to view the site.
