### ISSUE TITLE
[Bug]: using redirect with absolute urls

### ISSUE THREAD

**Issue by lockr7** [remix-run/react-router#9619]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

https://stackblitz.com/edit/github-1i2a85-k1qgvo?file=src%2Froutes.tsx%3AL132-L132

I added a `redirect` in my loader to an absolute url. You can reproduce by going to https://github-1i2a85-k1qgvo-pguekdga--3000.local-credentialless.webcontainer.io/todos (need to have the Stackblitz running in another tab) or by clicking the Todos `Link` that hits the `todosLoader`.

### Expected Behavior

I would expect to be able to use redirect with absolute urls and not hit a 404. If this is not allowed behavior I would want the docs updated

### Actual Behavior

Using redirect with absolute urls shows a 404 screen

**Comment by brophdawg11** [comment]
This should be working now, a fix went out with [6.4.4](https://github.com/remix-run/react-router/releases/tag/react-router-dom%406.4.4) last week 👍
