### ISSUE TITLE
[Feature]:  Use of handle is described in the official documentation

### ISSUE THREAD

**Issue by guaijie** [remix-run/react-router#9626]
### What is the new or updated feature that you are suggesting?

The documentation simply describes his type definition, and that's it
![image](https://user-images.githubusercontent.com/30885718/203460946-22bad386-fc64-44e6-8676-ff7781348b1f.png)

### Why should this feature be included?

I'd like to see handle in the official documentation, otherwise developers won't be able to understand it
const homeRoute: RouteObject = {
  path: '/home',
  element: <Home />,
  handle: {
    title: 'home'
  }
}
const handle = useMatches().at(-1)?.handle
const title = handle.title

**Comment by timdorr** [comment]
This is described more fully on the other side of the API, `useMatches`: https://reactrouter.com/en/main/hooks/use-matches
