### ISSUE TITLE
[Bug]: Error with message of "... call aborted" is thrown instead of standard DOMException

### ISSUE THREAD

**Issue by faergeek** [remix-run/react-router#9629]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

Launch `examples/ssr-data-router` with `npm run dev`. Open it in browser and either click Refresh/Stop browser button or press Ctrl/Cmd+R without a pause.

### Expected Behavior

[AbortSignal.prototype.reason](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason) is thrown, which defaults to `DOMException` with the name `'AbortError'` (or whatever you pass to `abort` method) and it's relatively easy to distinguish from other errors with code like `err instanceof DOMException && err.name === 'AbortError'` or matching with whatever value the user passes to `.abort`.

### Actual Behavior

`Error` instance with message `"... call aborted"` is thrown (can be seen in output of the running server), which needs custom logic matching error message to distinguish it from other errors.

The relevant code throwing that error exists inside [submit](https://github.com/remix-run/react-router/blob/f3d3e05ec00c6950720930beaf74fecbaf9dc5b6/packages/router/router.ts#L2056) and [loadRouteData](https://github.com/remix-run/react-router/blob/f3d3e05ec00c6950720930beaf74fecbaf9dc5b6/packages/router/router.ts#L2191).

Replacing both of those lines with `throw request.signal.reason;` would throw expected error, which is `DOMException` with `'AbortError'` by default or whatever the user passes to `.abort` call.

If there are no good reasons to keep it as it is, I'm more than happy to submit a PR for that change.

**Comment by faergeek** [comment]
@brophdawg11 great 👍 , I'll push a PR soon

**Comment by faergeek** [comment]
So, it seems like it won't work because of a polyfill used https://github.com/mysticatea/abort-controller/issues/33

I also tried to not use polyfill by removing "setupFiles" option from jest config (node supports fetch from version 18 without a flag https://nodejs.org/api/globals.html#fetch). But for some reason tests error with "Request is not defined". And that's strange, because if I add `console.log(Request)` right into a `jest.config.js`, it's there, but inside tests it's not defined for some reason.

@brophdawg11 do you have any idea what could be wrong?

**Comment by faergeek** [comment]
@brophdawg11 Does it make sense to drop polyfill and depend on fetch apis from node 18? Or it's not worth to even try for now?

**Comment by brophdawg11** [comment]
Hm - not offhand.  My hunch is that there's something also polyfilling down inside `@remix-run/web-fetch`.  Even if we figured out the test/polyfill issue - would we still have to be conditional since `reason` is not going to be supported everywhere?

```js
if (request.signal.reason instanceof Error) {
  throw request.signal.reason;
} else {
  throw new Error("queryRoute call aborted");
}
```

**Comment by faergeek** [comment]
Hm, yes. We can only get rid of the polyfill here and use `signal.reason` if remix/react-router itself would drop support for node < 18, so we're sure that it will work without polyfill. Otherwise it seems that the only way to fix it is to add proper `reason` support to polyfill. But it looks like polyfill code is not touched over 3 years already, may be it's abandoned. So most probably it would require to maintain a fork for that

**Comment by jcoc611-gvt** [comment]
What's the recommended best practice here? Always wrap `await router.query(...)` with try-catch?

**Comment by brophdawg11** [comment]
Yes - you should always wrap that in case it throws from being interrupted by another request.

**Comment by kevin1193** [comment]
Is there a resolution for this?

**Comment by nabeelpkl** [comment]
facing same issue on remix server, any solution for this?

**Comment by acolchagoff** [comment]
Actively dealing with this problem. Any updates here?

**Comment by brophdawg11** [comment]
I can take a look at this again now that v2 is node 18+ and polyfills are user-driven

**Comment by kevin1193** [comment]
Great to hear! Looking forward on resolving this!

**Comment by zolzaya** [comment]
any updates?
