### ISSUE TITLE
[Feature]: Typesafe useParam 

### ISSUE THREAD

**Issue by chann44** [remix-run/react-router#9635]
### What is the new or updated feature that you are suggesting?

so can we add type safe useparams 
like if you have a param in a route that should be string and it's name is userid 
so can i have a type safety on that so i can get suggestion what i named my param and which type it receive 

### Why should this feature be included?

it makes development experience better and we can reduce bugs and overhead of remembering names  of param

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8200#issuecomment-1023658322
