### ISSUE TITLE
[Bug]: useParams inside component causes rerender when changing hash

### ISSUE THREAD

**Issue by sarahfmurray** [remix-run/react-router#9636]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

- Set up a minimal router and component.
```
// router.js
...
const router = createBrowserRouter(
  [
    {
      path: "/",
      element: <div />
    },
    {
      path: "/test",
      element: <Test />
    }
  ]
)

// App.js
...
<RouterProvider router={router} />
...

// Test.js
...
import { useParams } from 'react-router-dom';
import { router } from '../router.js';

export default () => {
  console.log('reload')

  const params = useParams();

  return <div><h1>Test</h1><button onClick={() => router.navigate("#hello")}>Test button</button></div>
}
```
- Clicking the button to update the hash will cause the component to rerender.
- Comment out the `const params = useParams();` line
- Clicking the button to update the hash will not cause the component to rerender.

### Expected Behavior

The params aren't changing on pressing a button that changes the hash, so I would expect that the component is not rerendered when params are being tracked as well.

### Actual Behavior

Every time I press the button the component is rerendered.

**Comment by timdorr** [comment]
`useParams` is dependent on the current location. Whenever you `router.navigate()`, regardless of the contents of the new location, that will create a new location and `useParams` will trigger an update.

**Comment by Peter-Schorn** [comment]
I experienced this issue in my app too, as my app has an input field that updates that hash. With the `useParams` hook, the entire component would rerender every time the user typed a character in the input field, causing unacceptable performance issues.  I had to abandon the `useParams` hook and just parse the parameters from the URL myself, which is a little brittle and isn't exactly ideal.

Given that the route for my component does not use the hash for any dynamic parameters, the return value of `useParams` remains the same when the hash changes. Therefore, it seems like it's unecessary for this hook to cause a re-render. Could you at least explain why it is necessary for `useParams` to cause a rerender if its return value hasn't actually changed?
