### ISSUE TITLE
[Bug]: Sequential calls to `navigate` from `useNavigate` overwrite each-other's location

### ISSUE THREAD

**Issue by devonpmack** [remix-run/react-router#9638]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

Note that this bug doesn't happen on 6.0.0-beta.0 

See code sandbox https://codesandbox.io/s/react-router-v6-forked-gdyi9m?file=/src/App.js

```
navigate('/random_page')
navigate({search: '?q=abc'})
```

Obviously this example could be fixed with `navigate({path: '/random_page', search: '?q=abc'})`

But in situations where you have separate hooks managing each part of the query state sometimes this is not feasible without making the code harder to read. And this code used to work in previous versions of React Router.

### Expected Behavior

You would be navigated to `/random_page?q=abc`

### Actual Behavior

It only adds the query param `?q=abc` to wherever you currently are. The second call to navigate overrides the first one.

**Comment by ryanflorence** [comment]
This is expected behavior. `navigate` works on the current URL. If you call it multiple times in the same tick of the event loop, it's going to take the last value you gave it.
