### ISSUE TITLE
[Bug]: `useLocation()` and `useSearchParams()` cause rerender when navigate the url

### ISSUE THREAD

**Issue by xepozz** [remix-run/react-router#9640]
### What version of React Router are you using?

"react-router": "^6.3.0", "react-router-dom": "^6.4.3"

### Steps to Reproduce

Create a component that will provide a link.
Add `useLocation()` or `useSearchParams()` and log the results.

https://codesandbox.io/s/exciting-lena-hw8nkq

### Expected Behavior

React router do not rerender because all parts of URL are the same

### Actual Behavior

It changes `location.key` and causes rerender all components that use `useLocation()` or `useSearchParams()`

**Comment by timdorr** [comment]
When you navigate, even if it is the same URL, that still creates a new entry in the history stack. That is, you can click the back button in your browser. You may have things hidden in `location.state`, which necessitates a re-render. This is just how the History API works.
