### ISSUE TITLE
[Bug]: doubling mount side-effect

### ISSUE THREAD

**Issue by ilya-lopukhin** [remix-run/react-router#9652]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

Set-up a simple React app with one route, inside the element, set-up the mount effect, then load the route
![Screenshot 2022-11-29 at 16 07 54](https://user-images.githubusercontent.com/4680555/204550662-6fcff151-0dc9-454d-af29-fe7119eea691.png)

### Expected Behavior

Expected the mount effect to be ran once

### Actual Behavior

The effect just runs twice, so any async mount logic duplicates

**Comment by Mateusz-H** [comment]
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

In react >= 18 when you have strict mode enabled the useEffect run twice, this will not be the case in production build

**Comment by ilya-lopukhin** [comment]
> https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
> 
> In react >= 18 when you have strict mode enabled the useEffect run twice, this will not be the case in production build

thanks for pointing that out, that was so weird it looked like a bug, closing....
