### ISSUE TITLE
[Bug]:  Does createBrowserRouter  recalling many time?

### ISSUE THREAD

**Issue by Valar103769** [remix-run/react-router#9658]
### What version of React Router are you using?

latest

### Steps to Reproduce

because the 
```js
const routes = []
getUserInfo().then 
routes= newRoutes 
```
createBrowserRouter(routes)

### Expected Behavior

i dont know 

### Actual Behavior

xxx

**Comment by machour** [comment]
Please use the discussions tab if you want to ask questions
