### ISSUE TITLE
[Docs]: missing documentation on route children

### ISSUE THREAD

**Issue by Jernik** [remix-run/react-router#9661]
### What version of React Router are you using?

v6.4

### Steps to Reproduce

Go to https://reactrouter.com/en/main/route/route#children
See that there is a big TODO on a core concept
Shrug and guess you'll have to dig into the source code to figure out the answer to your question.

### Expected Behavior

Documentation to exist when I look for it

### Actual Behavior

There is just a TODO from 6 months ago from this PR:
https://github.com/remix-run/react-router/pull/8937

for a little more context, my questions are:
With nested routes, how do I have a "default" child for the `<Outlet />`, and what is the recommended way to get route parameters into child components? Should I just use the `useParams` hook?

**Comment by Jernik** [comment]
I have figured out the answers to my questions, but my complaints about the missing sections in the docs still stand

**Comment by jeremiedubuis** [comment]
I have spent a couple hours figuring out how nested routes work juste because no mention of the Outlet component is made in the [createBrowserRouter docs](https://reactrouter.com/en/main/routers/create-browser-router ). I would advocate for a simple mention in the section where nested routes are described.

**Comment by sgarcia-dev** [comment]
Agreed. Surprised such an essential aspect of routing is completely missing from the docs. Definitely less tempted to try Remix seeing how the docs for the main react-router library are maintained.

**Comment by Jernik** [comment]
There is still a todo on this section. This issue is not stale.

**Comment by camchardukian** [comment]
It would be nice for the docs to be more detailed and discuss best practices, but until then I've found the [React Router in Depth](https://www.youtube.com/playlist?list=PL4cUxeGkcC9iVKmtNuCeIswnQ97in2GGf) series to be helpful for less senior devs to at least pick up the basics.

**Comment by girishsontakke** [comment]
Hi, @brophdawg11 @ryanflorence if anyone is not working on this issue then can I try to write docs for the `children` prop of the `Route` element.

**Comment by Pyrolistical** [comment]
An FAQ would also be helpful. I looked there first. A good question would be:
> Q: Why does nested routes use `<Outlet/>` instead of `props.children`?

**Comment by danivideda** [comment]
Still no updates on the `children` docs? I'm new to learning react-router for my Electron project and found that this section is crucial. I had to realize that `children` props here is not just "to convenient the router naming" to be the same with the parents, but it's for layout purposes

**Comment by katokinawa** [comment]
Still no updates on the children docs...

**Comment by timdorr** [comment]
It's covered in the very first page of the documentation: https://reactrouter.com/6.28.0/start/overview#nested-routes

**Comment by timdorr** [comment]
`children` is an implicit prop for any React component. It's anything nested underneath the component. That is basic JSX and out of scope for what we have to explain. What we _are_ responsible for is explaining what nested Route components mean to the library. That is explained in that doc (and the Main Concepts one and the tutorial).
