### ISSUE TITLE
[Bug]: useSearchParams reverts to default value when removing the last value

### ISSUE THREAD

**Issue by eddiemonge** [remix-run/react-router#9668]
### What version of React Router are you using?

6.4.4

### Steps to Reproduce

[Link to example](https://react-ts-cq9stz.stackblitz.io/) ([edit mode](https://stackblitz.com/edit/react-ts-cq9stz?file=App.tsx))

1. Call useSearchParams with a default initialization like `const [searchParams, setSearchParams] = useSearchParams({ option: 'One' });`
1. Change the value of `searchParams.get('option')`. The value **_should_** change to the new value
2. Remove the param key. The value **_should be remove_**. In actuality, the default initialization is restored 

```
import * as React from 'react';
import { useSearchParams } from 'react-router-dom';

export default function App() {
  const [searchParams, setSearchParams] = useSearchParams({ option: 'One' });
  console.log('initial search params', searchParams.toString())

  const handleChange = ({ target: { value } }: React.ChangeEvent<HTMLInputElement>) => {
    if (value !== 'All') {
      console.log('Setting the option to', value)
      setSearchParams({ option: value});
    } else {
      console.log('Clearing the option')
      setSearchParams({});
    }
  };

  return (
    <div>
      <h1>Search Param Value</h1>
      <p>{searchParams.toString()}</p>
      <h1>Choose an option</h1>
      {['One', 'Two', 'All'].map((s) => (
        <div key={s}>
          <label>
            <input
              checked={searchParams.get('option') === s}
              name="choice"
              onChange={handleChange}
              type="radio"
              value={s}
            />
            <span>{s}</span>
          </label>
        </div>
      ))}
    </div>
  );
}
```

### Expected Behavior

The search params would be blank and `searchParam` would be an empty object-ish.

### Actual Behavior

`searchParam` reverts to `option: 'One'`

_edited to include a working example of the bug and instructions Jan 23, 2023_

**Comment by brophdawg11** [comment]
Could you provide a working reproduction of this in code sandbox, ideally without any component library dependencies?

**Comment by eddiemonge** [comment]
@brophdawg11 added

**Comment by eddiemonge** [comment]
thanks for the quick fix
