### ISSUE TITLE
[Feature]: Outlet could support fallback

### ISSUE THREAD

**Issue by jzombie** [remix-run/react-router#9674]
### What is the new or updated feature that you are suggesting?

https://reactrouter.com/en/main/components/outlet

In regards to the Outlet component, it would be nice if it could support an optional fallback in the case it were to return null.

### Why should this feature be included?

I have a use case where the Outlet returns null and would like content to be displayed there, only if it is null.  I might have to wrap Outlet for my particular use case, or discover something that I'm missing in the docs.

**Comment by timdorr** [comment]
This is better handled by having an explicit wildcard route. If you put it inside a layout route as a prop on a rendered component, that moves some of your routing logic away from the place where you'll end up having most of it. That seems error-prone to me and will likely lead to user confusion.

**Comment by jzombie** [comment]
In my use case, I'm rendering the app layout as the base route, and the sub routes in an outlet.  I previously couldn't see the home page content.

I already have a wildcard route acting as a catchall, but resorted to using this:

```
  <Outlet />
  <Routes>
    <Route path="/" element={<HomeView />} />
  </Routes>
```

Here's my router:

```js
const router = createBrowserRouter(
  [
    {
      path: "/",
      element: <AppLayout />,
      children: [
        {
          path: RoutePath.CreateNetwork,
          element: <NetworkCreatorView />,
        },
        {
          path: RoutePath.Networks,
          element: <NetworksView />,
        },
        {
          path: RoutePath.AVSettings,
          element: <AVSettingsView />,
        },
        {
          path: RoutePath.InNetwork,
          element: <CallView />,
        },
      ],
    },
    {
      // Catchall route
      path: "/*",
      element: <Virtual404View />,
    },
  ],
  {
    basename: process.env.PUBLIC_URL,
  }
);
```
