### ISSUE TITLE
[Bug]: Vite initial build reports sourcemap reference points to non-existing files

### ISSUE THREAD

**Issue by swernerx** [remix-run/react-router#9694]
### What version of React Router are you using?

6.4.4

### Steps to Reproduce

Set-up a Vite v3.2.5 project using React-Router 6.4.4. When using the dev-server: On the initial execution or via `--force` flag results into the following error reported on the console:

```
  VITE v3.2.5  ready in 419 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://169.254.82.90:3000/
  ➜  Network: http://169.254.44.47:3000/
  ➜  Network: http://192.168.13.192:3000/
  ➜  Network: http://192.0.2.42:3000/
Sourcemap for "/Users/sebastian/Workspace/enbw/agent-workbench/node_modules/.pnpm/react-router-dom@6.4.4_biqbaboplfbrettd7655fr4n2y/node_modules/react-router-dom/dist/index.js" points to missing source files
Sourcemap for "/Users/sebastian/Workspace/enbw/agent-workbench/node_modules/.pnpm/react-router@6.4.4_react@18.2.0/node_modules/react-router/dist/index.js" points to missing source files
```

The error is gone with the second execution, but re-appears when deleting/reinstalling `node_modules` or using the previously mentioned `--force` flag.

When checking out the installed npm module I can see the referenced `index.js.map`:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/145201/206024528-b2273ddb-b0ed-4bc3-9be1-021d055fc92a.png">

So the issue seems to be related to other files, referenced from the sourcemap, which are not part of the installed package:

The sourcemap starts with the following content:

```
{"version":3,"file":"index.js","sources":["../dom.ts","../index.tsx"],
```

Both TS-files listed here are not part of the package as it seems.

### Expected Behavior

Vite is happy optimizing `react-router-dom` without reporting any issues.

### Actual Behavior

Vite do not report the issue anymore.

**Comment by swernerx** [comment]
Might be related to this issue in Vite: https://github.com/vitejs/vite/issues/11238

**Comment by timdorr** [comment]
This isn't a React Router issue. [The file exists in the package](https://unpkg.com/browse/react-router-dom@6.4.4/dist/), so it should work. That seems like a Vite problem, or some tool it uses internally.
