### ISSUE TITLE
Layout is not displayed if child has pending loader

### ISSUE THREAD

**Issue by Drag13** [remix-run/react-router#9699]
### What version of React Router are you using?

18.2.0

### Steps to Reproduce

* Create react app
* Create browser router with the next code:

```jsx
const router = createBrowserRouter([
  {
    path: '/',
    element: <Layout />,
    children: [
      {
        index: true,
        element: <Home />,
        loader: () => new Promise((r) => setTimeout(() => r(true), 2500)),
      },
    ],
  },
]);
```
* Note that layout doesn't have any loader, but the first child does.
* Start the app

[Full code is here](https://stackblitz.com/edit/github-zuwpst?file=src%2FApp.tsx,src%2Fmain.tsx)

### Expected Behavior

* The Layout renders first with state `loading`. 
* After resolving the child's promise the rest of app should appear.

### Actual Behavior

The layout renders **after** resolving the child's promise. 
This leads to being impossible to draw some skeleton or spinner.

**Comment by brophdawg11** [comment]
You can use [`<RouterProvider fallbackElement>`](https://reactrouter.com/en/main/routers/router-provider#fallbackelement) to provide initial skeleton UI
