### ISSUE TITLE
[Bug]: useRevalidator doesn't clear route errors

### ISSUE THREAD

**Issue by charliematters** [remix-run/react-router#9713]
### What version of React Router are you using?

6.4

### Steps to Reproduce

Throw an error to show the error element. In the error element, resolve the problem and call revalidation.revalidate(). The loader reloads, throws no errors, and then renders the error element

https://stackblitz.com/edit/github-gkokwd?file=src%2FApp.tsx

### Expected Behavior

Once the error has been resolved by the error component, revalidating should cause the normal component to be rendered

### Actual Behavior

The revalidation is called, the loader is run and returns without error, but the error component is shown

**Comment by brophdawg11** [comment]
Yeah this feels like a bug.  The error boundary resets on location changes (since there was no `useRevalidator` in Remix) but it oughta reset on revalidation changes as well.

**Comment by brophdawg11** [comment]
Bump

**Comment by brophdawg11** [comment]
This is fixed by #10369 and will be available once React Router 6.11.0 is release

**Comment by charliematters** [comment]
That's great news - thanks
