### ISSUE TITLE
[Feature]: Type safe routes and search params

### ISSUE THREAD

**Issue by andriijas** [remix-run/react-router#9719]
### What is the new or updated feature that you are suggesting?

Suggesting fully type safe routes, so that you cant useNavigate or Link to={} a path that is not defined in the router.

while at it, would be super cool with an API to make query string params / search params typeble as well.

Thanks 🙌

### Why should this feature be included?

To aid teams using react router avoiding making routing mistakes.

**Comment by timdorr** [comment]
Data like this exists outside of the realm of Typescript. It both only happens at runtime and exists in parts of the DOM not controlled by Javascript (the URL bar, for instance). So, it is not possible to ensure type safety. 

We have used `unknown` types where relevant to encourage runtime checks, as this is the best guarantee and is semantically correct (we literally don't _know_ if something is a type).

**Comment by andriijas** [comment]
@timdorr True but values set as paths can dynamically be used as types when building. I think thats how tanstack router does it. 

https://tanstack.com/router/v1/docs/overview

**Comment by Kamahl19** [comment]
@timdorr what @andriijas means is shown in here https://www.youtube.com/watch?v=OwoZtv6u9p4&t=290s

**Comment by ronaldruzicka** [comment]
Is this feature forever thrown away? Because it would be really great to have type safe routes like `tanstack/router`. We are considering using Remix for our apps, but we are also considering `tanstack/router` because of the type safety. But if `react-router` also had type safety it would be easy decision.

**Comment by timdorr** [comment]
Tanstack router is a fundamentally different API. They create typed route objects, so you can do something like `useParams({ from: fooRoute.id })` and get a known type. We don't have that kind of direct connectivity, so Typescript can't be made aware that an arbitrary function call is contained within a particular context or not. This is just not how TS works or how our API design works. We simply cannot implement this without a different API structure.

**Comment by Kamahl19** [comment]
That's completely understandable. This issue is a feature request I believe. Might be worth exploring since the `tanstack/router` makes it its primary advantage over react-router.

**Comment by andriijas** [comment]
next.js gets statically typed links
https://twitter.com/shuding_/status/1620137501192253440

**Comment by ThatGuySam** [comment]
Finally figured out a solution that worked for me; however, it requires using a RouteObject and modifying each path, so it may not be helpful in every use case. 

<img width="623" alt="Screenshot 2023-06-27 at 12 16 28 PM" src="https://github.com/remix-run/react-router/assets/2830379/ff71e614-2b8f-4548-8aa4-b8ecfcba9e61">

Basically, I made each path a TypeScript Literal and recursed through children: 
```ts
export const routes = [
    {
        // We add `as const` to each path
        // so that they can be picked up as Literals
        path: '/blog' as const,
        errorElement: Component,
    },
    {
        // We add `as const` to each path
        // so that they can be picked up as Literals
        path: '/team' as const,
        errorElement: Component,
        children: [
            {
                index: true,
                element: Component,
            },
            {
                path: '/team/new' as const,
                element: Component,
            },
            {
                path: '/team/:teamId' as const,
                element: Component,
            },
        ],
    },
]

// ...

// '/blog' | '/team' | '/team/new' | '/team/:teamId'
export type RoutePath = NonNullable<LocalRoutePath<typeof routes[number]>>
```


You can try a working demo here: 
https://codesandbox.io/s/react-router-type-safe-routes-via-routeobject-h2pd3x?file=/index.ts

**Comment by vincerubinetti** [comment]
> We simply cannot implement this without a different API structure.

Going to call this now... I think in 1-2 year's time, people will think it was crazy that we ever had routers without type safety (and whatever other batteries-included features needed to make that happen like runtime-validation). And if the de-facto routers for React/Vue/etc don't adapt, people will flock to tanstack router.
