### ISSUE TITLE
[Bug]: TypeScript should be pinned to ~

### ISSUE THREAD

**Issue by j-m** [remix-run/react-router#9729]
### What version of React Router are you using?

^6

### Steps to Reproduce

TypeScript doesn't follow semver, e.g. 4.1 -> 4.2 is a breaking change. 
Patch is still effectively backwards compatible bug fixes so pinning  to ~ is fine. 

Create a project that depends on e.g. TypeScript ~4.1.
Install this project via ^ or latest.

### Expected Behavior

Installs a compatible version of `@remix-run/router`

### Actual Behavior

Get compilation errors for `@remix-run/router/dist/router.d.ts`

https://github.com/remix-run/react-router/blob/main/packages/router/router.ts#L52
`get` is not a valid property or signature for an interface.

Should it be `readonly`?

(Also, out of curiosity, how do dependencies work for this project? why are they all wiped when you look at package.json in the dist? why does @remix-run/router not inherit the root dependencies?)

**Comment by j-m** [comment]
> Should it be `readonly`?

Oh wait, this wouldn't even work. 

Worth outright removing? What difference does the `get` make?

**Comment by timdorr** [comment]
We don't really have a way to communicate a minimum required version. There is `typesVersions` that we can add to package.json, but that only allows us to point to declarations for older TS versions. 

Unfortunately, until that capability exists, the best we can tell you to do is to upgrade to a more recent version of TS.
