### ISSUE TITLE
[Bug]: preserve `location.state` reference on navigation

### ISSUE THREAD

**Issue by juliolmuller** [remix-run/react-router#9732]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

1. Navigate to a path setting a state to it (`navigate('/certain/path', { state: { /* some object */} })`);
1. In the page rendered by this path, access the state using **Location API** (`const { state } = useLocation()`);
1. Also sign this component to `useNavigate()` or another hook that uses **NavigateFunction** under the hood (for exemple, in my case, I'm using the setter function of `useSearchParams()`);
1. Still in this component, or any other consuming this `location.state`,  observe changes to its reference somehow (for example: `useEffect(() => /* some side effect */, [location.state])`);
1. Perform any navigation re-passing the same `state` object returned from `location` (`navigate('/any/where', { state })`);
1. Notice all observers will understand `location.state` as a brand new object reference and trigger unexpected side effects;

Some example closer to my use-case:
```ts
/**
 * Routes map:
 * path: "/"    element: <ComponentA />
 * path: "/foo" element: <ComponentB />
 */

function ComponentA() {
  const navigate = useNavigate()
  
  const handleClick = () => {
    navigate('/foo', { 
      state: {
        showProfile: true,
        showSettings: false,
        showTabs: true,
      }
    })
  }

  return (
    <button type="button" onClick={handleClick}>
      Go to Foo
    </button>
  )
}

function ComponentB() {
  const location = useLocation()
  const [searchParams, setSearchParams] = useSearchParams()
  const [settingId, setSettingId] = useState(searchParams.get('feat'))
  const [loading, setLoading] = useState(false)
  
  const handleClick = () => {
    setSearchParams({ feat: 'beta' }, { state: location.state })
  }

  useEffect(() => {
    const runAsyncProcess = async () => {
      setLoading(true)
      await someAsynchronousCall(location .state)
      setLoading(false)
    }
    runAsyncProcess()
  }, [location .state]) // <= observing changes on route state

  return (
    <button type="button" onClick={handleClick}>
      Access Beta Features
    </button>
  )
}
```

### Expected Behavior

As the object passed to **NavigateFunction** is the same extracted from **Location.state**, the reference to it should be preserved and any side effect observing it prevented.

```
Render BEFORE navigation                           | Render AFTER navigation
const navigate = useNavigate()                     | const navigate = useNavigate()
const { state } = useLocation()                    | const { state } = useLocation()
const stateRef = useRef(state)                     | const stateRef = useRef(state)
                                                   |
console.log(state === stateRef.current) // => true | console.log(state === stateRef.current) // => true 
                                                   |
navigate('.', { state })                           |
```

### Actual Behavior

Although the smae object is intentionally forwarded to the navigation, state reference changes, causing side effects.

```
Render BEFORE navigation                           | Render AFTER navigation
const navigate = useNavigate()                     | const navigate = useNavigate()
const { state } = useLocation()                    | const { state } = useLocation()
const stateRef = useRef(state)                     | const stateRef = useRef(state)
                                                   |
console.log(state === stateRef.current) // => true | console.log(state === stateRef.current) // => false
                                                   |
navigate('.', { state })                           |
```

**Comment by timdorr** [comment]
Under the hood, we are calling [`pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState). When state is stored via that API, it is serialized internally so that it can be preserved across even browser restarts. This means the state retrieved off the stack will never be the same instance, as it has been deserialized into memory. This is a platform limitation. 

You should likely depend on specific data in `location.state`, not the entire object.

**Comment by juliolmuller** [comment]
Great! Thank you for the quick reply and knowledge sharing.
