### ISSUE TITLE
[Bug]: useMatches returns empty route handle when <Route > is nested within <Routes>

### ISSUE THREAD

**Issue by DeepjyotiDeb** [remix-run/react-router#9743]
### What version of React Router are you using?

6.5

### Steps to Reproduce

I have a protected route component like so: 
```
<Route element={<UserRoute user={UserObj} />}>
     <Route path='mypage/*' element={<Dashboard />} />
 </Route>
```

 and subroutes :

```
<Routes>
          <Route
            path='movies'
            element={<Movies />}
            handle={{
              crumb: () =>  <span>test</span>,
            }}
          />
</Routes>          
```

### Expected Behavior

calling useMatches shows this:
```
data: undefined
handle:<span>test</span>
id: "1"
params: {*: 'movies'}
pathname: "/mypage/movies"
```

### Actual Behavior

when calling useMatches, the match element now returns :
```
data: undefined
handle: undefined
id: "1"
params: {*: 'movies'}
pathname: "/mypage/movies"
```

**Comment by timdorr** [comment]
`<Routes>` doesn't interact with the data routers (create*Router) that useMatches() pulls from, so it doesn't provide the `handle` data. This is documented in the note on the page: https://reactrouter.com/en/main/components/routes

**Comment by DeepjyotiDeb** [comment]
How would we render children routes then? createRoutesFromElement does not return React Children and we need to render the child components under a component.

**Comment by timdorr** [comment]
Look for the PageLayout component here: https://reactrouter.com/en/main/start/concepts#rendering Use a pathless route and the `<Outlet>` component.

**Comment by EugenDueck** [comment]
@timdorr Reading your last two comments, and also https://reactrouter.com/en/main/upgrading/v6-data :

Does using the new Data API mean limiting oneself to a single place in the code that defines all routes for the whole app?

I started using `handle` for breadcrumbs, but currently, my using `<Routes>` prevents me from getting handle data for routes that are not directly inside `createBrowserRouter(createRoutesFromElements(<Route>...</Route>))`. I would like to put sub-routes into different files, close to where they are used, rather than having a big monolith. Of course I cannot just get rid of `<Routes>` like this:

```diff
function AContainer() {
  return (
-    <Routes>
      <Route>
        <Route path="b" element={<B/>} handle={{ crumb: () => "b" }}/>
      </Route>
-    </Routes>
  )
}
```

Because
> A `<Route>` is only ever to be used as the child of `<Routes>` element, never rendered directly. Please wrap your `<Route>` in a `<Routes>`.

To put the problem into actual code:

**Routes in one place** - breadcrumbs fully work:
```javascript
const router = createBrowserRouter(createRoutesFromElements(
<Route path="/" element={<Root/>} handle={{ crumb: () => "root" }}>
  <Route path="a/*" handle={{ crumb: () => "a" }}>
    <Route path="b" element={<B/>} handle={{ crumb: () => "b" }}/>
  </Route>
</Route>
));
```

**Routes in two places** - `useMatches()` will not return a match for the "b" route:
```javascript
const router = createBrowserRouter(createRoutesFromElements(
<Route path="/" element={<Root/>} handle={{ crumb: () => "root" }}>
  <Route path="a/*" element={<AContainer/>} handle={{ crumb: () => "a" }}/>
</Route>
));

function AContainer() {
  return (
    <Routes>
      <Route>
        <Route path="b" element={<B/>} handle={{ crumb: () => "b" }}/>
      </Route>
    </Routes>
  )
}
```

**Comment by timdorr** [comment]
Routes is the prior API, not the new data API. You can't use it with data API hooks like `useMatches`.

**Comment by EugenDueck** [comment]
@timdorr My question is whether it is still possible to compose routes from multiple files, when using the new data API.

**Comment by EvanPartidas** [comment]
> @timdorr My question is whether it is still possible to compose routes from multiple files, perhaps some other way, when using the new data API.

This would be very useful for generating breadcrumbs for recursive paths. Is there any recommended way to do this yet?
