### ISSUE TITLE
[Bug]: Relative links are broken in react-router-dom

### ISSUE THREAD

**Issue by lifeiscontent** [remix-run/react-router#9748]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

https://stackblitz.com/edit/github-jybvx4?file=src%2FApp.tsx

1. click on "Test List Tasks"
2. click on "test task 1 Task"
3. look at the `href` of both "Lists" and "Tasks" links
4. they're using relative links, but the paths are incorrect.

Notes: if you change the path to `./..` or `./../..` they work as expected.

### Expected Behavior

I'd expect relative linking to work

### Actual Behavior

relative linking only works with `.` instead of `..` or `../..`

however, if you prefix `./..` it resolves correctly.

**Comment by lifeiscontent** [comment]
@machour this is not a support request, this is a bug react-router states it has support for relative links here: https://reactrouter.com/en/main/components/link#relative and they're not working as expected.

**Comment by lifeiscontent** [comment]
I've updated the "Steps to Reproduce" section to outline the specific issue.

**Comment by machour** [comment]
Well, you did post a bug report without a title nor a proper description. Flagging it as a support question was the obvious thing to do. 

Reopening.

**Comment by brophdawg11** [comment]
Relative routing in React Router goes up the `Route` hierarchy, but you're not using nested routes in this example so there is no hierarchy to traverse.

```jsx
<Route path="/" element={<Layout />}>
  <Route index element={<Navigate to="/lists" />} />
  <Route path="lists" element={<Lists />} />
  <Route path="lists/:listId/tasks" element={<Tasks />} />
  <Route path="lists/:listId/tasks/:taskId" element={<Task />} />
  <Route path="*" element={<NoMatch />} />
</Route>
```

Every `<Route>` is a child of the layout route, so any `<Link to="..">` (or `../..` etc.) will link back to the root.  If you want to keep this route hierarchy, you would need to use [`<Link relative="path">`](https://reactrouter.com/en/main/components/link#relative) to opt-out of `Route`-relative routing and into URL-segment relative routing.

Or if you move to nested routing then `to` will behave correctly:

```jsx
<Route path="/" element={<Layout />}>
  <Route index element={<Navigate to="/lists" />} />
  <Route path="lists" element={<Lists />}>
    <Route path=":listId" element={<List />} >
      <Route path="tasks" element={<Tasks />}>
       <Route path=":taskId" element={<Task />} />
     </Route>
   </Route>
  </Route>
  <Route path="*" element={<NoMatch />} />
</Route>
```

**Comment by lifeiscontent** [comment]
@brophdawg11 can you delve into the behavior I mentioned I was seeing? the `../../` vs `./../..` (which works) is this just happen stance and not something that would be considered expected behavior? the nested routing you suggested would require a completely different page design, so that's not an option for me.

If there's something I can do to help explain my problem better, happy to do so, just not sure what context is missing.

Either way, appreciate your efforts. Thanks.

**Comment by lifeiscontent** [comment]
@brophdawg11 would you consider this a valid use of react-router?

this would solve my problem, but I'm not sure if I'm abusing `Outlet` here or if this would be something reasonable to do.
```jsx
export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route index element={<Navigate to="/lists" />} />
        <Route path="lists" element={<Outlet />}>
          <Route index element={<Lists />} />
          <Route path=":listId/tasks" element={<Outlet />}>
            <Route index element={<Tasks />} />
            <Route path=":taskId" element={<Task />} />
          </Route>
        </Route>
        <Route path="*" element={<NoMatch />} />
      </Route>
    </Routes>
  );
}
```

**Comment by lifeiscontent** [comment]
also, fwiw it's not hard to do relative routing.

```js
const url = "https://github.com/remix-run/react-router/issues/9748";
const relativeUrl = new URL('../..', url);
console.assert(relativeUrl.toString()  === 'https://github.com/remix-run/');
```

**Comment by lifeiscontent** [comment]
@brophdawg11 @machour  can I get a response please?

**Comment by brophdawg11** [comment]
Yes - that's exactly how nested routes are intended to work.  You don't even need to specify `element={<Outlet/>}` since that's the default behavior ;)
