### ISSUE TITLE
Docs for the `opts.hydrationData` parameter

### ISSUE THREAD

**Issue by abubakarutar** [remix-run/react-router#9753]
### What is the new or updated feature that you are suggesting?

The `createBrowserRouter` function exported by `react-router-dom` takes 2 arguments:
- An array of `Route` objects, and
- an `opts` object, for further configuration.

The `opts` object has 3 parameters: `window`, `basename` and `hydrationData`.

There are currently no docs for the `hydrationData` parameter, and it is not immediately obvious what it is used for.

I suggest the docs be updated to include documentation on the `hydrationData`.

**Comment by timdorr** [comment]
This is still being built out more fully. For now, it's for use with `createStaticRouter`, which has yet to be marked stable and documented: https://github.com/remix-run/react-router/blob/590b7a25a454d998c83f4e5d6f00ad5a6217533b/packages/react-router-dom/server.tsx#LL225C29-L225C29
