### ISSUE TITLE
[Bug]: generatePath not working as expected when param is without leading /

### ISSUE THREAD

**Issue by giovannipiller** [remix-run/react-router#9755]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

`generatePath('something:id', { id: 'ABC' })` -> https://stackblitz.com/edit/github-7x2nae?file=src/App.tsx (6.5.0)

### Expected Behavior

should return `"somethingABC"` -> https://stackblitz.com/edit/github-18hamj?file=src%2FApp.tsx (6.4.5)

### Actual Behavior

returns `"something:id"`

https://stackblitz.com/edit/github-7x2nae?file=src/App.tsx (6.5.0)

**Comment by brophdawg11** [comment]
Hey @giovannipiller!  This was actually bug fix that just went out in [6.5.0](https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0). Partial parameter replacement (`something:id`) was a bug and wasn't ever intended to work - parameters are required to be full URL segments (i.e., `something/:id`). 

It's recommended to extract the static portion and append it separately:

```js
'something' + generatePath(':id', { id: 'ABC' }) // somethingABC
```

Or this also works if the parameter is it's own segment:

```js
generatePath('something/:id', { id: 'ABC' })} // something/ABC
```
