### ISSUE TITLE
[Bug]: children should be called after parents has been finished their loaders/renders?

### ISSUE THREAD

**Issue by vendramini** [remix-run/react-router#9756]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

A simple app containing 2 routes, both with loaders.

Simple test case, check out the console log order: https://stackblitz.com/edit/react-ts-rqewvy?devToolsHeight=33&file=index.tsx

Am I missing something? I didn't find any cases on documentation regarding to this (when we depends on parent's loaders).

I though that the behavior would be to render nested routes in order of successful pre-rendered routes.

### Expected Behavior

I was expecting that the child's loaders should be called/rendered after the parent's loader has been finished.

### Actual Behavior

Every nested route is called, no matter if their parent's are done or aren't.

**Comment by machour** [comment]
React Router will call your loaders in parallel, to make your app as speedy as possible.
The idea is that you shouldn't depend on your parent loader, in order to avoid creating request waterfalls.

This behavior should be documented.

Don't hesitate to open a new Q&A in the discussion tab to have support.

**Comment by brophdawg11** [comment]
The `Route` `loader` page does document that these are called in parallel: https://reactrouter.com/en/main/route/loader#loader.  

Keep an eye on [this proposal](https://github.com/remix-run/react-router/discussions/9564) for the ability to do things in a sequential top-down order.

**Comment by machour** [comment]
@brophdawg11 maybe an `Important` section would make it harder to miss + some explanation about why it's implemented like that

**Comment by brophdawg11** [comment]
yeah, I imagine we'll be making the distinction much clearer once we introduce `beforeLoader`

**Comment by vendramini** [comment]
Hey guys, I really appreciate your time explaining this. Indeed, being a so important architecture design I agree that adding it to the `Important` section would be interesting.

Although, how could we create dependent loaders to get a waterfall? How are the recommendations now? In some cases it is desirable.

**Comment by brophdawg11** [comment]
You can't create a waterfall with loaders, by design.  That's what the above proposal is addressing.

**Comment by brophdawg11** [comment]
We agree - that's why middleware is on the [roadmap](https://github.com/orgs/remix-run/projects/5) 😄
