### ISSUE TITLE
[Feature]: accept an "updater" function for useNavigate()

### ISSUE THREAD

**Issue by joshribakoff-sm** [remix-run/react-router#9758]
### What is the new or updated feature that you are suggesting?

You accept an updater function for `useSearchParams`'s `setSearchParams`, for updating params based on old params, although it's not "safe" per https://github.com/remix-run/react-router/issues/9757

The "ask" is to also surface an updater function for `useNavigate`

### Why should this feature be included?

So that the consumer can change the pathname / search params string safely, without referencing stale previous values.

**Comment by timdorr** [comment]
This wouldn't make sense, as you're not updating the existing location. Even if `replace: true` is set, that's still generating a new `location.key` every time. If you need to reference the current location, you would use `useLocation`, which is stable during the render (I'll bring this up in your other issue in a sec).

**Comment by joshribakoff-sm** [comment]
> This wouldn't make sense, as you're not updating the existing location.

I am, though 😆 if you want to know more about my use case just ask :)

>  you would use useLocation, which is stable during the render

Stability during render is not the problem. The problem is that you assume there will be a render in between each call to the function.

 Either the updater function provides the same guarantee as the React state updater, or it does not. If it does not offer the guarantees, why does it even exist? If it does offer the guarantees, wouldn't it be reasonable to want those guarantees regardless of whether you're updating search params, the path, or both of these?
