### ISSUE TITLE
[Bug]: Path that matched in 6.4.3 doesn't match in 6.5.0

### ISSUE THREAD

**Issue by bhollis** [remix-run/react-router#9762]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

I have a route with a path spec that looks like this:

```tsx
<Route path=":membershipId/d:destinyVersion/*" element={<Destiny />} />
```

Note that the second segment is `d` then `:destinyVersion`.

### Expected Behavior

I expect the path `/4611686018433092312/d2` to match this route, binding `:membershipId` to `4611686018433092312` and `:destinyVersion` to `2`, as react-router versions before 6.5.0 did.

### Actual Behavior

The path does not match, and path matching falls through to subsequent `Route`s.

If I rewrite the path matcher to be `:membershipId/:destinyVersion/*` it works, but then `:destinyVersion` is bound to `d2` and I have to fish out the number myself.

**Comment by machour** [comment]
Hey @bhollis, that behavior was actually a bug, check Matt's reply here: https://github.com/remix-run/react-router/issues/9755#issuecomment-1357793108

**Comment by bhollis** [comment]
Hi there - I understand your perspective, but I'd request that any major changes in behavior be accompanied by a major version release in the future. Whether this was documented or not, it worked before, and now it doesn't, and the documentation had not suggested that this was not supported.
