### ISSUE TITLE
[Bug]: generatePath does not work with url parameters

### ISSUE THREAD

**Issue by mdbodley** [remix-run/react-router#9763]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

I spent HOURS trouble shooting this, just to trace it back to this update.

```
//will not populate any of the url query parameters with data since the update
generatePath("/customer/details/:id?selected=:selected", {id: 1, selected: "infoTab"});   
```

downgraded to previous version and got it working again.  but HOURS of time lost tracking this down.

### Expected Behavior

```

const url = generatePath("/customer/details/:id?selected=:selected", {id: 1, selected: "infoTab"});   

//expected behavior: outputs "/customer/details/1?selected=infoTab"
```

### Actual Behavior

```

const url = generatePath("/customer/details/:id?selected=:selected", {id: 1, selected: "infoTab"});   

//outputs "/customer/details/1?selected=:selected
```

**Comment by brophdawg11** [comment]
This isn't a valid use case for [`generatePath`](https://reactrouter.com/en/main/utils/generate-path) - which is only for generating the "path" portion of a URL, not the `search`(or `URLSearchParams`) portion.

You can leverage `URLSearchParams` directly to generate your search params string:

```
new URLSearchParams({ selected: 'infoTab' }).toString()
// selectedId=infoTab
```
