### ISSUE TITLE
[Bug]: `errorElement` anywhere besides top-level not rendering

### ISSUE THREAD

**Issue by jtheberge** [remix-run/react-router#9765]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

Reproducible env: https://stackblitz.com/edit/github-9bi7en?file=src/App.tsx

### Expected Behavior

Expected `errorElement` to be rendered at the nearest parent as stated at https://reactrouter.com/en/main/route/error-element#bubbling.

### Actual Behavior

Using `errorElement` anywhere besides top-level not rendering. It only gets rendered to top level parent.

**Comment by brophdawg11** [comment]
This is correct behavior since in your example with the 404 - there were _no matching routes_, so there's no matched nested route to bubble up from.  If errors happen _at a given route_, they'll bubble up from there.  So for example, if you encountered a loader error at your nested route:

```jsx
          {
            path: '/',
            element: <Home />,
            errorElement: <ErrorPage />,
            async loader() {
              // This will cause render <ErrorPage /> to render
              throw new Error('Broken!');
            },
          },
```

Hope this helps!

**Comment by jtheberge** [comment]
> This is correct behavior since in your example with the 404 - there were _no matching routes_, so there's no matched nested route to bubble up from. If errors happen _at a given route_, they'll bubble up from there. So for example, if you encountered a loader error at your nested route:
> 
> ```js
>           {
>             path: '/',
>             element: <Home />,
>             errorElement: <ErrorPage />,
>             async loader() {
>               // This will cause render <ErrorPage /> to render
>               throw new Error('Broken!');
>             },
>           },
> ```
> 
> Hope this helps!

Thanks for the quick reply! Just to clarify then, it sounds like if part of a path is matched, such as `/`, it doesn't start the bubble up from there, but only bubbles up if an exact match of a path is found.

For example, if navigating to `/nested-url/test` with:
```
const router = createBrowserRouter([
  {
    errorElement: <ErrorPage />, // errorElement 1
    element: <AppWrapper />,
    children: [
      {
        errorElement: <ErrorPage />, // errorElement 2
        children: [
          {
            path: '/',
            element: <Home />,
            errorElement: <ErrorPage />, // errorElement 3
            children: [
              {
                path: 'nested-url',
                errorElement: <ErrorPage />, // // errorElement 4
              },
            ],
          },
        ],
      },
    ],
  },
]);
```

It will still render errorElement 1, not 4. Is that correct?

**Comment by brophdawg11** [comment]
Yes.  If you want 404s to be handled for sub-routes like that you could use a splat (`*`) route as a child of nested-url that threw a 404 Response from its loader

**Comment by weberankit** [comment]
const router = createBrowserRouter([
  {
    errorElement: <ErrorPage />, // errorElement 1
    element: <AppWrapper />,
    children: [
      {
        errorElement: <ErrorPage />, // errorElement 2
        children: [
          {
            path: '/',
            element: <Home />,
            errorElement: <ErrorPage />, // errorElement 3
            children: [
              {
                path: 'nested-url',
                element: <NestedURLComponent />,
                errorElement: <ErrorPage />, // Generic error handling for /nested-url
                async loader() {
                  // This will throw a specific error for /nested-url
                  throw new Error('Custom error for /nested-url');
                },
              },
            ],
          },
        ],
      },
    ],
  },
]);
means we have to do this way
