### ISSUE TITLE
[Feature]: useOnChange hook 

### ISSUE THREAD

**Issue by luist1228** [remix-run/react-router#9766]
### What is the new or updated feature that you are suggesting?

A hook that allows you to prevent the navigation by passing a function that returns either an object or a boolean so that you can do a check or an operation before navigation

### Why should this feature be included?

The useLocation and useEffect isn't enough for some use cases like hitting a home button in nav and if some changes need to be saved give the user a prompt or a modal, or doing an action in some routes before changing route

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/8139#issuecomment-1262630360
