### ISSUE TITLE
Cannot integrate `<ScrollToTop />` with `<RouterProvider>`

### ISSUE THREAD

**Issue by xsjcTony** [remix-run/react-router#9767]
### What version of React Router are you using?

v6.5.0

### Steps to Reproduce

With normal `<BrowserRouter>`, you can define a custom `<ScrollToTop />` component just like in v5 docs:
```tsx
import { useEffect } from "react";
import { useLocation } from "react-router-dom";

export default function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);

  return null;
}
```
and consume it inside `<BrowserRouter>`, being the sibling of `<Routes>`
```tsx
function App() {
  return (
    <BrowserRouter>
      <ScrollToTop />
      <Routes>
        {/* ... */}
      </Routes>
    </BrowserRouter>
  );
}
```

--- 
But I cannot do such things with `createBrowserRouter` and `<RouterProvider router={router} />` like this:
```tsx
function App() {
  return (
    <>
      <ScrollToTop /> {/* this WON'T work since `useLocation()` is not in the router's context */}
      <RouterProvider router={router} />
    </>
  );
}
```
How should I integrate them then? My App does not have any root page, so every route is for a whole new page, (no child routes are used at all).

I don't think including `<ScrollToTop />` in every page's component is a good way to do that, there should be some way to globally apply it just like with `<BrowserRouter>` and `<Routes>`

I DO WANT to use object instead of `JSX` syntax

---
Sorry for raising the usage issue here, but I cannot find anything specifically related to this after searching through it.

### Expected Behavior

N/A

### Actual Behavior

N/A

**Comment by brophdawg11** [comment]
Use a root pathless layout route and put the ScrollToTop inside there.

```
<Route path="" element={<Layout />}>
  /* all your routes here */
</Route>

function Layout() {
  return (
    <>
      <Outlet />
      <ScrollToTop />
    </>
  );
}
```

That's said, 6.4+ comes with built-in scroll management using the `ScrollRestoration  ` component - I would recommend using  that instead of a custom component.

https://reactrouter.com/en/main/components/scroll-restoration
