### ISSUE TITLE
[Bug]: Difference between printing with CTRL + P and window.print()

### ISSUE THREAD

**Issue by haiquang9994** [remix-run/react-router#9769]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

Create new project with `npx create-react-app`

Change index.js

```js
import React from 'react'
import { createRoot } from 'react-dom/client'
import {
  createBrowserRouter,
  RouterProvider,
  Route,
  Link,
} from 'react-router-dom'

function About() {
  return (
    <div>
      <>About</>
      <button onClick={() => window.print()}>Print</button>
    </div>
  )
}

const router = createBrowserRouter([
  {
    path: '/',
    element: (
      <div>
        <h1>Hello World</h1>
        <Link to="about">About Us</Link>
      </div>
    ),
  },
  {
    path: 'about',
    element: <About />,
  },
])

createRoot(document.getElementById('root')).render(
  <RouterProvider router={router} />,
)
```

### Case CTRL + P
- Click "About Us" to open About Page
- Press CTRL + P (Win) / CMD + P (MacOS)
- In print form, use mouse click back button of browser
- location.href equal / and render `Home page`.

-----

### Case Print button rendered
- Click "About Us" to open About Page
- Use mouse click Print button rendered
- In print form, use mouse click back button of browser
- location.href equal / and render `Home page`.

### Case CTRL + P
- Click "About Us" to open About Page
- Press CTRL + P (Win) / CMD + P (MacOS)
- In print form, use mouse click back button of browser
- location.href equal / and render `Home page`.
![ctrl_p](https://user-images.githubusercontent.com/13959257/208924065-69a87e87-3488-46a2-b7d9-2d5a4febae09.gif)

-----

### Case Print button rendered
- Click "About Us" to open About Page
- Use mouse click Print button rendered
- In print form, use mouse click back button of browser
- location.href equal / and render `About page`.
![click_print](https://user-images.githubusercontent.com/13959257/208924099-5c62e525-5ada-4bf2-9765-6b66e3ad836a.gif)

**Comment by haiquang9994** [comment]
I got this error when using Chromium-based browsers

**Comment by timdorr** [comment]
This has nothing to do with React Router.
