### ISSUE TITLE
[Bug]: Specifying formaction attribute on submit button does redirect to root

### ISSUE THREAD

**Issue by freddi301** [remix-run/react-router#9775]
### What version of React Router are you using?

6.6.0

### Steps to Reproduce

```typescript
function MyForm() {
  return (
    <Form method="post">
      <button type="submit" formAction="delete">
        delete
      </button>
    </Form>
  );
}

<RouterProvider
  router={createHashRouter(
    createRoutesFromElements(
      <Route path="my-resource/:resourceId" element={<MyForm />} />
    )
  )}
/>;
```

Clicking on delete button

### Expected Behavior

Get redirected to "/my-resource/:resourceId/delete"

### Actual Behavior

I get redirected to "/delete"

**Comment by freddi301** [comment]
I solved with https://reactrouter.com/en/main/hooks/use-form-action

It is intended?

**Comment by timdorr** [comment]
Yes, that is intended so we know to handle the action correctly internally to the Form component.
