### ISSUE TITLE
[Bug]: Router path with " - "

### ISSUE THREAD

**Issue by Brenerss** [remix-run/react-router#9790]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

```<Route path="/iv-:hash_room" element={<Home />} />```

### Expected Behavior

/iv-wYVsb1KDtT9YJJFUiSTq0dqUyvc5vK51nx7QW29CPJc - This route is matched

### Actual Behavior

/iv-wYVsb1KDtT9YJJFUiSTq0dqUyvc5vK51nx7QW29CPJc 

This route is NOT matched and redirect to Not found page

**Comment by timdorr** [comment]
This bug was already fixed in 6.4.3. Update your version and it will work.
