### ISSUE TITLE
[Bug]: Type exception after using defer, The inferred type of "loader" xxx

### ISSUE THREAD

**Issue by beilo** [remix-run/react-router#9794]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce
```

import React from 'react';
import { Outlet, useLoaderData, defer } from 'react-router-dom';

const MyLayout: React.FC = () => {
  const loaderData = useLoaderData();
  console.log('loaderData', loaderData);

  return (
    <div>
          <Outlet />
    </div>
  );
};
export default MyLayout;

export const loader = () => {
  const res = new Promise((resolve) => {
    setTimeout(() => {
      resolve('数据获取成功');
    }, 200);
  });
  return defer({
    res,
  });
};
```

### Expected Behavior

All is well

### Actual Behavior

The inferred type of "loader" cannot be named if ".pnpm/registry.npmmirror.com+@remix-run+router@1.2.1/node_modules/@remix-run/router/dist/utils" is not referenced. This is probably not portable. Type comments are required.

**Comment by timdorr** [comment]
I can't reproduce this in the [TS Playground](https://www.typescriptlang.org/play?ts=4.9.4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKFEljgG84B5AVxgBskYAaOFgZyQAZCCgAmSKABEUMFLwmZJcAL5xsuAkXQwAtDjaTdY3GSpU0EAHb94AWQCeQlA4hsAXImIwAdADEAYTgAXjgACgBKEIA+Bio4OEsbeHZRCWlZFBC+QRFxSRk5SIpKBKT+CE4fVIBzMPxU-Iy5fF5G9MKUCJL4uCIYFigrcN6EgB4xYAA3aNGE+fHWDi44AHpZ0vmx1cmZ3u6qFRKkAA9aeEUUFnZ7Jxc3GB7KU-PE61s4duVQyJi4zfK8CI-GyViQAHc4AAFHAgYCCMJhYGVKZIKLBWL0OaCGAAFVASAeiPRmLmCWR7FR9UADqaAO2NAO3BgDXlQAIRoB8pXwB02CRUvAATAAGfmc7nCvpcQbDRSSMJYrli-jcXoqTlHIA). It appears to be something with your build environment.

**Comment by beilo** [comment]
Is it caused by pnpm?
I'm going to click in from types file.

`react-router-dom(index.d.ts) -> @remix-run(utils.d.ts)`

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/19225489/210170736-e01b3350-039b-4418-a14a-41c18c6e169d.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/19225489/210170740-cb1e622d-c31c-47c4-b9ac-dea22edc928d.png">

**Comment by beilo** [comment]
I found out why.

I set it in tsconfig.json


`"declaration": true,`

Let me just delete that.

Why does this configuration cause errors?

What should a proper tsconfig.json configuration look like?
