### ISSUE TITLE
[Bug]: encoded uri component breaks path resolution in nested route

### ISSUE THREAD

**Issue by blasterpistol** [remix-run/react-router#9795]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

1. Open https://codesandbox.io/s/silent-wind-ey16ul?file=/src/App.tsx
2. Click on the "Works - Nested" link to verify that the simple case works without encoded param (you will see "Param Content: 123")
3. Click on the "Works - Not nested" link to verify that the simple case works with encoded param (you will see "Param Content: [Encoded]").
4. Click on the "Not Works - Nested" link and check the console (you will see no param content and a warning in the console)

### Expected Behavior

The path must be successfully resolved with an encoded param (in my case it is an encoded encrypted token (jwt-like) from the server that allows the user to change the email)

### Actual Behavior

Broken path resolution and a warning in the console

**Comment by timdorr** [comment]
This is because of the linebreaks in your token. Those are not valid characters for a URL, even when encoded. Remove them and it will work.
