### ISSUE TITLE
[Bug]: Navigate(-1) not working in safari 16.*

### ISSUE THREAD

**Issue by mseyfayi** [remix-run/react-router#9798]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

1. Use `BrowserRouter` as your router.
2. Create a button and set its `onClick` to `() => navigate(-1)`.
3. Build the project in production mode.
4. Open app with the Safari iOS 16.
5. Click on button

### Expected Behavior

URL should change and the page's content should change.

### Actual Behavior

URL will change but the content will not update, and by a reload the state will fix.

The source of the bug is that safari 16 will not support the `popstate` event properly, it only triggers on page load when we are using react (SPA), so it's useless.   
This problem will cause [`handlePop`](https://github.com/remix-run/react-router/blob/main/packages/router/history.ts#L597) not to trigger and the state of `BrowserRouter` will not update.

**Comment by mseyfayi** [comment]
**Update:** 
I noticed that I have some `<script async ... />` (like google analytics) in my HTML file and until these scripts are not downloaded popstate will not work.
In my case, I moved injected these scripts in an `useEffect`, so they will inject into DOM after the whole DOM is rendered and problem fixed

**Comment by brophdawg11** [comment]
Sounds like this was an unrelated issue?  Is it ok to close this out?
