### ISSUE TITLE
[Bug]: Uncaught ReferenceError: Cannot access 'RouterBoundary' before initialization

### ISSUE THREAD

**Issue by modex98** [remix-run/react-router#9799]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

```ts
import { useRouteError } from "react-router-dom";

function RouterBoundary() {
    let error = useRouteError();
    console.error(error);

    return (
        <>
            <div>Dang!</div>
            <p>{JSON.stringify(error)}</p>
        </>
    );
}

export const routes = [
    {
        path: "/auth",
        name: "Auth",
        element: (
            <Public auth={auth}>
                <Outer>
                    <Auth />
                </Outer>
            </Public>
        ),
    },

    {
        path: "/",
        element: <Private auth={auth} />,
        errorElement: <RouterBoundary />,
        children: [
            {
                index: true,
                element: <Dashboard />,
                name: "Dashboard",
            },

            {
                path: "profile",
                element: <Profile />,
                name: "Profile",
            },

            {
                path: "settings",
                element: <h1>Settings</h1>,
                name: "Settings",
            },

            {
                path: "orders",
                children: [
                    {
                        index: true,
                        element: <h1>Orders</h1>,
                        name: "Orders",
                    },
                    {
                        path: ":id",
                        element: <h1>Orders id</h1>,
                        name: "Order",
                    },
                    {
                        path: "add",
                        element: <h1>Orders id</h1>,
                        name: "AddOrder",
                    },
                ],
            },

            {
                path: "listings",
                children: [
                    {
                        index: true,
                        element: <ListingsIndex />,
                        name: "Listings",
                    },
                    {
                        path: ":id",
                        children: [
                            {
                                index: true,
                                element: <ListingForm />,
                                name: "Listing",
                            },
                            {
                                path: "edit",
                                element: <ListingForm />,
                                name: "EditListing",
                            },
                            {
                                path: "delete",
                                name: "DeleteListing",
                            },
                        ],
                    },
                    {
                        path: "add",
                        element: <h1>Listing id</h1>,
                        name: "AddListing",
                    },
                ],
            },

            {
                path: "help",
                element: <h1>help</h1>,
                name: "Help",
            },

            {
                path: "logout",
                name: "Logout",
            },
        ],
    },
];
```

### Expected Behavior

expected to work , it worked in the beginning but now this error stops everything

### Actual Behavior

after few weeks i doesn't work anymore i get this error in the console 
`index.tsx:29 Uncaught ReferenceError: Cannot access 'RouterBoundary' before initialization`

**Comment by timdorr** [comment]
This isn't a React Router bug. Something about your build setup is hoisting your `routes` array above the `RouterBoundary` definition (_side note: I thought functions were auto-hoisted 🤔_). I would try moving it to a separate module and importing it.

**Comment by saver711** [comment]
@timdorr 
I am facing similar problem

I am using Vite (React + Typescript)

### **STRUCTURE**
![image](https://user-images.githubusercontent.com/28202010/217410285-35190961-c30d-4ef3-a563-0a47a9ace2a9.png)

### **main.tsx & App.tsx**
![image](https://user-images.githubusercontent.com/28202010/217410384-a1f19d0f-75af-46d5-8d94-9bc410be3a3d.png)

### **src/routing/allRoutes.tsx**
![image](https://user-images.githubusercontent.com/28202010/217410698-3918c2b3-b5f8-434c-b768-17feeaab215e.png)

### **src/routing/Root.tsx**
![image](https://user-images.githubusercontent.com/28202010/217410945-bdc08741-a293-4add-a609-2401d154ad6e.png)

### **WHAT IS THE ERROR?**
### I have 2 pages
**1) SuperHeroes.tsx**
- i fetch data from json-server with **axios** only
- the error doesn't happen (I will tell you what the error is in a sec.)

**2) RQSuperHeroes.tsx**
- i fetch data with **axios** and **react-query**
- the error happens, Which is: 
When i am in this page at => http://localhost:5173/rq-superheroes
and i make any edit in vs code in RQSuperHeroes.tsx and save it
i see this error in the console
![image](https://user-images.githubusercontent.com/28202010/217411828-70b92f02-348d-43b3-b767-c9e848b17eaa.png)

------------------------------------------------- If you need to take a look in RQSuperHeroes.tsx
`/////////// IMPORTS
///
import { Helmet } from "react-helmet-async"
import { useQuery } from "react-query"
import { apiClient } from "../App"
///
/////////// Types
///
type RQSuperHeroesProps_TP = {
  title: string
}
///
export const RQSuperHeroes = ({ title }: RQSuperHeroesProps_TP) => {
  ///
  /////////// CUSTOM HOOKS
  ///
  type Hero_TP = {
    name: string
    id: number
  }

  const { isLoading, isSuccess, isError, data, error, refetch, isFetching } =
    useQuery<Hero_TP[], Error>("super-heroes", fetchSuperheroes, {
      cacheTime: 10000,
      staleTime: 6500,
      refetchOnMount: false,
      refetchOnWindowFocus: false,

      onSuccess: (data)=> console.log('Success', data),
      onError: (err)=> console.log('Failed', err),
    })
  ///
  
  ///
  /////////// EVENTS || IF CASES || FUNCTIONS
  ///
  async function fetchSuperheroes(): Promise<Hero_TP[]> {
    const res = await apiClient.get<Hero_TP[]>("/superheroes")
    return res.data
  }
  ///
  return (
    <>
      <Helmet>
        <title>{title}</title>
      </Helmet>
      {isLoading ? (
        <h1>LOADING...</h1>
      ) : (
        data?.map((hero) => <h4 key={hero.id}>{hero.name}</h4>)
      )}

      {isError && <h3>{error.message}</h3>}
    </>
  )
}
`

**Comment by seemX17** [comment]
I'm getting a similar error when I switched to Vite, were you able to resolve this issue? @saver711 @mod7ex

**Comment by laripereira14** [comment]
I'm having the same issue. Any success on solving this? @saver711 @mod7ex @seemX17

**Comment by kennydifiore** [comment]
I'm having a similar issue as well.  My functional component was already defined in a separate module and whenever I attempt to use it in the Routes definition, I get this error.

**Comment by mabitten** [comment]
Has anyone resolved this?

**Comment by k3vnb** [comment]
I was able to fix a similar error by using a default export:
```
const router =  createBrowserRouter([ ... ]);

export default router;
```
