### ISSUE TITLE
[Bug]: createHashHistory broken with a basename

### ISSUE THREAD

**Issue by allpro** [remix-run/react-router#9800]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

1. Create an app using Create React App.
2. Install latest react-router-dom.
3. Install gh-pages.
4. Add 2-page application and define a sitemap.
5. Render the app using a HashRouter, with a `basename` option.
6. Build & deploy the app to Github Pages: `npm run deploy`.
7. Run the app.

**package.json**
```js
{
  "name": "pokemon-sample",
  "homepage": "https://allpro.github.io/pokemon-sample",
  ...
```

**sitemap.js**
```js
import AppLayout from 'components/AppLayout';
import Details from 'components/Details';

const sitemap = [
  {
    path: '/*',
    element: <AppLayout />,

    children: [
      {
        path: ':name',
        element: <Details />,
      },
    ],
  },
];

export default sitemap;
```

I use dynamic code to get the `basename` so can run the app locally _without_ a basename, but this is not relevant to the issue so simplifying the code here...

**index.js**
```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import { createHashRouter, RouterProvider } from 'react-router-dom'

import sitemap from './sitemap';

const basename = 'https://allpro.github.io/pokemon-sample';

const router = createHashRouter(sitemap, { basename  });

const root = ReactDOM.createRoot(document.getElementById('root'));

root.render(
  <RouterProvider router={router} />
);
```

### Expected Behavior

The app should load and the routing work as expected on the deployed URL. 

- If I run the app locally, with no `basename`, the app loads properly.
- **If I switch to using `createBrowserRouter`, the app loads properly**. Navigation also works correctly.

Note: Although BrowserRouter works perfectly, I want to use HashRouter so that child-routes can be _refreshed_ without getting a 404 from Github Pages.

### Actual Behavior

The deployed app renders a blank screen, with no visible error. **The app does load correctly**, (confirmed by breakpoints), but no route is rendered.

I traced the problem and found that RR is rendering `null` because it thinks no route is matched. The cause seems to be a bug in the `createHashHistory()` method. This parses `pathname`, `search` and `hash` from `window.location.hash`, _instead of_ `window.location`, resulting in _no_ URL data being found. Because no `pathname` was found, it cannot 'start with' the basename. This causes RR to believe no routes match and so it renders `null`. An internal error is set, but this does not display anywhere.

Here is the relevant code, as compiled, with comments added for the relevant parts...

**node_modules/react-router-dom/dist/index.js**
```js
function createHashRouter(routes, opts) {
  return createRouter({
    basename: opts == null ? void 0 : opts.basename,
    history: createHashHistory({ // <----------------------------- Call to createHashHistory()
      window: opts == null ? void 0 : opts.window
    }),
    hydrationData: (opts == null ? void 0 : opts.hydrationData) || parseHydrationData(),
    routes: UNSAFE_enhanceManualRouteObjects(routes)
  }).initialize();
}
```

**/node_modules/@remix-run/router/history.ts**
```js
export function createHashHistory(
  options: HashHistoryOptions = {}
): HashHistory {
  function createHashLocation(
    window: Window,
    globalHistory: Window["history"]
  ) {
    let {
      pathname = "/",
      search = "",
      hash = "",
    } = parsePath(window.location.hash.substr(1)); // <--------- should be: parsePath(window.location) ???
    return createLocation(
      "",
      { pathname, search, hash },
      // state defaults to `null` because `window.history.state` does
      (globalHistory.state && globalHistory.state.usr) || null,
      (globalHistory.state && globalHistory.state.key) || "default"
    );
  }
  ...
  return getUrlBasedHistory(
    createHashLocation,
    createHashHref,
    validateHashLocation,
    options
  );
}

/**
 * Parses a string URL path into its separate pathname, search, and hash components.
 */
export function parsePath(path: string): Partial<Path> { // <------- `path` is ONLY `location.hash.substr(1)`
  let parsedPath: Partial<Path> = {};

  if (path) {
    let hashIndex = path.indexOf("#"); // <-------- returns -1 because '#' was stripped from `path` passed in
    if (hashIndex >= 0) {
      parsedPath.hash = path.substr(hashIndex);
      path = path.substr(0, hashIndex);
    }

    let searchIndex = path.indexOf("?");
    if (searchIndex >= 0) {
      parsedPath.search = path.substr(searchIndex);
      path = path.substr(0, searchIndex);
    }

    if (path) {
      parsedPath.pathname = path;
    }
  }

  return parsedPath; // <---- returns {} at the homepage url because above logic does not add any data
}
```

After creating the router, the RR code looks for a matching route to render, but will not find one!

**/node_modules/@remix-run/router/router.ts**
```js
export function createRouter(init: RouterInit): Router {
  ...
  let initialMatches = matchRoutes( // <---------------- Call to matchRoutes() (below)
    dataRoutes,
    init.history.location,
    init.basename
  );
  let initialErrors: RouteData | null = null;

  if (initialMatches == null) { // <----------- initialMatches == null because did not match a basename path
    // If we do not match a user-provided-route, fall back to the root
    // to allow the error boundary to take over
    let error = getInternalRouterError(404, {
      pathname: init.history.location.pathname,
    });
    let { matches, route } = getShortCircuitMatches(dataRoutes);
    initialMatches = matches;
    initialErrors = { [route.id]: error }; // <------------ Error added to RouterState (below)
  }

  let initialized =
    !initialMatches.some((m) => m.route.loader) || init.hydrationData != null;

  let router: Router;
  let state: RouterState = {
    ...
    matches: initialMatches, // <-------------- NO MATCHING ROUTES
    initialized,
    ...
    errors: (init.hydrationData && init.hydrationData.errors) || initialErrors, // <----- ERROR
    fetchers: new Map(),
  };
```

**/node_modules/@remix-run/router/utils.ts**
```js
export function matchRoutes<
  RouteObjectType extends AgnosticRouteObject = AgnosticRouteObject
>(
  routes: RouteObjectType[],
  locationArg: Partial<Location> | string,
  basename = "/"
): AgnosticRouteMatch<string, RouteObjectType>[] | null {
  let location =
    typeof locationArg === "string" ? parsePath(locationArg) : locationArg;

  let pathname = stripBasename(location.pathname || "/", basename); // <------- stripBasename() returns null

  if (pathname == null) {
    return null; // <--------------- returns null because pathname is null (no matching route)
  }
  ...
}

export function stripBasename(
  pathname: string,
  basename: string
): string | null {
  if (basename === "/") return pathname;

  if (!pathname.toLowerCase().startsWith(basename.toLowerCase())) {
    return null; // <------- returns null because pathname == '/', therefore it does NOT start with the basename
  }
   ...
}
```

This app is currently deployed to Github Pages: https://allpro.github.io/pokemon-sample
However I was forced to use BrowserRouter to make it work. Therefore visiting this app will not show the problem described here. It should be easy to replicate though.

**Comment by timdorr** [comment]
`basename` is intended to be just the path part of the URL you're hosting it under, not the full URL. From the perspective of the page's DOM, the History API is origin-agnostic. 

However, you don't need basename at all in this case. The URLs generated with a hash router will be appended onto the page URL/path automatically. This would only be needed if you're putting the hash part of the URL under a sub-path always (e.g., `https://allpro.github.io/pokemon-sample#/my/base/name/porygon` with `basename: '/my/base/name'`)

**Comment by allpro** [comment]
@timdorr Thanks for the explanation. It's easy to confuse path-basename and hash-basename when changing routers. This is especially true because a 'basename' in a hash-path is very unusual - I've never seen such a thing in over 40 years! Therefore it's _not obvious_ that `basename` applies to the hash, even though it's reasonable in hindsight.

Because I was _dynamically switching_ between BrowserRouter when deployed locally and HashRouter when deployed publicly, the necessity of the configuration change was not obvious to me.  Currently I'm using BrowserRouter, which _requires_ a `basename` to work correctly. However switching to HashRouter, a different configuration is required. The natural assumption is that _all other things_ would remain the same when changing routers, but this is untrue.

I suggest adding a note in the documentation for `HashRouter`/`createHashRouter` saying that `basename` applies to the hash portion only, and not the entire pathname like BrowserRouter. A simple sentence like this would have saved me hours of confusion when I decided to change to HashRouter.
