### ISSUE TITLE
[Docs]: Document Path pattern syntax

### ISSUE THREAD

**Issue by CreativeTechGuy** [remix-run/react-router#9801]
### What is the new or updated feature that you are suggesting?

There's been a lot of new syntax added to paths which isn't documented all in one place. There should be a single source in the public doc site that contains every symbol that can be used, what it is used for, and examples for each.

It seems like [here](https://reactrouter.com/en/main/route/route#path) is where this is already started, but not complete. It references the use of `-` which seems to indicate optional segments. And doesn't document the new `?` for optional segments. I'm not sure what other secret features might be available or what advanced ways they might be used since I cannot find information about them aside from release notes.

### Why should this feature be included?

Visibility into the core feature of React Router. The path strings include a lot of special syntax which is unique but poorly documented which leads to word-of-mouth features and a lot of confusion.

**Comment by timdorr** [comment]
There is a section for this already: https://reactrouter.com/en/main/start/concepts#matching

However, we do need to add documentation for the optional param stuff. A PR would be appreciated!

**Comment by CreativeTechGuy** [comment]
@timdorr Thanks! The section you linked though has even less information than here: https://reactrouter.com/en/main/route/route#path. It is missing star segments and only talks about dynamic segments. And it doesn't explain what exactly is and isn't possible. (For example, I don't see where it says if something like `/user/uuid_:id` is valid or not.)

I'd like to see a [Backus-Naur form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) defining the grammar somewhere so it's clear everything that is possible. I'm sure it'll only get more and more complex over time as new features are added and it'll get harder to explain every possible case with just words.

I'm not sure I can submit that PR as I'd have to first reverse engineer the library to figure out what is possible. I wouldn't know if things should be possible but aren't just because no one has ever tried before.

**Comment by timdorr** [comment]
I disagree with BNF there, since that's a more descriptive document. It may make sense for the API page (which includes things like typedefs), but I think it's more complicated than a plain description of the options.

**Comment by brophdawg11** [comment]
> There should be a single source in the public doc site that contains every symbol that can be used, what it is used for, and examples for each.

I'm going to close this out now that optional segments have been documented since the [`path`](https://reactrouter.com/en/main/route/route#path) docs now document all types of path matching supported by react router.
