### ISSUE TITLE
[Bug]: React Router Homepage error

### ISSUE THREAD

**Issue by bobziroll** [remix-run/react-router#9804]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

Go to the homepage at https://reactrouter.com/en/main. If it loads correctly, try clicking the logo to go to the homepage again.
<img width="706" alt="Screenshot 2023-01-03 at 11 49 26 AM" src="https://user-images.githubusercontent.com/6244647/210423027-089833d8-aed9-4f7c-895f-0bc80aa9a3a8.png">
<img width="761" alt="Screenshot 2023-01-03 at 11 49 58 AM" src="https://user-images.githubusercontent.com/6244647/210423031-8671eba4-28a6-4945-a3c1-0078c54caf6d.png">

### Expected Behavior

Regular working homepage 🙂

### Actual Behavior

TypeError: Cannot read properties of null (reading 'toLocaleString')

**Comment by rsmelo92** [comment]
The only way to access it for now is on an anonymous tab for those in need

**Comment by bobziroll** [comment]
Just realized there's a separate Repo for the website, and someone [already posted the issue](https://github.com/remix-run/react-router-website/issues/27). Closing this for now.
