### ISSUE TITLE
[Docs]: SSR in >= 6.4? (Documentation outdated)

### ISSUE THREAD

**Issue by xriter** [remix-run/react-router#9825]
### What is the new or updated feature that you are suggesting?

Is or will it be possible to still Server Side Render in React Router >= 6.4?

The documentation seems to be outdated at this moment (https://reactrouter.com/en/main/guides/ssr).
The new RouterProvider/Router object does not seem to be compatible with the older 'StaticRouter'.

### Why should this feature be included?

Not all the features of Remix might be needed, but it would still be nice to do a simple SSR, like we could in version <= 6.3.

**Comment by B3nten** [comment]
Some guidence on this would be helpful!

**Comment by brophdawg11** [comment]
Yeah we need to get the docs updated for the new SSR APIs - but for now feel free to check out the source code in this [example](https://github.com/remix-run/react-router/tree/main/examples/ssr-data-router) using the new Data APIs.  The README there also looks slightly outdated as we renamed a few things.

**Comment by brophdawg11** [comment]
SSR docs are now updated for data routers: https://reactrouter.com/en/main/guides/ssr
