### ISSUE TITLE
[Bug]: objects returned by useMatches are incomplete, missing other route props like name etc...

### ISSUE THREAD

**Issue by BennyAlex** [remix-run/react-router#9836]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

useMatch() hook and look at the returned objects

### Expected Behavior

If I have a routes definition like 
{ name: 'first route', 
path: '/first'
...}
useMatches() should also return the name of the route.

This is very need if for example you want to write a dynamic breadcrumbs element, eg 

```
{matches.map(el => (
          <Link to={`/${el.path}`} key={el.key}>
              {el.name}
          </Link>
        )
    )
}
```

### Actual Behavior

Other props than
data,
handle,
id,
params,
pathname
are missing in the match object.

**Comment by timdorr** [comment]
You cannot add arbitrary keys to the route object. If you're using Typescript, this will not compile. You should use the `handle` property for this.

**Comment by BennyAlex** [comment]
Writing a handle for every route just to get its title in a generic breadcrumb component is really unsatisfing. 
Aren't there any better ways to archive such things?
