### ISSUE TITLE
[Bug]: 使用useNavigate创建的方法跳转方法跳转携带参数，参数中包含 跳转这个方法本身，导致跳转后刷新页面

### ISSUE THREAD

**Issue by 18323727253** [remix-run/react-router#9868]
### What version of React Router are you using?

"react-router-dom": "^6.4.5"

### Steps to Reproduce

[
![image](https://user-images.githubusercontent.com/98686121/211527513-2e3b1e8e-a3db-4d04-b378-c5917a8f5081.png)
](url)
[
![a2370a392714959add7cf021ea9d7ac](https://user-images.githubusercontent.com/98686121/211527699-3f72e0f6-8f6a-4ae1-a4a2-6478c2da329b.png)
](url)

### Expected Behavior

携带参数包含跳转函数本身为什么会导致跳转刷新

### Actual Behavior

携带参数包含跳转函数本身为什么会导致跳转刷新

**Comment by machour** [comment]
Hi @18323727253, please reopen the bug report in English, including your comments in the screenshot 🙏🏼
