### ISSUE TITLE
[Bug]: Code-Splitting doesn't work any more

### ISSUE THREAD

**Issue by jpink** [remix-run/react-router#9870]
### What version of React Router are you using?

6.6.2

### Steps to Reproduce

Implement code splitting as previous (v5) documentation says. New documentation say nothing about it even it's the biggest issue of today's SPA:s.

### Expected Behavior

Code is loaded asynchronously as in versions before Data API routers (<6.4).
Documentation should have instructions, example or something how to do it properly.

### Actual Behavior

I have google the whole internet and I only found outdated documentation and hacks.
Are you permanently dropped the lazy loading support?!? Or should we stick with old branch?

**Comment by david-crespo** [comment]
This works for me with Vite. Curious what bundler you're using?

```ts
const MyPage = React.lazy(() => import('./pages/MyPage'))

// ...

<Route
  path="my-page"
  element={
    <Suspense fallback={null}>
      <MyPage />
    </Suspense>
  }
/>
```

**Comment by jpink** [comment]
@david-crespo you use old router. Try to [pick new data router](https://reactrouter.com/en/main/routers/picking-a-router).

**Comment by david-crespo** [comment]
> @david-crespo you use old router. Try to [pick new data router](https://reactrouter.com/en/main/routers/picking-a-router).

This is with the new data router. I left out my `loader` prop for simplicity.
