### ISSUE TITLE
[Bug]: Link "to" property should allow number in typescript

### ISSUE THREAD

**Issue by ceopaludetto** [remix-run/react-router#9872]
### What version of React Router are you using?

6.4

### Steps to Reproduce

In version 6 we can go back using -1 in navigate function. After some investigation I figured out that Link component allows -1 too, but typescript give us an error:

https://stackblitz.com/edit/github-hstusm?file=src/App.tsx

### Expected Behavior

Link component should allow -1 in "to" prop

### Actual Behavior

Link component show us an error

**Comment by timdorr** [comment]
We can't because we can't generate a valid `href`: https://github.com/remix-run/react-router/issues/8123#issuecomment-941896886
