### ISSUE TITLE
a way to update the query w/o doing a full transition

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#99]
One of the most common use-cases for query params is to build up a set of them for something like a product catalog or flight/hotel search UI.  The user interacts with some form controls and the query keeps updating.

We should should optimize for this path with something like `Router.setQuery(query)`.  This would update the props on all active routes but not do a transition so that `componentDidMount` and friends don't get called.

This should probably work like `this.setState` where you can just update bits as you know them. If you want to remove an item, set it to `null`.

**Comment by seethroughtrees** [comment]
I love the idea of setQuery(), wondering if anything came from that?  When I use this.replaceWith(), if I update the query params, the page refreshes.  If I remove the query object, it doesn't.

I'm looking for a way to change the query params without refreshing the page...  

Or am I maybe missing something? 

```
// page refreshes automatically
this.replaceWith('leverSub', {lever: this.props.leverTitle}, {show: activeFilters});

// no page refresh
this.replaceWith('leverSub', {lever: this.props.leverTitle});
```

Thanks in advance.
