### ISSUE TITLE
[Bug]: Tutorial bug: formData.entries is not a function

### ISSUE THREAD

**Issue by josef5** [remix-run/react-router#9905]
### What version of React Router are you using?

6.6.2

### Steps to Reproduce

Follow the tutorial up to Creating Contacts

Click on the "new" button in the app to create a new contact

### Expected Behavior

A new contact is created

### Actual Behavior

An error is logged to the console

> Uncaught (in promise) TypeError: formData.entries is not a function or its return value is not iterable
    at convertFormDataToSearchParams (router.ts:2919:37)
    at createClientSideRequest (router.ts:2908:11)
    at startNavigation (router.ts:959:19)
    at Object.navigate (router.ts:859:18)
    at index.tsx:917:16
    at submitHandler (index.tsx:663:7)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
> 

`formData.entries` is an array for some reason and not the function the Form component is expecting

**Comment by timdorr** [comment]
Can you reproduce this in CodeSandbox or StackBlitz?

**Comment by josef5** [comment]
Using the same files on CodeSandbox but running without Vite, the bug does not occur. 

Could this be a Vite issue?

**Comment by timdorr** [comment]
This doesn't seem like a React Router bug. If you can create a reproduction in another tool, we can take a look, but I'm going to close this for now.

**Comment by nayakunin** [comment]
I believe I know what might be causing this issue. @josef5 check if you are using an extension called Mokku. It is known to somehow modify the FormData object. I encountered exactly the same issue as you, but after turning it off everything is working fine.

**Comment by josef5** [comment]
Wow, thats a **hole-in-one** @nayakunin !!!
I did have this extension and disabling it fixes this. Amazing! I was completely baffled by this, thanks!!!

**Comment by darshanhexo** [comment]
@nayakunin Thanks Nikita that resolved it
