### ISSUE TITLE
[Bug]: useSearchParams changing a '+' to an empty space

### ISSUE THREAD

**Issue by jennikate** [remix-run/react-router#9908]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

When using useSearchParams to get a portion of a query string that has a '+' in it, it is returning a space instead of the '+'

e.g. `/activate-account?email=myemail+anotherbit@gmail.com&token=123`

```
const [searchParams] = useSearchParams();
const emailAddress = searchParams.get('email');
```

### Expected Behavior

return `myemail+anotherbit@gmail.com`

### Actual Behavior

returns `myemail anotherbit@gmail.com`

**Comment by machour** [comment]
A `+` in the url means a space. 
You should properly encode your url (+ => %20)

`/activate-account?email=myemail+%20anotherbit@gmail.com&token=123`

**Comment by salehi777** [comment]
Is there a way to get what is exactly in query string? (with +)
