### ISSUE TITLE
[Bug]: useSearchParams set function does not retain identity

### ISSUE THREAD

**Issue by pgsandstrom** [remix-run/react-router#9912]
### What version of React Router are you using?

6.6.2

### Steps to Reproduce

Set up this code and make the search string change:

```
  const [_searchparams, setSearchParams] = useSearchParams()
  const firstSetFunction = useRef(setSearchParams)
  if (firstSetFunction.current !== setSearchParams) {
    console.log("oh no, set function changed!")
  }
```

### Expected Behavior

Since the documentation emphazies the similarities between useSearchParams and useState I expected the set-function to retain its identity, just as it does in useState.

### Actual Behavior

It does not retain its identity.

**Comment by pgsandstrom** [comment]
I have been looking at doing my first PR to react-router. If people agrees that this should be fixed, I would love to make a PR for it.

**Comment by timdorr** [comment]
https://github.com/remix-run/react-router/issues/9304#issuecomment-1251706232
