### ISSUE TITLE
[Bug]: navigate() is a no-op when called on first render

### ISSUE THREAD

**Issue by TrevorBurnham** [remix-run/react-router#9921]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

Create this component and render it at the path `/old`:

```
const OldToNew() {
  const navigate = useNavigate();
  useEffect(() => {
    navigate('/new', {replace: true});
  }, []);
}
```

Then load `http://localhost/old` in your browser.

### Expected Behavior

When the component renders, it should perform a URL replacement, from `/old` to `/new`.

### Actual Behavior

The `navigate()` call is a no-op. The page URL doesn't change and nothing is emitted in the console.

If the `navigate()` call is deferred at all, then it works. For example:

```
const OldToNew() {
  const navigate = useNavigate();
  const [hasRendered, setHasRendered] = React.useState(false);

  useEffect(() => {
    if (!hasRendered) return;
    navigate('/new', {replace: true});
  }, [hasRendered]);

  useEffect(() => {
    setHasRendered(true);
  }, []);
}
```

This is with React/ReactDOM 16.14.0.

---

For folks wondering what the use case is: I have some tab navigation where the URL indicates the selected tab. Some tabs are disabled and cannot be selected. If a user follows a link that indicates that a disabled tab is selected, then I want the component that renders the tabs to replace the URL to indicate the fallback tab that's selected instead. If there's a better way of handling that case, let me know.

**Comment by timdorr** [comment]
Can you create a reproduction in CodeSandbox or StackBlitz? That will make investigation and testing fix _much_ easier (and therefore more likely to happen!)

**Comment by TrevorBurnham** [comment]
Hmm… curiously I'm [unable to replicate](https://codesandbox.io/s/sharp-mclean-cdhl08?file=/src/App.js) in a CodeSandbox, even though I'm still seeing this behavior in my application.

There must be some other factor involved, perhaps even something outside of react-router. I'll close this ticket until I can pin this down more.
