### ISSUE TITLE
[Bug]: Router v6.7.0 'useBlocker must be used within a data router' error when running tests

### ISSUE THREAD

**Issue by vladutclp** [remix-run/react-router#9939]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

1. Call `unstable_useBlocker` inside a component.
2. Render that component inside a test file

### Expected Behavior

Tests should work as expected.

### Actual Behavior

Tests fail with this error: 
![image](https://user-images.githubusercontent.com/22237268/213394529-3bef2a71-293a-4c8b-8da9-b909208d68e9.png)

Here is a reproduction repo that uses the example provided in https://github.com/remix-run/react-router/tree/dev/examples/navigation-blocking

**Reporoduction repo**: https://github.com/vladutclp/react-router-blocker-repro

**Comment by adagit94** [comment]
Hi, I would like to ask if use of useBlocker will be available in foreseeable future inside of router components (HashRouter and the like). In our case architecture changes needed for data router to be usable arent possible in easy way. Why its not supported for standard route components also?

**Comment by MarttiR** [comment]
Here's a _dirty,_ ___dirty___ workaround that makes `useBlocker` do its job correctly under `HashRouter`.

```js
useBlocker(() => {
  if (isLocked) {
    if (!window.confirm(message)) {
      throw new Error('Navigation blocked');
    }
  }
  return false;
});
```

**Comment by darckex** [comment]
> Here's a _dirty,_ _**dirty**_ workaround that makes `useBlocker` do its job correctly under `HashRouter`.
> 
> ```js
> const location = window.location.href;
> 
> useBlocker(() => {
>   if (isLocked) {
>     if (!window.confirm(message)) {
>       // Restore current path.
>       window.history.pushState(null, '', location);
>       // Prevent routing fn from running to completion.
>       throw new Error('Navigation blocked');
>     }
>   }
>   return false;
> });
> ```
this doesn't seem to work, the error `Error: useBlocker must be used within a data router.` is still present and the app wont load

**Comment by fabianboerner** [comment]
Sad this was closed, will the browser router be deprecated or is it already?
