### ISSUE TITLE
[Bug]: Router v6.7.0 unable to navigate using <HashRouter /> and location.href

### ISSUE THREAD

**Issue by chrisd1999** [remix-run/react-router#9940]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

1. Pick `<HashRouter />` router to manage your routes.
2. Dynamically modify `window.location.href` instead of using `<Link />` to navigate.

```js
const handleClick = (path: string) => {
  window.location.href = `#/${path}`;
};

return (
  <HashRouter>
    <button onClick={() => handleClick("link1")}>Link 1</button>
    <button onClick={() => handleClick("link2")}>Link 2</button>
    <Routes>
      <Route path="/link1" element={<div>Link1</div>} />
      <Route path="/link2" element={<div>Link2</div>} />
    </Routes>
  </HashRouter>
);
  ```

### Expected Behavior

After upgrade to react v6.7.0 you can still modify `window.location.href` and the routing will be handled.

### Actual Behavior

After upgrading from v6.6.2 to v6.7.0, unable to navigate using `window.location.href` and `<HashRouter />`

**Comment by timdorr** [comment]
There is a warning message in your console about this. @brophdawg11 is improving this message in #9941. 

I would continue the discussion over there if the message isn't clear enough, but it won't be possible to remove the warning. We want to ensure there aren't silent failures in production builds from incorrect paths being supplied to the router.

**Comment by brophdawg11** [comment]
Yeah this is the same explanation as https://github.com/remix-run/remix/issues/5147#issuecomment-1397184463.  You need to do client-side navigation in react router using router methods, not external `window.location` /`history.pushState` modifications/calls.  Changing the hash is a navigation and should be done via `<Link to="#hash">` or with `useNavigate`

**Comment by chrisd1999** [comment]
Great, thanks! I did run into silent failure in production after the latest upgrade, which lead me to believe there was an issue introduced with latest release. @brophdawg11, as currently we are migrating to fully use react-router for routing, we had to use `window.location.href` to do client-side navigation, as router methods were unavailable. Does the only solution would be to use earlier `react-router-dom` versions until the migration is complete?

**Comment by chrisd1999** [comment]
Thanks for great suggestions! As the previous behavior was resolved with latest release bug fix, in instance, where it would be required to navigate outside of `react-router`, would it be sufficient to have an event listener on `hashchange` and triggering `navigate`? For example,
```js
const navigate = useNavigate();
const stableNavigate = useRef(navigate);

useEffect(() => {
  stableNavigate.current = navigate;
});

useEffect(() => {
  const handleHashChange = () => {
    const [,path] = window.location.hash.split("#/");
    stableNavigate.current(path);
  };
  
  window.addEventListener("hashchange", handleHashChange);
  
  return () => {
    window.removeEventListener("hashchange", handleHashChange);
  }
}, []);
```

**Comment by brophdawg11** [comment]
yeah - if you have no control over the source of the hash change, you can probably do something like that.  You may want to do `navigate(path, { replace: true })` there as well to ensure you don't end up with duplicate entries in the history stack as well.
