### ISSUE TITLE
[Bug]: duplicated react tree issue after history change using `<Navigate />`

### ISSUE THREAD

**Issue by sanex3339** [remix-run/react-router#9955]
### What version of React Router are you using?

6.7.0/5.3.4

### Steps to Reproduce

- Open https://codesandbox.io/s/hydration-playground-forked-cdyvy5?file=/index.js:1555-1567
- In the `url` field add a second slash at the end, for example `https://cdyvy5.csb.app//`
- After page is loaded and `hydrateRoot` is called, the `<UrlSanitizer>` component is called with `<Navigate />` element. It sanitizes the URL but after the redirect, we have 2 copies of the children in the DOM. I believe one copy is from SSR render, and second copy is Client render. And no `hydration` errors

### Expected Behavior

We should not get duplicated HTML after `<Navigate />` redirect

### Actual Behavior

We have 2 copies of the children in the DOM

**Comment by timdorr** [comment]
You shouldn't be rendering `<Navigate />` on the server, as it uses an effect that will not be fired in that context. I'm not sure why this results in duplicate DOM elements for this example, but that seems tangential to the actual problem. 

@mjackson did a write-up on the issue here: https://gist.github.com/mjackson/b5748add2795ce7448a366ae8f8ae3bb

Since then, we've added the data routers and more recently a static data router for SSR. It's recommended you use those, as they are what Remix uses and it handles redirects server-side.

**Comment by sanex3339** [comment]
@timdorr we have the same issue in `5.3.*` with `Redirect`

**Comment by sanex3339** [comment]
@timdorr i simplified example. 
The problem has nothing related to the SSR:
https://codesandbox.io/s/hydration-playground-forked-weyt4r?file=/index.js

**Comment by timdorr** [comment]
This doesn't sound like a bug in React Router. You're getting in two different versions of our library with very different implementation details. This is more likely a React bug or misuse of their APIs.

For instance, if I switch to the `useNavigate` form, I do not get duplication: 

```js
const UrlSanitizer = ({ children }) => {
  const { pathname, search, hash } = useLocation();
  const navigate = useNavigate()

  useEffect(() => {
    if (pathname.match(URL_REWRITE_REGEXP)) {
      const cleanPath = pathname.replace(URL_REWRITE_REGEXP, "/");
  
      return navigate(`${cleanPath}${search}${hash}`);
    }
  })

  return children;
};
```

**Comment by sanex3339** [comment]
@timdorr yeah, this is strange.

Thank you for your solution, it works for 5.3.4 as well:

```
const UrlSanitizer = ({ children }: Props) => {
  const { pathname, search, hash } = useLocation()

  useLayoutEffect(() => {
    if (pathname.match(URL_REWRITE_REGEXP)) {
      const cleanPath = pathname.replace(URL_REWRITE_REGEXP, '/')

      return history.replace(`${cleanPath}${search}${hash}`)
    }
  })

  return children
}
```
