### ISSUE TITLE
[Bug]: `useLoaderData<typeof loader>()` Does not return a type like Remix

### ISSUE THREAD

**Issue by renomureza** [remix-run/react-router#9956]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

Are there any plans to add a feature that will allow `useLoaderData` to return the appropriate type such as remix?

The code below illustrates what I mean, it will be a bit of a hassle if we use the `defer` function in the `loader`.

```tsx
export async function loader({ params, request, context }: LoaderFunctionArgs) {
  const products = [{ id: 1, name: "x" }];
  return { data: products };
}

export default function Products() {

  const data = useLoaderData<typeof loader>(); // unknown

  const data = useLoaderData() as Awaited<ReturnType<typeof loader>>; // temporary solution

  return <></>
}
```

Related: https://github.com/remix-run/react-router/discussions/9792

### Expected Behavior

When `useLoaderData<typeof loader>()` should return the type of value returned by the loader.

### Actual Behavior

When `useLoaderData<typeof loader>()` return type `unknown`.

**Comment by machour** [comment]
There's already a proposal for this: https://github.com/remix-run/react-router/discussions/9854
