### ISSUE TITLE
[Docs]: Path to https://reactrouter.com/en/main/hooks/use-params

### ISSUE THREAD

**Issue by lorenzojkrl** [remix-run/react-router#9959]
### Describe what's incorrect/missing in the documentation

On VSCode, when using useParams() incorrectly, we get an error.
The error suggests to @see — https://reactrouter.com/docs/en/v6/hooks/use-params
However, that page errors to 404

Is the correct page https://reactrouter.com/en/main/hooks/use-params?

![image](https://user-images.githubusercontent.com/18583152/213981341-4701362c-7b62-47f0-8852-3112371f99ce.png)

**Comment by timdorr** [comment]
This was fixed a while ago: https://github.com/remix-run/react-router/commit/37f2d36948ed1e0751751acf62cab391b22c0c9c
