### ISSUE TITLE
[Bug]: useLocation seems to no longer update after history.replace starting from @remix-run/router@1.3.0

### ISSUE THREAD

**Issue by karfau** [remix-run/react-router#9960]
### What version of React Router are you using?

6.6.1,6.6.2,6.7.0

### Steps to Reproduce

0. install one of the listed versions for react router and `@remix-run/router@1.3.0`
1. Create a component that is always rendered (independent of a route) which uses `useLocation`
2. inside some code that loaded lazily initially use `history.replace` to handle the initial navigation to a route that is not matching one of the routes mapped with react-router.
3. observe that the component created in step 2 is not rerendering after the route changed

I will come up with a more detailed reproduction once it's clear that it's an issue and not expected behavior.

### Expected Behavior

The component using `useLocation` is expected to re-render even when other code triggers a route change to a route that is not registered as part of react-router.

### Actual Behavior

1. The component using `useLocation` dosn't re-render even when other code triggers a route change to a route that is not registered as part of react-router.

2. There is a new message in the console (independent of production or development build):
![image](https://user-images.githubusercontent.com/135657/214068943-c591f4a9-737c-4275-9732-9e2582a0a233.png)

3. When downgrading to `@remix-run/router@1.2.1` everything works as expected

**Comment by timdorr** [comment]
This message has been updated here and will be in the next release: #9941

Because of some internal changes, particularly to support things like useBlocker/usePrompt and the data routers, a warning was added to prevent production bugs with external navigation. You should use `useNaviate` to do this navigation, not use the History API directly. You'll end up with duplicate items on your history stack otherwise.

**Comment by karfau** [comment]
In our case we are in a micro-frontend where we do not controll all apllications and not all applications are using react. So it is not possible to impose the usave of react-router on every frontend.

I would consider this a breaking change, but it is maybe also not because it is not the code of this library that it being called.

Any chance to make this change something we can opt into or out of?

Otherwise we will have to stop updating this library.

**Comment by karfau** [comment]
Found the other related comments in https://github.com/remix-run/react-router/issues/9940

**Comment by brophdawg11** [comment]
yeah if you have scenarios where something external needs to navigate outside react router, your react router app will need to listen for those navigations and proxy them through a react router navigation with `replace:true` or something to re-sync up react-router with the URL.
