### ISSUE TITLE
[Bug]: Loader API doesn't fire when dynamically imported into a router element

### ISSUE THREAD

**Issue by mgmarlow** [remix-run/react-router#9990]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

Here's a [codesandbox with the minimum steps to reproduce](https://codesandbox.io/s/wonderful-violet-cqwc9x?file=/src/routes.js).

## Summarized
`loader` functions aren't called when they're included in a dynamically-imported `Routes` component.

1. Export a bundle of routes as a component using `useRoutes`.
2. Dynamically import this component in the root router and provide as an `element` for a particular route.
3. Observe that `useRouteLoaderData` returns `undefined` in one of my components, even though the parent route renders properly. The `loader` function is not called.

## Detailed walkthrough

I'm dynamically importing a collection of routes from somewhere in my application. Since I want all components for this collection of routes chunked into the same bundle, I need to export those components and routes from a component element. This follows the pattern demonstrated in [bulletproof react](https://github.com/alan2207/bulletproof-react/blob/master/src/features/discussions/routes/index.tsx).

Here are the routes that I'm bundling together into a single chunk:

```js
const PokemonDetailContainer = () => {
  const pokemon = useRouteLoaderData("pokemon");
  // ...
};

const routes = [
  {
    path: "",
    children: [
      {
        id: "pokemon",
        path: ":pokemonId",
        element: <PokemonRoot />,
        loader: ({ params }) =>
          fetch(`https://pokeapi.co/api/v2/pokemon/${params.pokemonId}`),
        errorElement: <FetchFailed />,
        children: [
          {
            index: true,
            element: <PokemonDetailContainer />
          }
        ]
      }
    ]
  }
];

const PokemonRoutes = () => {
  const element = useRoutes(routes);

  return <>{element}</>;
};

export default PokemonRoutes;
```

In particular, note the use of a `loader` function that fetches the data I want to use in the child routes. I've tagged the parent with an explicit `id: "pokemon"` so that I can use the `useRouteLoaderData` hook.

Here you can see me dynamically import the component as an `element` in my root router:

```js
const PokemonRoutes = loadable(() => import("./pokemon.routes"));

const routes = [
  {
    path: "/",
    children: [
      { index: true, element: <Home /> },
      {
        path: "/pokemon/*",
        element: <PokemonRoutes />
      }
    ]
  }
];
```

With this setup, my application is chunked into two bundles (a) `index.js` and (b) `pokemon-routes.js`.

However, the `useRouteLoaderData("pokemon")` call always returns `undefined`, and the `loader` function is not called.

### Expected Behavior

`useRouteLoaderData("pokemon")` returns the pokemon fetched by the parent loader function.

### Actual Behavior

`useRouteLoaderData("pokemon")` returns `undefined`.

> The only data available is the routes that are currently rendered. If you ask for data from a route that is not currently rendered, the hook will return undefined.

In my example, the `PokemonRoot` template is rendered properly, in addition to correctly passing through the child content into the `PokemonRoot` `Outlet`.

**Comment by timdorr** [comment]
`useRoutes` is a non-data router API. It's equivalent to `BrowserRouter`. It does not participate in data loading, so it doesn't make the loader data available to its routes.

**Comment by brophdawg11** [comment]
Descendant `<Routes>`do not participate in data loading because they aren't known until during the render.  However the data loading APIs are decoupled and happen before rendering, so there's no way to execute loaders that are not yet known to the router.

This is documented on the `<Routes>` docs [here](https://reactrouter.com/en/main/components/routes) but it's probably worth the same callout on `useRoutes`.  

There is a Proposal to consider a way to support this if you like to upvote and keep an eye on that: https://github.com/remix-run/react-router/discussions/9855

**Comment by brophdawg11** [comment]
Hah, jinx @timdorr - snuck in a response while I was typing on my phone!

**Comment by mgmarlow** [comment]
Great, thank you for the confirmation and especially the link to that discussion. I was searching through the docs to try and confirm my suspicions around the static requirement of routes but I was a little unclear.

Given this, it seems like the loader APIs cannot be used when lazy-loading with many components together in the same chunk, since the routing information isn't available until he application runtime via Routes.
