### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by Amedeo91** [remix-run/react-router#9992]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

Install router 6.8.0 and it breaks on loading with the exception in the screenshot.

![image](https://user-images.githubusercontent.com/8645312/214999429-521a78b7-00e0-4022-bdbc-e4420713183b.png)

Falling back to 6.7.0 solves the issue. It seems that the variable pathname is not defined, causing the js to break.

### Expected Behavior

The code does not break because of a non defined variable.

### Actual Behavior

![image](https://user-images.githubusercontent.com/8645312/214999429-521a78b7-00e0-4022-bdbc-e4420713183b.png)

**Comment by timdorr** [comment]
Can you show the code that calls this? Showing a stack trace from minified code doesn't give us much to work with.

**Comment by rpellerin** [comment]
@Amedeo91 you must always pass a `to` prop to a `<Link />`. The same error happened to me. Found an occurrence in the codebase of a `Link` with no `to` prop.

**Comment by Amedeo91** [comment]
@rpellerin thank you for the tip. I actually checked for that in the code, but I found none!

@timdorr I would love you to share the code, however, I have no idea where it is failing because the error is coming from react-dom and it appears after trying to bump the library version with no code changes on our side. What else could help you to provide us a solution?

**Comment by Amedeo91** [comment]
After a closer check, I noticed that we do not use the `<Link />` object, but we use the `<NavLink />` in many places

**Comment by timdorr** [comment]
That isn't the React Router documentation, it's unofficial docs of version 2.x. The official and updated docs are here: https://reactrouter.com/en/main/components/link There is a type definition at the top you can expand. 

If you were using the API in an undocumented way, it is not considered a breaking change for that functionality to go away or stop working.
