### ISSUE TITLE
[Bug]: npm ERR! notarget No matching version found for @remix-run/router@1.3.1.

### ISSUE THREAD

**Issue by dzienisz** [remix-run/react-router#9993]
### What version of React Router are you using?

none

### Steps to Reproduce

npm i

### Expected Behavior

all packeges get installed

### Actual Behavior

 npm i                  
(Use `node --trace-warnings ...` to show where the warning was created)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @remix-run/router@1.3.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by timdorr** [comment]
This isn't a bug with React Router.
