### ISSUE TITLE
[Bug]: Using the browser back button console logs a warning

### ISSUE THREAD

**Issue by matijs** [remix-run/react-router#9998]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

Minimal test case at https://stackblitz.com/edit/react-ts-gphlmg?file=App.tsx

1. Navigate to ‘foo’ or ‘bar‘ using the link on the page
1. Use browser back button to navigate back to the ‘index’
1. Use the browser forward button to navigate to ‘foo’ or ‘bar’ again

NB. Using only the links on the page works as expected without any warnings in the console.

### Expected Behavior

There should (probably?) be no warnings in the console in this simple use case. Nothing is actively blocked and no navigation outside of the router happens (unless using the browser's back/forward button _is_ considered navigation outside of the router).

### Actual Behavior

The following warning is logged in the console:

> You are trying to use a blocker on a POP navigation to a location that was not created by @remix-run/router. This will fail silently in production. This can happen if you are navigating outside the router via `window.history.pushState`/`window.location.hash` instead of using router navigation APIs.  This can also happen if you are using createHashRouter and the user manually changes the URL.

**Comment by brophdawg11** [comment]
Thanks for the report!  Pushed a fix for this in the above PR 👍

**Comment by brophdawg11** [comment]
This is fixed in `6.8.1-pre.0` if you want to give that spin to confirm.  If all goes well we should have the stable release out tomorrow or early next week.

**Comment by matijs** [comment]
> This is fixed in `6.8.1-pre.0` if you want to give that spin to confirm. If all goes well we should have the stable release out tomorrow or early next week.

Confirmed! No more warnings in the console when navigating forward/backward using the browser buttons.

Looking forward to the patch and thanks!

**Comment by brophdawg11** [comment]
This is now released in `6.8.1`
